### ISSUE TITLE
Autofill not working for extension on Edge canary Android

### ISSUE THREAD

**Issue by elias123tre** [bitwarden/clients#8666] opened 2024-04-10 12:50 UTC
### Steps To Reproduce

1. Download Microsoft Edge canary on Android (latest from play store, I've tested multiple versions)
2. [Enable developer tools and install extension by id](https://www.reddit.com/r/MicrosoftEdge/comments/1bp3yts/how_to_install_any_extension_on_microsoft_edge/): Bitwarden has id `jbkfoedolllekgbhcbcoahefnbanhhlh`
3. Log in to your bitwarden account from extensions menu
4. Go to a site where you have a saved password and focus the input field

### Expected Result

The accounts for the website should show in the autofill panel

### Actual Result

The autofill menu from the browser shows `No items to show` even though the account exists and can be autofilled from the extension menu

### Screenshots or Videos

![Screenshot_20240410_143124](https://github.com/bitwarden/clients/assets/18127101/6534b391-e3fc-4164-98de-47bd1016cfff)
![Screenshot_20240410_143140](https://github.com/bitwarden/clients/assets/18127101/1f8d4975-22cb-40fe-8873-3240388e5630)
![Screenshot_20240410_143150](https://github.com/bitwarden/clients/assets/18127101/a274bf3e-5702-4648-a742-a1f8e3ada944)

### Additional Context

I get that this is a low priority as it is for Edge canary on Android but it will reach stable eventually. It would also still be worth figuring out if this is an upstream issue from Edge or if it is regarding the Bitwarden extension

### Operating System

Android

### Operating System Version

Android 14

### Web Browser

Microsoft Edge

### Browser Version

Edge Canary 125.0.2512.0

### Build Version

2024.3.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment] 2024-04-10 14:21
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by micahblut** [comment] 2024-04-11 18:14
@elias123tre thanks for reporting this - I am going to close this issue since the Bitwarden browser extension is not officially supported on mobile browsers, where we instead recommend you use our mobile app. However, it is helpful to note that there is interest in this use-case.

**Closed by micahblut** 2024-04-11 18:14 UTC
Labels: bug, browser

**Comment by elias123tre** [comment] 2024-04-11 20:22
> @elias123tre thanks for reporting this - I am going to close this issue since the Bitwarden browser extension is not officially supported on mobile browsers, where we instead recommend you use our mobile app. However, it is helpful to note that there is interest in this use-case.

Thanks for the response! I understand completely, it is also only on the edge canary channel for now. But I have tried the Bitwarden extension for Firefox on Android and it seems to be better supported. The reason I want it working is that the Bitwarden app doesn't seem to show the autofill button for usernames/emails in the browser (even with accessibility permissions), only when entering a password. Which is a problem fro multi-stage logins. However I will see if an issue with this exists or open a new one.

**Comment by elias123tre** [comment] 2024-04-15 10:12
For future reference: This has been resolved for me by itself in Edge Canary 125.0.2518.0

**Comment by contentfree** [comment] 2024-08-09 16:15
Before opening a new issue, I wanted to comment that I'm experiencing this exact issue (options in form field for auto-fill shows "No items" but going to the context menu for Bitwarden, or using the extension's button, shows the valid available matching items) in Chrome v127 on macOS with extension v2024.7.1. 

Since it's the same behavior, would the Bitwarden team prefer to use this issue or have a new one created? (/cc @Neonwarden)
