### ISSUE TITLE
Autofill isn't working for a specific site

### ISSUE THREAD

**Issue by cscharf** [bitwarden/clients#1621] opened 2021-02-18 21:44 UTC
## Describe the Bug

We are aware of many sites' login forms, payment gateways, identity forms, etc. where the Bitwarden browser extension either on a single platform/browser or multiple will not autofill information. This is something the Bitwarden team is actively working on but need your help as a community and active Bitwarden users!

## Expected Result

When you have autofill configured and get to a page where you have saved credentials within Bitwarden, and your browser extension is unlocked, the credentials should be automatically populated. Otherwise, if you have saved information and use a manual action or command to autofill credentials, identity information, card information, etc.; it should properly populate the form.

## Actual Result

This works most of the time, but not always and it can depend on _many, many_ factors. Some sites simply don't work, some don't work consistently and others who knows. This is what we're aiming to fix!

## Call to Action

Below is a link to a Google Form that we have created for capturing information that will help us track down all of these pages and forms where Bitwarden has failed to autofill your information. You may submit as many as you like, just please help us help you and the community by providing meaningful information and only those sites/pages where it legitimately doesn't work.

[Report autofill failure](https://forms.gle/yYVQkepxxLKZ3kR6A)
[Report autofill failure on **Mobile**](https://github.com/bitwarden/mobile/issues/1389)

If you've been sent to this issue because another issue you had open was closed as a duplicate, thank you for taking the time to submit the issue to us, however we truly need to track this under a single item in aggregate fashion so we can manage it holistically and ensure we're taking broad measures that will improve this behavior with the maximum benefit to all. Please consider using the linked form above to submit the prior sites you had reported in the issue closed.

**Comment by setyb** [comment] 2021-02-20 11:41
I'm sorry, I ***don't use Google***, nor do I recommend any of their products to others.  In fact, Google-run host names as well as all known Google IP addresses are completely blocked here.  ***Life is better without Google™.***

I'm happy to continue to contribute via any non-Google and non-Facebook open-source product.

**Comment by cscharf** [comment] 2021-02-20 12:05
> I'm happy to continue to contribute via any non-Google and non-Facebook open-source product.

Understood @setyb , please feel free to respond in this thread; the form simply helps us collect and aggregate patterns (and works still with every kind of blocker on); however I understand your reluctance.

**Comment by skube** [comment] 2021-02-20 16:33
As a recent LP refugee, I find the term _Autofill_ a little ambiguous. Does it mean:

- Right-click input and select BitWarden > Auto-fill > Select login ?
- Or, click extension and select login ?
- Or, using the keyboard shortcut ?
- Or, Auto-fill on Page Load (which is the _most_ term-accurate IMHO)

I understand from the [Help page](https://bitwarden.com/help/article/auto-fill-browser/) it means all of the above, it's just if you are tracking and collating issues, shouldn't you differentiate the various modes a little better?

Case in point, I created #1624 which _only_ doesn't work if you use the keyboard shortcut.

**Comment by eliykat** [comment] 2021-02-21 20:14
@skube Good question. By "auto-fill", we mean auto-filling credentials by any method, including all those you list. Generally if one method won't work none of them will, but if the problem is with a particular method, you can note it in the Additional Info section of the form.

Also, we're trying to record problems caused by specific websites. So if you're experiencing a problem for all websites, it's more likely to be an issue with your install or configuration (as in your report), which is out of scope for this issue.

**Comment by Pulsar** [comment] 2021-02-26 14:54
Hello @cscharf,
As
* There are many websites that deviate a lot from a more standard way of naming input fields by "user" and "password"
* Collecting is highly a continuous process and would probably never end as sites change and new pop up every day
* Most probable, users giving feedback to this thread are probably either developers or IT professionals.

I suggest to create a simple feature that gives the user the ability to determine custom selector for user and password if it does not function properly. Also a small option to share the configuration would be nice. Example data shared:
```json
{
  "url": "exmaple.com/login",
  "userSelector": "#user",
  "passwordSelector": ".credentials.password[0]"
}
```
Each then shared custom selector could be downloaded by the other users.

Also a right click to element and then, **bitwarden > set as user input**, **bitwarden > set as password input** would be a solution.
Note: only user and password selector should be given by the user, the link should be automatically collected.

(To All: Show your support if you agree with this solution)

**Comment by cscharf** [comment] 2021-02-26 16:25
That's not a bad idea @Pulsar , however this can be accomplished today a bit easier by using [custom fields](https://bitwarden.com/help/article/custom-fields/) and just putting your username and/or password in a custom field (which can also be a hidden type) and using the matching rules for naming accordingly which alleviates some of the autofill issues with sites that have non-standard or odd naming schemes for those fields (or any fields for that matter).

As far as the ability for the community to be able to contribute these 1-off odd mappings in an easy way through the Bitwarden extension, that may certainly be something to look into as that allows economies of scale and a super easy way for a lot of people to contribute. That of course would have to be tempered with hardening and proper vetting of those to ensure malicious code isn't injected or other bad behaviors (manual review process, PRs, etc.). Will give this some thought and put a card on our backlog as a placeholder for it.

**Comment by EDIflyer** [comment] 2021-02-27 13:55
Interesting idea, @Pulsar - I remember LastPass did this for mapping saved website logins to Android apps when using it on the mobile, which was quite handy.  @cscharf perhaps that might be worth considering too?  I filed #1625 before I'd realised this thread and the Google Form exists - is there enough info in my previous bug to use or do you want me to complete the form too? (will bookmark it for the future!)

**Comment by cscharf** [comment] 2021-03-01 15:00
> is there enough info in my previous bug to use or do you want me to complete the form too? (will bookmark it for the future!)

@EDIflyer, if you're willing, submitting via the form would be great, otherwise someone on the team will backfill. Thanks!

**Comment by JanPokorny** [comment] 2021-03-02 21:57
I found a payment gate where card info auto-fill fails (or, rather, it fails the first time but works the second time), detailed at #1653. I was directed to this issue, but it seems that the form is specifically for log-ins. It asks for a login page URL... but payment gates don't work that way, you need to go to an e-shop that uses the gate and actually try to pay for something to see the gate.

So, what is the procedure for reporting payment gates where the card info autofill fails?

**Comment by cscharf** [comment] 2021-03-02 22:25
Hi @JanPokorny , I've updated the description and form to be more inclusive of all autofill, we did intend that but for whatever reason when I quickly tossed everything together I just had credentials/logins stuck in my head. Thanks!

**Comment by JanPokorny** [comment] 2021-03-03 08:05
@cscharf Hello, you did not answer my question. Autofill of card details fails on `https://platebnibrana.csob.cz/[something]`, but that's a one-time transactional URL and I can't simply give you the URL to test it yourself. To see the payment page, you actually have to try to pay for something. So, am I to give you an address for an e-shop that uses that payment gate, and instructions how to try to pay for something?

**Comment by cscharf** [comment] 2021-03-03 15:57
> Hello, you did not answer my question.

Sorry @JanPokorny , the example you have above is sufficient enough, we don't need the _actual_ URL if you have a representative version of it to share, along with the notes/explanation of how to get to it/invoke it.

Thanks again!
Chad

**Comment by setyb** [comment] 2021-04-25 01:33
@cscharf wrote:
> As far as the ability for the community to be able to contribute these 1-off odd mappings in an easy way through the Bitwarden extension, that may certainly be something to look into as that allows economies of scale and a super easy way for a lot of people to contribute. That of course would have to be tempered with hardening and proper vetting of those to ensure malicious code isn't injected or other bad behaviors (manual review process, PRs, etc.). Will give this some thought and put a card on our backlog as a placeholder for it.

I think this is an interested idea as well, but I share the same concerns as Chad (@cscharf).  Additionally, I have concerns about bloat in that the majority of special cases will not likely apply to the majority of users.  For example, if the community finds 1000 special cases, how many of those will actually be used by the average user?

As Chad mentioned, custom fields work very well in many cases, but do require some technical know-how (more than the typical user probably possesses, but not too hard or time-consuming to learn).  What I would like to see worked on the most is all the sites for which custom fields do not work.  I little bit of JavaScript injection by Bitwarden on those sites might be required.

**Comment by sigboe** [comment] 2021-05-03 17:15
Is there any way the Bitwarden extension could autodetect a failed auto-fill? This way we could opt in to automatically provide this data? Or opt in to have a pop up ala "update password" to send this failed attempt?

I am guessing if you actually got a good amount of data and the ability to sort it by failure reason you could quickly fix the most sites at once by starting doing changes that would fix the most sites.

**Comment by Charlock1** [comment] 2021-05-27 03:19
BitWarden doesn't recognize password field on bigbadtoystore.com

**Comment by sigboe** [comment] 2021-05-27 06:23
> BitWarden doesn't recognize password field on bigbadtoystore.com

Im sorry but it doesn't help just making a comment here. In the first post here, there is a link to a form you fill out to report issues with autofill. You also need to pick which browser and OS you are using. :smile:

**Comment by Charlock1** [comment] 2021-05-27 12:25
Hi Sigurd,

I also filled out the form. Thank you.

**Comment by jslawler** [comment] 2021-06-17 09:34
Form filled out for #1901.

**Comment by eliykat** [comment] 2021-07-22 20:41
Hi all! A quick update - we've gotten 200+ responses on the Google Form, which has been extremely useful for being able to review your reports in bulk and strike out any duplicates. It's also kept the rest of the Github Issues section tidy so that we don't get lost in a swathe of autofill issues. So thank you everyone for taking the time to submit or post your reports here. This is actively being reviewed and analyzed so that we can make some improvements in this area. We're still collecting responses in the meantime, so keep 'em coming.

**Comment by Unixware** [comment] 2021-08-04 13:51
the extension (chrome) is filling the passwords on a field that IS NOT PASSWORD.
this happens on the PHPList (admin console) 
the bitwarden is filling my password on the password field AND ON THE "Forgot Password? Enter your email address:" field.

To test it please try the demo page of the PHPlist: 

https://demo.phplist.org/lists/admin/

demo admin username: admin
demo admin password: phplist

thanks

so you can test any updates there,

could you please fix this, it's UNACCEPTABLE

**Comment by Unixware** [comment] 2021-08-04 14:20
good tip, thanks

**Comment by HaroonRehman** [comment] 2021-08-06 18:43
Tested Website:  🥇 https://forums.kali.org/forum.php

Auto-fill not working and password is disclosing which is a critical case if we are doing streaming or share our screen in a conference.
![Screenshot 2021-08-06 201803](https://user-images.githubusercontent.com/76829403/128557227-4348d420-3596-4e49-8c03-a80af5b0b114.png![Kali Foruum Bug my Mozilla Version](https://user-images.githubusercontent.com/76829403/128557337-dae8fa49-5ba6-4d5a-82fa-7f1975fb2498.png)
![Kali Foruum Bug my Mozilla Version](https://user-images.githubusercontent.com/76829403/128557244-cf5c6f2a-9d67-43c4-b40b-73937b0c98fa.png)

**Comment by simonz21** [comment] 2021-08-20 11:00
also doesn't work on my QNAP login pages. Works on password but not Username

**Comment by rajeshisnepali** [comment] 2021-10-16 12:51
Doesn't work in [Mega.nz](https://mega.nz/) extensions (URL: [chrome-extension://bigefpfhnfcobdlfbedofhhaibnlghod/mega/secure.html](chrome-extension://bigefpfhnfcobdlfbedofhhaibnlghod/mega/secure.html))

**Comment by andrhevictor** [comment] 2021-12-08 16:45
@eliykat I'm sorry to revive this issue, but I was wondering how does the "detection" of password change/creation works? Does it detect the HTML input names/ids?

**Comment by eliykat** [comment] 2021-12-09 02:14
@andrhevictor, yes:
* [this function](https://github.com/bitwarden/browser/blob/e835a53b80478e11ef2dd16e8f30db234a886e5e/src/content/autofill.js#L44) runs in the background on the webpage, scrapes its contents, and sends it to the extension in a consumable format (`PageDetails`)
* [this service](https://github.com/bitwarden/browser/blob/master/src/services/autofill.service.ts) is responsible for consuming the `PageDetails` and identifying fields (e.g. username, password, credit card number, whatever) for autofill. For example, [here](https://github.com/bitwarden/browser/blob/e835a53b80478e11ef2dd16e8f30db234a886e5e/src/services/autofill.service.ts#L949) is the logic that finds password fields.

If a field is not detected for autofill because it doesn't match the assumptions in that logic, you can still create a custom field (particularly a [linked custom field](https://bitwarden.com/help/article/auto-fill-custom-fields/#using-linked-custom-fields)) to specifically target the HTML input element. However, I acknowledge there are some autofill issues that this doesn't solve (e.g. accidentally overwriting CAPTCHA data or interfering with javascript on the page).

**Comment by andrhevictor** [comment] 2021-12-09 03:24
@eliykat Thank you! Was more curious than anything else 😅 Glad to know more about how it works underneath. Thanks again.

**Comment by Szeraax** [comment] 2021-12-25 20:26
@simonz21 , check out https://github.com/bitwarden/desktop/issues/1004

**Comment by razkif** [comment] 2022-01-05 00:28
Citi.com - I'm unable to login with autofill but if I autofill and then remove my username and manually enter my username, works.

**Comment by cscharf** [comment] 2022-02-14 22:28
thanks @lyricalpolymath , will need to evaluate how many of the submitted sites having issues with autofill are due to "user experience" scripts which do dumb stuff like disabling fields until another one is filled out, etc. and perhaps something simple like this _could_ work; of course there's always the risk of simply breaking a page itself when using autofill if it's scripted or written in a way that expects certain DOM states to be present and we're monkeying with those.

**Comment by lyricalpolymath** [comment] 2022-02-15 09:04
absolutely @cscharf 
A possible quick hackish solution would simply be to re-add the attribute AFTER having populated the field :) 

```
var field = document.getElementById("password")
if (field.hasAttribute("readonly") ) field.removeAttribute("readonly")

// add autofill here

// now put back the attribute to avoid other scripts
field.setAttributeNode( document.createAttribute("readonly") )
```

**Comment by ZantaClaws** [comment] 2022-03-09 07:12
Autofill is not working on site https://www.elkjop.no/

**Comment by TerminatedProcess** [comment] 2022-03-22 23:39
Does not autofill for Bank of America website. www.bankofamerica.com. For chrome, it will autofill manually with one click in the extension, but not automatically. For opera and firefox, it won't do that. You have to copy/paste the username/password per field.

**Comment by kennymc-c** [comment] 2022-04-30 15:37
I have a special AutoFill problem. I didn't want to create a new issue about it, since it might be related to this one.
When I pin the page of my Asus router (AC86U) in Safari, at some point the session runs out if I haven't opened it for a while and I have to log in again. But then AutoFill doesn't work anymore. However, when I unpin the tab, AutoFill works again.
Once the fields are filled in by AutoFill, I can pin the tab afterwards and AutoFill works even if I empty the fields manually. I have not found any other site that has the same problem.

**Comment by ikjadoon** [comment] 2022-05-09 17:46
Is this issue also meant for autofill failures unrelated to the URL / website? The relevant issue:  

URL: _**any**_ URL where a matching login item has the master password re-prompt enabled (confirmed on PayPal.com, Chase.com, etc.)

Autofill **is not** working: if master password re-prompt is enabled on the matching login
Autofill **is** working: if master password re-prompt is disabled on the matching login

When the master password re-prompt is enabled, autofill silently fails: no error, no ability to input the Master Password, not even the username is autofilled (usernames are **not** protected by the Master Password re-prompt anyways).

I've filled out the form with a note at the bottom. If this particular issue is not the right place, what's the right next step? I'm not sure if this is a bug, a missing feature, a planned feature, or simply a "wontfix" limitation.

- [ ] Make a feature request on the forums?
- [ ] Make a bug report on the forums?
- [ ] Make a GitHub issue?

**Comment by eliykat** [comment] 2022-05-10 03:04
Hi @ikjadoon, thanks for checking, I'd say that's slightly different to what this issue is targeting. There's an existing feature request thread here which I recommend you add to: https://community.bitwarden.com/t/master-password-re-prompt-for-hotkey-and-context-menu-fills/31768

**Comment by pc00per** [comment] 2022-07-17 06:19
Confirming the same issue on monkeytype #368

**Comment by masternetra** [comment] 2022-07-17 15:29
Autofill doesn't work right for Walmart's login. It will fill the password on the second part but not the email field (which is effectively the username part) on the initial page. On Desktop (Linux Mint 21, is a issue on windows 10 as well), using firefox 102.0.1, (64bit) url: https://www.walmart.com/account/login?vid=oaoh&tid=0&returnUrl=%2F

**Comment by illusioon** [comment] 2022-07-21 22:39
Autofill doesn't work, it fill the login*username*(with linked custom field) but won't fill the password field.

Website: https://www.ig.com.br/?l=1  

headerFormEmail(works) and headerFormSenha(doesn't work)

**Comment by quixoticraindrp** [comment] 2022-08-18 15:46
Using autofill on draft2digital.com fails due to Bitwarden attempting to overwrite the reCAPTCHA token.

**Comment by bym007** [comment] 2022-09-05 02:21
Autofill stopped working with NAB web portal a few days back. As reported by a few users, something must have changed in their website, as all reports came out at similar time a few days back.

https://ib.nab.com.au/nabib/index.jsp

**Comment by danielchalmers** [comment] 2022-10-03 20:21
Never seems to work on [Personal Capital](https://home.personalcapital.com/page/login/goHome)

**Comment by itslychee** [comment] 2022-10-05 17:06
Autofill doesn't work for https://studentaid.gov as it counts the password missing/invalid for some reason, a workaround is to view the password, and cut and paste it back into the input box

**Comment by flyconsulting** [comment] 2022-10-25 20:23
Autofill does not work on this page for the username or password field. 
https://account.lenovo.com/us/lenovopro/en/smbaccount/gatekeeper/showpage

**Comment by zainhussaini** [comment] 2022-11-16 18:48
Autofill doesn't work on https://www.anthem.com/login/ either.

**Comment by marsu-p** [comment] 2022-12-01 09:14
Autofill doesn't work on https://*.awsapps.com/start#/, resp https://*.awsapps.com/login/ either.

**Comment by vineetk101** [comment] 2022-12-20 15:49
Bitwarden 2022.12.0 extension on Firefox and Edge: internal servers (self signed): URI detection and autofill stopped working. Update looks real pretty, but something broke (as far as I can tell).

**Comment by TheKidRock** [comment] 2022-12-27 04:13
Password autofill is not working on Chrome, Firefox, Edge in this bank's login page - https://itouch.nicasiabank.com/login.xhtml
However, Firefox's default autofill is working but Chrome and Edge's default autofill is not working too.

**Comment by djsmith85** [comment] 2023-01-09 12:53
> Can't login on AWS login forms like: https://signin.aws.amazon.com/oauth redirected from https://XXX.signin.aws.amazon.com/console
> 
> Worked fine last year and broke sometime in November/December.
> 
> Error in console when I select the login to autofill:
> 
> ```
> Error in event handler: TypeError: Cannot read properties of null (reading 'indexOf')
>     at chrome-extension://jbkfoedolllekgbhcbcoahefnbanhhlh/content/autofill.js:618:40
>     at Array.some (<anonymous>)
>     at urlNotSecure (chrome-extension://jbkfoedolllekgbhcbcoahefnbanhhlh/content/autofill.js:618:24)
>     at doFill (chrome-extension://jbkfoedolllekgbhcbcoahefnbanhhlh/content/autofill.js:636:28)
>     at fill (chrome-extension://jbkfoedolllekgbhcbcoahefnbanhhlh/content/autofill.js:1006:5)
>     at chrome-extension://jbkfoedolllekgbhcbcoahefnbanhhlh/content/autofill.js:1029:7
> ```
@SC-CTS It sounds like you might have URL entry on items matching those urls with null. Please have a look at [this comment](https://github.com/bitwarden/clients/issues/3267#issuecomment-1216534494) to a related issues, showing how to resolve it.
(Re-creating the item(s) manually and then deleting the falsy one, would obviously also work.

In addition a null check was added with https://github.com/bitwarden/clients/pull/4277 and will be rolled out with the next release.

**Comment by abmclin** [comment] 2023-01-13 20:30
Autodetection of password change does not work for transunion.com, wageworks.com, github.com so far

**Comment by abmclin** [comment] 2023-01-13 21:09
Out of curiosity, would it be helpful to also list some sites where password update autodetection worked? In order to gauge how well detection techniques are working? For example, bitwarden successfully detected tumblr.com password change for me.

**Comment by Greenderella** [comment] 2023-01-30 15:44
We appreciate everyone for letting us know about the pages you are having issues with. Due to the nature of autofill issues, we started to track them internally using different Forms depending on the platform:

- mobile: https://docs.google.com/forms/d/e/1FAIpQLScMopHyN7KGJs8hW562VTzbIGL4KcFnx0wJcsW0GYE1BnPiGA/viewform
- browser extension: https://docs.google.com/forms/d/e/1FAIpQLSfkxh1w6vK8fLYwAbAAEVhvhMAJwfFNDtYtPUVk1y5WTHvJmQ/viewform

In the future, if anyone encounters other pages or apps that do not autofill as expected, please avoid opening a new GitHub issue and go directly to the corresponding form.

This issue will now be closed.

Thanks!

**Comment by eliykat** [comment] 2023-02-23 00:55
#4119 has been merged, which fixes a limitation where autofill wasn't filling form elements located in [shadow roots](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM). That fix will be in the March release and should help with websites that use shadow roots.

**Closed** 2024-02-23 19:43 UTC
Labels: enhancement, help wanted, browser
