### ISSUE TITLE
Application completes the login but does not show any data (sits and spins)

### ISSUE THREAD

**Issue by Rogue73k** [bitwarden/clients#8936] opened 2024-04-26 15:05 UTC
### Steps To Reproduce

1. Go to desktop icon for Bitwarden (Deployed from software tool in distro release)
2. Login with Master Password
3. Following successful login, the underlying data for any vault is not displayed only a spinning icon in the list pane

### Expected Result

The expected result is a displaying of the list of items in the vault.

### Actual Result

Spinning gleam in the listing pane. Searching for specific items, nor changing vaults changes this result. Also, attempted both Enabled & Disabled hardware acceleration, with no effect. 

### Screenshots or Videos

![Bitwarden(snap)-spinning_only- 2024-04-26 09-35-46](https://github.com/bitwarden/clients/assets/9404618/5a73f4ee-8d6b-48ba-bac6-67f3be071e23)
![Bitwarden(snap)-veriosn- 2024-04-26 09-36-12](https://github.com/bitwarden/clients/assets/9404618/62050582-8812-4a66-ae35-98c45a3b1aee)
![Bitwarden(snap)-veriosn- 2024-04-26 09-36-12](https://github.com/bitwarden/clients/assets/9404618/9247ed0d-71d9-4331-ab5b-5c2fde565926)

### Additional Context

Downloaded and ran the Linux App-image version of Bitwarden and all functioned as expected but that version is incremented by one (2024.4.1). All browser extensions [Firefox & Brave] are working fine.

### Operating System

Linux

### Operating System Version

ZorinOS 16.3

### Installation method

Snap

### Build Version

2024.4.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-04-26 15:07
Duplicate of https://github.com/bitwarden/clients/issues/8651

**Comment by djsmith85** [comment] 2024-04-26 15:07
Hi @Rogue73k !

Thank you for your report, it seems like it is a duplicate of this one (https://github.com/bitwarden/clients/issues/8651)

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2024-04-26 15:07 UTC
Labels: bug, desktop
