### ISSUE TITLE
Unable to view passwords of my other account

### ISSUE THREAD

**Issue by YamiYukiSenpai** [bitwarden/clients#3391] opened 2022-08-26 13:52 UTC
### Steps To Reproduce

1. Go to the top right corner
2. Click on the email/account drop down
3. Select the second account
4. Type your password 

### Expected Result

Second account's passwords should be viewable

### Actual Result

"error: cannot decrypt"

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/13153124/186918725-ccae1dd9-7931-4cfa-b518-cdb3d97a9c1a.png)

### Additional Context

Version 2022.8.1
Shell 19.0.8
Renderer 102.0.5005.148
Node 16.14.2
Architecture x64

### Operating System

macOS

### Operating System Version

12.5.1

### Installation method

Mac App Store

### Build Version

2022.8.1

**Comment by frdmn** [comment] 2022-09-07 07:07
Can confirm. Quick workaround is to manually sync the Vault (Menubar ➞ File Sync ➞ Vault) again.

**Comment by djsmith85** [comment] 2022-09-09 19:50
Hi @YamiYukiSenpai and thank you for your report.

This issue is a duplicate of https://github.com/bitwarden/clients/issues/3057. Please add any missing information there.

@frdmn Thanks for providing a workaround, until we 

Closing this now.

**Closed by djsmith85** 2022-09-09 19:50 UTC
Labels: bug, desktop
