### ISSUE TITLE
Sign unsigned DLL Files

### ISSUE THREAD

**Issue by hj-collab** [bitwarden/clients#4216] opened 2022-12-13 10:32 UTC
### Steps To Reproduce

1) Install Bitwarden Desktop Client via Bitwarden website or Microsoft Store.
2) Go to installation folder.
3) Right click on dll files and check for a digital signature.

### Expected Result

All DLL files should be signed.

### Actual Result

DLLs Files are not signed. Not able to use Bitwarden with WDAC Protection Enabled.

### Additional Context

If by any chance this is an electron app and using electron builder then you just need to use a parameter.

https://www.electron.build/configuration/win

![image](https://user-images.githubusercontent.com/101234934/207294416-9d32eaf3-872f-4455-8335-ee38766e8739.png)

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Latest

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by MarsCandyBars** [comment] 2023-07-14 14:21
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by djsmith85** [comment] 2023-07-21 08:41
Duplicate of https://github.com/bitwarden/clients/issues/3612

**Comment by Greenderella** [comment] 2023-07-24 12:24
Hi @hj-collab, I will proceed to close this report, since @djsmith85 found the original one, but not before adding the information you provided to our internal report.

Have a nice day.

**Closed by Greenderella** 2023-07-24 12:24 UTC
Labels: bug, desktop
