### ISSUE TITLE
When using TouchId to unlock items requiring Master Password Confirmation aren't accessible

### ISSUE THREAD

**Issue by smparekh** [bitwarden/clients#6311] opened 2023-09-15 14:40 UTC
### Steps To Reproduce

1. Unlock Vault using TouchId
2. Try to view or copy items that require Master Password Confirmation
3. Enter Master Password
4. Value is never copied and confirmation modal hangs

### Expected Result

Item value should be copied, whether the vault was unlocked via TouchId or Master Password

### Actual Result

Modal hangs, item isn't copied - if the vault is unlocked via Master Password it works as expected.

### Operating System

macOS

### Operating System Version

Ventura 13.5.1

### Installation method

Mac App Store

### Build Version

Version 2023.8.4 Shell 24.8.3 Renderer 112.0.5615.204 Node 18.14.0 Architecture arm64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment] 2023-09-15 14:50
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/6153. 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by Neonwarden** 2023-09-15 14:50 UTC
Labels: bug, desktop
