### ISSUE TITLE
bitwarden_bitwarden.desktop[224168] Error: No password found 

### ISSUE THREAD

**Issue by cbean310** [bitwarden/clients#5739] opened 2023-07-05 00:44 UTC
### Steps To Reproduce

Typing bitwarden from command line or accessing from Gnome

(node:333643) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `bitwarden --trace-deprecation ...` to show where the warning was created)
/usr/share/libdrm/amdgpu.ids: No such file or directory
amdgpu: unknown (family_id, chip_external_rev): (143, 60)
libGL error: failed to create dri screen
libGL error: failed to load driver: radeonsi
[333723:0704/174107.687879:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
(node:333643) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'init')
    at BiometricsService.<anonymous> (/snap/bitwarden/89/resources/app.asar/main.js:44455:55)
    at Generator.next (<anonymous>)
    at /snap/bitwarden/89/resources/app.asar/main.js:44421:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/snap/bitwarden/89/resources/app.asar/main.js:44417:12)
    at BiometricsService.init (/snap/bitwarden/89/resources/app.asar/main.js:44454:16)
    at Main.<anonymous> (/snap/bitwarden/89/resources/app.asar/main.js:52500:46)
    at Generator.next (<anonymous>)
    at fulfilled (/snap/bitwarden/89/resources/app.asar/main.js:52397:58)
(node:333643) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
/usr/share/libdrm/amdgpu.ids: No such file or directory
amdgpu: unknown (family_id, chip_external_rev): (143, 60)
libGL error: failed to create dri screen
libGL error: failed to load driver: radeonsi
[333783:0704/174107.801630:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
/usr/share/libdrm/amdgpu.ids: No such file or directory
amdgpu: unknown (family_id, chip_external_rev): (143, 60)
[333760:0704/174107.839117:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
17:41:08.246 › Error: No password found
17:41:08.280 › Error: No password found
17:41:08.281 › Error: No password found
17:41:08.292 › Error: No password found
17:41:08.314 › TypeError: Cannot read properties of undefined (reading 'osSupportsBiometric')
    at BiometricsService.<anonymous> (/snap/bitwarden/89/resources/app.asar/main.js:44460:55)
    at Generator.next (<anonymous>)
    at /snap/bitwarden/89/resources/app.asar/main.js:44421:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/snap/bitwarden/89/resources/app.asar/main.js:44417:12)
    at BiometricsService.osSupportsBiometric (/snap/bitwarden/89/resources/app.asar/main.js:44459:16)
    at BiometricsService.<anonymous> (/snap/bitwarden/89/resources/app.asar/main.js:44470:58)
    at Generator.next (<anonymous>)
    at fulfilled (/snap/bitwarden/89/resources/app.asar/main.js:44418:58)
17:41:08.315 › TypeError: Cannot read properties of undefined (reading 'osSupportsBiometric')
    at BiometricsService.<anonymous> (/snap/bitwarden/89/resources/app.asar/main.js:44460:55)
    at Generator.next (<anonymous>)
    at /snap/bitwarden/89/resources/app.asar/main.js:44421:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/snap/bitwarden/89/resources/app.asar/main.js:44417:12)
    at BiometricsService.osSupportsBiometric (/snap/bitwarden/89/resources/app.asar/main.js:44459:16)
    at DesktopCredentialStorageListener.<anonymous> (/snap/bitwarden/89/resources/app.asar/main.js:44644:59)
    at Generator.next (<anonymous>)
    at /snap/bitwarden/89/resources/app.asar/main.js:44572:71
    at new Promise (<anonymous>)
17:41:08.439 › Error: No password found
17:41:08.945 › Error: No password found
17:41:09.002 › Error: No password found
17:41:09.083 › Error: No password found
17:41:09.167 › Error: No password found
17:41:09.181 › Error: No password found
17:41:09.187 › Error: No password found
17:41:09.225 › Error: No password found
17:41:09.260 › Error: No password found
17:41:09.268 › Error: No password found
17:41:09.288 › Error: No password found
17:41:09.288 › Error: No password found
(node:333643) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'setContextMenu')
    at TrayMain.updateContextMenu (/snap/bitwarden/89/resources/app.asar/main.js:46583:23)
    at MessagingMain.updateTrayMenu (/snap/bitwarden/89/resources/app.asar/main.js:46083:28)
    at MessagingMain.onMessage (/snap/bitwarden/89/resources/app.asar/main.js:46009:22)
    at MessagingMain.<anonymous> (/snap/bitwarden/89/resources/app.asar/main.js:46000:151)
    at Generator.next (<anonymous>)
    at /snap/bitwarden/89/resources/app.asar/main.js:45979:71
    at new Promise (<anonymous>)
    at messaging_main_awaiter (/snap/bitwarden/89/resources/app.asar/main.js:45975:12)
    at IpcMainImpl.<anonymous> (/snap/bitwarden/89/resources/app.asar/main.js:46000:79)
    at IpcMainImpl.emit (node:events:513:28)
(node:333643) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
17:41:09.368 › Error: No password found
17:41:09.376 › Error: No password found
(node:333643) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'setContextMenu')
    at TrayMain.updateContextMenu (/snap/bitwarden/89/resources/app.asar/main.js:46583:23)
    at MessagingMain.updateTrayMenu (/snap/bitwarden/89/resources/app.asar/main.js:46083:28)
    at MessagingMain.onMessage (/snap/bitwarden/89/resources/app.asar/main.js:46009:22)
    at MessagingMain.<anonymous> (/snap/bitwarden/89/resources/app.asar/main.js:46000:151)
    at Generator.next (<anonymous>)
    at /snap/bitwarden/89/resources/app.asar/main.js:45979:71
    at new Promise (<anonymous>)
    at messaging_main_awaiter (/snap/bitwarden/89/resources/app.asar/main.js:45975:12)
    at IpcMainImpl.<anonymous> (/snap/bitwarden/89/resources/app.asar/main.js:46000:79)
    at IpcMainImpl.emit (node:events:513:28)
(node:333643) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
17:41:09.389 › Error: No password found
17:41:09.498 › Error: No password found

### Expected Result

Constant logs reports are not expected

### Actual Result

journalctl -xe produces non-stop errors

17:41:08.246 › Error: No password found
17:41:08.280 › Error: No password found
17:41:08.281 › Error: No password found
17:41:08.292 › Error: No password found

### Operating System

Linux

### Operating System Version

Debian 12

### Installation method

Snap

### Build Version

2023.5.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2023-07-05 07:32
Duplicate of https://github.com/bitwarden/clients/issues/5363

**Closed by djsmith85** 2023-07-05 07:32 UTC
Labels: bug, desktop
