### ISSUE TITLE
Updates interrupt the password typing process 

### ISSUE THREAD

**Issue by ioannis-koukourakis** [bitwarden/clients#5878] opened 2023-07-23 12:21 UTC
### Steps To Reproduce

More of a defect rather than a bug but it's quite annoying and delays the user. 
When the user starts the desktop version and a new update is available there's a delay before the pop-up prompt to update shows up. As a result, it interrupts the user while entering their password and they have to start over. 

1. While a new version is available start Bitwarden Desktop on the previous version.
2. Start typing the password.
3. Soon after you get interrupted by the update prompt. Especially noticeable with long strong passwords. 

### Expected Result

To avoid the issue above it would be better if the update prompt pops up after the user has successfully used their password.

1. While a new version is available start Bitwarden Desktop on the previous version.
2. Type the password to log in.
3. As soon as the user has logged in call the update prompt process for the pop-up window to show up. 

### Actual Result

More of a defect rather than a bug but it's quite annoying and delays the user. 
When the user starts the desktop version and a new update is available there's a delay before the pop-up prompt to update shows up. As a result, it interrupts the user while entering their password and they have to start over. 

1. While a new version is available start Bitwarden Desktop on the previous version.
2. Start typing the password.
3. Soon after you get interrupted by the update prompt. Especially noticeable with long strong passwords. 

### Operating System

Windows, macOS

### Installation method

Direct Download (from bitwarden.com), Mac App Store

### Build Version

2023.5.1

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2023-07-23 12:36
Duplicate of https://github.com/bitwarden/clients/issues/2608

**Comment by djsmith85** [comment] 2023-07-23 12:36
@ioannis-koukourakis: Thank you for the report. This is a duplicate of https://github.com/bitwarden/clients/issues/2608

Closing this now.

**Closed by djsmith85** 2023-07-23 12:36 UTC
Labels: bug, desktop
