### ISSUE TITLE
Auto-fill crashes webpage (Ansible Automation Platform)

### ISSUE THREAD

**Issue by Silejonu** [bitwarden/clients#8681] opened 2024-04-10 20:21 UTC
### Steps To Reproduce

1. Have Bitwarden auto-fill enabled (either mode produces the same result)
2. Have Ansible Automation Platform (I suppose the same issue is also present in AWX)
3. Create a new user
4. Click on "email" or "password" field
5. Wait a few seconds
6. Ansible Automation crashes (see screenshots)

### Expected Result

The webpage shouldn't crash.

### Actual Result

The webpage crashes, spewing JavaScript errors.

Ansible Automation Platform error logs:

```
Error: Permission denied to access property "removeAttribute"

r/n.toggleSiblingsFromScreenReaders@https://myansibletower.mydomain.com/static/js/main.1985ccb4.js:2:1166099
value@https://myansibletower.mydomain.com/static/js/main.1985ccb4.js:2:1167415
gs@https://myansibletower.mydomain.com/static/js/main.1985ccb4.js:2:858410
Ll@https://myansibletower.mydomain.com/static/js/main.1985ccb4.js:2:875199
6813/t.unstable_runWithPriority@https://myansibletower.mydomain.com/static/js/main.1985ccb4.js:2:913546
Gi@https://myansibletower.mydomain.com/static/js/main.1985ccb4.js:2:817017
Rl@https://myansibletower.mydomain.com/static/js/main.1985ccb4.js:2:871936
yl@https://myansibletower.mydomain.com/static/js/main.1985ccb4.js:2:868020
4463/Ki/<@https://myansibletower.mydomain.com/static/js/main.1985ccb4.js:2:817240
6813/t.unstable_runWithPriority@https://myansibletower.mydomain.com/static/js/main.1985ccb4.js:2:913546
Gi@https://myansibletower.mydomain.com/static/js/main.1985ccb4.js:2:817017
Ki@https://myansibletower.mydomain.com/static/js/main.1985ccb4.js:2:817187
Wi@https://myansibletower.mydomain.com/static/js/main.1985ccb4.js:2:817120
Le@https://myansibletower.mydomain.com/static/js/main.1985ccb4.js:2:888331
Yt@https://myansibletower.mydomain.com/static/js/main.1985ccb4.js:2:795733
```

### Screenshots or Videos

Before the crash:
![Capture d’écran du 2024-04-10 22-06-33](https://github.com/bitwarden/clients/assets/48565914/70fd4edc-6c04-4a6c-a790-791b0b45ba99)

Crash:
![Capture d’écran du 2024-04-10 22-16-14](https://github.com/bitwarden/clients/assets/48565914/3793e9c5-0a6b-43e5-ae45-7c206f495b44)

### Additional Context

Auto-fill needs to be on for the crash to happen. The mode does not matter.

If auto-fill is off, the webpage does not crash.

I tried disabling **all Firefox extensions but Bitwarden**, and I can confirm the issue is still present when auto-fill is on.

### Operating System

Linux

### Operating System Version

Fedora 39

### Web Browser

Firefox

### Browser Version

124.0.2 (64 bits)

### Build Version

2024.2.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cagonzalezcs** [comment] 2024-04-10 20:35
Duplicate of #8063

A fix for this has been merged recently. Details are present in the Github issue linked above

Until that update is released, you should be able to turn off the inline autofill menu and still use the other autofill methodologies without issue. 

That can be done by going to Settings > Autofill within the extension.

**Closed by cagonzalezcs** 2024-04-10 20:35 UTC
Labels: bug, browser
