### ISSUE TITLE
Bug in Ubuntu

### ISSUE THREAD

**Issue by mel0s** [bitwarden/clients#9594] opened 2024-06-11 23:55 UTC
### Steps To Reproduce

1. After to login
![Screenshot from 2024-06-11 17-49-45](https://github.com/bitwarden/clients/assets/21264919/f4584e43-72a3-42b9-8f39-76ee4e39853b)
2. Main view stays loading

### Expected Result

Show all the elements that I have generated

### Actual Result

After logging in it keeps loading the information

### Operating System

Linux

### Operating System Version

Ubuntu 22.04.4 LTS

### Installation method

Snap

### Build Version

Version 2024.5.0 Shell 28.3.1 Renderer 120.0.6099.291 Node 18.18.2 Architecture x64

### Issue Tracking Info

- [ ] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment] 2024-06-12 02:05
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/clients/issues/8651

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by sammbw** 2024-06-12 02:05 UTC
Labels: bug, desktop
