### ISSUE TITLE
Dead keys not recognized when they are the first ever key press on app launch.

### ISSUE THREAD

**Issue by CrumbleZ** [bitwarden/clients#7056] opened 2023-12-01 08:37 UTC
### Steps To Reproduce

1. Launch the Bitwarden Desktop Client, the cursor is already present in the master password field;
2. Press a dead key that requires no modifier key to activate (such as the `^` character on a de-CH keyboard layout);
3. Press the same key again two times more to see that character appear on the master password field only twice, with no hanging symbol.

### Expected Result

1. Pressing `^` + `space` when launching the app should yield `^` in the master password field.
2. Pressing `^` + `^` + `^` + `a` when launching the app should yield `^^â` in the master password field.

### Actual Result

1. Pressing `^` + `space` when launching the app yields ` ` in the master password field.
2. Pressing `^` + `^` + `^` + `a` when launching the app yields `^^a` in the master password field.

### Additional Context

* If you press and release any modifier key such as ALT or SHIFT before using a dead key that doesn't require such a modifier key to be used, then the dead key will be recognized normally;
* If you take the focus out of the master password field with a mouse click somewhere else in the window and press any key and then go back to the master password field, dead keys will be recognized normally. But if you just focus out, don't press any key and focus back into the field, the issue will still be present;
* The `^` character is the only character on my keyboard layout (de-CH) that doesn't require a modifier, so I can't test for other characters and maybe this only concerns this specific character.
* This may be a duplicate of #3257. But it has been closed and marked as duplicate of #2472, which is definitely not the case for this issue, either by the light of newer details, but also the reproducibility.
* Sorry to stress this out, but it's so weird that it might be easy to forget when trying to reproduce : This issue only concerns the **first ever key press once the app is launched.**

#### So what differs from #2472 ?
* This issue is not macOS specific since I'm having the issue on a Windows. I do not have a mac or linux at my disposal to test on another OS
* It has nothing to do with the toggle password visibility feature
* I do not have the issue with browser extensions (Brave)

### Operating System

Windows 11 Pro

### Operating System Version

22H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment] 2023-12-04 07:35
Hi @CrumbleZ 

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/2472 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

**Closed by Adedamola-Aina** 2023-12-04 07:35 UTC
Labels: bug, desktop

**Comment by CrumbleZ** [comment] 2023-12-04 10:48
Thank you for your answer @Adedamola-Aina 

I've taken the time to dig tickets #2472 and #3257 out, read through them, and explained why I believe my issue is dissimilar in behaviour by creating this new ticket, so I'm not sure I understand why it's being marked as duplicate. I would really appreciate if you would take a moment to clarify this for me.

Thank you kindly.
