### ISSUE TITLE
Unable to login. 

### ISSUE THREAD

**Issue by andyberks** [bitwarden/clients#8823] opened 2024-04-18 22:52 UTC
### Steps To Reproduce

master password has no effect. wheel keeps turning around without opening database. I am able to see my db in the chrome extension, on a browswer, and on my android device, so something is specifically wrong with the windows desktop app. 

### Expected Result

open database

### Actual Result

database not opening

### Operating System

Windows

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.4.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment] 2024-04-19 00:47
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by trmartin4** [comment] 2024-04-19 02:05
This is possibly the same issue that is reported [here](https://github.com/bitwarden/clients/issues/8673).

@andyberks, if you have a moment there are a few questions that might help us isolate the problem internally:

1. Are you running Windows 10 or Windows 11?
2. Did you download `2024.4.1` directly from Bitwarden.com, or did you download a previous version that auto-updated to `2024.4.1`?
3. Could you provide us with what your vault timeout action and settings are?

Thank you for your help!

**Comment by LeGhostFace** [comment] 2024-04-19 11:54
I don't know if I should open a separare Bug Report but I have the same exact issue. 

I realized that Firefox wasn't syncing with my desktop app. Syncing in desktop app said Syncing Failed, logged out, rebooted the app and now i'm stuck in a rotating wheel and my vault dosen't show up. Firefox extention still works at least.

**Comment by LeGhostFace** [comment] 2024-04-19 11:56
![Screenshot 2024-04-19 075555](https://github.com/bitwarden/clients/assets/73848349/70530584-6075-49e6-b364-d4d8b264b3e6)

**Comment by andyberks** [comment] 2024-04-19 12:38
I think this was a Windows problem. My laptop did a silent update yesterday
that seemed to have reset the Windows hello and other authentication
options. Bitwarden uses Windows Hello (fingerprint sensor).

However, this still does not explain the inability (last night) of the
Windows 11 BW app to open the database with my Bitwarden master password.

I got Windows Hello fixed, and now the problem appears to be resolved. I
opened BW twice this morning and it worked normally. Thanks!

**Comment by chrisposito** [comment] 2024-04-19 13:41
This doesn't seem to be Windows specific. I'm having the same issue on the latest snap version on Ubuntu 22.04 (bitwarden  2024.4.0  revision 108). No matter what I do, I just get a spinning circle upon logging in/unlocking the vault. Have tried `snap remove --purge bitwarden` and reinstall. No change.

**Comment by trmartin4** [comment] 2024-04-19 15:11
@chrisposito - we are tracking and investigating issues on Linux as well as Windows.  Here are the issues we're using to track them publicly:

- Windows desktop "endless loading" or JWT errors in 2024.4.0 or 2024.4.1 versions
  - https://github.com/bitwarden/clients/issues/8673
- Linux desktop "endless loading" or JWT errors in 2024.4.0 or 2024.4.1 versions
  - https://github.com/bitwarden/clients/issues/8651

Due to the nature of the issue involved (platform-specific secure storage) it is likely that the solution will be different between Windows and Linux - hence the independent tracking.

For snap in particular, we have instructions [here](https://btwrdn.com/install-snap) to configure the snap install to have the required support.  We are working on a more flexible solution that will not require this step, but it should solve the problem for you.

@LeGhostFace - thank you for your report.  Could you let me know the answers to these questions to help our investigation?

1. Are you running Windows 10 or Windows 11?  Could you provide the build number if possible?
2. Did you download 2024.4.1 directly from Bitwarden.com, or did you download a previous version that auto-updated to 2024.4.1?
3. Could you provide us with what your vault timeout action and settings are?
4. What PIN or Biometric settings do you have enabled, if any?

**Comment by LeGhostFace** [comment] 2024-04-19 15:43
@trmartin4 

Hi thank you for the reply. 

1. Win 11 - 22631.3447
2. The first version I had was updated, but I removed it and scrubbed it with Revo and then downloaded fresh from your site. Same issue
3. The vault timeout setting is set on "On Restart - lock"
4. No biometrics (Windows Hello or Pin etc..) all of this is deactivated.

**Comment by chrisposito** [comment] 2024-04-19 15:44
> @chrisposito - we are tracking and investigating issues on Linux as well as Windows. Here are the issues we're using to track them publicly:
> 
> * Windows desktop "endless loading" or JWT errors in 2024.4.0 or 2024.4.1 versions
>   
>   * [Windows 10 Desktop Fails to Sync or Login #8673](https://github.com/bitwarden/clients/issues/8673)
> * Linux desktop "endless loading" or JWT errors in 2024.4.0 or 2024.4.1 versions
>   
>   * [Error when syncing the vault on Linux desktop #8651](https://github.com/bitwarden/clients/issues/8651)
> 
> Due to the nature of the issue involved (platform-specific secure storage) it is likely that the solution will be different between Windows and Linux - hence the independent tracking.
> 
> For snap in particular, we have instructions [here](https://btwrdn.com/install-snap) to configure the snap install to have the required support. We are working on a more flexible solution that will not require this step, but it should solve the problem for you.
> 
> @LeGhostFace - thank you for your report. Could you let me know the answers to these questions to help our investigation?
> 
> 1. Are you running Windows 10 or Windows 11?  Could you provide the build number if possible?
> 2. Did you download 2024.4.1 directly from Bitwarden.com, or did you download a previous version that auto-updated to 2024.4.1?
> 3. Could you provide us with what your vault timeout action and settings are?
> 4. What PIN or Biometric settings do you have enabled, if any?

I did try `sudo snap connect bitwarden:password-manager-service` as you mentioned, as I saw it referenced elsewhere, but it did not fix the issue. Revision 105 seems to be working for me. 106 gave the same login issue. I've reverted to an old version and held the package for 90 days, until the issue is hopefully resolved, by running:
`sudo snap refresh --revision 105 bitwarden`
`sudo snap refresh --hold=2160h bitwarden`

**Comment by andyberks** [comment] 2024-04-19 15:48
I have Win 11 build 22631.3447
For Bitwarden, I had a previous version that updated. I have a recollection
that it updated itself in the past week.
I am not sure about vault timeout
I keep Windows Hello (biometrics) active for the fingerprint sensor. I also
have a Windows PIN.


Andrew H. Berks, Ph.D., J.D.
Patent Attorney
Berks IP Law PLLC
28 Liberty St 6th Fl
New York NY 10005
mobile: +1 845-558-7245 <http://voice.google.com/calls?a=nc,%2B18455587245>
<http://voice.google.com/calls?a=nc,%2B18455587245>
<http://voice.google.com/calls?a=nc,%2B18455587245>
***@***.***, berksiplaw.com  freship.com
LinkedIn <https://www.linkedin.com/in/andyberks/>

**Comment by trmartin4** [comment] 2024-04-19 20:38
In order to consolidate updates and avoid multiple discussions, I am going to close this and direct Windows users to
https://github.com/bitwarden/clients/issues/8673 and Linux users to https://github.com/bitwarden/clients/issues/8651.  We are actively investigating these issues and working on solutions.  We will update these threads as we make progress.

Thank you to all who provided detailed feedback on versions and replication steps.  Please continue to monitor the other threads for updates.

**Closed by trmartin4** 2024-04-19 20:38 UTC
Labels: bug, desktop

**Comment by andyberks** [comment] 2025-07-19 14:47
I need your assistance, please.
My husband, Andrew Berks, PhD, Esq., was killed in a Citibike Accident in
February.  He held a PhD in organic chemistry and a law degree.  It has
been devastating.  I am Deloria Berks, his wife, I am a psychotherapist in
NYC.

Andy and I were very close but he took care of ALL the Tech side of our
lives.  I have slowly pieced together many layers but I'm wondering how I
can obtain the password database?  I have executed Wills that state I am
the executor, and I am having the Will probated, which will produce a
letter of testamentary.  One insurance policy required the probate so it is
in the works.

I've been OK with figuring some things out -- but one problem is -- he had
an I-Phone to get into his office at Rivkin Radler.  All I have is the
phone number so I was able to stop the billing.  I'm trying to give the
phone to a young man who we mentored.  He plays ice hockey and is a major
star -- Andy helped fund his career.  He is now 2nd year in a top junior
league and captain of his team, and has an agent from France.  I'm trying
to give him this I-Phone but I need the phone Apple ID ????  ANd who knows
what else I need that I'm paying for and have no idea...

This is a lot but any advice you can give -- would be helpful.  I have a
downloaded password database from another company but it's 10 years old!

I realize the sensitivity but there must be a legal way I can obtain this
information.

I am writing to you from Andy's email now -- I am able to access his
computer.

My contact info:

Deloria Berks
77 Fulton St.
  4M
NY, NY  10038
84-558-8928
***@***.***
https://www.stresstoserenity.com/

My best,
Deloria
