### ISSUE TITLE
javascript error after update

### ISSUE THREAD

**Issue by linygany1** [bitwarden/clients#3283] opened 2022-08-11 16:10 UTC
### Steps To Reproduce

Open programm
Get error

### Expected Result

Before update it work perfect 

### Actual Result

After auto-updating to last version, programm just crash with this error, so i need to manually delete it and install older version. 
Old version (2022.6.0)  on first load just freeze in bitwarden window with 25% cpu load, so i need to shutdown procces and open it again, second load is ok

### Screenshots or Videos

![Screenshot_7](https://user-images.githubusercontent.com/28450967/184179080-347fbc0b-534c-4a82-bcad-eeaeefeaaf04.jpg)

### Operating System

Windows

### Operating System Version

Windows 7

### Installation method

Direct Download (from bitwarden.com)

### Build Version

I cant get version when crash occur, because window just dont open

**Comment by djsmith85** [comment] 2022-08-11 17:20
Hi @linygany1 and thank you for your report. This is a known issue, which is tracked with https://github.com/bitwarden/clients/issues/3264.

Closing this issue as duplicate of https://github.com/bitwarden/clients/issues/3264.

**Closed by djsmith85** 2022-08-11 17:20 UTC
Labels: bug, desktop
