### ISSUE TITLE
Unable to create new entries

### ISSUE THREAD

**Issue by abel-wilderfields** [bitwarden/clients#8599] opened 2024-04-03 16:22 UTC
### Steps To Reproduce

1. Select an company collection.
2. Click "+" button to add new item.
3. "There are no collections to list." and error when saving item.
4. I am the company vault owner.

### Expected Result

Item is added to the selected collection.

### Actual Result

An error has occurred, you must select at least one collection.

### Screenshots or Videos

<img width="265" alt="image" src="https://github.com/bitwarden/clients/assets/91687308/28fc1d6c-fc47-4890-8e4f-a81f7e06f7b7">
<img width="367" alt="image" src="https://github.com/bitwarden/clients/assets/91687308/2b1c82e2-9ad2-476f-8eb5-51a3ead269d3">

### Additional Context

I am able to add items to the seme folder using the browser interface; items added show up in the windows client.

_No response_

### Operating System

Windows

### Operating System Version

Windows 11 (Microsoft Windows [Version 10.0.22631.3374])

### Installation method

Microsoft Store

### Build Version

Version 2024.3.0 Shell 28.2.4 Renderer 120.0.6099.291 Node 18.18.2 Architecture x64

### Issue Tracking Info

- [ ] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TroyBW** [comment] 2024-04-03 23:17
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: [https://github.com/bitwarden/clients/issues/8258](https://github.com/bitwarden/clients/issues/8258). 

As a temporary solution, please switch the ownership drop-down to your account, then back to the organization. That should trigger the display of the collection. 

This issue will now be closed.

Thanks!

**Closed by TroyBW** 2024-04-03 23:17 UTC
Labels: bug, desktop
