### ISSUE TITLE
Unlock with biometrics is dependent on desktop app

### ISSUE THREAD

**Issue by Toryalai1** [bitwarden/clients#11553] opened 2024-10-15 08:30 UTC
### Steps To Reproduce

Important: Desktop client should be closed down!

1. Go to a random website that requires login
2. In the login page, click on the bitwarden web extension button. (In my case it is firefox)
3. Click on unlock with biometrics
4. The following window will pop up:  
![image](https://github.com/user-attachments/assets/85c3c86b-790e-415a-8213-740fd94724f1)

### Expected Result

The expected result should be that the extension should be independent on the desktop app.

### Actual Result

When unlocking with biometrics on the browser extension (firefox in my case). I get the following pop up:
![image](https://github.com/user-attachments/assets/47d04fa9-31a1-4adb-9c28-33e54ad23887)

### Operating System

Windows

### Web Browser

Firefox

### Browser Version

131.0.3

### Build Version

2024.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment] 2024-10-15 08:59
Hi there!

Thank you for your report, it seems like it is a duplicate of this one (https://github.com/bitwarden/clients/issues/11168)
If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Comment by NovaSilentium** [comment] 2024-10-15 08:59
duplicate of#11168

**Closed** 2024-10-15 09:00 UTC
Labels: bug, browser
