### ISSUE TITLE
 CLI client version 2024.10.0 is no longer free software

### ISSUE THREAD

**Issue by bobberb** [bitwarden/clients#11647] opened 2024-10-21 20:37 UTC
### Steps To Reproduce

Pull request https://github.com/bitwarden/clients/pull/10974 introduces the @bitwarden/sdk-internal dependency which is needed to build the cli client. The dependency contains a licence statement which contains the following clause:
```

You may not use this SDK to develop applications for use with software other
than Bitwarden (including non-compatible implementations of Bitwarden) or to
develop another SDK.
```

This violates [freedom 0](https://www.gnu.org/philosophy/free-sw.en.html).

It is not possible to build bitwarden-cli-v2024.10.0 (or, likely, current master) without removing this dependency.

### Expected Result

Free software

### Actual Result

Non-free software

### Operating System

Linux

### Web Browser

Firefox

### Build Version

2024.10.0 

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by kspearrin** [comment] 2024-10-22 00:41
Duplicate of https://github.com/bitwarden/clients/issues/11611

**Closed by kspearrin** 2024-10-22 00:41 UTC
Labels: bug, browser
