### ISSUE TITLE
High CPU, memory and slow on Microsoft Edge

### ISSUE THREAD

**Issue by mmagdy88** [bitwarden/clients#5812] opened 2023-07-13 10:33 UTC
### Steps To Reproduce

Click on Bitwarden extension button on Microsoft Edge

### Expected Result

Opens instantly without issues.

### Actual Result

Takes more than 200% CPU usage and 500MB of memory in addition to being slow and not responsive.

### Screenshots or Videos

![Screenshot_2](https://github.com/bitwarden/clients/assets/18657710/f022577c-1b49-4401-acaa-8b629c56bb7d)

### Additional Context

This happened suddenly today, it was working fine yesterday.

### Operating System

Windows

### Operating System Version

Windows 10 Pro 21H2 19044.3086

### Web Browser

Microsoft Edge

### Browser Version

114

### Build Version

114.0.1823.79 (Official build) (64-bit)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment] 2023-07-13 10:34
Hi @mmagdy88, 

Thank you for your report, it seems like it is a duplicate of this one - https://github.com/bitwarden/clients/issues/5807. 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Comment by mmagdy88** [comment] 2023-07-13 10:35
> Hi @mmagdy88,
> 
> Thank you for your report, it seems like it is a duplicate of this one - #5807.
> 
> If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.
> 
> This issue will now be closed.
> 
> Thanks!

My bad didn't see it, I will close this issue and track the other one.

**Closed by atjbramley** 2023-07-13 10:34 UTC
Labels: bug, browser
