### ISSUE TITLE
MACOS client 2024.2.0 unusable

### ISSUE THREAD

**Issue by diphigital** [bitwarden/clients#7987] opened 2024-02-16 19:33 UTC
### Steps To Reproduce

4. Click on '...'
Open the macOS client 

### Expected Result

Since the last update, the macOS client is not usable 

### Actual Result

No login or other option to access the client is presented

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/100888643/a58ba1a3-5d95-4215-aa33-b83c85694925)

### Operating System

macOS

### Operating System Version

Ventura 13.4.1

### Installation method

Mac App Store

### Build Version

Version 2024.2.0 Shell 28.1.3 Renderer 120.0.6099.199 Node 18.18.2 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment] 2024-02-16 21:47
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/7528. 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by Neonwarden** 2024-02-16 21:47 UTC
Labels: bug, desktop
