### ISSUE TITLE
Restart to update pop-up is shown while typing password

### ISSUE THREAD

**Issue by pana-exfo** [bitwarden/clients#5707] opened 2023-06-29 10:36 UTC
### Steps To Reproduce

Prequisities
1. Bitwarden is not in latest version
Steps
1. Start typing password
2. In middle of password, if you are slow, Restart to update pop-up is shown

### Expected Result

I would not like to have any popups shown while I'm typing my password.
Just before or just after it is fine.

### Actual Result

Restart to update pop-up is shown and I'm forced to make selection (Restart or later) before able to continue typing my password. When going back, I have to clear the password and type it from beginning.

### Screenshots or Videos

<img width="422" alt="image" src="https://github.com/bitwarden/clients/assets/138116383/755f11bc-5ede-438c-b99f-5832efdec02a">

### Operating System

Windows

### Operating System Version

10

### Installation method

Other

### Build Version

2023.4.0

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2023-06-29 12:24
@pana-exfo  Thank you for the report. This is a duplicate of https://github.com/bitwarden/clients/issues/2608

Closing this now.

**Closed by djsmith85** 2023-06-29 12:24 UTC
Labels: bug, desktop
