### ISSUE TITLE
Entering new credentials via toolbar popup loses all values on focus lost (i.e., via "Copy & Paste" )

### ISSUE THREAD

**Issue by bentolor** [bitwarden/clients#4278] opened 2022-12-20 12:55 UTC
### Steps To Reproduce

1. Go to a site in Firefox w/ the Bitwarden Client
2. Click on the BitWarden Toolbox
3. Press + on the upper right to create a new entry
4. Write / Paste i.e. your user name
5. Click to another application/tab (i.e. firefox password tab)
6. On resuming, all your previes entries will be lost.

### Expected Result

Ideally: The Popup stays open

Alternatively: On reopening the popup my entered values are rentained.

### Actual Result

You can't. Manually retype values. You just can't

### Operating System

Linux

### Web Browser

Firefox

### Build Version

2022.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2022-12-20 13:31
Hi @bentolor, thank you for your report.

This is a duplicate of https://github.com/bitwarden/clients/issues/1798, please see https://github.com/bitwarden/browser/issues/1798#issuecomment-831574003 closing that issue.

Closing this now.

**Closed by djsmith85** 2022-12-20 13:31 UTC
Labels: bug, browser

**Comment by bentolor** [comment] 2022-12-20 13:34
@djsmith85 Thanks for the triage. 

But I'm unable to find the follow-up. This bug is clearly unadressed.

I quote:

> Alternatively, there is a [feature request on our forums](https://community.bitwarden.com/t/browser-extension-remembers-where-i-was/1369/) to have the popup remember its state, so that you could reopen it without any data loss.

But following that link leads to a 404.

**Comment by djsmith85** [comment] 2022-12-20 13:37
@bentolor Apologies, indeed the link to the feature request was broken. I have updated @eliykat's comment with the correct link.
