### ISSUE TITLE
Very slow to unlock or display UI + list of items when the self-hosted server is turned off

### ISSUE THREAD

**Issue by rchomat** [bitwarden/clients#11024] opened 2024-09-13 08:47 UTC
### Steps To Reproduce

@justindbaur @trmartin4 
Please, reopen the issue https://github.com/bitwarden/clients/issues/9561 and push a HOTFIX ASAP. We're facing this issue since more than 3 months now and the last fix didn't fix anything.
Please take a look at my comment https://github.com/bitwarden/clients/issues/9561#issuecomment-2345528788

Turn off the self-hosted server

1. On the browser app, unlock the safe.
2. The app stays on the unlock screen for a while. Multi click on the unlock button doesn't change anything, it's stuck during several minutes. If you close the app and reopen it, the app is just a grey background without anything it in for several minutes

### Expected Result

When a self-hosted server is disconnected, we should be able to use the local data without having to wait several minutes

### Actual Result

UI & items are shown several minutes after the app is opened or the safe unlocked

### Screenshots or Videos

![Screenshot 2024-09-12 at 09 51 17](https://github.com/user-attachments/assets/e5dcd141-9df7-4539-bb72-b1ba74614c02)

### Additional Context

I use to turn on my server only when I need to synchronise my clients or save a new password. The rest of the time it's turned off.

### Operating System

macOS

### Operating System Version

14.4.1

### Web Browser

Chrome

### Browser Version

127.0.6533.100

### Build Version

2024.9.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-09-13 17:15
Duplicate of #9561

**Comment by djsmith85** [comment] 2024-09-13 17:16
Closing as duplicate and a [comment](https://github.com/bitwarden/clients/issues/9561#issuecomment-2349387211) has been added by @justindbaur on #9561

**Closed by djsmith85** 2024-09-13 17:16 UTC
Labels: bug, browser
