### ISSUE TITLE
bw login with apikey argument fails

### ISSUE THREAD

**Issue by noamkfir** [bitwarden/clients#3027] opened 2022-07-03 21:36 UTC
### Steps To Reproduce

# Interactive Repro
1. Run the command `bw login --apikey`.
2. When prompted, enter the `client_id`.
3. When prompted, enter the `client_secret`.

# Noninteractive Repro
1. Export the `BW_CLIENTID` and `BW_CLIENTSECRET` environment variables with the respective client id and client secret.
2. Run the command `bw login --apikey`

### Expected Result

The bitwarden cli should successfully log in.

### Actual Result

The cli immediately exits and displays the following error message in red:

> Cannot read properties of null (reading 'profile')

### Screenshots or Videos

I can't record it because that would expose the api key.

### Additional Context

I tried to debug the issue with vscode.

The line that throws the unhandled exception is in libs/common/src/misc/logInStrategies/logIn.strategy.ts at line 224 in the `setApiKeyClientId` function:
```
account.profile.apiKeyClientId = value;
```
As you might guess from the error message `account` is null so it can't read `account.profile`.

From what I can see, this is the general flow. When `ApiLogInStrategy` calls `startLogIn` with the api key, it calls the `apiService.postIdentityToken` method and gets an `IdentityTokenResponse`. When it processes that response, it calls `saveAccountInformation`, which tries to decode the token and extract the account information from the response.

The problem is that the decoded `accountInformation` object has a `client_sub` property but the method is looking for a `sub` property to assign to `profile.userId`. This seems to create a kind of chain reaction in which the account info can never be stored in memory or on disk, eventually culminating in the failure to load the account info from any storage and triggering the error.

The only reference I found to `client_sub` was in the server project  in `CurrentContext.SetContextAsync`, where both `sub` and `client_sub` are referenced as possible claims so I don't really know whether this behavior is correct or not and I can't really dig any deeper right now.

### Operating System

macOS

### Operating System Version

12.4 (21F79)

### Shell

Zsh

### Build Version

1.22.1

**Comment by graudeejs** [comment] 2022-08-15 07:40
I've just hit this very same issue

**Comment by dbosompem** [comment] 2022-08-15 13:52
Hi @noamkfir , @graudeejs , thank you for submitting this issue. The team will reproduce this, and upon a successful one we'd look into it and get back to you.

**Comment by rdaugherty** [comment] 2022-08-15 21:50
Hi @noamkfir, we were unable to reproduce this issue with our cli version 1.22.1 on MacOs 12.4 using zsh.

Version 1.22.1 was released in April, and since that time there have been a couple releases that have fixed some bugs related to login. Please try updating to the most recent version and see if the issue still persists. If so, is there any extra information you can provide that could assist in replicating the issue?

**Comment by graudeejs** [comment] 2022-08-16 07:41
![image](https://user-images.githubusercontent.com/1020124/184824838-61c7eacb-f3d7-4cdb-bc3d-5270135e1a07.png)

I used `bw` from npmjs.org (`npm install -g @bitwarden/cli`)

**Comment by rdaugherty** [comment] 2022-08-16 16:02
@graudeejs Thank you. I was able to replicate this issue on my end using 2022.8.0 with api credentials scoped to an organization. Turning this over to our development team to fix.

**Comment by noamkfir** [comment] 2022-08-25 23:23
@rdaugherty I tried to a number of different versions, including 2022.8.0, and this seems to happen with all of them. I tried installing it with both npm and homebrew, and neither helped. I also followed the advice I found in a thread on the community forum and tried to delete the various data.json files between attempts. No dice.

I'm really glad that you've been able to replicate this issue.

Can I ask if there's a rough estimate for when the dev team might take a look at it?

**Comment by rdaugherty** [comment] 2022-08-29 13:26
@noamkfir This ticket has been moved to the next stage where our dev team will determine it's priority and slot it in for a particular release. Our next release, in the coming weeks, has already reached code cutoff. So the earliest the team can potentially address the issue is during the following release cycle, which are usually six week cycles.

**Comment by GFoley83** [comment] 2022-10-08 05:42
Any update on this? Still present in Windows version 2022.9.0.

**Comment by szitasg** [comment] 2022-10-11 21:54
@rdaugherty is it prioritized to 2022.10.0?

**Comment by rdaugherty** [comment] 2022-10-27 16:51
Hello all. It's quite possible that I made a mistake here. The dev team recently picked up the related ticket and, based on the information provided, pointed me the the help documentation:

- https://bitwarden.com/help/cli/#using-an-api-key
- https://bitwarden.com/help/personal-api-key/

Basically, only personal API credentials can be used with the CLI client and the `--apikey` argument (EX: client_id=user.xxx). @graudeejs provided a screenshot showing they were getting the error using organization API credentials; @noamkfir was
this also the scope you were originally using as well?

As it stands now, using the correctly scoped credentials continue to be working as expected from my end. However, if anyone
is still running into the originally stated error using personal API credentials, please provide as much info as you
can and we will continue to investigate.

The dev team is currently re-scoping this ticket only to add appropriate error messaging in this scenario that a user attempts to login with improperly scoped credentials.

My apologies to everyone here, as this was a piece of the login process that I completely missed when originally investigating
this ticket.

**Comment by cyprain-okeke** [comment] 2022-11-18 20:44
completed via [#PR](https://github.com/bitwarden/clients/pull/3959). Fix will be included in the 2022.12 release.

**Closed** 2022-11-21 12:44 UTC
Labels: bug, cli

**Comment by jagjordi** [comment] 2024-10-24 08:36
For other people reaching this issue. I had this problem also. The issue was that my API key had trailing spaces at the beginning/end. Removing those solved the problem
