### ISSUE TITLE
Cannot proceed past Master Password Confirmation

### ISSUE THREAD

**Issue by JackDDavis** [bitwarden/clients#6292] opened 2023-09-14 14:50 UTC
### Steps To Reproduce

1. Enable 'Master Password Re-prompt' on an existing password
2. Navigate to website
3. Select credential
4. After being prompted for Master Password Re-prompt, attempt to select 'Ok'.

### Expected Result

Credential is then accessible and can be copied or viewed

### Actual Result

No response from 'Ok' button though darkened reflecting it has been pressed. Extension (as well as Desktop Application) is responsive as 'Cancel' button works. But cannot proceed with 'Ok'.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/24422671/bcef4927-ee58-42dc-b8e1-a05ee35b752c)

### Additional Context

Version 2023.8.3

- Same experience across desktop client & web extensions
- Same experience on Windows 10 & 11.
- Using Edge browser for web extension approach (but again, same experience with desktop app)

### Operating System

Windows

### Operating System Version

Windows 11/ Windows 10

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.8.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment] 2023-09-14 15:26
Hi @JackDDavis, 

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/6153

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by atjbramley** 2023-09-14 15:26 UTC
Labels: bug, desktop
