### ISSUE TITLE
Focus issue on email/master password fields on login page

### ISSUE THREAD

**Issue by warwickmm** [bitwarden/clients#3800] opened 2022-10-15 17:04 UTC
### Steps To Reproduce

1. Log out of the vault
2. Attempt to log in by either clicking on the Bitwarden icon and then "Log in", or hitting ctrl+shift+L and then selecting "Log in"
3. The master password field is not focused, even after waiting for a long time.

### Expected Result

The master password field should be given focus so that the user can just begin typing their password.

### Actual Result

The master password field is not focused, even after waiting for along period of time.  This behavior is similar to that reported in #3787 and #3685, but different than that reported in #3562, which indicates that focus is given after a brief lag.

### Operating System

Linux

### Operating System Version

6.0.1-arch2-1

### Web Browser

Brave

### Browser Version

Version 1.44.112 Chromium: 106.0.5249.119 (Official Build) (64-bit)

### Build Version

2022.10.0

**Comment by naxxfish** [comment] 2022-10-16 09:52
This is a duplicate of https://github.com/bitwarden/clients/issues/3718

**Comment by sadreck** [comment] 2022-10-16 11:47
The same behaviour can be observed when visiting https://vault.bitwarden.com (with no browser extension installed) - no fields are autofocused.

Before the most recent update if the username was saved it'd autofocus on the password, which no longer happens.

I'm using Firefox on Win10.

**Comment by warwickmm** [comment] 2022-10-18 01:39
It appears that if the vault is locked, then the password field is focused when attempting to unlock it.

However, if I am logged out of the vault, then the password field is not focused when attempting to log in.

**Comment by sir-pinecone** [comment] 2022-10-21 16:17
I did some git bisecting and determined that this breaks in #3424 (commit https://github.com/bitwarden/clients/commit/2357957c). I'm going to try and find the cause, but I'm new to this codebase and this might take a while. If anyone else wants to fix it, go for it!

**Comment by sir-pinecone** [comment] 2022-10-21 16:30
This focus removal is the cause https://github.com/bitwarden/clients/pull/3424/files?diff=split&w=0#diff-f450baeaf39177825d2b0b5c7337551100b3860336913e69c7eded08fc874522L66-L68 

I'll try to make a PR with a fix.

**Comment by djsmith85** [comment] 2022-11-03 15:44
With the upcoming release (2022.11) some changes were made to the login-pages and login-flows. During this work, this issue got addressed across clients.

Kudos to @sir-pinecone and @max-programming for offering their help and providing PRs.

Closing this now.

**Closed by djsmith85** 2022-11-03 15:44 UTC
Labels: bug, browser, web

**Comment by warwickmm** [comment] 2022-12-15 17:46
@djsmith85 , with version 2022.12.0 if the email is auto-filled one still has to tab over to "continue" to proceed to the master password page.  Is it possible for the continue button to be focused so that one can just hit enter to navigate to the master password page?

Previously, one just needed to hit ctrl+shift+L and start typing their master password.  With the past few releases, there are more obstacles that one has to navigate through.

This is using the browser extension with Brave Version 1.46.140 Chromium: 108.0.5359.99 (Official Build) (64-bit).
