### ISSUE TITLE
Safari: Premium membership button in Settings crashes Bitwarden and causes the extension to hang in background.

### ISSUE THREAD

**Issue by eon-pixel** [bitwarden/clients#4876] opened 2023-02-26 22:41 UTC
### Steps To Reproduce

1. Open the Bitwarden extension while logged in.
2. Click on Settings.
3. Scroll down to the 'Premium membership' button under the Account section.
4. Click on the button, the extension will freeze.

### Expected Result

The button will open the membership page if the user does not already have an active subscription.

### Actual Result

The extension freezes and no longer opens until either force quit in Activity Monitor or the browser is quit and reopened. The process sits in the background, using 100% of the CPU according to Activity Monitor and heavily increases power usage.

### Screenshots or Videos

<img width="499" alt="1" src="https://user-images.githubusercontent.com/85057057/221441755-6ce06f87-bb77-4f84-b6d6-ed6a9680a587.png">

### Additional Context

I do not have an active Bitwarden Premium membership, so I'm not sure what happens if the current account has an active subscription.

### Operating System

macOS

### Operating System Version

macOS Monterey 12.6.3

### Web Browser

Safari

### Browser Version

15.6.1

### Build Version

2023.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment] 2023-02-27 08:54
Hi @eon-pixel,

Thank you for your report. This seems like a duplicate of this one (https://github.com/bitwarden/clients/issues/2267).
If you wish to add any further information, please feel free to do so in the GitHub report above; This issue will now be closed.


Thank you.

**Closed by SergeantConfused** 2023-02-27 08:54 UTC
Labels: bug, browser
