### ISSUE TITLE
Vault Not Locked on Firefox Extension after Configured Lock time has passed (Bitwarden Open on a New Window)

### ISSUE THREAD

**Issue by germanfidalgo** [bitwarden/clients#2496] opened 2022-04-07 20:19 UTC
### Steps To Reproduce

1. Go to the extension, provide master password and unlock vault
2. Go to Settings, an set waiting time to Lock Vault to a Minute
3. Select / Press "open in a new Window"
4. Wait for a Minute

### Expected Result

Vault locked after configured time has passed.

### Actual Result

Vault NOT locked after configured time has passed (all passwords exposed for indetermine time)

### Operating System

Windows

### Operating System Version

Windows 11

### Web Browser

Firefox

### Browser Version

Firefox 98.0.2 (64-bit)

### Build Version

1.57.0

**Comment by djsmith85** [comment] 2022-07-21 09:51
Closing this as duplicate of https://github.com/bitwarden/clients/issues/854

**Closed by djsmith85** 2022-07-21 09:51 UTC
Labels: bug, browser
