### ISSUE TITLE
Bitwarden fails to quit when shutting down Macbook

### ISSUE THREAD

**Issue by mateipruteanu** [bitwarden/clients#8423] opened 2024-03-21 11:37 UTC
### Steps To Reproduce

1. Have close to menu bar enabled in Bitwarden.
2. Close app to menu bar (so that it's still open in the background)
3. Shut down MacOS from the Apple menu 

### Expected Result

Bitwarden quits automatically and MacOS shuts down.

### Actual Result

MacOS stays on for about 15 seconds then displays a window saying that "Your Mac hasn't shut down because "Bitwarden" failed to quit. To continue shutting down, quit "Bitwarden""
Bitwarden cannot be quit with CMD + Q, so the only solution is to do Command-Option-Esc and then Force Quit it.

### Screenshots or Videos

<img width="483" alt="Screenshot 2024-03-21 at 13 29 42" src="https://github.com/bitwarden/clients/assets/35728927/5ae1c496-8e5a-4c4c-9bff-da7337abf203">

### Operating System

macOS

### Operating System Version

Sonoma 14.3.1

### Installation method

Mac App Store

### Build Version

2024.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-03-21 11:42
Duplicate of https://github.com/bitwarden/clients/issues/8365

**Comment by djsmith85** [comment] 2024-03-21 11:42
Hi @mateipruteanu !

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/8365

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2024-03-21 11:42 UTC
Labels: bug, desktop
