### ISSUE TITLE
Organization policy for generator pass phrase not respected in desktop app

### ISSUE THREAD

**Issue by CThompso3** [bitwarden/clients#7604] opened 2024-01-18 16:19 UTC
### Steps To Reproduce

1. Turn on organization policy to force generator pass phrase to the following settings
![image](https://github.com/bitwarden/clients/assets/26146315/5abd907e-4901-4a87-801f-651a3a146ce1)
2. Log in to desktop app with organization account and open generator
3. Generator pass phrase shows as all lower case and options to include uppercase and number cannot be selected
![image](https://github.com/bitwarden/clients/assets/26146315/9442895a-a608-44a5-80fc-410a638c32c3)

Error occurs on Windows 11
Bitwarden Desktop app info:
- Version: 2024.1.0
- Shell: 27.2.0
- Renderer: 118.0.5993.159
- Node: 18.17.1
- Architecture x64

### Expected Result

Expect generator on desktop app to produce pass phrase in accordance to organization policy to include capitalization and number.

### Actual Result

Generator pass phrase is all lower case and missing required items (capitalization and number).

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment] 2024-01-18 16:34
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/clients/issues/7572. 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by jtodddd** 2024-01-18 16:34 UTC
Labels: bug, desktop

**Comment by CThompso3** [comment] 2024-01-18 18:27
That bug is specific to the browser extension. This is for the desktop app. His issue is also slightly different as it has to do with toggling back and forth between pass phrase and password. In this issue, the pass phrase never works correctly and toggling doesn't affect it one way or another.
