### ISSUE TITLE
Downloading the vault data is not storing any file

### ISSUE THREAD

**Issue by luckydonald** [bitwarden/clients#7430] opened 2024-01-03 03:36 UTC
### Steps To Reproduce

1. Open Extension
2. Go settings
3. click Export Vault...
4. Enter password
5. confirm it's unencrypted.

### Expected Result

A file will be saved.

### Actual Result

It does nothing, it only goes back to the settings main menu.

### Additional Context

There's no new output in the console when this happens.
There's no web requests in the console when this happens.

### Operating System

Windows

### Operating System Version

10

### Web Browser

Vivaldi

### Build Version

6.5.3206.42 (Stable channel) (64-bit) 

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by luckydonald** [comment] 2024-01-03 03:41
This is a huge issue, as with the most recent update it can't longer communicate with the selfhosted server, and therefore saved passwords may be lost with logging out.

**Comment by sammbw** [comment] 2024-01-03 05:18
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Regarding the vault contents - if you log in to your self-hosted environment via the web vault, you should be able to create an export there - ideally the extension will not allow you to create new vault items while it doesn't have a connection to the server.

Thanks once again!

**Comment by djsmith85** [comment] 2024-01-03 11:10
Duplicate of https://github.com/bitwarden/clients/issues/1885

**Comment by djsmith85** [comment] 2024-01-03 11:10
Hi @luckydonald,

this is unfortunately a known issue within Vivaldi. You'll need to popout the extension in a new window. Please see https://github.com/bitwarden/clients/issues/1885 for details.

In regards to the extension not syncing: https://github.com/bitwarden/clients/issues/7243 is likely the issue, which has been addressed and will released soon with `2024.1`. 

Closing this now.

**Closed by djsmith85** 2024-01-03 11:10 UTC
Labels: bug, browser
