### ISSUE TITLE
Get Error message when the client has open

### ISSUE THREAD

**Issue by glomme** [bitwarden/clients#9883] opened 2024-06-30 12:11 UTC
### Steps To Reproduce

1. Open the client and look on the top
2. then you see the following error message:

### Expected Result

No error message only the search bar where you can search for passwords

### Actual Result

On top a error message:
Bitwardencdk-virtual-scroll-viewport{display:block;position:relative;transform:translateZ(0)}.cdk-virtual-scrollable{overflow:auto;will-change:scroll-position;contain:strict;-webkit-overflow-scrolling:touch}.cdk-virtual-scroll-content-wrapper{position:absolute;top:0;left:0;contain:content}[dir=rtl] .cdk-virtual-scroll-content-wrapper{right:0;left:auto}.cdk-virtual-scroll-orientation-horizontal .cdk-virtual-scroll-content-wrapper{min-height:100%}.cdk-virtual-scroll-orientation-horizontal .cdk-virtual-scroll-content-wrapper>dl:not([cdkVirtualFor]),.cdk-virtual-scroll-orientation-horizontal .cdk-virtual-scroll-content-wrapper>ol:not([cdkVirtualFor]),.cdk-virtual-scroll-orientation-horizontal .cdk-virtual-scroll-content-wrapper>table:not([cdkVirtualFor]),.cdk-virtual-scroll-orientation-horizontal .cdk-virtual-scroll-content-wrapper>ul:not([cdkVirtualFor]){padding-left:0;padding-right:0;margin-left:0;margin-right:0;border-left-width:0;border-right-width:0;outline:none}.cdk-virtual-scroll-orientation-vertical .cdk-virtual-scroll-content-wrapper{min-width:100%}.cdk-virtual-scroll-orientation-vertical .cdk-virtual-scroll-content-wrapper>dl:not([cdkVirtualFor]),.cdk-virtual-scroll-orientation-vertical .cdk-virtual-scroll-content-wrapper>ol:not([cdkVirtualFor]),.cdk-virtual-scroll-orientation-vertical .cdk-virtual-scroll-content-wrapper>table:not([cdkVirtualFor]),.cdk-virtual-scroll-orientation-vertical .cdk-virtual-scroll-content-wrapper>ul:not([cdkVirtualFor]){padding-top:0;padding-bottom:0;margin-top:0;margin-bottom:0;border-top-width:0;border-bottom-width:0;outline:none}.cdk-virtual-scroll-spacer{height:1px;transform-origin:0 0;flex:0 0 auto}[dir=rtl] .cdk-virtual-scroll-spacer{transform-origin:100% 0}

### Screenshots or Videos

![grafik](https://github.com/bitwarden/clients/assets/39823647/8afdc0f9-c59d-471d-bb95-5980d83fcdb3)

### Operating System

Windows

### Operating System Version

Windows 11 Pro 23H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

224.6.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment] 2024-07-01 01:47
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by popy2k14** [comment] 2024-08-31 16:54
Same issue here and fixed it.
I think it had todo with a mix of different versions (manually installed & winget).

@glomme is the issue just present on autostart?
And not when you start it manuall?

In my case, it was exactly that.
Autostartet on windows logon had this issue. About showd (2024-07-1 version).
After closing this and launching it from start menu, issue was gone and it showed version 2024-08-1.

I have used "autoruns" tool from microsoft and removed the autostart entry.
Closed all Bitwarden instances and processes and startet it manually.
Logon and in Setiing tick "Autostart on Logon".

This has done it for me.

Give it a shot.

**Closed** 2024-09-17 05:28 UTC
Labels: bug, desktop, needs-reply
