### ISSUE TITLE
Touch ID auth doesn't pop up on app start

### ISSUE THREAD

**Issue by lshigw** [bitwarden/clients#6271] opened 2023-09-13 04:22 UTC
### Steps To Reproduce

1. Go to 'Settings'
2. Check "Unlock with Touch ID"
3. Check "Ask for Touch ID on app start
4. Exit Bitwarden
5. Run Bitwarden

### Expected Result

The Touch ID auth window should pop up automatically on app start.

### Actual Result

No Touch ID auth window. It only shows the default log in window which requires the Master password. Have to manually click on "Unlock with Touch ID" to initiate Touch ID auth.

### Additional Context

I'm running Bitwarden on an Apple M1 Pro MacBook Pro 14.

### Operating System

macOS

### Operating System Version

macOS Sonoma 14.0 Beta

### Installation method

Mac App Store

### Build Version

Version 2023.8.3, Shell 24.1.1, Renderer 112.0.5615.50, Node 18.14.0, Arm64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2023-09-13 08:31
Hi @lshigw

Thank you for your report, it seems like it is a duplicate of this one [ https://github.com/bitwarden/clients/issues/6134].

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2023-09-13 08:31 UTC
Labels: bug, desktop
