### ISSUE TITLE
Non-existent error handling for missing Secret Provider, gets Bitwarden into numerous broken states

### ISSUE THREAD

**Issue by amarshall** [bitwarden/clients#8695] opened 2024-04-11 14:27 UTC
### Steps To Reproduce

1. Do not start any Secret Provider (e.g. gnome-keyring or similar), stop it if it is running
2. Start Bitwarden

### Expected Result

Works normally.

### Actual Result

Forgive the somewhat poor reproduction steps. I ended up in so many varied broken states that they were difficult to keep track of.

- (if just upgrading from < 2024.3.2): Loads but vault sync is silently broken without any indication until manual action is attempted, account switcher is also missing. I also managed to get into a state where even after making a Secret Provider available, Bitwarden continued to be broken in this way—resolving required deleting the appData.

- (if already upgraded to 2024.3.2 with a Secret Provider previously present, but now disabled): Long loading spinner, broken login screen style with broken images and black-on-black text.

Other states I ended up in:

- Bitwarden opens to quick spinner then blank screen
- With empty appData, Bitwarden shows login screen, but actually logging in causes infinite spinner on login button

### Additional Context

Overall, the implementation of libsecret interaction appears to be severely lacking in error handling and prone to getting into bad states when the Secret Provider is unavailable.

Related to https://github.com/bitwarden/clients/issues/8651, but while that issue focuses only on Snap, this is *not* a Snap-only issue, but rather a general Linux one.

Further, the release notes for 2024.3.2 and 2024.4.0 have no indication that there are new system dependencies, instead they simply indicate an uninformative “Bug fixes and small improvements”.

Plenty of logs with:

> Error: No password found
>
> Error: Failed to decode access token: JWT must have 3 parts

### Operating System

Linux

### Installation method

Other

### Build Version

2024.3.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment] 2024-04-11 14:40
Hi there,

This issue has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by justin-yan** [comment] 2024-04-12 06:07
I commented previously on #8651, but have applied the remediation suggested on that issue:

- I am on ubuntu 22.04 LTS, installed bitwarden with snap, and on 2024.4.0 with the permissions applied as requested in the resolution of #8651 

I am observing the issues above:

- attempting to trigger a sync results in "Syncing failed"
- attempting to create a new entry results in "Failed to decode access token: JWT must have 3 parts"
- any entry with 2FA codes saved will no longer generate TOTP codes, and instead says "Premium subscription required" (even though I have such a subscription)

**Comment by trmartin4** [comment] 2024-04-29 21:16
@amarshall This appears to be a duplicate of https://github.com/bitwarden/clients/issues/8651, which we are using to track and provide updates on the issues experienced with the Linux client without a Secret Provider in place.  

As @justin-yan mentioned, we have provided a solution for snap deployments, but that solution is not consistent and the scope of https://github.com/bitwarden/clients/issues/8651 has been expanded to include issues in general with the absence of a Secret Provider on any distro.

We are currently working on a solution that will allow the client to detect and downgrade from secure storage if a provider is not in place, and updates in that regard will be on https://github.com/bitwarden/clients/issues/8651. 

If you feel as if this is a separate issue, please feel free to re-open.

**Closed by trmartin4** 2024-04-29 21:16 UTC
Labels: bug, desktop
