### ISSUE TITLE
Usability issue: Update dialogue pops up during password input

### ISSUE THREAD

**Issue by davidmy** [bitwarden/clients#3728] opened 2022-10-09 11:17 UTC
### Steps To Reproduce

With an un-updated Bitwarden desktop client:

1. Start Bitwarden desktop client
2. Begin entering Master Password
3. Update dialogue box pops up, stealing keyboard focus

### Expected Result

Focus on the Master Password textbox should not be interrupted during user input

The update prompt should either come before the Mater Password prompt, or after, or somewhere else in the GUI.

### Actual Result

Update dialogue steals focus, capturing keystrokes meant for the master password input

### Operating System

Windows

### Operating System Version

Windows 10

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.9.1 (after update)

**Comment by Hinton** [comment] 2022-10-10 07:54
Duplicate of https://github.com/bitwarden/clients/issues/2608

**Closed by Hinton** 2022-10-10 07:54 UTC
Labels: bug, desktop
