### ISSUE TITLE
RTL desktop client my account elements overlapping

### ISSUE THREAD

**Issue by salamwaddah** [bitwarden/clients#10357] opened 2024-08-01 06:27 UTC
### Steps To Reproduce

1. Change MacOS language to Arabic (RTL language)
2. Open Bitwarden client
3. Observe my account menu

### Expected Result

My account menu to be clearly visible and not hidden behind OS buttons

### Actual Result

MacOS window button is overlapping my account menu

### Screenshots or Videos

![bit ar](https://github.com/user-attachments/assets/eb91fa1e-5fb9-4f55-9635-ab1e328fafaf)

### Operating System

macOS

### Operating System Version

14.5

### Installation method

Direct Download (from bitwarden.com)

### Build Version

27455

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-08-01 07:25
Duplicate of https://github.com/bitwarden/clients/issues/8170

**Comment by djsmith85** [comment] 2024-08-01 07:25
Hi @salamwaddah !

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/8170

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2024-08-01 07:25 UTC
Labels: bug, desktop
