### ISSUE TITLE
Log in is OK, but the app in loop and can not show or load data. OS Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by zydmohd** [bitwarden/clients#8994] opened 2024-05-01 04:00 UTC
### Steps To Reproduce

4. Click on '...'

### Expected Result

The app should show my vault data after success log in

### Actual Result

circle looping inside the app after log in

### Screenshots or Videos

![Screenshot from 2024-05-01 11-58-36](https://github.com/bitwarden/clients/assets/93226542/af4a46f6-7dc3-4405-8603-ba2be5f991f1)
![Screenshot from 2024-05-01 11-58-36](https://github.com/bitwarden/clients/assets/93226542/5873b0d6-bff7-4f5f-8755-2e0554add0b8)

### Operating System

Linux

### Operating System Version

Ubuntu 24.04 LTS

### Installation method

Snap

### Build Version

2024.4.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by dcorrea-wtb** [comment] 2024-05-01 12:02
This happens also in .deb installation

**Comment by PadreAdamo** [comment] 2024-05-02 02:14
This occurs on OpenSUSE Tumbleweed via Flatpak, Official Repo, and AppImage (direct from Bitwarden). This was not present in PopOS.

**Comment by Adedamola-Aina** [comment] 2024-05-02 14:47
Hi @PadreAdamo 

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by lorenzodefranceschi** [comment] 2024-05-02 14:58
Hi,
it happens to me too, but not to others in the same organisation.
As of today it no longer loads endlessly but shows me nothing in the organisation.

From the web it works correctly

**Comment by dcorrea-wtb** [comment] 2024-05-02 15:54
Version 2024.4.1 works, previous version remains loaded
![image](https://github.com/bitwarden/clients/assets/113372056/e8d6e5f1-7f1d-4bec-93a8-c403d0d14fc3)

Snapcraft version is 2024.4.0.
![image](https://github.com/bitwarden/clients/assets/113372056/e92821bb-0fd7-451c-9415-cb6d426243e0)

**Comment by PadreAdamo** [comment] 2024-05-02 23:47
> This occurs on OpenSUSE Tumbleweed via Flatpak, Official Repo, and AppImage (direct from Bitwarden). This was not present in PopOS.

19:47:03.750 › State version: 48
19:47:03.754 › Migrator MinVersionMigrator (to version 3) should migrate: false - up
19:47:03.755 › Migrator RemoveEverBeenUnlockedMigrator (to version 4) should migrate: false - up
19:47:03.755 › Migrator AddKeyTypeToOrgKeysMigrator (to version 5) should migrate: false - up
19:47:03.755 › Migrator RemoveLegacyEtmKeyMigrator (to version 6) should migrate: false - up
19:47:03.755 › Migrator MoveBiometricAutoPromptToAccount (to version 7) should migrate: false - up
19:47:03.756 › Migrator MoveStateVersionMigrator (to version 8) should migrate: false - up
19:47:03.756 › Migrator MoveBrowserSettingsToGlobal (to version 9) should migrate: false - up
19:47:03.756 › Migrator EverHadUserKeyMigrator (to version 10) should migrate: false - up
19:47:03.756 › Migrator OrganizationKeyMigrator (to version 11) should migrate: false - up
19:47:03.757 › Migrator MoveEnvironmentStateToProviders (to version 12) should migrate: false - up
19:47:03.757 › Migrator ProviderKeyMigrator (to version 13) should migrate: false - up
19:47:03.757 › Migrator MoveBiometricClientKeyHalfToStateProviders (to version 14) should migrate: false - up
19:47:03.757 › Migrator FolderMigrator (to version 15) should migrate: false - up
19:47:03.757 › Migrator LastSyncMigrator (to version 16) should migrate: false - up
19:47:03.757 › Migrator EnablePasskeysMigrator (to version 17) should migrate: false - up
19:47:03.757 › Migrator AutofillSettingsKeyMigrator (to version 18) should migrate: false - up
19:47:03.758 › Migrator RequirePasswordOnStartMigrator (to version 19) should migrate: false - up
19:47:03.758 › Migrator PrivateKeyMigrator (to version 20) should migrate: false - up
19:47:03.758 › Migrator CollectionMigrator (to version 21) should migrate: false - up
19:47:03.758 › Migrator CollapsedGroupingsMigrator (to version 22) should migrate: false - up
19:47:03.758 › Migrator MoveBiometricPromptsToStateProviders (to version 23) should migrate: false - up
19:47:03.758 › Migrator SmOnboardingTasksMigrator (to version 24) should migrate: false - up
19:47:03.758 › Migrator ClearClipboardDelayMigrator (to version 25) should migrate: false - up
19:47:03.758 › Migrator RevertLastSyncMigrator (to version 26) should migrate: false - up
19:47:03.759 › Migrator BadgeSettingsMigrator (to version 27) should migrate: false - up
19:47:03.759 › Migrator MoveBiometricUnlockToStateProviders (to version 28) should migrate: false - up
19:47:03.759 › Migrator UserNotificationSettingsKeyMigrator (to version 29) should migrate: false - up
19:47:03.759 › Migrator PolicyMigrator (to version 30) should migrate: false - up
19:47:03.759 › Migrator EnableContextMenuMigrator (to version 31) should migrate: false - up
19:47:03.759 › Migrator PreferredLanguageMigrator (to version 32) should migrate: false - up
19:47:03.759 › Migrator AppIdMigrator (to version 33) should migrate: false - up
19:47:03.759 › Migrator DomainSettingsMigrator (to version 34) should migrate: false - up
19:47:03.760 › Migrator MoveThemeToStateProviderMigrator (to version 35) should migrate: false - up
19:47:03.760 › Migrator VaultSettingsKeyMigrator (to version 36) should migrate: false - up
19:47:03.760 › Migrator AvatarColorMigrator (to version 37) should migrate: false - up
19:47:03.760 › Migrator TokenServiceStateProviderMigrator (to version 38) should migrate: false - up
19:47:03.760 › Migrator MoveBillingAccountProfileMigrator (to version 39) should migrate: false - up
19:47:03.760 › Migrator OrganizationMigrator (to version 40) should migrate: false - up
19:47:03.760 › Migrator EventCollectionMigrator (to version 41) should migrate: false - up
19:47:03.761 › Migrator EnableFaviconMigrator (to version 42) should migrate: false - up
19:47:03.761 › Migrator AutoConfirmFingerPrintsMigrator (to version 43) should migrate: false - up
19:47:03.761 › Migrator UserDecryptionOptionsMigrator (to version 44) should migrate: false - up
19:47:03.761 › Migrator MergeEnvironmentState (to version 45) should migrate: false - up
19:47:03.761 › Migrator DeleteBiometricPromptCancelledData (to version 46) should migrate: false - up
19:47:03.761 › Migrator MoveDesktopSettingsMigrator (to version 47) should migrate: false - up
19:47:03.761 › Migrator MoveDdgToStateProviderMigrator (to version 48) should migrate: false - up
19:47:05.060 › State version: 48
19:47:05.071 › Error: The name org.freedesktop.secrets was not provided by any .service files
19:47:05.076 › Error: The name org.freedesktop.secrets was not provided by any .service files
19:47:05.084 › Error: The name org.freedesktop.secrets was not provided by any .service files
19:47:05.084 › Error: The name org.freedesktop.secrets was not provided by any .service files
19:47:05.101 › Error: The name org.freedesktop.secrets was not provided by any .service files
19:47:05.101 › Error: The name org.freedesktop.secrets was not provided by any .service files
19:47:05.110 › Error: The name org.freedesktop.secrets was not provided by any .service files
19:47:05.137 › Error: The name org.freedesktop.secrets was not provided by any .service files
19:47:05.138 › Error: The name org.freedesktop.secrets was not provided by any .service files
19:47:05.138 › Error: The name org.freedesktop.secrets was not provided by any .service files
19:47:05.148 › Error: The name org.freedesktop.secrets was not provided by any .service files
19:47:05.149 › Error: The name org.freedesktop.secrets was not provided by any .service files
19:47:05.156 › Error: The name org.freedesktop.secrets was not provided by any .service files
19:47:05.161 › Error: The name org.freedesktop.secrets was not provided by any .service files
19:47:05.162 › Unable to fetch ServerConfig: Failed to decode access token: JWT must have 3 parts
19:47:05.163 › Error: The name org.freedesktop.secrets was not provided by any .service files
19:47:05.168 › Error: The name org.freedesktop.secrets was not provided by any .service files
19:47:05.180 › Error: The name org.freedesktop.secrets was not provided by any .service files
19:47:05.193 › Error: The name org.freedesktop.secrets was not provided by any .service files
19:47:06.131 › Error: The name org.freedesktop.secrets was not provided by any .service files
19:47:06.140 › Error: The name org.freedesktop.secrets was not provided by any .service files
19:47:06.148 › Error: The name org.freedesktop.secrets was not provided by any .service files
(node:15596) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'setContextMenu')
    at TrayMain.updateContextMenu (/usr/lib64/bitwarden/main.js:87066:23)
    at MessagingMain.updateTrayMenu (/usr/lib64/bitwarden/main.js:86582:28)
    at MessagingMain.onMessage (/usr/lib64/bitwarden/main.js:86508:22)
    at MessagingMain.<anonymous> (/usr/lib64/bitwarden/main.js:86498:155)
    at Generator.next (<anonymous>)
    at /usr/lib64/bitwarden/main.js:86475:71
    at new Promise (<anonymous>)
    at messaging_main_awaiter (/usr/lib64/bitwarden/main.js:86471:12)
    at IpcMainImpl.<anonymous> (/usr/lib64/bitwarden/main.js:86498:83)
    at IpcMainImpl.emit (node:events:514:28)
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:15596) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
19:47:08.117 › Error: The name org.freedesktop.secrets was not provided by any .service files
19:47:08.126 › Error: The name org.freedesktop.secrets was not provided by any .service files
19:47:10.834 › Error: The name org.freedesktop.secrets was not provided by any .service files
19:47:10.842 › Error: The name org.freedesktop.secrets was not provided by any .service files
19:47:10.848 › Error: The name org.freedesktop.secrets was not provided by any .service files
19:47:10.856 › Error: The name org.freedesktop.secrets was not provided by any .service files
19:47:10.863 › Error: The name org.freedesktop.secrets was not provided by any .service files
19:47:10.865 › Error: The name org.freedesktop.secrets was not provided by any .service files
19:47:10.871 › Error: The name org.freedesktop.secrets was not provided by any .service files
19:47:10.872 › Error: The name org.freedesktop.secrets was not provided by any .service files
19:47:10.876 › Error: The name org.freedesktop.secrets was not provided by any .service files
19:47:10.890 › Error: The name org.freedesktop.secrets was not provided by any .service files
19:47:10.918 › Error: The name org.freedesktop.secrets was not provided by any .service files
19:47:10.919 › Error: The name org.freedesktop.secrets was not provided by any .service files
(node:15596) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'setContextMenu')
    at TrayMain.updateContextMenu (/usr/lib64/bitwarden/main.js:87066:23)
    at MessagingMain.updateTrayMenu (/usr/lib64/bitwarden/main.js:86582:28)
    at MessagingMain.onMessage (/usr/lib64/bitwarden/main.js:86508:22)
    at MessagingMain.<anonymous> (/usr/lib64/bitwarden/main.js:86498:155)
    at Generator.next (<anonymous>)
    at /usr/lib64/bitwarden/main.js:86475:71
    at new Promise (<anonymous>)
    at messaging_main_awaiter (/usr/lib64/bitwarden/main.js:86471:12)
    at IpcMainImpl.<anonymous> (/usr/lib64/bitwarden/main.js:86498:83)
    at IpcMainImpl.emit (node:events:514:28)
(node:15596) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
19:47:10.938 › Error: The name org.freedesktop.secrets was not provided by any .service files
19:47:10.940 › Error: Failed to decode access token: JWT must have 3 parts
19:47:15.094 › Error: The name org.freedesktop.secrets was not provided by any .service files

**Comment by PadreAdamo** [comment] 2024-05-03 00:04
> This occurs on OpenSUSE Tumbleweed via Flatpak, Official Repo, and AppImage (direct from Bitwarden). This was not present in PopOS.

20:03:46.598 › State version: 48
20:03:46.641 › Migrator MinVersionMigrator (to version 3) should migrate: false - up
20:03:46.645 › Migrator RemoveEverBeenUnlockedMigrator (to version 4) should migrate: false - up
20:03:46.648 › Migrator AddKeyTypeToOrgKeysMigrator (to version 5) should migrate: false - up
20:03:46.650 › Migrator RemoveLegacyEtmKeyMigrator (to version 6) should migrate: false - up
20:03:46.653 › Migrator MoveBiometricAutoPromptToAccount (to version 7) should migrate: false - up
20:03:46.655 › Migrator MoveStateVersionMigrator (to version 8) should migrate: false - up
20:03:46.657 › Migrator MoveBrowserSettingsToGlobal (to version 9) should migrate: false - up
20:03:46.659 › Migrator EverHadUserKeyMigrator (to version 10) should migrate: false - up
20:03:46.662 › Migrator OrganizationKeyMigrator (to version 11) should migrate: false - up
20:03:46.664 › Migrator MoveEnvironmentStateToProviders (to version 12) should migrate: false - up
20:03:46.666 › Migrator ProviderKeyMigrator (to version 13) should migrate: false - up
20:03:46.667 › Migrator MoveBiometricClientKeyHalfToStateProviders (to version 14) should migrate: false - up
20:03:46.669 › Migrator FolderMigrator (to version 15) should migrate: false - up
20:03:46.670 › Migrator LastSyncMigrator (to version 16) should migrate: false - up
20:03:46.671 › Migrator EnablePasskeysMigrator (to version 17) should migrate: false - up
20:03:46.673 › Migrator AutofillSettingsKeyMigrator (to version 18) should migrate: false - up
20:03:46.674 › Migrator RequirePasswordOnStartMigrator (to version 19) should migrate: false - up
20:03:46.675 › Migrator PrivateKeyMigrator (to version 20) should migrate: false - up
20:03:46.677 › Migrator CollectionMigrator (to version 21) should migrate: false - up
20:03:46.678 › Migrator CollapsedGroupingsMigrator (to version 22) should migrate: false - up
20:03:46.680 › Migrator MoveBiometricPromptsToStateProviders (to version 23) should migrate: false - up
20:03:46.681 › Migrator SmOnboardingTasksMigrator (to version 24) should migrate: false - up
20:03:46.682 › Migrator ClearClipboardDelayMigrator (to version 25) should migrate: false - up
20:03:46.684 › Migrator RevertLastSyncMigrator (to version 26) should migrate: false - up
20:03:46.685 › Migrator BadgeSettingsMigrator (to version 27) should migrate: false - up
20:03:46.686 › Migrator MoveBiometricUnlockToStateProviders (to version 28) should migrate: false - up
20:03:46.688 › Migrator UserNotificationSettingsKeyMigrator (to version 29) should migrate: false - up
20:03:46.689 › Migrator PolicyMigrator (to version 30) should migrate: false - up
20:03:46.690 › Migrator EnableContextMenuMigrator (to version 31) should migrate: false - up
20:03:46.692 › Migrator PreferredLanguageMigrator (to version 32) should migrate: false - up
20:03:46.693 › Migrator AppIdMigrator (to version 33) should migrate: false - up
20:03:46.694 › Migrator DomainSettingsMigrator (to version 34) should migrate: false - up
20:03:46.695 › Migrator MoveThemeToStateProviderMigrator (to version 35) should migrate: false - up
20:03:46.696 › Migrator VaultSettingsKeyMigrator (to version 36) should migrate: false - up
20:03:46.698 › Migrator AvatarColorMigrator (to version 37) should migrate: false - up
20:03:46.699 › Migrator TokenServiceStateProviderMigrator (to version 38) should migrate: false - up
20:03:46.700 › Migrator MoveBillingAccountProfileMigrator (to version 39) should migrate: false - up
20:03:46.702 › Migrator OrganizationMigrator (to version 40) should migrate: false - up
20:03:46.703 › Migrator EventCollectionMigrator (to version 41) should migrate: false - up
20:03:46.704 › Migrator EnableFaviconMigrator (to version 42) should migrate: false - up
20:03:46.705 › Migrator AutoConfirmFingerPrintsMigrator (to version 43) should migrate: false - up
20:03:46.706 › Migrator UserDecryptionOptionsMigrator (to version 44) should migrate: false - up
20:03:46.708 › Migrator MergeEnvironmentState (to version 45) should migrate: false - up
20:03:46.709 › Migrator DeleteBiometricPromptCancelledData (to version 46) should migrate: false - up
20:03:46.710 › Migrator MoveDesktopSettingsMigrator (to version 47) should migrate: false - up
20:03:46.711 › Migrator MoveDdgToStateProviderMigrator (to version 48) should migrate: false - up
20:03:55.748 › State version: 48
20:03:55.823 › Error: The name org.freedesktop.secrets was not provided by any .service files
20:03:55.858 › Error: The name org.freedesktop.secrets was not provided by any .service files
20:03:55.916 › Error: The name org.freedesktop.secrets was not provided by any .service files
20:03:55.918 › Error: The name org.freedesktop.secrets was not provided by any .service files
20:03:56.047 › Error: The name org.freedesktop.secrets was not provided by any .service files
20:03:56.112 › Error: The name org.freedesktop.secrets was not provided by any .service files
20:03:56.115 › Error: The name org.freedesktop.secrets was not provided by any .service files
20:03:56.324 › Error: The name org.freedesktop.secrets was not provided by any .service files
20:03:56.327 › Error: The name org.freedesktop.secrets was not provided by any .service files
20:03:56.331 › Error: The name org.freedesktop.secrets was not provided by any .service files
20:03:56.384 › Error: The name org.freedesktop.secrets was not provided by any .service files
20:03:56.386 › Error: The name org.freedesktop.secrets was not provided by any .service files
20:03:56.419 › Error: The name org.freedesktop.secrets was not provided by any .service files
20:03:56.460 › Error: The name org.freedesktop.secrets was not provided by any .service files
20:03:56.462 › Error: The name org.freedesktop.secrets was not provided by any .service files
20:03:56.471 › Unable to fetch ServerConfig: Failed to decode access token: JWT must have 3 parts
20:03:56.490 › Error: The name org.freedesktop.secrets was not provided by any .service files
20:03:56.571 › Error: The name org.freedesktop.secrets was not provided by any .service files
20:03:56.807 › Error: The name org.freedesktop.secrets was not provided by any .service files
20:03:57.253 › Error: The name org.freedesktop.secrets was not provided by any .service files
20:03:57.281 › Error: The name org.freedesktop.secrets was not provided by any .service files
20:03:57.310 › Error: The name org.freedesktop.secrets was not provided by any .service files
(node:6571) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'setContextMenu')
    at TrayMain.updateContextMenu (/usr/lib64/bitwarden/main.js:87066:23)
    at MessagingMain.updateTrayMenu (/usr/lib64/bitwarden/main.js:86582:28)
    at MessagingMain.onMessage (/usr/lib64/bitwarden/main.js:86508:22)
    at MessagingMain.<anonymous> (/usr/lib64/bitwarden/main.js:86498:155)
    at Generator.next (<anonymous>)
    at /usr/lib64/bitwarden/main.js:86475:71
    at new Promise (<anonymous>)
    at messaging_main_awaiter (/usr/lib64/bitwarden/main.js:86471:12)
    at IpcMainImpl.<anonymous> (/usr/lib64/bitwarden/main.js:86498:83)
    at IpcMainImpl.emit (node:events:514:28)
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:6571) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
20:03:59.119 › Error: The name org.freedesktop.secrets was not provided by any .service files

**Comment by Jaymoon85** [comment] 2024-05-03 03:06
I'm getting the same problem with the Desktop client on Windows 11. I would love to revert to a previous version, but it keeps auto-updating to the latest, so I guess I'll stick to browser extension only for a while.

`Version 2024.4.1
Shell 28.2.8
Renderer 120.0.6099.291
Node 18.18.2
Architecture x64`

**Comment by Ogrekin** [comment] 2024-05-03 10:27
I have the same problem but i have tried the client in several distros or pretty much all of them..,. The client can work without any problem in one arch distro but not in another and same goes for debian, fedora and everyone in between.. Works in one and not in others and for now with peppermintOS it doesn't work but worked in picaOS just a day ago.. It almost feels like some distros are missing a package that makes it works in others..

**Comment by belonog** [comment] 2024-05-03 10:44
I've got this issue with Linux desktop app only (not a browser extension) after updating the KDF iteration value.

**Comment by SergeantConfused** [comment] 2024-05-05 12:28
Hello everyone,

Thank you all for your input.
1. If you're experiencing this with the Snap release of the Bitwarden desktop client for Linux, please follow the [instructions in the Help Centre](https://bitwarden.com/help/getting-started-desktop/#tab-3-6vQUhrVotSKFarA3cqyESG) to allow that client to access Secure Storage, and then log out and log in anew to address this behaviour.
2. If you're experiencing this in other releases of the Bitwarden desktop client for Linux, we are currently working on this matter and you can learn more about this topic in [this existing thread](https://github.com/bitwarden/clients/issues/8651). For the time being, please consider using the Bitwarden browser extension and/or the Bitwarden Web App.

I will now close this GitHub report as a duplicate of [#8651](https://github.com/bitwarden/clients/issues/8651). Please feel free to get in touch using the [contact form](https://bitwarden.com/help/), if you have any questions or concerns.

Thank you all again,

**Closed by SergeantConfused** 2024-05-05 12:28 UTC
Labels: bug, desktop

**Comment by diegonz** [comment] 2024-05-05 13:55
Same here while using snap package in Ubuntu 24.04 fresh install.
AppImage is working fine.
Deb is working fine too.
