### ISSUE TITLE
Bitwarden opens in private mode when using Firefox Containers

### ISSUE THREAD

**Issue by adhamfarrag** [bitwarden/clients#5251] opened 2023-04-21 00:35 UTC
### Steps To Reproduce

1. Assuming Bitwarden is still locked.
2. Download Firefox and install [Firefox multi-containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/) extension.
2. Create a container called `Bitwarden` for example.
3. Open Bitwarden website and from the right side of the address bar force opening the website using the container we previously created. 
![image](https://user-images.githubusercontent.com/23562275/233513688-22ec9c39-f957-4828-bc43-1ebf8294fd56.png)
4. Try to login to bitwarden using keyboard command.

### Expected Result

1. Authentication should not open in private mode and Bitwarden logs in normally and keeps being unlocked.

### Actual Result

1.  it will open the password inside the container and in private mode.
2. if you try to open any other website not in a container you still want to authenticate bitwarden.

### Operating System

macOS

### Web Browser

Firefox

### Build Version

2023.3.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SaabirahMohamed** [comment] 2023-04-21 08:46
Duplicate of #5115

**Comment by SaabirahMohamed** [comment] 2023-04-21 08:50
Hi there! @adhamfarrag 

Thank you for your report, it seems like it is a duplicate of this one 

(https://github.com/bitwarden/clients/issues/5115)If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed** 2023-04-26 15:33 UTC
Labels: bug, browser
