### ISSUE TITLE
Bitwarden extension influences EVERY single website negatively significantly, ranging from loading speed up to scroll behaviour, responsiveness and animations

### ISSUE THREAD

**Issue by rexon112** [bitwarden/clients#11077] opened 2024-09-16 13:04 UTC
### Steps To Reproduce

1. Install Browser Firefox, or Chrome, or Edge, or Brave, or Vivaldi, or literally any browser based on Chromium or Firefox
2. Install the Bitwarden web extension
3. Log in with your account (I have like 800 saved passwords)
4. It doesn't matter if autofill or any other related setting influencing websites is enabled
5. Start browsing some websites

### Expected Result

Website should load almost instantly over a <20ms ping 250 mbit/s internet connection. I am living right next to a Cloudflare DNS 1.1.1.1 data center.

### Actual Result

Every single website loads slower. From Google, up to social media websites like Reddit, Instagram, X up to websites like example.com. They all have a noticable delay when opening said web pages. Even scrolling and animation stutters sometimes

Additionally, javascript heavy websites like X, Instagram, Reddit etc. become extremely sluggish when interacting with buttons to the point where I prefer using my phone than my desktop browser. 

I tried changing EVERYTHING, from browser (Firefox, Chrome), DNS server (Cloudflare, Quad9, Google), disabling ALL other extensions other than Bitwarden, changing literally EVERY browser setting imaginable from blocking cookies, always HTTPS, secure DNS, different internet connections (Fiber, DSL, 5G), different internet providers, WIFI, Ethernet. It had no effect in the loading speed and sluggishness of websites.

Only when I disabled the Bitwarden extension websites suddenly started loading as expected again, regardless of any setting above.

This bothers me so much because I loathe unexpected side effects of software. I used Bitwarden because I needed a password manager which is cross device, cross platform and which mimics Chrome's autofill. Over time I got more and more upset with websites loading ridiculously slow and being sluggish, until I noticed it's the Bitwarden extension which is the problem.

So for me the Bitwarden browser extension is *unusable*. It interferes with my browsing experience like malware. This leaves me clueless as how to store passwords for web experience but that's a different topic. I am so done with password manager extensions behaving like malware and slowing down EVERY single website and EVERY single interaction on EVERY website

### Operating System

Windows

### Operating System Version

Windows 11 22631.4169

### Web Browser

Chrome, Microsoft Edge, Firefox, Brave, Vivaldi

### Browser Version

Firefox 130, Chrome 128, Microsoft Edge 128, Brave 128, Vivaldi 6.9.3447.37

### Build Version

2024.9.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cagonzalezcs** [comment] 2024-09-16 16:42
Hello @rexon112 

Thank you for this report. I empathize with the concerns you're bringing up and understand the frustration you're experiencing with our extension's impact on browser performance. Equally, your [concerns are shared by other users](https://github.com/bitwarden/clients/issues/8699) so we're aware of the problem at hand. 

These performance issues largely are the result of how Bitwarden handles the collection of page details for a given tab. In particular, the cost of capturing ShadowDOM elements within a web page is fairly significant, and the method we employ to ensure we capture DOM changes in a page involves that ShadowDOM capture process. 

We've [merged in some work](https://github.com/bitwarden/clients/pull/10816) recently that should improve the issues you're experiencing. [Details for those improvements can be found in this comment](https://github.com/bitwarden/clients/issues/8699#issuecomment-2321497281). 

The changes for this should be released in the October release of the extension, and I'm hoping that they relieve the issues you're experiencing. 

As this is a duplicate of other tickets, and we have a fix in `main`, I'll be closing this ticket. Please feel free to continue discussion within the ticket as necessary.

**Closed by cagonzalezcs** 2024-09-16 16:42 UTC
Labels: bug, browser
