### ISSUE TITLE
Vault password input goes out of focus while typing

### ISSUE THREAD

**Issue by catabozan** [bitwarden/clients#5657] opened 2023-06-22 17:28 UTC
### Steps To Reproduce

Setup:
1. Be logged in the bitwarden account
2. Your vault must be locked
3. Bitwarden desktop app out of date

Steps to reproduce:
1. Open the app
2. Start typing the password

### Expected Result

I expected the app to let me type the password for my vault without being interrupted by the modal window telling me to update the Bitwarden client. 

### Actual Result

While I'm typing the password for my vault a modal window appears telling me to update the Bitwarden desktop app. This causes the password input to go out of focus, I don't notice the modal window because I'm looking at my keyboard while I'm typing; so I have to re-enter my password after closing the modal window.

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.5.1 (i have already updated it to the latest version, I don't know what was the last version I had installled)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2023-06-23 13:51
Duplicate of https://github.com/bitwarden/clients/issues/2608

**Comment by djsmith85** [comment] 2023-06-23 13:51
@catabozan Thank you for the report. This is a duplicate of https://github.com/bitwarden/clients/issues/2608

Closing this now.

**Closed by djsmith85** 2023-06-23 13:51 UTC
Labels: bug, desktop
