### ISSUE TITLE
Collections Missing unless you switch ownership

### ISSUE THREAD

**Issue by Addman43** [bitwarden/clients#8449] opened 2024-03-22 16:17 UTC
### Steps To Reproduce

1. Go to a Collection in a vault
2. Click on 'Add'
3. Fill out credential info 
4. Click on 'Save' returns an error message indicating that there is 'No collections to List'
5. Switching ownership from one user/group to another and a back then causes collections to populate and allows you to save

### Expected Result

When adding a new entry into BW collections should populate to specify which collection you would like to add credentials to. 

### Actual Result

Instead it returns an error indicating "No collections to List" if I switch Ownership to my personal vault back to the group vault collections then populate. 

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-03-22 16:24
Duplicate of https://github.com/bitwarden/clients/issues/8258

**Comment by djsmith85** [comment] 2024-03-22 16:24
Hello @Addman43,

Thank you for this report. It seems like a duplicate of the https://github.com/bitwarden/clients/issues/8258 linked above.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This report will now be closed.

Kind regards,
Daniel

**Closed by djsmith85** 2024-03-22 16:24 UTC
Labels: bug, desktop
