### ISSUE TITLE
Grey, blank menus that crash the app on Ubuntu 22.04

### ISSUE THREAD

**Issue by ghost** [bitwarden/clients#3622] opened 2022-09-26 21:42 UTC
### Steps To Reproduce

1. Open app and log in
2. Click on 'Account' or 'Window' in the menubar

### Expected Result

A drop-down displays

### Actual Result

A blank, grey blob appears

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/34213592/192385799-48c1038d-45f6-4d40-b0e0-c44ebda71480.png)

### Operating System

Linux

### Operating System Version

Ubuntu 22.04

### Installation method

Snap

### Build Version

2022.9.1

**Comment by lcoogan** [comment] 2022-09-26 21:43
If I click again, the grey blob goes away. If I click too much or start alternating between them, the app freezes and then crashes.

**Comment by lcoogan** [comment] 2022-09-26 21:45
To further clarify, the other menubar items work fine

**Comment by lcoogan** [comment] 2022-09-26 21:51
After running the app from the terminal, I can see that this error message keeps being outputted:
`** Message: 22:49:07.706: Remote error from secret service: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.293" (uid=1000 pid=31378 comm="/snap/bitwarden/76/bitwarden --no-sandbox --enable" label="snap.bitwarden.bitwarden (enforce)") interface="org.freedesktop.Secret.Service" member="OpenSession" error name="(unset)" requested_reply="0" destination=":1.10" (uid=1000 pid=23222 comm="/usr/bin/gnome-keyring-daemon --daemonize --login " label="unconfined")`

**Comment by RomainLAU** [comment] 2023-02-09 20:55
Hey ! Actually I don't think the issue is linked to bitwarden as I have the same issue on a lot of applications (also on Ubuntu 22.04 LTS), like Skype, Brave, Slack, Figma, etc... I'm still open for solutions but it's not only on bitwarden...

**Comment by piquark6046** [comment] 2023-02-15 17:02
I experience that my desktop environment (Ubuntu 22.10 vanilla-gnome-desktop) is frozen when the mentioned behavior appears or i interact with BitWarden.

**Comment by johassl** [comment] 2023-04-18 07:00
Samem issue Ubuntu 20.04.6 LTS

**Comment by Krychaz** [comment] 2023-08-17 14:40
Hello there, 

I was unable to replicate this issue. Can you please confirm that you still experience it?

**Comment by piquark6046** [comment] 2023-08-17 14:52
Yes. I can still experience it.

<details><summary>Screenshot</summary>

![Screenshot from 2023-08-17 23-47-59](https://github.com/bitwarden/clients/assets/98787049/218606aa-23fe-48ca-bc66-d109b5ac097c)


</details>

**Comment by johassl** [comment] 2023-08-17 14:57
Same, I also still have that problem! My Bitwarden Version:

![Screenshot from 2023-08-17 16-56-11](https://github.com/bitwarden/clients/assets/7466320/6b22553b-574c-4ee6-adca-c09eaeada2bd)

**Comment by Krychaz** [comment] 2023-08-18 06:51
Hello,

I have passed this to our QA team for further investigation.

**Comment by TheNetworkGuy** [comment] 2023-09-02 14:19
Might help some users: i've had the same experience on a fresh installation of Ubuntu 22.04. I was able to fix the issue by installing the latest Nvidia drivers (https://help.ubuntu.com/community/NvidiaDriversInstallation)

**Comment by trmartin4** [comment] 2024-03-20 20:43
As this appears to be related to display drivers, we are closing this issue.  If you continue to experience Bitwarden-app-specific display problems, please re-open or report a new issue.

Thank you!

**Closed by trmartin4** 2024-03-20 20:43 UTC
Labels: bug, desktop
