### ISSUE TITLE
Brave browser extension problem

### ISSUE THREAD

**Issue by user00036** [bitwarden/clients#7993] opened 2024-02-18 16:34 UTC
### Steps To Reproduce

1. View a certain password
2. Click Edit
3.Change password

### Expected Result

The password can be changed without the password being visible or hidden.

### Actual Result

The original password must be visible to change the password

### Additional Context

The Windows client does not have this problem, but the browser extension has this problem.

### Operating System

Windows

### Operating System Version

windows11

### Web Browser

Brave

### Build Version

2024.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-02-19 10:15
Duplicate of https://github.com/bitwarden/clients/issues/7889

**Comment by djsmith85** [comment] 2024-02-19 10:16
Hi @user00036

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/clients/issues/7889.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2024-02-19 10:16 UTC
Labels: bug, browser
