### ISSUE TITLE
Repeatedly prompted to activate the Safari extension after updating the app

### ISSUE THREAD

**Issue by infinitepower18** [bitwarden/clients#12384] opened 2024-12-12 21:58 UTC
### Steps To Reproduce

1. Have a Safari window open
2. Update the Bitwarden app on the Mac App Store

### Expected Result

The app should update without any popups.

### Actual Result

After updating, I end up with 6 tabs telling me how to activate the extension.

### Screenshots or Videos

https://github.com/user-attachments/assets/a468fb59-610a-4567-9b0c-3b53ba201619

### Operating System

macOS

### Operating System Version

15.2

### Web Browser

Safari

### Browser Version

18.2

### Build Version

2024.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by BBGhub** [comment] 2024-12-13 02:08
Hi There,

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/11694

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This should be fixed in a coming update to the Bitwarden Extension.

This issue will now be closed.

Thanks!

**Closed by BBGhub** 2024-12-13 02:08 UTC
Labels: bug, browser
