### ISSUE TITLE
Update not completing despite being on latest version

### ISSUE THREAD

**Issue by RustinFerris** [bitwarden/clients#2996] opened 2022-06-29 08:19 UTC
### Steps To Reproduce

1. Go to 'Help'
2. Click on 'About Bitwarden'
3. Find Bitwarden installation directory
4. Right click on 'Bitwarden.exe'
5. Navigate to 'Properties'
6. Go on 'Details'
7. Look at 'File Version'

### Expected Result

Due to the update prompt on start up of the system, I'd expect the Version to be 2022.5.0. 

### Actual Result

It tells me the version to be 2022.5.1, though it prompts me to restart the application to update it to 2022.5.1 on the next start up. 
Looking at the file version it says for Bitwarden.exe it seems to not update but think it updated. 

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/46075180/176383941-6213b3db-4673-4710-9b44-467b8a2ca3d1.png)
![image](https://user-images.githubusercontent.com/46075180/176386129-fde409a5-9291-4161-98b7-3a9d81539e14.png)

### Operating System

Windows

### Operating System Version

Win10 Pro 64-bit 21H2 19044.1766

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.5.0/1

**Comment by cyberjack88** [comment] 2022-07-17 15:17
Every time I reboot windows 7 i am prompted to update Bitwarden which I do and it does and I check to see that latest version (22.6.2) is installed which it is and then the next time I reboot windows it asks me again, rinse and repeat.

**Comment by jxfreeman** [comment] 2022-07-25 16:39
Same issue as @cyberjack88 on 2022.6.2.

OS Name	Microsoft Windows 10 Pro
Version	10.0.19044 Build 19044

![image](https://user-images.githubusercontent.com/3515454/180829981-428aac0f-aace-48d2-aa31-c6fb31227fbf.png)

**Comment by dbosompem** [comment] 2022-08-03 11:53
Hi all, apologies you're facing this. The team will reproduce this internally and try resolve this. We will update once we have a resolution. Thanks!

**Comment by Hinton** [comment] 2022-08-04 09:39
Duplicate of #2571

**Closed by Hinton** 2022-08-04 09:39 UTC
Labels: bug, desktop

**Comment by cyberjack88** [comment] 2022-10-23 16:06
I am still getting a request to install an update every time it loads which then fails
________________________________

**Comment by djsmith85** [comment] 2022-10-24 09:38
Hi @cyberjack88, sorry to hear you are still experiencing this.

Did you follow the instructions [here ](https://github.com/bitwarden/clients/issues/2571#issuecomment-1123341411) and possibly [here ](https://github.com/bitwarden/clients/issues/2571#issuecomment-1205020576)on the linked issue #2571?

If I remember correctly, Bitwarden got installed twice, one was updated to the newer version when you clicked on the dialog, but the other Bitwarden application stayed on that version and thus would prompt you to update again.

I hope that resolves it, if for some reason it doesn't, feel free to contact us using our [Contact page](https://bitwarden.com/contact). You can include a link to this issue in the message content.
