### ISSUE TITLE
VAULT NOT SYNCING

### ISSUE THREAD

**Issue by SaptaDatta** [bitwarden/clients#9232] opened 2024-05-17 08:52 UTC
### Steps To Reproduce

1. Logging into the vault
2. Going to File>Sync Vault
3. Error is showing as "Syncing failed" in red box at top right corner
4. Similarly for creating a new entry, when pressing "Save" button, it is showing "Failed to decode access token: JWT must have 3 parts" in red box at top right corner.

### Expected Result

I have created quite a few entries on my mobile app of BitWarden. After selecting "Sync Vault" I expect them to appear on Desktop client too. Also similarly I expect to be able to create new entries through the desktop client.

### Actual Result

Going to File>Sync Vault. Error is showing as "Syncing failed" in red box at top right corner. Similarly for creating a new entry, when pressing "Save" button, it is showing "Failed to decode access token: JWT must have 3 parts" in red box at top right corner.

### Operating System

Linux

### Operating System Version

Ubuntu 22.04.4 LTS

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.4.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-05-17 09:23
Duplicate of https://github.com/bitwarden/clients/issues/8651

**Closed** 2024-05-17 09:23 UTC
Labels: bug, desktop
