### ISSUE TITLE
Safari extension jump-scrolling text to top of extension window when I type

### ISSUE THREAD

**Issue by fenster44** [bitwarden/clients#4162] opened 2022-12-01 14:53 UTC
### Steps To Reproduce

When I make any text inputs in the Safari extension, the content immediately jump-scrolls so that the text is at the very top of the window. This is frustrating because you lose track of where you are in the extension window.

https://user-images.githubusercontent.com/119391088/205085770-7b7eff1c-e029-481b-9b3a-d508dcba4cfe.mov

### Expected Result

Adding text in the extension window should not cause the window to scroll.

### Actual Result

Window scrolls when adding text.

### Operating System

macOS

### Web Browser

Safari

### Browser Version

16.1

### Build Version

18614.2.9.1.12

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by markywarky** [comment] 2023-01-17 06:44
> When I make any text inputs in the Safari extension, the content immediately jump-scrolls so that the text is at the very top of the window.

Thank you @fenster44 for logging this and creating a great demo video.

One of those small but annoying things I figured would be fixed promptly in the next maintenance release because it's so annoying and obvious, but it's been there for months now through a number of maintenance releases.

Please help, anyone with the knowledge and ability.

**Comment by dmedi011** [comment] 2023-02-16 22:46
Any update on this?

**Comment by dbosompem** [comment] 2023-02-22 10:19
Hi @dmedi011, apologies for the delay in reaching out. Unfortunately we haven't been able to look at this as the team has been pretty tight with some high priority and security items. I will pick this up and raise it internally after we've reproduced this, so we take a look. Thank you for your patience!

**Comment by fenster44** [comment] 2023-02-22 18:37
Thank you for the update! Looking forward to the resolution.

**Comment by sporkman** [comment] 2023-06-13 17:13
Still exists - this could be solved by simply making the extension's window larger as it is in Firefox and Chrome.

I have a video in this thread as well, wasn't sure where bug reports go...

https://community.bitwarden.com/t/safari-extension-allow-window-resize-and-autoscroll-issue/55350

Super frustrating when you try to actually use the extension to edit or add sites...

https://github.com/bitwarden/clients/assets/510750/f7827f52-17cc-4265-bdef-b0dd0406e8ba

**Comment by sporkman** [comment] 2023-06-16 20:36
Finally found where this is:

https://github.com/bitwarden/clients/blob/3e79dd245b446f79ed48fea19159036141eb2f34/src/popup/scss/environment.scss

3 years ago the extension was initially added (I think?) and it has this odd bit of CSS here that makes the extension's window ridiculously short. Was it designed for mobile and never updated for desktop Safari? No idea. But opening the web inspector and removing that rule sure fixes this issue. Sadly, I think this extension is signed and everything so you can't simply go in and edit the CSS.

Bigger picture, I don't get why this window can't be resized on-the-fly...

Out of curiosity, how hard is to build and then self-sign an extension? I hate to do that for a one-line CSS change, but that's the state of development with all this JS stuff these days. :)

**Comment by djsmith85** [comment] 2023-07-17 20:27
With https://github.com/bitwarden/clients/pull/5226 we removed the workaround for a upstream [webkit bug](https://github.com/bitwarden/clients/issues/1692#issuecomment-880977768) which was fixed for Safari 16.1 and higher. 

The changes got released with `2023.5.0`. Is the jump-scrolling still an issue on the full-size popup?

**Comment by sporkman** [comment] 2023-07-17 21:05
I'm not sure what "full-size" popup is, but I'm on 2023.5.1 and I still get the jump scroll.

Also is there any local build guide for people looking to help troubleshoot things to help out?

**Comment by djsmith85** [comment] 2023-07-17 21:45
@sporkman: The smaller popup was only shown on Safari, so full-size is the actual regular size popup shown on all other browsers, previous to the release of `2023.5` and obviously Safari 16.1 and higher.

Regarding setting up a dev environment:  Bitwarden's [contribution guidelines](https://contributing.bitwarden.com/) detail everything you'll need.

**Comment by ryanwatkinson** [comment] 2023-09-22 23:09
Still an issue with 2023.9.1

**Comment by ToGitOrNotToGit** [comment] 2023-09-28 23:59
How is this still an issue after 9 months?
BW Version 2023.9.0 (11993)
Safari Version 17.0 (18616.1.27.111.22, 18616)
macOS 13.5.2 (22G91)

**Comment by markywarky** [comment] 2023-11-27 02:48
> I caannot reproduce this on 2023.10.1 and Safari Version 17.1 (19616.2.9.11.7).

I agree this is resolved in Bitwarden 2023.10.1 and Safari 17.1 on macOS 14.1.1.
I wonder whether it was fixed by a Bitwarden update or an Apple update.

**Closed** 2023-11-27 10:20 UTC
Labels: bug, browser
