### ISSUE TITLE
Menu in system bar not showing after client start before unlocking the vault

### ISSUE THREAD

**Issue by PhilTb7** [bitwarden/clients#9250] opened 2024-05-19 10:13 UTC
### Steps To Reproduce

1. make sure the settings "close to menu bar" and "start to menu bar" are ON
2. quit the app
3. open some other app, like your browser
4. open bitwarden app again
5. click on the menu bar app icon to show the app window
6. menu bar does not update to the app menu - still shows the browser menu
7. even switching between windows does not update the menu to the app menu of Bitwarden

### Expected Result

after opening the Bitwarden app window, the menu bar should show the app menu entries

### Actual Result

the menu bar shows the app menu of the other app

### Screenshots or Videos

<img width="711" alt="Screenshot 2024-05-19 at 12 11 10" src="https://github.com/bitwarden/clients/assets/13349968/15321a12-de5c-49ff-b457-beffcfb74631">

### Additional Context

Seems to only be the case when the app is freshly started and the vault is still locked.

As soon as you unlock the vault the first time, the issue goes away. Even if you lock the vault again afterwards.
Also the issue is resolved if you switch to another app and then use the dock icon to switch back to the Bitwarden window instead of just clicking the window.

### Operating System

macOS

### Operating System Version

Sonoma 14.4.1

### Installation method

Mac App Store

### Build Version

2024.4.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment] 2024-05-19 11:45
Hello @PhilTb7,

Thank you for this report. This report seems to be a duplicate of this [GitHub report](https://github.com/bitwarden/clients/issues/5252); If there's anything you'd like to add, such as screenshots or video recordings of the screen, please feel free to add them to that existing GitHub report so that they'd be reviewed by the Bitwarden Engineering department.

This report will now be closed as a duplicate.

Thank you again,

**Closed by SergeantConfused** 2024-05-19 11:45 UTC
Labels: bug, desktop
