### ISSUE TITLE
`--cleanexit` and `--quiet` is ignored when no `data.json` exists yet

### ISSUE THREAD

**Issue by mfocko** [bitwarden/clients#6144] opened 2023-08-29 20:52 UTC
### Steps To Reproduce

1. Install the CLI
   (if already installed, remove the `data.json`)
2. Run `bw --cleanexit --quiet`

### Expected Result

Return code is 0, no output present.

### Actual Result

Return code is 1 and help is printed.

### Screenshots or Videos

Terminal scrollback:
```
mfocko@hertz ~ 
λ rm -rf ~/.config/Bitwarden\ CLI/data.json
mfocko@hertz ~ 
λ bw --cleanexit --quiet                   
Could not find data file, "/home/mfocko/.config/Bitwarden CLI/data.json"; creating it instead.
Usage: bw [options] [command]

Options:
  --pretty                                    Format output. JSON is tabbed with two spaces.
  --raw                                       Return raw output instead of a descriptive message.
  --response                                  Return a JSON formatted version of response output.
  --cleanexit                                 Exit with a success exit code (0) unless an error is thrown.
  --quiet                                     Don't return anything to stdout.
  --nointeraction                             Do not prompt for interactive user input.
  --session <session>                         Pass session key instead of reading from env.
  -v, --version                               output the version number
  -h, --help                                  display help for command

Commands:
  login [options] [email] [password]          Log into a user account.
  logout                                      Log out of the current user account.
  lock                                        Lock the vault and destroy active session keys.
  unlock [options] [password]                 Unlock the vault and return a new session key.
  sync [options]                              Pull the latest vault data from server.
  generate [options]                          Generate a password/passphrase.
  encode                                      Base 64 encode stdin.
  config [options] <setting> [value]          Configure CLI settings.
  update                                      Check for updates.
  completion [options]                        Generate shell completions.
  status                                      Show server, last sync, user information, and vault status.
  serve [options]                             Start a RESTful API webserver.
  list [options] <object>                     List an array of objects from the vault.
  get [options] <object> <id>                 Get an object from the vault.
  create [options] <object> [encodedJson]     Create an object in the vault.
  edit [options] <object> <id> [encodedJson]  Edit an object from the vault.
  delete [options] <object> <id>              Delete an object from the vault.
  restore <object> <id>                       Restores an object from the trash.
  move <id> <organizationId> [encodedJson]    Move an item to an organization.
  confirm [options] <object> <id>             Confirm an object to the organization.
  import [options] [format] [input]           Import vault data from a file.
  export [options]                            Export vault data to a CSV or JSON file.
  share <id> <organizationId> [encodedJson]   --DEPRECATED-- Move an item to an organization.
  send [options] <data>                       Work with Bitwarden sends. A Send can be quickly created using this command or
                                              subcommands can be used to fine-tune the Send
  receive [options] <url>                     Access a Bitwarden Send from a url
  help [command]                              display help for command

  Examples:

    bw login
    bw lock
    bw unlock myPassword321
    bw list --help
    bw list items --search google
    bw get item 99ee88d2-6046-4ea7-92c2-acac464b1412
    bw get password google.com
    echo '{"name":"My Folder"}' | bw encode
    bw create folder eyJuYW1lIjoiTXkgRm9sZGVyIn0K
    bw edit folder c7c7b60b-9c61-40f2-8ccd-36c49595ed72 eyJuYW1lIjoiTXkgRm9sZGVyMiJ9Cg==
    bw delete item 99ee88d2-6046-4ea7-92c2-acac464b1412
    bw generate -lusn --length 18
    bw config server https://bitwarden.example.com
    bw send -f ./file.ext
    bw send "text to send"
    echo "text to send" | bw send
    bw receive https://vault.bitwarden.com/#/send/rg3iuoS_Akm2gqy6ADRHmg/Ht7dYjsqjmgqUM3rjzZDSQ

mfocko@hertz ~ 
λ echo $?                                                                                                                     
1
mfocko@hertz ~ 
λ rm -rf ~/.config/Bitwarden\ CLI/data.json
mfocko@hertz ~ 
λ bw --version
Could not find data file, "/home/mfocko/.config/Bitwarden CLI/data.json"; creating it instead.
2023.8.2
mfocko@hertz ~ 
λ echo $?
0
mfocko@hertz ~ 
λ 
```

### Additional Context

It's very annoying because of Ansible and since `bw --version` does complain, but ends with `0`, something's not right…

### Operating System

Linux

### Operating System Version

openSUSE Tumbleweed

### Shell

Zsh

### Build Version

2023.8.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment] 2023-09-19 08:22
Hi there,

Thank you for your report! 

We were able to reproduce this issue, and we have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by audrey-jensen** [comment] 2023-10-04 19:58
Hi @mfocko!

I'm looking into this bug, and it appears that `bw` may be functioning as expected. Here's what I've found so far!

When I run `bw --quiet --cleanexit`, I am not giving bitwarden a command to run (e.g. in `bw login`, `login` is the command). The client emits a failure because a missing command is a error (outside of a few edge cases, one of which I rely on below). On my machine (macOS) this results in an error whether the configuration is present or not. 

This is further confirmed by the usage information being written to stderr. If you redirect stderr as follows `bw --quiet --cleanexit 2>/dev/null`, you'll see that the usage information is redirected. (The examples still print though. That might be a bug.)

When a command succeeds, it does so regardless of whether the config is present or not. Here's an example that emits success even after I delete the config: `bw --quiet --cleanexit --version`.

Does that match the behavior on your machine? If so, could you elaborate as to why you need `bw --quiet --cleanexit` to exit cleanly? There may be a command better suited to your usage. If not, I'll dive right into solutioning. 😄

**Comment by audrey-jensen** [comment] 2023-10-10 15:31
Hey @mfocko! Just wondering whether you could provide more information? If not, then I'll look into closing this ticket as "works as expected".

**Comment by mfocko** [comment] 2023-10-12 09:52
I guess it's fine… maybe a follow-up question, since this came out of dotfiles via Ansible…

I use BW-hosted instance for work and I have a self-hosted instance for private purposes. What would you suggest for setting this up? Right now, I create two `data.json` files with different names and then just link them.

**Comment by audrey-jensen** [comment] 2023-10-17 14:36
I'm not sure myself, but I'll reach out to our customer success and integration teams and see if I can find you an answer! :)

**Comment by audrey-jensen** [comment] 2023-10-17 15:31
@mfocko - Our success team said that you'll get better results by changing the configuration directory instead of renaming the file. There's some guidance available in [the official documentation](https://bitwarden.com/help/cli/#log-in-to-multiple-accounts).

If you need further support, I suggest you reach out on the [community forums](https://community.bitwarden.com/c/support/pm-ask-the-community/62).

**Closed by audrey-jensen** 2023-10-17 15:31 UTC
Labels: bug, good first issue, cli
