### ISSUE TITLE
Auto-fill should not fill in password fields marked with `autocomplete="new-password"`

### ISSUE THREAD

**Issue by threema-danilo** [bitwarden/clients#11507] opened 2024-10-11 13:29 UTC
### Steps To Reproduce

1. Go to https://gabrielfin.github.io/autocomplete-new-password.html
2. Add a password in Bitwarden
3. Autofill

### Expected Result

The "new-password" field should not be auto-filled, as per https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#new-password

### Actual Result

Both input fields are filled out. This seems to be a regression, because this feature was implemented already in https://github.com/bitwarden/clients/issues/842.

### Additional Context

Probably related: https://github.com/bitwarden/clients/issues/7964 

### Operating System

Linux

### Operating System Version

Arch Linux Latest

### Web Browser

Chrome

### Browser Version

129.0.6668.89

### Build Version

2024.10.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cagonzalezcs** [comment] 2024-10-11 16:18
As identified, this is a duplicate of https://github.com/bitwarden/clients/issues/7964

Closing this for now. Thanks for bring this to my attention though, we'll see what we can do about the issue.

**Closed by cagonzalezcs** 2024-10-11 16:18 UTC
Labels: bug, browser
