### ISSUE TITLE
With the extension locked, it asks me to save a password that is already saved.

### ISSUE THREAD

**Issue by jasimancas** [bitwarden/clients#2242] opened 2021-12-21 18:48 UTC
### Steps To Reproduce

1. Save credentials
2. Lock extension
3. log out and relogin in the web

### Expected Result

Do not ask for the password as I have already saved it.

### Actual Result

Save Credentials banner

### Operating System

Windows

### Operating System Version

11

### Web Browser

Microsoft Edge

### Browser Version

96.0

### Build Version

1.55.0

**Comment by r7l** [comment] 2021-12-23 11:35
Can confirm this issue on Chrome even if **Disable Add Login Notification** option is checked in settings. It does work as expected once i am logged in.

**Comment by djsmith85** [comment] 2021-12-23 11:54
@r7l That the **Disable Login Notification** setting is not respected with a locked vault was indeed a bug, which I addressed here: https://github.com/bitwarden/browser/pull/2225. 

The fix will be rolled out in the next release.

**Comment by jasimancas** [comment] 2021-12-23 12:01
I want to get the notification to save credentials but only if they are NOT already saved, regardless of whether or not the vault is locked or not.

**Comment by patrickhlauke** [comment] 2022-01-02 08:37
you likely don't want to leak information when the vault is locked (i.e. giving a clue about whether or not there's an entry for the current site in the locked vault). however, i'd strongly favour replacing the "do you want to save..." notification with something like a "unlock your vault to save these credentials" type message instead (and somehow remembering the information so that when the user *does* unlock the vault, and it was indeed a site that wasn't stored yet, it re-prompts the user to save it)

**Comment by patrickhlauke** [comment] 2022-01-02 08:39
incidentally, the current behaviour always confuses my wife because she often forgets to unlock the vault the first time around, and then wonders why she keeps getting prompted. (not helped by the fact that she then also gets confused when/if chrome itself brings up its own "do you want to save these credentials" dialog)

**Comment by r7l** [comment] 2022-01-02 13:28
I haven't looked into the internals of this extension. But i would expect it not to be able to know about the content of the vault if it's locked. So the only way to work with locked vaults, should be a global "Ask to save ..." setting like it's already implemented.

**Comment by patrickhlauke** [comment] 2022-01-02 13:39
it should basically not offer to save when the vault is locked, and instead bring up a notification that the user needs to unlock the vault first

**Comment by jasimancas** [comment] 2022-01-03 13:52
I mean, I should unlock the vault when I start the browser and remove the automatic locking option after X minutes, right?
As far as I can see, there is no option when I click the eye to view the password (within the extension) to ask me for biometric authentication (I have it configured), it would be nice to be able to leave the vault unlocked without being in danger of someone accessing my computer being able to see the password.

**Comment by longzheng** [comment] 2022-01-11 02:15
> @r7l That the **Disable Login Notification** setting is not respected with a locked vault was indeed a bug, which I addressed here: #2225.
> 
> The fix will be rolled out in the next release.

@djsmith85 any ideas when the next release will be published to Chrome?

**Comment by djsmith85** [comment] 2022-01-11 14:29
longzheng the next release is scheduled for beginning of February.

**Comment by timkgh** [comment] 2022-01-11 22:15
When clicking on the "Never" answer in the prompt, what setting is that supposed to change? Does it mean never for this site or never for any sites? Where does it record the answer because that doesn't seem to work either when the vault is locked.

**Comment by longzheng** [comment] 2022-01-11 22:29
> When clicking on the "Never" answer in the prompt, what setting is that supposed to change? Does it mean never for this site or never for any sites? Where does it record the answer because that doesn't seem to work either when the vault is locked.

Currently when the vault is locked there is a bug, so it is always shown. (Fixed in next release as indicated above)

The actual setting that should be configured is "Disable add login notification" in "Options".

![image](https://user-images.githubusercontent.com/484912/149031518-71ea8dba-7daf-4b3a-a307-0d2977dab7c5.png)

**Comment by timkgh** [comment] 2022-01-11 22:31
OK but I'd still like to know what Never means and where it records that answer.

**Comment by longzheng** [comment] 2022-01-11 22:34
> OK but I'd still like to know what Never means and where it records that answer.

I just skimmed through the code
https://github.com/bitwarden/browser/blob/8fe821b9a3f9728bcb02d607ca75add468d380c1/src/notification/bar.js#L71-L76
https://github.com/bitwarden/browser/blob/8fe821b9a3f9728bcb02d607ca75add468d380c1/src/background/notification.background.ts#L109-L111
https://github.com/bitwarden/browser/blob/8fe821b9a3f9728bcb02d607ca75add468d380c1/src/background/notification.background.ts#L425-L446

It looks like it's "never for this domain" https://github.com/bitwarden/browser/blob/8fe821b9a3f9728bcb02d607ca75add468d380c1/src/background/notification.background.ts#L444

**Comment by timkgh** [comment] 2022-01-11 22:54
Ah it can be managed, but it looks like it's on a per extension basis, it does not get sync'ed across browsers :(
https://github.com/bitwarden/browser/pull/1376

**Comment by ccornici** [comment] 2022-01-14 21:02
Same here, I get notifications when the vault is locked, to save passwords, which are already saved....

**Comment by warmwhisky** [comment] 2022-03-03 19:37
> @longzheng the next release is scheduled for beginning of February.

Has a fix for this been released yet? I am still experiencing this issue.

**Comment by djsmith85** [comment] 2022-03-03 20:29
@warmwhisky The fix done with https://github.com/bitwarden/browser/pull/2225 had to do with the setting not being honored at all. Say a user had set that they do not want to get prompted for any new Login, then it would have still appeared. The setting applies regardless of the vault's lock-state. The fix mentioned was rolled out with the February release.

**Comment by djsmith85** [comment] 2022-03-03 20:29
I'll quote my own reply from https://community.bitwarden.com/t/disable-prompt-to-save-pw-when-bitwarden-is-locked/38764/12 which I posted to your thread earlier.

> Hi [@warmwhisky](https://community.bitwarden.com/u/warmwhisky),
> 
> I’m, sorry to hear you are having issues with this. I’ll try and shed some light on it.
> 
> This feature was built to prompt to save, on a locked vault, because especially new users would forget about unlocking their vault beforehand. Which also led to a lot of false reports found on: [Bitwarden does not prompt to save or update credentials · Issue #1620 · bitwarden/browser · GitHub](https://github.com/bitwarden/browser/issues/1620)
> 
> If the vault is locked all of your data is encrypted and there is no way for Bitwarden to know which sites you might have credentials saved for.
> 
> I’m assuming the reason you are seeing these save prompts are: A locked vault and manually entering your credentials to a website.
> 
> If you’d for example use the shortcut (Cmd/Ctrl+Shift+L) or the context-menu to trigger auto-fill it will prompt you to log-in on a separate tab, unlock the vault and auto-fill.
> As the vault is now unlocked and the credentials match an existing entry, no save-prompt is shown.
> 
> There is currently no setting to disable this functionality only for a locked vault. The setting mentioned earlier in this thread only disables all save or change password prompts.
> 
> If you are not entering your credentials manually and there is another reason for the prompt showing, then please detail all steps on the Github issue mentioned by [@not](https://community.bitwarden.com/u/not)
> 
> I hope this clears up some of the confusion.
> 
> Kind regards,
> Daniel

For everyone else experiencing this, please check if this resolved things up and if not please detail steps to reproduce as mentioned in my quote.

**Comment by warmwhisky** [comment] 2022-03-03 20:40
So am I correct in thinking that no matter what, the prompt to save the passwords will always show if you are locked and that is by design? The only way to stop it is to disable the prompt completely even when unlocked?

My steps are as follows.
1. Bitwarden is locked
2. Browse site where a saved password by Chrome is already filled
3. Login
4. Bitwarden prompts to save

**Comment by ccornici** [comment] 2022-03-04 08:36
I expect that the people working at bitwarden come up with smarter solutions rather than just saying "well it's by design deal with it".

Please implement a setting in the extension where users can disable the prompt if the vault is locked.

You can keep it enabled by default for your new users...

Now everyone is happy.

Or if you don't want to implement it yourself then at least give the OK to the community to implement it in a PR

**Comment by staszek998** [comment] 2022-04-02 06:48
@patrickhlauke, **would you** (or any other Bitwarden reviewer/contributor) **consider reviewing a PR consisting of a set of changes proposed by @ccornici** in the comment above? If so, I think I could try digging into the source code and prepare a solution - probably with @longzheng's help 😉

I'm asking before coding just to avoid wasting everybody's time.

**Comment by ccornici** [comment] 2022-04-28 07:27
![image](https://user-images.githubusercontent.com/15718751/165699927-677bff8d-d7d3-4b78-88f4-e5e33f213a8f.png)

**Comment by warmwhisky** [comment] 2022-04-28 07:49
I had to switch the timeout setting to "Never" to stop it continually popping up asking me to save a password that's already in my vault. Strangely Bitwarden warned me that its not entirely safe and "If you use this option you should ensure that you keep your device properly protected." But it would seem that bitwarden wants me permanently logged in anyway. So what is the best solution? 
1. Unlock the vault by signing in the moment I open my browser **which will mean it is unlocked all the time**
2. Never let it time out **which will mean it is unlocked all the time**

**Comment by ccornici** [comment] 2022-07-11 07:02
![image](https://user-images.githubusercontent.com/15718751/178207180-a491ae40-7d50-4ca9-8523-3a2d4b4e9cba.png)

**Comment by dbosompem** [comment] 2022-07-11 21:24
Hello @staszek998 , you can go ahead and open a PR for this, the team will make time and will surely review. @ccornici it's true that issue is pending, and we apologise for that. I'd pass it on to the team so they take a look at it. But if anyone wants to open a PR of this, it will be appreciated!

**Comment by staszek998** [comment] 2022-07-13 05:53
@dbosompem, thank's for letting me know! 💪🏻
Sadly, at this moment I'm pretty overloaded, but I'll keep this thread in mind and will come back to it when I'll have some free time.

**Comment by Amnesiac9** [comment] 2022-09-29 16:32
Still happening unfortunately, even if I click "never" save because I don't want it to bitwarden asks every time while locked, even though I already have credentials saved.

**Closed** 2023-01-27 09:36 UTC
Labels: bug, browser

**Comment by warmwhisky** [comment] 2023-02-08 11:30
@jasimancas @djsmith85 Is this completed or what as I am still seeing this issue. Not sure why you guys deflect on answering this. Maybe its a version lock issue?

**Comment by awfki** [comment] 2024-12-05 14:26
Two years later I have this issue in Edge and Chrome. If the extension is locked and there's a password field on the page it prompt me to save the password.  It's either already in BitWarden or saved elsewhere and that annoying little box sits there indefinitely.  Is there anything that can be done about it?

**Comment by crazedVic** [comment] 2025-05-12 16:19
Someone please fix this.  it's going to eventually be the reason i move to a different solution.   It's awful.
