### ISSUE TITLE
Reused Passwords Report bug?

### ISSUE THREAD

**Issue by BlueSky0237** [bitwarden/clients#4148] opened 2022-11-29 20:36 UTC
### Steps To Reproduce

When I access the resued passwords report there are online accounts showing as having "2 or 3 reused" passwords, but when I export the vault and look at all the passwords there are no duplicates, clones or instances where the password flagged as reused appears more than once for that one account

### Expected Result

I would NOT expect to see these accounts in the report because they have a very unique, randomly generated 20 charcter password that isn't use for any other accounts

### Actual Result

shows some of them as reused

### Operating System

Windows

### Operating System Version

11 PRO

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.10.1; server version 2022.11.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2022-11-30 15:47
Linking to the community discussion: https://community.bitwarden.com/t/reused-passwords-report/46428

**Comment by djsmith85** [comment] 2022-12-01 23:50
@BlueSky0237 Closing this, as the cause for the duplicates on the reports was identified in the community forums thread.

**Closed by djsmith85** 2022-12-01 23:50 UTC
Labels: bug, desktop
