### ISSUE TITLE
Browser extension not filling username/password fields

### ISSUE THREAD

**Issue by abulgher** [bitwarden/clients#11354] opened 2024-10-02 05:06 UTC
### Steps To Reproduce

Dear all,

I have been recently facing this issue with the Bitwarden browser extension. I am using Brave (Chrome) on Windows. The problem is unfortunately not always occurring making it the debug much more tedious. Restarting the browser is sometimes fixing the issue, but not necessarily always true. 

Here is the problem description.

1. Go to any page for which I have a saved loging. For example the github page here
2. In normal situation a small 1 should appear on the bitwarden extension logo, but there is nothing
3. Click on the bitwarden shield and the record corresponding to github login is shown. 
4. Click on the record and instead of filling in the authentication fields a red message appears saying that it was not possible to fill in the fields.
5. I can still copy paste the username and password to login. 

### Expected Result

The username and password fields should be automatically filled

### Actual Result

Got the error message shown in the screenshot attached

### Screenshots or Videos

![problem-bitwarden](https://github.com/user-attachments/assets/19e78561-5281-45ce-830b-a44d051bf0df)

### Operating System

Windows

### Operating System Version

Win10 22H2

### Web Browser

Brave

### Build Version

v1.70.119

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by JABirchall** [comment] 2024-10-02 10:21
This is a duplicate of https://github.com/bitwarden/clients/issues/10814

**Comment by cagonzalezcs** [comment] 2024-10-02 13:11
As mentioned previously, this is a duplicate issue that will be resolve with an upcoming update. 

Closing this thread

**Closed by cagonzalezcs** 2024-10-02 13:11 UTC
Labels: bug, browser
