### ISSUE TITLE
Does not prompt for touch ID

### ISSUE THREAD

**Issue by greylogan** [bitwarden/clients#7708] opened 2024-01-26 23:46 UTC
### Steps To Reproduce

Opening app does not prompt touch ID, I have to click the button to get it to ask for touch ID

### Expected Result

I expect it to do its job and prompt me for touch ID

### Actual Result

It won't request touch ID upon start of app
![Revenant 1](https://github.com/bitwarden/clients/assets/146689152/1095b91d-f427-4bf3-a9ad-b1668bbea1a7)
.

### Operating System

macOS

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment] 2024-01-28 17:46
Hi @greylogan,

Thank you for this report. It seems like it's a duplicate of [this one](https://github.com/bitwarden/clients/issues/6134) and there's progress on [this matter](https://github.com/bitwarden/clients/issues/6134#issuecomment-1847322441); If you wish to add any further information, such as screenshots or screen recordings, please feel free to do so at any time in that existing thread - our Engineering team will be happy to review them.

We use GitHub to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,

**Closed by SergeantConfused** 2024-01-28 17:46 UTC
Labels: bug, desktop
