### ISSUE TITLE
The Firefox extension window size appears too small.

### ISSUE THREAD

**Issue by Erd89** [bitwarden/clients#7206] opened 2023-12-13 15:56 UTC
### Steps To Reproduce

1. Log in to the extension
2. Use it normally

Important note is that the bug seems to reproduce only when the computer is connected to a 24" full-HD monitor therefore not Hidipi.
When connected to the personal monitor (27" 4k) during a working day the problem did not arise.

### Expected Result

I expect the size to remain fixed and not to suddenly shrink without allowing me to restore the size.

### Actual Result

By using the extension normally and then calling it to autocomplete the login forms in the various services, at a certain point the size of the extension window becomes smaller and it is no longer possible to restore it without restarting the browser.

Important note is that the bug seems to reproduce only when the computer is connected to a 24" full-HD monitor therefore not Hidipi.
When connected to the personal monitor (27" 4k) during a working day the problem did not arise.

### Screenshots or Videos

![immagine](https://github.com/bitwarden/clients/assets/68340121/ce8baee6-b2fe-4d06-897e-975f4d23bed7)

### Operating System

macOS

### Operating System Version

14.1.2 (23B92)

### Web Browser

Firefox

### Browser Version

120.0.1

### Build Version

2023.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment] 2023-12-19 14:53
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/1451 .

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by cbbit** 2023-12-19 14:53 UTC
Labels: bug, browser

**Comment by Erd89** [comment] 2023-12-19 15:19
> Hi there!
> 
> Thank you for your report, it seems like it is a duplicate of this one #1451 .
> 
> If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.
> 
> This issue will now be closed.
> 
> Thanks!

I hope it gets resolved because it makes it really difficult to use the extension and the problem is not related to the Firefox privacy setting.

**Comment by julienkosinski** [comment] 2024-01-05 18:17
I can reproduce this exact issue on Firefox on Wayland in my Fedora on KDE.
I cannot reproduce this size problem with widgets for other extensions, so I believe this might be a specific bug regarding Bitwarden Firefox Extension. I can confirm there's no working workaround with piracy settings.

I have to add that I use fractional scaling and KDE and that `widget.wayland.fractional-scale.enabled` is set to `false` (this is the default setting) as setting it to `true` make everything even worse. I can provide a screenshot with this setting on if needed but I'm not sure it's relevant.

@cbbit Could you reconsider your position on this issue? :)
