### ISSUE TITLE
Excluded domain / subdomain don't work - it always re-prompts to save a password

### ISSUE THREAD

**Issue by bjspi** [bitwarden/clients#7546] opened 2024-01-14 09:13 UTC
### Steps To Reproduce

1. Go to 'https://www.ib.dkb.de/banking'
2. Enter any data into the two input textfields
3. Click the Blue button "Anmelden"

Bitwarden will prompt to save the password (nevermind you entered a wrong one). If you click "Never for this page" - the URL gets added to excluded domains.

But if you start with (1) again, providing a random login again - you will be prompted again by Bitwarden to save the PW.

### Expected Result

Bitwarden should correctly consider the excluded domain to not prompt to ask the password again.
It actually happens on quite some pages for me.

### Actual Result

Bitwarden ALWAYS re-prompts to save the entered login-data.

### Operating System

Windows

### Operating System Version

11

### Web Browser

Chrome

### Browser Version

Latest (non-Beta) - but affected all previous versions as well

### Build Version

2023.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment] 2024-01-14 18:12
Hi @bjspi,

Thank you for your report. This seems to be a duplicate of [this](https://github.com/bitwarden/clients/issues/1641) and it was addressed in version [2024.1.0](https://bitwarden.com/help/releasenotes/); Please check if you're able to update the extension manually in Chrome.

I will now proceed and close this GitHub report; I thank you in advance for your understanding.

All the best,

**Closed by SergeantConfused** 2024-01-14 18:12 UTC
Labels: bug, browser

**Comment by bjspi** [comment] 2024-01-16 07:28
Thanks for the information - how to manually update it? It seems to not yet be pushed into the Chrome Extension Store - when is this planned!?

**Comment by SergeantConfused** [comment] 2024-01-16 18:01
Hi @bjspi,

Sure thing! 😊 In Chrome, you can right-click on the extension, click on (Manage extension), toggle (Developer mode) in the upper-right corner, and then you'd see an (Update) button in the upper left corner of the window which would allow you to manually update the extension. There is no need to manually install the extension via that link.

I hope this helps.
