### ISSUE TITLE
Login Screen loads then crashes

### ISSUE THREAD

**Issue by ShrugMcShrug** [bitwarden/clients#6599] opened 2023-10-16 22:23 UTC
### Steps To Reproduce

1. On a Debian/Ubuntu/PopOS machine open the Bitwarden client.
2. Begin to type credentials, client crashes, window goes black/blank.

### Expected Result

The login screen remains the same and I complete typing in credentials.

### Actual Result

As soon as I begin typing, the window removes the login boxes and I can only exit the window.

### Additional Context

I have all updated packages/flatpaks, etc...

### Operating System

Linux

### Operating System Version

Pop!_OS 22.04 LTS

### Installation method

Other

### Build Version

Version 2023.9.2 Shell 26.3.0 Renderer 116.0.5845.228 Node 18.16.1 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cswiger** [comment] 2023-10-16 22:42
Getting same issue - Ubuntu 

VERSION="20.04.6 LTS (Focal Fossa)"

Bitwarden:  Version 2023.9.2
Shell 26.3.0
Renderer 116.0.5845.228
Node 18.16.1
Architecture x64

**Comment by sammbw** [comment] 2023-10-16 23:21
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/clients/issues/6560

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by sammbw** 2023-10-16 23:21 UTC
Labels: bug, desktop
