### ISSUE TITLE
Syncing issue with Desktop app.

### ISSUE THREAD

**Issue by michaeleberly** [bitwarden/clients#7270] opened 2023-12-18 21:23 UTC
### Steps To Reproduce

Update credentials in vault via web browser.
Open desktop app and check credentials. (not updated)
Click file sync vault.

### Expected Result

Expected credentials in app to update to new credentials in vault.

### Actual Result

App displays syncing error in upper right corner and credentials not updated.

### Additional Context

This is happening on 2 separate windows machines. One is on Windows 11 and one is on Windows 10. IOS app seems to update properly.

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.12.0

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2023-12-18 21:47
Duplicate of #2472

**Comment by djsmith85** [comment] 2023-12-18 21:47
Hi @michaeleberly ,

Thank you for your report. This report seems like it is a duplicate of #2472.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This report will now be closed.

Thank you again

**Comment by Morse6690** [comment] 2023-12-18 21:47
I have exactly the same issue. Been happening for a few days now.
win11, v2023.12.0
I added an item in my mobile app which appears in my other mobile apps. But desktop refuses to sync even when manually triggered and shows the error.

**Closed by Morse6690** 2023-12-18 21:48 UTC
Labels: bug, desktop

**Comment by Morse6690** [comment] 2023-12-18 21:50
How can this be closer closed as a duplicate issue, when clearly this has been happening only for a few days?
The other issue was from years ago.

**Comment by djsmith85** [comment] 2023-12-18 21:51
Sorry @Morse6690, I had falsely linked the wrong issue number. Comments have been edited

**Comment by michaeleberly** [comment] 2023-12-18 21:56
Logging out and logging back in did fix this issue on Windows 11 app. I will test the Windows 10 machine as soon as I have opportunity. Thanks!

**Comment by Morse6690** [comment] 2023-12-19 02:04
No worries.
Logging out and in worked here too.

**Comment by PortgSelvadi** [comment] 2024-01-17 17:27
Hi,
I have this problem, too. Logging out and back into Bitwarden account works with the desktop app on macOS Sonoma (M1 and Intel tested). But I hope for a real fix and not just this workaround. It is annoying.
