### ISSUE TITLE
Blank message displayed in Zimbra when Bitwarden Apache2 module is ON

### ISSUE THREAD

**Issue by EmmJORT** [bitwarden/clients#9852] opened 2024-06-27 14:07 UTC
### Steps To Reproduce

Put Bitwarden Apache2 module ON, you can't see the mails content
Put it OFF, you can can see the content of mails
ON -> KO
OFF -> OK 
...

### Expected Result

See mails content when Bitwarden Apache2 module is ON

### Actual Result

Can't see the mails content when Bitwarden Apache2 module is ON

### Screenshots or Videos

![1](https://github.com/bitwarden/clients/assets/173906792/ac15760b-2115-4ca8-8f06-70797483e0d3)

![2](https://github.com/bitwarden/clients/assets/173906792/f6106da0-0410-4d62-850a-ecef3b3d200a)

### Additional Context

Problèm occured since 24/06/2024
Zimbra 10.0.8_GA_4611 (build 20240412081044) - no change 

### Operating System

Linux

### Operating System Version

Ubuntu 22.04

### Web Browser

Firefox

### Browser Version

Firefox 127.0.1 and Firefox 127.0.2

### Build Version

Bitwarden module 2024.6.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by EmmJORT** [comment] 2024-06-27 14:30
same than https://github.com/bitwarden/clients/issues/9618

**Comment by djsmith85** [comment] 2024-06-27 15:21
Duplicate of #9618

**Closed** 2024-06-27 15:21 UTC
Labels: bug, browser
