### ISSUE TITLE
error: cannot decrypt

### ISSUE THREAD

**Issue by ToGitOrNotToGit** [bitwarden/clients#9524] opened 2024-06-05 21:20 UTC
### Steps To Reproduce

1. Go to ‘any website'
2. Click on ‘Bitwarden Extension'
3. Scroll down to ‘Card or Login'

### Expected Result

Actually view decrypted values: Credit Card, Login, Secure Note, etc.

### Actual Result

[error: cannot decrypt], *ypt]
[error: cannot decrypt], *ypt]
[error: cannot decrypt], *ypt]
[error: cannot decrypt], *ypt]

### Screenshots or Videos

<img width="381" alt="Screenshot 2024-06-05 at 2 13 53 PM" src="https://github.com/bitwarden/clients/assets/68088552/8e0dc145-41a8-4180-88c9-ef7687e7fad9">

### Additional Context

**The Safari extension is really bad currently.**

### Operating System

macOS

### Operating System Version

14.5 (23F79)

### Web Browser

Safari

### Browser Version

Version 17.5

### Build Version

(19618.2.12.11.6)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by ToGitOrNotToGit** [comment] 2024-06-05 21:49
Didn’t see this as an Open issue. Just came across prior closed cases.

This is present in  Bitwarden
> Version: 2024.5.0
> Server version: 2024.5.0

**Comment by TroyBW** [comment] 2024-06-06 01:25
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by christas1961** [comment] 2024-06-06 05:51
I have had this problem for over a week

**Comment by mstevens** [comment] 2024-06-07 10:28
Also seeing this issue.

**Comment by KernelBypass** [comment] 2024-06-10 01:28
Not only I had this manifest for me, but the account with 2FA and a passkey that I had set up just before that happened is gone--it failed to save. Now I have to jump through hoops to restore access to it as that company's policy is not to restore via email if 2FA/passkey is enabled.

**Comment by mikkelnl** [comment] 2024-06-10 14:45
Same issue for me, and it seems to be getting worse. A (very) temporary "fix" is to disable/enable the extension.

**Comment by liqfx** [comment] 2024-06-11 08:59
This is happening to me too. Safari extension very bad at the moment

**Comment by anuraagm0** [comment] 2024-06-12 15:54
I have found that quitting safari. (CMD+Q) and reopening resolves the issue immediately but then resurfaces randomly without any reason. Sometimes while on a website for a few mins it will stop working.

**Comment by rhoekman** [comment] 2024-06-12 20:47
Also having the same issue

**Comment by nickdekruijk** [comment] 2024-06-14 16:20
Synchronizing sometimes helps too. Sometimes...

**Comment by rpc31** [comment] 2024-06-16 18:40
same issues too on safari with macos 14.5 on MacBook 14". Any news on that topic?

**Comment by warnerchad** [comment] 2024-06-17 13:58
I've been having this issue for 2-3 weeks as well. I've tried syncing the vault, locking and unlocking, logging out and back in, and uninstalling the MacOS app, but nothing has fixed it. The best workaround I've found is changing the vault timeout setting, but I'd rather not have to do that; I like the vault timing out after a relatively short amount of time. Looking forward to a true fix.

**Comment by christas1961** [comment] 2024-06-17 19:16
There is an update available that fixes it

**Comment by warnerchad** [comment] 2024-06-17 19:53
@christas1961 What version contains the update? I'm running 2024.6.0, which is [the latest version listed](https://bitwarden.com/help/releasenotes/).

**Comment by anuraagm0** [comment] 2024-06-17 19:59
> @christas1961 What version contains the update? I'm running 2024.6.0, which is [the latest version listed](https://bitwarden.com/help/releasenotes/).

I just saw that App Store has an update for 2025.6.1

**Comment by christas1961** [comment] 2024-06-17 20:03
There is a browser extension update 2024.6.1
Available here https://bitwarden.com/download

**Comment by warnerchad** [comment] 2024-06-17 20:04
@anuraagm0 Thanks! The App Store didn't show an available update for me until I navigated to BitWarden. Then I saw 2024.6.1, with description "Safari bug fixes." I'll see if it helps.

**Comment by rhoekman** [comment] 2024-06-17 20:12
For those not seeing the latest update in the App Store yet; you can do Command-R to force an update check.

**Comment by trmartin4** [comment] 2024-07-03 22:41
We believe that this issue has been resolved with the latest Safari update.  If you continue to experience any issues, please let us know.  Otherwise we will plan to close the issue as resolved.

Thank you!

**Comment by ToGitOrNotToGit** [comment] 2024-07-03 23:41
I saw the 'cannot decrypt error' yesterday on the prior build. 

Just forced App Store update to Version 2024.6.4 (26239) today.

Is it just me? I find the quality of Bitwarden Safari extension to be very bad recently, both in iOS and Safari, macOS.

On iOS autofill tries to autofill all new Login entry fields with actual BW account credentials!!!

Random User Name generation fails.

Autofill is just disastrous

- it is in the way

- doesn’t recognize you’ve logged in, 

 - After login: still prompts BW login while also now showing available logins for the site you are on.

Not sure why BW software quality has deteriorated so quickly this year. Really disappointing.

**Comment by normanlorrain** [comment] 2024-07-07 15:50
I'm seeing this on iOS, in the app, in a "family" vault.  Other user (member) is no longer able to access the collections in that vault.

Chrome extension on Windows works fine.

**Comment by trmartin4** [comment] 2024-07-27 20:33
As we do not have any further reports on the non-mobile clients, we are going to close this issue.

@normanlorrain if you continue to experience this on the iOS mobile app, please submit an issue on our iOS repo here: https://github.com/bitwarden/authenticator-ios.

**Closed by trmartin4** 2024-07-27 20:33 UTC
Labels: bug, web
