### ISSUE TITLE
Browser extension does not show autofill menu on focused form fields, right-click menu and badge counter in Microsoft Edge when "Allow in InPrivate" is toggled on

### ISSUE THREAD

**Issue by papageno** [bitwarden/clients#10691] opened 2024-08-23 04:49 UTC
### Steps To Reproduce

1. Go to a site with login form that has a password field.
2. Focus on the password field, or any filed concerning login, such as email, username, etc.

### Expected Result

Bitwarden's autofill menu shows up below the form field focused.

### Actual Result

Bitwarden's autofill menu does not show up.

### Additional Context

The right-click menu also seems not to be working. Bitwarden's menu does not show up.

I also tried disabling content-blocking extensions like AdGuard, but the bug still exists.

### Operating System

Windows

### Operating System Version

Windows 11

### Web Browser

Microsoft Edge

### Browser Version

128.0.2739.42 (Official build) (64-bit)

### Build Version

2024.8.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment] 2024-08-23 05:12
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by cagonzalezcs** [comment] 2024-08-23 06:29
Hmm... interesting, I just tested a fresh build of the extension in Edge and was able to use autofill's features without any issues.

Can you please try something for me. If you turn the extension off then on again (ie. reset the extension), does this resolve your issue? If that does not work, can you try uninstalling and re-installing the extension?

This might be happening due to an issue with feature flag initialization of the background processes for new features of the inline menu. Resetting the extension should fix that.

**Comment by papageno** [comment] 2024-08-23 06:45
> Hmm... interesting, I just tested a fresh build of the extension in Edge and was able to use autofill's features without any issues.
> 
> Can you please try something for me. If you turn the extension off then on again (ie. reset the extension), does this resolve your issue? If that does not work, can you try uninstalling and re-installing the extension?
> 
> This might be happening due to an issue with feature flag initialization of the background processes for new features of the inline menu. Resetting the extension should fix that.

Thank you for your advice!

I removed Bitwarden extension, restart Edge and reinstalled the extension. The issue was solved.

However, when I toggled on "Allow in InPrivate" (corresponding "Allow in incognito" in vanilla Chrome), the issue hit again.

Along with the autofill menu on focused form fields and right-click menu, I also found the badge number on the extension icon had gone.

Maybe the "Allow in incognito" toggle is the reason that caused the issue.

**Comment by papageno** [comment] 2024-08-23 06:59
I retrieve the following

> Maybe the "Allow in incognito" toggle is the reason that caused the issue.

I found not only the "Allow in incognito" toggle in Browser settings, but also "Unlock with biometrics", "Make Bitwarden your default password manager" toggles within the extensions itself will reproduce the issue.

It seems that any change on requested "additional access" will break autofill menu on focused form fields, right-click menu and badge counter.

**Comment by cagonzalezcs** [comment] 2024-08-23 07:16
Hmm... yeah so I looked into this further. This isn't an issue with incognito specifically, it's an issue with how we are referencing a class that enables faster decryption within the browser extension. It seems that we are encountering an issue with referencing an un-instantiated `BulkEncryptService`, which is triggering an uncaught error and breaking the initialization of the `OverlayBackground` and `TabsBackground` classes... as well as any other logic that happens after that invalid reference to `BulkEncryptService`.

I'm bringing this up with the team to see what can be done.

**Comment by cagonzalezcs** [comment] 2024-08-23 13:25
The feature flag that was causing this issue has been turned off. A fix for this will be coming soon.

For anyone affected, please turn off/on your extension to correct the issue. It that does not work, please try a re-installation of the extension.

**Comment by cagonzalezcs** [comment] 2024-08-23 23:37
Looks like disabling that feature flag has resolve the reported issue. Closing this ticket for now, but please feel free to continue discussion as necessary.

**Closed by cagonzalezcs** 2024-08-23 23:37 UTC
Labels: bug, browser

**Comment by ywwry66** [comment] 2024-08-24 01:09
I am still having this issue with macOS and safari. Besides missing the autofill dropdown menu, shift+cmd+L does not work either. However, if I click on the Bitwarden safari extension icon (on the tab bar) right after shift+cmd+L, password will be inserted correctly.

I have tried reinstalling Bitwarden but the issue persists.

**Comment by AbdelrahmanHafez** [comment] 2024-08-24 12:51
I'm having this issue with Chrome on MacOS, the nice auto-fill icon that appears on input doesn't appear anymore, that has been the case for a couple of days.

**Comment by Mte90** [comment] 2024-08-29 15:20
when it is planned a new release with the bugfix?

**Comment by Mte90** [comment] 2024-08-30 08:33
I saw now that the ticket is closed but to me asks the users to uninstall/reinstall the extension to fix the issue is not very handy.
There isn't also any alert to suggest it.

**Comment by dspaan** [comment] 2024-08-30 14:31
Disabling/enabling the extension didn't work for me but this suggestion on Reddit worked for me:
https://www.reddit.com/r/Bitwarden/comments/1f4kgns/how_to_disable_bitwarden_in_firefox_from_telling/

![image](https://github.com/user-attachments/assets/7a4ec5e9-cca5-4845-809b-fd945863640d)

**Comment by torpesco** [comment] 2024-08-30 21:40
> I am still having this issue with macOS and safari. Besides missing the autofill dropdown menu, shift+cmd+L does not work either. However, if I click on the Bitwarden safari extension icon (on the tab bar) right after shift+cmd+L, password will be inserted correctly.
> 
> I have tried reinstalling Bitwarden but the issue persists.

Exact same thing happens for me with Safari on macOS.
