### ISSUE TITLE
Bitwarden Browser Extension prevents login and causes error when attempting to login to store.playstation.com

### ISSUE THREAD

**Issue by boktai1000** [bitwarden/clients#8243] opened 2024-03-07 18:03 UTC
### Steps To Reproduce

1. Go to https://store.playstation.com
2. Click on Sign In
4. Click on field to type your username - wait a few seconds, and the page will redirect to an error message.

### Expected Result

You are able to type your username and password and login to the website

### Actual Result

Error message of "Something went wrong."

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/9054563/4f091c5f-e552-4443-8686-5eaf0cdf1984)

### Additional Context

Disabling Bitwarden browser extension on both Firefox and Edge allows login to work. These are the browsers I have tested with.

### Operating System

Windows

### Operating System Version

Windows 10 Pro x64 - 22H2

### Web Browser

Microsoft Edge, Firefox

### Browser Version

Firefox 123.0.1 | Edge 122.0.2365.66

### Build Version

Version 2024.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cagonzalezcs** [comment] 2024-03-07 18:22
Duplicate of https://github.com/bitwarden/clients/issues/8149

**Closed** 2024-03-07 18:23 UTC
Labels: bug, browser
