### ISSUE TITLE
Forwarded e-mail alias generation runs into error in browser extension

### ISSUE THREAD

**Issue by benhaspalace** [bitwarden/clients#7469] opened 2024-01-08 10:43 UTC
### Steps To Reproduce

1. Open the browser extension where you are signed in the latest version of Edge
2. Click Generate
3. Select username
4. Select Forwarded e-mail alias
5. Select DuckDuckGo
6. Enter the API key if you don't have it registered already
7. Click on `Regenerate username`

### Expected Result

New DuckDuckGo forwarded e-mail alias displayed in the username field.

### Actual Result

An error has occured
Failed to fetch

### Additional Context

The desktop client with the same API key does not have the problem and succeeds in connecting to DuckduckGo API and acquiring a new forwarded e-mail alias

### Operating System

Windows

### Operating System Version

22635.2700

### Web Browser

Microsoft Edge

### Browser Version

120.0.2210.121

### Build Version

2023.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-01-08 11:11
Duplicate of https://github.com/bitwarden/clients/issues/7082

**Comment by djsmith85** [comment] 2024-01-08 11:11
Hi @benhaspalace,

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/7082

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2024-01-08 11:11 UTC
Labels: bug, browser
