### ISSUE TITLE
Inline Autofill not working for password fields in some sites (Chrome)

### ISSUE THREAD

**Issue by mattjago** [bitwarden/clients#10792] opened 2024-08-29 13:55 UTC
### Steps To Reproduce

Inline autofill seems to be broken for certain websites that were working previously.  I have seen this both on my work PC and personal machine over the past few days.  Both are running the latest version of chrome and the 2024.8.1 browser extension.
Inline autofill works fine for the username field but does not work for the password field. 
Autofill works when clicking the extension or using the right-click context menu.

1. Go to https://www.gov.uk/driver-vehicles-account (the other sites that I've seen affected are ones I use for work so cannot share)
2. Click on 'Start Now' 
3. Enter your username using inline autofill and click Continue
4. Notice that inline autofill does not work for the password field

### Expected Result

Inline autofill should offer the password from my vault for the current page

### Actual Result

Inline autofill is not available for the field

### Operating System

Windows

### Operating System Version

Windows 11

### Web Browser

Chrome

### Browser Version

128.0.6613.85

### Build Version

2024.8.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Mte90** [comment] 2024-08-29 14:37
I see a similar issue on firefox also the right click menu doesn't have anymore the bitwarden one.

**Comment by NovaSilentium** [comment] 2024-08-29 15:16
Duplicate of #10691

**Comment by NovaSilentium** [comment] 2024-08-29 15:18
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/10691
If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thank you

**Closed** 2024-08-29 15:18 UTC
Labels: bug, browser
