### ISSUE TITLE
Linux Desktop Client - no collection pre-seclected and also no collection selectable

### ISSUE THREAD

**Issue by GibberishIT** [bitwarden/clients#8574] opened 2024-04-02 07:34 UTC
### Steps To Reproduce

1. Select any organisation collection
2. Click on '+' 
3. fill out user+pass
4. Scroll down, under organisation name "no collections available" visible (and not selectable)
5. Click on 'Save' 
6. Error message: "You must select at least one collection"

### Expected Result

When selecting a collection and click on '+' to add an entry, this collection is pre-selected.

### Actual Result

No collection is selected and there is noc possibility to select one.

### Screenshots or Videos

![bitwarden_collection](https://github.com/bitwarden/clients/assets/100764540/1c0eb9a3-c364-4321-b7b9-da2c72a42c62)

### Operating System

Linux

### Operating System Version

Ubuntu 22.04

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment] 2024-04-02 07:41
Hi there!
Thank you for your report, it seems like it is a duplicate of this one #8258 . 
If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.
This issue will now be closed.
Thanks!

**Closed by daniellbw** 2024-04-02 07:41 UTC
Labels: bug, desktop
