### ISSUE TITLE
Phone and Desktop APP do not open 'Ask for Master Password' fields

### ISSUE THREAD

**Issue by LucianoCrocco** [bitwarden/clients#6279] opened 2023-09-13 14:27 UTC
### Steps To Reproduce

1. Go to any field that has 'Ask for master passwod' on the Android device or Windows App
2. Enter your Master Password

### Expected Result

Edit or Watch the secured files with master pasword

### Actual Result

It doesn't give you any prompt if you enter the master password correctly, remains locked. But if the master password IS wrong it will warn you.

### Additional Context

This has been happening roughly since August, before i didn't had any problem with both devices.

### Operating System

Windows

### Web Browser

Vivaldi

### Build Version

-

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment] 2023-09-13 16:34
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/6153.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by Neonwarden** 2023-09-13 16:34 UTC
Labels: bug, browser
