### ISSUE TITLE
Firefox freezes on Home Assistant page

### ISSUE THREAD

**Issue by waclaw66** [bitwarden/clients#11259] opened 2024-09-26 17:32 UTC
### Steps To Reproduce

Firefox freezes during browsing HA panels

Home Assistant 2024.9.3
Bitwarden 2024.9.1

### Expected Result

No freezes as before

### Actual Result

https://share.firefox.dev/4gFDxDW

### Operating System

Windows

### Operating System Version

11

### Web Browser

Firefox

### Browser Version

130

### Build Version

130.0.1 (64 bit)

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by luc-bw** [comment] 2024-09-26 17:41
Hi,

Thanks for the report.

This is a duplicate of https://github.com/bitwarden/clients/issues/11234

Meanwhile, try disabling the settings as instructed, here: [https://github.com/bitwarden/clients/issues/11234#issuecomment-2374903445](https://github.com/bitwarden/clients/issues/11234#issuecomment-2374903445)

**Closed by luc-bw** 2024-09-26 17:41 UTC
Labels: bug, browser

**Comment by waclaw66** [comment] 2024-09-26 17:54
I've tried to disable those notification setting already, it didn't help.

**Comment by cagonzalezcs** [comment] 2024-09-26 19:50
If that isn't the issue at hand, then likely it has to do with the issues we've seen with the page collection process. A performance improvement for this kind of problem has been merged into `main` and should be releasing with the next extension release.

https://github.com/bitwarden/clients/pull/10816

At the moment, the only other suggestion I could make is to try rolling back to the previous version of Bitwarden, v2024.9.0. That said, unfortunately you are likely going to see the same issue until the performance improvements are released.

**Comment by waclaw66** [comment] 2024-09-27 08:37
I've tested all 2024 versions, they are all causing this problem. I believe it's because `custom:apexcharts-card` card. It creates svg inline charts with many nested nodes. When I hide those everything is much more nimble. Could it be parsing process optimized to ignore such svg nodes?

**Comment by waclaw66** [comment] 2024-10-04 14:01
This is still an issue with 2024.10.0.
https://share.firefox.dev/4erNuDx

**Comment by cagonzalezcs** [comment] 2024-10-04 16:19
@waclaw66 

Hm, we can filter out `svg` nodes within the TreeWalker process to hopefully improve this. I have a PR in code review set up for that here - https://github.com/bitwarden/clients/pull/11415

**Comment by waclaw66** [comment] 2024-10-04 18:52
Happy to test that, if you have an addon zip. SVG elements of Apex-charts definitely causing that, page is lightning fast when I remove them or Bitwarden addon is disabled.

**Comment by cagonzalezcs** [comment] 2024-10-07 20:55
@waclaw66 That'd be helpful, you can pull artifacts from that build from this page - https://github.com/bitwarden/clients/actions/runs/11183299195?pr=11415

Realistically, the extension is always going to have an impact on performance... but improving the performance is a top concern for the team. We've been working in improvements as time allows, but it is a tricky thing to handle while maintaining the expected behavior.

I'm hoping this change helps with your experienced issue.

**Comment by waclaw66** [comment] 2024-10-08 05:32
@cagonzalezcs I've checked the test build and the performance is much much better now. Thank you!
