### ISSUE TITLE
`bw list items` ignores `--session` argument and $BW_SESSION env variable

### ISSUE THREAD

**Issue by Kairixir** [bitwarden/clients#9168] opened 2024-05-14 08:56 UTC
### Steps To Reproduce

1. Go to shell
2. Input:
```bash
# Get session token and save it in TEST_VAR
TEST_VAR=$(bw --raw session)

# Use TEST_VAR token as --session argument
bw list items --session $TEST_VAR
```
3. Input:
```bash
# Save TEST_VAR in default BW_SESSION variable
BW_SESSION=$TEST_VAR

# Use BW_SESSION for bw run
bw list items
```

### Expected Result

In both examples (2., 3.) `bw list items` should run without requesting Master Password

### Actual Result

In both examples `bw list items` asks for Master Password even with valid Session token

### Additional Context

Working example (using TEST_VAR from before):
```bash
# Use local environment variable
BW_SESSION=$TEST_VAR bw list items
```

### Operating System

macOS

### Operating System Version

12.7.1

### Shell

Zsh

### Build Version

2024.4.0

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-05-14 09:16
Duplicate of https://github.com/bitwarden/clients/issues/9067

**Comment by djsmith85** [comment] 2024-05-14 09:16
@Kairixir This is a duplicate of https://github.com/bitwarden/clients/issues/9067 and resolved with https://github.com/bitwarden/clients/pull/9084

Please update to [2024.4.1](https://github.com/bitwarden/clients/releases/tag/cli-v2024.4.1) which includes the fix.

Closing this now.

**Closed by djsmith85** 2024-05-14 09:16 UTC
Labels: bug, cli
