### ISSUE TITLE
Experiencing a large performance impact while using the bitwarden extension on Chrome

### ISSUE THREAD

**Issue by derailius** [bitwarden/clients#7420] opened 2024-01-02 16:03 UTC
### Steps To Reproduce

1. Go to https://browserbench.org/Speedometer2.1/
2. Click on 'Start Test' without Bitwarden enabled
3. Click on 'Start Test' with Bitwarden enabled

### Expected Result

Slight performance impact

### Actual Result

Chrome is slower by ~33.78% with the Bitwarden extension enabled.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/9661551/b51f0606-a3a1-4c1d-84da-134a19a9fde7)
![image](https://github.com/bitwarden/clients/assets/9661551/ee7335c9-6ece-4a0d-abef-d4b811e34421)

### Operating System

Windows

### Operating System Version

Pro 23H2 22631.2861

### Web Browser

Chrome

### Browser Version

120.0.6099.130

### Build Version

2023.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-01-02 16:11
Duplicate of https://github.com/bitwarden/clients/issues/7267

**Comment by djsmith85** [comment] 2024-01-02 16:11
Hi @derailius ,

This is a duplicate of https://github.com/bitwarden/clients/issues/7267

Closing this now.

**Closed by djsmith85** 2024-01-02 16:11 UTC
Labels: bug, browser
