### ISSUE TITLE
Continuously creating "website name" checkbox in username generator page

### ISSUE THREAD

**Issue by scruel** [bitwarden/clients#10310] opened 2024-07-29 04:19 UTC
### Steps To Reproduce

- Open new registration page (any sites)
- Create item
- Click username generator icon
- Click "Catch-all email" option
- Change the domain

### Expected Result

No type checkbox created

### Actual Result

Continuously creating "website name" checkbox.

### Screenshots or Videos
![recording](https://github.com/user-attachments/assets/0046b0f1-c46a-4b7a-9115-96ea468bb64d)

### Operating System

Windows

### Web Browser

Firefox

### Browser Version

dev 129.0b6

### Build Version

2024.6.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-07-29 10:24
Duplicate of https://github.com/bitwarden/clients/issues/10161

**Comment by djsmith85** [comment] 2024-07-29 10:25
Hello @scruel,

Thank you for your report. This has previously been reported with https://github.com/bitwarden/clients/issues/10161 and has received a fix with https://github.com/bitwarden/clients/pull/9782. 

The changes will be included in an upcoming release.

This report will now be closed as a duplicate.

Thank you again,

**Closed by djsmith85** 2024-07-29 10:25 UTC
Labels: bug, browser
