### ISSUE TITLE
Fastmail Generator for forwarded email alias broken

### ISSUE THREAD

**Issue by lovetox** [bitwarden/clients#9461] opened 2024-05-31 15:57 UTC
### Steps To Reproduce

- Have a Fastmail account with your own hosted custom domain
- Go to the generator site
- Choose Fowarded email alias
- Select Fastmail as Service provider
- Try to generate a forwarded email alias

### Expected Result

Getting at least a @fastmail.com email alias.

Even better would be a setting or field where i can configure the domain where i want an alias for.

### Actual Result

An error happens, see screenshot
![image](https://github.com/bitwarden/clients/assets/8661218/b32581f3-55d1-4b48-9107-a7b6de20de39)

### Operating System

Linux

### Operating System Version

Ubuntu 24.04

### Web Browser

Firefox

### Browser Version

126

### Build Version

2024.4.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment] 2024-05-31 16:27
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by djsmith85** [comment] 2024-05-31 16:39
Duplicate of https://github.com/bitwarden/clients/issues/9183

**Comment by djsmith85** [comment] 2024-05-31 16:41
Hi @lovetox,

This was previously reported with https://github.com/bitwarden/clients/issues/9183 and addressed by a community member with https://github.com/bitwarden/clients/pull/9127.

The changes will be included in the next release.

Closing this now.

Kind regards,
Daniel

**Closed by djsmith85** 2024-05-31 16:41 UTC
Labels: bug, browser
