### ISSUE TITLE
User Preferences - Display Full Width Layout Settings Not Respected

### ISSUE THREAD

**Issue by wagisdev** [bitwarden/clients#3354] opened 2022-08-22 09:23 UTC
### Steps To Reproduce

- Go to account settings.
- Preferences
- Check Display full width layout
- Logout
- Close browser (Chrome *current)
- Open browser
- Go to site
- Enterprise SSO
- Org Identify login
- Master Password
- And....view that full width setting not observed. Back to original setting.

### Expected Result

Full width settings are maintained as active.

### Actual Result

Full width setting is not observed even though checked.

### Operating System

Windows

### Operating System Version

10

### Web Browser

Chrome

### Browser Version

104.0.5112.83

### Build Version

2022.8.1

**Comment by aj-bw** [comment] 2022-08-23 12:46
Hi @wagisdev! Thanks for reaching out.

I have been attempting to recreate this issue but so far have not been able to. One question, if you visit chrome://settings/cookies in Chrome, is the "Clear cookies and site data when you close all windows" toggled on? If so, I confirmed that setting being on would cause a browser close to clear the Display Full Width Layout setting.

**Comment by wagisdev** [comment] 2022-08-23 13:22
Good morning @aj-bw,

The only settings I have active in chrome://settings/cookies are....

- Block third-party cookies incognito
- Send a Do Not Track request w/ browsing traffic

I checked MS Edge and found that the same issue I experience in Chrome happens in Edge too. Display full width layout in both cases is checked but is not active when logging in.

**Comment by wagisdev** [comment] 2022-08-23 13:28
@aj-bw,

Just one more piece of info for you....

I have used several computers to check this behavior, spun up 2 VMs with different OS's, etc...etc. In all attempts this has been a consistent issue for me. Logged into Chrome, out of chrome, Edge, incognito vs. not, etc.

Thank you for looking at it.

**Comment by aj-bw** [comment] 2022-08-23 15:26
@wagisdev,
Thanks for the additional info, that was helpful.

I was able to recreate the bug, I will raise this internally for prioritization. Thanks for bringing this to our attention!

**Comment by wagisdev** [comment] 2022-08-23 15:37
@aj-bw phew! Glad to hear. Thank you ver much!

**Comment by tehmaspc** [comment] 2023-01-02 19:24
+1 - every time I re-login to the Vault I have to go into preferences to disable/enable + Save my preferences to regain full page width settings.

**Comment by jcenakt** [comment] 2023-07-14 02:41
+1 - also experience this problem, on firefox (v 115) in my case.

**Comment by TroyBW** [comment] 2023-08-25 19:04
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/clients/issues/5672

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by TroyBW** 2023-08-25 19:04 UTC
Labels: bug, web
