### ISSUE TITLE
Inline auto-fill blocking text field in Firefox

### ISSUE THREAD

**Issue by Nicowars** [bitwarden/clients#8638] opened 2024-04-07 04:08 UTC
### Steps To Reproduce

1. Go to https://account.xiaomi.com in Firefox Browser
2. Use autofill using Inline auto-fill menu

### Expected Result

I expect my username and password will be autofilled. Or in worst case scenario do nothing.

### Actual Result

It doesnt autofill. But also it completely block the text field. Making unable to write in the username or password field.

### Additional Context

In Chrome Browser it works as expected.
Context-menu and Keyboard Shortcut works as expected in Firefox.
It also happen in my bank homebanking, but is not simple to replicate.

I know that there is an specific form for auto-fill failure. But considering that this bug is blocking the login and not only no working, I consider doing in here. I'm sorry if is not the case.

If something is not clear I will do my best to clarify, but english is not my mother tongue.

### Operating System

Windows

### Web Browser

Firefox

### Build Version

2024.2.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cagonzalezcs** [comment] 2024-04-07 21:16
Duplicate of https://github.com/bitwarden/clients/issues/8063

A fix for this has been merged recently. Details are present in the ticket linked above.

**Closed by cagonzalezcs** 2024-04-07 21:16 UTC
Labels: bug, browser
