### ISSUE TITLE
Generator history lists a new entry every few seconds

### ISSUE THREAD

**Issue by windmueller** [bitwarden/clients#12074] opened 2024-11-20 21:37 UTC
### Steps To Reproduce

1. Go to 'Generator'
2. Click on 'Password history'

### Expected Result

The history should list only the passwords generated manually.

### Actual Result

A huge list of passwords appears with timestamps sometimes only seconds apart.

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/cfe1a859-500c-4230-a3c3-1a8b85af6842)

### Additional Context

I am not sure what triggers a newly generated password. Clicking in the browser, switching tabs etc. seems to trigger it but I might be mistaken.

### Operating System

Linux

### Operating System Version

Arch Linux

### Web Browser

Brave

### Browser Version

Version 1.73.89

### Build Version

2024.11.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment] 2024-11-21 07:47
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/12047

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by daniellbw** 2024-11-21 07:47 UTC
Labels: bug, browser
