### ISSUE TITLE
Failed to decode access token on Linux

### ISSUE THREAD

**Issue by jacopocerasoli** [bitwarden/clients#8957] opened 2024-04-28 10:39 UTC
### Steps To Reproduce

1. Install Bitwarden desktop on Linux
2. Sign up using email and master password
3. Enter 2FA verification code

### Expected Result

Accessing vault

### Actual Result

Red box saying "Failed to decode access token: JWT must have three parts"
![Screenshot from 2024-04-20 18-37-39](https://github.com/bitwarden/clients/assets/68323213/2afa91dc-4218-4f92-a351-ec3b078e89f8)

### Operating System

Linux

### Operating System Version

Ubuntu 22.04.4 LTS

### Installation method

Snap

### Build Version

2024.4.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment] 2024-04-28 13:52
Hi @jacopocerasoli,

Thank you for this report. It seems to be a duplicate of a matter discussed in an [existing GitHub report](https://github.com/bitwarden/clients/issues/8651); Please read the [documentation in the Bitwarden Help Centre](https://bitwarden.com/help/getting-started-desktop/#tab-3-6vQUhrVotSKFarA3cqyESG) to allow the Snap desktop client to access Secure Storage and operate as expected; Afterwards, log out and log in anew.

I will now proceed and close this GitHub report. If you have any further questions or concerns, please feel free to create a [support ticket](https://bitwarden.com/help/) or to raise them in that existing thread.

Thank you again,

**Closed by SergeantConfused** 2024-04-28 13:52 UTC
Labels: bug, desktop
