### ISSUE TITLE
The BitWarden Firefox extension doesnt log in over the Tor Browser

### ISSUE THREAD

**Issue by sallyFoster** [bitwarden/clients#6728] opened 2023-10-28 12:17 UTC
### Steps To Reproduce

1. Install the Firefox add-on (extension) on the Tor Browser
2. Try to log in with your credentials

### Expected Result

Being able to log in on the add-on on the Tor Browser

### Actual Result

It is throwing back an error on every log in attempt 

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/104597302/aaa1ab76-1e4e-477e-81ee-3f239d8d4d8a)

### Operating System

macOS

### Operating System Version

Sonoma 14.0

### Web Browser

Firefox

### Browser Version

Tor Browser 13.0.1 (Based on Mozilla Firefox 115.0esr)

### Build Version

2023.9.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment] 2023-11-02 14:47
Hi @sallyFoster,

Thank you for your report. It seems like it is a duplicate of this (https://github.com/bitwarden/clients/issues/5427).

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This report here will now be closed.

Thank you again,

**Closed by SergeantConfused** 2023-11-02 14:47 UTC
Labels: bug, browser
