### ISSUE TITLE
Cannot edit master-password-protected secure notes

### ISSUE THREAD

**Issue by kimkanu** [bitwarden/clients#6214] opened 2023-09-07 05:46 UTC
### Steps To Reproduce

1. Go to "Secure note"
2. Click on "Edit a protected memo"
3. Type password and press "OK"
4. "Error: Invalid parameters" raises

### Expected Result

Should proceed after pressing OK, or show me an error message when something went wrong

### Actual Result

The error is uncaught, resulting in nothing in the client side, only with a console.error message

### Screenshots or Videos

<img width="1552" alt="Screenshot 2023-09-07 at 14 39 13" src="https://github.com/bitwarden/clients/assets/22598138/ac3e8fcf-7e0d-4ee5-abb3-b54a8faf2a23">

### Additional Context

Cannot edit or delete the note as well

### Operating System

macOS

### Operating System Version

Ventura 13.4

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2023.8.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment] 2023-09-07 05:50
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/clients/issues/6153

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by sammbw** 2023-09-07 05:50 UTC
Labels: bug, desktop
