### ISSUE TITLE
Flathub app doesnt display correctly

### ISSUE THREAD

**Issue by nlp71677** [bitwarden/clients#6775] opened 2023-11-02 23:09 UTC
### Steps To Reproduce

open flathub version of bitwarden

### Expected Result

Display login page

### Actual Result

Blank window apart from the bitwarden logo

### Screenshots or Videos

![Screenshot from 2023-11-02 18-07-25](https://github.com/bitwarden/clients/assets/149735284/6a95c9d7-4e54-4445-ab25-bc3a4d0a8626)

### Operating System

Linux

### Operating System Version

Fedora 38

### Installation method

Other

### Build Version

Version 2023.9.3 Shell 25.9.1 Renderer 114.0.5735.289 Node 18.15.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by luc-bw** [comment] 2023-11-02 23:20
Hello,

Thanks for the report. Bitwarden does not maintain Flatpak distribution. This is a duplicate of https://github.com/bitwarden/clients/issues/6732

**Closed by luc-bw** 2023-11-02 23:20 UTC
Labels: bug, desktop
