### ISSUE TITLE
Item title is too short

### ISSUE THREAD

**Issue by HRIT-Florian** [bitwarden/clients#3831] opened 2022-10-19 07:46 UTC
### Steps To Reproduce

1. Log in to browser extension
2. Look at the name of any item (login, card, etc. in tab, safe or sidebar)
3. The name is displayed much too short

### Expected Result

In Our Case for example these items

- CompanyName - FTP /Files
- CompanyName - FTP /Documents
- CompanyName - FTP /Images (Juck)
- CompanyName - FTP /Images (Michael)
...

### Actual Result

- CompanyName - FT...
- CompanyName - FT...
- CompanyName - FT...
- CompanyName - FT...
...

With many entries, no one can understand which entry is for what.
It's so useless and we just have a lot of titles that can't all be optimised to 18 characters or what the limit is!

@admins, feel free to take out the wrong label, unfortunately there was no other choice because of #3832. Many thanks 🤘

**Comment by djsmith85** [comment] 2022-10-19 10:55
Duplicate of https://github.com/bitwarden/clients/issues/3831

Hi @HRIT-Florian thank you for your report. This issue has previously been reported and has also been addressed with https://github.com/bitwarden/clients/pull/3792.

**Closed by djsmith85** 2022-10-19 10:55 UTC
Labels: bug, browser
