### ISSUE TITLE
Start - error Bitwarden

### ISSUE THREAD

**Issue by Werner303** [bitwarden/clients#2944] opened 2022-06-21 17:17 UTC
### Steps To Reproduce

Version 2022.5.0
wants to install again and again the version 2022.5.1 at startup - afterwards again version 2022.5.0.
Even a manually installed version 2022.5.1 does not change the error message

### Expected Result

No error message

### Actual Result

error message

### Screenshots or Videos

![Fehler Biotwarden](https://user-images.githubusercontent.com/37148641/174859286-ef6301b1-0df9-4df2-92a7-1893128e9a5e.png)

### Operating System

Windows

### Operating System Version

11

### Web Browser

Chrome

### Browser Version

Version 103.0.5060.53 (Offizieller Build) beta (64-Bit)

### Build Version

Version 103.0.5060.53 (Offizieller Build) beta (64-Bit)

**Comment by ifernandezdiaz** [comment] 2022-08-03 13:19
Hi, @Werner303! I couldn't reproduce your issue, but I'd like to know if our latest version solved it!
Could you please install the latest version and confirm that?

Thanks in advance!

**Comment by Hinton** [comment] 2022-08-04 09:40
Closed as duplicate of #2571

**Closed by Hinton** 2022-08-04 09:40 UTC
Labels: bug, browser
