### ISSUE TITLE
Desktop release 2024.7.0 rolled back?

### ISSUE THREAD

**Issue by alextmz** [bitwarden/clients#10158] opened 2024-07-17 23:49 UTC
### Steps To Reproduce

I update my bitwarden linux desktop directly from the releases via scripting. The script notified me that it would roll back version 2024.7.0 to 2024.6.4.

### Expected Result

I did not expect a downgrade. There is no mention of the release 2024.7.0 being rolled back anywhere in forums or issues.

### Actual Result

I did expect a note, announcement or reason why a release was rolled back. Instead it just disappeared from releases.

### Operating System

Linux

### Operating System Version

dpkg compatible

### Installation method

Other

### Build Version

2024.7.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment] 2024-07-18 00:11
Hi there,

Your issue appears to be describing the intended behavior of the software. 2024.7.0 is marked as a pre-release - you can view the current releases here: https://github.com/bitwarden/clients/releases

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!

**Closed by sammbw** 2024-07-18 00:11 UTC
Labels: bug, desktop

**Comment by alextmz** [comment] 2024-07-18 01:36
Apologies, but it is incorrect that it is the intended behavior. There was clearly a tag "2024.7.0" on releases and which is not there anymore - `curl -s https://api.github.com/repos/bitwarden/clients/releases | grep 2024\.7\.0` at the moment of this writing returns empty, and that wasn't the case about 48 hours ago. I stand by the fact that there was a 2024.7.0 tag and it is not there anymore - which isn't a problem in itself, what worries me is releases disappearing without any communication on a software as sensitive as this.

**Comment by Reinitialized** [comment] 2024-07-18 04:50
Can confirm what alextmz is reporting to be true, as winget currently attempts to download 2024.7.0, but fails due to the file no longer being available:
![image](https://github.com/user-attachments/assets/181a3bb0-3aba-4a78-a038-6892f68bc044)

**Comment by tjorim** [comment] 2024-07-18 14:07
The release still exists in the manifest but actual installer seems to be pulled: https://github.com/microsoft/winget-pkgs/tree/master/manifests/b/Bitwarden/Bitwarden/2024.7.0
