### ISSUE TITLE
Login View Disappears; Can't login on Linux.

### ISSUE THREAD

**Issue by aaron-salisbury** [bitwarden/clients#6578] opened 2023-10-13 17:34 UTC
### Steps To Reproduce

1) Download app image from site, or install from package manager.
2) Launch Bitwarden.
3) Begin typing in email address.

### Expected Result

To be able to complete login.

### Actual Result

View disappears. Cannot login and use application.

### Additional Context

Linux Mint 21.2 Cinnamon
Cinnamon Version: 5.8.4
Linux Kernel: 5.15.0-86-generic
Processor: i9-12900K
Graphics Card: NVIDIA

### Operating System

Linux

### Operating System Version

Linux Mint 21.2 Cinnamon

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.9.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2023-10-13 17:39
Duplicate of https://github.com/bitwarden/clients/issues/6560

**Comment by djsmith85** [comment] 2023-10-13 17:39
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/6560.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed** 2023-10-13 17:39 UTC
Labels: bug, desktop
