### ISSUE TITLE
UI doesn't reflect new changes to item card when user hits the save button

### ISSUE THREAD

**Issue by albirch** [bitwarden/clients#12339] opened 2024-12-10 21:53 UTC
### Steps To Reproduce

1. Go to Bitwarden and click on any item
2. Make any adjustment such as updating the name of the item
3. Scroll down and hit "save"
4. Notice that the item card is not updated. The old name will still be shown. You have to click on another item and then go back to the item you adjusted to see the new changes. This is a really bad bug since I've almost gotten locked out with the TOTP field doing the same thing. 

### Expected Result

The UI should refresh to show the latest changes made on the item

### Actual Result

The UI DOES NOT refresh the item after a user invokes save. 

### Operating System

macOS

### Operating System Version

15.1.1

### Installation method

Mac App Store

### Build Version

Version 2024.11.2 Shell 32.1.1 Renderer 128.0.6613.137 Node 20.17.0 Architecture arm64

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by rmcdowell-bitwarden** [comment] 2024-12-11 08:00
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/12022. 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by rmcdowell-bitwarden** 2024-12-11 08:00 UTC
Labels: bug, desktop
