### ISSUE TITLE
Sync doesn't work

### ISSUE THREAD

**Issue by lflaurflorin** [bitwarden/clients#7288] opened 2023-12-19 18:20 UTC
### Steps To Reproduce

1. Go to 'File'
2. Click on 'Sync vault'
3. You will see the following message:
Syncing failed.

### Expected Result

Sync successfully or equivalent (internet access enabled, firewall disabled with the same result)

### Actual Result

Syncing failed error

### Screenshots or Videos

![syf](https://github.com/bitwarden/clients/assets/141065083/b909a9e0-e8b9-48cf-8347-4be00681e742)

### Operating System

Windows

### Operating System Version

Windows 11 Pro x64 build 22631.2861

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2023.12.0 Shell 25.9.1 Renderer 114.0.5735.289 Node 18.15.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2023-12-19 18:24
Duplicate of https://github.com/bitwarden/clients/issues/7243

**Comment by djsmith85** [comment] 2023-12-19 18:24
Hi @lflaurflorin,

Thank you for your report. This report seems like it is a duplicate of https://github.com/bitwarden/clients/issues/7243

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This report will now be closed.

Thank you again

**Closed by djsmith85** 2023-12-19 18:24 UTC
Labels: bug, desktop
