### ISSUE TITLE
Passkeys not working

### ISSUE THREAD

**Issue by speedy1804** [bitwarden/clients#10210] opened 2024-07-22 16:16 UTC
### Steps To Reproduce

1. Go to any website that supports passkeys (in my case passkeys.io to demonstrate passkeys are not working)
2. First click on "sign in" and then "create passkey"
3. The Bitwarden browser extension window should open, click "save passkey"
--------------------------------------------------------------------------------------
1. Go to any website that supports passykeys
2. Sign in with a saved passkey
3. The Bitwarden browser extension window should open where I am asked to log in with a passkey

### Expected Result

The Bitwarden extension should save the passkey in the corresponding account.
----------------------------------------------------------------------------------------
The extension should allow me to log in to my account using the passkey stored in my account

### Actual Result

In both cases, however, the expected status fails because the biometric verification could not be completed. A picture is attached.
![error](https://github.com/user-attachments/assets/f7816ed9-f089-42d6-9f72-606c1ee9b7c4)

### Screenshots or Videos

![trying to save the passkey](https://github.com/user-attachments/assets/a77fb58d-c9c6-4bd9-9974-ccaac3d08d1b)
![error](https://github.com/user-attachments/assets/c5f0f87a-6e82-4274-93ec-fff89c385015)

https://github.com/user-attachments/assets/7b0f973f-f84e-4542-898b-43153da79cdc

### Additional Context

Please note: The Bitwarden desktop app always ran in the background
!!! Edit: Passkeys actually work on some websites, such as: https://community.brave.com/ - The website accepted the passykey stored in Bitwarden without any problems, but there are still some websites where passkeys don't work, such as github.com , google.com or the demonstration page passkeys.io !!!

### Operating System

Windows

### Operating System Version

Windows 11 Pro 23H2

### Web Browser

Chrome, Brave

### Browser Version

Brave Version 1.67.234 with Chromium Version 126.0.6478.186

### Build Version

2024.6.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by antonlydell** [comment] 2024-07-22 18:07
I have another issue with passkeys that perhaps could be related to this issue.
See : [Unknown errorCode "Invalid 'sameOriginWithAncestors' value" when signed in to Bitwarden browser extension](https://github.com/bitwarden/passwordless-client-js/issues/62)

**Comment by TroyBW** [comment] 2024-07-22 23:24
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/clients/issues/9795. 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by TroyBW** 2024-07-22 23:24 UTC
Labels: bug, browser
