### ISSUE TITLE
Can't Login to Safari Extension

### ISSUE THREAD

**Issue by lankytom** [bitwarden/clients#6246] opened 2023-09-10 07:18 UTC
### Steps To Reproduce

Click on Safari extension
Log in with UID & PW
Getting error message (see screenshot)

### Expected Result

open vault

### Actual Result

getting error 'Username or password is incorrect. Try again'

### Screenshots or Videos

<img width="441" alt="Bildschirmfoto 2023-09-10 um 09 10 57" src="https://github.com/bitwarden/clients/assets/144584499/ec706420-049c-4999-8e46-d292e3aa82ab">

### Additional Context

Safari 16.6. on Mac OS 13.5
Tried ~20 times. No success
Then uninstalled desktop and extension, and reinstalled.
Could log in to desktop, with PW or with Touch ID.

but STILL can't log in to Safari extension!!!! Same error.

### Operating System

macOS

### Operating System Version

13.5

### Web Browser

Safari

### Browser Version

16.6

### Build Version

2023.8.2. ? can't log in to extension, not sure of correct

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment] 2023-09-10 13:47
Hi @lankytom,

Thank you for your report. Are you sure that you're selecting the same Region or Server in all your Bitwarden clients when you are logging in? I ask because I am unable to reproduce this behaviour on macOS 13.5.1 with Bitwarden 2023.8.2 on Safari 16.6.

If you continue to encounter this behaviour, please create a support ticket (https://bitwarden.com/help/) using your account's email address, and we'll assist you in troubleshooting this.

We use GitHub issues as a place to track bugs and other development related issues; I will now proceed and close this report.


Thank you again,

**Closed by SergeantConfused** 2023-09-10 13:47 UTC
Labels: bug, browser

**Comment by lankytom** [comment] 2023-09-10 17:37
yes that was it. 
On the desktop I was on bitwarden.com, in Safari on bitwarden.eu
I was not aware that there even was an option to select different servers.
Also, I wonder why the Safari extension was set to .eu - I didn't do that, there was no upgrade or similar.

On Github vs. help tickets: I was guided here when clicking 'report an error' in the desktop menu. So I thought this is the official way to 'report an error'. I even created a new Github account, as I didn't have one.

So that is quite confusing, if you are not involved deeply into your processes. But at least I do know now.
