### ISSUE TITLE
Syncing failed

### ISSUE THREAD

**Issue by Vosburgh** [bitwarden/clients#7532] opened 2024-01-11 23:00 UTC
### Steps To Reproduce

1. Go to 'File'
2. Click on 'Sync Vault'

### Expected Result

Great Success toast thrown with message: "Syncing successful yippie". As well my vault's entries being synced with the latest data I expect to be present.

### Actual Result

Error toast thrown with message: "Syncing failed". Data is stale and no logs thrown to gain more precise info.

### Additional Context

I am on a second machine with a stale vault. I've made entries while on the first machine that I expected to access from my second. It could be possible at the time of making the entries on my first machine that my machines time was not properly sync'd. The time between those entries made on the first machine and my attempt to sync on the second machine has been weeks.

I may access my correct fresh vault entries through the web UI.

### Operating System

Windows

### Operating System Version

Edition	Windows 11 Home
Version	22H2
Installed on	‎2023-‎08-‎22
OS build	22621.3007
Experience	Windows Feature Experience Pack 1000.22681.1000.0

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2023.12.0 
Shell 25.9.1 
Renderer 114.0.5735.289
Node 18.15.0 
Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-01-11 23:25
Hi @Vosburgh!

Thank you for your report, it seems like it is a duplicate of this one #7243

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed** 2024-01-11 23:25 UTC
Labels: bug, desktop
