### ISSUE TITLE
No access to password vault when offline

### ISSUE THREAD

**Issue by Cris70** [bitwarden/clients#7539] opened 2024-01-12 09:06 UTC
### Steps To Reproduce

1. Boot your computer and DO NOT start Bitwarden Desktop
2. Disable the Internet connection
3. Start the Bitwarden Desktop app
4. Enter the master password

### Expected Result

The expected result is that I'm able to access my logins without an Internet connection

### Actual Result

As a result of the above login attempt, I get an eternally-spinning spinner

### Operating System

Linux

### Operating System Version

openSUSE Tumbleweed

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2023.12.1 Shell 27.2.1 Renderer 118.0.5993.159 Node 18.17.1 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment] 2024-01-12 10:26
Hi @Cris70 ,

Thank you for your report, it seems like it is a duplicate of this one - https://github.com/bitwarden/clients/issues/6945

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by atjbramley** 2024-01-12 10:26 UTC
Labels: bug, desktop

**Comment by Cris70** [comment] 2024-01-12 10:39
Hi @atjbramley , thank you for your prompt reply.
I don't think it is a duplicate. I do not have any problem when I start Bitwarden Desktop if I'm online.
I only experience this problem when I'm offline.
Actually, I only noticed this because sometimes I need to connect to a VPN that inhibits external connections.

**Comment by atjbramley** [comment] 2024-01-12 12:09
Hi @Cris70, 

Thanks for your comment.  Please would you post your findings to the linked issue:
https://github.com/bitwarden/clients/issues/6945

The team is currently investigating several incidences of the Desktop Apps not loading, and they will be interested to hear about your findings in the issue linked.

If this issue is found to have a separate root cause, we will happily re-open it at a later date.

**Comment by fiveangle** [comment] 2025-03-19 02:33
Does anyone know of an alternative self-hosted password manager that supports offline password access/merging/conflict resolution ?
