### ISSUE TITLE
Chromium: Switching focus leads to Bitwarden closing and losing current view

### ISSUE THREAD

**Issue by mrusme** [bitwarden/clients#4320] opened 2022-12-26 18:00 UTC
### Steps To Reproduce

1. Open Bitwarden
2. Search for an entry
3. View the entry
4. Click on a different window on your desktop so that Chromium loses focus
5. Click back on the Bitwarden popup

### Expected Result

I would expect to be able to continue interacting with the entry I was viewing.

### Actual Result

Bitwarden popup simply closes. When re-opened, it doesn't remember the entry that was viewed.

### Operating System

Linux

### Operating System Version

6.0.11-gentoo

### Web Browser

Chrome

### Browser Version

Chromium 108.0.5359.124

### Build Version

2022.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2022-12-26 21:30
Hi @mrusme, thank you for your report.

This is a duplicate of #1798, please see #1798 (comment) closing that issue.

Closing this now.

**Closed** 2022-12-26 21:31 UTC
Labels: bug, browser
