### ISSUE TITLE
Bitwarden fails to decode access token.

### ISSUE THREAD

**Issue by nexussapphire** [bitwarden/clients#9455] opened 2024-05-31 13:35 UTC
### Steps To Reproduce

1)Download the app-image or install it from your distro(arch).
2) Login successfully
3) Wait forever for a throbber to finish spinning(It doesn't).
4)See in terminal ```Error: The name is not activatable
Error: Failed to decode access token: JWT must have 3 parts```
**Flatpak**
1) install flatpak
2) Try to log in and get must have 3 parts error

### Expected Result

Database loads and passwords are usable.

### Actual Result

Throbber just keeps spinning.

### Additional Context

```[lee@Monolith Downloads]$ ./Bitwarden-2024.5.0-x86_64.AppImage
MESA-LOADER: failed to open nvidia_drm: /usr/lib/gbm/nvidia_drm_gbm.so: cannot open shared object file: No such file or directory (search paths /usr/lib/gbm, suffix _gbm)
08:30:55.301 › State version: 60
08:30:55.305 › Migrator MinVersionMigrator (to version 3) should migrate: false - up
08:30:55.305 › Migrator RemoveEverBeenUnlockedMigrator (to version 4) should migrate: false - up
08:30:55.306 › Migrator AddKeyTypeToOrgKeysMigrator (to version 5) should migrate: false - up
08:30:55.306 › Migrator RemoveLegacyEtmKeyMigrator (to version 6) should migrate: false - up
08:30:55.306 › Migrator MoveBiometricAutoPromptToAccount (to version 7) should migrate: false - up
08:30:55.306 › Migrator MoveStateVersionMigrator (to version 8) should migrate: false - up
08:30:55.306 › Migrator MoveBrowserSettingsToGlobal (to version 9) should migrate: false - up
08:30:55.306 › Migrator EverHadUserKeyMigrator (to version 10) should migrate: false - up
08:30:55.307 › Migrator OrganizationKeyMigrator (to version 11) should migrate: false - up
08:30:55.307 › Migrator MoveEnvironmentStateToProviders (to version 12) should migrate: false - up
08:30:55.307 › Migrator ProviderKeyMigrator (to version 13) should migrate: false - up
08:30:55.307 › Migrator MoveBiometricClientKeyHalfToStateProviders (to version 14) should migrate: false - up
08:30:55.307 › Migrator FolderMigrator (to version 15) should migrate: false - up
08:30:55.307 › Migrator LastSyncMigrator (to version 16) should migrate: false - up
08:30:55.307 › Migrator EnablePasskeysMigrator (to version 17) should migrate: false - up
08:30:55.307 › Migrator AutofillSettingsKeyMigrator (to version 18) should migrate: false - up
08:30:55.307 › Migrator RequirePasswordOnStartMigrator (to version 19) should migrate: false - up
08:30:55.308 › Migrator PrivateKeyMigrator (to version 20) should migrate: false - up
08:30:55.308 › Migrator CollectionMigrator (to version 21) should migrate: false - up
08:30:55.308 › Migrator CollapsedGroupingsMigrator (to version 22) should migrate: false - up
08:30:55.308 › Migrator MoveBiometricPromptsToStateProviders (to version 23) should migrate: false - up
08:30:55.308 › Migrator SmOnboardingTasksMigrator (to version 24) should migrate: false - up
08:30:55.308 › Migrator ClearClipboardDelayMigrator (to version 25) should migrate: false - up
08:30:55.308 › Migrator RevertLastSyncMigrator (to version 26) should migrate: false - up
08:30:55.308 › Migrator BadgeSettingsMigrator (to version 27) should migrate: false - up
08:30:55.308 › Migrator MoveBiometricUnlockToStateProviders (to version 28) should migrate: false - up
08:30:55.308 › Migrator UserNotificationSettingsKeyMigrator (to version 29) should migrate: false - up
08:30:55.309 › Migrator PolicyMigrator (to version 30) should migrate: false - up
08:30:55.309 › Migrator EnableContextMenuMigrator (to version 31) should migrate: false - up
08:30:55.309 › Migrator PreferredLanguageMigrator (to version 32) should migrate: false - up
08:30:55.309 › Migrator AppIdMigrator (to version 33) should migrate: false - up
08:30:55.309 › Migrator DomainSettingsMigrator (to version 34) should migrate: false - up
08:30:55.309 › Migrator MoveThemeToStateProviderMigrator (to version 35) should migrate: false - up
08:30:55.309 › Migrator VaultSettingsKeyMigrator (to version 36) should migrate: false - up
08:30:55.310 › Migrator AvatarColorMigrator (to version 37) should migrate: false - up
08:30:55.310 › Migrator TokenServiceStateProviderMigrator (to version 38) should migrate: false - up
08:30:55.310 › Migrator MoveBillingAccountProfileMigrator (to version 39) should migrate: false - up
08:30:55.310 › Migrator OrganizationMigrator (to version 40) should migrate: false - up
08:30:55.310 › Migrator EventCollectionMigrator (to version 41) should migrate: false - up
08:30:55.310 › Migrator EnableFaviconMigrator (to version 42) should migrate: false - up
08:30:55.310 › Migrator AutoConfirmFingerPrintsMigrator (to version 43) should migrate: false - up
08:30:55.310 › Migrator UserDecryptionOptionsMigrator (to version 44) should migrate: false - up
08:30:55.310 › Migrator MergeEnvironmentState (to version 45) should migrate: false - up
08:30:55.310 › Migrator DeleteBiometricPromptCancelledData (to version 46) should migrate: false - up
08:30:55.310 › Migrator MoveDesktopSettingsMigrator (to version 47) should migrate: false - up
08:30:55.310 › Migrator MoveDdgToStateProviderMigrator (to version 48) should migrate: false - up
08:30:55.310 › Migrator AccountServerConfigMigrator (to version 49) should migrate: false - up
08:30:55.311 › Migrator KeyConnectorMigrator (to version 50) should migrate: false - up
08:30:55.311 › Migrator RememberedEmailMigrator (to version 51) should migrate: false - up
08:30:55.311 › Migrator DeleteInstalledVersion (to version 52) should migrate: false - up
08:30:55.311 › Migrator DeviceTrustServiceStateProviderMigrator (to version 53) should migrate: false - up
08:30:55.311 › Migrator SendMigrator (to version 54) should migrate: false - up
08:30:55.311 › Migrator MoveMasterKeyStateToProviderMigrator (to version 55) should migrate: false - up
08:30:55.311 › Migrator AuthRequestMigrator (to version 56) should migrate: false - up
08:30:55.311 › Migrator CipherServiceMigrator (to version 57) should migrate: false - up
08:30:55.311 › Migrator RemoveRefreshTokenMigratedFlagMigrator (to version 58) should migrate: false - up
08:30:55.311 › Migrator KdfConfigMigrator (to version 59) should migrate: false - up
08:30:55.311 › Migrator KnownAccountsMigrator (to version 60) should migrate: false - up
MESA-LOADER: failed to open nvidia_drm: /usr/lib/gbm/nvidia_drm_gbm.so: cannot open shared object file: No such file or directory (search paths /usr/lib/gbm, suffix _gbm)
MESA-LOADER: failed to open nvidia_drm: /usr/lib/gbm/nvidia_drm_gbm.so: cannot open shared object file: No such file or directory (search paths /usr/lib/gbm, suffix _gbm)
08:30:56.247 › State version: 60
08:30:56.251 › Error: The name is not activatable
08:30:56.277 › Error: The name is not activatable
08:30:56.313 › Error: The name is not activatable
(node:11072) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'setContextMenu')
    at TrayMain.updateContextMenu (/tmp/.mount_Bitwar3MB5in/resources/app.asar/main.js:88570:23)
    at MessagingMain.updateTrayMenu (/tmp/.mount_Bitwar3MB5in/resources/app.asar/main.js:87998:28)
    at MessagingMain.onMessage (/tmp/.mount_Bitwar3MB5in/resources/app.asar/main.js:87936:22)
    at MessagingMain.<anonymous> (/tmp/.mount_Bitwar3MB5in/resources/app.asar/main.js:87924:155)
    at Generator.next (<anonymous>)
    at /tmp/.mount_Bitwar3MB5in/resources/app.asar/main.js:87901:71
    at new Promise (<anonymous>)
    at messaging_main_awaiter (/tmp/.mount_Bitwar3MB5in/resources/app.asar/main.js:87897:12)
    at IpcMainImpl.<anonymous> (/tmp/.mount_Bitwar3MB5in/resources/app.asar/main.js:87924:83)
    at IpcMainImpl.emit (node:events:517:28)
(Use `bitwarden --trace-warnings ...` to show where the warning was created)
(node:11072) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
08:31:00.660 › Checking for update
08:31:01.202 › Update for version 2024.5.0 is not available (latest version: 2024.5.0, downgrade is disallowed).
08:31:04.976 › Error: The name is not activatable
08:31:04.977 › Error: The name is not activatable
08:31:04.982 › Error: The name is not activatable
(node:11072) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'setContextMenu')
    at TrayMain.updateContextMenu (/tmp/.mount_Bitwar3MB5in/resources/app.asar/main.js:88570:23)
    at MessagingMain.updateTrayMenu (/tmp/.mount_Bitwar3MB5in/resources/app.asar/main.js:87998:28)
    at MessagingMain.onMessage (/tmp/.mount_Bitwar3MB5in/resources/app.asar/main.js:87936:22)
    at MessagingMain.<anonymous> (/tmp/.mount_Bitwar3MB5in/resources/app.asar/main.js:87924:155)
    at Generator.next (<anonymous>)
    at /tmp/.mount_Bitwar3MB5in/resources/app.asar/main.js:87901:71
    at new Promise (<anonymous>)
    at messaging_main_awaiter (/tmp/.mount_Bitwar3MB5in/resources/app.asar/main.js:87897:12)
    at IpcMainImpl.<anonymous> (/tmp/.mount_Bitwar3MB5in/resources/app.asar/main.js:87924:83)
    at IpcMainImpl.emit (node:events:517:28)
(node:11072) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
08:31:04.987 › Error: The name is not activatable
08:31:05.002 › Error: Failed to decode access token: JWT must have 3 parts```

### Operating System

Linux

### Operating System Version

archlinux 6.9.2-zen1-1-zen

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.5.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-05-31 13:47
Duplicate of https://github.com/bitwarden/clients/issues/8651

**Comment by djsmith85** [comment] 2024-05-31 13:49
Hi @nexussapphire 

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/8651#issuecomment-2093261158.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2024-05-31 13:49 UTC
Labels: bug, desktop
