### ISSUE TITLE
Spinner is spinning forever and application cannot load vault. 

### ISSUE THREAD

**Issue by aldehydkrotonowy** [bitwarden/clients#9239] opened 2024-05-17 19:08 UTC
### Steps To Reproduce

1. Download **Bitwarden-2024.4.3-x86_64.AppImage** from [bitwarden.com](https://bitwarden.com/download/ )
2. login with master password
3. that's it

### Expected Result

Items in my vault loaded 

### Actual Result

Spinner is spinning forever and application cannot load vault. 

### Screenshots or Videos

![Bitwarden_spinner](https://github.com/bitwarden/clients/assets/12972380/449c15ac-882a-4383-8eb6-a181b9b4c710)

### Additional Context

With version **Bitwarden-2024.4.1-x86_64.AppImage** I had the same error as mentioned in [issue 7254](https://github.com/bitwarden/clients/issues/7254). Moreover when I tried to create new item and save it I had  error: "Failed to decode access token. JWT must have 3 parts"

OS:
- Kubuntu 22.04
- KDE Plasma Version: 5.24.7
- KDE Frameworks Version: 5.92.0
- Qt Version: 5.15.3
- Kernel Version: 6.5.0-35-generic (64-bit)
- Graphics Platform: X11

Bitwarden build version - more readable
- Version 2024.4.3
- Shell 28.3.1
- Renderer 120.0.6099.291
- Node 18.18.2
- Architecture x64

### Operating System

Linux

### Operating System Version

Ubuntu 22.04.4 LTS

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2024.4.3 Shell 28.3.1 Renderer 120.0.6099.291 Node 18.18.2 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by mawcs** [comment] 2024-05-17 20:12
I have a similar issue, except mine is stuck after entering my MFA code. 

![image](https://github.com/bitwarden/clients/assets/12551755/53a726f5-b910-4e19-8767-00374790b513)

I have this problem with both the .deb installer and the .appimage installer. I also experienced stalled logins with the FlatPak and Snap versions in the Discover store.


### System
Operating System: Kubuntu 24.04
KDE Plasma Version: 5.27.11
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.13
Kernel Version: 6.8.0-31-generic (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-4790K CPU @ 4.00GHz
Memory: 31.0 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 4600
Manufacturer: ASUS
Product Name: All Series

### Bitwarden
Version 2024.4.3
Shell 28.3.1
Renderer 120.0.6099.291
Node 18.18.2
Architecture x64

**Comment by gustavo-dotcom** [comment] 2024-05-17 20:37
I'm having this issue too, it never loads my vault. Downloaded from the Snap store.

*OS*
Ubuntu 22.04.4

*Version*
Version 2024.4.3
Shell 28.3.1
Renderer 120.0.6099.291
Node 18.18.2
Architecture x64

![image](https://github.com/bitwarden/clients/assets/130378554/79c2249b-bb49-4a32-9012-40775d41b877)

**Comment by TroyBW** [comment] 2024-05-18 00:16
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: [https://github.com/bitwarden/clients/issues/8651](https://github.com/bitwarden/clients/issues/8651). 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by TroyBW** 2024-05-18 00:16 UTC
Labels: bug, desktop
