### ISSUE TITLE
Bitwarden MacOS client opens and closes repeatedly

### ISSUE THREAD

**Issue by subdesign** [bitwarden/clients#11725] opened 2024-10-26 07:26 UTC
### Steps To Reproduce

no steps to reproduce, it just happens.

### Expected Result

stay fixed in the Dock ?

### Actual Result

closes then opens then closes etc..

### Screenshots or Videos

![bitwarden_bug](https://github.com/user-attachments/assets/bdab6b76-d33c-41a5-b5ac-ccef4ed92b63)

### Additional Context

This behaviour is new, didn't expected until yesterday. If I **restart** the computer, it doesn't come up, but after some time, somehow starts to open itself and then close itself and repeat until I restart again, or open Activity Monitor and **Force quit** the main executable

### Operating System

macOS

### Operating System Version

Monterey 12.7.6

### Web Browser

Chrome

### Browser Version

its not a browser problem, but native client

### Build Version

Version 2024.10.0 (31484)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by safisher** [comment] 2024-10-27 09:25
I believe this is coming from the DuckDuckGo integration. I got this behavior to stop when I disabled Bitwarden as the  DuckDuckGo password manager. This behavior only started with the latest Bitwarden Mac update (Oct 22).

**Comment by safisher** [comment] 2024-10-27 09:29
This may be a duplicate of #11692

**Comment by daniellbw** [comment] 2024-10-28 06:32
Hi there!

Thank you for your report, it seems like it is a duplicate of this one #11692

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by daniellbw** 2024-10-28 06:32 UTC
Labels: bug, browser

**Comment by subdesign** [comment] 2024-11-03 09:23
> I believe this is coming from the DuckDuckGo integration. I got this behavior to stop when I disabled Bitwarden as the DuckDuckGo password manager. This behavior only started with the latest Bitwarden Mac update (Oct 22).

true. disabling DuckDuckGo integration checkbox stops this behaviour.
