### ISSUE TITLE
Bitwarden 2024.10.1 opens but Window is not displayed on Windows 11/MacOS 15

### ISSUE THREAD

**Issue by JaneX8** [bitwarden/clients#11654] opened 2024-10-22 11:57 UTC
### Steps To Reproduce

On two different Windows 11 devices (Lenovo Thinkpad) laptops. Bitwarden icons shows in the start menu when opened but the window is not displayed. Bitwarden-Installer-2024.10.1.exe. I also tried alternative installers such as `scoop` and from the Microsoft Store. None of them worked. Also when hovered over the 'active app icon' in the start menu the thumbnail shows an empty screen and the app windows isn't shown. Running as administrator also didn't fix the issue. Both machines tested had not have Bitwarden (or as far as I know, any other Electron-based app) installed before. Neither of those laptops used an external screen.

I controlled both machines remotely using AnyDesk. This has worked before with prior versions but not with this one.

### Expected Result

Bitwarden window displayed as normal.

### Actual Result

App starts but window doesn't open/show.

### Additional Context

I tried ALT+SPACE to maximize and move the window as suggested here: https://www.reddit.com/r/Bitwarden/comments/1e5wzxq/comment/lsfajgu/ but without success. The context menu opened but the window still didn't show up. Also in the AppData Roaming folder I opened data.json and set window to maximized true and restarted but also no success. Restarting Windows altogether didn't work either.

### Operating System

Windows

### Operating System Version

11 Pro

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment] 2024-10-23 01:48
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by haffinn** [comment] 2024-10-23 15:35
Same thing happening for me for 2024.10.0 on MacOs (Sequoia 15.0.1) from AppStore.

**Comment by fbucek** [comment] 2024-10-23 17:31
Very same thing. 2024.10.0 on  macOS also Sequoia 15.0.1 Application unusable.
Menu is not visible ( couriously when I create screenshot on saved picture there is menu visible. )
Window application is not visible at all, but obstructs other windows like it is there, but not visible at all. So It is not possible to click on application which is "behind" invisible bitwarden window.

**Comment by JaneX8** [comment] 2024-10-23 18:23
I have two users restored to the web version because the desktop version became unusable. I'm unfortunately not able to provide more details now, only that I remember having a very similar (perhaps identical) issue a few years ago with another Electron-based app, however I forgot what was needed to fix it. I just remember it was specifically related to, and affecting all Electron based apps on a machine. Maybe thats not the case now, but it should be easy to exclude and test for anyone who runs in the issue:
- Does this issue only affect Bitwarden Desktop app or any other Electron based app?

I think that might be helpful information for debugging purposes.

**Comment by yangskyboxlabs** [comment] 2024-10-23 20:15
Desktop auto-updated this morning to 2024.10.1 and I'm having the same issue.

Windows 10 Pro 22H2.

**Comment by yangskyboxlabs** [comment] 2024-10-23 20:33
The app appears to load, and accept input, but is invisible.

If I drag _just the right spot_ I can grab the window the trancelucency effect of Windows makes it visible.
https://github.com/user-attachments/assets/211141cd-94a7-42eb-b57b-e0d4e664853a  (~8s mark)

**Comment by PantACRO4life** [comment] 2024-10-24 00:22
same issue here updated from preview version to 2024.10.1 behavior is the same

**Comment by trmartin4** [comment] 2024-10-24 01:26
Hello.  Thank you for your reports.

Could you check the `app.log` file located [in your OS-specific app file location](https://bitwarden.com/help/data-storage/#on-your-local-machine) to see if there are any errors that occur when opening the application?

**Comment by xiringuelu** [comment] 2024-10-24 11:28
I had exactly the same issue, but I have found that it only happens when I open the application on the secondary monitor connected via DisplayLink.

If I open it or move the transparent window to my Macbook screen, it displays fine.

I hope this is helpful, or at least a hint.

**Comment by JaneX8** [comment] 2024-10-24 11:59
> I had exactly the same issue, but I have found that it only happens when I open the application on the secondary monitor connected via DisplayLink.
> 
> If I open it or move the transparent window to my Macbook screen, it displays fine.
> 
> I hope this is helpful, or at least a hint.

I can confirm that the issue appeared on two different laptops who were not using any secondary or external screen, simply their own built-in display.

**Comment by haffinn** [comment] 2024-10-24 12:03
> I had exactly the same issue, but I have found that it only happens when I open the application on the secondary monitor connected via DisplayLink.
> 
> If I open it or move the transparent window to my Macbook screen, it displays fine.
> 
> I hope this is helpful, or at least a hint.

Just figured out the same for me. It was not an issue before the update though and does not happen for any other electron based apps that I can see.

**Comment by trmartin4** [comment] 2024-10-24 13:21
Hello, thank you for your reports.

We have an idea of what the root cause may be, but we have not been able to reproduce this internally.  We have reverted the suspected culprit and have produced new builds to see if they resolve the issue for you.  If you are comfortable doing so, could you try installing the desktop client from the appropriate build for your OS [here](https://github.com/bitwarden/clients/actions/runs/11499869600)?

⚠️ Please note that is a development build and has not been through our full QA process, so please plan to uninstall it and reinstall the production version once this issue has been diagnosed and fixed.

**Comment by fbucek** [comment] 2024-10-24 14:30
> We have an idea of what the root cause may be, but we have not been able to reproduce this internally. We have reverted the suspected culprit and have produced new builds to see if they resolve the issue for you. If you are comfortable doing so, could you try installing the desktop client from the appropriate build for your OS [here](https://github.com/bitwarden/clients/actions/runs/11499869600)?

Current version 2024.10.2 (31868) ( from link ) solved this issue for me.

**Comment by PantACRO4life** [comment] 2024-10-24 14:33
> Hello, thank you for your reports.
> 
> We have an idea of what the root cause may be, but we have not been able to reproduce this internally. We have reverted the suspected culprit and have produced new builds to see if they resolve the issue for you. If you are comfortable doing so, could you try installing the desktop client from the appropriate build for your OS [here](https://github.com/bitwarden/clients/actions/runs/11499869600)?
> 
> ⚠️ Please note that is a development build and has not been through our full QA process, so please plan to uninstall it and reinstall the production version once this issue has been diagnosed and fixed.




I would but running the installer gave me an error.
![image](https://github.com/user-attachments/assets/e3d4dbfb-3afd-46aa-858b-6fb70d09e187)

**Comment by audaines** [comment] 2024-10-24 15:23
The reverted version resolved this issue on Windows 11 Pro for me. But as [PantACRO4life](https://github.com/PantACRO4life) noted above your installer is broken for Bitwarden-Installer-2024.10.2.exe.

**Comment by trmartin4** [comment] 2024-10-24 15:31
@audaines @PantACRO4life thank you for letting us know.  We're looking into that as well.

**Comment by PantACRO4life** [comment] 2024-10-24 15:35
> @audaines @PantACRO4life thank you for letting us know. We're looking into that as well.


so after trying to run the dev build and failing I had to re-installed it cuz it had unistalled my current bugged version 10.1.
So I re-downloaded the 2024.10.1 official installer and it did install 2024.10.2. which was fine. 

I had to update the driver of my 4090 and after a reboot the bitwarden app act the same as before. being invisible.


I attached some log starting from oct 21 til today.
[bitwarden-app.log](https://github.com/user-attachments/files/17509353/bitwarden-app.log)

**Comment by yangskyboxlabs** [comment] 2024-10-24 16:04
> We have an idea of what the root cause may be, but we have not been able to reproduce this internally. We have reverted the suspected culprit and have produced new builds to see if they resolve the issue for you.

Working as expected in dev build.

If the screenshot prevention is the culprit, my specific case is likely interaction with Parsec.

I tried 2024.10.1 on a non-remote Windows 11 machine and the GUI was visible as expected.

**Comment by dani-garcia** [comment] 2024-10-24 16:18
> > Hello, thank you for your reports.
> > We have an idea of what the root cause may be, but we have not been able to reproduce this internally. We have reverted the suspected culprit and have produced new builds to see if they resolve the issue for you. If you are comfortable doing so, could you try installing the desktop client from the appropriate build for your OS [here](https://github.com/bitwarden/clients/actions/runs/11499869600)?
> > ⚠️ Please note that is a development build and has not been through our full QA process, so please plan to uninstall it and reinstall the production version once this issue has been diagnosed and fixed.
> 
> I would but running the installer gave me an error. ![image](https://private-user-images.githubusercontent.com/6643071/379814902-e3d4dbfb-3afd-46aa-858b-6fb70d09e187.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3ODY1NTgsIm5iZiI6MTcyOTc4NjI1OCwicGF0aCI6Ii82NjQzMDcxLzM3OTgxNDkwMi1lM2Q0ZGJmYi0zYWZkLTQ2YWEtODU4Yi02ZmI3MGQwOWUxODcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjRUMTYxMDU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTgxY2I1ZTI1MjBjNzAyMjVhYTYyMDJmZGI0YTFlMGUwMjFiMzI0N2UyZGQyNjNkM2YxZjU4MTMzNjY3ODZkYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Ie38c9kn5VeViHHmIhjx_4Gqhj12869GJKEb3j17gdA)

I think the installers in the dev builds don't work by default as they try to download the release files from the production servers and fail as they don't exist.

One workaround to that is downloading the `Bitwarden-Installer-2024.10.2.exe` and `bitwarden-2024.10.2-x64.nsis.7z`, placing them in the same folder, and then running the installer. That way the installer will use the local file instead of trying to download it. You can also use the portable version, which works correctly.

**Comment by PantACRO4life** [comment] 2024-10-24 16:39
> > We have an idea of what the root cause may be, but we have not been able to reproduce this internally. We have reverted the suspected culprit and have produced new builds to see if they resolve the issue for you.
> 
> Working as expected in dev build.
> 
> If the screenshot prevention is the culprit, my specific case is likely interaction with Parsec. Beyond screen streaming, we have Parsec's various privacy features enabled.
> 
> I tried 2024.10.1 on a non-remote Windows 11 machine and the GUI was visible as expected.

there must be something else, I tried without parsec installed. I unistall Parsec and bitwarden and reinstalled bitwarden but it was the same invisible gui.

**Comment by audaines** [comment] 2024-10-24 16:46
> > > We have an idea of what the root cause may be, but we have not been able to reproduce this internally. We have reverted the suspected culprit and have produced new builds to see if they resolve the issue for you.
> > 
> > 
> > Working as expected in dev build.
> > If the screenshot prevention is the culprit, my specific case is likely interaction with Parsec. Beyond screen streaming, we have Parsec's various privacy features enabled.
> > I tried 2024.10.1 on a non-remote Windows 11 machine and the GUI was visible as expected.
> 
> there must be something else, I tried without parsec installed. I unistall Parsec and bitwarden and reinstalled bitwarden but it was the same invisible gui.

Perhaps it's still not 10.2? You can do as [dani-garcia](https://github.com/dani-garcia) instructed. Or what I did was download bitwarden-2024.10.2-x64.nsis.7z and copied its contents into C:\Program Files\Bitwarden overwriting whatever is in there.

**Comment by PantACRO4life** [comment] 2024-10-24 17:18
> > > > We have an idea of what the root cause may be, but we have not been able to reproduce this internally. We have reverted the suspected culprit and have produced new builds to see if they resolve the issue for you.
> > > 
> > > 
> > > Working as expected in dev build.
> > > If the screenshot prevention is the culprit, my specific case is likely interaction with Parsec. Beyond screen streaming, we have Parsec's various privacy features enabled.
> > > I tried 2024.10.1 on a non-remote Windows 11 machine and the GUI was visible as expected.
> > 
> > 
> > there must be something else, I tried without parsec installed. I unistall Parsec and bitwarden and reinstalled bitwarden but it was the same invisible gui.
> 
> Perhaps it's still not 10.2? You can do as [dani-garcia](https://github.com/dani-garcia) instructed. Or what I did was download bitwarden-2024.10.2-x64.nsis.7z and copied its contents into C:\Program Files\Bitwarden overwriting whatever is in there.

Alright so I did the installation moving the nsis.7z inthe 10.2 exe folder after wiping both parsec and bitwarden.
All that connected via VNC. 10.2 is fine on that dev build. Then I reinstalled Parsec with privacy mode enable with its virtual display ParsecPDA. Rebooted connected to the pc via parsec. 

Bitwarden still display ok.
![image](https://github.com/user-attachments/assets/e09e39b8-87be-409a-b717-6ba7f0154ba3)

I also try that new experimental build on the parsec host and bitwarden still run just fine. I mean it is visually there.
![image](https://github.com/user-attachments/assets/a88a2ba8-a6a6-41ac-9eed-5633b667d82a)

**Comment by fung-jay** [comment] 2024-10-24 19:54
I have a similar problem. I launched the Bitwarden app (2024.10.1) in WIndows 11 Home and got the launch screen where I entered my email address and it went to the next screen where I entered the password. The spinner came on but nothing happened. I went to the task manager (Ctrl+Alt+Del) and saw there were 4 Bitwarden tasks. I killed them and restarted (also rebooted my computer) but got the same result. I uninstalled and reinstalled but the outcome was exactly the same. The mobile version and browser extensions all work fine except the desktop version.  What can I do?

**Comment by josue-palmera** [comment] 2024-10-25 16:39
Same issue here, M2 Pro Mac with MacOS 15.0.1

**Comment by CHerSun** [comment] 2024-10-25 19:54
I also have the issue of invisible window for 2024.10.1. But with a caveat:
- locally, on my machine - it works perfectly fine
- remotely (I needed to help my elder mother, which leaves pretty far) - invisible window. 

So I guess it's a streaming prevention or something like that. Problem is, for me this is a huge blocker, as I DO have to help remotely often (can't drive a thousand KM for each small problem). I'm using Microsoft Windows built-in Quick Assist normally, if that helps.

**Comment by JaneX8** [comment] 2024-10-25 20:55
Just to clarify my original post and after reading the other comments the issue in my case also appeared using remote controlled machines over AnyDesk. However the window wasn't visible according to the users who were physically at their machine during the remote session too.

I've added it into the original question.

**Comment by trmartin4** [comment] 2024-10-28 19:13
Thank you everyone for the feedback.  We'll be addressing this with a release of the desktop early this week.

**Comment by BombusAlpinus** [comment] 2024-10-29 09:58
i'm also facing this issue when remote supporting users via e.g. teamviewer. user in front of physically device is able to see the application but the remote supporter not. hopefully the version where the "prevent screenshot" feature was rolled back [https://github.com/bitwarden/clients/pull/11685](url) will be released soon...

**Comment by trmartin4** [comment] 2024-10-29 14:25
Hello.

We have released an updated [desktop](https://github.com/bitwarden/clients/releases/tag/desktop-v2024.10.2) today - version `2024.10.2`.  The release is available on our Github page above, and it has been submitted to app stores for review.

**Closed by trmartin4** 2024-10-29 14:25 UTC
Labels: bug, desktop
