### ISSUE TITLE
Bitwarden extension with Firefox breaking website rendering

### ISSUE THREAD

**Issue by sylvain-prt** [bitwarden/clients#10064] opened 2024-07-11 10:00 UTC
### Steps To Reproduce

If the bitwarden extension is activated, the rendering of Zimbra webmail is broken
![image](https://github.com/bitwarden/clients/assets/53967022/02b517a4-caca-4fd2-869d-a6f987959e6a)

### Expected Result

it should not prevent the rendering of the webmail if the extension is activated
expected rendering : 
![image](https://github.com/bitwarden/clients/assets/53967022/15c539f5-5359-43ce-a1aa-4192ce455f92)

### Actual Result

the rendering is broken
![image](https://github.com/bitwarden/clients/assets/53967022/02b517a4-caca-4fd2-869d-a6f987959e6a)

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/53967022/02b517a4-caca-4fd2-869d-a6f987959e6a)

### Additional Context

This is only affecting Firefox with bitwarden extension activated

rendering is not impacted with chrome/edge

### Operating System

Windows

### Operating System Version

windows 11 23H2 - 22631.3737

### Web Browser

Firefox

### Build Version

127.0.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sylvain-prt** [comment] 2024-07-11 10:03
Firefox updated to 128.0 
still the same issue

**Comment by djsmith85** [comment] 2024-07-11 10:11
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/9618.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2024-07-11 10:11 UTC
Labels: bug, web
