### ISSUE TITLE
bitwarden desktop linux starts white screen and unresponsive

### ISSUE THREAD

**Issue by shalom938** [bitwarden/clients#5628] opened 2023-06-16 09:59 UTC
### Steps To Reproduce

using opensuse tumbleweed with gnome desktop, i run bitwarden on startup with gnome tweaks startup applications.
since the latest update bitwarden start with white screen and unresponsive, can't even close it. i need to kiil it.
then when starting again it starts ok.

shalom@shin-opensuse:~$> ps -ef|grep bitwarden
shalom    3887  3352  0 12:48 ?        00:00:00 bwrap --args 39 bitwarden
shalom    4049  3887  0 12:48 ?        00:00:00 bwrap --args 39 bitwarden
shalom    4053  4049  0 12:48 ?        00:00:02 /app/Bitwarden/bitwarden
shalom    4123  4053  0 12:48 ?        00:00:00 /app/Bitwarden/bitwarden --type=zygote --no-zygote-sandbox
shalom    4133  4067  0 12:48 ?        00:00:00 bwrap --args 41 /app/bin/zypak-helper child - /app/Bitwarden/bitwarden --type=zygote
shalom    4190  4049  0 12:48 ?        00:00:00 bwrap --args 41 /app/bin/zypak-helper child - /app/Bitwarden/bitwarden --type=zygote
shalom    4205  4190  0 12:48 ?        00:00:00 /app/Bitwarden/bitwarden --type=zygote
shalom    4588  4123  0 12:48 ?        00:00:00 /app/Bitwarden/bitwarden --type=gpu-process --enable-crash-reporter=c6919053-54f1-41df-8598-a544f0a6de53,no_channel --user-data-dir=/home/shalom/.var/app/com.bitwarden.desktop/config/Bitwarden --gpu-preferences=WAAAAAAAAAAgAAAIAAAAAAAAAAAAAAAAAABgAAAAAAA4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAIAAAAAAAAAABAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAIAAAAAAAAAA== --shared-files --field-trial-handle=0,i,12362357785027438591,186120273960141484,131072 --disable-features=SpareRendererForSitePerProcess
shalom    4653  4053  0 12:48 ?        00:00:00 /app/Bitwarden/bitwarden --type=utility --utility-sub-type=network.mojom.NetworkService --lang=en-US --service-sandbox-type=none --enable-crash-reporter=c6919053-54f1-41df-8598-a544f0a6de53,no_channel --user-data-dir=/home/shalom/.var/app/com.bitwarden.desktop/config/Bitwarden --shared-files=v8_context_snapshot_data:100 --field-trial-handle=0,i,12362357785027438591,186120273960141484,131072 --disable-features=SpareRendererForSitePerProcess
shalom    4681  4053  0 12:48 ?        00:00:02 /app/Bitwarden/bitwarden --type=renderer --enable-crash-reporter=c6919053-54f1-41df-8598-a544f0a6de53,no_channel --user-data-dir=/home/shalom/.var/app/com.bitwarden.desktop/config/Bitwarden --app-path=/app/Bitwarden/resources/app.asar --no-sandbox --no-zygote --first-renderer-process --lang=en-US --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=4 --time-ticks-at-unix-epoch=-1686908872084355 --launch-time-ticks=33209528 --shared-files=v8_context_snapshot_data:100 --field-trial-handle=0,i,12362357785027438591,186120273960141484,131072 --disable-features=SpareRendererForSitePerProcess
shalom    8122  4313  0 12:54 pts/0    00:00:00 grep --color=auto bitwarden
shalom@shin-opensuse:~$> kill -9 4588
shalom@shin-opensuse:~$> kill -9 4123
shalom@shin-opensuse:~$> kill -9 3887 4049 4053 4123 4133 4190 4205 4588
bash: kill: (4588) - No such process
shalom@shin-opensuse:~$> 

### Expected Result

expecting bitwarden to start correctly at startup

### Actual Result

bitwarden starts unresponsive

### Operating System

Linux

### Installation method

Other

### Build Version

2023.5.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by galen1423** [comment] 2023-06-17 10:10
Hello,

I am using same Bitwarden version in Ubuntu 23.10 with Gnome Shell (44.2) - bug appears too with Ubuntu 22.04 LTS - and i can see this bug sometimes at start computer but rarely. For me, it happens each time i close my session and re-open it.
In this case, no needs to kill process, i click panel icon (show/hide) to retrieve an operational window and close it.

I notice that by putting a delay of about ten seconds at the start of the application, the bug does not occur.

**Comment by Findarato** [comment] 2023-10-13 17:26
Any update on this issue? I have been experiencing it on two separate Fedora 38 based Gnome desktops, both after doing a full reinstall.  I have commented on the other issue related to this.

**Comment by thatLeaflet** [comment] 2023-10-14 01:05
I'm also experiencing this issue. Using Plasma 5.27.8 Wayland on Fedora 39 beta. Never experienced this issue on Gnome.

Running Bitwarden 2023.9.2, the unoffical flatpak build.

It loads regularly for a few seconds, then turns blank, like this:

![image](https://github.com/bitwarden/clients/assets/80165419/ae769e95-c960-4854-9315-c29ea3f56be9)

**Comment by Alladyn47** [comment] 2023-10-14 22:48
I installed the Bitwarden-2023.9.2 application (tried .AppImage, .dep, Flatpak), but when I start authorization, the window is empty (black or white if installed via Flatpak). The window is restored for a while if you select View>Restart.
Operating System: Debian GNU/Linux 12
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.103.0
Qt Version: 5.15.8
Kernel Version: 6.1.0-13-amd64 (64-bit)
Graphics Platform: X11
Processors: 8 × 12th Gen Intel® Core™ i3-12100F
Memory: 15.5 ГиБ of RAM
Graphics Processor: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: B660M GAMING X DDR4
![Screenshot_20231015_024257](https://github.com/bitwarden/clients/assets/26250259/0768eb27-892b-4cf3-b66e-564acb02c746)
![Screenshot_20231015_024346](https://github.com/bitwarden/clients/assets/26250259/3f556625-c63f-4b7b-b992-701ba7380aec)
![Screenshot_20231015_024417](https://github.com/bitwarden/clients/assets/26250259/eec7de2d-6e37-448a-92ad-f8e682e5dfbf)

**Comment by ablonewolf** [comment] 2023-10-17 11:27
I am facing the same issue on Nobara Linux 38; plasma version is 5.27.8, graphics platform is X11. I have tried the three approaches: app image, flatpak and rpm apps.

**Comment by peroyhav** [comment] 2023-10-18 10:52
I'm experiencing the same on Linux Mint 21.2 Cinnamon Desktop after updating the flatpak app today

**Comment by djsmith85** [comment] 2023-10-18 14:44
For the more recent reports on this issue, they are likely a duplicate of #6560. Please upgrade to `2023.9.3`

**Comment by sixerstyle** [comment] 2023-11-01 12:01
version  2023.9.3 has the  same error   in fedora 38 with kde plasma.
with gnome it works

**Comment by swssl** [comment] 2023-11-02 08:52
I am facing the same issue on Kubuntu 22.04. Bitwarden opens a white screen, then blindly typing the master password unlocks the password safe.

**Comment by arislas** [comment] 2023-11-27 16:42
Same error on 6.6.2-arch1-1.

**Closed** 2024-02-21 12:13 UTC
Labels: bug, desktop

**Comment by rahilarious** [comment] 2024-02-26 03:38
I'm having this problem with >=Bitwarden-2024.1.0-x86_64.AppImage. Older Bitwarden-2023.12.1-x86_64.AppImage was working fine
