### ISSUE TITLE
Issue with inline autofill for identity

### ISSUE THREAD

**Issue by fabriziobagala** [bitwarden/clients#10788] opened 2024-08-29 09:01 UTC
### Steps To Reproduce

1. Go to 'https://www.synology.com/it-it/products/DS224+'
2. Scroll down slowly

### Expected Result

The inline menu in the upper left corner is not displayed.

### Actual Result

The inline menu in the upper left corner is displayed.

### Screenshots or Videos

![screenshot](https://github.com/user-attachments/assets/5e23f3fb-6e53-4822-98d0-4747e040a233)

### Additional Context

I use the following extensions:

- Decentraleyes 2.0.19
- Fakespot Fake Amazon Reviews and eBay Sellers 1.3.5
- Tampermonkey 5.1.1
- uBlock Origin 1.59.0

### Operating System

macOS

### Operating System Version

14.6.1

### Web Browser

Firefox

### Browser Version

129.0.2

### Build Version

2024.8.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by c3JpbmkK** [comment] 2024-08-29 09:14
I've also observed this in few other instances, but managed to capture only one screenshot 
![Screenshot 2024-08-29 at 11 12 59](https://github.com/user-attachments/assets/3fb0cf02-6abf-4fe7-b710-f7d44f76a604)

**Comment by NovaSilentium** [comment] 2024-08-29 13:28
Duplicate of #0494

**Comment by NovaSilentium** [comment] 2024-08-29 13:29
Duplicate of #10494

**Comment by NovaSilentium** [comment] 2024-08-29 13:31
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/10494
If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed** 2024-08-29 13:31 UTC
Labels: bug, browser

**Comment by fabriziobagala** [comment] 2024-08-29 14:02
@NovaSilentium does not seem to me to be a duplicate of either. This is a bug that you are having with the introduction of the inline menu for identity feature. Also, issue #10494 is closed.

@c3JpbmkK noted that there is another problem with the introduction of this feature.

Please reopen the issue and ask the team to consider resolving this bug that does not allow a proper user experience.
Thank you.

**Comment by c3JpbmkK** [comment] 2024-08-29 14:12
Meanwhile I stumbled across few more sites where the Identity pops up when it shouldnt, atleast it didnt prior (this week, maybe last days)
1. portal.azure.com (few sites where names are used)
2. Argocd UI (in the name filter)
3. Rfc editor (https://www.rfc-editor.org/ top right)

**Comment by c3JpbmkK** [comment] 2024-08-29 14:35
I'm not sure if https://github.com/bitwarden/clients/pull/10533 made things better or worse 

browser: firefox 129.0.1
extension version: 2024.8.0

**Comment by fabriziobagala** [comment] 2024-08-29 14:51
> I'm not sure if #10533 made things better or worse
> 
> browser: firefox 129.0.1 extension version: 2024.8.0

Effectively #10533 seems correct to me and perhaps the issue should be solved.
