### ISSUE TITLE
Cloning organizational items into several collections at once does not create separate duplicate items

### ISSUE THREAD

**Issue by Maruuv** [bitwarden/clients#9868] opened 2024-06-28 06:09 UTC
### Steps To Reproduce

1. Go to an Organizational Collection and choose a "Login" Item.
2. Click "Clone" and clone the item into two or more organizational Collections.
3. Edit one of the cloned items in one of the collections that is not the original item.
4. Verify that the changed information is also present in one of the other collections the original items was cloned to.

### Expected Result

All of the cloned Items should stay as separate entities and not be linked in any manner.

### Actual Result

The cloned items in different collections behave as the same credential and changing one of them automatically changes all of the other credentials as well.

### Operating System

Windows

### Operating System Version

11 Enterprise

### Web Browser

Microsoft Edge

### Browser Version

126.0.2592.68 

### Build Version

vault.bitwarden.eu current version

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment] 2024-06-28 11:23
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by micahblut** [comment] 2024-06-28 11:33
Hi @Maruuv, what you are describing is the intended behavior. The clone action creates a new copy of the vault item. When creating that copy, you can assign it to one or more collections.

I'd be interested to hear more about the use-case you have that requires copies of an item across a variety of collections, rather than just assigning a single item to those collections. 

Thanks!

**Closed by micahblut** 2024-06-28 11:33 UTC
Labels: bug, browser

**Comment by Maruuv** [comment] 2024-06-28 12:40
Hi!

Alright, I see the point now - it's just that I thought that each Clone in a separate Collection is another separate entity, but it is not. It only creates **one** clone that is just shared with different Collections as apposed to creating **several** separate clones into different Collections. I don't think this behaviour is quite well documented, even though it may be intended. 

The use case behind this is importing large, very similar credentials without the need to reconfigure all of the fields again except the unique parts, e.g keeping all of the notes and usernames, but creating unique passwords.
