### ISSUE TITLE
KDE wallet says "application misbehaving" and sync not working

### ISSUE THREAD

**Issue by mamama1** [bitwarden/clients#9190] opened 2024-05-15 11:01 UTC
### Steps To Reproduce

First (few?) starts of Bitwarden Desktop app on Fedora 40 KDE spin seem to work fine, but at some point when starting the app, I get a popup from KDE Wallet telling me "There have been repeated failed attempts to gain access to a wallet. An application may be misbehaving." and sync stops working.

Log says this:

```
flatpak run com.bitwarden.desktop
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: deb
12:56:44.462 › State version: 48
12:56:44.464 › Migrator MinVersionMigrator (to version 3) should migrate: false - up
12:56:44.464 › Migrator RemoveEverBeenUnlockedMigrator (to version 4) should migrate: false - up
12:56:44.465 › Migrator AddKeyTypeToOrgKeysMigrator (to version 5) should migrate: false - up
12:56:44.465 › Migrator RemoveLegacyEtmKeyMigrator (to version 6) should migrate: false - up
12:56:44.465 › Migrator MoveBiometricAutoPromptToAccount (to version 7) should migrate: false - up
12:56:44.465 › Migrator MoveStateVersionMigrator (to version 8) should migrate: false - up
12:56:44.465 › Migrator MoveBrowserSettingsToGlobal (to version 9) should migrate: false - up
12:56:44.465 › Migrator EverHadUserKeyMigrator (to version 10) should migrate: false - up
12:56:44.465 › Migrator OrganizationKeyMigrator (to version 11) should migrate: false - up
12:56:44.466 › Migrator MoveEnvironmentStateToProviders (to version 12) should migrate: false - up
12:56:44.466 › Migrator ProviderKeyMigrator (to version 13) should migrate: false - up
12:56:44.466 › Migrator MoveBiometricClientKeyHalfToStateProviders (to version 14) should migrate: false - up
12:56:44.466 › Migrator FolderMigrator (to version 15) should migrate: false - up
12:56:44.466 › Migrator LastSyncMigrator (to version 16) should migrate: false - up
12:56:44.466 › Migrator EnablePasskeysMigrator (to version 17) should migrate: false - up
12:56:44.466 › Migrator AutofillSettingsKeyMigrator (to version 18) should migrate: false - up
12:56:44.466 › Migrator RequirePasswordOnStartMigrator (to version 19) should migrate: false - up
12:56:44.466 › Migrator PrivateKeyMigrator (to version 20) should migrate: false - up
12:56:44.466 › Migrator CollectionMigrator (to version 21) should migrate: false - up
12:56:44.466 › Migrator CollapsedGroupingsMigrator (to version 22) should migrate: false - up
12:56:44.466 › Migrator MoveBiometricPromptsToStateProviders (to version 23) should migrate: false - up
12:56:44.466 › Migrator SmOnboardingTasksMigrator (to version 24) should migrate: false - up
12:56:44.466 › Migrator ClearClipboardDelayMigrator (to version 25) should migrate: false - up
12:56:44.466 › Migrator RevertLastSyncMigrator (to version 26) should migrate: false - up
12:56:44.466 › Migrator BadgeSettingsMigrator (to version 27) should migrate: false - up
12:56:44.466 › Migrator MoveBiometricUnlockToStateProviders (to version 28) should migrate: false - up
12:56:44.466 › Migrator UserNotificationSettingsKeyMigrator (to version 29) should migrate: false - up
12:56:44.466 › Migrator PolicyMigrator (to version 30) should migrate: false - up
12:56:44.467 › Migrator EnableContextMenuMigrator (to version 31) should migrate: false - up
12:56:44.467 › Migrator PreferredLanguageMigrator (to version 32) should migrate: false - up
12:56:44.467 › Migrator AppIdMigrator (to version 33) should migrate: false - up
12:56:44.467 › Migrator DomainSettingsMigrator (to version 34) should migrate: false - up
12:56:44.467 › Migrator MoveThemeToStateProviderMigrator (to version 35) should migrate: false - up
12:56:44.467 › Migrator VaultSettingsKeyMigrator (to version 36) should migrate: false - up
12:56:44.467 › Migrator AvatarColorMigrator (to version 37) should migrate: false - up
12:56:44.467 › Migrator TokenServiceStateProviderMigrator (to version 38) should migrate: false - up
12:56:44.467 › Migrator MoveBillingAccountProfileMigrator (to version 39) should migrate: false - up
12:56:44.467 › Migrator OrganizationMigrator (to version 40) should migrate: false - up
12:56:44.467 › Migrator EventCollectionMigrator (to version 41) should migrate: false - up
12:56:44.467 › Migrator EnableFaviconMigrator (to version 42) should migrate: false - up
12:56:44.467 › Migrator AutoConfirmFingerPrintsMigrator (to version 43) should migrate: false - up
12:56:44.467 › Migrator UserDecryptionOptionsMigrator (to version 44) should migrate: false - up
12:56:44.467 › Migrator MergeEnvironmentState (to version 45) should migrate: false - up
12:56:44.467 › Migrator DeleteBiometricPromptCancelledData (to version 46) should migrate: false - up
12:56:44.467 › Migrator MoveDesktopSettingsMigrator (to version 47) should migrate: false - up
12:56:44.467 › Migrator MoveDdgToStateProviderMigrator (to version 48) should migrate: false - up
LaunchProcess: failed to execvp:
xdg-settings
12:56:44.984 › State version: 48
12:56:45.017 › Error: No password found
12:56:45.020 › Error: No password found
12:56:45.026 › Error: No password found
12:56:45.026 › Error: No password found
12:56:45.036 › Error: No password found
12:56:45.041 › Error: No password found
12:56:45.042 › Error: No password found
12:56:45.054 › Error: No password found
12:56:45.054 › Error: No password found
12:56:45.056 › Error: No password found
12:56:45.057 › Error: No password found
12:56:45.057 › Error: No password found
12:56:45.060 › Error: No password found
12:56:45.062 › Error: No password found
12:56:45.070 › Error: No password found
12:56:45.070 › Unable to fetch ServerConfig: Failed to decode access token: JWT must have 3 parts
12:56:45.071 › Error: No password found
12:56:45.075 › Error: No password found
12:56:45.079 › Error: No password found
12:56:46.050 › Error: No password found
12:56:46.051 › Error: No password found
12:56:46.052 › Error: No password found
12:56:48.049 › Error: No password found
12:56:48.053 › Error: No password found
12:56:55.036 › Error: No password found
12:56:55.039 › Error: No password found
12:57:05.037 › Error: No password found
12:57:05.041 › Error: No password found
12:57:05.428 › Error: No password found
12:57:05.474 › Error: No password found
12:57:05.478 › Error: No password found
12:57:05.485 › Error: No password found
12:57:05.485 › Error: No password found
12:57:05.486 › Error: No password found
12:57:05.486 › Error: No password found
12:57:05.490 › Error: No password found
12:57:05.507 › Error: No password found
12:57:05.508 › Error: No password found
12:57:05.519 › Error: No password found
12:57:05.644 › Finished search indexing
12:57:05.645 › Error: No password found
12:57:05.664 › Error: Failed to decode access token: JWT must have 3 parts
12:57:09.383 › Error: No password found
12:57:09.394 › Error: No password found
12:57:15.038 › Error: No password found
12:57:25.037 › Error: No password found
12:57:35.038 › Error: No password found
12:57:45.033 › Error: No password found
12:57:55.040 › Error: No password found
12:58:05.038 › Error: No password found
12:58:15.038 › Error: No password found
12:58:25.039 › Error: No password found
12:58:35.039 › Error: No password found

```

### Expected Result

no "misbehaving" according to KDE wallet and working sync.

### Actual Result

"misbehaving" according to KDE wallet and non-working sync ("Syncing failed").

### Operating System

Linux

### Operating System Version

Fedora 40 KDE spin

### Installation method

Other

### Build Version

Flatpak 2024.4.1, Shell 28.2.8, Renderer 120.0.6099.291, Node 18.18.2, Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-05-15 11:08
Duplicate of https://github.com/bitwarden/clients/issues/8651

**Comment by djsmith85** [comment] 2024-05-15 11:08
Hi @mamama1

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/8651#issuecomment-2093261158.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2024-05-15 11:08 UTC
Labels: bug, desktop
