### ISSUE TITLE
Safari: "[Cannot Decrypt]"

### ISSUE THREAD

**Issue by KernelBypass** [bitwarden/clients#9557] opened 2024-06-09 21:50 UTC
### Steps To Reproduce

1. Go to 'Safari'
2. Click on 'click BW icon'

### Expected Result

Show vault items

### Actual Result

Shows "cannot decrypt"

### Screenshots or Videos

<img width="365" alt="image" src="https://github.com/bitwarden/clients/assets/62620821/1d5485b2-fe20-4259-b430-0023a629faa3">

### Additional Context

just updated BW and got this. Seems like the re-emergence of this bug from 2023:
https://github.com/bitwarden/clients/issues/6759

P.S. I am seeing so many bugs, I don't even file 90% of them. I am a paid user and seriously thinking about switching.

### Operating System

macOS

### Web Browser

Safari

### Browser Version

17.4.1 

### Build Version

2024.5.0

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by KernelBypass** [comment] 2024-06-09 21:53
FYI: Disabling and re-enabling extension did not help.

**Comment by sammbw** [comment] 2024-06-09 23:23
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/clients/issues/9524

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by sammbw** 2024-06-09 23:23 UTC
Labels: bug, browser
