### ISSUE TITLE
Reprompted master pw doesnt work

### ISSUE THREAD

**Issue by rcmdkick** [bitwarden/clients#6153] opened 2023-08-30 21:16 UTC
### Steps To Reproduce

1. create a note/login/etc
2. check the "prompt master pw"
3. save
4. tries to edit it or seeing pw
5. enter the Correct pw and click OK

### Expected Result

6. it enables editing/access to pw

### Actual Result

6. nothing happens

### Additional Context

Version 2023.8.2
Shell 24.1.1
Renderer 112.0.5615.50
Node 18.14.0
Architecture x64

### Operating System

Windows

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.8.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Szaamaan** [comment] 2023-08-30 21:24
I have the same issue and this also happens with the browser addon. Only way to access master password protected elements is to go through the bitwarden.com online vault.

**Comment by sammbw** [comment] 2023-08-31 02:37
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by Szaamaan** [comment] 2023-08-31 15:13
@trmartin4 Yes, I'm using biometrics.

**Comment by rcmdkick** [comment] 2023-09-01 11:23
I dont use biometrics, and its at my PC

**Comment by Netrvin** [comment] 2023-09-02 01:54
Having the same problem
Windows Desktop/Browser Extension: No response
Android: Crashed

**Comment by SergeantConfused** [comment] 2023-09-03 18:10
Hello everyone,

1. Could you please let us know if performing a clean new installation addresses this behaviour? Instructions can be found below.
2. Could you please let us know if you had (Unlock with biometrics) activated on the Bitwarden client (https://bitwarden.com/help/biometrics/) you had experienced this on?

Android: You can uninstall Bitwarden, turn the phone off (long press) and back on, install Bitwarden anew from the Google Play Store or F-Droid.
Extension: You can uninstall the extension, remove its leftover data (https://bitwarden.com/help/data-storage/), reboot the computer, and install it anew.
Desktop: You can uninstall the desktop client, remove its leftover data (https://bitwarden.com/help/data-storage/), reboot the computer, and install it anew.


Thank you in advance for your assistance,

**Comment by Szaamaan** [comment] 2023-09-03 18:49
I re-installed the Desktop app (and all findings described in this reply are related to the Desktop app only - I've not tested the browser addon nor the Android client for similar behaviour). Upon new install accessing master-password protected elements worked. After setting all the settings (inc. biometrics) and restarting the Bitwarden desktop client I was no longer able to access these elements with the same issue as originally described. However I've noticed that these elements DO work if I initially unlock Bitwarden using the master password (even if biometrics are configured).

**Comment by Szaamaan** [comment] 2023-09-03 18:55
More info: the browser addon and Android app seem to have similar behaviour - the master password prompt on protected items works correctly when the addon / app is initially unlocked using the master password.

**Comment by SergeantConfused** [comment] 2023-09-05 17:57
Hi @Szaamaan,

Thank you. Yes, it appears that this happens only when the client is unlocked using biometrics; This also is what I am experiencing.

If anyone sees this differently, please post a comment and let us know.


All the best,

**Comment by gkl1368** [comment] 2023-09-07 03:38
I have the same problem on macOS and browser extension. It only happened on unlock with touchid.

**Comment by jelondon** [comment] 2023-09-07 09:44
I'm having all of the same problems. It seems to be intermittent. The extra level of security of master password re-prompt is a pretty fundamental feature, especially when people continue to rely on basic phone / device unlock PINs/actions. Can I humbly request an acceleration of the response/fix for this issue? 

I would describe this problem as basically an unresponsive textbox control on the password re-prompt. It doesn't seem to post back at all - I can enter gibberish as a password and it doesn't reject it or close the text box. Same if enter no password. Cancel option works consistently.

I'm not a coder, but perhaps we're looking at an issue with validation?

**Comment by Szaamaan** [comment] 2023-09-08 05:55
Found another issue related to the master password prompt / protected items. This one has to do with accessing the vault via the website (i.e. vault.bitwarden.com).

If the vault is unlocked using a device then protected items can be accessed WITHOUT entering the master password. Specifically the prompt doesn't show up at all and the elements can be accessed immediately.

**Comment by warnerchad** [comment] 2023-09-08 14:20
I updated the BitWarden Mac app to 2023.8.3 this morning, hoping it would solve the problem of not being able to get past the master password reprompt after logging into BitWarden using biometric authentication, but it didn't. The Safari extension is still 2023.8.2.

**Closed** 2023-09-11 14:40 UTC
Labels: bug, browser, desktop

**Comment by igarca** [comment] 2023-09-11 20:45
I experience the same issue. Chromium 116.0.5845.96.

**Comment by jelondon** [comment] 2023-09-12 11:56
Not fixed for me. iOS.

**Comment by pschauhan480** [comment] 2023-09-13 16:40
Just mentioning more details that this issue happens when touchid is enabled and was resolved after clean install of Bitwarden without touchid enabled

**Comment by Szaamaan** [comment] 2023-09-15 08:23
I just downloaded a new update for the Bitwarden desktop client, and the issue is still there. What's the release cycle after a bug has been marked as closed?

**Comment by derrynj** [comment] 2023-09-15 08:30
> I just downloaded a new update for the Bitwarden desktop client (2023.8.4), and the issue is still there. What's the release cycle after a bug has been marked as closed?

You realise the answer to your question is IN the question: "2023.8.4" i.e. 4th August 2023 - long before this was solved, before it was even reported. I think they do a client release once a month or so, but don't quote me on it. Would be nice if they pushed it faster, but I doubt it.

**Comment by Szaamaan** [comment] 2023-09-15 08:40
@derrynj Good point. I failed to "compare" the release date vs current date and the PR date... TBH I kind of assumed, without thinking, that the version would have been "today".

In my defence the coffee hasn't kicked in properly. 😅

**Comment by warnerchad** [comment] 2023-09-15 13:15
Based on https://github.com/bitwarden/clients/releases, it looks like Desktop v2023.8.4 was released within the last 24 hours. The version numbers don't appear to indicate the date of release.

**Comment by warnerchad** [comment] 2023-09-16 11:47
I updated the BitWarden Mac app to 2023.8.4 this morning, hoping it would solve the problem of not being able to get past the master password reprompt after logging into BitWarden using biometric authentication, but it didn't. The Safari extension is still 2023.8.2.

**Comment by Szaamaan** [comment] 2023-09-18 19:24
> They're not doing anything special to send a Hotfix for this issue even if is a big issue and they're charging people for their paid service. For what I can see they will wait until the next release 2023.9 to have the patch included on the update.

To be fair, this is NOT a blocker. It's annoying, yes, but there IS a workaround for accessing master-password protected items. Just unlock Bitwarden using the master-password and then these items will work fine.

**Comment by zahtec** [comment] 2023-09-19 00:50
Issue seems to be on android as well. After a recent update this same behavior occurs.

**Comment by warnerchad** [comment] 2023-09-22 13:51
This is fixed for me, after updating the Mac app to 2023.8.4, which updated the Safari extension to 2023.9.1.
