### ISSUE TITLE
Firefox plugin stopped logging in: "i is undefined" error (with correct credentials)

### ISSUE THREAD

**Issue by lbraglia** [bitwarden/clients#6542] opened 2023-10-10 11:28 UTC
### Steps To Reproduce

1. Install Firefox plugin
2. try to login 

### Expected Result

You login correctly and access all your password by the plugin

### Actual Result

i get the red message "i is undefined" error and doesn't login

Note that inserted login/masterpassword is correct given that it works on bitwarden.com (tried various attempts).

### Operating System

Linux

### Operating System Version

Debian 12 stable

### Web Browser

Firefox

### Browser Version

102.15.1esr-1~deb12u1

### Build Version

Version 2023.9.1, taken from https://addons.mozilla.org/en-US/firefox/addon/bitwarden-password-manager/

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2023-10-10 12:20
Duplicate of #4076

**Comment by djsmith85** [comment] 2023-10-10 15:41
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/4076.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2023-10-10 15:41 UTC
Labels: bug, browser

**Comment by mseri** [comment] 2023-10-15 21:58
I got the same problem after firefox updated itself today. It is the first time I have this issue and the suggestions from #4076 didn't work for me
