### ISSUE TITLE
Vault timeouts "On system sleep" and "On system lock" do not allow to use Touch ID for unlocking vault

### ISSUE THREAD

**Issue by Alejandro-FA** [bitwarden/clients#5777] opened 2023-07-10 21:54 UTC
### Steps To Reproduce

Device where this issue is reproduced: MacBook Pro 16-inch, 2021

1. On macOS `System Settings`, go to `Lock Screen` and set `Require password after screen saver begins or displayed is turned off to` to `Immediately`.

2. Open the Bitwarden macOS app and (after unlocking your vault) go to `Settings` > `SECURITY`.

3. Set `Vault timeout` to either `On system sleep` or `On system lock`. 

4. Set `Vault timeout action` to `Lock`.

5. Check `Unlock with Touch ID`.

6. Leave all other options of the `SECURITY` section unchecked.

7. Close the laptop lid and open it again. If you've done step 1, you should be prompted to input your password or use Touch ID.

### Expected Result

Once the laptop user is logged in, the Bitwarden vault should appear as "locked", with the possibility to unlock it with either the master password or with Touch ID.

### Actual Result

Once the laptop user is logged in, the Bitwarden vault appears as "locked", but it is not possible to unlock it with Touch ID.

### Additional Context

**IMPORTANT NOTE**: Locking the screen of the laptop by going to the menu bar of macOS and clicking on the Apple logo > `Lock Screen` does not reproduce the issue.

### Operating System

macOS

### Operating System Version

13.4.1

### Installation method

Mac App Store

### Build Version

2023.5.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by mada199122** [comment] 2023-07-16 05:09
in Version 2023.7.0 (9969) the bug is still present...

**Comment by djsmith85** [comment] 2023-07-16 08:43
Duplicate of https://github.com/bitwarden/clients/issues/2572

**Closed by djsmith85** 2023-07-16 08:43 UTC
Labels: bug, desktop
