### ISSUE TITLE
No Password found

### ISSUE THREAD

**Issue by TinF0ilHat1** [bitwarden/clients#5363] opened 2023-05-04 12:18 UTC
### Steps To Reproduce

Hi there,

I was running journalctl and noticed i got this error like every minute or so. Do you have any idea?
Thanks

    mag 04 10:39:50 com.bitwarden.desktop.desktop[2127]: 10:39:50.196 › Error: No password found
    mag 04 10:40:00 com.bitwarden.desktop.desktop[2127]: 10:40:00.189 › Error: No password found
    mag 04 10:40:10 com.bitwarden.desktop.desktop[2127]: 10:40:10.195 › Error: No password found
    mag 04 10:40:20 com.bitwarden.desktop.desktop[2127]: 10:40:20.189 › Error: No password found

    flatpak remote-info --log flathub com.bitwarden.desktop
    ID: com.bitwarden.desktop
    Ref: app/com.bitwarden.desktop/x86_64/stable
    Arch: x86_64
    Branch: stable
    Collection: org.flathub.Stable
    Commit: dfc8934ef0fe3af74310cb71e6ee0ddcef160778ebd1ce050ea93131388b698c
    Parent: bfdf7aa113404715892e06cd6f09b09aefd8e2c1c4bf2daec22e3169e291f2ca
    Subject: Update 2 modules (fe727ae8)
    Date: 2023-04-26 19:24:32 +0000

I have:
allow browser integration = false
unlock with PIN = true

### Expected Result

Any idea what does it mean & how to fix it?

### Actual Result

mag 04 10:39:50 com.bitwarden.desktop.desktop[2127]: 10:39:50.196 › Error: No password found
mag 04 10:40:00 com.bitwarden.desktop.desktop[2127]: 10:40:00.189 › Error: No password found
mag 04 10:40:10 com.bitwarden.desktop.desktop[2127]: 10:40:10.195 › Error: No password found
mag 04 10:40:20 com.bitwarden.desktop.desktop[2127]: 10:40:20.189 › Error: No password found

### Operating System

Linux

### Operating System Version

Pop OS

### Shell

Bash

### Build Version

22.04

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by simonwiles** [comment] 2023-05-08 01:44
Exactly the same here -- it's every 10 seconds, not every minute (same as in the logs @TinF0ilHat1 posted).

**Comment by atjbramley** [comment] 2023-05-08 16:14
Hi @TinF0ilHat1, 

Thank you for your report! 

I was able to reproduce this issue on Manjaro, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by Freeman73** [comment] 2023-05-09 19:27
I'm using the *.AppImage version on 64bit Debian, I've been getting BiometricsService error for quite a bit, but since few days, there is also a lot of "Error: No password found" pushed to stdout. After pushing the output rapidly, it slows down to once every 10 seconds. If it is looking for some hash produced by biometric input device and can't find the device, it would explain the behavior.


```
$Bitwarden-2023.4.0-x86_64.AppImage &
(node:248130) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `bitwarden --trace-deprecation ...` to show where the warning was created)
(node:248130) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'init')
    at BiometricsService.<anonymous> (/tmp/.mount_BitwarO0gQu0/resources/app.asar/main.js:44459:55)
    at Generator.next (<anonymous>)
    at /tmp/.mount_BitwarO0gQu0/resources/app.asar/main.js:44425:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/tmp/.mount_BitwarO0gQu0/resources/app.asar/main.js:44421:12)
    at BiometricsService.init (/tmp/.mount_BitwarO0gQu0/resources/app.asar/main.js:44458:16)
    at Main.<anonymous> (/tmp/.mount_BitwarO0gQu0/resources/app.asar/main.js:52469:46)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_BitwarO0gQu0/resources/app.asar/main.js:52366:58)
(node:248130) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[248164:0509/202239.787045:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
20:22:40.593 › Error: No password found
20:22:40.614 › Error: No password found
20:22:40.615 › Error: No password found
20:22:40.622 › Error: No password found
20:22:40.634 › TypeError: Cannot read properties of undefined (reading 'osSupportsBiometric')
    at BiometricsService.<anonymous> (/tmp/.mount_BitwarO0gQu0/resources/app.asar/main.js:44464:55)
    at Generator.next (<anonymous>)
    at /tmp/.mount_BitwarO0gQu0/resources/app.asar/main.js:44425:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/tmp/.mount_BitwarO0gQu0/resources/app.asar/main.js:44421:12)
    at BiometricsService.osSupportsBiometric (/tmp/.mount_BitwarO0gQu0/resources/app.asar/main.js:44463:16)
    at DesktopCredentialStorageListener.<anonymous> (/tmp/.mount_BitwarO0gQu0/resources/app.asar/main.js:44648:59)
    at Generator.next (<anonymous>)
    at /tmp/.mount_BitwarO0gQu0/resources/app.asar/main.js:44576:71
    at new Promise (<anonymous>)
20:22:40.637 › TypeError: Cannot read properties of undefined (reading 'osSupportsBiometric')
    at BiometricsService.<anonymous> (/tmp/.mount_BitwarO0gQu0/resources/app.asar/main.js:44464:55)
    at Generator.next (<anonymous>)
    at /tmp/.mount_BitwarO0gQu0/resources/app.asar/main.js:44425:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/tmp/.mount_BitwarO0gQu0/resources/app.asar/main.js:44421:12)
    at BiometricsService.osSupportsBiometric (/tmp/.mount_BitwarO0gQu0/resources/app.asar/main.js:44463:16)
    at BiometricsService.<anonymous> (/tmp/.mount_BitwarO0gQu0/resources/app.asar/main.js:44474:58)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_BitwarO0gQu0/resources/app.asar/main.js:44422:58)
20:22:41.599 › Error: No password found
20:22:41.906 › Error: No password found
20:22:41.936 › Error: No password found
20:22:41.976 › Error: No password found
20:22:42.001 › Error: No password found
20:22:42.003 › Error: No password found
20:22:42.010 › Error: No password found
20:22:42.031 › Error: No password found
20:22:42.034 › Error: No password found
20:22:42.034 › Error: No password found
20:22:42.068 › Error: No password found
20:22:42.070 › Error: No password found
20:22:42.082 › Error: No password found
20:22:42.087 › Error: No password found
20:22:43.580 › Error: No password found
20:22:44.749 › Checking for update
20:22:45.597 › Update for version 2023.4.0 is not available (latest version: 2023.4.0, downgrade is disallowed).
20:22:50.576 › Error: No password found
20:22:55.731 › Error: No password found
20:22:55.732 › TypeError: Cannot read properties of undefined (reading 'deleteBiometricKey')
    at BiometricsService.<anonymous> (/tmp/.mount_BitwarO0gQu0/resources/app.asar/main.js:44517:55)
    at Generator.next (<anonymous>)
    at /tmp/.mount_BitwarO0gQu0/resources/app.asar/main.js:44425:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/tmp/.mount_BitwarO0gQu0/resources/app.asar/main.js:44421:12)
    at BiometricsService.deleteBiometricKey (/tmp/.mount_BitwarO0gQu0/resources/app.asar/main.js:44515:16)
    at DesktopCredentialStorageListener.<anonymous> (/tmp/.mount_BitwarO0gQu0/resources/app.asar/main.js:44699:45)
    at Generator.next (<anonymous>)
    at /tmp/.mount_BitwarO0gQu0/resources/app.asar/main.js:44576:71
    at new Promise (<anonymous>)
20:22:55.747 › Error: No password found
20:22:55.747 › Error: No password found
20:22:55.748 › Error: No password found
20:22:55.749 › Error: No password found
20:22:55.777 › Error: No password found
20:22:55.803 › Error: No password found
20:22:55.906 › Error: No password found
20:22:55.923 › Error: No password found
20:23:00.576 › Error: No password found
20:23:00.599 › Error: No password found
20:23:10.576 › Error: No password found
20:23:20.576 › Error: No password found
```

**Comment by curtisbelt** [comment] 2023-05-13 22:20
+1

- Fedora Workstation 38
- Gnome 44.1
- Linux 6.2.14-300.fc38.x86_64
- Bitwarden 2023.4.0 `sudo dnf install Bitwarden-2023.4.0-x86_64.rpm`

**Comment by jbillingredhat** [comment] 2023-05-17 13:40
I am also seeing this for myself and my customers.

I did a quick dig into the code. The actual error comes from https://github.com/bitwarden/clients/blob/master/apps/desktop/desktop_native/src/password/unix.rs , which is called from https://github.com/bitwarden/clients/blob/master/apps/desktop/desktop_native/src/lib.rs#L13, but that function name ("passwords") is super generic so trying to dig in what is prompting it to be called every 10 seconds is going to be fun for someone completely unfamiliar with the code.

I suspect it has to do with the automatic vault lock timeout.

**Comment by vinodkumark369** [comment] 2023-06-05 07:22
Workaround (which I personally do not like is), Go to Settings and set Vault timeout to never. It will create a password in Gnome Keyring which will end the password not found log. Now Bitwarden will be logged in automatically which is not ideal (at least for me).

**Comment by toppk** [comment] 2023-06-13 08:39
This looks like the vaultTimeout service here:

https://github.com/bitwarden/clients/blob/master/libs/common/src/services/vaultTimeout/vaultTimeout.service.ts#LL50C47-L50C47

Which eventually calls cryptoService.hasKeyStored(KeySuffixOptions.Auto, userId) here:

https://github.com/bitwarden/clients/blob/master/libs/common/src/auth/services/auth.service.ts#L248

Just looking at the blame, it seems likely that this behavior was introduced with this PR:

https://github.com/bitwarden/clients/commit/2e2849b4def0534f3f72b7a84c3183ab0b1589f2


the todo comment in that PR is interesting.  perhaps there's a behavior on non-linux desktops that avoids this issue.

**Comment by m8ram** [comment] 2023-07-18 07:13
Any update on this?
I'm still seeing this on:
* Fedora 38
* Gnome 44.2
* Flatpak version 2023.7.0

**Comment by manuelmazzuola** [comment] 2023-08-04 07:38
Same here:

- Archlinux
- Gnome 44.3
- Linux 6.4.7-arch1-1

**Comment by database64128** [comment] 2023-08-05 19:10
FWIW, this also affects Windows. The desktop client spams in the "Security" category in Event Viewer with a credential read event every 10 seconds. I only discovered this when I noticed there were constant writes to the event log files.

**Comment by RobLW** [comment] 2023-11-22 15:51
Getting this on CachyOS (Arch Linux) every 10 seconds during the boot.
Linux 6.6.2
KDE Plasma 5.27.9

**Comment by sup2069** [comment] 2023-12-09 18:53
Same issue.

OS: Debian/SID
Kernel: 6.5.13-1
DE: KDE

**Comment by asheriif** [comment] 2024-03-28 16:35
Is there any plan to address this? It's been almost a year and the journal is still being spammed literally every second.

**Comment by Freeman73** [comment] 2024-03-28 16:57
> Is there any plan to address this? It's been almost a year and the journal is still being spammed literally every second.

For me (*.AppImage on 64bit Debian), it's not outputting any more when the vault is unlocked.

**Comment by Freeman73** [comment] 2024-03-28 17:55
> > For me (*.AppImage on 64bit Debian), it's not outputting any more when the vault is unlocked.
> 
> i think problems arise when it is [locked]

I see, for my UC, I don't have reason to have it running while locked, so I just kill it.

I've tested and if I leave it locked and running, I also get the stdout.

**Comment by asheriif** [comment] 2024-03-29 12:00
> > Is there any plan to address this? It's been almost a year and the journal is still being spammed literally every second.
> 
> For me (*.AppImage on 64bit Debian), it's not outputting any more when the vault is unlocked.

It happens when the vault is locked, which happens when the system is idle and/or if you have auto vault timeout configured which is a pretty sane thing to do with a password manager. 

Hope the devs can make the time for this soon because it generates a tremendous amount of noise both in app.log and system journals.

**Comment by berkes** [comment] 2024-04-18 13:00
Also happens when unlocked. Might be a difference with snap.

Snap version: bitwarden 2024.4.0 108 latest/stable
OS: Ubuntu 22.04.4 LTS x86_64
Kernel: 6.5.0-27-generic
DE: Gnome

I did grant bitwarden the permission to "Read, add, change, or remove saved passwords" in snap (Software » Bitwarden » Permissions)

**Comment by boennhoff** [comment] 2024-05-13 07:47
**+1 here**... Wondering for weeks where this log spamming originates from.

I used the following keywords from the journal to look it up (without success): _kde_, _kde6_ and _plasmashell_ -- may this help another clueless user!

The mentioned **workaround** to disable the vault timeout **is definitely a no-go**!

**Comment by boennhoff** [comment] 2024-12-01 09:13
It's gone, at least with me... would love to know which version fixed it, and what the solution was. This bug could be closed...

**Comment by WebSpider** [comment] 2024-12-01 09:48
What version is this solved for you on what OS?

**Comment by m8ram** [comment] 2024-12-11 11:12
I can confirm that on Fedora 41, Gnome with flatpak version 2024.11.2 I have not seen this error anymore in the journal. Upgraded to this version on Dec 5.

**Comment by djsmith85** [comment] 2024-12-12 20:09
Thanks everyone for the reports, that this is resolved.

Closing this now.

**Closed by djsmith85** 2024-12-12 20:09 UTC
Labels: bug, desktop, cli
