### ISSUE TITLE
Unable to add attachment using CLI 2023.5.0 to self-host server

### ISSUE THREAD

**Issue by sso-bitwarden** [bitwarden/clients#5618] opened 2023-06-15 12:02 UTC
### Steps To Reproduce

1. Use the CLI to log in to a self-host server (tested on server 2023.5.0)
2. Add an attachment to an item using the command "bw create attachment"

### Expected Result

Attachment added

### Actual Result

There is an error in API logs

2023-06-10 09:41:16.891 +00:00 [Error] Unexpected end of Stream, the content may have already been read by another component.
System.IO.IOException: Unexpected end of Stream, the content may have already been read by another component.
   at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Stream.<CopyToAsync>g__Core|29_0(Stream source, Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at Bit.Core.Vault.Services.LocalAttachmentStorageService.UploadNewAttachmentAsync(Stream stream, Cipher cipher, MetaData attachmentData) in /home/runner/work/server/server/src/Core/Vault/Services/Implementations/LocalAttachmentStorageService.cs:line 40

### Additional Context

downgraded to CLI 2023.4.0 and the command works fine.

### Operating System

macOS, Linux

### Shell

Bash, Zsh

### Build Version

2023.5.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jeffbeagley** [comment] 2023-09-19 19:38
I receive this on 2023.8.2 CLI,  downgraded to 2023.4.0 CLI and still received same error. All on server version 2023.8.1

**Comment by jeffbeagley** [comment] 2023-09-19 19:56
I rebuilt CLI with nodejs 16 and is working now on 2023.8.2

**Comment by megamorf** [comment] 2023-12-13 16:53
The issue is still present in versions  `2023.9.0` and `2023.10.0`

**Comment by alsikora** [comment] 2024-06-27 08:57
Fixed on `main`

**Closed by alsikora** 2024-06-27 08:57 UTC
Labels: bug, cli
