### ISSUE TITLE
Window frame in day mode even when the system and application are in night mode.

### ISSUE THREAD

**Issue by ruizlenato** [bitwarden/clients#2649] opened 2022-05-06 21:35 UTC
### Steps To Reproduce

1. Open app.
2. Look at the application window.

### Expected Result

A dark window frame.

### Actual Result

A light window frame.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/49354525/167219139-e3c35ed8-aa41-477b-982a-f5586d8ff8eb.png)

### Operating System

Windows

### Operating System Version

Windows 11 Pro (21H1)

### Installation method

Direct Download (from bitwarden.com)

### Build Version

1.33.0

**Comment by djsmith85** [comment] 2022-07-21 10:00
Closing this as duplicate of https://github.com/bitwarden/clients/issues/2616

**Closed by djsmith85** 2022-07-21 10:00 UTC
Labels: bug, desktop
