### ISSUE TITLE
Master Password form doesn't work in Web Extension and Desktop Application

### ISSUE THREAD

**Issue by HH-Tips** [bitwarden/clients#6250] opened 2023-09-11 08:51 UTC
### Steps To Reproduce

Select an account which requires master password to copy the account's password.
1. Click on 'Copy Password Icon'
2. Compile the form with your master password
3. Click Ok or press Enter
4. Nothing happens

### Expected Result

The password was copied. 

### Actual Result

Nothing, the button Ok remains greyed (if you click on the button, else if you press enter same result but the button remains unchanged) out and nothing happens.

### Operating System

Windows

### Operating System Version

Windows 11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.8.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SaabirahMohamed** [comment] 2023-09-11 09:54
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/6153

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed** 2023-09-11 09:55 UTC
Labels: bug, desktop
