### ISSUE TITLE
Collection boxes are no longer automatically selecting when adding new items to a Collection

### ISSUE THREAD

**Issue by DrkEcho** [bitwarden/clients#8704] opened 2024-04-11 17:32 UTC
### Steps To Reproduce

Select the correct Collection for adding the new item. Create the new item.

### Expected Result

Once you selected the right Collection for adding the new item, the Collection box would automatically be selected at the bottom of the screen.

### Actual Result

Now having to manually select the correct Collection box in order to save any new items to the Collection.

### Screenshots or Videos

![Bitwarden Collection Bug](https://github.com/bitwarden/clients/assets/166742642/941236bc-b11a-4ed4-ad22-afc0ee062a25)

### Operating System

Windows

### Operating System Version

Windows 11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.4.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by StefanReppien** [comment] 2024-04-12 06:03
Same by us.
Version 2024.4.0
Shell 28.2.8
Renderer 120.0.6099.291
Node 18.18.2
Architecture x64

**Comment by cbbit** [comment] 2024-04-15 15:23
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by lukebishop121** [comment] 2024-06-18 23:55
This seems to be resolved in the new (2024.6.2) release! Thank you 👏

**Closed** 2024-06-25 09:42 UTC
Labels: bug, desktop
