### ISSUE TITLE
Application randomly prompts for authentication

### ISSUE THREAD

**Issue by mjdNjhNJ** [bitwarden/clients#7639] opened 2024-01-22 11:38 UTC
### Steps To Reproduce

1. Unlock the vault
2. Lock the vault
3. Continue using the device normally

### Expected Result

Application behaves as in early versions prompting authentication only when requested by the user.

### Actual Result

Application randomly prompts for authentication.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/129977466/1dcbbfdf-579f-40e6-b538-66d28997fa79)

### Additional Context

When selected 'Cancel' the prompt appeares again in a loop. The only solution is to exit the application.

### Operating System

macOS

### Operating System Version

14.2.1

### Installation method

Homebrew

### Build Version

2024.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-01-22 11:49
Duplicate of https://github.com/bitwarden/clients/issues/7541

**Comment by djsmith85** [comment] 2024-01-22 11:50
Hi @mjdNjhNJ,

this is a duplicate of https://github.com/bitwarden/clients/issues/7541 which has received a fix with https://github.com/bitwarden/clients/pull/7350. The changes will be included in the upcoming release (`2024.2`)

Closing this now.

Kind regards,
Daniel

**Closed by djsmith85** 2024-01-22 11:50 UTC
Labels: bug, desktop
