### ISSUE TITLE
Mac OS desktop app does not show Touch ID button after sleep from lid close

### ISSUE THREAD

**Issue by gergles** [bitwarden/clients#5591] opened 2023-06-11 02:28 UTC
### Steps To Reproduce

1. Enable the vault timeout to "On system sleep", the vault timeout action to "Lock", and enable (only) "Unlock with Touch ID" and "Approve login requests" in the Security preferences.
2. Unlock the vault with the password, or quit the app and relaunch it and log in with Touch ID.
3. Put the system (M2 MacBook Pro) to sleep by closing the lid.
4. Reopen the lid.

Note: Sleep from the Apple menu or `pmset sleepnow` in the Terminal do not cause this problem, only sleep by closing the lid.

### Expected Result

The "Login with Touch ID" button should be present and clicking it should provide a Touch ID authorization prompt.

### Actual Result

The "Unlock with Touch ID" button is not present and the Bitwarden app must be restarted to get it to appear. On restart of the Bitwarden app, the "Unlock with Touch ID" button appears and works normally.

(Note: the Bitwarden > Lock all vaults menu option does correctly show the Touch ID login too, it's only recovering from sleep caused by closing the lid that does not work.)

### Operating System

macOS

### Operating System Version

13.4

### Installation method

Mac App Store

### Build Version

2023.5.0 (9051)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment] 2023-06-12 12:37
Hi @gergles,

Thank you for your report. I was able to reproduce this behaviour and have flagged this matter to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.


Thank you again,

**Comment by mada199122** [comment] 2023-06-28 11:39
I confirm the bug.

**Comment by mada199122** [comment] 2023-07-16 05:08
in Version 2023.7.0 (9969) the bug is still present...

**Comment by djsmith85** [comment] 2023-07-16 08:39
Duplicate of https://github.com/bitwarden/clients/issues/2572

**Closed by djsmith85** 2023-07-16 08:39 UTC
Labels: bug, desktop

**Comment by mada199122** [comment] 2023-07-16 09:42
why did you close this issue? It is not the same thing with respect to #2572 
Here the Mac is not use in clamshell mode

**Comment by mada199122** [comment] 2023-08-29 12:11
the bug is still present even in the 2023.8.2

**Comment by z0r-run** [comment] 2023-12-18 21:11
I can repoduce the bug too on a _MacBook Air M2, 2022 (macOS 14.2)_ but the difference is that I'm not running bitwarden on this system. So I'm pretty sure that this isn't a bug of bitwarden itself but of macOS.


> *Edit: If you press CMD+L at that screen, it would refresh and offer you to unlock with Touch ID.

The solution for this bug from @SergeantConfused didn't work for my MacBook model but by coincidence I found another easy and also user friendly way to get along with it until apple fix this bug:

1. Put the MacBook to sleep by closing the lid.
2. Reopen the lid.
             --> Now you should be forced to type the password instead of using Touch ID to unlock.

3. Press "esc" to lock the screen manually.
4. Press any key on your keyboard / trackpad to wake up your system.
5. Touch ID can be used again to unlock the system.

**Comment by mbentley** [comment] 2023-12-30 11:00
I have the same issue where I do not get presented with the Touch ID unlock option.  CMD + L does allow the screen to reload and then I can unlock it fine using Touch ID but the thing I am curious about from others is whether or not you are able to type your master password to unlock successfully when it is not showing the Touch ID option.  When Touch ID isn't showing for me, the app just does nothing after I type my password and click unlock.  It doesn't give any sort of success or failure message.  I do know my master password but I found that to be an odd behavior and wasn't sure if anyone else was seeing the same.
