### ISSUE TITLE
Firefox bitwarden extension autofills clear input fields

### ISSUE THREAD

**Issue by blastrock** [bitwarden/clients#8072] opened 2024-02-23 18:31 UTC
### Steps To Reproduce

1. Register your bitwarden master password in bitwarden itself
2. Enable autofill
3. Go to https://vault.bitwarden.com/#/settings/security/change-password
4. Login as usual

### Expected Result

My master password should not show on my screen. Bitwarden should not autofill input fields that are not of type password.

### Actual Result

The bitwarden extension autofills the `Previous password` field *and* the `Master password hint`, and my password shows in clear text on the screen.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/1370530/c38e7162-d96c-4b7b-9262-19bfcbed4ab3)

### Operating System

Linux

### Operating System Version

Debian unstable

### Web Browser

Firefox

### Browser Version

122.0.1

### Build Version

2024.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cagonzalezcs** [comment] 2024-02-27 22:25
@blastrock 

Thank you for this report.

I spoken with the team on this to verify the expected behavior, and the design decision to autofill passwords from login vault items into a `<input type="text">` field is indeed a deliberate choice. There are use cases where this is necessary to do, and as a result your described bug is actually behavior that is working as intended.

I'm closing this thread as a result, but please feel free to comment further.

**Closed by cagonzalezcs** 2024-02-27 22:25 UTC
Labels: bug, browser

**Comment by Tipoff4317** [comment] 2024-02-28 00:10
@blastrock

I personally hate this feature too, because I at one time exposed my master password this way and had to change it.

The workaround is to create a custom field for the password hint to be whatever hint you want to put in there.

**Comment by cagonzalezcs** [comment] 2024-02-28 16:17
@Tipoff4317 

I'll bring up your concern regarding Bitwarden's vault autofilling this value and ensure we get some kind of fix in place that mitigates that. 

This ticket describes in generality that we are autofilling "clear" (or rather `input type="text"`) input fields. Due to what I mentioned earlier, we fill those fields with intention rather than by mistake. That's to say, other websites that incorporate this kind of "password hint" field will continue to be autofilled if that action is triggered on the page. 

Regardless, I'll see if we can resolve this on our own site.
