### ISSUE TITLE
Master password re-prompt option KILLS the entry completely

### ISSUE THREAD

**Issue by wilflet** [bitwarden/clients#6384] opened 2023-09-22 22:28 UTC
### Steps To Reproduce

Create a new entry
give it a username
give it a password
select the option to enforce "Master password re-prompt"
save the new entry (this also happens to any existing entry, BTW)
try to see the password (or anything else you may have hidden)
no Master password will allow you to view anything hidden again
no Master password will allow you to edit this entry again
no Master password will allow you to delete this entry
the entry is now completely useless - an albatross in your database
PLEASE FIX THIS

### Expected Result

Whenever you are prompted for a Master password you should receive what you are looking for upon giving the correct password.

### Actual Result

Upon selecting "Master password re-prompt" option for any entry (new or existing):
The entry is locked forever.
You cannot see anything hidden - or use it to feed a browser.
You cannot edit the entry ever again.
You cannot delete the entry ever.
The program demands to see the Master password but does not respond to being given the correct (or incorrect) password.
The dropdown asking for the Master password FREEZES upon being given ANY password.  It doesn't even check the password you give it.  The program response is to do nothing when you click OK.  The entry is worse than dead wood - it bloats your database and requires you to recreate every entry you ever applied this option on - whenever you did it.

### Screenshots or Videos

https://github.com/bitwarden/clients/assets/47976779/54f982df-e904-4dde-8cee-c1f694b06909

### Additional Context

I recently asked for a fix to this 2nd password routine because it was not working properly - the entire program minimized upon giving it a good password - but at least before it was checking the password and opening up the fields for view/copy and you could delete the entry upon giving the correct password.  Whoever applied the fix for that minor glitch made an even bigger one that now has significant and irreversible impact.   You cannot even delete the dead entries.  Anyone out there using this option for any appreciable number of entries will go ballistic encountering this error.  It is a ticking time-bomb for the unaware.  Please review the earlier "fix" and debug what is happening thoroughly.  It is more than obvious that whoever worked on my earlier issue did NOT test their fix thoroughly.

### Operating System

Windows

### Operating System Version

10

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2023.8.4

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by luc-bw** [comment] 2023-09-22 23:01
Hi @wilflet,

Thank you for your report. This is a duplicate of: [bitwarden/clients#6153](https://github.com/bitwarden/clients/issues/6153)

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks

**Closed by luc-bw** 2023-09-22 23:01 UTC
Labels: bug, duplicate, desktop
