### ISSUE TITLE
Bitwarden Help/About text is unreadable

### ISSUE THREAD

**Issue by butlerrscott** [bitwarden/clients#5541] opened 2023-05-30 15:10 UTC
### Steps To Reproduce

1. Start Bitwarden from terminal.
2. Click "Help"
3. Click "About Bitwarden"
4. The dialog box that appears has only empty letter boxes.  There is no text.

![bitwarden_error](https://github.com/bitwarden/clients/assets/4777499/25db861e-96c2-4bba-a4ac-a4c6c30b4adb)

### Expected Result

Dialog box showing text containing version.

### Actual Result

Dialog box contains only empty letter-sized boxes.

### Screenshots or Videos

![bitwarden_error](https://github.com/bitwarden/clients/assets/4777499/37ca2d31-e1c6-4b52-ae7b-0ac6c5e51c37)

### Additional Context

None

### Operating System

Linux

### Operating System Version

Ubuntu 22.04.2 LTS

### Installation method

Snap

### Build Version

:-) That's what I was trying to determine when I found the bug.  I'm running the latest version.

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2023-05-30 15:17
Hi @butlerrscott and thank you for your report.

This seems to be a duplicate of https://github.com/bitwarden/clients/issues/2628.

Closing this now.

**Closed** 2023-05-30 15:17 UTC
Labels: bug, desktop
