### ISSUE TITLE
Windows Hello PIN shows behind the Bitwarden Windows Desktop Client

### ISSUE THREAD

**Issue by pilcherd** [bitwarden/clients#7658] opened 2024-01-23 18:35 UTC
### Steps To Reproduce

Run Bitwarden Desktop client (2024.1.0).
Enter master password to login (this is assuming you have logged in in the past sometime ok).
Client appears to hang.

### Expected Result

Shown Windows Hello PIN to login

### Actual Result

PIN dialog is shown hidden in background.

### Operating System

Windows

### Operating System Version

22631.30.78

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-01-23 18:37
Duplicate of https://github.com/bitwarden/clients/issues/5287

**Comment by djsmith85** [comment] 2024-01-23 18:37
Hi @pilcherd !

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/clients/issues/5287.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2024-01-23 18:37 UTC
Labels: bug, desktop
