### ISSUE TITLE
Losing focus while logging in leads to vault that can't be displayed

### ISSUE THREAD

**Issue by rootwork** [bitwarden/clients#3483] opened 2022-09-09 21:03 UTC
### Steps To Reproduce

0. Be using Yubikey 2FA for login
1. Click login on the browser extension
2. Enter your password
3. Press the Yubikey when prompted to do so
4. Click outside the extension area (losing focus) before the spinner has stopped/logging in has completed

### Expected Result

Having received a correct password and a correct Yubikey entry, Bitwarden will continue to login in the background.

### Actual Result

Until recently, Bitwarden would appear to be logged in (icon color would change) but when clicked on would have a message that no logins existed; i.e. that the vault was empty. This was really distressing the first time it happened -- I thought I had lost my entire vault! Subsequently I realized that the message was just incorrect.

When I went to reproduce this for this issue report, I saw different behavior: Now Bitwarden will appear to be logged in (icon color will change) but when clicked on it will simply display the spinner -- as if it's still in the process of logging in -- and never complete. Whether leaving it visible or clicking away, even after several minutes it still won't be logged in and functional. This is definitely better than wrongly suggesting my vault is empty, but still less than ideal.

In either case, the only solution is to force a log out.

### Screenshots or Videos

(I can take one if you want, but I assume you know what the spinning loader looks like, and that's really all I see.)

### Additional Context

I don't know if the Yubikey 2FA is a necessary condition to this occurring or if it's some mix of my OS/browser setup, but given that I was using Yubikey I wanted to include it.

Although the problem is not critical, in that if it happens I now know to just log out and log back in, it can be pretty frustrating as it is easy to unintentionally lose focus on the extension while I'm waiting for it to log in.

### Operating System

Linux

### Operating System Version

Mint 20.3

### Web Browser

Firefox

### Browser Version

104.0.2

### Build Version

2022.8.0

**Comment by tangowithfoxtrot** [comment] 2022-09-20 18:42
Hey, @rootwork.

I was able to reproduce this as well. I _think_ this is because, when the extension goes through the login process, it tries to execute an initial vault sync, which is being cancelled-out by clicking away from the extension. For what it's worth, when this happens, you can go into Settings -> Sync and see that its "last sync" date was "Never", and you can run a manual sync to have your vault items appear instead of relogging.

I _do_ think there is probably a better way that this could handle this though. I marked this as reproducible in our internal tracking system so that this behavior can be revisited in the future. 

Thanks again for reporting!

**Comment by rootwork** [comment] 2022-09-20 21:27
Glad to know it's not just me! And thanks for the helpful workaround.

**Comment by trmartin4** [comment] 2024-12-05 02:30
@rootwork we have made several improvements in this area, and we'd like to confirm whether you are still seeing this behavior.  We are no longer able to reproduce this internally, and if you can confirm this I can close the ticket.

Thank you for the report.

**Closed** 2024-12-20 05:28 UTC
Labels: bug, browser, needs-reply
