### ISSUE TITLE
Firefox extension blank after logging in with device

### ISSUE THREAD

**Issue by shiokoala** [bitwarden/clients#5833] opened 2023-07-14 07:21 UTC
### Steps To Reproduce

1. Log out of BW on extension
2. Choose 'Log in with device'
3. Approve login from smartphone app
4. Confirm that extension is logged in (popup is still open)
5. Close BW extension popup
6. Open extension again
7. Popup is empty

### Expected Result

I expect the popup to display contents

### Actual Result

There is nothing displayed on the popup

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/63235669/fa783eb7-069a-4afe-b534-0129bbac436b)

### Additional Context

If I restart the browser, the popup is fixed but the problem persists.
If I open a private windows the popup is also fixed.
If I login using passwords, the problem does not occur AFAIK.
~~The smartphone app displays the fingerprint phrase BEFORE I login using biometric authentication.~~

### Operating System

Windows

### Operating System Version

10 22H2 19045.3208

### Web Browser

Firefox

### Browser Version

115.0.2 (64-bit)

### Build Version

2023.5.1

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment] 2023-07-14 14:33
Hi @shiokoala ,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by shiokoala** [comment] 2023-07-14 14:40
Hi Aina, thanks for the response. 
I've checked again whether my "shows fingerprint phrase BEFORE logging in" comment was correct, and it may have just been a rendering glitch/bug on Android  since I cannot reproduce it. I've edited the comment to match.

**Comment by Adedamola-Aina** [comment] 2023-07-14 14:48
close as its a duplicate of this https://github.com/bitwarden/clients/issues/4878

**Closed by Adedamola-Aina** 2023-07-14 14:48 UTC
Labels: bug, browser
