### ISSUE TITLE
Constantly getting "There are no collects to list." in Bitwarden desktop client

### ISSUE THREAD

**Issue by matthewknill** [bitwarden/clients#8607] opened 2024-04-03 22:25 UTC
### Steps To Reproduce

1. Click on a collection
2. Click the plus button to add a new item
3. It says there are no collects to list

### Expected Result

It should show all the collections that are assigned with the one that you're currently in checked.

### Actual Result

It simply says "There are no collects to list." and doesn't allow me to save it or anything.

### Screenshots or Videos

Here is the shown under the collections section:
![image](https://github.com/bitwarden/clients/assets/50228686/78c216f6-b545-46b4-9ad6-2e464113fec9)

### Additional Context

Even when I select "All items" rather than an individual collection, it still mentions says "There are no collections to list."

To my knowledge, it seems to only be an issue with the Bitwarden desktop...

I've found that if I save it to my personal vault and then move to my organisation, that seems to work but obviously highly annoying to do so for everything that I add.

### Operating System

Windows

### Operating System Version

Windows 10

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-04-03 22:29
Duplicate of https://github.com/bitwarden/clients/issues/8258

**Comment by sammbw** [comment] 2024-04-04 03:20
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/clients/issues/8258

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by sammbw** 2024-04-04 03:20 UTC
Labels: bug, desktop
