### ISSUE TITLE
Error: Failed to decode access token: JWT must have 3 parts in 2024.3.2 Desktop release

### ISSUE THREAD

**Issue by moo1210** [bitwarden/clients#8662] opened 2024-04-10 10:59 UTC
### Steps To Reproduce

1. Login and/or unlock the vault on 2024.3.2

### Expected Result

You only see a only see a spinning icon

### Actual Result

My Vault should load normally

### Additional Context

Downgrading the desktop app to an older release (2024.3.2) solved the issue.

### Operating System

Windows, macOS, Linux

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.3.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment] 2024-04-10 11:06
Duplicate of #8651

**Closed** 2024-04-10 11:07 UTC
Labels: bug, desktop
