### ISSUE TITLE
Secure note is lost while editing if vault timeout expires

### ISSUE THREAD

**Issue by matejaputic** [bitwarden/clients#3720] opened 2022-10-07 12:28 UTC
### Steps To Reproduce

1. Go to Preferences > Vault timeout > 1 minute > scroll down to the bottom > Close
2. Leftmost column under Types, select Secure Note > + > Select type "Secure Note" (aside: this is a different bug. If I already selected "secure note" under Types, the Add Item drop-down should pre-select "Secure Note". Right now the default is Login)
3. Enter some information into secure note, do not click save
4. Wait until BW locks
5. Unlock BW

### Expected Result

After BW is unlocked, I would expect it to open back up to the same editing screen I was on before it auto-locked (preferred).

Less optimal but still acceptable, I would expect the portion of the note that I entered to be saved so I can find it and pick up where I left off. 

### Actual Result

After BW is unlocked, it opens to the home screen and the note I was editing is gone.

### Operating System

macOS

### Operating System Version

Monterey 12.6

### Installation method

Homebrew

### Build Version

Version 2022.9.1 (4562)

**Comment by djsmith85** [comment] 2022-10-07 13:23
Hi @matejaputic and thank you for your report.

This seems to be a duplicate of https://github.com/bitwarden/clients/issues/2579.

Closing this now.

**Closed by djsmith85** 2022-10-07 13:23 UTC
Labels: bug, desktop

**Comment by beenalongday** [comment] 2023-03-20 18:25
This was closed as a duplicate of 2579 and 2579 was closed as a duplicate of this issue. (Both closed linked to each-other on close) Can you please re-open one? This issue still occurs the client version. This not only effects secure notes but any edited and not yet saved entry, including new entries.

version 2023.2.0
shell 21.3.1
renderer 106.0.5249.191
node 16.16.0
arch x64
