### ISSUE TITLE
Master Password re-prompt fails

### ISSUE THREAD

**Issue by chraebsli** [bitwarden/clients#6283] opened 2023-09-13 20:11 UTC
### Steps To Reproduce

Default:
1. Create a Login with email & password with the "Master Password re-prompt" option.

Case 1:
1. Go to [wallet.uphold.com/login](https://wallet.uphold.com/login)
2. Click on the extension and select the entry with the re-prompt enabled
3. Enter the Master Password and click on "OK"

Case 2:
1. Click on the extension and open the entry with the re-prompt enabled
2. Click the copy password/ show password button
3. Enter the Master Password and click on "OK"

### Expected Result

Case 1: Bitwarden fills in the fields on the website
Case 2: You can see the password or the password gets copied to the clipboard

### Actual Result

Both Cases: The "OK" button gets darker and noting more happens. No fields filled out

### Screenshots or Videos

![bitwarden-error](https://github.com/bitwarden/clients/assets/73113302/df3ea51c-1ecb-421b-b3e9-c675b1d4c824)
In this picture, you can see, how the OK button just grayed out.

### Additional Context

To use these passwords, I have to go to [vault.bitwarden.com](https://vault.bitwarden.com/) and enter the password there to see the secured password. It's annoying, since I don't always have a PC/ Laptop with me and the passwords are 20 char randoms.

=> Info for those who have similar problems and don't know a workaround

### Operating System

Windows, Linux, Android

### Operating System Version

Windows 11; Android 13; Linux Manjaro

### Web Browser

Brave

### Browser Version

1.57.64

### Build Version

Brave: 2023.8.3; Android: 2023.8.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by dimadk24** [comment] 2023-09-14 04:50
> To use these passwords, I have to go to [vault.bitwarden.com](https://vault.bitwarden.com/) and enter the password there to see the secured password. It's annoying, since I don't always have a PC/ Laptop with me and the passwords are 20 char randoms.

Thank you for providing workaround! I thought this issue completely blocks me from getting my password, since it's reproducible on all other clients: windows 11 desktop app, Chrome extension (Chrome 116.0.5845.188 (Official Build) (64-bit) (cohort: Stable)), Android 12 app.

Attaching JS error details from chrome extension inspect view: https://pastebin.com/vg49EHXB

**Comment by MutedExclamation** [comment] 2023-09-14 07:52
I can confirm it's the same case with PIN. I can't open the vault through the Firefox extension.

**Comment by djsmith85** [comment] 2023-09-14 08:57
Duplicate of https://github.com/bitwarden/clients/issues/6153

**Comment by djsmith85** [comment] 2023-09-14 08:58
Hi @chraebsli, @dimadk24 

Thank you for your reports. This has previously been reporting with https://github.com/bitwarden/clients/issues/6153 for web/desktop/browser with a fix which will be included in the upcoming 2023.9-release

For mobile this has previously been reported with https://github.com/bitwarden/mobile/issues/2733 which has also received a fix to be included in the 2023.9 release.

**Closed by djsmith85** 2023-09-14 08:58 UTC
Labels: bug, browser

**Comment by djsmith85** [comment] 2023-09-14 09:00
@MutedExclamation: The issue with unlocking with PIN on Firefox is unrelated to this, but the team is aware and working on it.
