### ISSUE TITLE
Passwords in app do not display < symbols

### ISSUE THREAD

**Issue by Gerrit-Hoving** [bitwarden/clients#8557] opened 2024-03-31 17:15 UTC
### Steps To Reproduce

1. Go to the Android app
2. Navigate to a saved password item that contains a < symbol
3. Click the eye icon to display the password

### Expected Result

This should show the whole password so one can enter it

### Actual Result

The < symbol fails to display and instead text characters after it are highlighted with red like special characters

### Additional Context

I also don't see any bug report form for the Android app so the information below is not applicable. I'm in Version 2024.3.0 (9799) downloaded from the Google Play Store

### Operating System

Windows

### Installation method

Direct Download (from bitwarden.com)

### Build Version

N/A

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment] 2024-04-01 11:25
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/mobile/issues/3110

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by Greenderella** 2024-04-01 11:25 UTC
Labels: bug, desktop
