### ISSUE TITLE
[Browser Extension] [Chrome] Password Generation UI does not display constraint fields

### ISSUE THREAD

**Issue by JanMosigItemis** [bitwarden/clients#10358] opened 2024-08-01 08:50 UTC
### Steps To Reproduce

1. Go to "Generator"
2. Chose "Password"
3. Scroll down to where the fields for "Number of special characters" etc. should be
4. Fields are empty and cannot be set.

Also the UI does not remember my previous choices anymore.

### Expected Result

Fields are visible and editable. UI remembers my previous choices.

### Actual Result

* Fields are empty and cannot be set even when clicked on.
* UI does not remember my previous choices.

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/8f2ea4ad-1ea0-4fa5-95c1-5b0c939d53d2)

### Operating System

Windows

### Operating System Version

Microsoft Windows [Version 10.0.22621.3880]

### Web Browser

Chrome

### Browser Version

127.0.6533.89

### Build Version

2024.7.1, 2024.8.0, 2024.8.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment] 2024-08-01 09:59
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by JanMosigItemis** [comment] 2024-08-28 07:10
FYI problem also exists with versions 2024.8.0 and 2024.8.1

**Comment by djsmith85** [comment] 2024-08-28 07:29
Hi @JanMosigItemis 

I've been unable to reproduce this on Chrome or Firefox. Setting the display language to German or English: In both instances the expected text is shown and the settings are being saved. I suspect your generator settings might be corrupted? Any information within the Dev console when you open the generator page or adjust settings?

Does logging out of your account (which removes all stored user-data) or re-installing the extension resolve this?

Kind regards,
Daniel

**Comment by JanMosigItemis** [comment] 2024-08-28 07:33
I'll test it and come back to you. In the mean time: @NovaSilentium said she was able to reproduce. Maybe she could provide information on her setup?

**Comment by JanMosigItemis** [comment] 2024-08-28 07:43
Logout/Login did not work. However, deleting and reinstalling the extension **did work**. Thanks for the suggestion.

Tested with 2024.8.1

**Comment by djsmith85** [comment] 2024-08-28 08:01
> Logout/Login did not work. However, deleting and reinstalling the extension **did work**. Thanks for the suggestion.
> 
> Tested with 2024.8.1

Happy to hear that this issue was resolved by reinstalling the extension. @NovaSilentium unfortunately did not provide any additional steps/information to reproduce. As I am not able to reproduce and as the issue is resolved, I'm going to close this. 

The generators are currently being re-built which also includes some larger UI changes. Looking forward to show off these changes in a future release.

Kind regards,
Daniel

**Closed by djsmith85** 2024-08-28 08:01 UTC
Labels: bug, browser
