### ISSUE TITLE
Extension on chromeos doesn't required webauthn when enabled

### ISSUE THREAD

**Issue by rupaschomaker** [bitwarden/clients#3172] opened 2022-07-25 12:34 UTC
### Steps To Reproduce

Enable 2fa using webauthn for account following instructions.
Verify that website now requires webauthn to authenticate.  (yes)

Login via extension and see that only userid/password is required.

### Expected Result

I would expect the webauthn popup to show -- it does not.

### Actual Result

Authentication passes with just userid / password

### Operating System

Linux

### Operating System Version

ChromeOS 104

### Web Browser

Chrome

### Browser Version

104

### Build Version

2022.6.1

**Comment by dbosompem** [comment] 2022-07-25 12:50
Hi @rupaschomaker thank you for submitting this issue. The team will reproduce this and we'd look into resolving it whiles we keep you in the loop. Very appreciated!

**Comment by aj-bw** [comment] 2022-08-22 13:37
hi @rupaschomaker! Thanks for reaching out.

After some additional research and testing, we have been unable to reproduce this issue. It is possible the "remember me" option was checked when signing in, clearing your browser cache or re-installing the browser extension should clear that setting for you.

We use GitHub issues as a place to track bugs and other development related issues. Since this issue appears to be a support request, it would otherwise be better handled by our dedicated Customer Success team.

Please contact us using our [Contact page](https://bitwarden.com/contact)[.](https://bitwarden.com/contact.) You can include a link to this issue in the message content to help provide context for the user.

**Closed by aj-bw** 2022-08-22 13:37 UTC
Labels: bug, browser
