### ISSUE TITLE
generated passwords will not exist in Password History unless it copied

### ISSUE THREAD

**Issue by weifeng12x** [bitwarden/clients#3396] opened 2022-08-26 21:05 UTC
### Steps To Reproduce

1. Go to 'Generator'
2. Click on 'Password History'

### Expected Result

Password History just show passwords which I copied

### Actual Result

every time, I click generator button will generate a new password and the password will exist in Password History. Unfortunately if I want to see the History Password the only one entrance is Generator button. Therefore lots of useless password exist in Password History.

### Operating System

Windows, macOS, Linux

### Web Browser

Chrome

### Build Version

2022.8.0

**Comment by bnagawiecki** [comment] 2022-09-01 20:21
Hey @weifeng12x,

Thanks for taking the time to submit this!

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com/) has a [Feature Requests section](https://community.bitwarden.com/c/feature-requests) for submitting, voting for, and discussing requests like this one.

I went ahead and checked, and it looks like there's already a [feature request](https://community.bitwarden.com/t/only-store-password-history-when-a-new-password-is-selected-or-copied/1632) for this. Please [sign up on our forums](https://community.bitwarden.com/signup), and you can vote for it and contribute to any discussions about it.

I'll go ahead and close this issue out. Thanks!

**Closed by bnagawiecki** 2022-09-01 20:21 UTC
Labels: bug, browser

**Comment by weifeng12x** [comment] 2022-09-01 21:27
> Hey @weifeng12x,
> 
> Thanks for taking the time to submit this!
> 
> Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.
> 
> We use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com/) has a [Feature Requests section](https://community.bitwarden.com/c/feature-requests) for submitting, voting for, and discussing requests like this one.
> 
> I went ahead and checked, and it looks like there's already a [feature request](https://community.bitwarden.com/t/only-store-password-history-when-a-new-password-is-selected-or-copied/1632) for this. Please [sign up on our forums](https://community.bitwarden.com/signup), and you can vote for it and contribute to any discussions about it.
> 
> I'll go ahead and close this issue out. Thanks!

thanks for you explaination.
