### ISSUE TITLE
The app did not start on Mac since last update

### ISSUE THREAD

**Issue by RalphAtHamburg** [bitwarden/clients#8082] opened 2024-02-24 14:24 UTC
### Steps To Reproduce

1. Start the bitwarden app

### Expected Result

See the start window with the password prompt

### Actual Result

See screenshot. 

### Screenshots or Videos

<img width="1351" alt="Bildschirmfoto 2024-02-24 um 15 19 52" src="https://github.com/bitwarden/clients/assets/34203/eae2921e-c8bb-42cb-9632-d78181e08a63">

### Additional Context

This behavioe appeares since the last update of the bitwarden app.

### Operating System

macOS

### Operating System Version

12.7.3 (21H1015)

### Installation method

Mac App Store

### Build Version

Version 2024.2.0 (20587)

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-02-24 16:48
Duplicate of https://github.com/bitwarden/clients/issues/8003

**Comment by SergeantConfused** [comment] 2024-02-24 17:08
Hello everyone,

Thank you @RalphAtHamburg for this report. It seems like a duplicate of the [GitHub report](https://github.com/bitwarden/clients/issues/8003) linked above.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This report will now be closed.

Thank you all again,

**Closed by SergeantConfused** 2024-02-24 17:08 UTC
Labels: bug, desktop
