### ISSUE TITLE
Double scroll bar

### ISSUE THREAD

**Issue by shayded-exe** [bitwarden/clients#5171] opened 2023-04-05 20:56 UTC
### Steps To Reproduce

Open the browser extension

### Expected Result

There is a single scrollbar

### Actual Result

There are two scrollbars

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/1417838/230207357-7acde314-630d-486e-9df6-28854217d6b1.png)
![image](https://user-images.githubusercontent.com/1417838/230207507-cbdeccae-1c88-47ce-b9ff-0f29fb7c7225.png)

### Operating System

Windows

### Operating System Version

19044.2728

### Web Browser

Chrome

### Browser Version

111.0.5563.65 (Official Build) (64-bit) (cohort: Stable) 

### Build Version

2023.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2023-04-06 11:33
Hi @shayded-exe and thank you for your report.

This seems to be a duplicate of https://github.com/bitwarden/clients/issues/3811

Closing this now.

**Closed by djsmith85** 2023-04-06 11:33 UTC
Labels: bug, browser
