### ISSUE TITLE
Account removed (even if i check remember e-mail) if no connection to the server (corporate vpn)

### ISSUE THREAD

**Issue by 0verEngineer** [bitwarden/clients#7547] opened 2024-01-14 12:37 UTC
### Steps To Reproduce

   1. Have a Bitwarden server behind a VPN
   2. Add the account and check the save E-Mail button
   3. Close Bitwarden
   4. Close the VPN connection
   5. Open Bitwarden
   6. See that the account was removed

### Expected Result

The account should not be removed, it is a selfhosted instance and it is a pain that i have to add it everytime again.

### Actual Result

Account removed from client

### Additional Context

This is not a feature request, this is clearly a bug as i click the remember checkbox but it does not remember. I will not create an account in the forum to create a feature request that should definitely be a bug report / issue as stated here: https://github.com/bitwarden/clients/issues/7111

### Operating System

Linux

### Installation method

Other

### Build Version

2023.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-01-15 12:37
Duplicate of https://github.com/bitwarden/clients/issues/7111

**Comment by djsmith85** [comment] 2024-01-15 12:38
Hi @0verEngineer, I have marked this as duplicate and re-opened your original request. Please do not create duplicate issues, instead you can always re-open your report.

Depending on your settings (Vault-timeout= On restart and Vault-timeout action = Logout), closing the application will remove the account on logout.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to the original issue in the message content.

Greetings from Germany :)

**Closed by djsmith85** 2024-01-15 12:37 UTC
Labels: bug, desktop
