### ISSUE TITLE
Error cannot decrypt

### ISSUE THREAD

**Issue by fabiobeoni** [bitwarden/clients#3057] opened 2022-07-07 09:20 UTC
### Steps To Reproduce

Switching account does shows the issue, randomly. 

![image](https://user-images.githubusercontent.com/16882089/177739024-515ba7ba-2c4e-4f3f-b859-5190bfdeeee6.png)

### Expected Result

See the list

### Actual Result

Not decrypted

### Operating System

Linux

### Operating System Version

22.04

### Installation method

Snap

### Build Version

2022.6.0

**Comment by c1xx** [comment] 2022-07-11 06:15
Have the same issue on Windows with Build Version 2022.6.1

**Comment by c1xx** [comment] 2022-07-12 05:26
Windows Build Version 2022.6.2 issue still exists

**Comment by gomerust** [comment] 2022-07-22 12:02
Same here with 2022.6.2, switching back and forth seems to helhelp until the next needed relogin

**Comment by bobvandevijver** [comment] 2022-07-26 07:26
Same issue here

**Comment by dbosompem** [comment] 2022-07-26 10:28
Hi all, apologies for facing such issue, and thanks for bringing this up. The team will reproduce this, and we will take time to resolve the issue as well.

**Comment by nekhebit** [comment] 2022-08-01 09:01
A workaround I found was to add the env var
```OPENSSL_CONF=/dev/null bw list items --collectionid uuid

**Comment by Djohn12** [comment] 2022-08-29 20:11
Randomly hitting a similar issue on Firefox browser extension.

After logging in, the extension couldn't retrieve any information and the collections item in Vault tab was marked with the `[error: cannot decrypt]` message.

Running Firefox 104.0 on Ubuntu 20.04 with Bitwarden extension 2022.08.0

Restarting firefox, rebooting machine didn't change anything.

Locking did not resolve the issue but actually logging out and in again did the trick.

I didn't realize locking and login out were two separate things at first, if needed you can check this config in the extension settings:
`Settings` tab > `Security` section > make sure the `Vault Timeout action` config is set to `Log out`

**Comment by pro4tlzz** [comment] 2022-09-02 09:33
Happens quite frequently on macOS 12.5.1

Bitwarden App store app:
Version 2022.8.1
Shell 19.0.8
Renderer 102.0.5005.148
Node 16.14.2
Architecture arm64

**Comment by o1dnik** [comment] 2022-10-27 12:27
Same issue on switching between private (paid) account and organisation account.
Desktop App version:  2022.10.1 (5129)
MacBook Air (M1, 2020)
OS: Monterey 12.6

**Comment by vinnnyr** [comment] 2022-11-10 15:53
I experienced this issue on Ubuntu/Pop 22.04
 

> ➜  ~ cat /etc/os-release
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os


Resolution here worked: https://github.com/bitwarden/clients/issues/3057#issuecomment-1200918928

**Comment by Aposhian** [comment] 2022-11-10 15:55
It sounds like this might be an incompatibility with newer versions of the default version of the openssl conf that ships with newer OS's like Ubuntu 22.04?

**Comment by metrixsean** [comment] 2022-11-10 15:59
How is this not priority #1? The CLI is completely broken on these OS versions. We had to switch solutions.

**Comment by sbourdette** [comment] 2022-11-26 16:52
Same for me on ubuntu 22.04. using command line bw 2022.10.0
Only name show message "Cannot decrypt" and only for items in an organisation

`bw list items --search "XXXX" --pretty
`

```
  {
    "object": "item",
    "id": "a26fac08-ee4f-4886-XXXXXXXXXXXXXX",
    "organizationId": "a89ef9be-d111-XXXXXXXXXXX",
    "folderId": null,
    "type": 1,
    "reprompt": 0,
    "name": "[error: cannot decrypt]",
    "notes": null,
    "favorite": false,
    "login": {
      "uris": [
        {
          "match": null,
          "uri": "https://www.google.com"
        }
      ],
      "username": "XXXXXXXXX@gmail.com",
      "password": "XXXXXXX",
      "totp": null,
      "passwordRevisionDate": "2022-11-16T20:23:24.217Z"
    },
    "collectionIds": [
      "b9651cdd-cd3b-456c-XXXXXXXXXXXXX"
    ],
    "revisionDate": "2022-11-16T20:23:24.564Z",
    "deletedDate": null,
    "passwordHistory": [
      {
        "lastUsedDate": "2022-11-16T20:23:24.217Z",
        "password": "XXXXXXXXXXXX"
      }
    ]
  }

```

**Comment by Bo-Zi** [comment] 2022-11-27 15:48
yep. same for me (Ubuntu 22.04; bw CLI) - [error: cannot decrypt] .
tried on Ubuntu 20.04 - all the records are properly decrypted.

**Comment by ergosteur** [comment] 2023-02-22 14:45
I seem to get this issue on the Windows client after an update. fix/workaround is to log out of the secondary account and log back in, then it works until the next update. Currently on 2023.2.0.

**Comment by GuizmoFR** [comment] 2023-07-05 07:30
Hello, i have the same issue on MacOS client.

**Comment by TomKeur** [comment] 2023-07-19 07:32
I'm having the same issue on macOS (latest version, latest BW version 2023.5.1).

Steps to reproduce:

I have two accounts on my Bitwarden client:  let's call them `foo` and `bar`.
Foo is my main account, when I'm having the app open with the Foo account and restart the program, everything looks fine.

When I have the `bar` account/Vault open and close the App, when reopening the App it will unlock the `bar` Account/Vault, I can see the content of the `bar` Vault/Account. But when switching to the `foo` (main account) I'm seeing: `[error: cannot decrypt]` after that I need to reopen the client to get the `foo` account working again.

This issue is open for a long time, it's already had its first birthday. Hopefully it can be fixed soon.

**Comment by FLL128** [comment] 2023-11-02 08:01
Turning off autofill on page load fixed the bug for me

**Comment by RollyBolly** [comment] 2023-11-02 13:37
> Turning off autofill on page load fixed the bug for me

Yes, for me too. Selected one of the id's and changed autofill. Great!!

**Comment by mcgannator** [comment] 2024-03-11 14:59
Thank you, SergeantConfused.  I see no solution to my issue #8263 in this forum.  Like others, I have two accounts in my Windows desktop version, a paid enterprise and a free account for personal.  Furthermore, I do not have autofill enabled.  One commenter mentions that it breaks after certain windows updates.  That may be what is happening for me too.  Odd that this has been an issue since 2022 and there seems to be no definite solution.

**Comment by kyz3** [comment] 2024-05-27 06:58
Still happening on 

Bitwarden Version 2024.5.1 (7674)
iOS Version: 17.5.1

**Comment by la32094uf** [comment] 2024-06-05 07:15
Issue since this week happening here on macOS safari version 17.5 (19618.2.12.11.6). Bitwarden version: 2024.5.0
Serverversie: 2024.5.0

<img width="357" alt="Scherm­afbeelding 2024-06-05 om 09 13 55" src="https://github.com/bitwarden/clients/assets/11858721/da06e971-d9ed-4d62-86ae-dc83adb2c853">

**Comment by kyz3** [comment] 2024-06-21 07:19
Still happening on

Bitwarden Version 2024.6.0 (7846)
iOS Version: 17.5.1

**Comment by trmartin4** [comment] 2024-07-03 22:47
Hello,

It appears there are several issues that have been reported that all manifest themselves as "Error: cannot decrypt".  Unfortunately this is a generic error message that likely has different causes and different resolutions between clients.  In order to ensure the most accurate and expedient response to tickets, I would like to first ask @fabiobeoni or any of the reporters of a **desktop** application error whether this is still occurring.  We have not been able to replicate this internally.  If that is the case, we plan to close this as resolved.

@la32094uf your issue on the Safari extension is likely the same as https://github.com/bitwarden/clients/issues/9524, so to avoid conflation of multiple different issues I would recommend you check there.

@kyz3 as this was originally entered as a desktop bug, I would ask if you could create an issue in our [iOS](https://github.com/bitwarden/ios) repo instead so that it can get prompt attention there.

Thank you!

**Closed** 2024-07-18 05:27 UTC
Labels: bug, desktop, needs-reply
