### ISSUE TITLE
App forcing when trying to view card number with master password re-prompt enabled

### ISSUE THREAD

**Issue by MasKash3** [bitwarden/clients#6410] opened 2023-09-26 08:10 UTC
### Steps To Reproduce

1. Add a card and enable master password re-prompt
2. Go to 'Card'
3. Click on the card you just added
4. Click on the eye icon to view the card number
5. Enter the master password
6. App force closes 

### Expected Result

I was expecting to be able to see the card number that I had saved.

### Actual Result

The app crashes and restarts.

### Additional Context

I am also having the same issue on mobile. The app also crashes when trying to modify a card details that has master re-prompt enabled

### Operating System

Windows

### Operating System Version

Windows 11 Home v22H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.8.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2023-09-26 08:16
Duplicate of https://github.com/bitwarden/clients/issues/6153

**Comment by djsmith85** [comment] 2023-09-26 08:16
Hi @MasKash3 

This has previously been reported with https://github.com/bitwarden/clients/issues/6153 and fixes have been issued which are included in `2023.9`-release.

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2023-09-26 08:16 UTC
Labels: bug, desktop
