### ISSUE TITLE
Browser extension:  unlock with biometrics - setting cannot be done

### ISSUE THREAD

**Issue by Overblown8831** [bitwarden/clients#7245] opened 2023-12-15 16:24 UTC
### Steps To Reproduce

Browser extension:  unlock with biometrics - setting cannot be done
It is not possible to activate Windows Hello in the browser extension. I always get the error message that the browser extension should be set up in the desktop app settings. But it is set up. 

Also the workaround is not solving the issue. 

suggested Workaorund that still is not working for me: 
In Bitwarden Desktop:
Disable Login With Windows Hello
Disable Browser integration
Restart your machine.

In Bitwarden Desktop:
Enable Browser Integration
Enable Windows Hello / Biometrics
In the Browser Extension:
Enable Biometrics

![bitwarden integration fail](https://github.com/bitwarden/clients/assets/153924565/492443e0-4c8f-4002-beba-a1b7f0d2232c)

### Expected Result

unlock with biometric ( windows hello) 

### Actual Result

error message :i should activate the browser extension on the bitwarden client app,  but this setting is already set.

### Operating System

Windows

### Operating System Version

windows 11 

### Web Browser

Microsoft Edge

### Browser Version

Version 120.0.2210.61

### Build Version

Version 2023.12.0 

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment] 2023-12-20 17:22
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/2942. 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by cbbit** 2023-12-20 17:22 UTC
Labels: bug, browser
