### ISSUE TITLE
Bitwarden opens webpage on its own

### ISSUE THREAD

**Issue by fransjohan** [bitwarden/clients#11356] opened 2024-10-02 06:22 UTC
### Steps To Reproduce

4. Click on '...'

### Expected Result

Open bitwarden. 

### Actual Result

Open bitwrden. Also opens webpage. No I opren bitwarden, not a webpage (:-(). Can't seem to stop this behavior. It is really really annoying,

### Operating System

macOS

### Operating System Version

macos 14.7

### Installation method

Mac App Store

### Build Version

Version 2024.9.0 (30042)

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by rmcdowell-bitwarden** [comment] 2024-10-02 08:49
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/11354. 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed** 2024-10-02 09:02 UTC
Labels: bug, desktop
