### ISSUE TITLE
Unable to display contents in zh-TW after storage passkey

### ISSUE THREAD

**Issue by dylan940126** [bitwarden/clients#9043] opened 2024-05-05 13:08 UTC
### Steps To Reproduce

1. Go to [Preferences](https://vault.bitwarden.com/#/settings/preferences) and change language to zh-TW
2. Create an normal item (for me is a github account).
3. Click on 'save'
4. Go to [github passkeys](https://github.com/settings/security) -> add a passkey
5. Use bitwarden to storage that passkey
6. Check the item in bitwarden extension

### Expected Result

- show URI
- show button descriptions
- show TOTP
- show passkey

### Actual Result

- miss URI field
- show button icon but no description
- show TOTP field and button but no keys
- miss passkey field

## Extension in zh-TW
![螢幕截圖_20240505_203202](https://github.com/bitwarden/clients/assets/82047621/94fd537e-2541-46f8-8029-18b9733eed02)
## Website in zh-TW
![image](https://github.com/bitwarden/clients/assets/82047621/56bad7f0-c345-4e0d-930e-679c5de6e745)
## Website in en
![image](https://github.com/bitwarden/clients/assets/82047621/f36cd42b-4def-4f4d-bdc2-6c09ef6c9892)

### Additional Context

Only items with passkeys cannot be displayed, but auto fill still works.
Both Android and Ipad apps work fine, but website and extension don't.
I don't know how to change language of extension, so I am not sure if it works.

### Operating System

Linux

### Operating System Version

fedora Linux 40 (KDE Plasma)

### Web Browser

Chrome, Firefox

### Browser Version

Chrome:126.0.6439.0 Dev flatpak, Firefox:125.0.3 flatpak

### Build Version

2024.4.1

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment] 2024-05-05 16:03
Hi @dylan940126,

Thank you for your report. This report seems to be a duplicate of this [one](https://github.com/bitwarden/clients/issues/6821). If there's anything you'd like to add, such as screenshots or videos, please feel free to add them to that existing report so that they'd be reviewed by the Engineering department.

This report will now be closed as a duplicate.

Thank you again,

**Closed by SergeantConfused** 2024-05-05 16:03 UTC
Labels: bug, browser
