### ISSUE TITLE
Changes to an existing entry are NOT shown after you click the save button

### ISSUE THREAD

**Issue by shiftingsand** [bitwarden/clients#12541] opened 2024-12-22 17:34 UTC
### Steps To Reproduce

I have recently noticed a very confusing and very easily reproducible problem with the macOS client. The first time it happened to me a website was asking me to change my password.  I went into the client, clicked edit, generated a new password, saved the entry, and copied it. I was confused because the attempt failed.  It was actually because I was pasting my OLD password because the entry Bitwarden was displaying wasn't updated when I hit the save button. 

Second time I encountered this is when I added a new field to an existing entry.  When I hit save the new field was not present.

I both of these cases when I went to another entry and came back to the one I had edited the changes/new items were then shown to me.

### Expected Result

When you make a change and hit save the change should be shown in the current entry (as it always has).

### Actual Result

The displayed data is as if you had hit "cancel" until you leave the current item and come back to it.

### Operating System

macOS

### Operating System Version

15.2

### Installation method

Mac App Store

### Build Version

2024.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by HelmutZZN** [comment] 2024-12-23 07:02
The issue is not only on Mac, it's a very confusing issue on Windows (11 Pro, 24H2 26100.2605) as well. Regardless if you delete a folder or change the path to another folder, it's not shown on the new folder

**Comment by cbw23** [comment] 2024-12-23 12:41
Hi there!

Thank you for your report, it seems like it is a duplicate of this one #12022 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by cbw23** 2024-12-23 12:41 UTC
Labels: bug, desktop
