### ISSUE TITLE
Flatpak app issue

### ISSUE THREAD

**Issue by depgod** [bitwarden/clients#6868] opened 2023-11-11 18:07 UTC
### Steps To Reproduce

1. OS Ubuntu 23.04 LTS
2. Install bitwarden flatpak app
3. Launch from menu
4. screenshot attached

![Bitwarden Flatpak app Screenshot](https://github.com/bitwarden/clients/assets/23638290/bf96d5ed-cbf3-4b37-a6a9-cfd43f04ca33)

### Expected Result

Usual gui

### Actual Result

All text invisible, can just see the blinking input cursor, Rest of the login description is gone, invisible.

Version 2023.10.1
Shell 25.9.1
Renderer 114.0.5735.289
Node 18.15.0
Architecture x64

Flatpak version: 1.14.4

### Screenshots or Videos

![Flatpak app Screenshot(https://github.com/bitwarden/clients/assets/23638290/afdb332c-a9a2-48cc-8267-4b08b7af9a6b)

### Operating System

Linux

### Operating System Version

Ubuntu 23.04 LTS

### Installation method

Other

### Build Version

Version 2023.10.1 Shell 25.9.1 Renderer 114.0.5735.289 Node 18.15.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Supermath101** [comment] 2023-11-11 22:41
I think this issue is a duplicate of #6818.

**Comment by SergeantConfused** [comment] 2023-11-12 14:33
Hi @depgod,

Thank you for your report. It seems like it is a duplicate of this [one](https://github.com/bitwarden/clients/issues/6818).

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue here will now be closed.

Thank you again,

**Closed by SergeantConfused** 2023-11-12 14:33 UTC
Labels: bug, desktop
