### ISSUE TITLE
Bitwarden desktop fails to unlock

### ISSUE THREAD

**Issue by daeh** [bitwarden/clients#11191] opened 2024-09-22 14:47 UTC
### Steps To Reproduce

1. Open Bitwarden `2024.8.2 (29359)` on MacOS `14.7` (silicon, M2 pro)
2. enter master password
3. click "Unlock" or press enter

### Expected Result

Vault should unlock

### Actual Result

Nothing happens when the correct password is entered. The "Unlock" button becomes unfocused, but the vault does not unlock. I can click the unlock button over and over --- i.e. the app is not freezing or anything, the unlock button just seems to be not triggering the next action. 

If I enter an incorrect password, I get the normal alert "An error has occurred: Incorrect master password", so the app is clearly processing my password and knows when it is correct. But I cannot make it past the initial unlock screen.

### Additional Context

This only just started happening. As far as I know, there has not been an update to the OS or the Bitwarden application.

### Operating System

macOS

### Operating System Version

14.7

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.8.2 (29359)

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daeh** [comment] 2024-09-23 00:03
A full logout, and log back in, seems to have resolved this. 

I'll the the issue open because it's definitely a bug. The landing unlock window of the app shouldn't just silently fail to open the vault without providing any feedback.

**Comment by SergeantConfused** [comment] 2024-10-01 11:30
Hi @daeh,

Thank you for this report. I suspect that what you encountered could have been a temporary matter in the application; In testing, we were unable to reproduce this behaviour within a similar environment. With that in mind, if you encounter this again and have a set of reproduction steps, meaning that you noticed a pattern of actions that you can take in order to get to that state in the Bitwarden macOS desktop client, please feel free to [get in touch](https://bitwarden.com/help/) with us and we'll look into that together. 

At this point, I'm going to proceed and close this GitHub report as it is unreproducible; Please feel free to reach out to us via a [support ticket](https://bitwarden.com/help/), if you have any questions or concerns.

Thank you again,

**Closed by SergeantConfused** 2024-10-01 11:30 UTC
Labels: bug, desktop
