### ISSUE TITLE
Open's with blank screen

### ISSUE THREAD

**Issue by 66schoollane** [bitwarden/clients#3212] opened 2022-08-01 08:09 UTC
### Steps To Reproduce

4. Click on '...'

### Expected Result

opened with blank page

### Actual Result

copy of terminal
```
[justin@blackbox-lan ~]$ flatpak install flathub com.bitwarden.desktop
Looking for matches…

com.bitwarden.desktop permissions:
    ipc     network     wayland     x11     dri     file access [1]     dbus access [2]

    [1] xdg-download
    [2] com.canonical.AppMenu.Registrar, org.freedesktop.Notifications, org.freedesktop.secrets, org.kde.StatusNotifierWatcher


        ID                             Branch          Op          Remote          Download
 1. [✓] com.bitwarden.desktop          stable          i           flathub         114.6 MB / 114.0 MB

Installation complete.
[justin@blackbox-lan ~]$ flatpak run com.bitwarden.desktop
(node:2) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `bitwarden --trace-deprecation ...` to show where the warning was created)
Gtk-Message: 08:50:59.423: Failed to load module "canberra-gtk-module"
Gtk-Message: 08:50:59.423: Failed to load module "pk-gtk-module"
Gtk-Message: 08:50:59.423: Failed to load module "canberra-gtk-module"
Gtk-Message: 08:50:59.423: Failed to load module "pk-gtk-module"
[2:0801/085059.432663:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0801/085059.471235:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0801/085059.471282:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0801/085059.471312:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
LaunchProcess: failed to execvp:
xdg-settings
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)

```
```

             .',;::::;,'.                justin@blackbox-lan 
         .';:cccccccccccc:;,.            ------------------- 
      .;cccccccccccccccccccccc;.         OS: Fedora Linux 36 (Workstation Edition) x86_64 
    .:cccccccccccccccccccccccccc:.       Kernel: 5.18.13-200.fc36.x86_64 
  .;ccccccccccccc;.:dddl:.;ccccccc;.     Uptime: 1 hour, 51 mins 
 .:ccccccccccccc;OWMKOOXMWd;ccccccc:.    Packages: 1883 (rpm), 26 (flatpak) 
.:ccccccccccccc;KMMc;cc;xMMc:ccccccc:.   Shell: bash 5.1.16 
,cccccccccccccc;MMM.;cc;;WW::cccccccc,   Resolution: 1920x1080 
:cccccccccccccc;MMM.;cccccccccccccccc:   DE: GNOME 42.3.1 
:ccccccc;oxOOOo;MMM0OOk.;cccccccccccc:   WM: Mutter 
cccccc:0MMKxdd:;MMMkddc.;cccccccccccc;   WM Theme: Adwaita 
ccccc:XM0';cccc;MMM.;cccccccccccccccc'   Theme: Adwaita [GTK2/3] 
ccccc;MMo;ccccc;MMW.;ccccccccccccccc;    Icons: Adwaita [GTK2/3] 
ccccc;0MNc.ccc.xMMd:ccccccccccccccc;     Terminal: gnome-terminal 
cccccc;dNMWXXXWM0::cccccccccccccc:,      CPU: AMD Ryzen 5 5600 (12) @ 3.500GHz 
cccccccc;.:odl:.;cccccccccccccc:,.       GPU: NVIDIA GeForce GTX 1650 
:cccccccccccccccccccccccccccc:'.         Memory: 4511MiB / 31926MiB 
.:cccccccccccccccccccccc:;,..
  '::cccccccccccccc::;,.                                         
        
```
                                 

### Screenshots or Videos

![Screenshot from 2022-08-01 09-00-34](https://user-images.githubusercontent.com/59388296/182103148-bd1edd3b-5a9c-43d2-ba9f-72d016f1ae9f.png)

### Operating System

Linux

### Operating System Version

OS: Fedora Linux 36 (Workstation Edition) x86_64

### Installation method

Other

### Build Version

2022.5.0

**Comment by djsmith85** [comment] 2022-08-01 08:19
Hi @66schoollane and thank you for your report. Closing this as a duplicate of https://github.com/bitwarden/clients/issues/2604.

**Closed by djsmith85** 2022-08-01 08:19 UTC
Labels: bug, desktop
