### ISSUE TITLE
Bitwarden in Opera giving the wrong login item 

### ISSUE THREAD

**Issue by pimwillems** [bitwarden/clients#5750] opened 2023-07-06 06:11 UTC
### Steps To Reproduce

1. Switch from workspace A to workspace B
2. Workspace B will give the login based on the URL active in workspace A
3. In my example workspace A is fhict.instructure.com and workspace B is webflow.com

https://i.imgur.com/qlsOYXR.png

### Expected Result

I would expect Bitwarden to give me the URL in the active tab in the active workspace

### Actual Result

Bitwarden is serving the URL from a different workspace

### Screenshots or Videos

https://i.imgur.com/qlsOYXR.png

### Operating System

macOS

### Operating System Version

13.3.1 (a)

### Web Browser

Opera

### Browser Version

Opera One(version: 100.0.4815.20)

### Build Version

2023.5.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment] 2023-07-07 07:05
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by pimwillems** [comment] 2023-07-10 07:05
Hi Krychaz,

Thanks for escalating this issue. I do not have any more information I just wanted to let you know that if I can be of any assistance by screen recording or showing this in a call, let me know. I can reproduce it every time.

**Comment by Greenderella** [comment] 2023-07-21 10:45
Hi @pimwillems we have noticed that this issue is a duplicate of https://github.com/bitwarden/clients/issues/5221. Luckily, a fix is already under code review: https://github.com/bitwarden/clients/pull/5711

This issue will now be closed.

Thanks!

**Closed by Greenderella** 2023-07-21 10:45 UTC
Labels: bug, browser
