### ISSUE TITLE
Firefox: bitwarden extension hangs browser

### ISSUE THREAD

**Issue by jdeluyck** [bitwarden/clients#4317] opened 2022-12-24 22:33 UTC
### Steps To Reproduce

1. go to a random site which has entries
2. open up the browser extension
3. mouse over on the icons, wait until the text appears, and then move to the next. Do this several times. At some point the whole browser screen will 'flash' white when you do this (redraw errors?)
4. repeat 3
5. browser hangs

### Expected Result

Everything just keeps working

### Actual Result

Browser hangs

### Additional Context

Fedora 37 kde spin
Firefox 108
Full Wayland setup

### Operating System

Linux

### Operating System Version

Fedora 37

### Web Browser

Firefox

### Browser Version

108

### Build Version

2022.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jdeluyck** [comment] 2022-12-24 23:11
It feels like  https://github.com/bitwarden/clients/issues/3024 but not 100%.

**Comment by jdeluyck** [comment] 2022-12-25 11:57
Can confirm it does *NOT* happen when using X.org. Only wayland.

**Comment by djsmith85** [comment] 2022-12-30 11:46
@jdeluyck: Thank you for your report. This does seem to be a duplicate of #3024.

Closing this now.

**Closed by djsmith85** 2022-12-30 11:46 UTC
Labels: bug, browser
