### ISSUE TITLE
Autofill and context menu stopped working.

### ISSUE THREAD

**Issue by JABirchall** [bitwarden/clients#10814] opened 2024-08-30 12:50 UTC
### Steps To Reproduce

Unknown how to reproduce, they just stopped working.

### Expected Result

expect to see autofill options in context menu and autofill from the extention to work.

### Actual Result

Bitwarden context menu has disapeared.
Clicking on login in the extention results in "unable to autofill the item" error.

### Screenshots or Videos

![](https://i.imgur.com/3es0SJ9.png)

![](https://i.imgur.com/fDktCOW.png)

### Additional Context

Disabling and reenabling the extention fixes the issue untill the browser is restarted.

### Operating System

Windows

### Operating System Version

19045.4780

### Web Browser

Firefox

### Browser Version

129.0.2

### Build Version

2024.8.*, 2024.9.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by gemal** [comment] 2024-08-30 12:51
console says "Error: Could not establish connection. Receiving end does not exist."

**Comment by JABirchall** [comment] 2024-08-30 12:52
> console says `Error: Could not establish connection. Receiving end does not exist. trigger-autofill-script-injection.js:5:20`

Yes it does.

![](https://i.imgur.com/VT11X2J.png)

**Comment by Krychaz** [comment] 2024-08-30 14:16
Hello,

Will you try uninstalling the application, removing any leftover data, powering off and on your device and re-installing? Does this issue still persist?

Guide to the leftover data: https://bitwarden.com/help/data-storage/#on-your-local-machine

Let me know if that helps.

**Comment by budimanjojo** [comment] 2024-09-01 03:34
@Krychaz It's not fixing the problem for me. I also found out that this problem is happening because of weird login issue. When I first start Firefox, Bitwardent client is not showing the padlock icon but still ask me to unlock my vault. And if I unlock my vault, autofill will not work. And I also can't log out of the vault.

But, if I go to Add-ons Manager, disable and re enable the Bitwarden extension, then the extension will then show padlock and when I unlock the vault autofill will then work again.

This is happening after the recent update (version 2024.8.1 updated on 31st August 2024).

**Comment by Bbawt** [comment] 2024-09-01 19:11
Bitwarden browser extension (Edge on Win 10) stopped autofilling today and logged me out each time I closed my browser even though I had set it to Never.  Yesterday I installed the android app and authenticator on my phone.  I just uninstalled the android apps and the browser extension is back to working properly - autofilling and not logging me out.

**Comment by reikrom** [comment] 2024-09-02 08:59
Autofill stopped working on Chrome, when opening the Extension floating window it was stuck in the loading icon state. After a while, it loaded vault content but autofill still didn't work.

Fix that worked:
1. Remove from chrome
2. Add to Chrome.
3. Re-bind autofil hotkey in settings  - Autofill the last used login for the current website

**Comment by ChrisLane** [comment] 2024-09-02 09:14
Yep, removing the extension and then re-adding it fixed the issue for me in Firefox on Linux.

**Comment by Danie10** [comment] 2024-09-02 10:16
Removing the extension and then re-adding it in Brave on Linux did not work for me. It just broke too on my Vivaldi browser when the extension updated to v2024.8.1. It's a problem as every login I have is inside Bitwarden.

**Comment by Bbawt** [comment] 2024-09-05 16:02
Update: Mine started working again instantly after I deleted my BW app on my phone. Yesterday, the extension on Edge quit working again. Had to uninstall the extension and re-add to Edge and it works again.  I can't tell if this is an open bug or not.

**Comment by JABirchall** [comment] 2024-09-06 21:24
> Hello,
> 
> Will you try uninstalling the application, removing any leftover data, powering off and on your device and re-installing? Does this issue still persist?
> 
> Guide to the leftover data: https://bitwarden.com/help/data-storage/#on-your-local-machine
> 
> Let me know if that helps.

This only fixes it until the browser is restarted.

HOWEVER: I did notice there is a new UI for the dropdown on login fields.

![](https://i.imgur.com/3Sg9Q65.png)

This is new, it didnt look like this before it all broke. So from process of deduction, whatever changes that new dropdown UI is responsable for the breaking.

**Comment by Danie10** [comment] 2024-09-08 06:42
Mine has stopped again on Brave Stable on Manjaro Linux after I logged in the next day. Autofill stopped, vault not syncing. It says it last synced yesterday evening. This is after I again removed the extension and its data folder yesterday, and re-installed it.

**Comment by budimanjojo** [comment] 2024-09-08 07:30
Like I said above, signing in / unlock the vault from cold start is not working unless the extension is being toggled off and on. It's very frustrating.

**Comment by Danie10** [comment] 2024-09-08 09:03
More frustrating is Bitwarden not acknowledging the issue here and assigning the issue to someone. 

I'm using the Extensity extension to just toggle it off and on again, and then it seems to work until I reboot. This is at least the easiest way to toggle. I did say to Bitwarden in the issue I logged to the call centre, that considering the information I gave and the reference to this Github issue, that I really did not appreciate the "standard form response" I got to the issue I logged. Clearly no-one even wrote what I had stated I'd already tried, nor even looked at this Github issue. 

I'm a paying premium member, and would at least like to have seen more involvement and presence, seeing this affects so many people.

**Comment by pyluyten** [comment] 2024-09-08 10:08
Had same issue on Chrome/Linux 
* Autofill did not work ( I could copy paste login then password)
* Log off did not work

Removed and reinstalled extension fixed it.

Extension - 2024.8.1
Chrome - Version 128.0.6613.119 (Build officiel) (64 bits)

**Comment by rpodric** [comment] 2024-09-08 14:50
Does 2024.8.2 make a difference? Not that the brief release notes for it mention anything seemingly related.

Also, clearly not everyone is seeing the issue or it would have been much more widely discussed by now. It might be informative to learn why this is the case.

**Comment by budimanjojo** [comment] 2024-09-08 14:50
@pyluyten Have you tried rebooting your computer? For me and many people here, after a reboot (even browser restart on me) will trigger the issue again and I needed to disable and reenable the extension again.

**Comment by pyluyten** [comment] 2024-09-08 15:42
@budimanjojo oh sadly you are right. Browser restart was fine but after full reboot then issues are back, some ui freezes + impossible to autofill.

Both my Linux are under Wayland

**Comment by Bbawt** [comment] 2024-09-08 16:46
I had interesting discoveries yesterday after on and off again issues with the "unable to autofill" notice.  Win 10 Edge BW extension opens from fresh boot in either locked status (even though my setting for vault timeout is "never") or unlocked but I get the orange unable to fill bar.  If its unlocked yet unable to fill, I then go and boot up my Win 11 laptop Edge and BW extension works just fine - and when that happens, BW extension on Win 10 Edge starts working normally again on its own.  

I also had a similar situation just on the Win 10 computer - today after boot Edge BW extension says "locked". Switch immediately to Vivaldi browser and BW extension is working fine.  Switch back to Win 10 Edge and extension is unlocked and working fine.

No difference in browser versions, extension versions, or other extensions.

**Comment by rpodric** [comment] 2024-09-08 16:58
@Bbawt Wow, that is beyond odd, especially since in at least one case you found that an action on one device seemed to affect another. That suggests that BW has some kind of IP-based system in which if it sees you logged in successfully from that IP, at least for a period of time it'll then relax things for you. I wasn't aware that was a feature.

**Comment by jnihil** [comment] 2024-09-08 23:42
@rpodric I am also seeing this issue for the past couple of weeks on Brave (Flatpak). I recover via remove/reinstall of the extension, but the problem returns after some interval. I do not see this issue on Floorp browser (.deb). Both browsers are used actively on a Debian 12 system.

**Comment by Danie10** [comment] 2024-09-10 07:49
Now I'm really worried as I had to add a new password last night. This morning, Bitwarden extension says it is not syncing to vault after I logged in. If I delete and reinstall the extension (like I'm now doing daily), will I lose that password I added yesterday? This is all seems to be falling apart for me.

For me, it has been a combination of autofill as well as vault syncing stopping.

**Comment by JABirchall** [comment] 2024-09-10 08:01
> Now I'm really worried as I had to add a new password last night. This morning, Bitwarden extension says it is not syncing to vault after I logged in. If I delete and reinstall the extension (like I'm now doing daily), will I lose that password I added yesterday? This is all seems to be falling apart for me.
> 
> For me, it has been a combination of autofill as well as vault syncing stopping.
> 
> EDIT: OK just noticed that although the extension says sync failed and shows yesterday's date, if I go back to sync about 5 mins later, it actually shows the current date and time. Verified in another browser that the password updated (even tho that extension also says vault sync failed).

Ive already started doing daily exports incase the day comes that the sync doesnt happen and i loss an important password.

**Comment by arnelap** [comment] 2024-09-10 08:58
Since it works if you turn off and on the extension I'm thinking "something that takes time to initiate within the browser on first browser start" 

What are you-all's DNS settings in Firefox?/

I had it on "'Max Protection" and just switched in to "Default" and the last few restarts Bitwarden worked without having to restart the extension or the browser!

But I have had other cases where suddenly it seemed to work for a bit, so it's difficult to debug this issue. Anyone care to test the same?

**Comment by ccalhoun1999** [comment] 2024-09-10 09:00
I'm on default protection for DNS (although using Zen-browser, a derivative of Firefox so things may be different) but the problem still occurs for me.

**Comment by budimanjojo** [comment] 2024-09-10 09:40
I have DNS protection set to "Off" this entire time because I use my own DNS server so that's definitely not the real culprit.

**Comment by Bbawt** [comment] 2024-09-10 17:26
> Since it works if you turn off and on the extension I'm thinking "something that takes time to initiate within the browser on first browser start"

I think so too, and I'm wondering if on that first browser start that the issue of being logged out or getting the Unable to autofill is a result of that initiation gone wrong.  I now know if I open my browser on boot, BW extension (2024.8.2) shows me locked out even though I have it set to never. Stays that way as long as the browser is open and no other browser used that has BW.  Close the browser and restart it, and BW opens up working just fine. So my work around seems to be - open browser, close browser, open again.

**Comment by ccalhoun1999** [comment] 2024-09-11 00:23
I'm unsure if its related, but my vault is not locking either even with a vault timeout set.

**Comment by budimanjojo** [comment] 2024-09-11 04:21
Seems like the latest version 2024.8.2 fixes this issue

**Comment by JABirchall** [comment] 2024-09-11 04:34
preliminary results, 2024.8.2 fixes the issue. 
will give it a couple day to see if it regresses back to broken.

**Comment by AuspeXeu** [comment] 2024-09-11 07:19
Still broken for me on 2024.8.2

**Comment by Danie10** [comment] 2024-09-11 11:00
Mine has just updated to version 2024.9.0 today so let's see how this goes.

**Comment by JABirchall** [comment] 2024-09-11 14:20
> I can recreate this issue with my firefox browser after a hard reboot (holding down my computers power button) It no longer fills in the fields. To resolve the issue I had to reboot from the windows menu. I was able to repeat it several times with the same results.

Then dont do that.

**Comment by rpodric** [comment] 2024-09-11 14:44
2024.9.0 is certainly promising. It was a surprise seeing that get into the Chrome store so quickly given that it just hit GitHub yesterday. Only listed fix is "bug fixes" but so far so good upon two launches anyway. I've never had it work with two successive launches since the problem began.

**Comment by Danie10** [comment] 2024-09-12 08:13
Sadly for me v2.9.0 is still doing the same on Brave and Vivavldi browsers. Nearly a minute to login, and subsequent vault syncs fail, as well as autofill. I did delete and reinstall v2.9.0 yesterday on my Brave browser.

The question is whether Bitwraden actually is aware of this at all? I did log the issue to their call centre, but I'm not aware if anyone from their team has accepted or allocated this issue yet? Right now I'm using Proton Pass to be sure (after just paying for another year of Bitwarden) so this is getting messy as I don't know whether to trust my Bitwarden account when I see vault sync failed.

All my other extensions, inc Proton Pass, appear to be working as normal.

**Comment by Bbawt** [comment] 2024-09-12 15:54
2024.9.0.  Open Edge, extension shows not logged in and asks for master password to unlock. Leave browser open for more than an hour, no change.  Close browser and reopen and extension is ready within about 2 sec. No more "unable to autofill" - that seems to be fixed, but the inability to be unlocked with first open remains for me.  Does not happen on Vivaldi browser.

**Comment by Danie10** [comment] 2024-09-12 20:30
On Edge after I log into Bitwarden extension, the icon still shows the padlock symbol. I'm wondering if this is not related to the auto-lock after an hour or something similar.  Because if I just log in in then autofill and vault sync works. A while after that it stops.

Thing is, it is still broke across all my browsers even after re-installing the extension. I can't believe it can go so wrong. But it is a major pain to have to reinstall every day across 4 different browsers. I'm testing one browser now to never lock and see what happens.

**Comment by rpodric** [comment] 2024-09-12 21:36
I was fooled with 2024.9.0, as it doesn't work consistently.  This is an improvement on the 8.1 release, which consistently doesn't work (without the off/on toggle) on those systems where that was needed at all (some people never see a problem with any of these releases).

With 9.0, when you do have the problem, the extension can look normal (i.e. when clicked you see your logins and no sign of any issue) but autofill doesn't work using any method without toggling off/on first. So, appearances can be deceiving.

**Comment by Danie10** [comment] 2024-09-13 11:59
Not sure if this will help, but I did turn on Error Collection for the extension and this is one that seems to repeat quite a bit (bearing in mind I have deleted the extension folder a few times and recreated it):

![BitwardenError3](https://github.com/user-attachments/assets/2c44df49-bcf0-442c-8e42-c0c935754777)

**Comment by lissyx** [comment] 2024-09-13 21:33
I could not get autofill to work at all with 2024.8.1, then 2024.8.2 came and fixed it and now 2024.9.0 broke it again?

**Comment by JABirchall** [comment] 2024-09-13 23:05
Yea its still broken since the lastest updates.

**Comment by Danie10** [comment] 2024-09-14 11:43
@lissyx yes that has been deceptive to me as it works immediately after disabling (and even full delete and restore) and then it starts it issues after that again. It's driving me mad now, but I'm sick of every day reinstalling the extension across all three of my browsers (then changing each's settings, and using my Yubikey to reauthenticate). I've exported my data to Proton Pass and trying to use that until this is fixed - I just don't like the way Proton Pass works on the UI, so really would prefer to have a fully functioning Bitwarden extension.

Really don't know what else to try when the full deletion and reinstallation of the extension does not keep working.

**Comment by JABirchall** [comment] 2024-09-14 13:51
> Really don't know what else to try when the full deletion and reinstallation of the extension does not keep working.

You dont have to reinstall it, just disable and reenable the extension.

**Comment by Danie10** [comment] 2024-09-14 16:10
Thanks @JABirchall yes the disable/enable is working now for me. Previous update was not doing so, so I started reinstalling. This is a bit better. Let's hope Bitwarden is aware of this issue and gets it fixed soon.

**Comment by rpodric** [comment] 2024-09-14 16:32
I wouldn't hold your breath, since there's some X factor to this that may not be readily apparent. For example, on the same system with the same account, I have never reproduced the problem in Edge.

**Comment by jsspen** [comment] 2024-09-15 13:36
Version: 2024.9.0
Server Version: 2024.9.0
Librewolf 130.0-3

I've been dealing with this for a while now. Disabling and re-enabling doesn't work reliably. Just had to do the reinstall again to get it working. Has there been any acknowledgement of this problem by the devs at Bitwarden?

**Comment by esalanguerra** [comment] 2024-09-15 16:41
1. Right click on the bitwarden extension
2. Manage extension
3. Scroll down and click on "Allow access to file URLs"

This is a temporary solution for every time the extension blocks or restarts the Google Chrome and Firefox browser

**Comment by JABirchall** [comment] 2024-09-16 08:33
> 1. Right click on the bitwarden extension
> 
>     2. Manage extension
> 
>     3. Scroll down and click on "Allow access to file URLs"
> 
> 
> This is a temporary solution for every time the extension blocks or restarts the Google Chrome and Firefox browser

I dont see that setting on firefox?

**Comment by esalanguerra** [comment] 2024-09-16 14:18
> > 1. Clique com o botão direito na extensão bitwarden
> >    
> >    2. Gerenciar extensão
> >    3. Role para baixo e clique em "Permitir acesso a URLs de arquivos"
> > 
> > Esta é uma solução temporária para cada vez que a extensão bloqueia ou reinicia o navegador Google Chrome e Firefox
> 
> Não vejo essa configuração no Firefox?

1. Right click on the extension
2. click on Manage Extension
3. Go to "Permissions" which is next to Details
4. Click on "Optional permissions for added functionality"

It's just a temporary solution, it would happen again when opening the browser

**Comment by JABirchall** [comment] 2024-09-17 16:47
> Looking at open issues sorted by comments this is in the top 5 and yet it's @JABirchall that I see communicating with users across issue threads and trying to get to the root of this problem and as far as I know he isn't on the payroll...

Hehehe, bitwarden cant afford me :)

**Comment by JABirchall** [comment] 2024-09-17 16:51
+1 more report.

**Comment by JABirchall** [comment] 2024-09-17 16:54
+2 new reports.

**Comment by cagonzalezcs** [comment] 2024-09-18 20:22
Hello everyone,

Thank you for the detailed comments on the issue and for having patience with our response on this concern. I'd like to give some details on what we think is causing this problem, give some manner to apply a temporary resolution for the issue, and talk a bit about some changes coming down the pipeline that should provide a more stable solution. 

[When problems similar to the ones reported in this thread](https://github.com/bitwarden/clients/issues/10691#issuecomment-2306450136) were first reported to us, we identified that a featured flagged reference to an uninitialized class instance was causing issues with the init of autofill behavior. We turned off that feature flag and asked users to refresh/re-install their extension to allow for re-initialization of the background script. 

This suggested course of action resolved the issue found for most users, and we are [soon releasing a fix](https://github.com/bitwarden/clients/pull/10696) that resolves that specific problem effectively. However, it seems that the issues with autofill have persisted past this initial concern. 

With the release of the `v2024.8.0` extension, [we released a larger scale refactor of the autofill inline menu's behavior](https://github.com/bitwarden/clients/pull/8431) which facilitates interactions with a given web page at the top level frame of a page exclusively. This was done to address some larger issues that were being noticed with the rendering of the inline menu in SPA environments and within small iframe elements. 

The work for this refactor was merged into our `main` branch in mid July and the code ran through several regression periods with QA before hitting production. Along with that, we incorporated a feature flag to the implementation that would allow us to revert to the legacy inline menu. This feature flag instantiates the inline menu's background script content in the extension in a delayed manner. This allows us to pull the feature flag from the config of the account's server in order to identify whether to use the new or old inline menu behavior.

Unfortunately, this delayed initialization of the inline menu's background script content is likely the core reason why some sessions of the extension are experiencing a broken autofill experience, while others are not. In truth, I'm having trouble replicating a broken state in any manner, either with a self-hosted local instance or one of our QA cloud environments.

The issues reported by users in this thread point to several inconsistencies with the breaking behavior, all of which fall in line with the idea that somehow the way we are initializing the core behavior of `OverlayBackground` and `TabsBackground` is at fault.

If you experience this behavior, you should be able trigger a quick action to correct the problem by going to the browser page where you manage extensions and toggling the Bitwarden extension off/on. This will trigger a lock state of the extension, which is annoying, but it will also trigger a re-init of the extension's background processes. When that happens, you should see the issue resolve for the rest of your browsing session. 

In effect, this resolution should remain intact even when you close and re-open the browser.  On init of the browser, the extension loads in a locked state and should initialize the inline menu's background behavior without a problem. However, that doesn't seem to always be the case, and if you still see the issue then the same procedure described above should help.

To resolve this more concretely, we've [implemented a removal of this delayed initialization of the inline menu's background script processes](https://github.com/bitwarden/clients/pull/11134) with the hope that this resolves the reported issues. This would effectively remove the ability for us to fallback to the legacy inline menu, but we feel that removing the ability to do this would be an adequate tradeoff if the fix resolves the issues with autofill.

I've brought up the idea of releasing a hotfix for this with my manager; which would release after the upcoming `2024.9.1` release happening this week. That said, it would be incredibly helpful to have some feedback from users who are experiencing problems with the `v2024.8.x ` and `v2024.9.x` versions of the extension. 

As I mentioned, I'm unable to trigger this problem on any of my machines at home. If you are comfortable with doing so, it would be helpful to have confirmation on whether the fix mentioned above resolves the autofill issues encountered. To do that, you [can side-load one of the extension artifacts built with the fix in place](https://github.com/bitwarden/clients/actions/runs/10928574843); ensure that you download one of the files listed as `dist-<browser>-b0f4b7b.zip`.

If those changes do not fix the problem, then that's also good news and just means we'll have to dig in a bit more to identify why this problem is happening for users. 

I'll be consolidating any existing and future Github issues reported by users to focus discussion within this thread specifically. Looking forward to your feedback and to resolving this problem as soon as possible.

**Comment by Danie10** [comment] 2024-09-18 21:02
@cagonzalezcs thanks for that comprehensive response. Yes, I can certainly confirm that the toggling off and on of the extension, as you suggested, does at least solve the problem completely for me for the entire rest of the day's session.

I'll see what it does tomorrow for a new start-up, and then maybe try that sideloading if it is still requiring the toggling. The toggling at least has made it manageable.

**Comment by cagonzalezcs** [comment] 2024-09-18 21:14
@Gudine 

Hmm... behavior surrounding logging in in that manner could introduce all kinds of problems, including breaking logic for autofill. 

@justindbaur Not sure what might be happening here, but some of those listed error surrounding `Reseeding local storage in a timely manner` are new to me... 

Is it possible that something breaking in the process of seeding local storage in the extension triggers other problems?

**Comment by sarimc** [comment] 2024-09-19 07:26
Is there anywhere we can track the status of this bug? We made the switch to Bitwarden for our enterprise some time back and it's becoming a support nightmare. Is there a temporary workaround we can relay to users experiencing the issue of not being able to autofill forms via browser extension?

**Comment by budimanjojo** [comment] 2024-09-19 07:37
@sarimc Do you not read the official announcement from [post above](https://github.com/bitwarden/clients/issues/10814#issuecomment-2359336680)?

You can track this issue specifically to track the status of this bug and they need your inputs to fix it because they can't reproduce it. I just side loaded the unreleased extension for my browser and I'll report again when I decided to restart my computer, you should do the same too. The temporary workaround is to toggle the browser extension whenever you restart your computer/browser/when the problem occurs.

**Comment by cagonzalezcs** [comment] 2024-09-19 13:10
@Gudine By chance, are you a self hosted user or hosting with Bitwarden cloud?

**Comment by Gudine** [comment] 2024-09-19 14:32
@cagonzalezcs I use the Bitwarden cloud.

**Comment by lissyx** [comment] 2024-09-19 17:17
@cagonzalezcs While I was hitting the issue as reported earlier, a few days ago (before you shared the analysis) I did the disabling/enabling again of the extension and it seemed to have fixed it for now. I'll make sure to collect logs and try that artifact if it comes again.

**Comment by Gudine** [comment] 2024-09-19 17:36
@cagonzalezcs I'm not having any of the problems when using that new version. There are still some error messages (nothing about storage), but I assume they're unrelated.

**Comment by Danie10** [comment] 2024-09-19 17:41
@cagonzalezcs tested it on Brave browser. Deleted older version, and new install shows v2024.9.1. Restarted the browser twice and seems to work just fine. Shows the padlock on the extension icon straight after starting up the browser, login is quick, and vault sync works as well as form fill.

**Comment by cagonzalezcs** [comment] 2024-09-19 17:42
That's good to hear, thank you for confirming that this works.

**Comment by Danie10** [comment] 2024-09-19 17:58
Oops, but after about 10 mins use it gave this error, even after restarting it (it may be some other issue):
Your file couldn’t be accessed It may have been moved, edited or deleted.
ERR_FILE_NOT_FOUND

![Screenshot_20245619_075628](https://github.com/user-attachments/assets/bc360711-4aca-47a7-b8d2-871b2e484dc6)

![Screenshot_20245719_075740](https://github.com/user-attachments/assets/91f1e729-3cab-4c3d-bbf5-094e34f96204)

**Comment by cagonzalezcs** [comment] 2024-09-19 18:40
@Danie10 

Yes, sideloading an extension reads it locally rather than importing the extension into the browser's directory. Moving or deleting the files will break the extension in the browser, though it won't de-register it.

**Comment by gemal** [comment] 2024-09-20 07:13
whenever I get the error I always see this in the console:
`Error: Could not establish connection. Receiving end does not exist. trigger-autofill-script-injection.js:5:20`

![image](https://github.com/user-attachments/assets/6e235172-5027-4f55-ab4a-6aabeeeb463a)

**Comment by superthin** [comment] 2024-09-20 09:00
The same as guy above:

Error: Could not establish connection. Receiving end does not exist. trigger-autofill-script-injection.js:5:20

```
/******/ (function() { // webpackBootstrap
(function () {
    // FIXME: Verify that this floating promise is intentional. If it is, add an explanatory comment and ensure there is proper error handling.
    // eslint-disable-next-line @typescript-eslint/no-floating-promises
    chrome.runtime.sendMessage({ command: "triggerAutofillScriptInjection" });
})();

/******/ })()
;
```
I have 2 other extensions:  uBlock Origin (install but Turn Off) and Privacy Badger.

**Comment by gemal** [comment] 2024-09-20 09:04
> I have 2 other extensions: uBlock Origin (install but Turn Off) and Privacy Badger.

I have the same 2 extensions. Both turned on

**Comment by Danie10** [comment] 2024-09-20 09:10
Have others tried side-loading the new version from the link [above](https://github.com/bitwarden/clients/actions/runs/10945259339?pr=11156)? I used the Chrome one on Brave Browser and it is working fine. That has certainly solved it for me with all my normal uBlock Origin etc on. Big thing was just to leave the unpacked extension files as they are, after installing it, otherwise the extension crashes. I'm on day 2 now and finally everything unlocked fine, vault syncing, and forms filling fine.

**Comment by msummers** [comment] 2024-09-20 10:51
Chrome  129.0.6668.58 on Ubuntu 24.04 LTS with dist-chrome-MV3-251b8fc.zip from above has survived 3 browser restarts and continues to work well.

**Comment by LawrenceIRL** [comment] 2024-09-20 18:04
Just confirming that so far loading dist-firefox-b0f4b7b resolves the issue on my first machine here with Firefox v130.0.0 (RPM) on Fedora 40 while on both X11 and Wayland.

**Comment by WrichikBasu** [comment] 2024-09-22 08:00
dist-firefox-b0f4b7b works as intended on Firefox 130.0 on Ubuntu 22.04.4, x11.

**Comment by colibris79** [comment] 2024-09-24 22:50
dist-chrome-MV3-251b8fc.zip seems to be working fine as well with Chrome 129.0.6668.70  and Mint 21.3

**Comment by dovry** [comment] 2024-09-26 07:19
Stopped working again.
Bitwarden Version 	2024.9.1
Firefox 			130.0.1
Win 10 pro 22H2

**Comment by Bbawt** [comment] 2024-09-27 03:31
Desktop browser extension 2024.9.1 has been working fine for last 2 weeks on both Vivaldi and Edge.  Vivaldi was open and BW working on desktop when I just installed Bitwarden on my ipad and logged in. Immediately my desktop browser extension logged out, and when I logged back in, it no longer autofills. This is the same issue I had several weeks ago when I installed BW app on my phone.

**Comment by tdewolff** [comment] 2024-09-27 14:16
For me sometimes it works and sometimes it doesn't. Restarting the browser sometimes fixes it.

**Comment by thezoggy** [comment] 2024-09-27 16:21
autofill stopped working

Bitwarden Version: 2024.9.1
Firefox: 130.0.1
OS: Win10 pro 22H2

**Comment by Danie10** [comment] 2024-09-27 16:29
My sideloaded version 2024.9.1 with Brave is still working perfectly. Logs in fine first time after browser start, and stays working for the rest of the day with autofill. I'm not sure whether the app store version 2024.9.1 is out yet.

**Comment by JasonKhew96** [comment] 2024-09-27 16:48
please read this https://github.com/bitwarden/clients/issues/10814#issuecomment-2361740565 before commenting, stop pinging everyone subscribed to this issue if you don't have new information. Thank you.

**Comment by cagonzalezcs** [comment] 2024-09-27 21:28
To that effect, given that the [work for that PR](https://github.com/bitwarden/clients/pull/11156) seems to resolve this issue for those who have side-loaded the fix, I'll be closing this thread as completed.

Those changes should be release with the next version of the extension, until then if the issue persists you can fix the problem by reloading the extension or if you'd like you can side-load the [extension artifacts that I linked previously](https://github.com/bitwarden/clients/actions/runs/10945259339?pr=11156) until the next release.

Also, just want to re-iterate a huge thank you to everyone who tested the fix.

**Closed by cagonzalezcs** 2024-09-27 21:28 UTC
Labels: bug, browser

**Comment by stateless** [comment] 2024-10-13 19:51
I have this [problem](https://github.com/bitwarden/clients/issues/11498), which has been closed and pointed at this issue.

Autofill works, but the context menu function ignores the setting option. So I can't turn the field context popup off. Also ignores the "[excluded domains list](https://bitwarden.com/help/exclude-domains/)" option.

**Comment by JABirchall** [comment] 2024-10-16 19:22
Any timeline when the update will be released @cagonzalezcs

**Comment by Gudine** [comment] 2024-10-16 19:28
It's been working for me since v2024.10.0.

**Comment by tayl** [comment] 2024-10-16 19:31
> Any timeline when the update will be released @cagonzalezcs

> It's been working for me since v2024.10.0.

This build is not released widely yet. Still moving through the bureaucracy of various app/extension stores.

**Comment by stateless** [comment] 2024-10-16 19:42
Just updated for Firefox on Linux to v2024.10.0. I had to change the autofill option to something else and back again. Now looks like it's fixed. Thanks

**Comment by MrSuddenJoy** [comment] 2024-12-11 22:58
Its beyond comprehension guys. No matter which OS, browser, tricks I do, autofill refuses to work. BW staff seems to be ignoring users.

**Comment by colibris79** [comment] 2024-12-12 00:30
> Its beyond comprehension guys. No matter which OS, browser, tricks I do, autofill refuses to work. BW staff seems to be ignoring users.
> 
> Its highest time we ( = users ) started ignoring BW. Ive already cancelled my paid plan and am actively looking for competitor to use.

It's been working fine here since last fix (hopefully it keeps like this)

**Comment by Danie10** [comment] 2024-12-12 08:26
> Its beyond comprehension guys. No matter which OS, browser, tricks I do, autofill refuses to work. BW staff seems to be ignoring users.
> 
> Its highest time we ( = users ) started ignoring BW. Ive already cancelled my paid plan and am actively looking for competitor to use.

Been working fine for me since last fix too, across Vivaldi, Brave, Edge and Firefox Dev browsers in Manjaro Linux.

**Comment by IetIesAai** [comment] 2024-12-12 09:01
> > Its beyond comprehension guys. No matter which OS, browser, tricks I do, autofill refuses to work. BW staff seems to be ignoring users.
> > Its highest time we ( = users ) started ignoring BW. Ive already cancelled my paid plan and am actively looking for competitor to use.
> 
> Been working fine for me since last fix too, across Vivaldi, Brave, Edge and Firefox Dev browsers in Manjaro Linux.

Same here might want to make absolutely sure you are on the latest version? Only thing I had to do is change the shortcut keys, due to some browsers  not/no longer willing to work with ctrl+shift, so changed to ctrl+alt.

**Comment by MrSuddenJoy** [comment] 2024-12-12 12:56
> > > Its beyond comprehension guys. No matter which OS, browser, tricks I do, autofill refuses to work. BW staff seems to be ignoring users.
> > > Its highest time we ( = users ) started ignoring BW. Ive already cancelled my paid plan and am actively looking for competitor to use.
> > 
> > 
> > Been working fine for me since last fix too, across Vivaldi, Brave, Edge and Firefox Dev browsers in Manjaro Linux.
> 
> Same here might want to make absolutely sure you are on the latest version? Only thing I had to do is change the shortcut keys, due to some browsers not/no longer willing to work with ctrl+shift, so changed to ctrl+alt.

@letlesAai Yes, Im more than sure Im using latest possible version, because I downloaded it from BW webpage.

**Comment by James-Oakley** [comment] 2024-12-12 13:37
> > > > Its beyond comprehension guys. No matter which OS, browser, tricks I do, autofill refuses to work. BW staff seems to be ignoring users.
> > > > Its highest time we ( = users ) started ignoring BW. Ive already cancelled my paid plan and am actively looking for competitor to use.
> > > 
> > > 
> > > Been working fine for me since last fix too, across Vivaldi, Brave, Edge and Firefox Dev browsers in Manjaro Linux.
> > 
> > 
> > Same here might want to make absolutely sure you are on the latest version? Only thing I had to do is change the shortcut keys, due to some browsers not/no longer willing to work with ctrl+shift, so changed to ctrl+alt.
> 
> @letlesAai Yes, Im more than sure Im using latest possible version, because I downloaded it from BW webpage.

What version number are you on, and in which browser?

**Comment by MrSuddenJoy** [comment] 2024-12-13 20:15
@James-Oakley Im on `Safari`, version 17.6 if this matters.....
BW extension is `2024.11.2`
![Screenshot 2024-12-13 at 21 13 59](https://github.com/user-attachments/assets/e5dae5a3-5567-4522-b0fb-b18f0d5ab4b0)

**Comment by James-Oakley** [comment] 2024-12-13 20:23
> @James-Oakley Im on `Safari`, version 17.6 if this matters..... BW extension is `2024.11.2` ![Screenshot 2024-12-13 at 21 13 59](https://private-user-images.githubusercontent.com/171280730/395686128-e5dae5a3-5567-4522-b0fb-b18f0d5ab4b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxMjE0ODYsIm5iZiI6MTczNDEyMTE4NiwicGF0aCI6Ii8xNzEyODA3MzAvMzk1Njg2MTI4LWU1ZGFlNWEzLTU1NjctNDUyMi1iMGZiLWIxOGYwZDVhYjRiMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxM1QyMDE5NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjRjMDAwNGZkNDJmN2Y2Njc3MGU3YjEyNzcyMGU5MTcxNzE1ZjQ3OWI2ZjA4N2ZjZmU3NjQ4N2IxOTAzZDU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BABZf9EmcHh91V9SRYppfSqo3hzfzD-YnHQvvHtDlys)

Agreed - weird that. 2024.11.2 is the version I installed (into Firefox) that fixed the problem in this issue.

I take it you've tried uninstalling the extension and reinstalling it ("turn it off and on again")?

You say you downloaded it from the Bitwarden website. Strangely, the [Bitwarden page for Safari](https://bitwarden.com/help/install-safari-app-extension/) says that won't work and you have to install from the Safari webstore. But I'm not a Safari user to know the workarounds for something like that.

Maybe open a fresh issue here on github. If the developers believe they've fixed the bug being discussed here, you're problem may not get the visibility. It could well be that you've hit a different problem, that happens to present the same.
