### ISSUE TITLE
Program updates overwritten/not working

### ISSUE THREAD

**Issue by whroberts1411** [bitwarden/clients#3273] opened 2022-08-10 11:44 UTC
### Steps To Reproduce

4. Click on '...'

### Expected Result

When the Update Available dialog is displayed, I expect it to install the update.
When I manually install an update from your website, I expect it to stick, and not revert to an old version on reboot.

### Actual Result

Keep getting update reminder every time I start BitWarden - doesn't matter which button I click - the install button doesn't do anything.
Downloaded and installed the update manually (2022.8.0), but on next reboot it's reverted to version 2022.5.0 and I get the update reminder AGAIN!

### Additional Context

Seriously thinking of deleting this program and trying something else - very annoying.

### Operating System

Windows

### Operating System Version

Windows 10 Home 21H2 OS build 19044.1889

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.5.0 (despite many attempts to upgrade)

**Comment by djsmith85** [comment] 2022-08-10 12:05
Hi @whroberts1411 sorry to hear you are experiencing issues after with the update. This was an issue introduced with a previous release.

Please check [this](https://github.com/bitwarden/clients/issues/2571#issuecomment-1123341411) issue for further information.

I'll close this now, as it's a duplicate of https://github.com/bitwarden/clients/issues/2571, but please comment after you have tried the suggested solutions.

**Closed by djsmith85** 2022-08-10 12:05 UTC
Labels: bug, desktop
