### ISSUE TITLE
Firefox extension not autofilling with Firefox 131

### ISSUE THREAD

**Issue by James-Oakley** [bitwarden/clients#11388] opened 2024-10-03 16:32 UTC
### Steps To Reproduce

This all worked fine before upgrading Firefox from 130.x to 131.

1. Go to any website that has a matching URL in bitwarden
2. Click on the login page

### Expected Result

The username and password should be autofilled.

### Actual Result

Nothing happens.
Further, the blue Bitwarden icon in the extensions toolbar does not display a number to indicate that there are matching entries.
Clicking on that blue icon drops down the Bitwarden element, and matching entries in the vault are shown under "logins". However, clicking the entry to attempt a manual autofill triggers the error "Unable to auto-fill the selected item on this page. Copy and paste the information instead"

### Operating System

Linux

### Operating System Version

Fedora 40

### Web Browser

Firefox

### Browser Version

131.0

### Build Version

2024.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment] 2024-10-03 18:00
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/10815. 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by Neonwarden** 2024-10-03 18:00 UTC
Labels: bug, browser
