### ISSUE TITLE
Chrome extension logs out on close when not set to

### ISSUE THREAD

**Issue by thnk2wn** [bitwarden/clients#5175] opened 2023-04-06 17:42 UTC
### Steps To Reproduce

Version 2023.3.0

1. Login to Chrome extension
2. Verify extension settings are set to only lock after a period of time (4 hours)
3. Quit browser
4. Notice it requires you to login again though it's not set to require on browser restart

This worked before

### Expected Result

Not required to login again after closing the browser if it was within time interval

### Actual Result

Required to login again after closing the browser

### Screenshots or Videos

https://user-images.githubusercontent.com/120529/230454931-4763e05f-a16c-4a92-a557-77f4f2c97728.mp4

### Operating System

macOS

### Operating System Version

Mac Ventura 13.3 (22E252)

### Web Browser

Chrome

### Browser Version

Version 111.0.5563.146 (Official Build) (x86_64)

### Build Version

2023.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment] 2023-04-07 09:58
Hi @thnk2wn,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request.

In particular, please note that closing the browser window will overrule all Vault Timeout actions.  The Vault Timeout actions are valid for the duration of a single browser session only.

We use GitHub issues as a place to track bugs and other development related issues. The Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

This issue will now be closed. 

Thanks!

**Closed by atjbramley** 2023-04-07 09:58 UTC
Labels: bug, browser

**Comment by thnk2wn** [comment] 2023-04-07 22:11
Thank you. Not intuitive but good to know.
