### ISSUE TITLE
Bitwarden on Linux Mint - sign in page disappears and the window goes blank. 

### ISSUE THREAD

**Issue by naujramirez** [bitwarden/clients#6584] opened 2023-10-15 01:34 UTC
### Steps To Reproduce

1. Download Bitwarden
2. Click "Launch"

### Expected Result

After installing and launching Bitwarden, the sign-in screen loads up and I can sign in. 

### Actual Result

After installing and launching Bitwarden, the sign-in screen loads up and then immediately goes blank.

### Screenshots or Videos

![bitwarden1](https://github.com/bitwarden/clients/assets/57121033/05ff507f-5841-43db-be1b-c41b5dec5c94)
![bitwarden2](https://github.com/bitwarden/clients/assets/57121033/1446f26a-2579-4de3-9056-db66036cecb4)

### Operating System

Linux

### Operating System Version

Mint (Cinnamon) 

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Bitwarden-2023.9.2-x86_64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by bigkrp** [comment] 2023-10-15 06:53
Same for Fedora 38, installed from flathub.

**Comment by mol0ch13** [comment] 2023-10-15 07:07
Hi, I'm getting the same issue on Pop_OS on my desktop (2023.9.2) and the previous version on my laptop which I haven't updated now is refusing to launch (also on Pop_OS), fortunately I can still use the web vault and I keep a csv database backup of the vault.

**Comment by lrBonneville** [comment] 2023-10-15 07:35
Same for me on Debian 12 via flatpak and appimage

**Comment by hal1961** [comment] 2023-10-15 09:28
Same issue on Ubuntu focal 20.04.6 LTS kernel 5.15.0-86-generic

**Comment by djsmith85** [comment] 2023-10-15 13:16
Duplicate of https://github.com/bitwarden/clients/issues/6560

**Comment by SergeantConfused** [comment] 2023-10-15 13:25
Hi @naujramirez,

Thank you for your report. This report seems like it is a duplicate of this (https://github.com/bitwarden/clients/issues/6560).

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This report will now be closed.

Thank you again,

**Closed by SergeantConfused** 2023-10-15 13:25 UTC
Labels: bug, desktop

**Comment by mol0ch13** [comment] 2023-10-15 21:21
> Duplicate of #6560

Hi, Thanks for your reply, maybe you could be a bit less sarcastic and a bit more helpful like SergeantConfused for example.
