### ISSUE TITLE
MacOS Desktop App from appstore does not automatically ask for touch ID anymore 

### ISSUE THREAD

**Issue by 1LikeTrains** [bitwarden/clients#6328] opened 2023-09-18 15:03 UTC
### Steps To Reproduce

4. Click on '...'
when the bitwarden app is opened by any means on macos ventura 13.5.2 (and also some earlier versions I think too), I need to click on the unlock with touch ID button. In the past it has automatically asked for touch ID. I have the setting enabled to request touch ID when the app is opened.

### Expected Result

bitwarden should ask for touch ID automatically when the app is opened.

### Actual Result

I need to click on the unlock with touch ID button to get a prompt to unlock with touch ID.

### Operating System

macOS

### Operating System Version

13.5.2

### Installation method

Mac App Store

### Build Version

2023.8.4 (11864)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment] 2023-09-18 16:50
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by PixelEnvision** [comment] 2023-09-24 10:02
+1
Still an issue with the latest build 2023.9.0 on macOS Venture 13.6

**Comment by PixelEnvision** [comment] 2023-09-24 10:07
Seems to be Duplicate of #6134 & #6271

**Comment by djsmith85** [comment] 2023-09-25 08:04
Duplicate of #6134

**Comment by djsmith85** [comment] 2023-09-25 08:06
Hi @1LikeTrains, @Private-Fragrance, @PixelEnvision 

Thank you for your report, it seems like it is a duplicate of this one #6134.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2023-09-25 08:06 UTC
Labels: bug, desktop
