### ISSUE TITLE
Windows Hello fails first attempt on Desktop app every time

### ISSUE THREAD

**Issue by nayeemrahman13** [bitwarden/clients#4671] opened 2023-02-06 13:59 UTC
### Steps To Reproduce

1. Enable windows hello and make sure bitwarden is open on startup
2. Go to through windows hello prompts, try to scan face
3. Fails here

### Expected Result

 I expect to be let into my vault.

### Actual Result

I have to authenticate again via Windows Hello

### Operating System

Windows

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.1.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment] 2023-02-06 14:53
Thanks for reaching out!

To troubleshoot this, I'd recommend doing the following:

1. Uninstalling the Bitwarden desktop application.
2. Install the Bitwarden desktop application from this link: https://vault.bitwarden.com/download/?app=desktop&platform=windows
3. In your Bitwarden Desktop app, navigate to Settings (on Windows, File → Settings). 
4. Scroll down to the Options section, and check the Enable Browser Integration box.
5. In your Browser, navigate to the Extensions manager (e.g., chrome://extensions or brave://extensions), open Bitwarden, and toggle the Allow access to file URLs option. Not all browsers will require this to be toggled on, so feel free to skip this step and circle back to it only if the remaining procedure doesn't work.
6. In your Browser Extension, open the Settings tab.
7. Scroll down to the Security section and check the “Unlock with biometrics” box. You should be prompted by your Desktop app to input your biometric. Doing so will complete the initial setup procedure. 

After completing that process, you should be able to unlock the browser extension with biometrics. Please let us know if you need further assistance.

**Comment by patrickhlauke** [comment] 2023-02-07 01:11
just to check...is this a duplicate of https://github.com/bitwarden/clients/issues/3148 ?

**Comment by Krychaz** [comment] 2023-02-07 08:09
This seems like the same issue. As the issue is confirmed in #3148 I will close this one.

**Closed by Krychaz** 2023-02-07 08:09 UTC
Labels: bug, desktop

**Comment by sycx2** [comment] 2023-04-06 10:11
It's definitely not the same problem and I've got it too.
In #3148 the vault is unlocked (for 5 seconds).
In this issue which I also have, the first face login fails where in windows and everywhere else it works on the first try.
