### ISSUE TITLE
Bitwarden does not start any more, exits with error message

### ISSUE THREAD

**Issue by T3rm1** [bitwarden/clients#3444] opened 2022-09-02 22:17 UTC
### Steps To Reproduce

Start the application.

### Expected Result

The application starts.

### Actual Result

It does not start and exits with following error message.
![image](https://user-images.githubusercontent.com/5060247/188241794-5cdc4ccd-c6f7-438b-9a7c-580e64994728.png)

### Operating System

Windows

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.8.1.0

**Comment by djsmith85** [comment] 2022-09-04 17:27
Hi @T3rm1 and thank you for your report. This is a known issue, which is tracked with https://github.com/bitwarden/clients/issues/3264.

Closing this issue as duplicate of https://github.com/bitwarden/clients/issues/3264.

**Closed by djsmith85** 2022-09-04 17:27 UTC
Labels: bug, desktop
