### ISSUE TITLE
iPhone app Login three dots no longer functions

### ISSUE THREAD

**Issue by rlholden** [bitwarden/clients#5225] opened 2023-04-16 15:41 UTC
### Steps To Reproduce

1. Search for any Login item
2. Click on '...’
3. Previous behavior was a pop-up to choose to copy username or password 

### Expected Result

Choice to copy username or password 

### Actual Result

Nothing happens 

### Additional Context

This for the iPhone app
Version: 2023.3.2 (3195)

### Operating System

macOS

### Operating System Version

Version: 2023.3.2 (3195)

### Web Browser

Firefox

### Build Version

Version: 2023.3.2 (3195)

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment] 2023-04-16 17:36
Hi @rlholden,

Thank you for your report, it seems like it is a duplicate of this one (https://github.com/bitwarden/mobile/issues/2446).

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in that existing thread - our engineering team will be happy to review these.

This issue will now be closed.


Thank you again

**Closed by SergeantConfused** 2023-04-16 17:36 UTC
Labels: bug, browser

**Comment by rlholden** [comment] 2023-04-17 01:51
Yes, it appears to be a duplicate. Thanks!
