### ISSUE TITLE
duckduckgo integration bitwarden tries to open repeatedly even when already open

### ISSUE THREAD

**Issue by waddlek** [bitwarden/clients#11833] opened 2024-11-02 14:58 UTC
### Steps To Reproduce

I have both Duckduckgo and Bitwarden installed on my Apple M3 Macbook Air.  Open both applications.  Click on a field you have a known password, it says Bitwarden is locked, click to go unlock it.  Enter master password in Bitwarden app, it unlocks.  Go back to website in Duckduckgo, it does not recognize that Bitwarden is now unlocked and just says to unlock it again. Also, Bitwarden app is in the dock showing it is open.  Repeatedly another instance of Bitwarden appears and disappears as though it is trying to open again.

### Expected Result

Expected to be able to use Bitwarden with Duckduckgo

### Actual Result

See above.

### Operating System

macOS

### Operating System Version

14.6.1

### Web Browser

Chrome

### Browser Version

Not Chrome, it’s on DuckDuckGo

### Build Version

2024.10.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by hevisko** [comment] 2024-11-04 07:56
Hit the same/similar problems
MBP16 - M1Pro 
Macos: 14.7 (23H124) 
BitWarden - AppStore installed
DuckDuckGo - HomeBrew installed

What I can add: 
During the "dialog" box that pops up when I wanted to switch from internal to BitWarden, the bottom line alternates with:
 - <spinner>"Waiting for permission to use BitWarden in DuckDuckGo"
 - <greenCheck>"BitWarden is ready to connect to DuckduckGo!"
 
If I close DuckDuckGo at this point, reopen and go to settings in DuckDuckGo, it seems to have bitwarden selected, but it's alternating between 
- "Missing Handshake" message with "Complete Setup.." button
- "Bitwarden app not running" message with "Open Bitwarden"  button

and a BitWarden icon pop-and-go in the dock as the OP reports

**Comment by hevisko** [comment] 2024-11-04 08:08
Note: When I disable DuckDuckG in BitWarden, the messages change to:
"Integration with duckduckGo is not approved in BitWarden app"
Button: "Complete Setup..."

**Comment by realmistered** [comment] 2024-11-05 07:36
Hi. I have this too. Macbook Pro 2015, MacOS Sonoma 14.7.1.

I’m getting the same issue as described above. Also very annoying is that the Bitwarden dock icon keeps coming in and out of the dock as if it’s not able to decide if it wants to run or not. This is a newly downloaded version of the app.

<img width="358" alt="Screenshot 2024-11-05 at 12 34 53 AM" src="https://github.com/user-attachments/assets/c790abc6-25e3-45a3-8e68-9149a82e17fe">
<img width="348" alt="Screenshot 2024-11-05 at 12 34 21 AM" src="https://github.com/user-attachments/assets/a9bb6381-0fda-45fa-959b-dfe30a026720">
<img width="541" alt="Screenshot 2024-11-05 at 12 36 22 AM" src="https://github.com/user-attachments/assets/544c9667-ed9d-421e-af7e-849e94b7cee4">
<img width="542" alt="Screenshot 2024-11-05 at 12 36 12 AM" src="https://github.com/user-attachments/assets/bf401893-d92d-430a-9541-e8672cd206d2">

**Comment by psteichen** [comment] 2024-11-05 10:11
Exact same issue ([realmistered](https://github.com/realmistered)) here, please advise how to solve this.

**Comment by SergeantConfused** [comment] 2024-11-05 16:55
Hello everyone,

Thank you for your report. This report seems to be a duplicate of this [GitHub report](https://github.com/bitwarden/clients/issues/11692); If there's anything you'd like to add, such as screenshots or video recordings of the screen, please feel free to add them to that existing GitHub report so that they'd be reviewed by the Bitwarden Engineering department.

This report will now be closed as a duplicate.

Thank you again,

**Closed by SergeantConfused** 2024-11-05 16:55 UTC
Labels: bug, browser
