### ISSUE TITLE
Scroll position in entry list returns to top after editing and saving an entry

### ISSUE THREAD

**Issue by CamboNZ** [bitwarden/clients#2607] opened 2021-05-19 20:29 UTC
## Describe the Bug

After the recent update to 1.26.3 on the Windows Desktop version, if an entry is edited and then saved, the scroll position is returned to the top of the current folder, previously the position was maintained and you would still be in the position of the edited entry in the list.

## Steps To Reproduce

1. Edit an entry you have to scroll down to get to.
2. Hit save.

## Expected Result

Scroll position is not changed.

## Actual Result

The list is scrolled back to the top of the list. In version 1.25.1 this does not happen.

## Environment

- Operating system: Windows 10
- Installation method: Downloaded from Bitwarden.com
- Build Version 1.26.3

**Comment by djsmith85** [comment] 2022-07-21 09:45
Closing this as duplicate of https://github.com/bitwarden/clients/issues/2564 which has more recent traction/examples.

**Closed by djsmith85** 2022-07-21 09:45 UTC
Labels: desktop
