### ISSUE TITLE
macOS - Desktop client does not prompt for Touch ID authentication (unlock) on launch.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/clients#3898] opened 2022-10-26 14:40 UTC
### Steps To Reproduce

1. Open the Bitwarden macOS desktop client (Installed via Mac App Store).
2. Make sure that (Unlock with Touch ID) and (Ask for Touch ID on launch) are toggled in the Settings menu.
3. Quit Bitwarden and launch it again.

### Expected Result

To be prompted to use Touch ID in order to unlock the vault.

### Actual Result

The macOS client does not automatically offer to unlock via Touch ID.

### Screenshots or Videos

N/A.

### Additional Context

Pressing on (Unlock with Touch ID) allows you to unlock the vault using Touch ID.

### Operating System

macOS

### Operating System Version

13.0.

### Installation method

Mac App Store

### Build Version

2022.10.1 (5129).

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2022-10-26 17:21
Duplicate of #3774

**Closed by djsmith85** 2022-10-26 17:21 UTC
Labels: bug, desktop
