### ISSUE TITLE
win 10: after the last update, I have to keep running the desktop app in order to login with biometrics in Opera browser.

### ISSUE THREAD

**Issue by DimitriosPi** [bitwarden/clients#3533] opened 2022-09-15 08:33 UTC
### Steps To Reproduce

1. Go to 'bitwarden addon for opera'
2. Click on 'bitwarden icon'
3. Scroll down to 'no scroll down'
4. Click on 'no click'

### Expected Result

Normaly a window "Scan your finger...  " pops up

### Actual Result

A window with normal login (password) pops up, and when I click on biometrics, I get the message "waiting for desktop app authentication". Then I have to run that and keep it always running, in order to use the browser add on. 

### Operating System

Windows

### Operating System Version

Edition	Windows 10 Home Version	21H2 Installed on	‎3/‎1/‎2022 OS build	19044.2006 Experience	Windows Feature Experience Pack 120.2212.4180.0

### Web Browser

Opera

### Browser Version

90.0.4480.84

### Build Version

Version 2022.9.0 Shell 19.0.8 Renderer 102.0.5005.148 Node 16.14.2 Architecture x64

**Comment by Hinton** [comment] 2022-09-15 10:17
Please ensure "Close to tray icon" is enabled. 
![image](https://user-images.githubusercontent.com/137855/190379012-200d5db6-b6a5-4515-99a3-239109bf5ee6.png)

**Comment by DimitriosPi** [comment] 2022-09-15 10:54
It is: 
![screenshot_32](https://user-images.githubusercontent.com/55955666/190386173-41e8624a-1b91-4e96-9397-bad7a727e9c6.jpg)
 and when I hit the bw icon in opera I get this:
![screenshot_31](https://user-images.githubusercontent.com/55955666/190386343-7fc60cb9-f696-4cc7-a865-2a82f6913264.jpg)

**Comment by dracula385** [comment] 2022-09-15 10:57
I have the same issue. 

The desktop app is running in the tray. I am using Chrome and when I try to unlock the vault, my biometrics is not recognized. Windows hello dialogue pops up but until I click on the Windows hello prompt my biometrics are not recognized. 
It's like the focus does not switch on to the Windows hello dialogue. Once I click on Windows hello prompt then it can recognize my fingerprint. It is happening since 2022.09 on all of my 5 computers window windows 11

**Comment by DimitriosPi** [comment] 2022-09-15 11:04
Exactly!

**Comment by Hinton** [comment] 2022-09-15 11:32
Sounds like a duplicate of https://github.com/bitwarden/clients/issues/3504, going to close this in favor of that issue.

**Closed by Hinton** 2022-09-15 11:32 UTC
Labels: bug, browser, needs-reply
