### ISSUE TITLE
AutoFill Password Option Does Not Work On iOS 18

### ISSUE THREAD

**Issue by arazilsongweaver** [bitwarden/clients#11143] opened 2024-09-19 00:48 UTC
### Steps To Reproduce

1. Long press on a text field.
2. Try to auto fill a form using the "AutoFill" -> "Passwords" option.

### Expected Result

Bitwarden offers autofill options appropriate to the website.

### Actual Result

The operation fails with an "Update Bitwarden to support the AutoFill feature" error message. Autofill fails.

### Screenshots or Videos

![IMG_5570](https://github.com/user-attachments/assets/23378e3c-60f3-42fd-a355-d0af2802124c)

### Operating System

iOS

### Operating System Version

18.0

### Web Browser

Safari

### Browser Version

18.0

### Build Version

2024.9.0 (1080)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by luc-bw** [comment] 2024-09-19 08:27
Hi there!

Thank you for your report, it seems like it is a duplicate of [#916](https://github.com/bitwarden/ios/issues/916). 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by luc-bw** 2024-09-19 08:27 UTC
Labels: bug, browser
