### ISSUE TITLE
Database Randomly Goes Corrupt preventing login and displaying Error: Cannot Decrypt with spinning circle

### ISSUE THREAD

**Issue by mcgannator** [bitwarden/clients#8263] opened 2024-03-08 14:50 UTC
### Steps To Reproduce

1. Go to shortcut for desktop app 
2. Click on shortcut and enter Windows 11 fingerprint (Windows Hello) when application opens and prompts for login
3. Application will not load and shows spinning circle in second column of window.  First column ends with blue error -  [error: cannot decrypt]
4. Click on '...'

### Expected Result

Database opens to passwords as normal

### Actual Result

Application will not load database

### Screenshots or Videos

![2024-03-08 09_43_22-](https://github.com/bitwarden/clients/assets/162720238/f79eb969-535c-4a68-bca9-d0a49994b710)

### Additional Context

Must remove login account from application by choosing File --> Log Out and then go through the whole login process again to get it to load.  Super annoying.  Happens about 2 times a month over the past few months.

Note that the Windows Hello fingerprint prompt takes about 5 to 10 seconds to pop up on a newer laptop.  It pops up in the background with it minimized and takes about 5 to 10 seconds to come to the foreground at which point you can use it.  This behavior started late last year.  It used to pop up immediately.  I have rebuilt the laptop OS and confirmed all firmware and Windows updates to no avail.  

### Operating System

Windows

### Operating System Version

11   23H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.2.0  Shell 28.1.3 Renderer 120.0.6099.199

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by mcgannator** [comment] 2024-03-08 14:53
Note that when I say you must log back in after logging out, I mean you must add the account back into the application as if it is a new account, requiring all settings to be reconfigured to get the correct preferences (like deleting password from clipboard after a certain amount of time, locking the database after a specified amount of inactivity, etc...)

**Comment by mcgannator** [comment] 2024-03-08 14:57
Furthermore, this is on a Samsung Galaxy Book 2 Pro 360 and likely occurs after the system goes to sleep with the database open.

**Comment by SergeantConfused** [comment] 2024-03-11 10:15
Hi @mcgannator,

Thank you for your report. This seems like a duplicate of this [one](https://github.com/bitwarden/clients/issues/3057).

With regard to "Windows Hello fingerprint prompt takes about 5 to 10 seconds to pop up" I'd recommend comparing this to other applications on that same computer to see if it's isolated to the Bitwarden desktop client in order to know how to best proceed; Deactivating Windows Hello completely, meaning to a point where the operating system User Account is protected using only a password, rebooting, and then setting Windows Hello up anew may assist. To be clear, the Windows Hello prompt for facial recognition appears within less than a second of launching the Bitwarden desktop client on my Windows 11 Pro machine. Please feel free to get in touch with us using the form [here](https://bitwarden.com/help/) if you'd like us to troubleshoot that together.

If you'd like to add additional information/screenshots/recordings etc., please feel free to do so at any time in that existing thread - our engineering team will be happy to review these.

This report will now be closed.

Thank you again,

**Closed by SergeantConfused** 2024-03-11 10:15 UTC
Labels: bug, desktop
