### ISSUE TITLE
Inconsistent behavior for reading Verification Codes when "Master password re-prompt" is applied

### ISSUE THREAD

**Issue by mciantar** [bitwarden/clients#6346] opened 2023-09-20 11:13 UTC
### Steps To Reproduce

Using the Browser (Chrome) Extension:
1. Open an item that has password and verification code configured.
2. Check "Master password re-prompt" and save the item.
3. Find the Item and click on Clock Icon to copy the Verification code, at this step you are re-prompted for the password.
4. Open the Item and you can see the verification code WITHOUT any password required.

### Expected Result

Either the Verification Code is Protected, or it is not.

### Actual Result

The Verification code is protected by Master Password when clicking on the Icon, but not when opening the item.

### Operating System

Windows

### Web Browser

Chrome

### Build Version

2023.8.3

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment] 2023-09-20 11:18
Duplicate of [#2733](https://github.com/bitwarden/mobile/issues/2733)

**Comment by Adedamola-Aina** [comment] 2023-09-20 11:19
Hi @mciantar ,
This seems to have previously been reported with [#2733](https://github.com/bitwarden/mobile/issues/2733) and a fix has been issued with [#2713](https://github.com/bitwarden/mobile/pull/2713) which will be included in the next release (2023.9)
This issue will now be closed.
Thanks!

**Closed by Adedamola-Aina** 2023-09-20 11:19 UTC
Labels: bug, browser

**Comment by mciantar** [comment] 2023-12-04 09:36
@Adedamola-Aina , I do not think you understood what this bug is about, as it remains unfixed. The linked ticket does not reflect what this ticket was explaining.

Open the Item and you can see the verification code WITHOUT any password required.

It does not make sense that only the password is protected, while the MFA code is not.
