### ISSUE TITLE
Bitwarden scans every entry on Deluge WebUI page for password entry field, repeatedly with every page interaction

### ISSUE THREAD

**Issue by jiraph** [bitwarden/clients#7226] opened 2023-12-14 19:35 UTC
### Steps To Reproduce

1. Open Deluge WebUI.
2. Interact in any way. Scroll, click, right click, etc.
3. Page freezes for several seconds, Firefox pops up "_Bitwarden is slowing down Firefox_"

### Expected Result

Page should load normally and not freeze.

### Actual Result

Page takes longer to load initially, and any kind of interaction makes the page freeze for several seconds. 

### Screenshots or Videos

Through Firefox performance logger, it appears that Bitwarden is scanning several thousand times looking for a password input field.

This is the log after scrolling down the page:

![Screenshot 2023-12-14 111720](https://github.com/bitwarden/clients/assets/19298861/a15abbc1-6b26-4821-bab2-a8015894e345)
![Screenshot 2023-12-14 111715](https://github.com/bitwarden/clients/assets/19298861/ca8ab3b4-c1b7-4de8-a586-df8a0811723c)

### Additional Context

I have the address for this page blacklisted in excluded domains.

### Operating System

Windows

### Web Browser

Firefox

### Browser Version

117.0

### Build Version

2023.12.0

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment] 2023-12-18 01:54
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in auto-fill v2 incompatibility with Firefox 117.0 - please try updating to 120.0.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by toddnotplaying** [comment] 2023-12-23 02:32
I am experiencing the same issue. Details sent to support as well as requested:

I am on Firefox 121.0 (64-bit)

This happens on at least 2 windows PCs, one running Win 10 and one running Win 11.

The deluge instance in question has a little over 1000 torrents. I do NOT experience the issue in the same browser when accessing a deluge instance with roughly 40 torrents.

**Comment by SergeantConfused** [comment] 2024-05-07 15:11
Hello everyone,

This GitHub report will be reopened because we're exploring this matter internally at this time.

All the best,

**Comment by cagonzalezcs** [comment] 2024-05-07 22:29
@jiraph  

Thank you for your bug report, we've been pushing hard on manifest v3 since early this year so I haven't been able to get these kinds of performance issues until recently. 

That said, we have a set of [changes](https://github.com/bitwarden/clients/pull/9063) that should alleviate the performance issues being described here.

I'd like to centralize related conversations to a single Github issue, so I'll be closing this thread for now.

Please feel free to continue discussion in this [Github issue thread.](https://github.com/bitwarden/clients/issues/8699)

**Closed by cagonzalezcs** 2024-05-07 22:29 UTC
Labels: bug, browser
