### ISSUE TITLE
Can't create new organization logins

### ISSUE THREAD

**Issue by Manamius** [bitwarden/clients#8675] opened 2024-04-10 18:40 UTC
### Steps To Reproduce

When trying to create a new login in an organization collection on the desktop app it says there are no collections listed

### Expected Result

Create new login

### Actual Result

Errors saying there are no collections to list.

![image](https://github.com/bitwarden/clients/assets/122295366/98395cf7-c9d9-4d8c-859d-3b39a1de1e80)

### Operating System

Windows

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TroyBW** [comment] 2024-04-12 17:31
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: [https://github.com/bitwarden/clients/issues/8258](https://github.com/bitwarden/clients/issues/8258)

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by TroyBW** 2024-04-12 17:31 UTC
Labels: bug, desktop
