### ISSUE TITLE
Locked out immediately

### ISSUE THREAD

**Issue by xIUPITERx** [bitwarden/clients#3088] opened 2022-07-12 11:52 UTC
### Steps To Reproduce

1. Open the Bitwarden desktop app
2. Click on 'login with Windows Hello'
3. You will be locked out and have to repeat Step 2. 
4. Step 3. will repeat itself a few times before you are logged in without being logged out again

### Expected Result

If you log in to Bitwarden with Windows Hello, you should also stay logged in for the specified 15 minutes.

### Actual Result

If you log in to Bitwarden with Windows Hello, you will be locked out once or twice and have to log in again with Windows Hello, after that the specified 15 minutes will be kept.
This usually happens when you open the app for the first time after booting your PC.

### Operating System

Windows

### Operating System Version

Windows 11 Pro 21H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.6.2

**Comment by djsmith85** [comment] 2022-07-29 11:01
@xIUPITERx Thank you for your report. Closing this as duplicate of https://github.com/bitwarden/clients/issues/3148. Favouring it, because it has some more information on reproduction steps.

**Closed by djsmith85** 2022-07-29 11:01 UTC
Labels: bug, desktop
