### ISSUE TITLE
Popup Prompt Font Missing (Unreadable)

### ISSUE THREAD

**Issue by klondikemarlen** [bitwarden/clients#5873] opened 2023-07-21 21:26 UTC
### Steps To Reproduce

1. Create a new item.
2. Click the trash can icon to delete the item.
3. You will see this prompt.
![image](https://github.com/bitwarden/clients/assets/23045206/6d0e79ba-1815-42b5-a032-0e19134bcea3)

### Expected Result

I would expect the font to render correctly.

### Actual Result

The message is unreadable.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/23045206/ea01bb90-7239-4630-b51c-86be270d4949)

### Additional Context

Actually this bug affects every popup. The Help -> About Bitwarden looks like
![image](https://github.com/bitwarden/clients/assets/23045206/7a783bb7-cafb-48fb-aea0-265f3f32ae15)

Luckily I know that copy has 4 charaters and is a common feature.

### Operating System

Linux

### Operating System Version

Ubuntu 23.04, GNOME 44.2, X11 and Wayland

### Installation method

Snap

### Build Version

Version 2023.7.0 Shell 24.1.1 Renderer 112.0.5615.50 Node 18.14.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2023-07-21 22:36
Duplicate of https://github.com/bitwarden/clients/issues/2628

**Comment by djsmith85** [comment] 2023-07-21 22:37
Hi @klondikemarlen thank you for your report. 

I believe this is a duplicate of https://github.com/bitwarden/clients/issues/2628.

Please any further information there.

Closing this now

**Closed** 2023-07-21 22:38 UTC
Labels: bug, desktop
