### ISSUE TITLE
TouchID broken in Version 2023.8.2 (11197)

### ISSUE THREAD

**Issue by larrymcj** [bitwarden/clients#6134] opened 2023-08-29 03:54 UTC
### Steps To Reproduce

1. Click the Dock icon for Bitwarden.

### Expected Result

Up until version Version 2023.8.2 (11197) which was released today, opening Bitwarden invoked TouchID when using an Apple TouchID Board. I still have this configured in settings per the following screenshot.

<img width="257" alt="Bitwarden TouchID" src="https://github.com/bitwarden/clients/assets/143465627/c9378b8f-5701-4ff8-9ea3-3b38511acb21">

### Actual Result

When Bitwarden opens, TouchID is no longer invoked.

### Operating System

macOS

### Operating System Version

Ventura 13.5

### Installation method

Mac App Store

### Build Version

Version 2023.8.2 (11197)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment] 2023-08-30 12:18
Hello,

Could you please to perform a full reinstall of your desktop application.

**Comment by Krychaz** [comment] 2023-08-31 13:10
After consulting with my team, this is indeed not the expected behaviour. I have passed this to our Engineering team.

**Comment by larrymcj** [comment] 2023-08-31 13:23
Thanks, Krystian.

**Comment by kangaroo72** [comment] 2023-09-01 23:34
I can confim the issue on my Macbook Pro (M1 2021) 16" - Ventura 13.5.1

**Comment by larrymcj** [comment] 2023-09-02 00:35
I should have thought to try this when I originally posted this. I just tried this with my wife's M2 Pro Mac mini can confirm it happens on it, also. When I first tried it on her machine, it still had the previous version of Bitwarden install (9969) and it worked perfectly. As soon as I updated it to (11197) it also displayed this behavior.

**Comment by umerf52** [comment] 2023-09-05 07:24
I'm also facing this issue.
14" MacBook Pro 2021 (M1 Pro) - Monterey 12.6.8
Bitwarden: Version 2023.8.2 (11197)

**Comment by kangaroo72** [comment] 2023-09-07 12:28
Issue still exists in 2023.8.3

**Comment by larrymcj** [comment] 2023-09-07 14:54
I just installed 2023.8.3 (11485) also – it's still a problem for me.

**Comment by andylundqvist** [comment] 2023-09-08 09:55
Same here, Auto-Touch ID request on startup is still broken on macOS 13.5.1 with Bitwarden 2023.8.3 (11485).

On iOS Face ID has also not been working normally as of late and it often forced me to input the master password. No idea if there is a connection. I just installed 2023.8.0 (4566) on iOS and will test if it's changed.

**Comment by emaraszek** [comment] 2023-09-10 15:39
Having the same issue on macOS 13.5.2 (M1 Air) with Bitwarden 2023.8.3. For me, this wasn't an issue until I updated to macOS 13.5.2 from 13.5.1. Bitwarden 2023.8.3 was installed before the upgrade.

Also after the macOS upgrade I'm no longer able to use Touch ID to unlock the Firefox extension. It will automatically prompt for Touch ID and then hang indefinitely on "Awaiting confirmation from desktop". I have uninstalled and reinstalled both the desktop app and the extension, but am still experiencing these issues.

**Comment by umerf52** [comment] 2023-09-11 06:09
> Having the same issue on macOS 13.5.2 (M1 Air) with Bitwarden 2023.8.3. For me, this wasn't an issue until I updated to macOS 13.5.2 from 13.5.1. Bitwarden 2023.8.3 was installed before the upgrade.
> 
> Also after the macOS upgrade I'm no longer able to use Touch ID to unlock the Firefox extension. It will automatically prompt for Touch ID and then hang indefinitely on "Awaiting confirmation from desktop". I have uninstalled and reinstalled both the desktop app and the extension, but am still experiencing these issues.
> 
> EDIT: Adding more data here. My work machine (14" Pro 2021, M1 Pro) auto-updated to macOS 13.5.2 and is now exhibiting the same behaviors as my M1 Air:
> 
>     * No auto Touch ID prompt on desktop app startup. Requires clicking the button, but does log in successfully after doing so
> 
>     * Firefox extension auto-prompts for Touch ID but hangs indefinitely. Only unlocks with master password or PIN
> 
> 
> Auto-prompt Touch ID works correctly with Safari on both machines, so I realize this Firefox issue may be a separate bug. However, both issues started occurring at the same time for me.

For browser extension: https://github.com/bitwarden/clients/issues/6169

**Comment by PixelEnvision** [comment] 2023-09-24 10:06
+1
Still an issue with the latest build 2023.9.0 on macOS Ventura 13.6

**Comment by xxhh1112** [comment] 2023-09-25 01:50
q

**Comment by dabeeeenster** [comment] 2023-09-25 07:33
Still an issue with Version 2023.9.0 (11993) on Mac OS Ventura 13.6 (22G120)

**Comment by ToGitOrNotToGit** [comment] 2023-09-28 23:57
Same issue. 
The BW **APP** NO LONGER PROMPTS me for TouchID, but the Safari 17 extensions does. It does work when clicked.

Version 2023.9.0 (11993)
macOS 13.5.2 (22G91)
Safari Version 17.0 (18616.1.27.111.22, 18616)

**Comment by qxrv** [comment] 2023-10-01 07:39
+1
This is still an issue on Bitwarden 2023.9.1
macOS version: 14.0

**Comment by Gondor83** [comment] 2023-10-03 15:31
+1
Same issue, Bitwarden don't show up automatically Touch ID prompt at app startup.

Version 2023.9.1 (12289)
macOS Sonoma 14.0 (23A344)

**Comment by doobix** [comment] 2023-10-05 22:55
+1

Version 2023.9.1 (12289)
macOS Sonoma 14.0 (23A344)

**Comment by Gondor83** [comment] 2023-10-18 08:07
> +1 Same issue, Bitwarden don't show up automatically Touch ID prompt at app startup.
> 
> Version 2023.9.1 (12289) macOS Sonoma 14.0 (23A344)


Version 2023.9.3 (12828) macOS Sonoma 14.0 (23A344)

Same as always. Just me?

**Comment by larrymcj** [comment] 2023-10-18 12:33
I’ve used Bitwarden from the beginning, but this one has finally pushed me
off the edge. If it actually gets fixed with this next release, I’ll stay,
otherwise I’m already using another solution. This is just too rudimentary
of a bug to last this long. Bitwarden is a great product, but users can’t
be expected to open it multiple times in order for it to stay open so they
can use it.

**Comment by thomasync** [comment] 2023-10-19 16:06
I solved the problem and [created a PR](https://github.com/bitwarden/clients/pull/6400) 3 weeks ago, but it still hasn't been reviewed...

**Comment by berkkivircik** [comment] 2023-10-23 21:03
I'm experiencing the same issue on my Windows laptop with an up-to-date Bitwarden version.

<img width="149" alt="image" src="https://github.com/bitwarden/clients/assets/50699281/cc8cdd63-32c7-487f-89e3-8b89c717231b">

<img width="176" alt="image" src="https://github.com/bitwarden/clients/assets/50699281/642cb3b3-7d85-4f37-9ec6-9e62fa0a5994">

**Comment by fsafq41** [comment] 2023-10-28 23:52
I also have the same issue and it has been ongoing for the past several months and versions.
Current version with the same issue: 2023.9.3 (12828)

**Comment by Gondor83** [comment] 2023-11-08 14:18
Version 2023.10.1 (13648) macOS Sonoma 14.1 (23B74)

Nothing changed.


At this point it would be interesting to know whether it is a bug or a precise choice of UX

**Comment by qxrv** [comment] 2023-11-08 14:23
This is getting ridiculous to be honest. This same issue existed earlier this year iirc and they fixed it, only for it to re-emerge again. Several updates have passed and still no fix, even though the fix is literally right there, waiting to be patched in. I would switch to something like Proton Pass if it were a more mature product.

**Comment by larrymcj** [comment] 2023-11-08 14:55
I so agree! I’m using 1Password until this gets fixed.

**Comment by unikitty37** [comment] 2023-11-12 11:46
![image](https://github.com/bitwarden/clients/assets/139183/cc643dea-3105-4290-930a-8608f828d24e)

BitWarden now doesn't even _show_ the prompt for Touch ID in Settings. This is, quite frankly, rubbish. What is the point of having a long, complex vault password, safe in the knowledge that you will only have to type it occasionally, if BitWarden then decides to throw your configuration in the bin and make you type the damn thing every time.

That just leads to users setting the timeouts to maximum and using the shortest, easiest-to-type passwords that they can. **This bug greatly reduces security, and should be treated as a high priority.** And yet it has been an issue for **over two months.**

Given Apple's App Store doesn't allow users to roll back to older, working versions (because Apple apparently think no release ever introduces new bugs, despite their obvious track record of doing exactly that) I'd appreciate knowing how I can install a version that Just Works with Touch ID and then disable automatic updates?

I've had a look through the code tree, and I can't find any automated tests for the macOS client. _Are_ there any? There _should_ be. That way, issues like this can be spotted and the offending release blocked until they're fixed…

**Comment by ToGitOrNotToGit** [comment] 2023-11-12 16:42
Whose attention can we bring this to if it has potentially been fixed with #6400 ???
How do we get this implemented?

**Comment by thomasync** [comment] 2023-11-12 17:02
> Whose attention can we bring this to if it has potentially been fixed with #6400 ??? How do we get this implemented?

If you want to implement it right away, you can build the project from the fix branch on my fork. But I wouldn't advise you to do that. 

The only solution, unfortunately, is to wait for them to merge the fix, and get the update from the app store... 

While waiting for their merge, I don't use bitwarden anymore.

**Comment by doobix** [comment] 2023-11-12 20:22
> ![image](https://user-images.githubusercontent.com/139183/282295780-cc643dea-3105-4290-930a-8608f828d24e.png)
> 
> BitWarden now doesn't even _show_ the prompt for Touch ID in Settings. This is, quite frankly, rubbish. What is the point of having a long, complex vault password, safe in the knowledge that you will only have to type it occasionally, if BitWarden then decides to throw your configuration in the bin and make you type the damn thing every time.
> 
> That just leads to users setting the timeouts to maximum and using the shortest, easiest-to-type passwords that they can. **This bug greatly reduces security, and should be treated as a high priority.** And yet it has been an issue for **over two months.**
> 
> Given Apple's App Store doesn't allow users to roll back to older, working versions (because Apple apparently think no release ever introduces new bugs, despite their obvious track record of doing exactly that) I'd appreciate knowing how I can install a version that Just Works with Touch ID and then disable automatic updates?
> 
> I've had a look through the code tree, and I can't find any automated tests for the macOS client. _Are_ there any? There _should_ be. That way, issues like this can be spotted and the offending release blocked until they're fixed…

That's weird, I have the latest Bitwarden 2023.10.1 (13648) and I have the Touch ID settings:
![Screenshot 2023-11-12 at 12 13 52 PM](https://github.com/bitwarden/clients/assets/7928977/56d18ddb-2bdc-4d6e-8a6c-6c9f5493c862)

Although it doesn't automatically prompt for my fingerprint when I launch Bitwarden, I can still click "Unlock with Touch ID" which only takes 1 second:
![Screenshot 2023-11-12 at 12 10 33 PM](https://github.com/bitwarden/clients/assets/7928977/33827097-6965-4096-85d4-1c082b43573f)

**Comment by unikitty37** [comment] 2023-11-15 09:32
@doobix After updating to macOS 13.6.1 (22G313) and rebooting, the Touch ID settings have reappeared in Bitwarden.

However, it's still not working in the Chromium plugin — it says "start the Bitwarden desktop application" even though the desktop app is *right there*:

![SCR-20231115-itmg](https://github.com/bitwarden/clients/assets/139183/38c6d394-61e7-4807-b4ab-814028a1aec3)

I'm not sure if this is the right repo for that — and if it is, whether that would be better as a separate ticket.

**Comment by maimuta8** [comment] 2023-12-01 08:53
Is there any update on this issue? I'm about to purchase Premium but right now this issue persisting is keeping me from that. It's not so much the issue, although that is very frustrating since it used to work perfectly, but more so it being ignored or at least addressed, or removed as an option.

**Comment by thomasync** [comment] 2023-12-01 10:37
- fix
- wait 1 month for review
- request changes because they made modifications
- 🔁

we have to be patient, it's a very specific bug, even if many people encounter it. but I think we've reached the end this time.

**Closed** 2023-12-13 18:16 UTC
Labels: bug, desktop

**Comment by gavro** [comment] 2024-01-02 21:30
Should the #6400 (PM-4090) PR be part of the 2023.12.1 release (see #7123)? It still does not seem to trigger on macOS when starting the app here with the latest release. I've checked the release (source tar from the releases page), but specific code found in the PR is not present in the release (e.g. `private async delayedAskForBiometric` can't be found).

**Comment by gavro** [comment] 2024-01-02 21:37
Aiii, sorry did not see that comment! Thnx!

**Comment by Pinemail** [comment] 2024-02-14 10:42
Update installed 14 February 2024 and it is now fixed, allowing Touch ID again!

**Comment by unikitty37** [comment] 2024-02-26 16:43
It still fails periodically for me, but can be re-enabled by visiting a site that has a passkey saved in Keychain, not in Bitwarden. That prompts me for my password rather than Touch ID (so it looks like macOS has forgotten it has Touch ID!) but after that, Touch ID works again until the next time.

It's possible some of this might be down to a bug in Ventura; I'll see if it still occurs once I get around to moving to Sonoma.

**Comment by stathisaska** [comment] 2024-03-11 18:50
> It still fails periodically for me, but can be re-enabled by visiting a site that has a passkey saved in Keychain, not in Bitwarden. That prompts me for my password rather than Touch ID (so it looks like macOS has forgotten it has Touch ID!) but after that, Touch ID works again until the next time.
> 
> 
> 
> It's possible some of this might be down to a bug in Ventura; I'll see if it still occurs once I get around to moving to Sonoma.

@unikitty37 Could you please describe the exact steps of what you found to be fixing the issue ?

**Comment by unikitty37** [comment] 2024-03-12 14:21
> @unikitty37 Could you please describe the exact steps of what you found to be fixing the issue ?

@stathisaska Sure:

* Try to access Bitwarden app and get error saying biometric authentication is not available on device.
* Visit a site which has a passkey saved in the browser (I'm using Vivaldi; the site I generally use is heroku.com as I've always got a tab with CI running on it, and Heroku logs you out after only a _day_).
* Press the autofill shortcut; Bitwarden browser plugin requires passphrase entry as biometric authentication is not available.
* Heroku prompts for passkey for 2FA; Touch ID prompt does _not_ appear but I am prompted for my password. (Bitwarden has already been set to "never for this site" for passkeys on heroku.com, as the iOS app doesn't support passkeys yet).
* Enter password; Heroku is now logged in.
* Try to access Bitwarden app; Touch ID is now available and works. (The same applies for the browser plugin once it has re-locked).

The fact that the passkey authentication prompt isn't generated by Bitwarden is what makes me think macOS might be at least partly to blame here.

**Comment by stathisaska** [comment] 2024-03-12 19:55
> > @unikitty37 Could you please describe the exact steps of what you found to be fixing the issue ?
> 
> @stathisaska Sure:
> 
> * Try to access Bitwarden app and get error saying biometric authentication is not available on device.
> * Visit a site which has a passkey saved in the browser (I'm using Vivaldi; the site I generally use is heroku.com as I've always got a tab with CI running on it, and Heroku logs you out after only a _day_).
> * Press the autofill shortcut; Bitwarden browser plugin requires passphrase entry as biometric authentication is not available.
> * Heroku prompts for passkey for 2FA; Touch ID prompt does _not_ appear but I am prompted for my password. (Bitwarden has already been set to "never for this site" for passkeys on heroku.com, as the iOS app doesn't support passkeys yet).
> * Enter password; Heroku is now logged in.
> * Try to access Bitwarden app; Touch ID is now available and works. (The same applies for the browser plugin once it has re-locked).
> 
> The fact that the passkey authentication prompt isn't generated by Bitwarden is what makes me think macOS might be at least partly to blame here.

Great thanks that resolved the issue!
