### ISSUE TITLE
New element pop-up doesn't show up in Safari until Bitwarden is called by clicking on the app icon next to the address bar

### ISSUE THREAD

**Issue by markspercyspencer** [bitwarden/clients#9041] opened 2024-05-04 22:05 UTC
### Steps To Reproduce

1. Go on a website with no credentials stored in Bitwarden and click on a login/sign up form. 
2. Click on 'New element (or Add element depending on the language) dropdown button'
3. Nothing happens: the password generating pop-up doesn't show up - you have to click on Bitwarden's icon next to the address bar for the pop up to eventually show up.

### Expected Result

The password generating pop-up (or New element pop-up) should appear when clicking on the dropdown button.

### Actual Result

The password generating pop-up (or New element pop-up) doesn't appear instantly when clicking on the dropdown button.

### Screenshots or Videos

https://github.com/bitwarden/clients/assets/125167586/e44fd5dc-81da-45e8-9b60-44b7644ef4cd

### Operating System

macOS

### Operating System Version

macOS 14.4.1

### Web Browser

Safari

### Browser Version

Version 17.4.1 (19618.1.15.11.14)

### Build Version

Version 2024.4.1 Shell 28.2.8 Renderer 120.0.6099.291 Node 18.18.2 Architecture arm64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment] 2024-05-06 06:41
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/clients/issues/8317

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by sammbw** 2024-05-06 06:41 UTC
Labels: bug, browser

**Comment by markspercyspencer** [comment] 2024-05-06 07:44
Hi, 

Yes, it's quite similar but I thought it was a great idea to create a separate ticket since I'm encoutnering this issue when trying to generate a password but not when unlocking the vault. 

    Le lundi 6 mai 2024 à 08:42:04 UTC+2, sammbw ***@***.***> a écrit :  
 
 


Hi there!

Thank you for your report, it seems like it is a duplicate of this one: #8317

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!
