### ISSUE TITLE
Firefox Bitwarden logging me out almost every day (again)

### ISSUE THREAD

**Issue by matteematt** [bitwarden/clients#10876] opened 2024-09-04 06:08 UTC
### Steps To Reproduce

I have my bitwarden browser extention to keep my session logged in and only require the PIN to unlock.

### Expected Result

When I start my laptop in the morning I should be able to unlock bitwarden with just the PIN I configured.

### Actual Result

It has forgotten my session and requires the master password (but usually not 2fa code that I have set). 

### Additional Context

https://github.com/bitwarden/clients/issues/8873

I raised this before and it feels like I repeat of that. Again I am not having issues in other places such as chrome, anything on Linux, or bitwarden desktop apps. 

When that issue was said as fixed before it was fixed for a while.

### Operating System

macOS

### Operating System Version

14.4.1 (23E224)

### Web Browser

Firefox

### Browser Version

129.0.2 (64-bit)

### Build Version

2024.4.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-09-04 07:27
@matteematt Based on the comment [here](https://github.com/bitwarden/clients/issues/8873#issuecomment-2185418723), this was resolved with `2024.6.3`. You state using `2024.4.1`. Please update the extension to `2024.6.3` or higher.

**Comment by matteematt** [comment] 2024-09-04 08:09
My bad, I thought it would have automatically updated by now. I had to remove it and add it againt to get it to update. Strange then that I didn't have the issue for ages then when the original ticket was closed

**Comment by djsmith85** [comment] 2024-09-04 08:33
Duplicate of #8873

**Comment by djsmith85** [comment] 2024-09-04 08:33
No worries.

Closing this now.

**Closed by djsmith85** 2024-09-04 08:33 UTC
Labels: bug, browser
