### ISSUE TITLE
Error on Bitwarden: failed to decode access token: JWT must have 3 parts

### ISSUE THREAD

**Issue by bulgroz06** [bitwarden/clients#9188] opened 2024-05-15 08:30 UTC
### Steps To Reproduce

Open Bitwarden software. 
Create a new entry (new item)
Try to save the entry
Error message appears in a red window: "An error has occurred. Failed to decode access token: JWT must have 3 parts."

I do not understand the meaning of that error and I am unable to correct it.
I cannot add new entries in my Bitwarden system.
Urgent help is needed.
Thanks

### Expected Result

The new entry should have been saved as usual

### Actual Result

Error message appears in a red window: "An error has occurred. Failed to decode access token: JWT must have 3 parts."

### Operating System

Linux

### Operating System Version

Ubuntu 22.04.4 LTS

### Web Browser

Firefox

### Browser Version

125.0.3 (64 bits)

### Build Version

version 2024.4.3 Shell 28.3.1 Renderer 120.0.6099.291 Node 18.18.2 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-05-15 08:36
Duplicate of https://github.com/bitwarden/clients/issues/8651

**Comment by djsmith85** [comment] 2024-05-15 08:37
Hi @bulgroz06 

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/8651#issuecomment-2093261158.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Comment by bulgroz06** [comment] 2024-05-15 09:01
Hello,
I am not a Linux specialist. What do I need to do ? Do you mean that a solution was found or that the problem is already known but not solved ?
I also noticed that I cannot sync vault any more.
Thanks for your help.
Laurent

**Comment by djsmith85** [comment] 2024-05-15 09:13
@bulgroz06 It is a known issue and actively being worked on as stated with https://github.com/bitwarden/clients/issues/8651#issuecomment-2093261158.

A pre-release build is available, but only meant to be used to verify it fixes the issue (see https://github.com/bitwarden/clients/issues/8651#issuecomment-2096839654). Once work on https://github.com/bitwarden/clients/pull/8913 has completed, a release will become available that addresses this issue.

**Closed by djsmith85** 2024-05-15 09:13 UTC
Labels: bug, browser

**Comment by bulgroz06** [comment] 2024-06-04 16:19
David,
I am not an expert but I cannot find a Bitwarden directory in the .config directory.
I use Ubuntu 22.04.4 LTS
I still have the same two issues with Bitwarden: unable to add a new item (error message) and unable to sync vault (syncing failed).
I am really annoyed and I hope a solution will come soon.
Laurent

**Comment by resl1337** [comment] 2024-06-06 01:32
Hey Laurent,

Since you're using Ubuntu, the location of the Bitwarden configuration directory might be different.
On Ubuntu, the Bitwarden configuration might be stored in a directory called ~/.local/share/bitwarden. You can try deleting this directory (if it exists) and then restarting Bitwarden.

**Comment by bulgroz06** [comment] 2024-06-07 19:35
Thanks for your answer. I checked : /.local/share exists. But not /.local/share/bitwarden

Regards
Laurent

**Comment by resl1337** [comment] 2024-06-07 19:48
Hi, The CTRL + H shortcut shows hidden folders on linux.  try checking both of the directories i told you about, if you still cannot find it, try searching for a file called data.json or any file mentioning "Bitwarden" using your search in ubuntu, this can help you find the config file.

Also, Bitwarden offers a built-in reset option that clears the application data without affecting the vault itself Its in settings, advanced and Reset Application Data This might help too. If not, update bitwarden in your terminal by executing: sudo apt update && sudo apt upgrade bitwarden

if neither of these options work, try reinstalling the application if you didnt already

**Comment by bulgroz06** [comment] 2024-06-07 20:06
Hey,

I searched "Bitwarden" and found the following files.

and found the following files named data.json

I could not find in the Bitwarden menus a built-in reset option.

Laurent

**Comment by bulgroz06** [comment] 2024-06-07 20:10
Tried to upgrade without success:

***@***.***:~$ sudo apt update && sudo apt upgrade bitwarden
[sudo] Mot de passe de laurent :
Atteint :1 https://linux.teamviewer.com/deb stable InRelease
Réception de :2 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Atteint :3 http://fr.archive.ubuntu.com/ubuntu jammy InRelease
Réception de :4 http://fr.archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Atteint :5 http://fr.archive.ubuntu.com/ubuntu jammy-backports InRelease
Réception de :6 https://apt.syncthing.net syncthing InRelease [15,1 kB]
272 ko réceptionnés en 1s (232 ko/s)
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances... Fait
Lecture des informations d'état... Fait
17 paquets peuvent être mis à jour. Exécutez « apt list --upgradable » pour les voir.
W: https://apt.syncthing.net/dists/syncthing/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances... Fait
Lecture des informations d'état... Fait
E: Impossible de trouver le paquet bitwarden
***@***.***:~$

**Comment by bulgroz06** [comment] 2024-06-07 20:11
If I reinstall it, I will loose all my data ?
Laurent

**Comment by resl1337** [comment] 2024-06-07 20:15
no, your data is safe and stored on cloud, but you will have to log-in again and enter your 2fa code if you have two factor authentication enabled.

**Comment by bulgroz06** [comment] 2024-06-07 20:18
Hey David,
Thanks for your help.
I need to check if I have the required passwords.
Laurent

**Comment by bulgroz06** [comment] 2024-06-07 21:15
I tried what dom21121 explained on the forum:Good morning,
I'm running bitwarden snap on Ubuntu 22.04. After doing all the manipulations -> still doesn't work.
Remove /home/snap/bitwarden folder.
Re-launch bitwarden -> OK.

I restarted Bitwarden. Bitwarden is empty and is looping constantly.

Help !!

**Comment by resl1337** [comment] 2024-06-07 21:36
Have you tried reinstalling the app?

**Comment by bulgroz06** [comment] 2024-06-07 21:49
After reinstalling, I tried to sync vault and it says "échec de la synchronisation"

**Comment by bulgroz06** [comment] 2024-06-10 08:41
David,
I give up. I need daily a password manager and Bitwarden does not work any more. Therefore I decided to move to Proton Pass.
Thanks for your help.
Regards
Laurent

**Comment by resl1337** [comment] 2024-06-10 10:46
Hey, i completely understand. even though Im not in any way related to bitwarden im sorry i could not help :[

Proton Pass is a great choice and i hope it works great for you.
