### ISSUE TITLE
Autofill doesn'work any longer - still aproblem #11435 

### ISSUE THREAD

**Issue by grauerpanther-bitwarden** [bitwarden/clients#11475] opened 2024-10-09 17:40 UTC
### Steps To Reproduce

Go to a website, which is integrated in Bitwarden
Click on login
Nothing happens, Bitwarden offers me no options

### Expected Result

Autofill-function has to work correct.

### Actual Result

Autofill doesn'work any longer - still aproblem #11435

Hello, the problem still exists. The workaround does not work. I am not able to log in without copying from the vault. I also do not use Linus with Firefox. But Windows 10 with the Bitwarden version

Version 2024.9.0
Shell 32.0.1
Renderer 128.0.6613.36
Node 20.16.0
Architecture x64

with Chrome Version 129.0.6668.90 (Offizieller Build) (64-Bit). Autofill does not work with Chrome or Edge, which I also tried. Deactivating the browser extension and reactivating the browser extension also doesn't help. Disabling the browser extension and only using the Bitwarden programme under Windows does not solve the problem, autofill does not work. I need a remedy here as quickly as possible.

### Operating System

Windows

### Operating System Version

Windows 10

### Web Browser

Chrome

### Browser Version

Version 129.0.6668.90 (Offizieller Build) (64-Bit)

### Build Version

Version 2024.9.0 Shell 32.0.1 Renderer 128.0.6613.36 Node 20.16.0 Architecture x64

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment] 2024-10-09 19:22
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/10814. 

**You might try updating your extension, as 2024.9.0 is an outdated version.**

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by Neonwarden** 2024-10-09 19:22 UTC
Labels: bug, browser
