### ISSUE TITLE
Cannot read properties of null (reading 'profile')

### ISSUE THREAD

**Issue by orassyag** [bitwarden/clients#11214] opened 2024-09-24 03:07 UTC
### Steps To Reproduce

Not sure how to reproduce, I see it on our production logs

### Expected Result

not to have this bug

### Actual Result

having this bug

### Additional Context

"/usr/local/lib/node_modules/@bitwarden/cli/build/bw.js:38741
                state.accounts[userId].profile = diskAccount.profile;
                                                             ^

TypeError: Cannot read properties of null (reading 'profile')
    at StateService.<anonymous> (/usr/local/lib/node_modules/@bitwarden/cli/build/bw.js:38741:62)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/@bitwarden/cli/build/bw.js:38651:71
    at new Promise (<anonymous>)
    at state_service_awaiter (/usr/local/lib/node_modules/@bitwarden/cli/build/bw.js:38647:12)
    at /usr/local/lib/node_modules/@bitwarden/cli/build/bw.js:38736:61
    at StateService.<anonymous> (/usr/local/lib/node_modules/@bitwarden/cli/build/bw.js:39263:44)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/@bitwarden/cli/build/bw.js:38651:71
    at new Promise (<anonymous>)

Node.js v18.13.0

### Operating System

Windows

### Shell

Bash

### Build Version

@bitwarden/cli@2024.7.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by BBGhub** [comment] 2024-09-24 03:17
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/9646. 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by BBGhub** 2024-09-24 03:17 UTC
Labels: bug, cli
