### ISSUE TITLE
Error in generating a forwarded email alias with Forward Email provider

### ISSUE THREAD

**Issue by Warafreak** [bitwarden/clients#10300] opened 2024-07-26 21:47 UTC
### Steps To Reproduce

1. Go to 'Generator -> Username'
2. Click on 'Forwarded Email Alias'
3. Select 'Forward Email' as Service
4. Enter a valid API token and the chosen domain
5. Click on the 'Generate' button (reloading symbol)

### Expected Result

The generated username is shown in the field and able to be entered into the entry

### Actual Result

The error message 'Response.json: Body has already been consumed.' pops up.

The network tab clearly shows a successful request with response code 200 and all the required information contained therein.

### Additional Context

I believe the error occurs [here](https://github.com/bitwarden/clients/blob/main/libs/tools/generator/core/src/strategies/forwarders/forward-email.ts#L80). 

### Operating System

Windows

### Web Browser

Firefox

### Browser Version

128.0.2

### Build Version

2024.6.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-07-27 00:04
Duplicate of https://github.com/bitwarden/clients/issues/10091

**Comment by SergeantConfused** [comment] 2024-07-28 15:53
Hello @Warafreak,

Thank you for your report. If there's anything you'd like to add, such as screenshots or video recordings of the screen, please feel free to add them to that [existing GitHub report](https://github.com/bitwarden/clients/issues/10091) so that they'd be reviewed by the Bitwarden Engineering department.

This report will now be closed as a duplicate.

Thank you again,

**Closed by SergeantConfused** 2024-07-28 15:53 UTC
Labels: bug, browser

**Comment by djsmith85** [comment] 2024-08-01 07:33
> Team here from @forwardemail – ping us or email `support@forwardemail.net` if you have any issues with our service or need us to contribute here again on Bitwarden 🙏

Thank you @titanism for offering your help❤️ ! This was issue on our end, caused by a large rewrite of the generators. It's been addressed with https://github.com/bitwarden/clients/pull/10075 and those changes will be included in the next release.

**Comment by Segment0895** [comment] 2024-08-14 11:38
Can anyone verify if fixed? Two days ago it wasn't.

**Comment by djsmith85** [comment] 2024-08-14 12:28
> Can anyone verify if fixed? Two days ago it wasn't.

@Segment0895 The changes are included in the current release candiate which is currently scheduled to be released next week.
