### ISSUE TITLE
Infinite loading after logging in on ubuntu desktop

### ISSUE THREAD

**Issue by ReyJust** [bitwarden/clients#8915] opened 2024-04-25 07:50 UTC
### Steps To Reproduce

1. Open bitwarden
2. Login with your password

### Expected Result

I expect that all my passwords appear.

### Actual Result

Infinite loading

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/74152565/a828d9ea-edc3-4c74-82d2-bd3df4e32102)

### Additional Context

Using the browser, on bitwarden vaut, or my phone I can access everything without any problem.

Let me know what can I do to provide more logs etc...

I can't no my build version, look at the about ahah (But my .deb contains "2024.4.1-amd64")
![image](https://github.com/bitwarden/clients/assets/74152565/9bcfb510-d71f-4218-8186-35f024fca34d)

### Operating System

Linux

### Operating System Version

Ubuntu 23.10

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.4.1-amd64

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TansyEH** [comment] 2024-04-25 14:30
Exactly the same thing is happening for me with Ubuntu :-( Has been going on for a few days. Please help BitWarden...

**Comment by TansyEH** [comment] 2024-04-25 14:32
I've tried uninstalling and reinstalling and it just infinitely spins...

**Comment by djjuhasz** [comment] 2024-04-25 15:50
I'm having the same problem with the Bitwarden snap on Ubuntu 22.04.4 LTS.

Bitwarden info:
Version 2024.4.0
Shell 28.2.8
Renderer 120.0.6099.291
Node 18.18.2
Architecture x64

**Comment by djsmith85** [comment] 2024-04-25 15:53
Duplicate of https://github.com/bitwarden/clients/issues/8651

**Comment by djsmith85** [comment] 2024-04-25 15:53
Hi there!

Thank you for your report, it seems like it is a duplicate of this one (https://github.com/bitwarden/clients/issues/8651)

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2024-04-25 15:53 UTC
Labels: bug, desktop

**Comment by TansyEH** [comment] 2024-04-25 16:09
Hello,
I've switched on the 'Read, add, change' and bitwarden is still not working.
Please help me out.

With all best wishes,
Tansy.

Tansy E. Hoskins. Award-winning author and journalist
Click here for my website + sign up for my free newsletter:
https://tansyhoskins.org/

**Comment by cg-scorpio** [comment] 2024-05-30 07:38
I have the same problem. Very embarrassing...
