### ISSUE TITLE
Bitwarden Firefox extension shows Autofill menu when it's disabled

### ISSUE THREAD

**Issue by BarisKaragoz** [bitwarden/clients#11485] opened 2024-10-10 12:40 UTC
### Steps To Reproduce

1. Go to a website where you have credentials stored in Bitwarden
2. I get the Bitwarden autofill menu, but it's disabled so the menu should not show up.

### Expected Result

Login forms should not show the Bitwarden autofill menu when it's disabled

### Actual Result

Bitwarden autofill menu still being shown at login forms

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/7d1421c0-4137-465f-83ce-ea1de7816154)
![image](https://github.com/user-attachments/assets/cf5254fe-8ec7-4c88-b9b8-f7cee260a511)

### Additional Context

I use Firefox ESR 128.3.1
Bitwarden Extension version 2024.9.1

I also tried the main branch of Firefox, still the same.
Reinstalled Firefox, extension, new profile etc etc. Still the same.

I use a selfhosted version of Bitwarden called Vaultwarden, version 1.32.1 however I don't think this should cause the issue because it worked without problems before and the Firefox extension is official from Bitwarden.

### Operating System

Windows

### Operating System Version

Windows 11 23H2

### Web Browser

Firefox

### Browser Version

128.3.1 ESR

### Build Version

128.3.1 ESR

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by dev-nicolaos** [comment] 2024-10-10 14:36
This is happening for me on both of my machines.

- Windows 10 22H2 w/Firefox 131.0.2
- Fedora 40 w/Firefox Flatpak 131.0.2

**Comment by mort666** [comment] 2024-10-10 16:08
Likewise, having the same issue with Firefox and Chromium now. Was occurring with Firefox now for a few days and today it started to occur in Chromium and Brave, pretty much occurs with any Chromium based browser that is 126.x.x or newer. For Firefox based browsers it is occurring in ESR and Normal Firefox and in other Firefox forked browsers such as Zen (1.0.1-a.7), Tor Browser and LibreWolf 126.0-1 and newer.

**Comment by cagonzalezcs** [comment] 2024-10-10 17:46
This is a duplicate of https://github.com/bitwarden/clients/issues/11173

This was fixed in version `2024.10.0` of the extension. This version was submitted to the Firefox add-ons store last week and should be appearing soon.

**Closed by cagonzalezcs** 2024-10-10 17:46 UTC
Labels: bug, browser
