### ISSUE TITLE
Passkeys -> getPublicKey() function not implemented, passkeys feature not following W3C standards

### ISSUE THREAD

**Issue by wnelson03** [bitwarden/clients#6913] opened 2023-11-20 03:09 UTC
### Steps To Reproduce

1. Go to https://webauthn.passwordless.id/demos/playground.html
2. Click on **Register Device** button
3. Scroll down to under that button you just clicked
4. You will see that the "publicKey" field is empty.

### Expected Result

A valid public key is retrieved

### Actual Result

No valid public key is retrieved, empty string. Failed registration

### Additional Context

Supposedly this occurs according to the creator of this passwordless.id WebAuthn library because Bitwarden doesn't provide a `getPublicKey` method, which does not follow W3C standards

https://github.com/passwordless-id/webauthn/issues/37#issuecomment-1794726672

I look forward to this being resolved soon. It would be great if some of my website users who can't afford a physical security key can still benefit from WebAuthn stored in their Bitwarden.

I tested on Firefox, but the original poster of the GitHub issue I linked supposedly tested on Chrome. So it's a problem on all distributions of the Browser extension.

### Operating System

Windows

### Web Browser

Firefox

### Build Version

2023.10.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by coroiu** [comment] 2023-11-21 15:56
I'm not sure it would be fair to say that we are not compatible with the WebAuthn standard. From the way I understand the specification `getPublicKey()` is optional and might return `null`. But maybe I've misunderstood? The spec is pretty complex :)

https://www.w3.org/TR/webauthn-3/#dom-authenticatorattestationresponse-getpublickey
> This operation returns the DER [SubjectPublicKeyInfo](https://tools.ietf.org/html/rfc5280#section-4.1.2.7) of the new credential, or null if this is not available. See [§ 5.2.1.1 Easily accessing credential data](https://www.w3.org/TR/webauthn-3/#sctn-public-key-easy).

Also I'm not saying that we shouldn't implement this! I'm just saying that the bug might not be our fault, and that this issue might appear in the future with other authenticators as well

**Comment by holow29** [comment] 2023-11-21 16:25
It seems like it might be allowably null in 2 cases (from [§ 5.2.1.1 Easily accessing credential data](https://www.w3.org/TR/webauthn-3/#sctn-public-key-easy)):
1) user-agent is not at level 2 of the spec
> Note: [getPublicKey()](https://www.w3.org/TR/webauthn-3/#dom-authenticatorattestationresponse-getpublickey) and [getAuthenticatorData()](https://www.w3.org/TR/webauthn-3/#dom-authenticatorattestationresponse-getauthenticatordata) were only added in level two of this spec. [Relying Parties](https://www.w3.org/TR/webauthn-3/#relying-party) SHOULD use feature detection before using these functions by testing the value of 'getPublicKey' in AuthenticatorAttestationResponse.prototype. [Relying Parties](https://www.w3.org/TR/webauthn-3/#relying-party) that require this function to exist may not interoperate with older user-agents.

2) User-agent doesn't understand public key algorithm requested

> Use of [getPublicKey()](https://www.w3.org/TR/webauthn-3/#dom-authenticatorattestationresponse-getpublickey) does impose some limitations: by using [pubKeyCredParams](https://www.w3.org/TR/webauthn-3/#dom-publickeycredentialcreationoptions-pubkeycredparams), a [Relying Party](https://www.w3.org/TR/webauthn-3/#relying-party) can negotiate with the [authenticator](https://www.w3.org/TR/webauthn-3/#authenticator) to use public key algorithms that the user agent may not understand. However, if the [Relying Party](https://www.w3.org/TR/webauthn-3/#relying-party) does so, the user agent will not be able to translate the resulting [credential public key](https://www.w3.org/TR/webauthn-3/#credential-public-key) into [SubjectPublicKeyInfo](https://tools.ietf.org/html/rfc5280#section-4.1.2.7) format and the return value of [getPublicKey()](https://www.w3.org/TR/webauthn-3/#dom-authenticatorattestationresponse-getpublickey) will be null.

> User agents MUST be able to return a non-null value for [getPublicKey()](https://www.w3.org/TR/webauthn-3/#dom-authenticatorattestationresponse-getpublickey) when the [credential public key](https://www.w3.org/TR/webauthn-3/#credential-public-key) has a [COSEAlgorithmIdentifier](https://www.w3.org/TR/webauthn-3/#typedefdef-cosealgorithmidentifier) value of:
-7 (ES256), where [kty](https://tools.ietf.org/html/rfc9052#name-cose-key-common-parameters) is 2 (with uncompressed points) and [crv](https://tools.ietf.org/html/rfc9053#name-double-coordinate-curves) is 1 (P-256).
-257 (RS256).
-8 (EdDSA), where [crv](https://tools.ietf.org/html/rfc9053#name-double-coordinate-curves) is 6 (Ed25519).

> A [SubjectPublicKeyInfo](https://tools.ietf.org/html/rfc5280#section-4.1.2.7) does not include information about the signing algorithm (for example, which hash function to use) that is included in the COSE public key. To provide this, [getPublicKeyAlgorithm()](https://www.w3.org/TR/webauthn-3/#dom-authenticatorattestationresponse-getpublickeyalgorithm) returns the [COSEAlgorithmIdentifier](https://www.w3.org/TR/webauthn-3/#typedefdef-cosealgorithmidentifier) for the [credential public key](https://www.w3.org/TR/webauthn-3/#credential-public-key).

It seems that adding support would therefore allow for better compatibility and be progress towards elevating Bitwarden to a higher level of the spec, but that this might require more care to make sure it supports the requisite algorithms.

**Comment by coroiu** [comment] 2023-11-21 16:33
Yeah so without this we are technically only Level 1 compliant, thanks for providing additional information! We'll look into this as soon as we are able :)

**Comment by trmartin4** [comment] 2023-11-27 18:51
This will be resolved with the fix in https://github.com/bitwarden/clients/pull/6934 when it is released.

**Closed by trmartin4** 2023-11-27 18:51 UTC
Labels: bug, browser

**Comment by gbubemismith** [comment] 2023-12-08 15:30
@wnelson03 the fix for this issue was not included in the latest release, and this was due to the timing of our release cycle and when the fix was implemented. However, I can confirm that the fix has been completed and is slated for inclusion in our next release.

**Comment by djsmith85** [comment] 2023-12-22 21:01
> > @wnelson03 the fix for this issue was not included in the latest release, and this was due to the timing of our release cycle and when the fix was implemented. However, I can confirm that the fix has been completed and is slated for inclusion in our next release.
> 
> Wow. Version 2023.12.1 just came out and the `getPublicKey()` function **still does not work**. What is the ETA for this? Will this ever release?

@wnelson03: What @gbubemismith meant was the next major release which will be `2024.1`. The `2023.12.1`-release was cut to fix an issue with the newly available inline autofill
