### ISSUE TITLE
Flatpak from official default repository and AppImage from Bitwarden website blank after 2-5 seconds (sign-in page, no info on other page as it's stuck on the sign in one)

### ISSUE THREAD

**Issue by tsoruu** [bitwarden/clients#6587] opened 2023-10-15 14:15 UTC
### Steps To Reproduce

1. Run flatpak install bitwarden, choose the only option. Wait for install
2. Upon install is finished, run Bitwarden. Try to login
3. Open https://bitwarden.com/download/ and click on the Linux one. Run after file downloaded
4. Install Bitwarden from the downloaded file, run Bitwarden. Try to login

### Expected Result

No blank page, login as usual by inputting email and password

### Actual Result

Blank after 2-5 seconds. DevTools indicate it got disconnected from the page.

### Screenshots or Videos

[Screencast from 2023-10-15 22-12-33.webm](https://github.com/bitwarden/clients/assets/83799574/35ec80e9-0531-4fc8-bd87-a709d112949d)

### Additional Context

Bitwarden installed obtained from Flatpak official repository and Bitwarden official download page. No sub-system is used when installing both application.

### Operating System

Linux

### Operating System Version

VanillaOS 

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.9.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2023-10-15 15:09
Duplicate of https://github.com/bitwarden/clients/issues/6560

**Comment by djsmith85** [comment] 2023-10-15 15:10
Hi @tsoruu,

Thank you for your report. This report seems like it is a duplicate of this (https://github.com/bitwarden/clients/issues/6560).

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This report will now be closed.

Thank you again

**Closed** 2023-10-15 15:10 UTC
Labels: bug, desktop

**Comment by tsoruu** [comment] 2023-10-15 15:38
Sorry for the duplicated post... Will be waiting for the fix in said post...
