### ISSUE TITLE
Password and Username edits not showing until you click out and back into the item

### ISSUE THREAD

**Issue by Tuition0479** [bitwarden/clients#12219] opened 2024-12-03 15:14 UTC
### Steps To Reproduce

1. Click on an item.
2. Edit the item.
3. Run the password or username generator.
4. Accept generated change.
5. click save
6. If you view or copy the password at this point, it will be the old password or username.  You have to click on another item, then back into the item you just updated for it to register the updated password or username.

### Expected Result

The password or username would immediately be updated onscreen and available for copy after saving as it has for the past few years I have used BitWarden

### Actual Result

The information is stale and must be refreshed by clicking on another item them back into the updated item

### Screenshots or Videos

https://github.com/user-attachments/assets/6f04d653-1713-4911-9b5d-5bd510cb5991

### Operating System

Windows

### Operating System Version

Edition	Windows 11 Pro Version	23H2 Installed on	‎8/‎31/‎2023 OS build	22631.4460 Experience	Windows Feature Experience Pack 1000.22700.1047.0

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.11.2 

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment] 2024-12-03 15:25
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by Tuition0479** [comment] 2024-12-03 15:34
That is great!  Will there be any further status updates on the issue?

Thank you,

Brian Burkett
Accounting Manager
Family Health Center, Inc
502-772-8632 Phone
502-772-8615 Fax


***@***.***


CONFIDENTIALITY NOTICE: This electronic mail may contain information that is privileged, confidential, and/or otherwise protected from disclosure to anyone other than its intended recipient(s). Any dissemination or use of this electronic mail or its contents by persons other than the intended recipient(s) is strictly prohibited. If you have received this communication in error, please notify the sender immediately by reply e-mail so that we may correct our internal records. Please then delete the original message.

**Comment by SergeantConfused** [comment] 2024-12-07 17:56
Hello @Tuition0479 and everyone else,

Thank you for this report and input. This report does indeed seem to be a duplicate of this existing [GitHub report](https://github.com/bitwarden/clients/issues/12022) (thank you, @bwbug); if there's anything anyone would like to add, such as screenshots or video recordings of the screen, please feel free to add those to that existing GitHub report so that they'd be reviewed by the Bitwarden Engineering team.

This report will now be closed as a duplicate.

Thank you all again,

**Closed by SergeantConfused** 2024-12-07 17:56 UTC
Labels: bug, desktop
