### ISSUE TITLE
Unable to save new entry

### ISSUE THREAD

**Issue by pepijnhub** [bitwarden/clients#9391] opened 2024-05-28 07:09 UTC
### Steps To Reproduce

1. Go to " + ", enter information, attempt to save:

### Expected Result

New entry is saved.

### Actual Result

Error message about invalid JWT

### Screenshots or Videos

![Screenshot](https://github.com/bitwarden/clients/assets/35801081/24283436-d4ee-4bcc-824c-7b4dfe2e598c)

### Additional Context

Also experiencing sync issues, as reported here: https://github.com/bitwarden/clients/issues/9341 

### Operating System

Linux

### Operating System Version

Ubuntu 22.04.4

### Installation method

Other

### Build Version

2024.5.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment] 2024-05-28 10:55
Hi @pepijnhub ,

Thank you for this report. It seems to be a duplicate of a matter discussed in an https://github.com/bitwarden/clients/issues/8651; 

Please read the [documentation in the Bitwarden Help Centre](https://bitwarden.com/help/getting-started-desktop/#tab-3-6vQUhrVotSKFarA3cqyESG) to allow the Snap desktop client to access Secure Storage and operate as expected; Afterwards, log out and log in anew.

I will now proceed and close this GitHub report. If you have any further questions or concerns, please feel free to create a [support ticket](https://bitwarden.com/help/) or to raise them in that existing thread.

Thank you again,

**Closed by daniellbw** 2024-05-28 10:55 UTC
Labels: bug, desktop

**Comment by keilmillerjr** [comment] 2024-06-21 22:11
SNAP SUCKS. Not everyone uses snap. Stop peddling that nonsense as an excuse for leaving many with a broken app.

**Comment by keilmillerjr** [comment] 2024-06-25 23:02
Issue resolved with yesterdays update in arch extra repository, bitwarden 2024.6.2-1. It is about time. A tool that people have become to rely on for security should never have a change that yields it broken.
