### ISSUE TITLE
Firefox extension prevents proper XML file display

### ISSUE THREAD

**Issue by hrunting** [bitwarden/clients#6865] opened 2023-11-10 22:27 UTC
### Steps To Reproduce

1. Go to '[this XML file](https://www.w3schools.com/xml/simple.xml)'

### Expected Result

In Firefox, this should display a navigable XML document tree.

### Actual Result

In Firefox, this renders the text in the nodes found in the XML document, rather than the XML tree itself.

### Screenshots or Videos

![XML file without Bitwarden extension enabled](https://github.com/bitwarden/clients/assets/260933/2285b571-69f5-4721-9073-f01242ea9bd8)
![XML file with Bitwarden extension enabled](https://github.com/bitwarden/clients/assets/260933/66d71bb7-e9db-46e6-8bd1-afd1cfc55d9b)

### Additional Context

This seems to have started with version 2023.10.x. I currently have Firefox 119.0.1 and Bitwarden extension version 2023.10.2. The behavior of XML documents definitely changed within the past two weeks, as XML previously displayed fine.

You can restore the correct browser XML document behavior by either disabling the extension or going to Settings > Excluded domains within the extension and adding the domain of the page.

I have not tested on other browsers.

### Operating System

Windows

### Operating System Version

Windows 11 23H2

### Web Browser

Firefox

### Browser Version

119.0.1

### Build Version

2023.10.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by vaionescu** [comment] 2023-11-11 22:47
I'm having the same issue on Firefox on Linux. I tried downgrading the Bitwarden addon - version 2023.10.1 still has the same issue, but version 2023.9.2 doesn't, so presumably the bug was introduced in release 2023.10.1.

OS: Debian 12
Browser: Firefox 119.0.1 (64-bit)
Addon Version: 2023.10.2

**Comment by SergeantConfused** [comment] 2023-11-12 14:00
Hi @hrunting,

Thank you for your report. I was able to reproduce this behaviour and I have flagged it to our Engineering team.

If you wish to add any further information, such as screenshots or screen recordings, please feel free to do so at any time - our Engineering team will be happy to review them.

Thank you again,

**Comment by ChristopherCarver** [comment] 2023-11-14 16:05
Same exact issue. The ability to look at XML files directly for ServiceNow development is critical. I have to turn off the plugin to do my daily work.

OS: Windows 10.0.19044 Build 19044
Browser: Firefox 119.0.1 
Addon Version: 2023.10.2

**Comment by SjetCraft** [comment] 2023-11-15 21:50
Same issue with viewing XML files. @ChristopherCarver Downgrading the plugin to version 2023.9.2 is working as a workaround. 

OS: Windows 11 22H2 
Browser: Firefox 119.0.1
Addon Version: 2023.10.2

**Comment by le-burger** [comment] 2023-11-20 12:35
Same issue. 

OS: macOS Sonoma
Browser: Firefox 119.0.1
Addon Version: 2023.10.2

**Comment by gaeljw** [comment] 2023-11-26 14:38
Same here.

OS: Fedora 38
Browser: Firefox 119.0.1
Addon version: 2023.10.2

**Comment by elisimpson** [comment] 2023-12-05 08:12
Same.

OS: Windows 11 23H2
Browser: Firefox 120.0.1
Addon: 2023.10.3

**Comment by ahmadalkhansa** [comment] 2023-12-05 13:53
Experiencing the same issue.

OS: macOS Sonoma 14.1.2
Browser: Firefox Version 120.0.1
Addon: 2023.10.2

**Comment by hrunting** [comment] 2023-12-12 18:31
Now with version 2023.12.0, it also seems to be ignoring the excluded domain list. The site that I was having this problem with was in my excluded domain list, and now Bitwarden is injecting a script into it.,

It's getting worse, guys. Any update?

**Comment by dan2097** [comment] 2023-12-12 18:33
Same
OS: Windows10.0.19045 Build 19045
Browser: Firefox 120.0.1
Addon: 2023.12.0

I started noticing this issue a couple of months ago, and was working around this issue using the excluded domain list, but this is also no longer working for me

**Comment by kepstin** [comment] 2023-12-13 16:48
A Firefox issue regarding a different extension: [Bug 1605657](https://bugzilla.mozilla.org/show_bug.cgi?id=1605657#c4) provides some technical information about why this happens:

> FWIW, this looks to me like a compat issue between the react devtools and our XML pretty printer. The pretty printer turns itself off if anything modifies the DOM ( https://searchfox.org/mozilla-central/rev/8f7b017a31326515cb467e69eef1f6c965b4f00e/dom/xml/nsXMLPrettyPrinter.cpp#147 ), which the react devtools do because they insert a <script> tag from https://github.com/facebook/react/blob/b438699d3620bff236282b049204e1221b3689e9/packages/react-devtools-extensions/src/injectGlobalHook.js#L85 .
> 
> The simplest fix here would be the react/redux devtools not doing that (ie don't inject <script> tags into random XML documents...).

A similar issue and fix likely applies here - the Bitwarden extension should check that the content-type of the document is `text/html` before injecting a `<script>` tag.

Given that this only started with a recent update, I suspect it's related to the script injected to override the browser's FIDO2 implementation, which appears to be this code:

https://github.com/bitwarden/clients/blob/bf60711efec33fd3b07227a58856dec6396e8e18/apps/browser/src/vault/fido2/content/content-script.ts#L66-L82

**Comment by funky-jojo** [comment] 2023-12-13 16:50
Nice - makes sense.


Joseph Gabriel
Norima Consulting
828-455-0672
________________________________

**Comment by kepstin** [comment] 2023-12-13 17:35
Note that if you're not actually using the Bitwarden extension's Passkey support, a workaround is available. You can turn off "Settings → Options → Ask to save and use passkeys" and the script injection will be disabled, so XML files will display correctly.

**Comment by funky-jojo** [comment] 2023-12-13 17:39
Genius.  Thank you for taking time to investigate and provide this information.  Your idea solved my problem immediately.  I use xml viewer many times per day so this is a big help


Joseph Gabriel
Norima Consulting
828-455-0672
________________________________

**Comment by elisimpson** [comment] 2023-12-13 23:59
> Note that if you're not actually using the Bitwarden extension's Passkey support, a workaround is available. You can turn off "Settings → Options → Ask to save and use passkeys" and the script injection will be disabled, so XML files will display correctly.

Thank you for the workaround! Resolved the issue immediately

**Comment by SylwesterZarebski** [comment] 2023-12-22 10:06
Not fixed in latest 2023.12.1.

**Comment by StefanBrand** [comment] 2024-02-02 08:18
> You can turn off "Settings → Options → Ask to save and use passkeys" and the script injection will be disabled, so XML files will display correctly.

This workaround does not work for me in 2024.1.1. I disabled the option and still XML files such as https://tiles.maps.eox.at/wms?service=wms&request=getcapabilities display unformatted.

**Comment by StefanBrand** [comment] 2024-02-02 14:02
I have contacted Bitwarden support and this is the response I received a couple hours later: 

>>>

> ​Thank you for reaching out!
> 
> **​Our engineering team is aware of this issue and is working on a solution.** I apologise for the inconvenience in the meantime.
> 
> On the GitHub issue you sent a link to one user(https://github.com/bitwarden/clients/issues/6865#issuecomment-1854321285) seems to have found a possible workaround for the solution. 
> 
> Another thing you could do is side loading the extension(this is not recommended but an option):
> https://extensionworkshop.com/documentation/publish/distribute-sideloading/
> ​
> If there's anything else we can help with, please let us know!
> 

>>>

**Comment by StefanBrand** [comment] 2024-02-22 06:51
> and make sure that it's actually the Bitwarden extension that's causing the problem by disabling all extensions and turning them on one by one until you find the one that's causing the issue.

Turns out that I had yet another extension that meddled with XML: https://addons.mozilla.org/en-US/firefox/addon/web-scraper/

After disabling that, Firefox can pretty-print XML again.

**Comment by cagonzalezcs** [comment] 2024-03-05 18:30
Thank you for the feedback everyone.

A fix for this issue is now in review, and should be available within the `v2024.4.0` extension release. The workaround for this problem until this fix goes into production will be to turn off saving of passkeys within your extension. This can be done by going to `Settings > Options > Ask to save and use passkeys` and checking the checkbox input for this to an off state.

I'm closing this thread, but please feel free to continue discussion as necessary.

**Closed by cagonzalezcs** 2024-03-05 18:30 UTC
Labels: bug, browser

**Comment by EpocDotFr** [comment] 2024-04-10 21:49
Have the exact same versions as @Fossil01, except I'm on Windows 10. I confirm the issue's still there:

![image](https://github.com/bitwarden/clients/assets/2053431/75ed9e9a-ab36-4bc2-b14e-8785d527e7a2)

**Comment by SylwesterZarebski** [comment] 2024-04-11 09:47
Official release is still `2024.2.1`, thus no fix available. When can we expect `2024.4.0` version?

**Comment by cagonzalezcs** [comment] 2024-04-11 15:41
The next version is `v2024.3.1`, which has been submitted to all web stores. They should be released upon approval, and is already appearing within Chrome and Edge. Mozilla takes a bit more time in their review process, but the release of that version should be out soon.

**Comment by EpocDotFr** [comment] 2024-04-11 18:09
Thank you Cesar.
