### ISSUE TITLE
Firefox extension appears to interfere with javascript on Mozilla MDN site

### ISSUE THREAD

**Issue by alyandon** [bitwarden/clients#11408] opened 2024-10-04 12:53 UTC
### Steps To Reproduce

1. Create a new Firefox profile
2. Go to https://developer.mozilla.org/en-US/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript/
3. Notice that the example canvas element at the bottom of the pages has shapes drawn
4. Install Firefox Bitwarden extension
5. Log into extension
6. Exit Firefox
7. Restart Firefox and revisit https://developer.mozilla.org/en-US/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript/
8. Notice that the example canvas element is left blank after page has rendered
9. Dsiable the Bitwarden extension and refresh the page
10. Notice that the example canvas elements are drawn correctly
11. Re-enable Bitwarden extension and refresh page
12. Notice that the canvas element is now blank again

### Expected Result

Example canvas elements should always be drawn regardless of whether the Bitwarden extension is enabled or not.

### Actual Result

Canvas does not appear to render correctly.

### Operating System

Windows

### Operating System Version

Windows 22H2 19045.4894

### Web Browser

Firefox

### Browser Version

132.0b2 (64-bit)

### Build Version

2024.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment] 2024-10-07 13:00
Hi there!

Thank you for your report, It seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/11234

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by cbbit** 2024-10-07 13:00 UTC
Labels: bug, browser
