### ISSUE TITLE
Bug in new autofill menu on form fields thingy

### ISSUE THREAD

**Issue by simonz21** [bitwarden/clients#7563] opened 2024-01-16 10:03 UTC
### Steps To Reproduce

Switch on new Autofill on menu option (on focus or Icon, happens with both options)
Find a login screen that used to work before, and now doesn't. I have come across quite a few, but this morning it was with https://areariservata.ing.it/login  
autofill for username & p/w  on load no longer works
neither does fill on keyboard shortcut
turn OFF autofil menu thing, and site immediately starts working again

### Expected Result

username & p/w should fill automatically, or the BW logo should appear in the fields, or the option should be there if i click inside the field. But I get nothing. only way to complete the field is to copy and paste. Turn off new option and BW autofills both fields correctly. Not just happening on one site. Noticed it on a few.

### Actual Result

autofill for username & p/w  on load no longer works

### Additional Context

there’s a bug in the new autofill from menu fields thingy. Some logins (like ING Bank Italy) which work fine with this switched off, stop working completely when either of the autofill menu options is selected. doesn’t look like it’s completely working yet so i have had to turn it off. shame, as it looked pretty handy…

### Operating System

Windows

### Operating System Version

10 Pro 22H2

### Web Browser

Chrome, Microsoft Edge

### Browser Version

latest

### Build Version

23.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment] 2024-01-19 08:27
Hi there,

I tested this and unfortunately could not replicate. 

This can also be marked as a duplicate of #1621 , so I will close this
https://github.com/bitwarden/clients/issues/1621#issue-811491652 
Please could you look at #1621 to better understand how this can be reported in a single place.

**Closed by daniellbw** 2024-01-19 08:27 UTC
Labels: bug, browser
