### ISSUE TITLE
Application crash when interacting with Card records when 'prompt master password' is enabled

### ISSUE THREAD

**Issue by jessehorner** [bitwarden/clients#6345] opened 2023-09-20 00:43 UTC
### Steps To Reproduce

1. Unlock Bitwarden using biometrics (Face ID, Touch ID etc.) and NOT the master password.
2. Navigate to the 'Card' section and select a card which has 're-prompt master password is enabled'
3. Attempt an action which would prompt the master password (edit, reveal a hidden field, copy a hidden etc.)

The application will crash _after_ entering the master password. 

This only occurs when the application is initially unlocked using biometrics. If the master password is used to unlock the app performing these actions above will not crash the app.

This also occurs on iOS, but don't see the iOS app as an option.

### Expected Result

The application to not crash.

### Actual Result

Application crash

### Operating System

macOS

### Operating System Version

13.5.2 (22G91)

### Installation method

Mac App Store

### Build Version

Version 2023.8.4 (11864)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment] 2023-09-20 05:15
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: [bitwarden/clients#6153](https://github.com/bitwarden/clients/issues/6153)

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by sammbw** 2023-09-20 05:15 UTC
Labels: bug, desktop
