### ISSUE TITLE
Variable storing the hostname of the connecting server  displays its variable name instead of the actual hostname after upgrade from earlier version (2023.3.1 => 2023.12.1)...

### ISSUE THREAD

**Issue by djchateau** [bitwarden/clients#7389] opened 2023-12-28 22:44 UTC
### Steps To Reproduce

I had an older version (2023.3.1) of Bitwarden still running on one of my Linux boxes and realized I hadn't updated in awhile (I utilize the Debian package for installation). When I went to update it, a weird bug popped up where the variable containing what host I would be connecting to showed the actual variable name used to store the server name and not listing the actual server I normally connect to. I was still able to decrypt the vault, but syncing would fail for obvious reasons. Reloading the desktop application did not resolve this, but blowing away the original directory for it located in `~/.config/` did. I have not tried to replicate this with other installation methods so I'm unsure if this is unique to the Debian package installation method or something occurring across all installation method of Bitwarden's desktop application.

### Steps to Reproduce

1. _Install_ version `2023.3.1`.
2. _Login_ to store session.
3. _Close_ application.
4. _Install_ version `2023.12.1`.
5. _Open_ the application.

### Expected Result

Displaying the host the user account was logged into from previous session.

### Actual Result

Server variable displaying its variable name instead of the previous server it was connected to.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/1657434/0864614e-aef8-49c6-ae18-1f3b24a41bf2)

### Additional Context

As this was a jump of several versions, this may very well be a non-issue, but it does create the possibility of users submitting unnecessary support requests for an issue that could be avoided if the desktop application is doing additional checks to deal with either corrupted data or changes in data format after an upgrade. If you'd like me to try to replicate in some other way or if you need additional details, please let me know.

### Operating System

Linux

### Operating System Version

Ubuntu 22.04.3 LTS

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment] 2023-12-28 23:04
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below.

Thanks!

**Comment by djsmith85** [comment] 2024-01-02 17:02
Duplicate of https://github.com/bitwarden/clients/issues/7160

**Closed by djsmith85** 2024-01-02 17:02 UTC
Labels: bug, desktop
