### ISSUE TITLE
Activate Bitwarden keeps popping up

### ISSUE THREAD

**Issue by nebea** [bitwarden/clients#12474] opened 2024-12-19 07:56 UTC
### Steps To Reproduce

Happens randomly when I 
- either open bitwarden desktop
- come back the next day on turn on my laptop (from sleep)

### Expected Result

No spam

### Actual Result

Spam

### Screenshots or Videos

<img width="2542" alt="image" src="https://github.com/user-attachments/assets/01eef528-a2fa-4ba7-b0e8-fdbc1de0c9ef" />

### Additional Context

It happens since I have it (over months). It happens sometimes more and sometimes less. 

### Operating System

macOS

### Operating System Version

15.0

### Web Browser

Safari

### Browser Version

18.0

### Build Version

2024.12.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment] 2024-12-19 10:21
Hello there, 

Will you try uninstalling the application, removing any leftover data, powering off and on your device and re-installing? Does this issue still persist?

Guide to the leftover data: https://bitwarden.com/help/data-storage/#on-your-local-machine

**Comment by djsmith85** [comment] 2024-12-19 12:11
Duplicate of https://github.com/bitwarden/clients/issues/11694

**Comment by djsmith85** [comment] 2024-12-19 12:12
Hi There,

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/11694

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This should be fixed in a coming update to the Bitwarden Extension.

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2024-12-19 12:12 UTC
Labels: bug, browser
