### ISSUE TITLE
Remember email feature not work anymore

### ISSUE THREAD

**Issue by scruel** [bitwarden/clients#10311] opened 2024-07-29 04:32 UTC
### Steps To Reproduce

1. Goto bitwarden plugin login page
2. Type your email
3. Tick "Remember email"
4. Login as usual, then logout
5. Goto login page again to check the remembered eamil

### Expected Result

email will be remembered by plugin

### Actual Result

No email been remembered.

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/9c42dea4-70d7-46fe-84fa-eed6bfb9fbe7)

### Additional Context

https://community.bitwarden.com/t/chrome-extension-will-no-longer-remember-email-address/68227

### Operating System

Windows

### Web Browser

Firefox

### Browser Version

dev 129.0b8 (64-bit)

### Build Version

2024.6.3

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment] 2024-07-30 07:29
Also duplicate of https://github.com/bitwarden/clients/pull/9750

**Closed by Adedamola-Aina** 2024-07-30 07:29 UTC
Labels: bug, browser
