### ISSUE TITLE
Linux DT App just spins after login

### ISSUE THREAD

**Issue by EmanNo1** [bitwarden/clients#9540] opened 2024-06-06 20:18 UTC
### Steps To Reproduce

1. Launch Application
2. Authenticate
3. Vaults and Items populate, main area has spinner

### Expected Result

Used to show list of password items

### Actual Result

Continuous spinner

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/2874846/5b469594-bbce-4beb-b805-1980224b8834)

### Additional Context

Same behavior on multiple computers

### Operating System

Linux

### Operating System Version

Ubuntu 24.04

### Installation method

Snap

### Build Version

2024.5.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment] 2024-06-07 01:23
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/clients/issues/8651

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by sammbw** 2024-06-07 01:23 UTC
Labels: bug, desktop
