### ISSUE TITLE
Unable to shutdown Mac OS 14.4.1 without Bitwarden force quit.

### ISSUE THREAD

**Issue by S3767** [bitwarden/clients#8726] opened 2024-04-12 19:15 UTC
### Steps To Reproduce

4. Click on '...'
Click on Apple symbol on Mac top left.
Click on shutdown or restart.
Mac does not shut down.
Click on Apple Symbol or Command-Option-Escape.
Click on Bitwarden 
Then click on force quit to close Bitwarden
Mac shuts down or restarts as needed.

### Expected Result

For the Mac OS 14.4.1 to shutdown when it is instructed to shut down.

### Actual Result

Mac does not shut down until force quit for Bitwarden is completed.

### Operating System

macOS

### Operating System Version

Sonoma 14.4.1

### Installation method

Mac App Store

### Build Version

24.3.0 (21897)

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TroyBW** [comment] 2024-04-12 19:38
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: [https://github.com/bitwarden/clients/issues/8292](https://github.com/bitwarden/clients/issues/8292). 

Additionally, it seems that the most recent update to the Bitwarden desktop application may have resolved the issue. Please update the desktop app to version 2024.3.2 and see if that resolves the issue.

This issue will now be closed.

Thanks!

**Closed by TroyBW** 2024-04-12 19:38 UTC
Labels: bug, desktop

**Comment by S3767** [comment] 2024-04-12 20:11
The Apple Mac store was unable to update the application or prompt me to update it until I force quit it, removed the app through the settings and downloaded it again. Thank you.

Respectfully,

Patrick B. McBride

***@***.***
713-517-2737

On Apr 12, 2024, at 14:39, Troy ***@***.***> wrote:

﻿

Hi there!

Thank you for your report, it seems like it is a duplicate of this one: #8292<https://github.com/bitwarden/clients/issues/8292>.

Additionally, it seems that the most recent update to the Bitwarden desktop application may have resolved the issue. Please update the desktop app to version 2024.3.2 and see if that resolves the issue.

This issue will now be closed.

Thanks!
