### ISSUE TITLE
Brave macos: need to unlock destop app to unlock nav extension

### ISSUE THREAD

**Issue by Ant1-21** [bitwarden/clients#9832] opened 2024-06-25 19:39 UTC
### Steps To Reproduce

1. Bitwarden desktop app configured to *Start automatically on login* and *Start to menu bar*
2. Open Brave
3. Click on extension icon to unlock it 

### Expected Result

It should ask password, pin code or fingerprint to unlock the app

### Actual Result

Display the following message:

*User locked or logged out
Please unlock this user in the desktop application and try again.*

### Screenshots or Videos

![Capture d’écran 2024-06-25 à 21 18 55](https://github.com/bitwarden/clients/assets/96075449/f3440e40-f7f5-4a6c-861d-b4f7218fc79c)

### Operating System

macOS

### Operating System Version

Macos Somona 14.5

### Web Browser

Brave

### Browser Version

1.67.123

### Build Version

2024.6.1

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Pear-Tea** [comment] 2024-06-26 08:57
Same in Firefox on Windows

**Comment by djsmith85** [comment] 2024-06-26 10:18
Duplicate of https://github.com/bitwarden/clients/issues/9539

**Comment by djsmith85** [comment] 2024-06-26 10:18
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/9539.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2024-06-26 10:18 UTC
Labels: bug, browser
