### ISSUE TITLE
windows hello desktop communication doesnt work

### ISSUE THREAD

**Issue by navigum** [bitwarden/clients#6258] opened 2023-09-11 15:13 UTC
### Steps To Reproduce

1. Go to 'Firefox' then bitwarden icon next to adress bar
2. Click on 'biometric unlock'
3. Add-on drop-down will close and
4. desktop-app-Fingerprint-prompt appears in foreground, unlocking in windows hello is successful but is not send to Add-on!

### Expected Result

Unlocking the tresor after biometric check by windoes hello via bitwarden desktop-app.

### Actual Result

windows hello allows fingerprint but bitwarden-browser-add-on doesnt unlock. This happens only in firefox 117.0 (64-Bit). In chrome add-on works as expected.

### Operating System

Windows

### Operating System Version

w11 22h2 22621.2215

### Web Browser

Firefox

### Browser Version

117.0 (64-Bit)

### Build Version

2023.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment] 2023-09-11 19:13
Hi there!

Thank you for your report, it seems like it is a duplicate of this one [https://github.com/bitwarden/clients/issues/6169]. 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by Neonwarden** 2023-09-11 19:13 UTC
Labels: bug, browser
