### ISSUE TITLE
FireFox constant log out.

### ISSUE THREAD

**Issue by RealTrueDeviL** [bitwarden/clients#9915] opened 2024-07-02 18:00 UTC
### Steps To Reproduce

No idea, I just use the app, and it does not work correctly.

### Expected Result

I expected for it to remember the pin & settings I choose.

### Actual Result

The browser extension does not remember any setting, I set a pin, it forgets it, and it constantly logs me out, and I have to log in with the master password.

It started doing this a month or so ago, before that it worked flawlessly, I've got to the point it's not worth having it installed, as it's faster for my to use a pin to access the desktop app, and just copy/paste the details.

### Operating System

Windows

### Operating System Version

11

### Web Browser

Firefox

### Browser Version

Latest one 127.0.2

### Build Version

2024.6.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-07-02 21:26
@RealTrueDeviL Thank you for your report.
This seems like a duplicate of https://github.com/bitwarden/clients/issues/8873#issuecomment-2185418723, but should be resolved with `2024.6.3`.

Is this still occurring after installing 2024.6.3?

**Comment by RealTrueDeviL** [comment] 2024-07-03 10:03
I will double check, but I only logged in a couple days ago, and I'm already logged out completely, I'll log in now, and see what happens.

**Comment by RealTrueDeviL** [comment] 2024-07-03 10:31
Ok, so I set a pin, restarted the browser, it worked this time, I then restarted the PC, and tried, and it's asking for the pin.

So I guess something got fixed, and right at this time, it's fine.

But even after the 27th update, it still didn't work correctly a few times.. So I dunno what happend, or how it seemed to fix itself this time.

As the post above says, maybe it's just inconsistant, and it'll work 50% of the time, only time will tell. I'll keep an eye on it, and see if it breaks again.

**Comment by jtodddd** [comment] 2024-07-03 13:13
Hi there!

Thank you for your report, since this seems like it is a duplicate of this one: https://github.com/bitwarden/clients/issues/8873#issuecomment-2185418723 , I'm going to close this issue here. 

If this does continue happening, please comment on the original post and feel free to submit a ticket to bring our attention to it further since this should have been resolved with the latest update: https://bitwarden.com/help/

This issue will now be closed.

Thanks!

**Closed by jtodddd** 2024-07-03 13:13 UTC
Labels: bug, browser
