### ISSUE TITLE
Traffic from your network looks unusual. Connect to a different network and try again later [Error code 7]

### ISSUE THREAD

**Issue by luis-fnogueira** [bitwarden/clients#5276] opened 2023-04-24 20:56 UTC
### Steps To Reproduce

1. Go to My Vault
2. Click on Add Item, then try save something
3. Scroll down to Save
4. Click on Save

### Expected Result

Save something, a credential

### Actual Result

Traffic from your network looks unusual. Connect to a different network and try again later [Error code 7]

### Screenshots or Videos

![Screenshot 2023-04-24 174447](https://user-images.githubusercontent.com/82065199/234114539-700bd9b1-bece-4544-805c-220680f53b3e.png)

### Additional Context

I tried to log in on Bitwarden by browser also, but I had the same error before logging in. When I type the password and hit enter it raises the exact same error. My network is the same that I've used for years. It's my home's network.

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.3.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by gkrawiec** [comment] 2023-04-28 10:39
me too, started this week

**Comment by StalinMazaEpn** [comment] 2023-04-28 20:40
me too, this week i cannot update my vault, it´s always reproduces the same error message

**Comment by djwinston** [comment] 2023-04-29 20:31
I provided information for support related this bitwarden [manual](https://bitwarden.com/help/unusual-traffic-error/) - Unusual Traffic Error
Support answer:
> This can happen if you are connecting using a VPNs, Proxies, Tor, and shared networks (shared IPs) as they are commonly used to send malicious traffic towards our cloud infrastructure because they mask the true origin of the traffic. When using such services/networks, you are essentially communicating with our cloud infrastructure from an IP address that is used to many other people as well, and when that IP address is flagged by our security mechanisms by what most likely are the actions of other people on that network, you'd also be prevented from communicating with our cloud infrastructure even though your actions are legitimate. 

After bitwarden  support response app error was resolved. I guess it was resolved by support manually 🧑‍💻

**Comment by Tipoff4317** [comment] 2023-04-29 20:53
@gkrawiec

> but also, there is a UI bug. When I try to edit or manually add site I get the error, but when I press save to the pop up that automatically shows up when bitwarden detects new credentials or an update to old ones, bitwarden accepts the change without error, but in reality the credentials where not saved. So the UI bug is it should show the error to let people know the password is NOT on bitwarde yet

It seems like you should file another bug report for this issue, because this "Traffic from your network looks unusual" error may not be viewed by BW as a bug, or even if viewed partially as a bug (because some settings make it more prone to happen), this issue may be off in another code path altogether that it won't get fixed (check and alert on error condition) when the settings are fixed.

**Comment by SergeantConfused** [comment] 2023-05-01 14:18
Hello everyone,

Thank you all for your input. This report appears to be describing the intended behaviour of the software; You can learn more about this here (https://bitwarden.com/help/unusual-traffic-error/) and you're more than welcome to follow the steps outlined in the guide to troubleshoot this.

With regard to comment made by @gkrawiec; That is correct and we're working on making adjustments from our end to address this.

We use GitHub issues as a place to track bugs and other development related issues; This thread will now be closed.


Thank you again,

**Closed by SergeantConfused** 2023-05-01 14:18 UTC
Labels: bug, desktop
