### ISSUE TITLE
New window constantly opening when using autofill on page load and master password re-prompt

### ISSUE THREAD

**Issue by muriloAJacon** [bitwarden/clients#6416] opened 2023-09-27 01:00 UTC
### Steps To Reproduce

1. Have "autofill on page load" enabled
2. Have a password for a website that requires re-prompt of the master password
3. Go to said website

### Expected Result

No new window opens and to autofill the password you have to click the extension and select the specified password and only then enter the master password. This was the behavior of versions before 2023.9.

### Actual Result

A new window opens prompting for the master password, this happens regardless of whether there is a form to be filled on the page or not.
Navigating around the website will make new windows appear despite having closed the first one.
Sometimes, several new windows open at the same time (I've found this to be the case in the AWS console).

### Operating System

Windows

### Operating System Version

Windows 11 22H2

### Web Browser

Microsoft Edge

### Browser Version

117.0.2045.41

### Build Version

2023.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment] 2023-09-27 12:11
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by Korvenwin** [comment] 2023-09-29 08:03
I'm having this issue too in Safari and in Edge for Windows and macOS.

**Comment by chraebsli** [comment] 2023-09-29 08:12
Please refer to [this comment](https://github.com/bitwarden/clients/issues/6389#issuecomment-1739836296).

**Comment by djsmith85** [comment] 2023-09-29 12:43
Duplicate of https://github.com/bitwarden/clients/issues/6389

**Closed by djsmith85** 2023-09-29 12:43 UTC
Labels: bug, browser
