### ISSUE TITLE
Autofill menu always displayed on Firefox even if the Autofill menu is set to OFF in the addon.

### ISSUE THREAD

**Issue by iGormilhit** [bitwarden/clients#11357] opened 2024-10-02 08:32 UTC
### Steps To Reproduce

1. Install the Firefox bitwarden addon.
2. Set the *Show autofill menu on form Fields* to OFF. 
3. Go to a page with a login form.
4. See that the form entries has bitwarden autofill menu.

### Expected Result

The autofill menu shouldn't be displayed in the login form input when the setting is set to OFF.

### Actual Result

The autofill menu are displayed in the form input.

### Screenshots or Videos

The setting:
![ksnip_20241002-102156](https://github.com/user-attachments/assets/4fbe0baf-8c53-49a1-8bc4-37da6c5ff0e6)

The result:
![ksnip_20241002-102105](https://github.com/user-attachments/assets/6cc3feed-1d25-4cb7-8181-9ec4986a2097)

### Operating System

Linux

### Operating System Version

Linux 6.11.1-arch1-1

### Web Browser

Firefox

### Browser Version

131

### Build Version

2024.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by rmcdowell-bitwarden** [comment] 2024-10-03 07:43
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/clients/issues/11173

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed** 2024-10-03 07:55 UTC
Labels: bug, browser
