### ISSUE TITLE
Unlock with Biometrics Stopped Working (Mac Touch ID, Chrome)

### ISSUE THREAD

**Issue by sonicseamus** [bitwarden/clients#11457] opened 2024-10-08 16:09 UTC
### Steps To Reproduce

1. Use command-shift-L keyboard shortcut or click on browser extension to get Bitwarden to autofill (when locked)

### Expected Result

1. Bitwarden automatically launches the system TouchID prompt
2. I TouchID with my fingerprint
3. Bitwarden autofills my username and password

### Actual Result

The Bitwarden popup launches, but it does not launch the TouchID prompt. Even if I click "unlock with biometrics," nothing happens. I am forced to enter my master password if I want to access my vault.

### Screenshots or Videos

<img width="1499" alt="Screenshot 2024-10-08 at 12 01 21 PM" src="https://github.com/user-attachments/assets/acdb2910-c94e-4daa-8d9a-6175dc008669">

### Additional Context

Bitwarden has worked the way I described above (keyboard shortcut->press fingerprint->autofilled) for me for years, until this week, when it mysteriously stopped. I restarted my computer to see if that would fix it but it didn't. TouchID unlock still works fine for the desktop app—just not the Chrome extension.

I also tried "In your Browser, navigate to the extensions manager (e.g. chrome://extensions or brave://extensions), open Bitwarden, and toggle the Allow access to file URLs option" (suggested in the Bitwarden [help article](https://bitwarden.com/help/biometrics/#tab-browser-extension-2vCWb5iFg4OqKS0B2xXpqW)) and also tried disabling and re-enabling biometric unlock in the browser extension. It did successfully prompt for my fingerprint when I re-enabled but the same issue persists when unlocking the vault.

### Operating System

macOS

### Operating System Version

14.6.1

### Web Browser

Chrome

### Browser Version

129.0.6668.90 (Official Build) (arm64) 

### Build Version

 2024.10.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by przemoch-dev** [comment] 2024-10-09 05:24
Same problem here. I noticed it when update to 15.0 Sequoia.

Chrome version is 129.0.6668.90 (same problem after updating to 129.0.6668.101)

**Comment by MerkulovDaniil** [comment] 2024-10-09 08:25
I have exactly the same issue in Safari on MacOs after system upgrade.

Bitwarden
Version: 2024.9.1

Server version: 2024.9.2

Macos Sequoia 15.0.1

**Comment by jtodddd** [comment] 2024-10-09 12:47
Hi there!

Thank you for your report, it seems like it may be a duplicate of this still open one https://github.com/bitwarden/clients/issues/11168 . Let me know if I'm mistaken and this one is different!

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will be closed for now.

Thanks!

**Closed by jtodddd** 2024-10-09 12:47 UTC
Labels: bug, browser
