### ISSUE TITLE
Too many clicks to unlock when using biometrics on mac

### ISSUE THREAD

**Issue by mwisnicki** [bitwarden/clients#9210] opened 2024-05-16 15:22 UTC
### Steps To Reproduce

1. Lock vault
2. Go to website asking for password and click on password input field
3. Click `Unlock account` in dropdown of password input
4. Click `Unlock with biometrics` in bitwarden popup
5. Use touch ID / windows hello

### Expected Result

Step 4 should be unnecessary.
If unlock with biometrics is enabled jump straight to it. Or make it a preference.

In fact maybe even make step 3 optional (with preference).

### Actual Result

Unnecessary click and mouse movement :D

### Additional Context

It's a bit annoying that I can't copy bitwarden version from about dialog to paste it into this report.

Only tested on Mac but I'm guessing Windows Hello is the same.

### Operating System

Windows, macOS

### Web Browser

Chrome

### Build Version

2024.4.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-05-16 19:12
Duplicate of https://github.com/bitwarden/clients/issues/8332

**Comment by djsmith85** [comment] 2024-05-16 19:13
Hi @mwisnicki 

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/8332

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2024-05-16 19:13 UTC
Labels: bug, browser
