### ISSUE TITLE
Syncing fails

### ISSUE THREAD

**Issue by nikossarris** [bitwarden/clients#7689] opened 2024-01-25 22:35 UTC
### Steps To Reproduce

1. Go to File/sync vault

### Expected Result

should complete sync

### Actual Result

I continuously get the message 'syncing failed' although from the chrome extention I perform the sync and it gives me the message that syncing completes, although in reality it doesnt as I check an itme I have changed on the chrome extention and on the desktop client the password is outdated

### Operating System

macOS

### Operating System Version

14.2.1 (23C71)

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2023.12.1 Shell 25.9.1 Renderer 114.0.5735.289 Node 18.15.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-01-26 11:39
Duplicate of https://github.com/bitwarden/clients/issues/7243

**Comment by djsmith85** [comment] 2024-01-26 11:39
Hi @nikossarris,

Thank you for your report. This report seems like it is a duplicate of https://github.com/bitwarden/clients/issues/7243

The issue was addressed and the changes are included in the most recent version. Please update all your clients.

This report will now be closed.

Thank you again

**Closed by djsmith85** 2024-01-26 11:39 UTC
Labels: bug, desktop
