### ISSUE TITLE
Problems with Bitwarden on Firefox

### ISSUE THREAD

**Issue by DKCal** [bitwarden/clients#12595] opened 2024-12-26 21:46 UTC
### Steps To Reproduce

4. Click on '...'
1) When a pop-up window is activated, it is so large it overfills the screen and cannot be reduced. Can't find an X or way to exit the pop-up screen and get back to main screen. 
2) When Card view is selected on main screen, it is not saved, so next time I use Bitwarden, have to re-select Card view.
3) Can't move screen location or reduce size.
.

### Expected Result

I expect to be able to get out of the pop-out window. Expect to be able to move Bitwarden screen and reduce size of screen. Expect setting of Cards on main screen to stick, so it doesn't have to be re-selected each time I use BW.

### Actual Result

Described above

### Screenshots or Videos

Tried to attach screenshot, the title showed, but the screenshot was not attached,

### Operating System

Windows

### Operating System Version

Windows 10

### Web Browser

Firefox

### Browser Version

133.0.3

### Build Version

2024.12.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment] 2024-12-27 14:58
duplicate of #12598

**Comment by NovaSilentium** [comment] 2024-12-27 14:59
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/12598

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed** 2024-12-27 15:00 UTC
Labels: bug, browser
