### ISSUE TITLE
Continues to update latest version even though latest version is installed

### ISSUE THREAD

**Issue by cyberjack88** [bitwarden/clients#3125] opened 2022-07-17 15:21 UTC
### Steps To Reproduce

reboot windows 7 pro 32 bit

### Expected Result

Should be updated only when a new version is available.

### Actual Result

Every time I reboot windows 7 i am prompted to update Bitwarden which I do and it does and I check to see that latest version (22.6.2) is installed which it is and then the next time I reboot windows it asks me again, rinse and repeat.  

### Operating System

Windows

### Operating System Version

windows 7 32 bit

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.6.2

**Comment by MartinX3** [comment] 2022-07-18 12:57
The check for updates function redirects to the wrong repository.
(The old, archived desktop one)

**Comment by svtmontagna** [comment] 2022-07-19 08:05
I have the same problem only on windows machine. Always ask me to update to latest version but it doesn't and I still have 2022.5.0 version.

**Comment by djsmith85** [comment] 2022-07-28 14:35
@cyberjack88 and @svtmontagna Thank you for your reports.
Closing this as duplicate of https://github.com/bitwarden/clients/issues/2571

@MartinX3 I saw your comment and the missing updates also got released onto the old repo.

**Closed by djsmith85** 2022-07-28 14:35 UTC
Labels: bug, desktop
