### ISSUE TITLE
Syncing Failed on MacOS Sonoma 14.2.1

### ISSUE THREAD

**Issue by yorksa10** [bitwarden/clients#7489] opened 2024-01-09 16:58 UTC
### Steps To Reproduce

4. Click on '...'

Open BitWarden Desktop App
Go to 'File' and choose 'Sync Vault'
Wait a bit and eventually it will come up with "Syncing Failed"

### Expected Result

It should come up with Sync Complete

### Actual Result

It comes up with Syncing Failed.

### Additional Context

I've tried removing and reinstalled BitWarden, and it doesn't solve the problem.

### Operating System

macOS

### Operating System Version

macOS Sonoma 14.2.1

### Installation method

Mac App Store

### Build Version

Version 2023.12.1 (16254)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment] 2024-01-09 17:32
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/7270. 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

If you're seeing a "sync failed" error, please fully log out and log back into the client you're seeing this occur on. Once you've logged back in, you should be able to sync your vault successfully.

This issue will now be closed.

Thanks!

**Closed by Neonwarden** 2024-01-09 17:32 UTC
Labels: bug, desktop
