### ISSUE TITLE
Safari - The browser extension does not list folders when offering to save new or last-used credentials on the fly.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/clients#3694] opened 2022-10-05 12:47 UTC
### Steps To Reproduce

1. Unlock your Safari Bitwarden browser extension.
2. Navigate to Vimeo.
3. Attempt to log in using dummy credentials.
4. Attempt to select a folder to save the new vault item to from the "Should Bitwarden remember this password for you?" bar.

### Expected Result

To be able to list and select a folder.

### Actual Result

Clicking on the drop-down menu does nothing.

### Screenshots or Videos

Internal.

### Operating System

macOS

### Operating System Version

12.6.

### Web Browser

Safari

### Browser Version

16.0.

### Build Version

2022.8.0.

**Comment by Martijn8** [comment] 2023-09-04 15:48
Can someone please sort out the cause of this problem?

**Comment by cagonzalezcs** [comment] 2024-02-21 18:50
A resolution for this has been merged into `main` and will be present in the upcoming release of the extension.

https://github.com/bitwarden/clients/pull/7729

Closing this Github issue for now, if the issue persists past the release of extension `v2024.3.0`, then we can re-address any potentially missed issues.

**Closed by cagonzalezcs** 2024-02-21 18:50 UTC
Labels: bug, browser
