### ISSUE TITLE
Password will not paste on google login screen

### ISSUE THREAD

**Issue by rbhall52** [bitwarden/clients#8269] opened 2024-03-09 04:58 UTC
### Steps To Reproduce

1. Go to google.com
2. Click on login
3. If email is already entered, click "Next"
4. Password has to be copied from bitwarden vault and then pasted into password blank field on form. 

### Expected Result

I expected bitwarden to be able to paste the password into the password field on the form.

### Actual Result

When asking bitwarden to paste the password into the password field on the form, the error message appears which says that bitwarden is unable to paste the password into the password field on the form, and that the password has to be copied from the bitwarden vault and pasted manually into the password field on the form.

### Operating System

Windows

### Operating System Version

Windows 11 home

### Web Browser

Firefox

### Browser Version

123.0.1 64-bit

### Build Version

2024.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment] 2024-03-11 09:50
Hello there,

Are you using the shortcut of CTRL/CMD + Shift + L to autofill?

**Comment by 0oWow** [comment] 2024-03-12 14:02
I'm finding this same problem with several websites I use, including Google.  It's as-if BW doesn't acknowledge that the fields are fillable, since even the hotkeys don't work.  But if you refresh the Google Password page (after the Username page), BW will then autofill.

I just started looking into this, but I think it's similar to this bug:  

https://github.com/bitwarden/clients/issues/8063

**Comment by cagonzalezcs** [comment] 2024-03-13 17:22
@0oWow 

That issue doesn't seem likely to be the reason for this bug. Rather, this bug is likely due to some improvements we previously introduced for validating search input fields. 

A fix for that has been implemented and is currently in review - https://github.com/bitwarden/clients/pull/8117

I'm closing this thread for now, as a fix for the issue is currently in review. Please feel free to continue discussion as necessary.

**Closed by cagonzalezcs** 2024-03-13 17:22 UTC
Labels: bug, browser
