### ISSUE TITLE
Auto-Update not working when installed over App Store

### ISSUE THREAD

**Issue by PhilTb7** [bitwarden/clients#9249] opened 2024-05-19 09:57 UTC
### Steps To Reproduce

1. Wait for macos to show the popup that the app can be updated and therefore needs to be closed first
2. Click on 'continue'
3. nothing happens

### Expected Result

after clicking continue, the app should be quit automatically and be updated by app store.

### Actual Result

app does not quit and is also not updated.

### Additional Context

Also the launchpad shows that Bitwarden has been downloaded and is waiting to be installed, but that's it.

I guess it could have something to do with the fact that the Bitwarden client is just minimizing to the system bar if you quit the app. Probably the app store tries the same, but due to the app still running, it can't install the new version.

My workaround was to quit the app via activity monitor with force quit and then install the new version via the update button in the app store.

### Operating System

macOS

### Operating System Version

Sonoma 14.4.1

### Installation method

Mac App Store

### Build Version

2024.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by PhilTb7** [comment] 2024-05-19 10:03
The new version 2024.4.1 which I installed manually seems to quit now when you quit via cmd+q or the menu. So maybe this issue is already resolved implicitly by the new version.

**Comment by SergeantConfused** [comment] 2024-05-19 11:30
Hi @PhilTb7,

Thank you for this report. It sounds like you encountered [this behaviour](https://github.com/bitwarden/clients/issues/8292) in the prior version whilst attempting to upgrade; Going by this, and by the fact that you're now unable to reproduce this in version 2024.4.1, I will proceed and close this GitHub report.

If you wish, please feel free to get in touch with us using the form in the [Bitwarden Help Centre](https://bitwarden.com/help/); Please include a link to this GitHub report in the body of your message, if you do so.

Thank you again,

**Closed by SergeantConfused** 2024-05-19 11:30 UTC
Labels: bug, desktop
