### ISSUE TITLE
Chrome plugin biometrics not working

### ISSUE THREAD

**Issue by TTECGH** [bitwarden/clients#11487] opened 2024-10-10 14:47 UTC
### Steps To Reproduce

1. Open Chrome
2. Click the Bitwarden plug-in logo at the top
3. In the menu select unlock with Biometrics
4. Error message appears saying biometrics is unavailable

### Expected Result

1. Open Chrome
2. Click the Bitwarden plug-in logo at the top
3. In the menu select unlock with Biometrics
4. A Windows window pops up asking for my fingerprint
5. I place my finger on the fingerprint reader
6. The window disappears and Bitwarden opens in the Chrome browser

### Actual Result

Error message appears saying biometrics is unavailable

### Operating System

Windows

### Operating System Version

Windows 10 22H2

### Web Browser

Chrome

### Browser Version

Version 129.0.6668.90 (Official Build) (64-bit)

### Build Version

2024.10.0

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment] 2024-10-10 15:20
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/11168. 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by Neonwarden** 2024-10-10 15:20 UTC
Labels: bug, browser
