### ISSUE TITLE
Password not updating

### ISSUE THREAD

**Issue by compruteru** [bitwarden/clients#12153] opened 2024-11-25 20:22 UTC
### Steps To Reproduce

1. Go to '...' an item
2. Click on '....', modify the password field
3. Scroll down to '....' save the changed password
4. Click on '...' View or Copy the password, you can see it is still showing the old password. 

### Expected Result

expected the password to update the viewport as well as the entry within the item.

### Actual Result

passwords appears to update the item, but does not populate the password field with the latest change.

### Screenshots or Videos

Windows 10, latest patched, bitwarden desktop, latest patched. 

### Additional Context

not sure.

### Operating System

Windows

### Operating System Version

Microsoft Windows 10 Home

### Installation method

Direct Download (from bitwarden.com)

### Build Version

10.0.19045 N/A Build 19045

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by nfnfgo** [comment] 2024-11-26 03:12
Also faced the same issue.

System: **Window11**
Version: **2024.11.2**

<details><summary>Version Detail Screenshot</summary>
<p>

![Detailed Version Info Screenshot](https://github.com/user-attachments/assets/7b1f0e32-af02-42b2-90ba-b5a3082bc41e)

</p>
</details>

More specifically, after updating a password:

- Update operation actually success, and the **changes could be seen immediately on other clients** (E.g.: Web vault)
- Desktop UI not refresh. **Both list item name and detailed info page**.
- Partially refreshed after switch list item. That is, switch to any other different list item then switch back. In this case **detailed info page is now updated with the newest change**, however the **name of list item is still not updated** unless user sync vault manually.

**Comment by cbw23** [comment] 2024-11-26 23:08
Hi there!

Thank you for your report, it seems like it is a duplicate of this one #12022 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by cbw23** 2024-11-26 23:08 UTC
Labels: bug, desktop
