### ISSUE TITLE
Safari browser extension memory leak

### ISSUE THREAD

**Issue by ven** [bitwarden/clients#5388] opened 2023-05-07 06:37 UTC
### Steps To Reproduce

1. Kill the `Bitwarden Safari Web Extension` process completely and restart it.
2. Open Activity Monitor and navigate to the memory tab. Search for `Bitwarden Safari Web Extension`. Observe expected/normal memory usage (<500MB).
3. Open the Bitwarden extension 20 times by clicking the blue icon on the Safari address bar.
4. Observe that memory usage increases by 500~ MB.
5. Repeat steps 3-4, observing that memory usage keeps increasing: 1GB, 2GB, 3GB, until it uses up all of the system memory.

### Expected Result

The extension should remain <500MB memory usage. 

### Actual Result

The extension's memory usage grows every single time you click the extension.

### Screenshots or Videos

<img width="138" alt="2023-05-07 at 07 33 51@2x" src="https://user-images.githubusercontent.com/46830208/236661850-4eeb40ed-85a2-4d3e-b659-30aeac239619.png">

Each time you click this icon, the memory usage of the Bitwarden extension increases permanently until the process is killed or the computer is restarted.

### Additional Context

Seems like once the extension window closes, the window isn't being killed correctly? See issue #1770 and #4744 for the same issues. This demonstration explains why all users experienced the problems after around a week - when they had opened the extension multiple times a day for a few days.

### Operating System

macOS

### Operating System Version

Ventura 13.3.1 (a)

### Installation method

Direct Download (from bitwarden.com), Other

### Build Version

Version: 2023.3.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment] 2023-05-08 08:53
Hi @ven,

Thank you for your report, it seems like it is a duplicate of (https://github.com/bitwarden/clients/issues/1770).

If you wish to add any further information such as logs or screenshots, or to check on the status of this, please feel free to do so in the existing thread and we'll do our best to follow up with you there.

This issue will now be closed.

I thank you in advance for your understanding.

**Closed by SergeantConfused** 2023-05-08 08:53 UTC
Labels: bug, desktop
