### ISSUE TITLE
Windows desktop app shows items in their assigned folder as well as 'No Folder'

### ISSUE THREAD

**Issue by sawft99** [bitwarden/clients#2962] opened 2022-06-23 13:58 UTC
### Steps To Reproduce

1. Open Windows desktop app and go to the 'No Folder' folder section
2. Notice items, in my case all of them, are in that folder
3. Also check your own created folders
4. See that items that are assigned to a folder will show up in 'No Folder' as well as their assigned folder

### Expected Result

Items should only show in their assigned folder.

### Actual Result

Items show up in their assigned folder as well as the 'No Folder' section.

### Screenshots or Videos

- Note 'Act~' folders ID from exported json file
- Note 'adv~' login is assigned to the same folder ID as 'Act~'
- Note the login entry shows in both 'No Folder' and 'Act~' folder

![Folders](https://user-images.githubusercontent.com/81699231/175314023-ab25bddf-ede3-4374-93e3-8efe75a24a8d.jpg)

![Config](https://user-images.githubusercontent.com/81699231/175314149-8fbb6dd1-643d-44a0-b703-210c9088482d.jpg)

![App](https://user-images.githubusercontent.com/81699231/175314190-808eed03-e957-4ac9-bac7-f011d9ac390c.jpg)

![App2](https://user-images.githubusercontent.com/81699231/175314204-4f92f60e-f7ae-4c25-81f4-d89c632587b3.jpg)

### Additional Context

Attempts to fix:

1. Changing entry to a different folder and then back to its original folder
2. Setting it to 'No folder' and then setting back to its original folder
3. Resyncing
4. Fully logging out of app and then back in
5. Rebooting

### Operating System

Windows

### Operating System Version

11 [Version 10.0.22000.739]

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.5.1

**Comment by djsmith85** [comment] 2022-06-23 21:02
Hi @sawft99 thank you for report. Is this possibly a duplicate of https://github.com/bitwarden/clients/issues/2821? This has already been fixed and will be released soon.

**Comment by sawft99** [comment] 2022-06-23 21:07
> Hi @sawft99 thank you for report. Is this possibly a duplicate of #2821? This has already been fixed and will be released soon.

Yes. Guess I should have also looked through the closed issues before submitting. Since it was still ongoing I didn't think to look there. Feel free to close, merge, etc.

**Closed** 2022-06-23 22:13 UTC
Labels: bug, desktop
