### ISSUE TITLE
The Web Vault is displaying organizations from the Provider Portal in the Vaults view.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/clients#4804] opened 2023-02-20 11:19 UTC
### Steps To Reproduce

1. Log into your Bitwarden account via the Web Vault (https://vault.bitwarden.com/#/).
2. Look at the (FILTERS) pane on the left.

### Expected Result

To see only the organizations that your Bitwarden account is a member of.

### Actual Result

You see the organizations that your Bitwarden account is a member of, and the organizations that are part of your Provider Portal.

### Screenshots or Videos

Internal.

### Additional Context

N/A.

### Operating System

Windows

### Operating System Version

Windows 11 Pro 22H2.

### Web Browser

Firefox

### Browser Version

110.0.

### Build Version

2023.2.0.

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment] 2024-07-26 11:52
As the issue is no longer reproducible, I will proceed to close it.

Thanks!

**Closed by Greenderella** 2024-07-26 11:52 UTC
Labels: bug, web
