### ISSUE TITLE
Timout action defaults to Lock, and overrides previously set vault preferences

### ISSUE THREAD

**Issue by qfyra** [bitwarden/clients#4812] opened 2023-02-21 12:05 UTC
### Steps To Reproduce

I already basically reported this here https://github.com/bitwarden/clients/issues/2100

But you didn't believe me for some reason, and obviously you did not look into it either, which, in turn, makes your product insecure and inferior. 

I installed the plugin on a new computer and a brand new Firefox installation. Logged in into my vault so that I could log in to some standard websites I'm usually logged in to. Shut down computer, come back the next day, notice that the vault is now locked rather than logged out, meaning no 2 factor auth prompt. Turns out the setting defaults to "Lock", rather than respecting the account settings. And what's worse, the account settings are now OVERWRITTEN to the values that your shitty plugin defaults to. When I log in via vault.bitwarden.com, the vault timeout is set to 15 minutes rather than the 4 hours which is what I had before, and the timeout action is set to Lock rather than the Log out setting I had before. 

How about fixing this for once? 

### Expected Result

RESPECT VAULT PREFERENCES KTHXBYE

### Actual Result

YOU CAN NO HAS RESPECT VAULT PREFERENCES 

### Operating System

Windows

### Operating System Version

10

### Web Browser

Firefox

### Browser Version

110.0 64 bit

### Build Version

2023.1.0 

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment] 2023-02-21 13:05
Hello there,

Looking at the previous Github issue, have you ever contacted our Support for further troubleshooting? Could you please check and see if this issue is the same on a different browser, e.g. Vivaldi, Chrome, Opera etc.?  If so, I would suspect a conflict between your Bitwarden extension, and some of the other extensions that you have configured.  
​
It would be worth refreshing your Firefox profile (https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings) and starting again with only Bitwarden enabled.  If you have success with this configuration, you can re-enable your other addons one-by-one, testing each time. 

This should enable you to work out what is causing the issue, and then take appropriate action.

**Comment by qfyra** [comment] 2023-02-21 14:32
> Looking at the previous Github issue, have you ever contacted our Support for further troubleshooting? 

No. This is obviously a bug in your Firefox browser plugin. It was obvious back then, and it's even more obvious now since it's now easily reproducible. 

- New computer (implying new Windows installation)
- New Firefox install (implying latest version of plugin)
- Existing vault with non-default timeout and lock settings (implyingthe vault was set up using another computer)
- Shut down new computer
- Start it again when the default timeout have elapsed 
- Vault is now locked, not logged out
- Check web vault, now has default settings rather than custom
 
Easy peasy lemon squeezy. You probably don't even need to shutdown and start the computer to be honest. You probably don't even need a new computer. You probably just have to install Firefox on a separate computer that never had it before 

> Could you please check and see if this issue is the same on a different browser, e.g. Vivaldi, Chrome, Opera etc.? 

No. It's not my job to do this. I'm reporting an obvious bug in your browser plugin. If you're not willing to receive bug reports, you should consider closing the Github issue tracker. 

> It would be worth refreshing your Firefox profile (https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings) and starting again with only Bitwarden enabled.

No. I explicitly wrote the following: 

"I installed the plugin on a new computer and a brand new Firefox installation"

Operative keyword here is **new**. Refreshing my Firefox profile is definitely **not** worth trying in this particular case.

**Comment by Krychaz** [comment] 2023-02-21 15:16
I'm unable to reproduce this issue using a fresh install of Firefox. While this issue could potentially be related to some ongoing issues we are tracking. More reports are required. I will pass this issue to QA for further testing.

**Comment by joshtrichards** [comment] 2023-02-22 04:17
Disclaimer: I don't work for BW and these comments are drawn entirely from my own experiences as a user and modest dives into the code base.

In your most recent report (the one I'm replying within not the older one) something stood out to me:

> I installed the plugin on a new computer and a brand new Firefox installation. Logged in into my vault so that I could log in to some standard websites I'm usually logged in to. Shut down computer, come back the next day, notice that the vault is now locked rather than logged out, meaning no 2 factor auth prompt. Turns out the setting defaults to "Lock", rather than respecting the account settings. And what's worse, the account settings are now OVERWRITTEN to the values that your shitty plugin defaults to. When I log in via vault.bitwarden.com, the vault timeout is set to 15 minutes rather than the 4 hours which is what I had before, and the timeout action is set to Lock rather than the Log out setting I had before.

Is there a chance part of the confusion here may be arising because of the inadvertent idea of vault timeout parameters being "account settings" (i.e. server-side or server-side vault-stored)?

This behavior sounds like what I'd expect on a new installation because within BW there are no *account* settings (i.e. settings stored server-side or stored within the master copy of your vault stored server-side) related to vault timeouts and actions.

These parameters are pulled independently from a given client app's instance's locally defined settings (which may simply be the defaults codified in each client until defined otherwise by the user). The settings are stored only locally within each client app's own definition of local/session storage and do not get pushed around to all client app installations on a user's various computers/devices (or even on the same device). 

So in every client app *instance* the settings are stored locally to that instance. Even if you have the same browser client (extension) installed on two computers: each installation on each computer maintains its own timeout settings. 

And that includes the web client app that gets loaded when you visit https://vault.bitwarden.com - those vault timeout settings never leave that browser.

If you want proof, open up two different browsers (e.g. Firefox + MS Edge) and log into https://vault.bitwarden.com in each one simultaneously. Arbitrarily change the timeout setting (or even theme) in either/both.

The changes won't impact nor be visible to each other. 

That's because those settings are stored as cookies/local browser data accessible by the instance of the web client that starts up when you visit the URL, but they aren't pulled from the URL or server-side APIs.

Admittedly, if you log out then then back in within the same browser (even closing and reopening your browser in between) your settings may appear to be saved "in your account" because they will remain the same... _but they're only saved for logins within that specific browser_. 

You can easily prove this by deleting your site cookies for *.bitwarden.com and logging back in... Your timeout/custom settings will be reset when you next log-in.

**Comment by qfyra** [comment] 2023-02-22 12:10
> Is there a chance part of the confusion here may be arising because of the inadvertent idea of vault timeout parameters being "account settings" (i.e. server-side or server-side vault-stored)?

Sure, yes, it may very well be the case that the UI is completely fraudulent.

> This behavior sounds like what I'd expect on a new installation because within BW there are no account settings (i.e. settings stored server-side or stored within the master copy of your vault stored server-side) related to vault timeouts and actions.

If that's indeed the inner workings of Bitwarden then I understand why you would expect it, if you happen to have insight in how Bitwarden works. But there's nothing to suggest that this is the case in terms of the UI. The UI doesn't make this clear at all. In fact, most of the lingo in the UI suggests the opposite. 

Logging in to the web vault, there's a menu option saying Account Settings. 

<img width="179" alt="account-settings" src="https://user-images.githubusercontent.com/59998991/220611644-96a373e0-66c7-4901-a7b6-d7a44a6b0327.png">

And by "Account Settings", I assume Bitwarden means the following:

- "Account Settings"

As in "Settings" that applies to an "Account". Not "Settings" that apply only to "the current browser session until the cache is removed or whatever". 

And when you go to Account Settings > Preferences and set the timeout action to Log out, Bitwarden issues the following confirmation dialog: 

<img width="365" alt="timeout-action-warning" src="https://user-images.githubusercontent.com/59998991/220612482-98a44fed-2744-44fc-a2d7-943a7dc4591d.png">

And by "Logging out will remove all access to your vault and requires online authentication after the timeout period", I assume Bitwarden means the following:

-  "Logging out will remove all access to your vault and requires online authentication after the timeout period". 

When I click Yes, that's what I'm clicking Yes to. And given that I'm in the "Account Settings" section, I expect it to be account-wide. 

Regardless, the original bug remains a bug.  Doesn't matter if the account settings in the web vault and the plugin is browser-cache-session-wide only. And it's a critical bug at that, from an InfoSec perspective. If I configure a required 2fac for my vault, and set my vault account settings to "require online authentication after the timeout period" as per the dialog box above, then I expect this setting to stick across all browsers, all browser plugin versions, all web versions of the vault, and all desktop application versions of the softwart. Not sure why anybody would expect any different. And I certainly don't understand why it would be in any way acceptable to be able to circumvent the required 2fac just because you install a plugin on a new browser and didn't go into the settings and explicitly set it to the same preference that you've already set multiple times before. 

I mean, if Bitwarden wants to have a fraudulent UI and an inherently insecure product, fine, but then don't expect people to actually use it or pay for it. I certainly won't use it anymore, and I'll make sure everybody I know don't use it.

**Comment by qfyra** [comment] 2023-09-13 12:20
This happened again. This time in Chrome, so that answers that question, it definitely spans multiple browsers. 

I rarely use Chrome, but I had to yesterday because of some site being incompatible with Firefox. Bitwarden plugin was already installed in Chrome, and I've previously set the vault settings to my liking, but that was a while ago (most likely in February when I reported this bug). So I logged in yesterday, then closed the browser. Note that neither cache nor cookies have been cleared from this browser, because in my browser history I can still see stuff I accessed months ago. Today I had to use Chrome again, and I find, yet a gain, that the Bitwarden plugin doesn't respect my settings, and reverts to the insecure default setting that circumvents 2fac. 

So if it is indeed the case that these settings are just stored locally in cache/cookies/browserstorage/whatever, then I guess it's pretty obvious what's happening: **you're for some reason saving these settings with an expiry date.**

**Comment by qfyra** [comment] 2023-11-02 09:38
This happened again on my primary browser on my primary work computer, Firefox (119.0 64-bit, Windows 10). I've got two BitWarden accounts, one for work, one for private. Both of these are set to log out on browser restart rather than lock. 

Two days ago I was logged in to the work account, and had to switch to my private account. I took extra care to select to log out rather than lock. I logged in to my private account, then at some later point I closed the browser. Yesterday, I log in to my work account again, and at a later point I closed the browser and left the computer on overnight. Today, I open my browser, and find Bitwarden being locked rather than logged out. At this point, I only had to use my work account password to gain access, which again **completely cirumvents the second factor in the two factor authentication**. When I log in and check my vault timeout action, the settings have reverted to "Lock" rather than "Log out". For the past two years, I have **NEVER** actively selected "Lock" for this setting, on any of my accounts. It's always been set to "Log out". Ergo, under certain circumstances, the **PLUGIN** is overwriting these settings and making the product inherently insecure.

**Comment by micahblut** [comment] 2024-06-17 13:55
Users session timeout and session timeout action settings are not synced via the cloud and are set per-client. Each time you install a new client, they will be set to the default settings, and will need to be configured to your preferred settings.

**Closed by micahblut** 2024-06-17 13:55 UTC
Labels: bug, browser
