### ISSUE TITLE
Multi-select does not allow moving records to No Folder

### ISSUE THREAD

**Issue by ajgold** [bitwarden/clients#7221] opened 2023-12-14 16:01 UTC
### Steps To Reproduce

1. Go to 'My Vault' and any folder with multiple records
2. Select the checkboxes for more than one existing record
3. Select the overflow menu for the list of records
4. Select 'Move selected'
5. From the 'Folder' dropdown, select 'No folder'
6. Select 'Save'
7. Note that a blocking alert 'Input is required.' is displayed and the records are not moved

### Expected Result

The selected records should no longer be associated with the folder they are in

### Actual Result

A blocking alert prevents multi-selected records from being disassociated with a folder

### Operating System

Windows

### Operating System Version

11

### Web Browser

Chrome

### Browser Version

119.0.6045.160

### Build Version

2023.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2023-12-14 17:01
Duplicate of https://github.com/bitwarden/clients/issues/5278

**Comment by djsmith85** [comment] 2023-12-14 17:02
Hi @ajgold ,

Thank you for your report. This report seems like it is a duplicate of https://github.com/bitwarden/clients/issues/5278.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This report will now be closed.

Thank you again

**Closed by djsmith85** 2023-12-14 17:02 UTC
Labels: bug, web
