### ISSUE TITLE
spinning wheel of doom

### ISSUE THREAD

**Issue by quincunxpunx** [bitwarden/clients#9203] opened 2024-05-16 00:51 UTC
### Steps To Reproduce

1. Ubuntu 23.10
2. Double click on blue Bitwarden App Icon
3. Enter correct log-in information

### Expected Result

Open the program and use it. 

### Actual Result

I get a spinning wheel of doom and cannot access anything. 

### Screenshots or Videos

![Screenshot from 2024-05-15 17-47-55](https://github.com/bitwarden/clients/assets/169957424/46d172f0-3968-4ff5-9046-6e4758cff9ad)

### Additional Context

When I try to figure out the build version, this is what it shows me instead : 
![Screenshot from 2024-05-15 17-50-16](https://github.com/bitwarden/clients/assets/169957424/c1cb790b-b450-4430-bafa-ebb2f03086b6)

### Operating System

Linux

### Operating System Version

Ubuntu 23.10

### Installation method

Other

### Build Version

unknown

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment] 2024-05-16 00:58
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/clients/issues/8651

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by sammbw** 2024-05-16 00:58 UTC
Labels: bug, desktop
