### ISSUE TITLE
Windows Hello credential prompt is not centered on the app

### ISSUE THREAD

**Issue by malmentm** [bitwarden/clients#3018] opened 2022-06-30 22:03 UTC
### Steps To Reproduce

Windows Hello credential prompt is not centered on the app when whn autostart is enabled and minimized settings is set. When trying to use Hello for unlocking the Chrome browser extension the hello promt is always in the uppe left corner.

### Expected Result

Windows Hello prompt should be centered in the screen

### Actual Result

Hello prompt always appears in the upper left cornet of the screen.

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.6.0

**Comment by dbosompem** [comment] 2022-07-04 00:51
Welcome @malmentm, and thank you for raising this issue! The team will make time to prioritise this and hopefully issue will be resolved, but, would you like to submit a PR to address this?

**Comment by oeloo** [comment] 2022-08-01 13:49
Hi, I can confirm this issue. Windows Hello prompt is not centered on the app.
I can add that currently Bitwarden for Windows even does not show the Windows Hello prompt on the correct monitor when you have 2 monitors. As a result you often do not realized you have been requested for your fingerprint.

**Comment by sbrewster2** [comment] 2022-08-25 06:16
I have the same issue. I use Windows Hello Face recognition on a wide monitor. As the Hello dialog is on the extreme left, your eyes are naturally drawn to it and you turn your face slightly, causing the face recognition to not work. I have to drag the dialog back to the centre of the monitor, and then it recognises me.

**Comment by oeloo** [comment] 2022-08-25 09:20
I hope this issue is going to a higher priority quicky because this is about security and this should be the prior consideration for a tool like Bitwarden.

**Comment by xIUPITERx** [comment] 2022-08-25 09:54
I also have the problem, but only after I have moved it once myself.

**Comment by Hinton** [comment] 2022-09-15 09:13
This should be resolved in the latest version. The Windows Hello prompt now contains the expected window handler for the Bitwarden application and will be centered within the application window if visible.

**Closed by Hinton** 2022-09-15 09:13 UTC
Labels: bug, desktop
