### ISSUE TITLE
CLI Not Posting to Event Logs when doing get password

### ISSUE THREAD

**Issue by jonjohnston** [bitwarden/clients#11039] opened 2024-09-13 20:15 UTC
### Steps To Reproduce

1. Log into bw cli
2. run bw get password itemname
3. Log into Admin Console and go to Event Logs

### Expected Result

Event logs show cli user "Logged in"
Event logs show cli user "Viewed password for item fasdfadfd"

### Actual Result

Event logs show cli user "Logged in"
Does not record that the password was viewed.

On a probably related issue. When I perform the "bw get password item" when it returns the item password it also says: "Event Post Failed"

### Operating System

Windows, macOS, Linux

### Shell

Bash, Zsh, PowerShell

### Build Version

2024.8.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment] 2024-09-15 15:00
Hi @jonjohnston,

Thank you for this report. I was able to reproduce this and have flagged it to the Engineering department.
Please feel free to post additional information, such as screenshots or a screen video recordings, if you wish.

By the way, are you seeing [1107 (Viewed Item) events](https://bitwarden.com/help/event-logs/#item-events) for the relevant vault item, after running ```bw get password <item id>```? Also, on which operating system did you test this?

Thank you again,

**Comment by jonjohnston** [comment] 2024-09-15 15:41
@SergeantConfused after running bw get password I get no events. I do not get 1107 or 1108 when getting password. This was tested on MacOS and Linux.

**Comment by djsmith85** [comment] 2024-12-19 12:08
Duplicate of https://github.com/bitwarden/clients/issues/10413

**Closed by djsmith85** 2024-12-19 12:08 UTC
Labels: bug, cli
