### ISSUE TITLE
"Unlock with PIN" setting cannot be set -Linux -Linux Mint 21.3 and KDE Neon 6

### ISSUE THREAD

**Issue by rafikiphoto** [bitwarden/clients#8504] opened 2024-03-27 06:13 UTC
### Steps To Reproduce

1. Go to "Settings"
2. Click on "Unlock with PIN"
3. Look for box to insert PIN

### Expected Result

Box should pop up allowing a PIN to be inserted.

### Actual Result

Nothing appears. No way to set PIN

### Additional Context

This was BW installed from Flatpak in the Software Manager. Thinking this might be a corruption in that installer I uninstalled it and downloaded the appimage from the BW website. That exhibited the same problem. Thinking further that it might be a Linux Mint problem I installed BW in KDE Neon on the same machine, that copy installed from Neon’s software manager. The same problem again.
As an aside the BW extension used in Vivaldi browser on all machines works as expected in this respect.

### Operating System

Linux

### Operating System Version

Linux Mint 21.3 and KDE Neon 6

### Installation method

Direct Download (from bitwarden.com), Other

### Build Version

Version 2024.3.0 Shell 28.2.4 Renderer 120.0.6099.291 Node 18.18.2 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-03-27 14:37
Duplicate of https://github.com/bitwarden/clients/issues/8270

**Comment by djsmith85** [comment] 2024-03-27 14:37
Hello @rafikiphoto,

Thank you for this report. It seems like a duplicate of the https://github.com/bitwarden/clients/issues/8270 linked above.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This report will now be closed.

Kind regards,
Daniel

**Closed by djsmith85** 2024-03-27 14:37 UTC
Labels: bug, desktop
