### ISSUE TITLE
Issue generating an username using an alias (simplelogin)

### ISSUE THREAD

**Issue by ovirex** [bitwarden/clients#9302] opened 2024-05-22 04:46 UTC
### Steps To Reproduce

1. Go to 'Robinhood.com (or any other website)'
2. Click on 'The bitwarden extension.'
3. Click on 'Generator button'
4. Click on 'Username'
5. Click on 'Forwarded email alias'
6. Select 'SimpleLogin as the service'
7. Click on 'Regenerate usarname'
8. Go to 'github.com (or any other website)'
9. Repeat process of generating alias.

### Expected Result

It should create an alias using the domain in which the browser extension is open on. If I create an alias in the tab with the domain robinhood.com it should create an alias using that domain. And if I move to another tab, in this case I have open github.com. It should create an alias using the github.com domain.

### Actual Result

The first time, on the first website, it's going to create an alias with the website domain. Example: robinhood.example123@simplelogin.com. If you check in your simplelogin account, the alias description is gonna say "website: robinhood. Created by: bitwarden". Now, the problem is that, if you go to another website and create another alias, the browser extension is gonna keep the first website domain in order to create the alias. i.e. If I'm creating an alias for github, it's gonna be robinhood.example2.123@simplelogin.com, it's using robinhood domain again instead of github.

### Operating System

Windows

### Web Browser

Brave

### Build Version

2024.4.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-05-22 09:42
Duplicate of https://github.com/bitwarden/clients/issues/3371

**Comment by djsmith85** [comment] 2024-05-22 09:43
Hi @ovirex,

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/3371

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2024-05-22 09:43 UTC
Labels: bug, browser
