### ISSUE TITLE
Huge bitwarden icon shows on text input in Google chrome

### ISSUE THREAD

**Issue by samislam** [bitwarden/clients#7826] opened 2024-02-06 12:56 UTC
### Steps To Reproduce

1. Go to [asci tree generator website](https://tree.nathanfriend.io/?s=(%27options!(%27fancy0~fullPath!false~trailingSlash0~rootDot0)~2(%272%27src.app4%7Bdashboard%7D4auth4*login4*forgot-password4*3media.types%2F%27)~version!%271%27)*%20%20.%2F30!true2source!3%5Cn*4.*%014320.*)
2. Click on 'the text input'
3. start writing

### Expected Result

to not see bitwarden on <textarea /> inputs, or to only see the bitwarden icon in <input /> elements when `type="email"` `type="password"` attributes are set.

### Actual Result

Big bitwarden icon

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/59496975/3c15fd67-671c-4cc3-a30c-4a16736308f1)

### Operating System

Linux

### Operating System Version

Linux Mint 21.2

### Web Browser

Chrome

### Build Version

Version 121.0.6167.139 (Official Build) (64-bit)

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-02-06 12:58
Hi @samislam,

the issue is that textareas are treated as inputs for inline-autofill. It was previously reported with https://github.com/bitwarden/clients/issues/7628.

This has been addressed with https://github.com/bitwarden/clients/pull/7655 and will be included in a future release (2024.2).

Closing this now.

**Closed by djsmith85** 2024-02-06 12:58 UTC
Labels: bug, browser

**Comment by samislam** [comment] 2024-02-06 13:02
Do I need to update anything to stop this problem?

**Comment by djsmith85** [comment] 2024-02-06 13:27
> Do I need to update anything to stop this problem?

@samislam Your browser extension should automatically update, once `2024.2` becomes available. Depending on which browser you are using, there might be a delay of up to a week after Bitwarden has released, due to review and approval of the browser stores.

**Comment by samislam** [comment] 2024-02-06 13:40
Alright thanks for your help.
