### ISSUE TITLE
Unlock desktop app — unable to enter diactitics in invisible password mode

### ISSUE THREAD

**Issue by NeoRey73** [bitwarden/clients#7260] opened 2023-12-18 08:53 UTC
### Steps To Reproduce

1. Unlock macOS desktop app
2. Enter Master password which contains diacritics (å, à, é, ë, à, á, etc)
3. Diacritics are not entered in invisible password mode (password as dots mode ••••••••••)
4. Click on the _Toggle visability_ icon
5. Adjust the letter in question (in my case e > ë)
6. Login

### Expected Result

The Master password should contain diacritics and be able to be entered during login.

### Actual Result

Diacritic ë doesn't work, password needs to be made visable to corect this.

### Screenshots or Videos

![Screenshot 2023-12-18 at 09 44 21](https://github.com/bitwarden/clients/assets/26891752/74351297-037a-40b9-ab07-9d6e25e7ef06)
![Screenshot 2023-12-18 at 09 44 34](https://github.com/bitwarden/clients/assets/26891752/c1ec4599-ad11-43ba-9ab7-eec522028616)
![Screenshot 2023-12-18 at 09 44 42](https://github.com/bitwarden/clients/assets/26891752/334e6de9-2e80-4c14-9e9d-b2495de78fc4)

### Operating System

macOS

### Operating System Version

14.2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.12.0 (15279)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NeoRey73** [comment] 2023-12-18 08:58
The desktop app is installed through the App Store instead of the direct download option on bitwarden.com.

**Comment by djsmith85** [comment] 2023-12-18 12:59
Hi @NeoRey73,

Thank you for your report. This report seems like it is a duplicate of https://github.com/bitwarden/clients/issues/2472.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This report will now be closed.

Thank you again

**Closed by djsmith85** 2023-12-18 12:58 UTC
Labels: bug, desktop
