### ISSUE TITLE
[macOS] Application window is missing most display content

### ISSUE THREAD

**Issue by d-Martian** [bitwarden/clients#8440] opened 2024-03-22 01:14 UTC
### Steps To Reproduce

1. Open the desktop client (issue only when downloaded from the macOS App Store) window using any method (opening app, menu bar, hotkey, etc.)

### Expected Result

Application window is displayed with content appropriate for each view such as log-in when not logged in yet.

### Actual Result

Client window is missing text, input areas, logo images, borders. Only layer background colors are shown.

### Screenshots or Videos

![Bitwarden_Client_Window_macOS](https://github.com/bitwarden/clients/assets/92518074/9ae57a3c-e314-4aa8-8730-a5ee2fde5783)

### Additional Context

This issue doesn't apply to installs other than the Mac App Store, but only the Mac App Store has Safari integration.

### Operating System

macOS

### Operating System Version

12.7.4

### Installation method

Mac App Store

### Build Version

2024.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment] 2024-03-22 05:50
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/clients/issues/8003

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by sammbw** 2024-03-22 05:50 UTC
Labels: bug, desktop
