### ISSUE TITLE
Firefox - private mode - extension is blank (both sidebar, and clicking on the icon)

### ISSUE THREAD

**Issue by amit-nz** [bitwarden/clients#8986] opened 2024-04-30 12:33 UTC
### Steps To Reproduce

1. Open firefox
2. Invoke private mode (CTRL+SHIFT+P)
3. Click on the bitwarden extension icon
4. Alternatively, presses CTRL+SHIFT+Y to call up the Bitwarden sidebar.

### Expected Result

The bitwarden extension drop-down/pop-over should open and ask to authenticate w/ your master password OR, the sidebar should load up and ask for your master password

### Actual Result

A blank box shows up instead:

![image](https://github.com/bitwarden/clients/assets/12567648/aba91237-62f2-46ad-982f-b850d702b6d2)

And the CTRL+SHIFT+Y "sidebar" mode:
![image](https://github.com/bitwarden/clients/assets/12567648/e61c9114-8c0b-4331-8aee-da3792e7bb57)

### Additional Context

This started happening a week or so ago.

This issue only exists in Firefox; it works OK in edge InPrivate and chrome Incognito modes but I don't use those browsers.

### Operating System

Windows 11 Pro

### Operating System Version

 build 23H2

### Web Browser

Firefox

### Browser Version

125.0.3

### Build Version

Desktop App & Extension Version 2024.4.1; Self-hosted (server version 2024.3.1)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbw23** [comment] 2024-04-30 15:04
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by MGibson1** [comment] 2024-04-30 20:19
This should be fixed by #8709. The I was able to reproduce seemed to be due to attempting to access a fake messaging api being used in private mode. Unfortunately, that PR didn't make the cut for the release planned to go out this week, but will be in the next.

It's a rather large change, so it wouldn't be prudent to pick it into this release (there have been an number of issues that have been caused by it and cleaned up since it was merged). It will be ready for the next release, though.

**Closed by MGibson1** 2024-04-30 20:19 UTC
Labels: bug, browser
