### ISSUE TITLE
BitWarden not appearing in Firefox on Windows 10

### ISSUE THREAD

**Issue by ImagineReason** [bitwarden/clients#11194] opened 2024-09-22 23:07 UTC
### Steps To Reproduce

1. Go to any login page.
2. Right click on the login boxes.
3. Nothing happens.  No Bitwarden menu item appears.
4. No existing login appears as a dropdown.

### Expected Result

Edge extension is working.  Firefox worked for a few weeks after the last disappearance but is having the same problem again.

### Actual Result

Bitwarden add-on should be usable in Firefox, not disappear.

### Operating System

Windows

### Operating System Version

10

### Web Browser

Firefox

### Browser Version

130.0.1

### Build Version

2024.9.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment] 2024-09-23 03:58
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/clients/issues/10814

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by sammbw** 2024-09-23 03:58 UTC
Labels: bug, browser
