### ISSUE TITLE
Constant Log Out

### ISSUE THREAD

**Issue by Lainemac** [bitwarden/clients#12336] opened 2024-12-10 19:06 UTC
### Steps To Reproduce

Seems to happen everyday or so and only in safari. I have the desktop and chrome extension and those are functioning perfectly. 

### Expected Result

Stay logged in. Set to lock and never time out as well as setting pin and biometrics. Nothing seems to keep me logged in.

### Actual Result

Logged out.

### Operating System

macOS

### Web Browser

Safari

### Browser Version

18..1.1

### Build Version

2024.11.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment] 2024-12-13 12:12
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/11386
If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by Greenderella** 2024-12-13 12:12 UTC
Labels: bug, browser

**Comment by SergeantConfused** [comment] 2024-12-14 15:11
Hi @Lainemac,

For added context, could you please detail to what the Vault Timeout Action function is set in each browser you use?

Thank you in advance,

**Comment by Lainemac** [comment] 2024-12-19 07:53
Vault action is always sweet to ‘lock’ with time out being set to ‘never‘

-Lain-
www.JustBreatheMovers.com
