### ISSUE TITLE
Not able to sync

### ISSUE THREAD

**Issue by GigaLoop** [bitwarden/clients#9173] opened 2024-05-14 14:10 UTC
### Steps To Reproduce

Fresh install of version 2024.4.3
After logged in with master password app failed to sync.
Interestingly, I received an email that "Your Bitwarden account was just logged into from a new device. " 
Also, Firefox Add-on works great. That's how I get by. 

### Expected Result

App should sync the account.

### Actual Result

![Sync failed_Bitwarden 4](https://github.com/bitwarden/clients/assets/169815086/3824da14-44a9-497c-8391-1061b2f7ce29)

### Screenshots or Videos

![Sync failed_Bitwarden 4](https://github.com/bitwarden/clients/assets/169815086/733e9a74-b077-46ad-af5e-a689afd4a8eb)
![Sync failed_Bitwarden 5](https://github.com/bitwarden/clients/assets/169815086/d1d8b7b9-107b-4f39-b979-b9bab633d4a0)
![Sync failed_Bitwarden 1](https://github.com/bitwarden/clients/assets/169815086/65955c01-d695-4af6-a933-fa3ac316be2d)
![Sync failed_Bitwarden 6](https://github.com/bitwarden/clients/assets/169815086/b16accc2-8517-4718-aef5-965de903162f)

### Additional Context

![SYS info](https://github.com/bitwarden/clients/assets/169815086/aeb708e2-cca1-4f29-bb2c-6b40934f05db)

### Operating System

Linux

### Operating System Version

EndeavourOS Linux

### Installation method

Other

### Build Version

2024.4.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-05-15 08:38
Duplicate of https://github.com/bitwarden/clients/issues/8651

**Comment by djsmith85** [comment] 2024-05-15 08:38
Hi @GigaLoop,

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/8651#issuecomment-2093261158.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2024-05-15 08:38 UTC
Labels: bug, desktop
