### ISSUE TITLE
Can't open credential protected by "Master password re-prompt"

### ISSUE THREAD

**Issue by darthsebulba04** [bitwarden/clients#6331] opened 2023-09-18 19:41 UTC
### Steps To Reproduce

Try to open a password with the radio "Master password re-prompt" checked.  

On the iOS app, it crashes.  On the macOS app, it just hangs.  In the browser, it also hangs.

Works from the web.

### Expected Result

To view the credential.

### Actual Result

Crash or hang of the application. 

### Operating System

macOS

### Operating System Version

13.5.2

### Installation method

Mac App Store

### Build Version

11864

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jamerst** [comment] 2023-09-18 19:44
I am also experiencing this in the Firefox extension on Linux (version 2023.8.3).

**Comment by Neonwarden** [comment] 2023-09-18 19:50
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/6153. 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by Neonwarden** 2023-09-18 19:50 UTC
Labels: bug, desktop
