### ISSUE TITLE
mac os x - syncing failed

### ISSUE THREAD

**Issue by lestatcheb** [bitwarden/clients#7715] opened 2024-01-29 01:46 UTC
### Steps To Reproduce

1. Open Bitwaden Desktop mac os x
2. Click on File --> Sync vault
3. Get an error "Syncing failed"

### Expected Result

1. Open Bitwaden Desktop mac os x
2. Click on File --> Sync vault
3. shouldn't get any sync errors

### Actual Result

Error "Syncing failed"

### Additional Context

If I sync the same vault on my mobile device using Bitwarden iOS app - it works correctly.
Only on Mac OS X I see this `Syncing failed` error.
If I toggle developer tools and check Network tab - I don't see any network errors, I get 200 OK response.

### Operating System

macOS

### Operating System Version

Sonoma 14.2.1 (23C71)

### Installation method

Mac App Store

### Build Version

Version 2023.12.1 Shell 25.9.1 Renderer 114.0.5735.289 Node 18.15.0 Architecture arm64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by GHA193** [comment] 2024-01-29 14:57
# me too. 
## Operating System
macOS

## Operating System Version
Sonoma 14.3 (23D56)

## Installation method
Mac App Store

## Build Version
Version 2023.12.1
Shell 25.9.1
Renderer 114.0.5735.289
Node 18.15.0
Architecture x64

**Comment by SergeantConfused** [comment] 2024-01-30 15:25
Hi @lestatcheb and @GHA193,

Thank you for this report. It seems like it's a duplicate of this [one](https://github.com/bitwarden/clients/issues/7243); Hopefully its [fix](https://github.com/bitwarden/clients/issues/7243#issuecomment-1885065027) will be incorporated into a future release of the macOS and Safari clients. If you wish to add any further information, such as screenshots or screen recordings, please feel free to do so at any time in that existing thread - our Engineering team will be happy to review them.

We use GitHub to track bugs and other development related matters; This GitHub report will be closed at this point.

Thank you again,

**Closed by SergeantConfused** 2024-01-30 15:25 UTC
Labels: bug, desktop

**Comment by lestatcheb** [comment] 2024-01-30 18:04
The latest mac app store version is 2023.12.1

<img width="1493" alt="Screenshot 2024-01-30 at 10 04 16 AM" src="https://github.com/bitwarden/clients/assets/822527/0a3ff654-59a7-4ee4-8dc4-7e754e56691c">

**Comment by spiceee** [comment] 2024-02-08 18:30
Can confirm it's not fixed in mac os 13.6.3, Bitwarden 2023.12.1 (16254)

**Comment by mptm436** [comment] 2024-04-29 09:11
updated to the latest version on App store, which is version 2024.4.1(23240), Syncing failed

**Comment by ctschach** [comment] 2024-09-25 21:25
The issue showed up on macOS Sequoia with the latest Bitwarden version from the MacAppStore.
The desktop client syncs fine, while the browser extension in Safari fails. All other browsers work fine...

**Comment by gus4rs** [comment] 2024-11-10 19:27
Bitwarden 2024.10.2 (32149) still fails to sync on macos
