### ISSUE TITLE
Icon for Safari extension is not showing

### ISSUE THREAD

**Issue by karim-al-amin** [bitwarden/clients#4702] opened 2023-02-09 07:08 UTC
### Steps To Reproduce

1- Download Bitwarden from App Store 
2- Go into Safari preferences and enable extension 
3- Right click on the Safari toolbar and select "Customise Toolbar..."
4- Drag Bitwarden icon into the toolbar

### Expected Result

The icon for Bitwarden should be now be visible in the toolbar and shows a counter when there are passwords in the vault that apply. 

### Actual Result

The Bitwarden extension works as expected but the icon for it is missing. It appears as an invisible square. It also does not show in the Safari preferences under extensions. 

### Screenshots or Videos

<img width="519" alt="Screenshot 2023-02-09 at 07 57 29" src="https://user-images.githubusercontent.com/95564910/217740901-a6e7034d-0a1a-440c-afef-4ad1c9db4ba2.png">

<img width="380" alt="Screenshot 2023-02-09 at 07 57 46" src="https://user-images.githubusercontent.com/95564910/217740906-4353f133-9977-4bb5-97d2-fca2b37e929b.png">

### Operating System

macOS

### Operating System Version

11.7.3

### Web Browser

Safari

### Browser Version

Version 16.3 (16614.4.6.11.4, 16614)

### Build Version

Version 2023.1.1 (6572)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment] 2023-02-09 09:38
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by rohswell** [comment] 2023-02-13 03:59
I have same issue. I found the help page for browser extensions, https://bitwarden.com/help/getting-started-browserext/, and got the extension from the Apple store. I'll note that the BitWarden listing in the Apple store identifies it as a browser extension, not as a desktop app. That gave me the expectation that I was only working with an extension. I did the download and Open from the Apple store.

<img width="450" alt="bitwarden-app-store" src="https://user-images.githubusercontent.com/7015570/218365125-a0ac49a5-84e9-4b8b-9812-d55695280bea.png">

After reading the help page above and installing the app from the Apple store, I immediately enabled the extension in Safari, because that is what I'm used to doing with browser extensions. At that point, I did not see the BitWarden icon in the Safari toolbar. I tried closing Safari and opening it again, with no change. The icon was still missing.

<img width="306" alt="no-bitwarden-icon" src="https://user-images.githubusercontent.com/7015570/218364777-523405fb-d73a-4a05-b9e6-72c640cb0a88.png">

The gray block would not dock when I dragged it to the toolbar in the Customize Toolbar dialog.

After futzing with this for a while, I found a second help page, https://bitwarden.com/help/install-safari-app-extension/, that says to run the desktop app at least once before activating the Safari extension. That's potentially useful information, but I learned it too late. Adding that note to the first help page would be more helpful. I did try removing the BitWarden app, and reinstalling it from the Apple store. However, that changed nothing.

My current status is that I must open the Apple store, search for BitWarden, and click the Open button to open BitWarden. I still can't get BitWarden to fill any login forms, I guess because I can't find a way to launch the extension in Safari. Only the desktop app runs.

Outstanding questions:
1) How do I launch the Safari extension so I can use BitWarden for logins?
2) Can I undo my current state and install BitWarden for Safari correctly?

**Comment by rohswell** [comment] 2023-02-16 22:20
I learned that I actually did customize the Safari toolbar when I dragged the gray BitWarden icon block to the toolbar. I just couldn't see the icon on the toolbar. However, when I visited a page with logins in my vault, a little numeral in a red capsule appeared by the URL address bar. And clicking on the empty space or the numeral opened a BitWarden dialog box. So the icon exists, but is invisible.

<img width="395" alt="BitWardenIcon" src="https://user-images.githubusercontent.com/7015570/219499916-3ded277a-78a8-49cb-93f4-bb1b3406bb35.png">

**Comment by perarg** [comment] 2023-04-02 21:16
Exactly the same behaviour (bug) here too.
MacOS 11.7.3, Safari: 16.3

**Comment by Greenderella** [comment] 2024-08-21 15:19
Thank you all for your patience and for reporting this issue. We apologize for the delay in addressing your concern.

After further investigation, the team was unable to reproduce the problem on macOS 14.5 with Safari 17.5. It appears that this issue might have been specific to macOS v11.7.3 and Safari 16.3, as noted in Apple's forum: https://discussions.apple.com/thread/254590311

Unfortunately, Apple does not provide detailed release notes for patch versions, which makes it challenging to verify specific fixes. If anyone experiences similar issues with newer versions, please let us know.

**Closed** 2024-09-05 05:28 UTC
Labels: bug, browser, needs-reply
