### ISSUE TITLE
App turns blank after 2 sec

### ISSUE THREAD

**Issue by Zolektric** [bitwarden/clients#6666] opened 2023-10-23 11:22 UTC
### Steps To Reproduce

1. Open desktop-app
2. The app turns blank after about 2 seconds. 

### Expected Result

Be able to login and use the app.

### Actual Result

Just a blank window. The meny is till operable however, but everything relating to login/logout is grayout. 

Have purge old install (flatpak) and installed new deb, with the same result. 

### Operating System

Linux

### Operating System Version

Pop!_OS 22.04 LTS

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.9.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2023-10-23 13:03
Hi @Zolektric ,

Thank you for your report. This report seems like it is a duplicate of this (https://github.com/bitwarden/clients/issues/6560). A fix has been made available with `2023.9.3`

This report will now be closed.

Thank you again

**Closed by djsmith85** 2023-10-23 13:03 UTC
Labels: bug, desktop
