### ISSUE TITLE
Desktop App & Browser Extension hangs when backend service is unavailable/connection times out

### ISSUE THREAD

**Issue by DigitallyRefined** [bitwarden/clients#10839] opened 2024-09-01 11:50 UTC
### Steps To Reproduce

**With `vault.bitwarden.com`**

1. Launch the Desktop App & Browser Extension and login and sync passwords
2. Trigger a network timeout or a slow connection while connecting to the `vault.bitwarden.com` backend
	* For example open `/etc/hosts` (or `%SystemRoot%\System32\drivers\etc\hosts` on Windows) and add   
	`192.168.215.156 vault.bitwarden.com`
4. Lock or restart the app and attempt to login

**On a [self-hosted Bitwarden instance](https://bitwarden.com/help/install-on-premise-linux/) behind a VPN**

1. Connect to VPN where self-hosted Bitwarden instance is available (or VPN like service such as Tailscale etc.)
2. Launch the Desktop App & Browser Extension and login and sync passwords
3. Disconnect from VPN (making the backend unreachable/timeout)
3. Lock or restart the app and attempt to login

### Expected Result

* To be logged in within a second or two using an offline/cached copy of the password database
* Folder navigation to be almost instant
* Creating/editing/deleting entries should show a cannot edit error while backend is unavailable/unreachable
* Database is loaded almost instantly and passwords are synced in the background (when the connection is available again)

### Actual Result

**Desktop and Browser Extension (using password)**

1. Login screen hangs and doesn't show that it's currently loading after entering password or fingerprint
2. After around 60 seconds or so, cached passwords are shown
3. Clicking through different folders a spinner is shown and then after around 30-60 seconds a cached list of passwords from that folder is shown

**Browser Extension (using biometric/fingerprint login)**

1. Login screen is shown
2. After using biometric login a blank popup is shown

### Screenshots or Videos

**Login via password hanging**

https://github.com/user-attachments/assets/3fa9d801-a84d-4a5d-8efc-e8c09f9d0cb9

**Blank Bitwarden Extension page when using biometric/fingerprint login**
<img src="https://github.com/user-attachments/assets/b92e5fe3-0a0f-4300-83c5-4616836fa0b7" width="350">

**Changing folder hanging**

https://github.com/user-attachments/assets/2cd6d3d6-bdee-4a25-bdb1-56ee118ce2fb

### Additional Context

Using Bitwarden Desktop 2024.3.2 does not appear to have this issue and loads an offline copy almost instantly (favicons don't load, but that's to be expected)

### Operating System

Windows, macOS, Linux

### Operating System Version

Windows 11, macOS Sonoma, Fedora 40

### Installation method

Direct Download (from bitwarden.com), Mac App Store

### Build Version

2024.8.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment] 2024-09-01 13:51
Hello @DigitallyRefined,

Thank you for your report. This report seems to be a duplicate of this [GitHub report](https://github.com/bitwarden/clients/issues/9561); If there's anything you'd like to add, such as screenshots or video recordings of the screen, please feel free to add them to that existing GitHub report so that they'd be reviewed by the Bitwarden Engineering department.

Please bear in mind that this topic was also brought up [here](https://github.com/bitwarden/clients/issues/10001) and [here](https://github.com/bitwarden/clients/issues/10743); More information about its fix can be found [here](https://github.com/bitwarden/clients/issues/10743#issuecomment-2312954065).

This report will now be closed as a duplicate.

Thank you again,

**Closed by SergeantConfused** 2024-09-01 13:51 UTC
Labels: bug, desktop
