### ISSUE TITLE
Device login not working on Desktop + Android

### ISSUE THREAD

**Issue by guillemglez** [bitwarden/clients#6819] opened 2023-11-07 11:21 UTC
### Steps To Reproduce

1. Go to Log in and enter user email address
2. Click on Log in with another device (other device shall be registered)
3. Tap the notification on the other device (I used an Android device)

### Expected Result

Login is succeded

### Actual Result

Nothing happens

### Screenshots or Videos

Desktop stays in this screen

![image](https://github.com/bitwarden/clients/assets/25482726/c7055012-de17-4cfc-849c-685ee28b2484)

Can't send Android screenshot since Bitwarden is a protected app :/

### Additional Context

Using Android 13 on a Pixel 6 device. Android app 2023.9.2 (8002).

Snap package for Ubuntu 22.04:

Version 2023.10.1
Shell 25.9.1
Renderer 114.0.5735.289
Node 18.15.0
Architecture x64

### Operating System

Linux

### Operating System Version

Ubuntu 22.04

### Installation method

Snap

### Build Version

2023.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2023-11-07 12:24
Hi @guillemglez ,

Thank you for your report. It seems like it is a duplicate of this (https://github.com/bitwarden/clients/issues/5297). A pull request was created with https://github.com/bitwarden/clients/pull/6715 which addresses this and the changes will be included in the next release.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This report here will now be closed.

Thank you again,

**Comment by guillemglez** [comment] 2023-11-07 12:32
Hi @djsmith85,

I think the issue #5297 refers to Account Fingerprint Phrase, but my issue is being unable to login using the *Login with another device* option:

![image](https://github.com/bitwarden/clients/assets/25482726/02c32808-407e-48f2-a093-9644ba1f988e)

The Account Fingerprint Phrase can't be accessed prior to login. Moreover, I am also affected by #2606 which prevents me from using SSO, mandatory in my organization. I am effectively locked out of the Bitwarden Desktop App which makes me unable to check if I am affected with #5297.

**Comment by djsmith85** [comment] 2023-11-07 13:17
@guillemglez Apologies, I'll re-open. That does sound like a different issue. Is it possibly related to https://github.com/bitwarden/mobile/issues/2859

**Comment by guillemglez** [comment] 2023-11-07 13:35
Just to clarify, I do receive the Android notification, but opening it only shows the Bitwarden App, and nothing else happens in the Desktop.

I am not sure if this is particularly a mobile app issue, but it does not seem so since I could not find any similar issue.

**Comment by atjbramley** [comment] 2023-11-07 15:01
Hi @guillemglez ,

I attempted to reproduce your issue and was unable to do so.

In particular, I:

- installed Bitwarden 2023.10.1 via snap on Ubuntu 22.04.03 LTS
- configured an Android 13 device with Bitwarden Android app 2023.9.2 (8002).
- sent a login with device request from the Ubuntu snap app to my Android device

I furthermore tested the additional steps noted in https://github.com/bitwarden/mobile/issues/2859

I received the push notification and was able to continue with the login without difficulty.

I think your error could have its origin in a networking issue, and would encourage you to re-install both clients and try again.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Closed by atjbramley** 2023-11-07 15:01 UTC
Labels: bug, desktop
