### ISSUE TITLE
Opera extension [error: cannot decrypt]

### ISSUE THREAD

**Issue by seg-on** [bitwarden/clients#6784] opened 2023-11-03 09:53 UTC
### Steps To Reproduce

Reopen the browser and unlocking Bitwarden.

### Expected Result

I can see my saved logins and passwords.

### Actual Result

All records are "[error: cannot decrypt]" and it is unusable.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/19683952/a33f675d-750c-4fff-9478-b44832fdd6a8)

### Additional Context

If I sign out and then sign in with the 2-factor authentication I have enabled, it works until I close the browser.

### Operating System

Windows

### Operating System Version

10.0.19045.3636

### Web Browser

Opera

### Browser Version

105.0.4970.6 and 104.0.4944.36

### Build Version

2023.10.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2023-11-03 12:32
Duplicate of https://github.com/bitwarden/clients/issues/6759

**Comment by djsmith85** [comment] 2023-11-03 12:33
Hi @seg-on, this seems to be a duplicate of #6759.

As you can see from [this comment](https://github.com/bitwarden/clients/issues/6759#issuecomment-1791745443) the issue has been addressed and `2023.10.1` should resolve it.

Closing this now.

Kind regards,
Daniel

**Closed by djsmith85** 2023-11-03 12:33 UTC
Labels: bug, browser
