### ISSUE TITLE
Windows 11 Desktop app stuck at loading.  Circling icon.  Won't load data

### ISSUE THREAD

**Issue by cqaigy** [bitwarden/clients#7733] opened 2024-01-29 19:00 UTC
### Steps To Reproduce

1. Open Bitwarden app.

### Expected Result

Expect to access passwords etc.

### Actual Result

Can not access passwords etc from desktop application.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/5987375/d60a93fb-81e3-4806-93aa-9744956bfd29)

### Additional Context

Removed application and reloaded from Windows store and from Bitwarden site.

### Operating System

Windows

### Operating System Version

Microsoft Windows 11 Home. verson:10.0.22631

### Installation method

Direct Download (from bitwarden.com), Microsoft Store

### Build Version

Version 2024.1.0 Shell 27.2.0 Renderer 118.0.5993.159 Node 18.17.1 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment] 2024-01-30 00:28
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/clients/issues/6878

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by sammbw** 2024-01-30 00:28 UTC
Labels: bug, desktop

**Comment by cqaigy** [comment] 2024-01-30 00:59
Oh yes.  It looks exactly the same.

Thanks!
