### ISSUE TITLE
GIANT Bitwarden icon obstructing a multi-line text box element in Safari (MacOS)

### ISSUE THREAD

**Issue by KernelBypass** [bitwarden/clients#7752] opened 2024-01-31 03:51 UTC
### Steps To Reproduce

1. Go to '[help.sourcegraph.com/hc/en-us/requests/](https://help.sourcegraph.com/hc/en-us/requests/')
2. Open an issue.
3. Start typing secondary response in a text box.

### Expected Result

Several reasonable outcomes in the order of preference from best to ok:

1. No Bitwarden involvement: this is a multi-line text entry box, which is obviously not a one-line password/login field. Bitwarden has no business getting triggered here.

2. Small Bitwarden icon with ability to dismiss (not ideal).
3. Small Bitwarden icon with ability to ignore (even less ideal).

### Actual Result

GIGANTIC Bitwarden icon that won't go away:

<img width="1123" alt="image" src="https://github.com/bitwarden/clients/assets/62620821/1e7e29b8-cf7e-4d77-bb97-8d645f9c00bb">

Cannot ignore a giant icon that's obstructing a big part of the box.

### Screenshots or Videos

<img width="1123" alt="image" src="https://github.com/bitwarden/clients/assets/62620821/3ad52b59-9c9c-469c-911f-25f53136c396">

### Additional Context

I believe it's a self-hosted ZenDesk instance, but I am not 100% sure. The login does occur at a ZenDesk subdomain, but then you get redirected to Sourcegraph's own domain. 

### Operating System

macOS

### Operating System Version

14.2.1

### Web Browser

Safari

### Browser Version

17.2.1 

### Build Version

2023.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by KernelBypass** [comment] 2024-01-31 04:16
Additional screenshot showing a window with account selection that also opens up intermittently as you type:

---

<img width="1004" alt="image" src="https://github.com/bitwarden/clients/assets/62620821/9fdacd97-0b41-43f7-bbf0-01e1c69b3206">

**Comment by Greenderella** [comment] 2024-01-31 12:18
Hi there,

I am unable to reproduce this issue as we don't have access to this Zendesk instance, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by djsmith85** [comment] 2024-01-31 13:11
Duplicate of https://github.com/bitwarden/clients/issues/7628

**Closed** 2024-01-31 13:12 UTC
Labels: bug, browser
