### ISSUE TITLE
bitwarden doesn't auto lock after search and copy password

### ISSUE THREAD

**Issue by shalom938** [bitwarden/clients#4947] opened 2023-03-07 10:12 UTC
### Steps To Reproduce

Using flatpak client on opensuse tumbleweed.
1. Go to search box
2. search for an item and copy the password, don't clear the search box, and leave the bitwarden window.

### Expected Result

bitwarden should lock after configured timeout

### Actual Result

bitwarden never locks if the search box is not cleared.

### Additional Context

when I do a search in bitwarden , find my item, copy the password and leave the bitwarden window without clearing the search box. bitwarden never locks again, i came back to my computer after 24 hours and the window was still as is with the search result and not locked, i could continue viewing all the items.

### Operating System

Linux

### Operating System Version

openeuse tumbleweed

### Installation method

Other

### Build Version

Version 2023.2.0 Shell 21.3.1 Renderer 106.0.5249.181 Node 16.16.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment] 2023-03-07 23:14
Hi @shalom938,

Thank you for this report. I tested this in a similar environment and I was unable to reproduce this behaviour; To be clear, I set the Vault Timeout to 1 minute, searched for a vault item, opened the vault item, copied the password, and waited 1 minuted while the desktop client remained in the foreground and in focus, and it locked after a minute.

Did you put the computer to sleep? I ask because I'm wondering if that could be the cause, in case the application/operating system did not keep track of time in that state. If not, please feel free to get in touch with us (https://bitwarden.com/contact/) so we'll troubleshoot this together.

We use GitHub issues as a place to track bugs and other development related issues; I'm going to close this report now.


Thank you again,

**Closed by SergeantConfused** 2023-03-07 23:14 UTC
Labels: bug, desktop
