### ISSUE TITLE
The button for filling in login and password is very small

### ISSUE THREAD

**Issue by illia-weisser** [bitwarden/clients#12443] opened 2024-12-17 16:10 UTC
### Steps To Reproduce

1. Go to any website
2. Click on bitwarden extension's icon

### Expected Result

I expect a HUGE autofill button somewhere in the expected place, like on the right. Not in the middle of a bunch of other buttons.

### Actual Result

Now every time I try to find this mini-button with my eye and manage to hit it

### Additional Context

Give your design team a slap on the wrist. It takes skill to make so many mistakes these days!

I can forgive problems with colors, fonts and their sizes. But why spoil the already established schemes of working with the extension, removing important buttons and hanging the main functions on micro buttons in unexpected places? I don't understand

### Operating System

macOS

### Web Browser

Chrome

### Browser Version

Version 131.0.6778.140 (Official Build) (x86_64)

### Build Version

Version: 2024.12.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by AkramiPro** [comment] 2024-12-18 07:55
> Thank you for reporting this issue! We've added this to our internal tracking system. ID: PM-16131

This is very poor UX. It should be the same as the old version, where the fill process is triggered by clicking on the item, not a button! You changed the behavior and replaced the edit button with the fill button. This is not correct at all.

**Comment by Krazy998** [comment] 2024-12-18 08:01
Unfortunately its a +1 here. Pretty annoying UX change. I am constantly hitting the edit button instead of fill. Please change it back and make the tiny fill button the edit button.

**Comment by jtodddd** [comment] 2024-12-18 14:13
Hi there,

Your issue appears to be describing the intended behavior of the software. If you want this to be changed, it would be a feature request. We use GitHub issues as a place to track bugs and other development related issues. 

I will say that we have received other feedback about the button size in the form of people contacting support via our Help Center (https://bitwarden.com/help/) so this is known feedback and is being evaluated.

 If you'd like to be able to have a forum to keep up with this, the Bitwarden Community Forums has a Feature Requests section for submitting, voting for, and discussing requests like this one: https://community.bitwarden.com/c/feature-requests/  

Please sign up on our forums (https://community.bitwarden.com/signup) and search to see if this request already exists. If so, you can vote for it and contribute to any discussions about it. If not, you can re-create the request there so that it can be properly tracked.

In the meantime if you're looking for speed, you could consider the autofill keyboard shortcut: https://bitwarden.com/help/keyboard-shortcuts/

This issue will now be closed here since this is technically intended, but please know that feedback like yours is crucial in helping us align with user expectations. As mentioned, we are currently reviewing this change and considering options. Our team values user input highly, and we are committed to improving your experience with Bitwarden.

Thank you for your patience and understanding.

**Closed by jtodddd** 2024-12-18 14:13 UTC
Labels: bug, browser
