### ISSUE TITLE
Bitwarden extension for Safari error - Unable to find "popup/fonts/bwi-font.svg" in the extension’s resources.

### ISSUE THREAD

**Issue by archonium-github** [bitwarden/clients#11145] opened 2024-09-19 06:33 UTC
### Steps To Reproduce

1. Go to 'Safari -> Settings'
2. Click on 'Extensions -> Bitwarden Password Manager'
3. Scroll down to 'Errors for 'Bitwarden Password Manager'
4. Error shown is 'Unable to find "popup/fonts/bwi-font.svg" in the extension’s resources'

<img width="584" alt="Screenshot 2024-09-19 at 14 28 28" src="https://github.com/user-attachments/assets/4c98bfa7-9ca0-4d5b-8905-c7fb8b1ed3a9">

Safari - Version 18.0 (19619.1.26.111.10, 19619)
macOS - 14.7 (23H124)

### Expected Result

No errors

### Actual Result

Error shown is 'Unable to find "popup/fonts/bwi-font.svg" in the extension’s resources'

### Screenshots or Videos

<img width="584" alt="Screenshot 2024-09-19 at 14 28 28" src="https://github.com/user-attachments/assets/f188e0bc-6a1c-4591-a7b2-d0310bc16049">

### Operating System

macOS

### Operating System Version

14.7 (23H124)

### Web Browser

Safari

### Browser Version

Version 18.0 (19619.1.26.111.10, 19619)

### Build Version

Version 18.0 (19619.1.26.111.10, 19619)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment] 2024-09-19 08:59
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by ksnell88** [comment] 2024-09-28 02:04
I have the same issue, and I only noticed because all the sudden the extension doesn't seem to be recognizing the webpage I am on to update autofill suggestions on the `Tab` pane. The extension works as expected in Microsoft Edge on the same machine so this seems to be related to Safari.

I've tried uninstalling the desktop app (and extension), restarting, etc. and it doesn't fix either issue.

macOS: 15.0 (24A335)
Safari: Version 18.0 (20619.1.26.31.6)

Bitwarden version: 2024.9.1
Server version:  2024.9.1

**Comment by AndreasLueck** [comment] 2024-10-08 11:34
I have the same issue: Can't synchronize the Safari Bitwaren Extension, only the Chrome alternative runs smoothly. Same Error in the extension screen "unable to find popup/fonts/bwi-font.svg"

Vaultwarden Web
Version 2024.6.2

![SCR-20241008-mcsd](https://github.com/user-attachments/assets/35a82e5e-6b5c-42c7-9717-d7afa377621c)

**Comment by aldupon** [comment] 2024-10-10 15:27
Same for me Last update by the AppStore on Safari 18.0.1 the window at the opening of BitWarden is empty OSX Sonoma 14.7 The app is working but the error on the Safari extension is: Impossible de trouver « popup/fonts/bwi-font.svg » dans les ressources de l’extension. Impossible to find: popup/fonts/bwi-font.svg  
I'd love to get the older version which was working great ... please!!

**Comment by Expalmi** [comment] 2024-10-16 14:04
Same problem here, OSX Sequoia 15.0.1 Safari 18.0.1 Bitwarden 2024.9.0. The app is working, the extension shows the category's they are empty no items are shown.

**Comment by josemaX** [comment] 2024-10-19 08:42
Same here macOS Sonoma 14.7 + Safari 18.0.1 (18.0 worked fine)

**Comment by sporkman** [comment] 2024-10-23 02:21
> I have the same issue: Can't synchronize the Safari Bitwaren Extension, only the Chrome alternative runs smoothly. Same Error in the extension setup screen "unable to find popup/fonts/bwi-font.svg"
> 
> Vaultwarden Web Version 2024.6.2
> 
> ![SCR-20241008-mcsd](https://private-user-images.githubusercontent.com/49411756/374538268-35a82e5e-6b5c-42c7-9717-d7afa377621c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2NDkxMzUsIm5iZiI6MTcyOTY0ODgzNSwicGF0aCI6Ii80OTQxMTc1Ni8zNzQ1MzgyNjgtMzVhODJlNWUtNmI1Yy00MmM3LTk3MTctZDdhZmEzNzc2MjFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIzVDAyMDAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyZTUwNTM5YTNkMjYwM2UxNTliYmIzMzhlOTJlNmJiNDZiN2YxMjBkZjNjNjc2ZDFhYmM2M2RjZjg4MjkxNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1Qtdenf4yj5qdiyFMj1QA9gOq8Iz_w3I5mwvWJtbnjI)

^^ I started seeing this same issue today (with syncing), tracked it to my update to macOS 14.7 last night, which also bumped Safari to 18.0.1. I *am* a Vaultwarden person, so not sure if I can chime in, but it seems Safari extension specific (I'll test with an actual Bitwarden account if I can). Firefox, Chrome and iOS app syncing all work fine, including signing in and out and doing a full re-sync. I do have a large number of entries (3,000+), perhaps that's a factor.

<img width="387" alt="Screenshot 2024-10-22 at 2 11 18 PM" src="https://github.com/user-attachments/assets/d4cfbe2e-0a6b-459d-b783-2e7e9dcb01fa"> (note that the "last synced" timestamp is incorrect, it has not successfully synced today)

**Comment by archonium-github** [comment] 2024-10-23 04:17
Just to be clear I have no issues with Bitwarden, be it syncing, or using the Safari extension.
I am on MacOS14.7 and using Safari 18.0.1

From my experience in the past, log out and log in again or reinstalling the extension fixes issues with syncing or the extension not showing any entries.

The only issue I have is as posted whereby the extension reports an SVG image is not found.

**Comment by sporkman** [comment] 2024-10-23 04:42
> Just to be clear I have no issues with Bitwarden, be it syncing, or using the Safari extension. I am on MacOS14.7 and using Safari 18.0.1
> 
> From my experience in the past, log out and log in again or reinstalling the extension fixes issues with syncing or the extension not showing any entries.
> 
> The only issue I have is as posted whereby the extension reports an SVG image is not found.

Yeah, I'm looking at @AndreasLueck's reply, as I thought maybe he was drawing a connection between the two issues (could be possible I guess?). I mean it shipped with error output, which is something I've not seen before.

Just for completeness, the sync issue is limited to Safari and only popped up for me when I (manually - don't think apple pushed 18.0.1 as critical) updated the OS and got the new Safari. I don't know if the average mac + safari + bitwarden user even has 18.0.1 yet. I don't know if the error reporting in the extensions prefpane is something new in 18.0.1. I'm just waiting it out for now and troubleshooting with a new vault with fewer entries, trying non self-hosted, etc.

**Comment by trmartin4** [comment] 2024-11-17 00:47
@archonium-github are you still experiencing this error with the Safari extension?  I am not able to reproduce with `2024.11.0` and I wanted to confirm to see if we could close this issue as resolved.

Thank you.

**Comment by aldupon** [comment] 2024-11-17 08:28
Hi to all,
This time it's working, I had to use AppCleaner to uninstall BitWarden on my MacBook Pro M1 Pro running Sonoma 14.7 and Safari Version 18.0.1... the last Bitwarden version taken on the App Store this morning:
<img width="380" alt="Capture d’écran 2024-11-17 à 09 24 04" src="https://github.com/user-attachments/assets/00c1c9d8-18a6-4725-bf4a-1c6318247ac7">

**Comment by archonium-github** [comment] 2024-11-18 02:00
> @archonium-github are you still experiencing this error with the Safari extension? I am not able to reproduce with `2024.11.0` and I wanted to confirm to see if we could close this issue as resolved.
> 
> Thank you.

@trmartin4 I still see the error.

<img width="948" alt="Screenshot 2024-11-18 at 09 58 05" src="https://github.com/user-attachments/assets/7dec4c65-52e2-42e8-b09a-7a57498a42f8">


MacOS 15.1
Safari 18.1
BitWarden Version 2024.10.2 (32149)

**Comment by Expalmi** [comment] 2024-11-18 06:04
I can confirm, I still see the error an my MacBook Pro with M2 Max, Bitwarden 2024.11.0 and Safari 18.0.1

**Comment by AndreasLueck** [comment] 2024-11-18 16:17
Can't confirm: it's working on my system since the new version again. I just did the update and all MAC OS updates... 
Ah! And I did another manual sync (!) in the plugin and then it worked again. 
![SCR-20241118-pdib](https://github.com/user-attachments/assets/ef6801a1-dc01-45f8-b158-91a558b70f30)
![SCR-20241118-pdci](https://github.com/user-attachments/assets/86668b29-11c1-4925-9e65-4e559ee0b51b)

**Comment by archonium-github** [comment] 2024-11-28 03:59
> @archonium-github are you still experiencing this error with the Safari extension? I am not able to reproduce with `2024.11.0` and I wanted to confirm to see if we could close this issue as resolved.
> 
> Thank you.

@trmartin4 I no longer see the error.

<img width="948" alt="Screenshot 2024-11-28 at 11 39 16" src="https://github.com/user-attachments/assets/2229772e-8c36-4101-9d38-e23da12cef68">

**Comment by trmartin4** [comment] 2024-12-10 23:44
Thank you!  We'll close this issue.  Please feel free to report again if the issue reoccurs.

**Closed by trmartin4** 2024-12-10 23:44 UTC
Labels: bug, browser
