### ISSUE TITLE
Bitwarden Version: 2024.7.1 Browser extension for MacOs Firefox  still not rendering correctly Zimbra emails

### ISSUE THREAD

**Issue by CirrusThink** [bitwarden/clients#10412] opened 2024-08-06 11:55 UTC
### Steps To Reproduce

This relates to closed ticket #  #10064 , still happening in Firefox v 128.0.3 for MacOS

### Expected Result

The expectation is that no changes to passkey verifications need to be set in order to use zimbra in firefox while bitwarden is active

### Actual Result

Cannot view email as per # #10064

### Operating System

macOS

### Operating System Version

Sonoma 14.6

### Web Browser

Firefox

### Browser Version

128.0.3

### Build Version

Version: 2024.7.1  Server version Version: 2024.7.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbw23** [comment] 2024-08-06 12:29
Hi there!

Thank you for your report, it seems like it is a duplicate of this one [
](https://github.com/bitwarden/clients/issues/9618)

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Comment by cbw23** [comment] 2024-08-06 12:47
Hi there!

Thank you for your report, it seems like it is a duplicate of this one #9618 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed** 2024-08-06 12:49 UTC
Labels: bug, browser
