### ISSUE TITLE
Master passwords containing a ~ are not working while the password is hidden

### ISSUE THREAD

**Issue by nirbos** [bitwarden/clients#4356] opened 2022-12-30 12:45 UTC
### Steps To Reproduce

0. Have a master password containing a ~
1. Open Bitwarden client
2. Type in your master password while the password is hidden
3. The login fails
4. Click on the show password button
5. The password you typed in does not contain the ~ 
6. Type the ~ while the password is visible
7. The login succeeds 

### Expected Result

The login succeeds the first time while the password containing a ~ is hidden.

### Actual Result

An error prompt appears warning about a wrong password.

### Operating System

macOS

### Operating System Version

12.6.1.

### Installation method

Direct Download (from bitwarden.com)

### Build Version

5788

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2022-12-30 12:53
Hi @nirbos and thank you for your report.

This seems to be a duplicate of https://github.com/bitwarden/clients/issues/2472.

Closing this now.

**Closed by djsmith85** 2022-12-30 12:53 UTC
Labels: bug, desktop
