### ISSUE TITLE
Bw on Ubuntu can't display my safe

### ISSUE THREAD

**Issue by LaLils** [bitwarden/clients#8856] opened 2024-04-22 10:34 UTC
### Steps To Reproduce

1. Open Bitwarden software on Ubuntu 
2. Connect with mail and password (on bitwarden.com)

### Expected Result

It may open my vault and display all my account.

### Actual Result

But it doesn't load the safe

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/108285633/ae3cfe70-5b5c-4480-81e6-c654cd3918a8)

### Additional Context

Before when I want to create a new passwrod I got the message "failed to decode access token: jwt mus have 3 parts" .I saw many similar problems on internet but no solutions operate for me. Si I decide to uninstall and reinstall Bitwarden on my desktop (I know it is not the best solution :sweat_smile: ). Since then I can't acced to my safe with the software

### Operating System

Linux

### Operating System Version

Ubuntu 22.04.4 LTS

### Installation method

Snap

### Build Version

2024.4.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Bcromas** [comment] 2024-04-22 12:50
Same issue for me.

Version 2024.4.0
Shell 28.2.8
Renderer 120.0.6099.291
Node 18.18.2
Architecture x64

Ubuntu 22.04.4 LTS

**Comment by NovaSilentium** [comment] 2024-04-22 13:20
Duplicate of #8651

**Comment by NovaSilentium** [comment] 2024-04-22 13:20
Hi there!

Thank you for your report, it seems like it is a duplicate of this one (https://github.com/bitwarden/clients/issues/8651)

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by NovaSilentium** 2024-04-22 13:21 UTC
Labels: bug, desktop
