### ISSUE TITLE
Ubuntu version will not allow manual sync

### ISSUE THREAD

**Issue by nhlvic** [bitwarden/clients#7402] opened 2023-12-30 18:12 UTC
### Steps To Reproduce

1. Go to File
2. Click on  Sync Vault
3. error message: Syncing Failed

### Expected Result

Successful sync

### Actual Result

Syncing failed

### Screenshots or Videos

![bt_error](https://github.com/bitwarden/clients/assets/155255118/b47b7bee-4c32-4afa-aa03-555e6f601415)

### Additional Context

I had updated my Hotmail password on my Android tablet but the changes were not reflected in the Bitwarden version on my desktop Ubuntu system. 
1. I tried to do a manual sync and got "syncing failed". 
2. I then tried to open the Bitwarden web vault. It opened with no issue and the Android version was in there (the updates were migrated to the vault) but not on my Ubuntu version.
3. I tried to change the existing Hotmail entry on my Ubuntu version and I got an error "The cypher you are trying to update is out of date. Please try to do a manual sync (paraphrased the last sentence)". 
4. I checked the time on my desktop system and my Android system and they were both exactly identical.
5. I then deleted my Hotmail entry in the Ubuntu version and re-entered the correct data.
6. The data I entered in my Ubuntu version had synced both in my Android version and my vault with no issue
7. I then tried a manual sync again which failed again with "syncing failed"

### Operating System

Linux

### Operating System Version

Ubuntu

### Installation method

Snap

### Build Version

Ubuntu 22.04.3 LTS Release:	22.04

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment] 2023-12-31 07:45
Hi @nhlvic,

Thank you for this report. This seems to be a duplicate of [this one](https://github.com/bitwarden/clients/issues/7243) which also relates to the desktop client; For now, please feel free to log out and log back in to refresh your session.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in that thread - our engineering team will be happy to review that material.

This report will now be closed.

Thank you again,

**Closed by SergeantConfused** 2023-12-31 07:45 UTC
Labels: bug, desktop

**Comment by nhlvic** [comment] 2023-12-31 14:45
Not quite the same. I am trying to do the sync through the app, not through a browser extension.

Dec 30, 2023 23:45:52 SergeantConfused ***@***.***>:

Hi @nhlvic<https://github.com/nhlvic>,

Thank you for this report. This seems to be a duplicate of this one<https://github.com/bitwarden/clients/issues/7243> which also relates to the desktop client; For now, please feel free to log out and log back in to refresh your session.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in that thread - our engineering team will be happy to review that material.

This report will now be closed.

Thank you again,
