### ISSUE TITLE
`bw-fido2-page-script` breaks non-html documents

### ISSUE THREAD

**Issue by hjalm8** [bitwarden/clients#8330] opened 2024-03-14 09:26 UTC
### Steps To Reproduce

1. Go to any `.xml` document, [like a sitemap](https://bitwarden.com/sitemap.xml)

### Expected Result

Normal rendering of xml files
![image](https://github.com/bitwarden/clients/assets/31273368/fa851e38-1f4e-43ba-b31f-a1f197ede51d)

### Actual Result

Document is rendered as HTML because a script tag was injected.

![image](https://github.com/bitwarden/clients/assets/31273368/7cfc08bc-e0f8-4986-96fc-a562bc48fb09)

### Additional Context

This also happens on SVG files. While it does not break or change the rendering, it will be included if you download a SVG file by visiting the URL and clicking "Save Page As...". 

[Example with the Bitwarden logo](https://github.com/bitwarden/clients/assets/31273368/6cefd856-cdaf-45ac-a6bb-9922578ef0b5)

### Operating System

Linux

### Operating System Version

Fedora Workstation 39 (GNOME)

### Web Browser

Firefox

### Browser Version

123.0.1 (RPM)

### Build Version

2024.2.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment] 2024-03-14 11:30
Hi there,

I attempted to reproduce your issue and was unable to do so. Does this behaviour happens on other browsers too?

**Comment by cagonzalezcs** [comment] 2024-03-14 13:44
Duplicate of https://github.com/bitwarden/clients/issues/6865

A fix for this issue is currently in review. https://github.com/bitwarden/clients/pull/8214

**Closed as completed by cagonzalezcs** 2024-03-14 13:44 UTC
Labels: bug, browser
