### ISSUE TITLE
Box for Master Password disappears after short time

### ISSUE THREAD

**Issue by Joe-Gee** [bitwarden/clients#6618] opened 2023-10-18 01:08 UTC
### Steps To Reproduce

This is the initial login screen for the Linux version of the desktop client. I don't even have to type, it just disappears after a few seconds.

My laptop config:
System:
  Kernel: 6.2.0-34-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 5.8.4 tk: GTK 3.24.33
    wm: muffin dm: LightDM Distro: Linux Mint 21.2 Victoria base: Ubuntu 22.04 jammy
Machine:
  Type: Laptop System: System76 product: Darter Pro v: darp8 serial: <superuser required> Chassis:
    type: 9 serial: <superuser required>
  Mobo: System76 model: Darter Pro v: darp8 serial: <superuser required> UEFI: coreboot
    v: 2022-11-21_b337ac6 date: 11/14/2022
Battery:
  ID-1: BAT0 charge: 73.8 Wh (99.9%) condition: 73.9/73.9 Wh (100.0%) volts: 8.7 min: 7.7
    model: Notebook BAT serial: <filter> status: Not charging
CPU:
  Info: 12-core (4-mt/8-st) model: 12th Gen Intel Core i7-1260P bits: 64 type: MST AMCP
    arch: Alder Lake rev: 3 cache: L1: 1.1 MiB L2: 9 MiB L3: 18 MiB
  Speed (MHz): avg: 1615 high: 2500 min/max: 400/4700:3400 cores: 1: 520 2: 656 3: 866 4: 2500
    5: 775 6: 2500 7: 827 8: 2500 9: 831 10: 786 11: 580 12: 2500 13: 2500 14: 2500 15: 2500
    16: 2500 bogomips: 79872
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Intel Alder Lake-P Integrated Graphics vendor: CLEVO/KAPOK driver: i915 v: kernel
    ports: active: HDMI-A-1,eDP-1 empty: DP-1, DP-2, DP-3, DP-4 bus-ID: 00:02.0 chip-ID: 8086:46a6
  Device-2: Chicony USB2.0 Camera type: USB driver: uvcvideo bus-ID: 3-7:3 chip-ID: 04f2:b6fb
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: modesetting unloaded: fbdev,vesa
    gpu: i915 display-ID: :0 screens: 1
  Screen-1: 0 s-res: 3840x3240 s-dpi: 96
  Monitor-1: HDMI-1 mapped: HDMI-A-1 pos: primary,top-left model: LG (GoldStar) Ultra HD
    res: 3840x2160 dpi: 163 diag: 690mm (27.2")
  Monitor-2: eDP-1 pos: primary,bottom-r res: 1920x1080 dpi: 142 diag: 395mm (15.5")
  OpenGL: renderer: Mesa Intel Graphics (ADL GT2)
    v: 4.6 Mesa 23.1.3-1pop0~1689084530~22.04~0618746~dev direct render: Yes
Audio:
  Device-1: Intel Alder Lake PCH-P High Definition Audio vendor: CLEVO/KAPOK driver: snd_hda_intel
    v: kernel bus-ID: 00:1f.3 chip-ID: 8086:51c8
  Sound Server-1: ALSA v: k6.2.0-34-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Intel Alder Lake-P PCH CNVi WiFi driver: iwlwifi v: kernel bus-ID: 00:14.3
    chip-ID: 8086:51f0
  IF: wlp0s20f3 state: up mac: <filter>
  Device-2: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: CLEVO/KAPOK
    driver: r8169 v: kernel pcie: speed: 2.5 GT/s lanes: 1 port: 4000 bus-ID: 2e:00.0
    chip-ID: 10ec:8168
  IF: enp46s0 state: down mac: <filter>
  IF-ID-1: wgpia0 state: unknown speed: N/A duplex: N/A mac: N/A
Bluetooth:
  Device-1: Intel AX201 Bluetooth type: USB driver: btusb v: 0.8 bus-ID: 3-10:4 chip-ID: 8087:0026
  Report: hciconfig ID: hci0 rfk-id: 0 state: up address: <filter> bt-v: 3.0 lmp-v: 5.2
    sub-v: 35fc
RAID:
  Device-1: bpool type: zfs status: ONLINE level: linear raw: size: 1.88 GiB free: 1.32 GiB
    zfs-fs: size: 1.75 GiB free: 1.19 GiB
  Components: Online: N/A
  Device-2: rpool type: zfs status: ONLINE level: linear raw: size: 1.81 TiB free: 1.76 TiB
    zfs-fs: size: 1.76 TiB free: 1.71 TiB
  Components: Online: N/A
Drives:
  Local Storage: total: raw: 3.66 TiB usable: 5.42 TiB used: 73.43 GiB (1.3%)
  ID-1: /dev/nvme0n1 vendor: Samsung model: SSD 980 PRO 2TB size: 1.82 TiB speed: 63.2 Gb/s
    lanes: 4 serial: <filter> temp: 35.9 C
  ID-2: /dev/nvme1n1 vendor: Intel model: SSDPEKNW010T9 size: 953.87 GiB speed: 31.6 Gb/s
    lanes: 4 serial: <filter> temp: 29.9 C
  ID-3: /dev/sda type: USB vendor: SanDisk model: Extreme Portable SSD size: 931.51 GiB
    serial: <filter>
Partition:
  ID-1: / size: 1.72 TiB used: 8.66 GiB (0.5%) fs: zfs logical: rpool/ROOT/ubuntu_z765u7
  ID-2: /boot size: 1.75 GiB used: 568.2 MiB (31.7%) fs: zfs logical: bpool/BOOT/ubuntu_z765u7
  ID-3: /boot/efi size: 511 MiB used: 14.3 MiB (2.8%) fs: vfat dev: /dev/nvme0n1p1
  ID-4: /var/log size: 1.71 TiB used: 37.8 MiB (0.0%) fs: zfs
    logical: rpool/ROOT/ubuntu_z765u7/var/log
Swap:
  ID-1: swap-1 type: partition size: 2 GiB used: 0 KiB (0.0%) priority: -2 dev: /dev/dm-1
    mapped: cryptoswap
Sensors:
  System Temperatures: cpu: 74.0 C mobo: N/A
  Fan Speeds (RPM): cpu: 0
Repos:
  Packages: 2422 apt: 2364 flatpak: 50 snap: 8
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb https: //mirrors.advancedhosters.com/linuxmint/packages victoria main upstream import backport
    2: deb http: //mirrors.advancedhosters.com/ubuntu jammy main restricted universe multiverse
    3: deb http: //mirrors.advancedhosters.com/ubuntu jammy-updates main restricted universe multiverse
    4: deb http: //mirrors.advancedhosters.com/ubuntu jammy-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
  Active apt repos in: /etc/apt/sources.list.d/system76-dev-stable-jammy.list
    1: deb [signed-by=/etc/apt/keyrings/system76-dev-stable-jammy.gpg] https: //ppa.launchpadcontent.net/system76-dev/stable/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/vivaldi.list
    1: deb [arch=amd64] https: //repo.vivaldi.com/stable/deb/ stable main
Info:
  Processes: 611 Uptime: 28m Memory: 62.64 GiB used: 7.63 GiB (12.2%) Init: systemd v: 249
  runlevel: 5 Compilers: gcc: 11.4.0 alt: 11/12 Client: Cinnamon v: 5.8.4 inxi: 3.3.13

### Expected Result

Expected the login window to wait for me to type my passcode

### Actual Result

The login window disappeared after a few seconds

### Screenshots or Videos

![Screenshot from 2023-10-17 20-59-02](https://github.com/bitwarden/clients/assets/148295759/f37f649e-761c-4532-a6cd-e443585e0510)
![Screenshot from 2023-10-17 20-53-37](https://github.com/bitwarden/clients/assets/148295759/43260e32-b212-4246-b8ef-b15348ea22dc)

### Operating System

Linux

### Operating System Version

Linux Mint 21.2 Victoria base: Ubuntu 22.04 jammy

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2023.9.2 Shell 26.3.0 Renderer 116.0.5845.228 Node 18.16.1 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2023-10-18 01:25
Hi @Joe-Gee,

Thank you for your report, it seems like it is a duplicate of this one: #6560

The issue has been addressed and fix with the release of 2023.9.3

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2023-10-18 01:25 UTC
Labels: bug, desktop
