### ISSUE TITLE
Generated password not updated after saving

### ISSUE THREAD

**Issue by jogarbe** [bitwarden/clients#12282] opened 2024-12-07 13:55 UTC
### Steps To Reproduce

1. "Add item" in Windows GUI
2. Generate a new password
3. Save the item
4. Choose "toggle visibility" to view the password
5. Press "edit"
6. Press "generate password"
7. Toggle visibility to see the new password
8. Save
9. Toggle visibility -- the old password is shown, when you copy the password, the old password is copied

### Expected Result

After saving a newly generated password the new password is shown and copied

### Actual Result

The previously generated password (even it was not saved at all) is shown/copied

### Operating System

Windows

### Operating System Version

Windows 11 23H2, build 22631.4541

### Installation method

Microsoft Store

### Build Version

2024.11.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment] 2024-12-07 16:47
Hello @jogarbe,

Thank you for your report. This report seems to be a duplicate of this [GitHub report](https://github.com/bitwarden/clients/issues/12022); If there's anything you'd like to add, such as screenshots or video recordings of the screen, please feel free to add them to that existing GitHub report so that they'd be reviewed by the Bitwarden Engineering department.

This report will now be closed as a duplicate.

Thank you again,

**Closed by SergeantConfused** 2024-12-07 16:47 UTC
Labels: bug, desktop
