### ISSUE TITLE
LMDE5 Bitwarden problem

### ISSUE THREAD

**Issue by MicronDiY** [bitwarden/clients#6979] opened 2023-11-27 17:46 UTC
### Steps To Reproduce

1. Go to Bitwarden start up
2. Flat Hub Bitwarden App is dead!

### Expected Result

Most menus are greyed out, nothing works, no data, no login
the App is dead. 

### Actual Result

Doesn't work

### Operating System

Linux

### Operating System Version

LMDE5

### Installation method

Other

### Build Version

2023.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment] 2023-11-30 13:08
Hi there,

This is a duplicate of https://github.com/bitwarden/clients/issues/6732. Flatpak is maintained by the community, not Bitwarden. You can use the official .AppImage installer from the [Bitwarden website](https://bitwarden.com/download/) or from our [repository ](https://github.com/bitwarden/clients/releases). 

This issue will now be closed.

Thanks!

**Closed by Greenderella** 2023-11-30 13:08 UTC
Labels: bug, desktop
