### ISSUE TITLE
"i is undefined" when trying to log in to Firefox extension

### ISSUE THREAD

**Issue by SammyTheBEAST** [bitwarden/clients#4067] opened 2022-11-16 16:38 UTC
### Steps To Reproduce

1. Install Firefox extension
2. Log in and remember 2FA
3. Wait a couple of days
4. Log out of Bitwarden
5. Click on "Log In"
6. Enter valid credentials
7. Click on "Log In"

### Expected Result

2FA prompt is shown or Bitwarden vault opens.

### Actual Result

An error occurs that states "i is undefined".

### Screenshots or Videos

https://imgur.com/a/2yTpTbO

### Additional Context

- Uninstalling and reinstalling the extension fixes the issue temporarily.
- It has only appeared when I restart my PC or update my browser, causing Bitwarden to log itself out.
- I have 2FA enabled, the error comes before it asks for 2FA. I have Bitwarden remember my 2FA, it could be an issue with loading the 2FA session? It usually happens after a long time of it working, it may only be happening when the 2FA session expires.
- If I enter incorrect credentials, it gives me the "credential are incorrect" error instead of "i is undefined".

### Operating System

Windows

### Operating System Version

19044.2251

### Web Browser

Firefox

### Browser Version

106.0.5

### Build Version

2022.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by kintaro1981** [comment] 2023-03-01 13:03
I have the same issue (latest firefox 110.0 64bit on macos 10.14)

many others too here: https://www.reddit.com/r/Bitwarden/comments/xb73kd/cant_log_in_to_firefox_plugin_error_i_is_undefined/

**Comment by paxter** [comment] 2023-03-10 16:41
Same issue.

**Comment by dfwdraco76** [comment] 2023-04-27 21:43
I have the same issue on a Linux Mint 21.1 Cinnamon laptop, FF 112.0.2, Bitwarden extension 2023.3.1

**Comment by blaxoid** [comment] 2023-04-28 02:20
Same issue

Windows 11 22H2 22621.1555
FF 112.02
Extension version 2023.3.1

**Comment by djsmith85** [comment] 2023-04-28 08:53
Duplicate of #4076

**Closed by djsmith85** 2023-04-28 08:53 UTC
Labels: bug, browser
