### ISSUE TITLE
"Clear clipboard"option does not work under wayland

### ISSUE THREAD

**Issue by isingasimplesong** [bitwarden/clients#10855] opened 2024-09-02 14:25 UTC
### Steps To Reproduce

1. Go to "Setting > preferences"
2. Set "Clear clipboard" to any value
3. Clipboard is never cleared

### Expected Result

Clipboard should be cleared

### Actual Result

![image](https://github.com/user-attachments/assets/399903ae-07ec-4de4-8c8c-14c9971db71c)
10, 7 and 6 are copied from Bitwarden (desktop + browser extension)

### Operating System

Linux

### Operating System Version

up to date archlinux, operating under wayland

### Installation method

Other

### Build Version

24.8.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-09-02 14:48
Likely related/duplicate of https://github.com/bitwarden/clients/issues/1047 or https://github.com/bitwarden/clients/issues/2633

**Comment by trmartin4** [comment] 2024-09-23 22:30
@isingasimplesong could you clarify the issue a bit for us?  You reference the "Clear clipboard" functionality, which sets an empty value to the clipboard after a configured duration.  That is separate from interfacing with clipboard managers, which you appear to be using from the screenshot.

Can you confirm that the issue is related to a clipboard manager that you are using?  If so, we would like to change the title of this ticket and classify it as a duplicate of #1047 , as this is where we are tracking support for the necessary APIs to support that on Linux.

**Comment by isingasimplesong** [comment] 2024-09-24 22:40
yes, sorry for the lack of clarity. That screenshot was for illustration, and not very relevant.

In the desktop app, the option to clear clipboard is set to 2 min. But whether that i use a clipboard manager or not, my system clipboard is not cleared. I run cliphist (https://github.com/sentriz/cliphist) but as far as i understand that shouldn't be the issue here

**Comment by dani-garcia** [comment] 2024-10-28 14:56
I tried to check this issue and I can't reproduce it, the value is correctly cleared from clipboard, even if the value stays in history (which is issue #1047). It might be good to know which desktop environment you're using to cause this.

To try to reproduce it I've:
- Installed latest Bitwarden desktop in Kubuntu 22.04 using Wayland
- Configured clear clipboard to 10 seconds and copied a password using the copy button
- Saw that I could immediately paste the value with Ctrl+V in other apps
- Waited ten seconds and saw that trying to paste with Ctrl+V won't work

If after the 10 seconds pass I press Win+V to open the KDE native clipboard history, I can see the password still there. This is issue #1047. 

Note also that the clipboard values only get cleared when using the copy button, if you select the text and use Ctrl+C manually then they won't be cleared (#5857)

**Comment by isingasimplesong** [comment] 2024-10-28 15:13
I use [hyprland](https://hyprland.org/), it works now! Not completely sure if my tests where not accurate or if a recent update in hyprland fixed it, but.. i works.

`❯ wl-paste; sleep 31 && echo "after 31 seconds: " && wl-paste
copied-password-from-bitwarden-desktop-as-a-test-again
after 31 seconds:

`

**Comment by dani-garcia** [comment] 2024-10-30 13:41
Nice! I think this issue can be closed then, we'll track the clipboard history not being cleared in #1047.

Thanks for your help!

**Closed by dani-garcia** 2024-10-30 13:41 UTC
Labels: bug, desktop
