### ISSUE TITLE
The window is no longer resizable (Flatpak, Linux)

### ISSUE THREAD

**Issue by Odi-3** [bitwarden/clients#11404] opened 2024-10-04 10:00 UTC
### Steps To Reproduce

1. Open Bitwarden Linux Flatpak client
2. Make sure the window is not maximized
3. Try resizing the window

### Expected Result

The window should be resizable like all the others.

### Actual Result

The resizing cursor does not appear, neither at the corners nor at the edges. Also the title bar is not clickable at all points for dragging the window (it is likely that the two issues are related).

### Operating System

Linux

### Operating System Version

Fedora 40, GNOME 46, Linux 6.10.11

### Installation method

Other

### Build Version

2024.9.0 (Flatpak from Flathub)

### Issue Tracking Info

- [ ] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment] 2024-10-04 10:36
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by deliarmin** [comment] 2024-10-07 06:47
Same issue here.
Fedora 40, GNOME 46, Wayland, Linux 6.10.12

**Comment by myhops** [comment] 2024-10-09 07:36
I have this problem too on Pop!_OS 22.04 LTS, 64 bit, Gnome version 42.9

**Comment by LSeelig** [comment] 2024-10-12 20:47
I have this with RPM

**Comment by bhibb** [comment] 2024-10-16 21:56
I am experiencing this issue for the last two weeks with my flatpak installation of Bitwarden.

**Comment by ocosta** [comment] 2024-11-01 19:38
Problem manifests also on Fedora 41 with GNOME 47 on Wayland.

For the record, `mutter`'s changelog for version 47 shows this:
```
* Fix resizing of electron windows [Jonas; !3997]
```

**Comment by LSeelig** [comment] 2024-11-04 19:20
It is working again.

**Comment by ocosta** [comment] 2024-11-04 19:46
Flatpak version (2024.9.0 , many versions behind latest stable) still can't resize the window. I installed their own RPM (2024.10.2), and it works again. The downside of using their RPM is that they don't provide a proper RPM repository, so I'll have to update manually from time to time (it's the same with Slack :roll_eyes: )

**Comment by Slummz** [comment] 2024-11-06 21:15
Having the same issue on Fedora 41.26 (Gnome 47.1, Muter & Wayland) as of 2024-11-06.

Bitwarden version (Flatpak)
Version 2024.9.0
Shell 32.0.1
Renderer 128.0.6613.36
Node 20.16.0
Architecture x64

**Comment by amadeusp** [comment] 2024-11-14 05:56
I have the same issue with Bitwarden Flatpak
```
Version 2024.9.0
Shell 32.0.1
Renderer 128.0.6613.36
Node 20.16.0
Architecture x64
```
on Manjaro Linux GNOME 46.5 (Wayland).

**Comment by dasunsrule32** [comment] 2024-11-19 16:34
Issue exists on Ubuntu 24.04 using the flatpak version.
```
Version 2024.11.1
Shell 32.1.1
Renderer 128.0.6613.137
Node 20.17.0
Architecture x64
```

**Comment by quexten** [comment] 2024-12-03 22:03
This seems to be the same bug that is blocking https://github.com/bitwarden/clients/pull/10359. Upstream electron has a bug that prevents resizing on wayland, and the flatpak manifest enabled wayland (whereas the upstream clients don't yet).

In a few minutes, flathub bot should provide a testable build on this PR: https://github.com/flathub/com.bitwarden.desktop/pull/231

Anyone experiencing this issue, please give it a try and see if it fixes it for you.

**Comment by amadeusp** [comment] 2024-12-04 02:12
@quexten The testable build mentioned in your post above does work for me. Should I work with this build for the time being or should I go back to the stable build and wait for an official update to roll out? Many thanks!

**Comment by quexten** [comment] 2024-12-04 09:39
The change is merged for the flathub manifest so it should roll out as soon as flathub reviewers approve the change to the permissions (removing wayland).

**Closed as completed** 2024-12-05 11:05 UTC
Labels: bug, desktop
