### ISSUE TITLE
Bitwarden-cli list items issue

### ISSUE THREAD

**Issue by fgprodigal** [bitwarden/clients#7200] opened 2023-12-13 04:56 UTC
### Steps To Reproduce

```
bw list items
```

### Expected Result

list all items without errors

### Actual Result

 list all items, and then hangs for few seconds with an error comes out:
```
Error: Lock file is already being held
    at /snapshot/clients/node_modules/proper-lockfile/lib/lockfile.js:68:47
    at callback (/snapshot/clients/node_modules/graceful-fs/polyfills.js:306:20)
    at FSReqCallback.oncomplete (node:fs:212:5) {
  code: 'ELOCKED',
  file: '/Users/ray/Library/Application Support/Bitwarden CLI/data.json'
}
```

### Operating System

macOS

### Operating System Version

Sonoma 14.2

### Shell

Zsh

### Build Version

2023.12.0

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by stefanfluit-robin** [comment] 2023-12-13 09:20
We unfortunately have the same issue, breaking production atm. If any logs help, let me know.

**Comment by djsmith85** [comment] 2023-12-13 10:28
Duplicate of https://github.com/bitwarden/clients/issues/7126

**Comment by djsmith85** [comment] 2023-12-13 10:29
Hi @fgprodigal and @stefanfluit-robin,

thank you for your reports. This seems to have been reported with https://github.com/bitwarden/clients/issues/7126 and there's a potential fix by a community member with https://github.com/bitwarden/clients/pull/7133

Closing this now. 

Kind regards,
Daniel

**Closed by djsmith85** 2023-12-13 10:29 UTC
Labels: bug, cli
