### ISSUE TITLE
Send link doesn't work

### ISSUE THREAD

**Issue by DCA318** [bitwarden/clients#5105] opened 2023-03-29 14:30 UTC
### Steps To Reproduce

1. Go to Send in Firefox-Extention
2. Create a send and copy link after saving
3. Paste in Browser to access send

### Expected Result

Send should pop up on site

### Actual Result

Login-prompt pops up and adress bar shows "https://vault.bitwarden.com/#/login"

### Screenshots or Videos

![Screenshot 2023-03-29 162630](https://user-images.githubusercontent.com/32304205/228570692-1e312c4b-a08f-434c-a630-5cc3d2d7ffd9.png)

### Operating System

Windows

### Operating System Version

10.0.19045 Build 19045

### Web Browser

Firefox

### Build Version

111.0.1 (64-Bit)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment] 2023-03-29 14:38
Hi @DCA318 !

Thank you for your report, it seems like it is a duplicate of this one:

https://github.com/bitwarden/clients/issues/5037 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by atjbramley** 2023-03-29 14:38 UTC
Labels: bug, browser
