### ISSUE TITLE
Firefox Extension keeps logging me out

### ISSUE THREAD

**Issue by hausler89** [bitwarden/clients#9066] opened 2024-05-07 09:31 UTC
### Steps To Reproduce

The Firefox extension keeps logging me out within roughly 1 day. This happens on Windows and Mac.

I can set a PIN as an unlocking method, and when I uncheck the box for "Require Master Password after Browser Restart," everything works for a while.

I can restart my browser, and I can also restart my OS, and I can always log in with the set PIN.

However, after roughly 1 day, I'm logged out of the extension and must enter my mail and my master password. What's even worse is that I have to set the PIN manually again, which is extremely irritating.

Previously, the Pin setup was stable for weeks and months, and Bitwarden wouldn't bother me. Now, it's tedious to use because of the constant logging out.

I've tried reinstalling the extension to no avail.

I don't see the problem with the mobile iOS app, nor with the Desktop app.

Another thing that I've noticed is that the extension doesn't ask me for my second factor after logging me out. So it's retaining some data from the previous login.

### Expected Result

Doesn't log me out.

### Actual Result

Logs me out.

### Operating System

Windows, macOS

### Operating System Version

Windows 11, Sonoma

### Web Browser

Firefox

### Browser Version

125.0.3

### Build Version

2024.4.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment] 2024-05-07 09:58
Duplicate of #8873

**Comment by NovaSilentium** [comment] 2024-05-07 09:59
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/8873

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed** 2024-05-07 09:59 UTC
Labels: bug, browser
