### ISSUE TITLE
Firefox "show autofill menu on form fields" set to off not honored

### ISSUE THREAD

**Issue by mil1i** [bitwarden/clients#11498] opened 2024-10-11 03:09 UTC
### Steps To Reproduce

1. In a Firefox Browser, go to Bitwarden Extension Settings > Autofill
2. Set "Show autofill menu on form fields" to off
3. Go to page with login field
4. Click on field

### Expected Result

No drop-down menu of available logins should expand, nor should there be the bitwarden icon inside in the form.

### Actual Result

Both the icon and the drop-down of all available logins to choose from are present.

### Additional Context

This only occurs in Firefox for me. Does not happen with Chromium based browsers.

### Operating System

Windows, macOS

### Operating System Version

macOS 15, Windows 11

### Web Browser

Firefox

### Browser Version

Firefox 131.0.x

### Build Version

2024.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by BBGhub** [comment] 2024-10-11 03:15
Hi there!

Thank you for your report, it seems like it is a duplicate of this onehttps://github.com/bitwarden/clients/issues/10814

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

**Closed by BBGhub** 2024-10-11 03:15 UTC
Labels: bug, browser

**Comment by FlorianLang06** [comment] 2024-10-14 19:42
@BBGhub this issue isn't a duplicate. The other issue was about the autofill not working. But in this case the context menu works, but if the setting is set to "off" the context menu + the icon still shows up. Can you please reopen this issue
