### ISSUE TITLE
Login success but vault sync failed with version >2024.3.0 on Windows 11

### ISSUE THREAD

**Issue by ayalys** [bitwarden/clients#8991] opened 2024-04-30 17:25 UTC
### Steps To Reproduce

Just login and then the vault appears empty and force sync failed.

### Expected Result

A vault full of logins/passwords !

### Actual Result

After updating the app on my computer (Windows 11) it failed to sync with my auto-hosted Vaultwarden (on a Synology server).
Apps on my tablet, phone and navigators plugins all worked. The last desktop app version worked on my professionnal PC with Windows 10 but it remains failing on my personnal computer.
I checked all version (including portables versions) until I notice it works again with v2024.3.0 and lower desktop app. So currently I stay on this version.

In all versions, the login step works well but with versions >2024.3.0 on Windows 11, once logged in, it fails to sync the vault. When I force the sync I got the message "Sync vault failed" (approx).

I checked the windows events center and firewall and didn't saw any abnormal facts.

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.4.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by tamastimar** [comment] 2024-05-01 15:12
Possible duplicate of #8651?

**Comment by bvwidt** [comment] 2024-05-02 06:04
More a duplicate of #8673 as that targets Windows.

**Comment by Greenderella** [comment] 2024-05-02 08:40
Hi there,

It is important to note that vaultwarden is not associated with Bitwarden.

Vaultwarden is a re-writing of the Bitwarden server code in Rust, that is not contributed to or supported by the Bitwarden team or organization. The security audits granted to Bitwarden do not apply to vaultwarden, and the Bitwarden support team is not able to respond to questions regarding vaultwarden.

Bitwarden also offers a self-hosted option, which many of our customers run in an air-gapped environment.  You can find information on this here:
- https://bitwarden.com/help/install-on-premise-linux/ 
- https://bitwarden.com/help/install-and-deploy-offline/ 

I hope you find this helpful. Please do not hesitate to let me know if you have any questions.

**Closed by Greenderella** 2024-05-02 08:40 UTC
Labels: bug, desktop
