### ISSUE TITLE
Do not show "Log in with Device" when SSO is required

### ISSUE THREAD

**Issue by KramNamez** [bitwarden/clients#11891] opened 2024-11-07 10:26 UTC
### Steps To Reproduce

Both "Log in with device" and Trusted Devices use the same known devices, leading to bad UX.

Both of these use the Devices API, mixing the log in information and the decryption information, despite not being the same thing and not being mutually compatible.

As seen here: https://github.com/bitwarden/clients/blob/f5e6fc8ed5a4756d7866ae05118ff795ec68a374/libs/angular/src/auth/components/login-v1.component.ts#L394 

The login option is shown as log as there is a known device - even if that device is used for TDE, which requires SSO and therefore _disables_ the login option. Instead, the login option should be shown _if and only if_ there is a device and the Require SSO policy is NOT set.

### Expected Result

As I have "Require SSO" set, my users should never be prompted to "log in with device".

### Actual Result

Once there is a Trusted Device, the "log in with device" option is shown on every login attempt. It silently fails to work, as it cannot work.

### Operating System

Windows, macOS, Linux, Android, iOS

### Web Browser

Chrome, Firefox

### Build Version

2024.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment] 2024-11-07 14:56
Duplicate of #1863

**Comment by NovaSilentium** [comment] 2024-11-07 14:57
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/11863

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed** 2024-11-07 14:57 UTC
Labels: bug, web

**Comment by KramNamez** [comment] 2024-11-07 15:44
Yes, but I was hoping that this time, someone would read it and respond to the actual content instead of a made-up version of the content.

**Comment by KramNamez** [comment] 2024-11-07 15:47
Unless of course you're telling me that it is intended behavior to confuse users and present them with non-functional UI.

**Comment by trmartin4** [comment] 2024-11-08 02:01
@KramNamez, thank you for providing this feedback.

You are correct that users cannot use Login with Device to log in if you have "Require SSO" policy enabled (which you would with Trusted Devices).  However, it does not silently fail to work.  If the login request is approved on another device, the requesting device receives an error toast indicating that SSO login is required, which is the intended behavior.
![image](https://github.com/user-attachments/assets/f56faa87-a21c-43b5-a19d-8fdbf634c2ba)

It is possible that we could infer that a device being trusted for a given user implies that they are a member of an org with "Require SSO" enabled, and thus cannot use Login with Device.  This would require additional testing to ensure that there are no edge cases that might falsely disable the feature, especially around the off-boarding from TDE (i.e. changing from Trusted Devices to Master Password as your decryption option).

I will take this up with our product team to see if this is something we'd like to move forward with adding at some point.

Thank you again for the suggestion.

**Comment by KramNamez** [comment] 2024-11-08 07:41
That does not happen for us. It just sits there and gives no indication of why it didn't work. Eventually "Resend Notification" shows up. But no notification ever shows up on another device.

**Comment by KramNamez** [comment] 2024-11-08 07:59
[Bitwarden-No-Toast.webm](https://github.com/user-attachments/assets/a5e4e901-3628-4cba-ae6f-0322c423d90e)

You're gonna have to trust me that I clicked on the notification both times, but you can see, no toast. Nothing. On my Pixel 6 Pro, Android 14, I received a notification each time and got the "Login Confirmed" toast.

**Comment by trmartin4** [comment] 2024-11-14 15:41
@KramNamez thank you for the feedback!  We have decided to implement this feature and have put the work on our backlog.  We also have some changes to how the SSO login option is presented with an upcoming UI update that should also make this a bit clearer.

**Comment by KramNamez** [comment] 2024-11-14 19:34
Thank you! That's great to hear.
