### ISSUE TITLE
Browser Extension doesn't detect input fields if opened before page is fully loaded

### ISSUE THREAD

**Issue by ArgonGlow** [bitwarden/clients#5633] opened 2023-06-19 10:11 UTC
### Steps To Reproduce

1. Navigate to a login page with input fields, for which you have a stored login
2. Click on the Bitwarden extension icon in the browser, while the page is still loading
3. Click a stored login item from the list

### Expected Result

My login credentials are auto-filled in the login page's input fields.

### Actual Result

My login credentials are not auto-filled, and the Bitwarden extension displays the following error:
Unable to auto-fill the selected item on this page. Copy and paste the information instead.

### Additional Context

I would hazard a guess that the extension checks for input fields when it is activated, causing the mentioned behaviour when visiting a slow loading login page. If this is the case then having the extension check for input fields when a login is clicked/selected to be auto-filled might solve the issue.

### Operating System

macOS

### Operating System Version

13.4

### Web Browser

Chrome

### Browser Version

114.0.5735.133

### Build Version

2023.5.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2023-06-27 09:28
Duplicate of https://github.com/bitwarden/clients/issues/488

**Closed by djsmith85** 2023-06-27 09:28 UTC
Labels: bug, browser, intended-behavior
