### ISSUE TITLE
[REGRESSION] Uploading Attachments or Send Files via CLI v2023.5.0 or newer fails

### ISSUE THREAD

**Issue by BlackDex** [bitwarden/clients#5876] opened 2023-07-22 15:18 UTC
### Steps To Reproduce

1. Install a Self-Hosted environment (I tested using v2023.7.0)
2. Create an account which is able to upload attachments or Send Files
3. Create a cipher
4. Try to upload an attachment to it using either CLI v2023.5.0 or higher (tested both v2023.5.0 and v2023.7.0)

### Expected Result

Attachment/File is uploaded.

### Actual Result

An error messages gets displayed `An unhandled server error has occurred.`

### Additional Context

The issue seems to be the update to v18 of Node. If i compile v2023.5.0 or v2023.7.0 with v16 of Node they work just fine.
A similar issues like this got triggered in the past at Arch Linux, where they were using the latest version of Node for a while already. This broke upload too. After they changed it back to v16 of Node it all started working again.

I'm no Node dev, but probably something has changed in either Node 18, or the way the libraries interact with it.

I also tried to use the pre-build version available on GitHub, but they show the same issues, except for v2023.4.0.

v2023.4.0:
Response from POST to `/ciphers/<cipher-id>/attachment/v2`
```
{"key":"2.Y2U...","fileName":"2.W4/qzzyusQbE8aDOdwr2bw==|+TvRHmTcCHz6nZxKd8kC6g==|pCwPvunx450SvNUGjP1AP7zcWwxtwSev6kBvph1ElNg=","fileSize":65,"adminRequest":false}
```

POST to `../attachment/file-id`
```
Device-Type: 8
User-Agent: Bitwarden_CLI/2023.4.0 (LINUX)
Content-Type: multipart/form-data;boundary=--------------------------008061237489075735152341
Bitwarden-Client-Name: cli
Bitwarden-Client-Version: 2023.4.0
Accept: */*
Accept-Encoding: gzip,deflate

----------------------------008061237489075735152341
Content-Disposition: form-data; name="data"; filename="2.W4/qzzyusQbE8aDOdwr2bw==|+TvRHmTcCHz6nZxKd8kC6g==|pCwPvunx450SvNUGjP1AP7zcWwxtwSev6kBvph1ElNg="
Content-Type: application/octet-stream

.)..).v......3.C..[.......tQ%.....3.6..4...%.z.'.. XW.p..!.#...1.
----------------------------008061237489075735152341--

HTTP/1.1 200 OK
```

v2023.5.0:
Response from POST to `/ciphers/<cipher-id>/attachment/v2`
```
{"key":"2.LAg...","fileName":"2.uUbS/yclTzgvVmvHLxtE5w==|BoHEetW/TXCaRCliONHjyw==|S98wgJvFMpJEh30fThGzxErTosuTG2bMTMadTb/DjT8=","fileSize":65,"adminRequest":false}
```

POST to `../attachment/file-id` (And no, the `Conten` just before the 500 is not a typo or copy/paste error)
```
Device-Type: 8
User-Agent: Bitwarden_CLI/2023.5.0 (LINUX)
Content-Type: multipart/form-data;boundary=--------------------------063325875256692998973141
Bitwarden-Client-Name: cli
Bitwarden-Client-Version: 2023.5.0
Accept: */*
Accept-Encoding: gzip,deflate

----------------------------063325875256692998973141
Content-Disposition: form-data; name="data"; filename="DjT8="
Content-Type: application/octet-stream

----------------------------063325875256692998973141
Content-Disposition: form-data; name="data"; filename="2.uUbS/yclTzgvVmvHLxtE5w==|BoHEetW/TXCaRCliONHjyw==|S98wgJvFMpJEh30fThGzxErTosuTG2bMTMadTb/DjT8="
Conten
HTTP/1.1 500 Internal Server Error
```

### Operating System

Linux

### Operating System Version

Arch Linux

### Shell

Bash

### Build Version

2023.5.0 and 2023.7.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jchristensen-bw** [comment] 2023-07-25 21:21
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by djsmith85** [comment] 2023-07-26 09:40
Duplicate of https://github.com/bitwarden/clients/issues/5618

**Comment by djsmith85** [comment] 2023-07-26 09:41
@BlackDex Thanks for the additional context

**Closed by djsmith85** 2023-07-26 09:41 UTC
Labels: bug, cli

**Comment by MGibson1** [comment] 2023-07-26 12:56
@BlackDex @jchristensen-bw, are you able to correlate with a server error? The 500 suggests that there should be some more context there.

**Comment by BlackDex** [comment] 2023-07-26 14:20
@MGibson1 i have.

```
[26/Jul/2023:14:14:03 +0000] "POST /api/ciphers/<cipher-uuid>/attachment/v2 HTTP/1.1" 200 2638 "-" "Bitwarden_CLI/2023.7.0 (LINUX)"

==> api/Api/20230726.txt <==
2023-07-26 14:14:04.571 +00:00 [Error] Unexpected end of Stream, the content may have already been read by another component. 
System.IO.IOException: Unexpected end of Stream, the content may have already been read by another component. 
   at Microsoft.AspNetCore.WebUtilities.MultipartReaderStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Stream.<CopyToAsync>g__Core|29_0(Stream source, Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
   at Bit.Core.Vault.Services.LocalAttachmentStorageService.UploadNewAttachmentAsync(Stream stream, Cipher cipher, MetaData attachmentData)
   at Bit.Core.Vault.Services.CipherService.UploadFileForExistingAttachmentAsync(Stream stream, Cipher cipher, MetaData attachment)
   at Bit.Api.Vault.Controllers.CiphersController.<>c__DisplayClass40_0.<<PostFileForExistingAttachment>b__0>d.MoveNext() in /home/runner/work/server/server/src/Api/Vault/Controllers/CiphersController.cs:line 620
--- End of stack trace from previous location ---
   at Bit.Api.Utilities.MultipartFormDataHelper.GetFileAsync(HttpRequest request, Func`2 callback) in /home/runner/work/server/server/src/Api/Utilities/MultipartFormDataHelper.cs:line 114
   at Bit.Api.Vault.Controllers.CiphersController.PostFileForExistingAttachment(String id, String attachmentId) in /home/runner/work/server/server/src/Api/Vault/Controllers/CiphersController.cs:line 618
   at lambda_method55(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

==> nginx/access.log <==
[26/Jul/2023:14:14:04 +0000] "POST /api/ciphers/<cipher-uuid>/attachment/<attachment-id> HTTP/1.1" 500 185 "-" "Bitwarden_CLI/2023.7.0 (LINUX)"
[26/Jul/2023:14:14:05 +0000] "DELETE /api/ciphers/<cipher-uuid>/attachment/<attachment-id> HTTP/1.1" 200 0 "-" "Bitwarden_CLI/2023.7.0 (LINUX)"
```

**Comment by BlackDex** [comment] 2023-07-26 14:45
But, keep in mind that when the CLI v2023.7.0 is build with Node v16, this issue does not occur.
The problem is, that the CLI doesn't send the data anymore. And looking at the code of the server, that is exactly where it fails and produces the 500 error.

**Comment by rbreunung** [comment] 2024-05-20 21:48
Will there please be a solution to the issue? This is also providing inconvenience to me ...
