### ISSUE TITLE
Chrome Ext: Ask to add/update login breaks layout of many websites

### ISSUE THREAD

**Issue by simeydk** [bitwarden/clients#5562] opened 2023-06-05 06:51 UTC
### Steps To Reproduce

1. Do this on a website where its UI relies on the site's own HTML elements taking up 100% of the viewport height
1. Perform an action that makes the "Should Bitwarden remember/update this password for you" popup appear
2. Website's layout breaks because of the bitwarden bar

### Expected Result

Bitwarden bar appears over top of the rest of the website.

And/or Bitwarden gives me the option to choose between a popup that injects into the flow of the page or a absolutely positioned "over the top" popup that sits on top of the page. 

### Actual Result

Bitwarden bar shifts the website layout down, breaking the layout for many websites.

### Operating System

Windows

### Web Browser

Chrome

### Browser Version

112.0.56

### Build Version

2023.4.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by simeydk** [comment] 2023-06-05 06:59
I you would be happy with such a change, I would be happy to contribute it. I'm have basic/intermediate web dev skills. I might just need a smidge of guidance.

**Comment by atjbramley** [comment] 2023-06-06 10:50
Hi @simeydk,

Thanks for opening this issue.  Can you please supply an example of such a page so that I can investigate your report?

**Comment by djsmith85** [comment] 2023-06-06 13:23
Duplicate of https://github.com/bitwarden/clients/issues/2231

**Comment by atjbramley** [comment] 2023-06-06 14:05
Hi @simeydk 

Thank you once again for your report.  As @djsmith85 states, it seems like it is a duplicate of [this one](https://github.com/bitwarden/clients/issues/2231). 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by atjbramley** 2023-06-06 14:05 UTC
Labels: bug, browser
