### ISSUE TITLE
Passkeys Intermittently broken in macOS Sequoia on Safari 18.0.1

### ISSUE THREAD

**Issue by lalaRLH** [bitwarden/clients#11598] opened 2024-10-17 02:42 UTC
### Steps To Reproduce

Go to https://www.google.com >> Sign In >> Enter Google account email address that is onboarded into Bitwarden Vault as a Passkey Sign In >> Attempt Login >> Sign in with a Passkey popup appears 3x >> Pressing Confirm does not work >> Google Fails and prompts user to select why they're having issues signing in with the Passkey. 

Errors in safari extensions (8x listed after attempting sign-in with Passkey):
Unable to find “popup/fonts/bwi-font.svg” in the extension’s resources.
Unable to find “popup/fonts/bwi-font.svg” in the extension’s resources.
Unable to find “popup/fonts/bwi-font.svg” in the extension’s resources.
Unable to find “popup/fonts/bwi-font.svg” in the extension’s resources.
Unable to find “popup/fonts/bwi-font.svg” in the extension’s resources.
Unable to find “popup/fonts/bwi-font.svg” in the extension’s resources.
Unable to find “popup/fonts/bwi-font.svg” in the extension’s resources.
Unable to find “popup/fonts/bwi-font.svg” in the extension’s resources.

Included video evidence of issue also. Note: not every site is impacted but a vast number of sites are, and these are large + widely adopted sites used by mass market e.g. Google above. 

### Expected Result

Passkey prompt to load 1x not 3x and sign in button to work.

### Actual Result

Passkey prompt 3x and fails to perform sign in as expected. 

### Screenshots or Videos

https://github.com/user-attachments/assets/2a78ed58-f4b7-47e8-ba15-e8ee5b2ab9b5

### Operating System

macOS

### Operating System Version

Sequoia 15.0.1 (24A348)

### Web Browser

Safari

### Browser Version

Version 18.0.1 (20619.1.26.31.7)

### Build Version

OS Build Version: 24A348 | Browser Build Version: 20619.1.26.31.7

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by BBGhub** [comment] 2024-10-17 02:49
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/10714

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by BBGhub** 2024-10-17 02:49 UTC
Labels: bug, browser
