### ISSUE TITLE
generate command is bug once you're logged into the CLI

### ISSUE THREAD

**Issue by Wdeb1** [bitwarden/clients#5834] opened 2023-07-14 09:39 UTC
### Steps To Reproduce

1. Get Bitwarden CLI for windows (version 2023.5.0)
2. Open Powershell to the executable's location
3. Login to the Bitwarden CLI
4. Execute command: bw generate --passphrase --words 3 --separator - --includeNumber --capitalize

### Expected Result

A passphrase of 3 words with Capital letters on each word separated by a dash with at least 1 word paired with a number.
e.g.

Testing2-Random-Password

### Actual Result

A password of the default 14 characters with capital & normal letters, numbers, and special characters.

e.g.
@C9rPP2%B*%5#e

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/139242091/485be13a-0d9f-43d9-8cfb-cd2d358066e5)

### Additional Context

Further digging into the issue of #5787
Bugged behavior only occurs when you are logged into the Bitwarden CLI.

As shown in the screenshot, when you run the command when NOT logged in, it works as expected.
As soon as you log in however, it is bugged and doesn't work as expected.

### Operating System

Windows

### Operating System Version

Win10 22H2 19045.3086

### Shell

PowerShell

### Build Version

2023.5.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Wdeb1** [comment] 2023-07-14 09:43
Tag in @MarsCandyBars

**Comment by djsmith85** [comment] 2023-07-14 09:48
Duplicate of #5787

**Comment by djsmith85** [comment] 2023-07-14 09:49
@Wdeb1 Please comment with any additional information on the original issue and do not open a new duplicate issue. The original issue can always be re-opened if needed.

Closing this now.

**Closed by djsmith85** 2023-07-14 09:49 UTC
Labels: bug, cli
