### ISSUE TITLE
Chrome extension Vault timeout on browser restart when other chrome profile window keep opening

### ISSUE THREAD

**Issue by tamamaforever** [bitwarden/clients#1702] opened 2021-03-15 02:34 UTC
## Describe the Bug

If you have 2 Chrome windows, one with Chrome profile A with bitwarden extension and the other with Chrome profile B, only close the window with Chrome profile A will not trigger the Vault timeout on browser restart.

## Steps To Reproduce

1. Open a Chrome window with Chrome profile A and unlock the bitwarden extension, set the Vault timeout option to  "on browser restart".
2. Open a Chrome window with Chrome profile B
3. Close the Chrome window with Chrome profile A
4. Open the Chrome window with Chrome profile A

## Expected Result

The Chrome profile A window bitwarden extension is still unlock

## Environment

- Operating system: Windows 10 Home 20H2
- Browser: Chrome 89.0.4389.90
- Build Version (go to "Settings" → "About" in the app): 1.49.0

## Additional Context

I think it will be more secure if the bitwarden extension can lock once the profile A window is closed while other profile Chrome windows keep opening. The Vault timeout  "on browser restart" option also need to rename to "on profile close"

**Comment by cesarfarias** [comment] 2022-01-25 12:05
Yes, must be the latest chrome version or so, I used to keep it under 'browser restart' and it would never ask my password as long the browser is on.

now, if I close the browser profile on chrome and open another one, even tho chrome itself is always open, it asks my password again, it used to not be like that.

**Comment by Hinton** [comment] 2023-03-21 09:25
Hi,

This is the expected behavior. Chrome profiles behave as completely separate browsers, which is why you can log into different accounts on them. The _browser restart_  behavior is therefor working as expected. See also https://github.com/bitwarden/clients/issues/2395 which describes a related issue for macOS where closing the window now exits the chrome process.

Closing this, since it's working as expected.

**Closed by Hinton** 2023-03-21 09:25 UTC
Labels: browser
