### ISSUE TITLE
SSO - Display Full Width Settings Ignored

### ISSUE THREAD

**Issue by wagisdev** [bitwarden/clients#4770] opened 2023-02-15 14:57 UTC
### Steps To Reproduce

If the account is a administrator, and SSO is configured, when logging on via SSO the display full width layout setting (if set to full width) is ignored.

Only tested against self hosted.

### Expected Result

Full width settings for administrator account works via any logon method.

### Actual Result

Full width, while logging in via SSO as an administrator, is ignored.

### Operating System

Windows

### Operating System Version

10

### Web Browser

Chrome

### Browser Version

110.0.5481.100

### Build Version

2023.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by joshuabjordan** [comment] 2023-02-15 15:05
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by cksapp** [comment] 2023-02-16 19:30
I was also able to [confirm](https://community.bitwarden.com/t/question-about-saving-web-vault-settings/50980/4) this within the individual vault, without SSO as well as another user experiencing the same FWIW.

**Comment by djsmith85** [comment] 2023-07-14 07:39
Duplicate of https://github.com/bitwarden/clients/issues/3354

**Closed by djsmith85** 2023-07-14 07:39 UTC
Labels: bug, web
