### ISSUE TITLE
Safari Extension suddenly states "Biometry unlock not supported on this device"

### ISSUE THREAD

**Issue by vordenken** [bitwarden/clients#4227] opened 2022-12-14 09:34 UTC
### Steps To Reproduce

1. Just click on the bitwarden icon in safari, if you have "Ask for biometry after start" enabled, the prompt shows immediately. 

### Expected Result

It should just show the TouchID Prompt and after successful authentication unlock the vault.

### Actual Result

It says that this isn't an option on my device.

### Screenshots or Videos

<img width="369" alt="image" src="https://user-images.githubusercontent.com/62395860/207558863-6ab9ce47-bc8b-458e-b461-597ed30b6cb6.png">

### Additional Context

The option to unlock with TouchID seems to be gone in the desktop app as well...

### Operating System

macOS

### Operating System Version

13.0.1

### Web Browser

Safari

### Browser Version

16.1

### Build Version

2022.10.2

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2022-12-14 12:11
Hi @vordenken and thank you for your report.

Could this be a possible duplicate of https://github.com/bitwarden/clients/issues/2470?

**Comment by vordenken** [comment] 2022-12-14 12:23
Damn, you're right... I started using my MacBook in clamshell mode recently. Didn't think about that.

I've read #2470 but if this is the problem, why can't the desktop app of bitwarden use biometrics (In this case not touchID but my Watch)? Is this the same issue? 

Looks like the PR for it only would apply to the safari extension?

**Comment by djsmith85** [comment] 2022-12-14 12:44
On the desktop app, the same problem appears when used in clamshell-mode, which is being tracked with https://github.com/bitwarden/clients/issues/2572.

I'm going to close this now, as it is a duplicate. Please add any additional information you might have to those issues mentioned.

**Closed by djsmith85** 2022-12-14 12:44 UTC
Labels: bug, browser
