### ISSUE TITLE
There are no collections to list

### ISSUE THREAD

**Issue by mastenzales** [bitwarden/clients#8354] opened 2024-03-15 17:01 UTC
### Steps To Reproduce

1. Go to '.+" for new item
Collections blank on new entries

### Expected Result

list of collections

### Actual Result

There are no collections to list.

### Operating System

Windows

### Operating System Version

windows 11 pro

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-03-15 18:13
Duplicate of https://github.com/bitwarden/clients/issues/8258

**Comment by djsmith85** [comment] 2024-03-15 18:14
Hello @mastenzales,

Thank you for this report. It seems like a duplicate of the https://github.com/bitwarden/clients/issues/8258 linked above.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This report will now be closed.

Kind regards,
Daniel

**Closed by djsmith85** 2024-03-15 18:14 UTC
Labels: bug, desktop
