### ISSUE TITLE
Windows desktop update prompt is intrusive

### ISSUE THREAD

**Issue by megafinz** [bitwarden/clients#2986] opened 2022-06-28 06:52 UTC
### Steps To Reproduce

0. Have an outdated version of Desktop app.
1. Open the app.
2. Start typing your Master Password.
3. Observe that an update dialog appeared while you were typing so you actually didn't enter your master password and also your "Enter" caused the app to close and start the update process.

### Expected Result

Would be nice to have a less intrusive update experience, e.g. an icon or a button could appear somewhere in the UI that doesn't interrupt the user flow and requires conscious user interaction.

### Actual Result

Update prompt interrupts typing the master password.

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.5.1

**Comment by Hinton** [comment] 2022-06-28 10:03
Duplicate of https://github.com/bitwarden/clients/issues/2608

**Closed by Hinton** 2022-06-28 10:03 UTC
Labels: bug, desktop
