### ISSUE TITLE
Long Collection names not distinguishable

### ISSUE THREAD

**Issue by ByteBitten** [bitwarden/clients#4703] opened 2023-02-09 11:03 UTC
### Steps To Reproduce

1. Add multiple (2 will do) Collections with long names in the following fashion:
- Department 01 - Customer 01
- Department 01 - Customer 02
2. Go to web interface and see truncation:
- Department 01 - Cust...
- Department 01 - Cust...

### Expected Result

Expected result:
- Full Collection name showing with mouse-over
- Collection name visable after "Vault items" when clicking collection

### Actual Result

- Department 01 - Cust...
- Department 01 - Cust...

and no other indication if you have the correct Collection.

### Additional Context

Suggested solution:
Adding the 'title' attribute to the 'button' could be easiest for mouse-over.

Adding the collection name to 'small' in the div with 'page-header d-flex' class could work.

### Operating System

Windows, macOS, Linux

### Web Browser

Chrome, Firefox, Vivaldi

### Build Version

2023.1.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment] 2023-02-09 14:37
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by cksapp** [comment] 2023-02-16 19:52
@ByteBitten This may be a duplicate of https://github.com/bitwarden/clients/issues/3296
For a work around currently see the comment there, which appears it may work for your scenario as well.

![2023-02-16_14h50_36](https://user-images.githubusercontent.com/66083310/219471991-da8c62eb-c1ca-4b8b-9f68-f4374ddbc040.png)

> For the full-width issue, it seems Bitwarden implemented an option at least for the web vault (it still doesn't help if your browser window is less wide though).
> 
> ![image](https://user-images.githubusercontent.com/22837936/193057937-b7b26a0e-8458-4768-80aa-275248a44ced.png)

Though from what I can tell it appears there is now some hover text, which also appears to make it easier to distinguish longer collection names like this.

![2023-02-16_14h50_19](https://user-images.githubusercontent.com/66083310/219472083-93358368-0177-4048-b80a-8d878538a7ab.png)

**Comment by ByteBitten** [comment] 2023-02-17 10:40
This issue is resolved with 2023.2.0

**Closed** 2023-02-17 10:40 UTC
Labels: bug, web

**Comment by tonaltti** [comment] 2023-04-17 10:32
This is still an issue with the desktop client.

**Comment by pa-jberanek** [comment] 2023-04-17 10:35
> This is still an issue with the desktop client.

Agreed, truncated and no tooltip:

**Comment by djsmith85** [comment] 2023-04-17 18:28
@tonaltti, @pa-jberanek: For the desktop, we have an open community contribution which is located here: https://github.com/bitwarden/clients/pull/5131

**Comment by davidroth** [comment] 2023-09-26 14:10
What about the browser app? Long names are also indistinguishable in the browser plugin 😔
