### ISSUE TITLE
Display issues in firefox 127.0 

### ISSUE THREAD

**Issue by RealLordK1** [bitwarden/clients#9709] opened 2024-06-18 08:56 UTC
### Steps To Reproduce

In some webistes, like Zimbra webmail, items won't show up properly only if bitwarden module is installed and enabled.

### Expected Result

Website properly displayed.

### Actual Result

Missing parts of the website (like mail contents, title, sender, etc.)

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/63750689/d63ba839-649f-4026-b838-6a87b7c6e8ec)

### Operating System

Windows, Linux

### Operating System Version

Windows 10 and 11, Linux Mint and Ubuntu

### Web Browser

Firefox

### Browser Version

127.0

### Build Version

2024.4-2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-06-18 09:07
Duplicate of https://github.com/bitwarden/clients/issues/9618

**Comment by djsmith85** [comment] 2024-06-18 09:07
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/9618.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2024-06-18 09:07 UTC
Labels: bug, browser
