### ISSUE TITLE
Firefox extension has significant performance impact

### ISSUE THREAD

**Issue by wooque** [bitwarden/clients#7267] opened 2023-12-18 19:22 UTC
### Steps To Reproduce

1. Go to https://browserbench.org/Speedometer2.1/
2. Click on 'Start Test' without Bitwarden enabled
3. Click on 'Start Test' with Bitwarden enabled

### Expected Result

Slight performance impact

### Actual Result

Firefox being slower as much as 15% with Bitwarden extension enabled

### Screenshots or Videos

![without_bitwarden](https://github.com/bitwarden/clients/assets/1936195/286778b1-a4fb-42c2-ba39-fbbe497f52a4)

![with_bitwarden](https://github.com/bitwarden/clients/assets/1936195/f85d18e9-d020-499b-8e7a-393da2099129)

### Operating System

Linux

### Operating System Version

Debian 12

### Web Browser

Firefox

### Browser Version

120

### Build Version

2023.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by skarekrow** [comment] 2023-12-18 19:52
FWIW, on macOS Sonoma 14.2, I see a 3% differential with Bitwarden enabled. 409 (enabled) -> 418 (enabled) on that same test using `Brave 1.61.100`

**Comment by NovaSilentium** [comment] 2023-12-20 10:44
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by shawngmc** [comment] 2024-04-27 18:42
I'm seeing the same thing on Chrome as well. Changing nothing else between runs (no other addons, open apps, etc.), I'm seeing a drop from 16.6 to 14.2 on [Speedometer 3.0](https://browserbench.org/Speedometer3.0/#). What's odd is that addons that I think would be more compute intensive - uBlock Origin, which is set to remove unnecessary elements - is nowhere near as much of an impact.

I'm trying to profile a Speedometer run to see if I can narrow it down some, but it's tricky: it's a very large profiling run, profiling changes performance in and of itself, and I'm not sure how to isolate extension behavior here. (To be fair, I don't profile JS often - I'm more accustomed to Java via JVisualVM.)

**Comment by cagonzalezcs** [comment] 2024-05-07 22:29
@wooque 

Thank you for your bug report, we've been pushing hard on manifest v3 since early this year so I haven't been able to get these kinds of performance issues until recently. 

That said, we have a set of [changes](https://github.com/bitwarden/clients/pull/9063) that should alleviate the performance issues being described here.

I'd like to centralize related conversations to a single Github issue, so I'll be closing this thread for now.

Please feel free to continue discussion in this [Github issue thread.](https://github.com/bitwarden/clients/issues/8699)

**Closed by cagonzalezcs** 2024-05-07 22:29 UTC
Labels: bug, browser
