### ISSUE TITLE
UI blank in Firefox after using "Log in with device"

### ISSUE THREAD

**Issue by afeick** [bitwarden/clients#5120] opened 2023-03-30 18:28 UTC
### Steps To Reproduce

1. Install Bitwarden Firefox extension
2. Log in for the first time (requires master password)
3. Set the Vault timeout action to "Log out"
4. Restart Firefox
5. Click "Log in with device"
6. Approve from iOS app
7. Close Bitwarden extension UI
8. Click on Bitwarden extension button again
9. UI is blank

### Expected Result

UI should show normally

### Actual Result

UI is blank

### Screenshots or Videos

Blank UI:

![image](https://user-images.githubusercontent.com/686807/228929957-a2a932ff-49ec-445b-9cb9-dc52d5d8de95.png)

### Operating System

macOS

### Operating System Version

12.6.4

### Web Browser

Firefox

### Browser Version

111.0.1 (64-bit)

### Build Version

2023.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by iCodeHead** [comment] 2023-04-24 13:41
Can this issue please get some loving interest already!!!
It has been almost 2 months since this issue was first reported. 
Here it the Github link to the closed report back in Feb 27th.
https://github.com/bitwarden/clients/issues/4878

**Comment by djsmith85** [comment] 2023-04-26 15:43
Duplicate of #4878 

Response here: https://github.com/bitwarden/clients/issues/4878#issuecomment-1505726359

**Closed by djsmith85** 2023-04-26 15:43 UTC
Labels: bug, browser
