### ISSUE TITLE
MS Edge Browser Extension "error: cannot decrypt"

### ISSUE THREAD

**Issue by shuaiy2023** [bitwarden/clients#6765] opened 2023-11-02 13:11 UTC
### Steps To Reproduce

Within Bitwarden extension, set the auto-fill to be on page load and vault timeout as close browser. 
1. Close the MS Edge browser
2. Reopen the MS Edge brower and navigate to a website that has the login saved in the vault.
3. Once the website login page loaded, the auto-fill will put [error: cannot decrypt] in both the username and password field
4. Unlock the bitwarden vault within Edge browser
5. All the saved logins within bitwarden extension are shown as [error: cannot decrypt]
6. Close the Edge browser and re-open it
7. Unlock the bitwarden vault first and then open the website login page.
8. The auto-fill function works and other saved logins are showing fine.

### Expected Result

If the vault was locked while loading a website login page, the auto-fill should not try to fill anyting. Once vault is unlocked, the auto-fill function should kick-in on website loads.

### Actual Result

It seems the new version of bitwarden browser extension, the auto-fill function is too aggressive to fill unnecessary info even the vault is unlocked. 

### Screenshots or Videos

<img width="274" alt="1" src="https://github.com/bitwarden/clients/assets/140644154/962ccb04-4351-4add-971e-ff23c1c07a43">
<img width="581" alt="2" src="https://github.com/bitwarden/clients/assets/140644154/4ac67ed9-148f-4cb9-b119-1695b05baae8">

### Operating System

Windows

### Operating System Version

Win 10 Ent 22H2 Build 19045.3636

### Web Browser

Microsoft Edge

### Browser Version

118.0.2088.76

### Build Version

2023.10.0

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment] 2023-11-02 13:28
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/6759. 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by Neonwarden** 2023-11-02 13:28 UTC
Labels: bug, browser
