### ISSUE TITLE
Cannot create new Items in Client - There are no collections to list

### ISSUE THREAD

**Issue by christian-kaana-it** [bitwarden/clients#9451] opened 2024-05-31 06:34 UTC
### Steps To Reproduce

1. Select a Collection
2. Click on 'Add Item'
3. Cannot Save because 'There are no collections to list'

### Expected Result

Collections gets listed and adding New Items is working!

### Actual Result

Cannot save in Client (It is working in the Web Version)

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.4.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-05-31 06:41
Duplicate of https://github.com/bitwarden/clients/issues/8258

**Comment by djsmith85** [comment] 2024-05-31 06:41
Hi @christian-kaana-it and thank you for your report.

This has previously been reported with https://github.com/bitwarden/clients/issues/8258. Please update your client, as this has been fixed within `2024.4.3`.

Closing this now.

Kind regards,
Daniel

**Closed by djsmith85** 2024-05-31 06:41 UTC
Labels: bug, desktop
