### ISSUE TITLE
Updating to v2023.8.2 from v2023.7.1 causes entries with "master password re-prompt" turned on to be unreadable

### ISSUE THREAD

**Issue by NitCelcius** [bitwarden/clients#6171] opened 2023-09-01 14:04 UTC
### Steps To Reproduce

1. Make sure you have v2023.7.1 Bitwarden extension. This may occur the same when you update from v2023.8.0.
2. Create at least one "login" entry with "require master password re-prompt" enabled.
3. Update the extension to v2023.8.2.
4. Try to copy, view, or edit the password of the entry. You will be asked to input your master password.
5. Click OK or hit enter key.

### Expected Result

If the master password you entered is correct, the master password re-prompt dialog will close.
You should be able to copy, view, or edit the password of the entry you have created. When you copy it you will see a "Password copied" pop-up.

If the master password you entered is NOT correct, the master password re-prompt dialog will not close and you will see a "Incorrect master password" pop-up.

### Actual Result

When you try to copy the password, master password re-prompt dialog won't close and the password is not copied. You can press the OK button but nothing happens.

Either your master password you enter is correct or not, OK button or Enter key does not do anything.

![image](https://github.com/bitwarden/clients/assets/76618755/b34ade23-ba48-4f5d-8562-f3d3dd32416b)

### Screenshots or Videos

From chrome's settings, you can see an error like this:

![image](https://github.com/bitwarden/clients/assets/76618755/9bb7aeb0-d10d-4574-9bc0-dbbdf8d29278)

In DevTools:
![image](https://github.com/bitwarden/clients/assets/76618755/e0001e64-1ef0-4427-bf54-3a143cf0492b)

### Additional Context

Note that, this error will **not** occur when you clear the data from the previous version and log into your account again. This means you can **re-install BitWarden extension and log in to your account again to fix this problem**.
I did not see any entries corrupted by this bug. All entries with "require master password re-prompt" enabled will be unreadable unless you reinstall the extension.

I confirmed the same problem on Vivaldi 6.2.3105.45.

Also: On Android device you may find the same issue. I am not sure if the same-looking issue on Android app is caused by update and trying to reproduce the problem, so I have not created an issue (of Android app) on GitHub.

### Operating System

Windows

### Operating System Version

22H2, build 22621.2134

### Web Browser

Chrome, Vivaldi

### Browser Version

Chrome 116.0.5845.140, Vivaldi 6.2.3105.45

### Build Version

2023.8.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2023-09-01 14:06
Duplicate of https://github.com/bitwarden/clients/issues/6153

**Comment by djsmith85** [comment] 2023-09-01 14:06
@NitCelcius Thank you for your report this is a known issue and a duplicate of https://github.com/bitwarden/clients/issues/6153

**Closed by djsmith85** 2023-09-01 14:06 UTC
Labels: bug, browser
