### ISSUE TITLE
Secure Input Never Relinquished if Safari asks for Bitwarden TouchID Authentication after Calling for an Autofill

### ISSUE THREAD

**Issue by kuanjuliu** [bitwarden/clients#6694] opened 2023-10-25 14:49 UTC
### Steps To Reproduce

Affected hardware:

- 2021 M1 Max 16" MacBook Pro
- 2023 M2 Pro 16" MacBook Pro

1. Safari Bitwarden extension set to "Unlock with biometrics" and "Ask for biometrics on launch"
2. Set Bitwarden Desktop app to "Unlock with TouchID"
3. Quit Safari
4. Open Safari and surf to a website with a login that Bitwarden can fill
5. Either use the Bitwarden extension's menu, right-click in the login fields, or hit Cmd-Shift-L to trigger an autofill with Bitwarden
6. Use TouchID to authenticate with Bitwarden
7. Observe with `ioreg -l -w 0 | grep SecureInput` that Secure Input has been locked by Safari
8. Observe that Secure Input _is never relinquished thereafter_, unless Safari itself is quit

So far the only way around this is to immediately log into the Bitwarden extension when starting Safari.

If I don't immediately authenticate Bitwarden after opening Safari, Secure Input is permanently acquired if I try to autofill using Bitwarden in Safari.

### Expected Result

I expect Secure Input to be relinquished by Safari after I authenticate Bitwarden with TouchID.

### Actual Result

Safari acquires Secure Input after a Bitwarden autofill attempt results in asking for biometrics, and never relinquishes it.

This causes text expander programs like Snippety, TypeIt4Me, etc to stop working immediately and until Safari itself is quit.

### Operating System

macOS

### Operating System Version

MacOS Ventura 13.6, Sonoma 14.0

### Web Browser

Safari

### Browser Version

Safari 17.0

### Build Version

Ventura (186156.1.27.111.22, 18616), Sonoma (19616.1.27.211.1)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment] 2023-10-25 17:17
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/6134 which, in turn, causes issues with Touch ID for the Safari extension. 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by Neonwarden** 2023-10-25 17:17 UTC
Labels: bug, browser
