### ISSUE TITLE
Bitwarden App is blacked out, weird rectangles

### ISSUE THREAD

**Issue by rharder** [bitwarden/clients#8389] opened 2024-03-19 16:45 UTC
### Steps To Reproduce

1. Go to App Store and download BitWarden
2. Open BitWarden
3. Main window is drawn wrong with black and white rectangles.

### Expected Result

BitWarden window should be drawn correctly

### Actual Result

BitWarden window cannot be read.

### Screenshots or Videos

![bitwarden messed up screen](https://github.com/bitwarden/clients/assets/75600/3ef2ae51-2cb1-4702-b707-4fab1febf01d)

### Additional Context

MacOS Catalina
Safari 15.6.1

### Operating System

macOS

### Operating System Version

Catalina 10.15.7

### Installation method

Mac App Store

### Build Version

Version 2024.3.0 (21897)

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment] 2024-03-19 16:54
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/8003 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by Neonwarden** 2024-03-19 16:54 UTC
Labels: bug, desktop
