### ISSUE TITLE
Don't save zoom scale 

### ISSUE THREAD

**Issue by yiannispan** [bitwarden/clients#3590] opened 2022-09-22 14:26 UTC
### Steps To Reproduce

Open desktop application.
Change zoom scale using Ctrl + = and/or Ctrl + -
Close application.
Reopen the application.
Zoom settings was not saved.

### Expected Result

Zoomed UI.

### Actual Result

Always the default zoom.

### Operating System

Windows

### Operating System Version

Windows 10 Pro 21H2 19044.2006

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2022.9.1 Shell 19.0.8 Renderer 102.0.5005.148 Node 16.14.2 Architecture x64

**Comment by tangowithfoxtrot** [comment] 2022-09-22 17:27
Hi, @yiannispan. I was able to reproduce this on my end as well. I have indicated this in our internal bug-tracking system. Thanks again for reporting!

**Comment by djsmith85** [comment] 2022-09-23 15:57
This seems like a duplicate of https://github.com/bitwarden/clients/issues/2623.

I'm going to close this issue, but I have linked the tickets in our internal-bug tracking system.

@yiannispan Thanks again for the report and @tangowithfoxtrot for vetting

**Closed by djsmith85** 2022-09-23 15:57 UTC
Labels: bug, desktop
