### ISSUE TITLE
Bitwarden login page disappears (Debian..not sure of other systems)

### ISSUE THREAD

**Issue by themagicm** [bitwarden/clients#6580] opened 2023-10-13 17:46 UTC
### Steps To Reproduce

4. Click on '...'

1. Open version 2023.9.2 on Debian, 5.18.0-2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.5-1 (2022-06-16) x86_64 GNU/Linux.

2.  Just open Bitwarden 2023.9.2 and let it sit for a few seconds. Login page disappears.  I am able to type my password real fast and it goes to my Logins but then it disappears and nothing is seen.

### Expected Result

Expect to see my logins.

### Actual Result

Blanks screen

### Additional Context

./Bitwarden-2023.9.2-x86_64.AppImage 
(node:16720) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `bitwarden --trace-deprecation ...` to show where the warning was created)
(node:16720) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'init')
    at BiometricsService.<anonymous> (/tmp/.mount_BitwarGi1yDp/resources/app.asar/main.js:47194:55)
    at Generator.next (<anonymous>)
    at /tmp/.mount_BitwarGi1yDp/resources/app.asar/main.js:47160:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/tmp/.mount_BitwarGi1yDp/resources/app.asar/main.js:47156:12)
    at BiometricsService.init (/tmp/.mount_BitwarGi1yDp/resources/app.asar/main.js:47193:16)
    at Main.<anonymous> (/tmp/.mount_BitwarGi1yDp/resources/app.asar/main.js:53805:46)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_BitwarGi1yDp/resources/app.asar/main.js:53702:58)
(node:16720) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
[16720:1013/124542.940015:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
12:45:43.558 › Error: No password found
12:45:43.570 › Error: No password found
12:45:43.593 › Error: No password found
12:45:43.594 › Error: No password found
12:45:43.595 › Error: No password found
12:45:43.603 › Error: No password found
12:45:43.611 › TypeError: Cannot read properties of undefined (reading 'osSupportsBiometric')
    at BiometricsService.<anonymous> (/tmp/.mount_BitwarGi1yDp/resources/app.asar/main.js:47199:55)
    at Generator.next (<anonymous>)
    at /tmp/.mount_BitwarGi1yDp/resources/app.asar/main.js:47160:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/tmp/.mount_BitwarGi1yDp/resources/app.asar/main.js:47156:12)
    at BiometricsService.osSupportsBiometric (/tmp/.mount_BitwarGi1yDp/resources/app.asar/main.js:47198:16)
    at BiometricsService.<anonymous> (/tmp/.mount_BitwarGi1yDp/resources/app.asar/main.js:47209:58)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_BitwarGi1yDp/resources/app.asar/main.js:47157:58)
12:45:43.612 › TypeError: Cannot read properties of undefined (reading 'osSupportsBiometric')
    at BiometricsService.<anonymous> (/tmp/.mount_BitwarGi1yDp/resources/app.asar/main.js:47199:55)
    at Generator.next (<anonymous>)
    at /tmp/.mount_BitwarGi1yDp/resources/app.asar/main.js:47160:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/tmp/.mount_BitwarGi1yDp/resources/app.asar/main.js:47156:12)
    at BiometricsService.osSupportsBiometric (/tmp/.mount_BitwarGi1yDp/resources/app.asar/main.js:47198:16)
    at DesktopCredentialStorageListener.<anonymous> (/tmp/.mount_BitwarGi1yDp/resources/app.asar/main.js:47383:59)
    at Generator.next (<anonymous>)
    at /tmp/.mount_BitwarGi1yDp/resources/app.asar/main.js:47311:71
    at new Promise (<anonymous>)
12:45:43.620 › Error: No password found
[16720:1013/124543.655397:ERROR:nss_util.cc(357)] After loading Root Certs, loaded==false: NSS error code: -8018
12:45:43.783 › Error: No password found
12:45:44.058 › Error: No password found
12:45:44.084 › Error: No password found
12:45:44.123 › Error: No password found
12:45:44.129 › Error: No password found
12:45:44.147 › Error: No password found
12:45:44.157 › Error: No password found
12:45:44.172 › Error: No password found
12:45:44.189 › Error: No password found
(node:16720) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'setContextMenu')
    at TrayMain.updateContextMenu (/tmp/.mount_BitwarGi1yDp/resources/app.asar/main.js:46304:23)
    at MessagingMain.updateTrayMenu (/tmp/.mount_BitwarGi1yDp/resources/app.asar/main.js:45804:28)
    at MessagingMain.onMessage (/tmp/.mount_BitwarGi1yDp/resources/app.asar/main.js:45730:22)
    at MessagingMain.<anonymous> (/tmp/.mount_BitwarGi1yDp/resources/app.asar/main.js:45721:151)
    at Generator.next (<anonymous>)
    at /tmp/.mount_BitwarGi1yDp/resources/app.asar/main.js:45700:71
    at new Promise (<anonymous>)
    at messaging_main_awaiter (/tmp/.mount_BitwarGi1yDp/resources/app.asar/main.js:45696:12)
    at IpcMainImpl.<anonymous> (/tmp/.mount_BitwarGi1yDp/resources/app.asar/main.js:45721:79)
    at IpcMainImpl.emit (node:events:513:28)
(node:16720) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
12:45:44.195 › Error: No password found
12:45:44.196 › Error: No password found
12:45:44.202 › Error: No password found
12:45:44.301 › Error: No password found
12:45:44.600 › Error: No password found
(node:16720) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'setContextMenu')
    at TrayMain.updateContextMenu (/tmp/.mount_BitwarGi1yDp/resources/app.asar/main.js:46304:23)
    at MessagingMain.updateTrayMenu (/tmp/.mount_BitwarGi1yDp/resources/app.asar/main.js:45804:28)
    at MessagingMain.onMessage (/tmp/.mount_BitwarGi1yDp/resources/app.asar/main.js:45730:22)
    at MessagingMain.<anonymous> (/tmp/.mount_BitwarGi1yDp/resources/app.asar/main.js:45721:151)
    at Generator.next (<anonymous>)
    at /tmp/.mount_BitwarGi1yDp/resources/app.asar/main.js:45700:71
    at new Promise (<anonymous>)
    at messaging_main_awaiter (/tmp/.mount_BitwarGi1yDp/resources/app.asar/main.js:45696:12)
    at IpcMainImpl.<anonymous> (/tmp/.mount_BitwarGi1yDp/resources/app.asar/main.js:45721:79)
    at IpcMainImpl.emit (node:events:513:28)
(node:16720) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
12:45:46.580 › Error: No password found
12:45:47.937 › Checking for update
12:45:48.646 › Update for version 2023.9.2 is not available (latest version: 2023.9.2, downgrade is disallowed).

### Operating System

Linux

### Operating System Version

Debian 5.18.0-2-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.5-1 (2022-06-16) x86_64 GNU/Linux

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.9.2, shell 26.3.0, renderer 116.0.5845.228, node 18.16.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2023-10-13 18:11
Duplicate of https://github.com/bitwarden/clients/issues/6560.

**Comment by djsmith85** [comment] 2023-10-13 18:11
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/6560.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2023-10-13 18:11 UTC
Labels: bug, desktop
