### ISSUE TITLE
'Update Available' popup appears even when the user is actively interacting with the application.

### ISSUE THREAD

**Issue by zwresn453** [bitwarden/clients#6204] opened 2023-09-06 16:21 UTC
### Steps To Reproduce

Interact with application while it finds an available update.

### Expected Result

One of these options:

- The application sends a toast notification instead of a popup
- If you really want to send a popup, send it after the user copies the password (or after they copy the totp code if applicable) so that the user can update if desired, without needing to restart the application and reauthenticate and reauthenticate again in order to get their password. The popup is offensive to the user, though, so I would recommend the toast instead.

### Actual Result

THE PROBLEMS:

This popup:
- Appears when the user is typing, and if they press the spacebar, this will press buttons on the popup without the user's intention.
- Does not appear immediately after opening/unlocking application, which makes it more likely for the user to be unaware of the popup
- 

### Operating System

Windows

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.8.2

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2023-09-06 20:40
Duplicate of https://github.com/bitwarden/clients/issues/2608

**Comment by djsmith85** [comment] 2023-09-06 20:40
Hi @zwresn453 and thank you for your report.

Closing this as a duplicate of https://github.com/bitwarden/clients/issues/2608

**Closed by djsmith85** 2023-09-06 20:40 UTC
Labels: bug, desktop
