### ISSUE TITLE
Linux Desktop: List of entries returns to top entry when creating or editing an entry instead of maintaining focus on current entry.

### ISSUE THREAD

**Issue by DavidPesticcio** [bitwarden/clients#7554] opened 2024-01-15 11:27 UTC
### Steps To Reproduce

1. Create a new entry, or edit an existing one (by manually scrolling to the entry and selecting it)
2. Save the entry and the list of entries returns to top item (while the new or edited entry remains highlighted, but not in view)

### Expected Result

When creating a new entry, the list of entries should reveal the new entry in list.
When editing an entry, the list of entries leave the focused entry in view - i.e. not scroll out of view.

### Actual Result

After saving a new or existing entry (even if selected in the list), the list of entries scrolls to the top item instead of keeping the active entry visible.

### Additional Context

```text
$ pacman -Qi bitwarden

Name            : bitwarden
Version         : 2024.1.0-1
Description     : A secure and free password manager for all of your devices
Architecture    : x86_64
URL             : https://github.com/bitwarden/clients/tree/master/apps/desktop
Licenses        : GPL3
Groups          : None
Provides        : None
Depends On      : electron27  libnotify  libsecret  libxtst  libxss  libnss_nis
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 29.18 MiB
Packager        : Alexander Epaneshnikov <alex19ep@archlinux.org>
Build Date      : Wed 10 Jan 2024 19:33:11 GMT
Install Date    : Sun 14 Jan 2024 11:08:40 GMT
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

### Operating System

Linux

### Operating System Version

$ neofetch --stdout user@host  ---------  OS: Manjaro Linux x86_64  Host: 20L50000UK ThinkPad T480  Kernel: 6.6.10-1-MANJARO  Uptime: 45 mins  Packages: 2391 (pacman)  Shell: bash 5.2.21  Resolution: 1920x1080  DE: Xfce  WM: awesome  Theme: Matcha-light-sea [GTK2], Matcha-dark-azul [GTK3]  Icons: ePapirus [GTK2], Papirus-Dark-Maia [GTK3]  Terminal: terminator  CPU: Intel i5-8250U (8) @ 3.400GHz  GPU: Intel UHD Graphics 620  Memory: 7228MiB / 31863MiB 

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2024.1.0 Shell 27.2.1 Renderer 118.0.5993.159 Node 18.17.1 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-01-15 12:20
Duplicate of https://github.com/bitwarden/clients/issues/5039

**Comment by djsmith85** [comment] 2024-01-15 12:20
Hi @DavidPesticcio

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/5039

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2024-01-15 12:20 UTC
Labels: bug, desktop
