### ISSUE TITLE
Windows taskbar having an empty tray icon beside Bitwarden app on boot up

### ISSUE THREAD

**Issue by H3llBoy-26** [bitwarden/clients#7989] opened 2024-02-17 19:17 UTC
### Steps To Reproduce

1. Under app settings, ensure all the options below are checked:
- Ensure that the checkbox for "Show tray icon" is checked
- Ensure that the checkbox for "Minimise to tray icon" is checked
- Ensure that the checkbox for "Close to tray icon" is checked
- Ensure that the checkbox for "Start automatically on login" is checked
2. Restart PC
3. After logging into Windows, go to the taskbar

### Expected Result

There should not be any empty tray icon

### Actual Result

There will be an empty tray icon beside the Bitwarden icon (See screenshot below)

![image](https://github.com/bitwarden/clients/assets/133878698/71d3df17-4fcb-4c87-978a-300c645b3f79)

### Additional Context

# Workaround
Fully close the Bitwarden app and relaunch it again, and the empty tray icon will disappear

### Operating System

Windows

### Operating System Version

Version 23H2 (OS Build 22631.3155)

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment] 2024-02-20 08:31
Hi there!

Thank you for your report, it seems like it is a duplicate of this one [link to the original GitHub issue]. 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed** 2024-02-20 08:31 UTC
Labels: bug, desktop
