### ISSUE TITLE
Slow script warnings on Firefox with 2023.3

### ISSUE THREAD

**Issue by mullr** [bitwarden/clients#5160] opened 2023-04-04 22:07 UTC
### Steps To Reproduce

This isn't super clean. But what I'm seeing is:

1. Open an enormous Github PR
2. Click the little plus button to leave a code review. 
3. Start typing. 

### Expected Result

The letters I'm typing should show up. 

### Actual Result

Nothing shows up as I type, for a good 5 or 10 seconds.  Firefox will briefly pop up a warning saying 'hey bitwarden is slowing the page down'

### Screenshots or Videos

I was able to profile the page while the problem happened. I can't share the actual profile (it was from a page with proprietary information), but maybe this is helpful enough. 

![image](https://user-images.githubusercontent.com/24409/229933021-a4260818-d9e1-49f8-8c34-58eff059edc4.png)

### Additional Context

Why is it even doing anything at all? I've disabled 'auto-fill on page load', so I can't think of any reason why bitwarden would be running any code at all in this context. 

### Operating System

Linux

### Operating System Version

Ubuntu 22.10

### Web Browser

Firefox

### Browser Version

111

### Build Version

2023.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by c1-jack** [comment] 2023-04-05 01:59
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/clients/issues/5107

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by c1-jack** 2023-04-05 01:59 UTC
Labels: bug, browser
