### ISSUE TITLE
Ask windows Hello on startup not working

### ISSUE THREAD

**Issue by M0fafahrer** [bitwarden/clients#3812] opened 2022-10-17 14:39 UTC
### Steps To Reproduce

Starting the PC program only gives the login screen.

### Expected Result

Ask for Fingerprint scan

### Actual Result

nothing happens, but an extra-click on the button "unlock with Windows Hello" is needed.

### Additional Context

Same behavior on my windows laptop.
started with october update.
Android is working well.

### Operating System

Windows

### Operating System Version

21H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.10.0

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Hinton** [comment] 2022-10-17 15:25
Duplicate of https://github.com/bitwarden/clients/issues/3774

**Closed by Hinton** 2022-10-17 15:25 UTC
Labels: bug, desktop
