### ISSUE TITLE
Enabling bitwarden breaks content of https://n26.com/en-eu/plans on Firefox

### ISSUE THREAD

**Issue by theodoor** [bitwarden/clients#11590] opened 2024-10-16 19:13 UTC
### Steps To Reproduce

1. Open Firefox (tested in 132 and 133) 
2. Install Bitwarden Password Manager (tested 2024.9.1)
3. Navigate: https://n26.com/en-eu/plans (at least 1100 pixels width)
4. Hover over an ( i )-button

### Expected Result

pop up appears

### Actual Result

pop up doesn't appear

### Screenshots or Videos

When Bitwarden enabled:
![image](https://github.com/user-attachments/assets/1caa7bb0-c152-4cbd-9ba4-403a4baebe26)

With bitwarden disabled: 
![image](https://github.com/user-attachments/assets/0a28b72b-36ba-4b1b-8782-d8c1251d6afa)

### Additional Context

```
Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    Oa https://n26.com/_build/assets/components-CDWYZ3Uc.js:38
    vh https://n26.com/_build/assets/components-CDWYZ3Uc.js:40
    hh https://n26.com/_build/assets/components-CDWYZ3Uc.js:40
    Hv https://n26.com/_build/assets/components-CDWYZ3Uc.js:40
    ch https://n26.com/_build/assets/components-CDWYZ3Uc.js:40
    C https://n26.com/_build/assets/components-CDWYZ3Uc.js:25
    X https://n26.com/_build/assets/components-CDWYZ3Uc.js:25
    EventHandlerNonNull* https://n26.com/_build/assets/components-CDWYZ3Uc.js:25
    <anonymous> https://n26.com/_build/assets/components-CDWYZ3Uc.js:25
components-CDWYZ3Uc.js:157:487


Uncaught Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    vh https://n26.com/_build/assets/components-CDWYZ3Uc.js:40
    hh https://n26.com/_build/assets/components-CDWYZ3Uc.js:40
    Bv https://n26.com/_build/assets/components-CDWYZ3Uc.js:40
    Qi https://n26.com/_build/assets/components-CDWYZ3Uc.js:40
    Xa https://n26.com/_build/assets/components-CDWYZ3Uc.js:40
    ch https://n26.com/_build/assets/components-CDWYZ3Uc.js:40
    C https://n26.com/_build/assets/components-CDWYZ3Uc.js:25
    X https://n26.com/_build/assets/components-CDWYZ3Uc.js:25
    EventHandlerNonNull* https://n26.com/_build/assets/components-CDWYZ3Uc.js:25
    <anonymous> https://n26.com/_build/assets/components-CDWYZ3Uc.js:25
components-CDWYZ3Uc.js:40:45149

```

### Operating System

Windows

### Operating System Version

11

### Web Browser

Firefox

### Browser Version

132

### Build Version

2024.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cagonzalezcs** [comment] 2024-10-16 19:45
@theodoor Thank you for the bug report.

This report is a duplicate of https://github.com/bitwarden/clients/issues/11234 and the fix for it should be coming out with an upcoming release of the Firefox extension. 

Closing this thread for now.

**Closed by cagonzalezcs** 2024-10-16 19:45 UTC
Labels: bug, browser
