### ISSUE TITLE
 Firefox on macOS: Vault locks immediately after unlocking

### ISSUE THREAD

**Issue by christophberger** [bitwarden/clients#2482] opened 2022-03-30 20:00 UTC
### Steps To Reproduce

Observed with version 1.57.0, Firefox (latest), macOS 12.3.

1. Configure the Firefox plugin to unlock with biometrics
2. Set the vault timeout to a time-based value
3. Let the plugin lock
4. Unlock the plugin through biometrics
5. Wait.

### Expected Result

The plugin stays unlocked.

### Actual Result

The plugin locks within 0–3 seconds.

### Additional Context

The issue does not occur if the vault timeout is set to "on browser restart". 

The issue does not occur consistently. In rare situations (for example, when locking manually for testing purposes), I observed that the vault remains unlocked after biometric unlock.

Related: https://community.bitwarden.com/t/firefox-vault-locks-immediately-after-unlocking/38478

### Operating System

macOS

### Operating System Version

12.3

### Web Browser

Firefox

### Browser Version

98.0.2

### Build Version

1.57.0

**Comment by kapitainsky** [comment] 2022-04-14 04:59
I can confirm I experience the same behaviour. As reported by @christophberger this is not consistent but happen more often than does not. In most cases I have to unlock BW vault twice or even three times.

**Comment by AreiousX** [comment] 2022-04-20 05:46
Getting the same thing but on Windows, it has been happening since extension v1.55. Tested with biometrics disabled and it works as expected.

Firefox 99.0.1, Windows 10.0.19044

**Comment by kapitainsky** [comment] 2022-04-27 06:35
No change with the latest browser plugin (1.58.0). Set vault timeout is not respected and vault locks randomly - very often within few seconds after biometric unlocking.

**Comment by francois-claude** [comment] 2022-05-04 20:21
Same issue here. MacOS 12.3.1 | Bitwarden v1.58.0 | Firefox v99.0.1

**Comment by christophberger** [comment] 2022-05-05 08:09
With Bitwarden 1.58.0 and FF 99.0.1 as well as with FF 100.0, the issue seems to be gone (at my end at least).
FWIW, my Bitwarden Desktop app is at v1.33.0. I also rebooted my entire Mac recently (which happens rarely enough), maybe this step influenced the result.

**Comment by kapitainsky** [comment] 2022-05-05 08:16
on macOS 12.3.1 with Bitwarden 1.58.0 and  FF 100.0 it still happens for me. I also have latest BW App v.1.33.0. I do not have 100% reliable way to reproduce it every single time so it is only subjective but I think it happens less frequently now.

**Comment by kapitainsky** [comment] 2022-05-05 08:27
OK here we are some crude way to reproduce this issue. Crude as it is not 100% but frequent enough.

I have vault timeout set to 5min.

Unlock BW plugin with biometrics. Then change active tab, change to another tab... usually BW locks itself again on max. 3rd tab but sometimes immediately after first tab change.

**Comment by pro4tlzz** [comment] 2022-05-28 23:11
> OK here we are some crude way to reproduce this issue. Crude as it is not 100% but frequent enough.
> 
> I have vault timeout set to 5min.
> 
> Unlock BW plugin with biometrics. Then change active tab, change to another tab... usually BW locks itself again on max. 3rd tab but sometimes immediately after first tab change.


I have the exact same problem

Microsoft Edge 101.0.1210.53 (Official build) (64-bit) 
Windows 10 Version 21H2 (Build 19044.1706)
Bitwarden 1.33.0


Its the worst thing I have experienced with Bitwarden

**Comment by smithed** [comment] 2022-06-11 05:04
I'd say this happens pretty consistently -- more often then not.
Bitwarden plugin Version 2022.5.0
desktop 1.33
firefox 102

I've found if you unlock and then immediately click the bitwarden icon to hold the window open, it doesn't seem to re-lock. I could very well be imagining this.

**Comment by kapitainsky** [comment] 2022-06-12 06:23
After the latest software updates:

Firefox BW plugin version 2022.5.0
BW desktop version 2022.5.1 (3283)
Firefox version 101.0.1 

No fix.

**Comment by kapitainsky** [comment] 2022-06-13 16:20
yes - specific user behaviour makes it bearable. But bottom line is I set to lock it in 5min - I unlock it and expect it stays unlocked for 5min - regardless what I do.

**Comment by mmcnl** [comment] 2022-06-15 14:28
This re-locking behavior is also happening for me with the browser extension on Chrome (102.0.5005.115) and macOS 12.3.1.

**Comment by pro4tlzz** [comment] 2022-06-15 20:50
> > OK here we are some crude way to reproduce this issue. Crude as it is not 100% but frequent enough.
> > I have vault timeout set to 5min.
> > Unlock BW plugin with biometrics. Then change active tab, change to another tab... usually BW locks itself again on max. 3rd tab but sometimes immediately after first tab change.
> 
> I have the exact same problem
> 
> Microsoft Edge 101.0.1210.53 (Official build) (64-bit) Windows 10 Version 21H2 (Build 19044.1706) Bitwarden App 1.33.0 Bitwarden Plugin 1.58.0
> 
> Its the worst thing I have experienced with Bitwarden
> 
> Edit: my issues seems to be related to the Windows clients and incognito mode. I'll raise a separate issue

Edge extension Version: 2022.5.0 seems to have fixed my problem

**Comment by pro4tlzz** [comment] 2022-06-22 22:39
I have raised this for Windows Edge users https://github.com/bitwarden/clients/issues/2949

**Comment by pro4tlzz** [comment] 2022-06-27 16:29
This is also happening to me with Brave 1.40.107 Chromium: 103.0.5060.53 (Official Build) (64-bit) 

so it seems to be cross platform amongst all chromium browsers because they share the extension

**Comment by smithed** [comment] 2022-06-28 02:38
> so it seems to be cross platform amongst all chromium browsers because they share the extension

It seems pretty clear the extension in all its forms across all OSs has code which doesn't handle timeouts correctly, and hasn't for at least 3 months

**Comment by pro4tlzz** [comment] 2022-06-29 07:24
fixed in https://github.com/bitwarden/clients/releases/tag/web-v2022.6.0 
Vault timeout fix that requires a minimum of 1 min lockout

Please test

**Comment by kapitainsky** [comment] 2022-07-01 07:24
> Please test

Not showing in Firefox extensions yet. 

This is good news that there is attempt to fix it. Hopefully it works - we will see when it is available in extensions updates.

**Comment by KevoM** [comment] 2022-07-01 23:02
Same problem here. Still happening with version 2022.6.0 on Brave Browser. 
I use keyboard shortcut to prompt BW, unlock with biometrics, autofill on a tab. The login executes itself, sometimes the tab get refreshed in the process then the vault immediately re-locks. Doesn't necessarily need to change the tab or view an other tab

**Comment by pro4tlzz** [comment] 2022-07-02 18:30
I haven't got the new extension from the chrome web store yet so I am still facing the same problem

**Comment by kapitainsky** [comment] 2022-07-06 17:26
2022.6.0 landed in approved Firefox extensions.

And it changed not much. I have Vault timeout set to 5 min and BW extension self locked sometimes after seconds.

Back to you guys.

**Comment by esn89** [comment] 2022-08-25 15:37
I am getting the same issue:

Firefox Bitwarden add-on 2022.8
MacOS 12.5.1
Firefox: 104.0

**Comment by roccolord** [comment] 2022-09-30 09:41
Same issues on Vivaldi 5.5, Chrome 105 on both Windows 11 22H2, and MacOS 12.6.1.
Freshly installed extension 2022.9.1
Freshly installed ap 2022.9.1

**Comment by henrypa** [comment] 2022-10-13 09:31
Exactly the same issue here, both on latest MacOS and Windows 21H2 using Firefox on multiple machines. I have deleted the Firefox profile completely and started a brand new profile, tried all the tips, setting custom lock time, switching Lock & Logout settings back and forth etc. but none of these seem to help. Using bitwarden is a constant fight, unlocking via biometric, extension locks itself up, unlocking, locking...

I don't even remember anymore when the timed lock function got broken, happened a long time ago.

Firefox 105.0.3
Bitwarden Extension 2022.10.0

Sorry, don't have any better technical information to give, but at current state Bitwarden is frustrating to use.

**Comment by pro4tlzz** [comment] 2022-10-13 10:16
I should mention I don't have this issue anymore now on macOS.

I also use Linux as well so can't say the same for windows 10

**Comment by kapitainsky** [comment] 2022-10-13 10:21
latest macOS and still the same issue - it is random though - definitely BW does not obey lock time settings and does what it pleases it.

**Comment by roccolord** [comment] 2022-10-16 14:08
Still same problem on 2022.10, even happened directly when signing in to post here.... a chame there is no focus on this bug.

**Comment by smithed** [comment] 2022-10-17 04:32
seems to happen less often now, maybe?, but its definitely still failing

**Comment by jpjonte** [comment] 2022-10-19 07:45
Still happens for me: macOS 12.5.1, Firefox 105.0.3, Bitwarden browser extension 2022.10.0 and Bitwarden desktop 2022.10.0

**Comment by roccolord** [comment] 2022-11-03 06:59
Still happens everytime. macOS 13.0, Vivaldi  5.6.2829.3, Bitwarden browser extension 2022.10.1 and Bitwarden desktop 2022.10.1

**Comment by pro4tlzz** [comment] 2022-11-21 22:55
So I started using Windows 10 again (Ubuntu 22.04 for a few months).

This is still an issue. When is it going to be looked at?

**Comment by pro4tlzz** [comment] 2022-12-12 22:34
This is still an issue. Does no one from Bitwarden actually use their own product?

**Comment by yodapotatofly** [comment] 2022-12-22 15:21
This issue still persists after 8 month.

**Comment by smithed** [comment] 2023-01-14 22:47
Actually I think we are coming up on a year pretty soon. I definitely remember seeing it before I found this issue but not realizing what was happening for a while.

also, my previous message about it being less prevalent....its gone back to normal, pretty much every login takes 2-4 attempts.

**Comment by pro4tlzz** [comment] 2023-01-15 21:13
It's almost like they don't use their own product. Ridiculous  now that we haven't had a statement from them on this,

**Comment by pro4tlzz** [comment] 2023-01-16 10:05
Is anyone else using a USB Fingerprint reader to unlock Bitwarden?

**Comment by yodapotatofly** [comment] 2023-01-16 14:56
mine is builtin but I believe it uses USB

**Comment by pro4tlzz** [comment] 2023-01-20 15:04
I believe the issue is with unlocking with a fingerprint scanner maybe. I just changed motherboard and cpu so I got a new Windows 10 OS and I have had the issue for the first time.

I will try to speak to support.

**Comment by 4fosaefp** [comment] 2023-01-20 15:08
> I believe the issue is with unlocking with a fingerprint scanner maybe. I just changed motherboard and cpu so I got a new Windows 10 OS and I have had the issue for the first time.
> 
> I will try to speak to support.

No, I don't use fingerprint and also have the issue.

**Comment by roccolord** [comment] 2023-02-03 09:56
I use fingerprint, touch id, hello camera, and pin. On windows, mac, linux, on whaterver browser i can find this issue is present.

**Comment by phyzical** [comment] 2023-02-23 07:45
this one was bugging me enough i decided to give debugging it a crack, what i found is `lastActive` is never updated, and so after the first login it thinks its time to lock and the next tick of the setInverval fires itll lock again

https://github.com/bitwarden/clients/blob/master/libs/common/src/services/vaultTimeout/vaultTimeout.service.ts#L124

i will try to figure out why its not being updated and post a pr if so

**Comment by phyzical** [comment] 2023-02-23 09:13
so what i found is that the lastActive is only updated if
```
 this.ngZone.runOutsideAngular(() => {
      window.onmousedown = () => this.recordActivity();
      window.ontouchstart = () => this.recordActivity();
      window.onclick = () => this.recordActivity();
      window.onscroll = () => this.recordActivity();
      window.onkeypress = () => this.recordActivity();
    });
 ```
 and confirmed if i click something in the popup an autologout does occur.

Which makes sense (in my case using biometrics) as it never triggers any of the above window level functions

ive got a fix that works specifically for biometrics but im curious what your way of logging in is that could avoid keypresses @4fosaefp ?

**Comment by 4fosaefp** [comment] 2023-02-23 15:21
> so what i found is that the lastActive is only updated if
> 
> ```
>  this.ngZone.runOutsideAngular(() => {
>       window.onmousedown = () => this.recordActivity();
>       window.ontouchstart = () => this.recordActivity();
>       window.onclick = () => this.recordActivity();
>       window.onscroll = () => this.recordActivity();
>       window.onkeypress = () => this.recordActivity();
>     });
> ```
> 
> and confirmed if i click something in the popup an autologout does occur.
> 
> Which makes sense (in my case using biometrics) as it never triggers any of the above window level functions
> 
> ive got a fix that works specifically for biometrics but im curious what your way of logging in is that could avoid keypresses @4fosaefp ?

I'm using PIN because my pc doesn't support any other windows hello login methods.

**Comment by phyzical** [comment] 2023-02-24 00:00
@4fosaefp and that pin is an external windows popup im assuming? which wold also explain why you see the bug thanks 👍

**Comment by smithed** [comment] 2023-02-25 03:36
yes, pin is a popup that appears roughly analogous to UAC. Not sure if its related to the secure desktop.

thanks for looking into this, its very appreciated

**Comment by LeChatNoir666** [comment] 2023-04-18 15:53
Same Problem in Firefox 102.9 in private mode.
I can't even get User/Password filled because Bitwarden locks immediately... :-/
I wanted to switch from LastPass to Bitwarden but because of this I can't...
In Iron Browser it works like a charm...

> The issue does not occur if the vault timeout is set to "on browser restart".

Unfortunately this don't work for me, even User defined, Never aso..

> opened this issue on Mar 30, 2022

Wow... 
Any chance that it will be fixed or should I go back to LP?

**Comment by kapitainsky** [comment] 2023-04-18 16:05
There is fix being worked on:

https://github.com/bitwarden/clients/pull/4835

In the meantime when you unlock BW just click at something there or type in search field - it will initiate timer correctly and your timeout will be respected.

**Closed** 2023-05-03 19:28 UTC
Labels: bug, browser

**Comment by smithed** [comment] 2023-06-17 23:21
This was released in the .5 version, right? I'm still experiencing in firefox/windows. Should I make a new issue?

**Comment by henrypa** [comment] 2023-06-19 08:54
> This was released in the .5 version, right? I'm still experiencing in firefox/windows, (just locked/unlocked 4 times in a row). Should I make a new issue?

Same here, using the latest Firefox/Windows version and extension 2023.5.0. Bitwarden seems to be working correctly on macOS (Firefox), but the Windows version still locks the extension immediately after opening. Uncertain if this should also be fixed on the Windows side?

**Comment by phyzical** [comment] 2023-06-19 09:01
i can confirm its in the latest build and seems to have solved it for me, maybe theres some oddity around windows if you wanted to debug should just be a matter of confirming this isn't firing. https://github.com/bitwarden/clients/blob/browser-v2023.5.0/apps/browser/src/popup/app.component.ts#L69

**Comment by smithed** [comment] 2023-06-21 01:49
its very strange, actually -- it seems to work ok on my desktop (pin, but windows hello still) but on laptop (fingerprint) its happened again yesterday.

Looking at the linked file, i see there is a specific set of events that count as activity -- I could see some weird conditions where the windows hello dialog is treated differently (I saw another issue indicating while its not on Secure Desktop its still handled through a "more secure" mechanism) but in that case the pin would have the same issue.

I'll poke around and see if I can find a more stable reproducing case, or see if I can get it to happen on the desktop as well.

**Comment by spsilk** [comment] 2023-08-01 10:05
I'm also (still) experiencing this issue in Firefox on Win 10 with the following config: 

Windows:
Edition	Windows 10 Pro
Version	21H2
OS build	19044.3086
Experience	Windows Feature Experience Pack 1000.19041.1000.0

Firefox: 115.0.2 (64-bit)

Desktop App:
Version 2023.5.1
Shell 24.1.1
Renderer 112.0.5615.50
Node 18.14.0
Architecture x64

Firefox Extension:
Version: 2023.7.1

I'm unlocking with the built-in fingerprint reader on a Lenovo x380 Yoga laptop. 

Same behaviour as described by some users above: if the extension is locked, when I unlock (at least with fingerprint, haven't compared with password unlock recently), it will often re-lock within a few seconds. Sometimes it will do this multiple times in a row. Like just now I had to unlock it 5 or 6 times before it stayed unlocked. Clicking to different windows or different tabs in Firefox seems to exacerbate the situation. 

Thanks.

**Comment by boardlord1** [comment] 2023-08-08 08:01
> I'm also (still) experiencing this issue in Firefox on Win 10 with the following config:
> 
> Windows: Edition Windows 10 Pro Version 21H2 OS build 19044.3086 Experience Windows Feature Experience Pack 1000.19041.1000.0
> 
> Firefox: 115.0.2 (64-bit)
> 
> Desktop App: Version 2023.5.1 Shell 24.1.1 Renderer 112.0.5615.50 Node 18.14.0 Architecture x64
> 
> Firefox Extension: Version: 2023.7.1
> 
> I'm unlocking with the built-in fingerprint reader on a Lenovo x380 Yoga laptop.
> 
> Same behaviour as described by some users above: if the extension is locked, when I unlock (at least with fingerprint, haven't compared with password unlock recently), it will often re-lock within a few seconds. Sometimes it will do this multiple times in a row. Like just now I had to unlock it 5 or 6 times before it stayed unlocked. Clicking to different windows or different tabs in Firefox seems to exacerbate the situation.
> 
> Thanks.

I can echo this wit the same config. Sometimes I need to unlock with Windows Hello (face recognition) in order to have the vault stay unlocked.

**Comment by kapitainsky** [comment] 2023-08-08 08:09
1 - this is a ticket for macOS/Firefox issue. And this is already fixed and ticket is closed.
2 - as clearly now there is an issue with Windows/Firefox I suggest you open new ticket to give it more visibility (and mention this ticket and PR with fix https://github.com/bitwarden/clients/pull/4835)
3 - good thing is that it is probably very similar thing with some element missing which is Windows specific

**Comment by dellskin** [comment] 2023-09-18 17:35
Agree with @kapitainsky, this is an ongoing problem with Windows and #5987 needs to be addressed.

**Comment by edinaldo12** [comment] 2023-11-02 12:30
The same problem here:
MacOS: 13.5.2 Ventura
Firefox Developer Edition: 120.0b5 (64-bits)
BitWarden: 2023.9.2
Server version: 2023.10.0
