### ISSUE TITLE
Windows Client - after deleting any login the very first login is selected

### ISSUE THREAD

**Issue by dmz73vu** [bitwarden/clients#2595] opened 2022-01-04 00:02 UTC
### Steps To Reproduce

1. have 100s of logins
2. go to login 150
3. delete it
4. login 1 is now selected
5. go to login 153
6. delete it
7. login 1 is now selected

### Expected Result

After deleting a login either next or previous login should be selected

### Actual Result

After deleting a login the very first login is always selected

### Operating System

Windows

### Operating System Version

Windows 10

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 1.30.0 Shell 14.2.0 Renderer 93.0.4577.82 Node 14.17.0 Architecture x64

**Comment by djsmith85** [comment] 2022-07-21 09:45
Closing this as duplicate of https://github.com/bitwarden/clients/issues/2564 which has more recent traction/examples.

**Closed by djsmith85** 2022-07-21 09:45 UTC
Labels: bug, desktop
