### ISSUE TITLE
Uncaught Exception: TypeError: Cannot read properties of null (reading 'webContents')

### ISSUE THREAD

**Issue by tebbsy** [bitwarden/clients#12070] opened 2024-11-20 17:45 UTC
### Steps To Reproduce

1. Launch Bitwarden desktop application
2. The error message appears in a modal box after random amount of time, and keep reappearing

### Expected Result

This message NOT to appear

### Actual Result

The following error appears in a modal box that when closed keeps reappearing, and the app is unusable.
App needs to be force quit and restarted

'Uncaught Exception:
TypeError: Cannot read properties of null (reading 'webContents’)
at /Applications/Bitwarden.app/Contents/Resources/app.asar/main.js:85790:45'

### Operating System

macOS

### Operating System Version

Sonoma 14.6.1

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2024.11.1 (33298)

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment] 2024-11-26 21:22
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by tebbsy** [comment] 2024-11-27 10:14
Hi, and thanks for your response.

This is a screengrab of the error message. It tends to appear after long
periods of inactivity, laptop going to sleep mode too

[image: image.png]

Regards,

James

**Comment by trmartin4** [comment] 2024-12-11 02:25
@tebbsy do you have the DuckDuckGo integration enabled?  If so this could be related to https://github.com/bitwarden/clients/issues/12190.

**Comment by tebbsy** [comment] 2024-12-12 09:24
Yes, I do.

James

**Comment by trmartin4** [comment] 2024-12-23 18:34
@tebbsy can you verify if this still occurs with the `2024.12.0` release of the desktop client?  We addressed some issues with the DuckDuckGo integration that could have resulted in this behavior.

**Comment by tebbsy** [comment] 2024-12-23 18:44
Hi, looks like you’ve fixed it. It hasn’t happened again. A job well done,JamesOn 23 Dec 2024, at 18:34, Todd Martin ***@***.***> wrote:﻿
@tebbsy can you verify if this still occurs with the 2024.12.0 release of the desktop client?  We addressed some issues with the DuckDuckGo integration that could have resulted in this behavior.

**Comment by trmartin4** [comment] 2024-12-23 21:03
Closing this issue as it was addressed with better message handling for the IPC connection to DuckDuckGo in https://github.com/bitwarden/clients/pull/11987.

**Closed by trmartin4** 2024-12-23 21:03 UTC
Labels: bug, desktop
