### ISSUE TITLE
bit-notification-bar-spacer height May Displace Other Elements/Components On Page

### ISSUE THREAD

**Issue by atb-brown** [bitwarden/clients#7152] opened 2023-12-08 20:03 UTC
### Steps To Reproduce

1. Go to a website without registered Bitwarden credentials
2. Log in
3. Observe the banner `Should Bitwarden remember this password for you?`
4. Some elements _may_ shift in the website.

### Expected Result

The banner appears, but does not affect the rendering of the site's page by shifting things around.

### Actual Result

The banner appears, but may shift components on the web page.

### Screenshots or Videos

Unfortunately, I cannot provide a screenshot of the website where I'm experiencing the issue because it is an internal/proprietary website.

Here is a crude illustration of what I'm seeing:
<img width="1361" alt="image" src="https://github.com/bitwarden/clients/assets/6782887/efbabbdb-3e1f-4571-b268-e5466d0b5d37">

As you can see, there's a bottom banner element that's fully visible on the left, but it's getting shifted down on the right-hand side when the Bitwarden `bit-notification-bar-spacer` is present.

### Additional Context

It appears that the issue I'm experiencing is caused by having the `height` styling on the `bit-notification-bar-spacer`.

https://github.com/bitwarden/clients/blob/483a197e4dadb9ef932ce18f9d554a6fcb867a1a/apps/browser/src/autofill/content/notification-bar.ts#L884

I've turned the height off in Chrome developer mode, and the notification bar appears to be displaying normally and the other elements on the page haven't shifted. I'm not a JavaScript expert, but is this `height` field necessary?

### Operating System

macOS

### Operating System Version

13.6 (22G120)

### Web Browser

Chrome

### Browser Version

Version 120.0.6099.71 (Official Build) (arm64)

### Build Version

2023.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment] 2023-12-25 17:19
Hi there,

I am unable to reproduce this issue or find other reports of websites that are publicly accessible to test this. I have escalated this issue for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by djsmith85** [comment] 2024-02-23 11:34
Duplicate of https://github.com/bitwarden/clients/issues/2231

**Comment by djsmith85** [comment] 2024-02-23 11:34
Hi @atb-brown

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/clients/issues/2231.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2024-02-23 11:34 UTC
Labels: bug, browser
