### ISSUE TITLE
ctrl + shift + L fill in stopped working after upgrade to Brave 1.35.100 (chromium 98)

### ISSUE THREAD

**Issue by Sartan4455** [bitwarden/clients#2307] opened 2022-02-03 17:12 UTC
### Steps To Reproduce

1. Go to any site with credentials(tested not working on jira, box,  github)
2. ctrl + shift + L
3. Nothing filled in
4. right click and fill in or use extension pin works

### Expected Result

After hitting short cut command, fills in username and password

### Actual Result

nothing is filled in

worked in previous build

### Operating System

Linux

### Operating System Version

ubuntu 21.10

### Web Browser

Brave

### Browser Version

Version 1.35.100

### Build Version

Version 1.35.100 Chromium: 98.0.4758.87 (Official Build) (64-bit)

**Comment by Sartan4455** [comment] 2022-02-03 17:14
testing actual chrome official build
Short cut works.
Version 98.0.4758.80 (Official Build) (64-bit)
Could be a brave bug? or could be bitwarden not sure

**Comment by Sartan4455** [comment] 2022-02-03 17:23
uninstalling and reinstalling the extension fixed it.
So ok work around, just annoying.

**Comment by djsmith85** [comment] 2022-05-30 14:16
Closing this issue as it appears the originally posted problem has been resolved. Likely an issue with Brave. If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.

**Closed by djsmith85** 2022-05-30 14:16 UTC
Labels: bug, browser
