### ISSUE TITLE
"Master password re-prompt" broken in desktop app

### ISSUE THREAD

**Issue by bannmann** [bitwarden/clients#6340] opened 2023-09-19 16:01 UTC
### Steps To Reproduce

1. Enable 'Master password re-prompt' in a test entry and save it.
2. Try any of the following: edit the entry, copy the password or toggle visibility
3. When prompted, enter the correct master password.

### Expected Result

The master password is accepted and the action chosen in step 2 (editing / copying / displaying) is performed.

### Actual Result

The password prompt stays on screen. No error message appears, but the developer tools console shows the following:

```
Error: Invalid parameters.
    at useClass.<anonymous> (crypto.service.ts:244:13)
    at Generator.next (<anonymous>)
    at r (main.js:1:188749)
    at c.invoke (zone.js:375:26)
    at Object.onInvoke (ng_zone.ts:423:29)
    at c.invoke (zone.js:374:52)
    at o.run (zone.js:134:43)
    at zone.js:1278:36
    at c.invokeTask (zone.js:409:31)
    at Object.onInvokeTask (ng_zone.ts:408:29)
    at C (zone.js:1214:31)
    at zone.js:1121:17
    at zone.js:1137:33
    at a (main.js:1:456407)
    at c.invoke (zone.js:375:26)
    at Object.onInvoke (ng_zone.ts:423:29)
    at c.invoke (zone.js:374:52)
    at o.run (zone.js:134:43)
    at zone.js:1278:36
    at c.invokeTask (zone.js:409:31)
```

### Additional Context

I was not able to access an entry with "Master password re-prompt" on the mobile app or the Firefox extension, either. Maybe the error is in a shared part of the code base?

Note: when entering a bogus master password, the same behavior can be seen, instead of a message like "Wrong master password."

### Operating System

Windows

### Operating System Version

Windows 10, 22H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2023.8.4 Shell 24.8.3 Renderer 112.0.5615.204 Node 18.14.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment] 2023-09-19 17:00
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/6153. 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by Neonwarden** 2023-09-19 17:00 UTC
Labels: bug, desktop
