### ISSUE TITLE
Dialogs displayed by the BitWarden desktop app (snap) show squares □□□□□□□□ instead of text

### ISSUE THREAD

**Issue by Flimm** [bitwarden/clients#3484] opened 2022-09-10 10:27 UTC
### Steps To Reproduce

1. Install BitWarden on Ubuntu 22.04 LTS using snap: `sudo snap install bw`, and log in with your account
2. Click "File", "Export vault", enter the options, and click the download button.
3. Or click "Help", "About"

### Expected Result

I expect the dialogs that appear to contain legible text.

### Actual Result

Instead, the dialogs that appear contain squares □□□□□□□□ instead of text, see screenshots.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/355454/189479054-5487c4bc-d1a0-4675-87d1-ed55e518ce93.png)

![image](https://user-images.githubusercontent.com/355454/189479084-d90dd9e8-a8db-4875-8d0b-050967b1ecd8.png)

![image](https://user-images.githubusercontent.com/355454/189479224-c942af35-c8e8-4ccc-914d-a453315ce9ef.png)

### Operating System

Linux

### Operating System Version

Ubuntu 22.04

### Installation method

Snap

### Build Version

2022.8.0 2022-08-09

**Comment by djsmith85** [comment] 2022-09-10 10:51
Hi @Flimm  and thank you for your report. This seems to be a duplicate of https://github.com/bitwarden/clients/issues/2628. 

Closing this now.

**Closed by djsmith85** 2022-09-10 10:51 UTC
Labels: bug, desktop
