### ISSUE TITLE
Random Password Generator Bug

### ISSUE THREAD

**Issue by Swatto86** [bitwarden/clients#12477] opened 2024-12-19 11:20 UTC
### Steps To Reproduce

When filling out a registration form for a new account (doesn't matter on which website), the Bitwarden browser extension pops up to fill in the password field with a randomly generated password, this is fine but then if you look at the Password History within Bitwarden extension itself to see what was generated (in case you forgot to save the entry) it is littered with multiple generated passwords at the same time so you do not know which is which.

### Expected Result

The password history within Bitwarden contains 1 or 2 entries for a recently generated random password.

### Actual Result

The password history contains a long list of entries.

### Operating System

Windows

### Web Browser

Firefox

### Build Version

2024.11.2

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-12-19 11:54
Duplicate of https://github.com/bitwarden/clients/issues/12047

**Comment by djsmith85** [comment] 2024-12-19 11:58
Hi @Swatto86!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/12047

Which already got addressed with https://github.com/bitwarden/clients/pull/12226 and is included in 2024.12.0

This issue will now be closed.

Thanks!**

**Closed by djsmith85** 2024-12-19 11:58 UTC
Labels: bug, browser
