### ISSUE TITLE
Unable to copy passwords on browser

### ISSUE THREAD

**Issue by LVMVRQUXL** [bitwarden/clients#6274] opened 2023-09-13 09:44 UTC
### Steps To Reproduce

1. Go to any secured credential.
2. Click on the 3 vertical dots near the credential.
3. Click on copy password.
4. Type the main password.
5. Click on `Ok`.

### Expected Result

Should copy the password to the clipboard.

### Actual Result

A notification is displayed but the password is not correctly copied to the clipboard.

### Screenshots or Videos

![Capture d’écran 2023-09-13 à 11 39 53](https://github.com/bitwarden/clients/assets/43500570/6edcd3f2-1159-4d84-9aac-e0ef831604ae)
![Capture d’écran 2023-09-13 à 11 39 57](https://github.com/bitwarden/clients/assets/43500570/35d4e584-c8c0-49fc-af34-d23cfede1f9f)

### Operating System

macOS

### Operating System Version

Ventura 13.5.2

### Web Browser

Safari

### Browser Version

16.6

### Build Version

2023.8.4

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by wasee292** [comment] 2023-09-13 11:16
I too am facing the issue. It is not only for copying the password, I can't even reveal the password.
Apps in iOS, iPadOS, Android, macOS are also effected along with the extensions of Chrome, Safari

**Comment by pschauhan480** [comment] 2023-09-13 15:59
Facing the same issue on all the clients

**Comment by LVMVRQUXL** [comment] 2023-09-13 17:10
@wasee292 @pschauhan480 For information, @Krychaz says that the engineering team is investigating this bug and gives more details about it in [this comment](https://github.com/bitwarden/clients/issues/6273#issuecomment-1717284795).

**Comment by atjbramley** [comment] 2023-09-13 17:55
Hi @LVMVRQUXL, 

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/6273#issuecomment-1717284795

While the OSs are different, I can confirm that the underlying issue is the same. 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by atjbramley** 2023-09-13 17:55 UTC
Labels: bug, browser
