### ISSUE TITLE
Unable to render properly

### ISSUE THREAD

**Issue by joaortizro** [bitwarden/clients#6766] opened 2023-11-02 13:43 UTC
### Steps To Reproduce

1. Open the bitwarden client from the desktop

### Expected Result

Render the email, password fields

### Actual Result

a white rectangle

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/20843665/fcc37d4f-1f70-409e-afb4-33bb24204d64)

### Operating System

Linux

### Operating System Version

Linux Mint 21.2 Cinnamon

### Installation method

Other

### Build Version

Version 2023.9.3 Shell 25.9.1 Renderer 114.0.5735.289 Node 18.15.0 Architecture x64

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by afro-systems** [comment] 2023-11-02 16:42
I'm having the same issue on Fedora 38 KDE Plasma.

Version 2023.10.0
Shell 25.9.1
Renderer 114.0.5735.289
Node 18.15.0
Architecture x64

**Comment by jtodddd** [comment] 2023-11-02 18:18
Hi there,

Will you tell me your installation method please?

**Comment by joaortizro** [comment] 2023-11-02 19:01
Flatpak

**Comment by AlexSBlackburn** [comment] 2023-11-02 19:26
I'm having the same issue on Linux Mint 21.2 Cinnamon. It started for me after the latest update to the Kernel.

**Comment by jtodddd** [comment] 2023-11-02 20:23
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/6757. 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by jtodddd** 2023-11-02 20:23 UTC
Labels: bug, desktop
