### ISSUE TITLE
Changes/edits do NOT show after saving item

### ISSUE THREAD

**Issue by Kamika007z** [bitwarden/clients#12382] opened 2024-12-12 20:27 UTC
### Steps To Reproduce

1. Open Bitwarden,
2. Select any item,
3. Click on Edit on the bottom,
4. Make your changes and click on Save

From this, you do not see your saved changes on the Desktop application unless you click off on another item, then back onto it. Additionally, the Name of the item does not update to reflect any changes made unless you click on File > "Sync vault".

### Expected Result

Any changes made, then saved, should immediately be updated as it used to work.

### Actual Result

It looks like the Bitwarden Desktop application isn't updating your changes as soon as you click on "Save".

If you edit any existing item, make changes to it, then click on save, the updated information does **not** show up immediately, making it seem like the changes had not taken effect.

You have to click off on another item then click back on it in order to see your changes within the item. This effects the name, login information, TOTP key, notes, everything.

Additionally, I have found that the "Name" of the item does (in the center column) does not immediately update either unless you click on File > "Sync vault".

I have been seeing this issue since a few builds back across multiple machines on both Windows and macOS operating systems.

### Additional Context

Unless this is a change made on purpose, it is causing A LOT of confusion for myself as well as others whom also use the Bitwarden desktop application. Maybe make this an option if it is an intended change (though I don't know why it would be).

PLEASE HELP!

Thank you!

### Operating System

Windows, macOS

### Operating System Version

Windows 10/11, macOS

### Installation method

Microsoft Store

### Build Version

Version 2024.12.0 SDK 'main (edee180)' Shell 32.1.1 Renderer 128.0.6613.137 Node 20.17.0 Architecture x64

### Issue Tracking Info

- [ ] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by 3v6bih2w** [comment] 2024-12-12 21:22
Same issue on Desktop version.

I also noticed that the right-click on the main item/title and choose "copy password" was not updated or did not match the clipboard copy button to the right of the password under Item Information after changing to a new password.

**Comment by mossicrue** [comment] 2024-12-13 09:53
Same here. Logging out from the app and re-login didn't work.

Version 2024.11.2
Shell 32.1.1
Renderer 128.0.6613.137
Node 20.17.0
Architecture x64

**Comment by Kamika007z** [comment] 2024-12-13 18:18
> This appears to be a duplicate of #12022.

It would appear to be but that only explains part of the issue so I do not want only one aspect of it fixed as the issue is not only within the notes as shown, it's everywhere within the Desktop application. No changes show up on any field that is updated then saved.

**Comment by AriZoNaiCe** [comment] 2024-12-13 18:29
In addition to what Kamika007z mentioned, this bug also hits the Edge and Firefox browser extensions (likely others, but I haven't tested).  If you update a password, save the password, and then immediately click the "copy password" button, it will copy the old password.  You need to click onto a different item and then back to the recently-saved item to copy the newly-saved password.

**Comment by Kamika007z** [comment] 2024-12-13 18:35
> The discussion of Issue #12022 references both Windows and macOS versions of the Desktop app, and mentions problems occurring when editing login items in addition to secure notes.

Thank you. Since this issue was reported a month ago, is there an estimated time for resolution? It’s quite a noticeable problem, and it’s concerning that it wasn’t identified before newer versions were released.

Thank you in advance!

**Comment by Locktutor** [comment] 2024-12-13 22:47
I am seeing the same issue using the Mac app, Version 2024.11.0 (33157)
Anytime I make an edit and save it, the change is not visible until you either click edit again, or click away and back.

**Comment by rmcdowell-bitwarden** [comment] 2024-12-31 06:57
Hi there!

Thank you for your report, it seems like it is a duplicate of this one  https://github.com/bitwarden/clients/issues/12022

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

My apologies for not addressing this sooner, this fell through the cracks of my queue. We're not able to provide an ETA for when this will be resolved, but our Development team is aware of this and hopes to have this behavior addressed in an upcoming release of Bitwarden.

This issue will now be closed.

Thanks!

**Closed by rmcdowell-bitwarden** 2024-12-31 06:57 UTC
Labels: bug, desktop
