### ISSUE TITLE
Autofill doesn'work any longer

### ISSUE THREAD

**Issue by grauerpanther-bitwarden** [bitwarden/clients#11435] opened 2024-10-07 09:51 UTC
### Steps To Reproduce

1. Go to a website, which is integrated in Bitwarden
2. Click on login
3. Nothing happens, Bitwarden shows me no options

### Expected Result

Autofill-function hast to work correct.

### Actual Result

I am using the newest version Bitwarden, Chrome under Windows 10. Since today morning the autill-option doesn't word. No reaction from the bitwarden-Software. The Chrome-Browser-extension is activated. Also have I made a new start. 

### Operating System

Windows

### Operating System Version

Windows 10

### Web Browser

Chrome

### Browser Version

Version 129.0.6668.90 (Offizieller Build) (64-Bit)

### Build Version

Version 129.0.6668.90 (Offizieller Build) (64-Bit)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment] 2024-10-07 13:33
Hi @grauerpanther-bitwarden ,

Thank you for this report.

This appears to be a duplicate of the problem described in https://github.com/bitwarden/clients/issues/10814.

Please see this comment for details surrounding the problem(https://github.com/bitwarden/clients/issues/10814#issuecomment-2359336680)

**Closed by daniellbw** 2024-10-07 13:33 UTC
Labels: bug, browser

**Comment by grauerpanther-bitwarden** [comment] 2024-10-07 18:26
Hello, the problem still exists. The workaround does not work. I am not able to log in without copying from the vault. I also do not use Linus with Firefox. But Windows 10 with the Bitwarden version 

Version 2024.9.0
Shell 32.0.1
Renderer 128.0.6613.36
Node 20.16.0
Architecture x64

with Chrome Version 129.0.6668.90 (Offizieller Build) (64-Bit). Autofill does not work with Chrome or Edge, which I also tried. Deactivating the browser extension and reactivating the browser extension also doesn't help. Disabling the browser extension and only using the Bitwarden programme under Windows does not solve the problem, autofill does not work. I need a remedy here as quickly as possible.
