### ISSUE TITLE
Can't login on PayPal with Bitwarden unlocked.

### ISSUE THREAD

**Issue by fr-gg** [bitwarden/clients#6084] opened 2023-08-22 13:35 UTC
### Steps To Reproduce

1. Go to "https://www.paypal.com/signin"
2. Enter your email
3. Click "Next"
4. See error message

### Expected Result

I expect to login on PayPal without issues, it works fine when I lock my vault. 

### Actual Result

![image](https://github.com/bitwarden/clients/assets/93214699/cabfb79a-6eae-401a-a5be-e483002bf9d1)
(I removed my email but normally there is an email)

### Additional Context

Locking the vault solves the problem.

### Operating System

Windows

### Operating System Version

Windows 11

### Web Browser

Brave

### Browser Version

v1.57.49

### Build Version

2023.7.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2023-08-22 14:02
Duplicate of https://github.com/bitwarden/clients/issues/5880

**Closed by djsmith85** 2023-08-22 14:02 UTC
Labels: bug, browser

**Comment by blur231** [comment] 2024-01-02 19:17
Same issue on Windows.
