### ISSUE TITLE
Autofill menu not showing up

### ISSUE THREAD

**Issue by D4VID0x2** [bitwarden/clients#11430] opened 2024-10-06 07:32 UTC
### Steps To Reproduce

1. Unlock my vault
2. Go to any site with a login form
3. Click in the login fields (with autofill menu on form fields enabled)

### Expected Result

The autofill menu shows up with my saved credentials for that site

### Actual Result

No menu shows up and there is an error in the console

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/792a6d12-fdbf-4242-8c2b-0a070b38e65f)

### Additional Context

Started happening recently. Probably after the last update.

### Operating System

Linux

### Operating System Version

Archlinux

### Web Browser

Firefox

### Browser Version

131.0

### Build Version

2024.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by BBGhub** [comment] 2024-10-07 00:32
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/clients/issues/10815

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

You may also find a workaround for your specific browser within the GitHub issues comments above.

This issue will now be closed.

Thanks!

**Closed by BBGhub** 2024-10-07 00:32 UTC
Labels: bug, browser
