### ISSUE TITLE
Latest browser extension in Firefox causes autofill menu to popup, even when set to off

### ISSUE THREAD

**Issue by Olifant1990** [bitwarden/clients#11254] opened 2024-09-26 11:58 UTC
### Steps To Reproduce

Go to a login field, click on it and the menu pops up

### Expected Result

The popup menu not to be showed

### Actual Result

Popup is opening

### Screenshots or Videos

![afbeelding](https://github.com/user-attachments/assets/535cb5b1-a163-4e78-8048-0e1cd8149612)
![afbeelding](https://github.com/user-attachments/assets/6069c116-e6ed-4f8d-9347-73f12e388116)
![afbeelding](https://github.com/user-attachments/assets/015a9336-c2c6-41db-9522-a4fb26d66e18)

### Operating System

Windows

### Operating System Version

11

### Web Browser

Firefox

### Browser Version

Latest

### Build Version

2024.9.1

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment] 2024-09-26 12:07
Hi there!

Thank you for your report, it seems like it is a duplicate of this one #11173 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by daniellbw** 2024-09-26 12:07 UTC
Labels: bug, browser
