### ISSUE TITLE
[bug][firefox] locked plugin unlocks in private mode

### ISSUE THREAD

**Issue by jcgonnard** [bitwarden/clients#5230] opened 2023-04-17 18:39 UTC
### Steps To Reproduce

1. Get your plugin locked
2. Try to auto-fill using *Ctrl+Shif+L**
3. Unlock page opens in new tab => Displays **private mode** warning
4. Enter your password =>  Vault is unlocked in **private mode**. Plugin is not showing the locker icon but clicking it ask for your password to unlock

### Expected Result

**Step 3** should not display **private mode** warning
**step 4** should unlock in standard mode

### Actual Result

**Step 3** Displays **private mode** warning
**step 4** Vault is unlocked in **private mode**. Plugin is not showing the locker icon but clicking it ask for your password to unlock

### Screenshots or Videos

[https://share.gonnard.me/s/pFjYBs8QPDcYPGg](url)

### Additional Context

- Firefox 111.0
- Linux gentoo
- First occurrence in plugin version 2023.3.0 

### Operating System

Linux

### Operating System Version

Linux home 6.2.2-gentoo #1 SMP PREEMPT_DYNAMIC Tue Mar 14 08:48:35 CET 2023 x86_64 AMD Ryzen 9 5950X 16-Core Processor AuthenticAMD GNU/Linux

### Web Browser

Firefox

### Browser Version

111.0

### Build Version

2023.3.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jcgonnard** [comment] 2023-04-17 18:41
Sorry, duplicates issue https://github.com/bitwarden/clients/pull/5116

**Comment by djsmith85** [comment] 2023-04-26 15:34
Duplicate of #5115

**Closed by djsmith85** 2023-04-26 15:34 UTC
Labels: bug, browser
