### ISSUE TITLE
"There are no collections to list" until ownership dropdown is changed.

### ISSUE THREAD

**Issue by mstatectc** [bitwarden/clients#8311] opened 2024-03-12 19:48 UTC
### Steps To Reproduce

1. Login to the Bitwarden desktop client.
2. Click on a collection in the bottom left corner
3. Click on the plus button (to add an item to the collection)
4. Scroll to the bottom of the new item
5. Under **Collections** see "There are no collections to list." (Note: the **Who owns this item** defaults, correctly, to the organization.)
6. Change the **Who owns this item** to the individual user
7. Change the **Who owns this item** back to the organization.
8. The accessible collections now show underneath **Collections**

### Expected Result

If the organization is already selected, I expect the accessible collections to available without needing to change the **Who owns this item** dropdown.

### Actual Result

Collections aren't listed until the **Who owns this item** dropdown is changed.

### Screenshots or Videos

First entry into new item:
![image](https://github.com/bitwarden/clients/assets/50374511/d53e50eb-b1c2-4eff-9220-240c9e9242c5)
User selects themselves:
![image](https://github.com/bitwarden/clients/assets/50374511/e25d88d4-3b51-4788-9701-e6ffad469eb7)
After user changes it back to the org:
![image](https://github.com/bitwarden/clients/assets/50374511/b180c72b-9f86-4220-8b70-6944755806a8)

### Additional Context

The desktop client is connecting to a self-hosted Bitwarden server (v2024.2.3). 

### Operating System

Windows

### Operating System Version

Windows 11 Education 23H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-03-12 20:23
Duplicate of https://github.com/bitwarden/clients/issues/8258

**Comment by djsmith85** [comment] 2024-03-12 20:25
Hello @mstatectc,

Thank you for this report. It seems like a duplicate of the https://github.com/bitwarden/clients/issues/8258 linked above.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This report will now be closed.

Kind regards,
Daniel

**Closed by djsmith85** 2024-03-12 20:25 UTC
Labels: bug, desktop
