### ISSUE TITLE
Decrypt error when using multiple accounts

### ISSUE THREAD

**Issue by rajitha-d** [bitwarden/clients#4986] opened 2023-03-11 11:11 UTC
### Steps To Reproduce

1. Open the Bitwarden desktop app
2. Add 2 or more accounts
3. Lock all vaults
4. Switch to a different account
5. Unlock with biometrics, pin, or master password

### Expected Result

I expect to see all my vault items without having to sync manually

### Actual Result

'error: cannot decrypt' on every vault item

### Screenshots or Videos

![Bitwarden_bug](https://user-images.githubusercontent.com/123333207/224480665-5759d6ce-0596-43a4-9528-e8f644890d37.png)

### Additional Context

Version: 2023.2.0

### Operating System

Windows, Linux

### Operating System Version

Windows 10 Pro x64, Debian 11.6 'Bullseye', Debian Testing

### Installation method

Microsoft Store, Snap

### Build Version

2023.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2023-07-05 07:28
Duplicate of https://github.com/bitwarden/clients/issues/3057

**Closed by djsmith85** 2023-07-05 07:28 UTC
Labels: bug, desktop
