### ISSUE TITLE
La Barra de Menu no se muestra correctamente (Edit Menu, View Menu, Acount Menu Or Help Menu)

### ISSUE THREAD

**Issue by robertolabarca** [bitwarden/clients#3679] opened 2022-10-04 01:32 UTC
### Steps To Reproduce

Click en opciones de la barra de menu- (Edit Menu, View Menu, Acount Menu Or Help Menu)

### Expected Result

**_File_** Menu y **_Window_** Menu . Se muestran  OK

### Actual Result

La Barra de Menu no se muestra correctamente (Edit Menu, View Menu, Acount Menu Or Help Menu)

### Screenshots or Videos

![screen01](https://user-images.githubusercontent.com/3769893/193714530-5c11b774-f5c4-4c9b-b6c8-949b76400414.jpg)

### Additional Context

**by shell:**

:/$ **bitwarden**
(node:13401) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `bitwarden --trace-deprecation ...` to show where the warning was created)
/usr/share/libdrm/amdgpu.ids: No such file or directory
Error org.freedesktop.DBus.Error.Failed: cannot find desktop file "/var/lib/snapd/desktop/applications/bitwarden_Bitwarden.desktop"
** Message: 21:25:29.228: Remote error from secret service: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.456" (uid=1000 pid=13401 comm="/snap/bitwarden/76/bitwarden --no-sandbox --enable" label="snap.bitwarden.bitwarden (enforce)") interface="org.freedesktop.Secret.Service" member="OpenSession" error name="(unset)" requested_reply="0" destination=":1.78" (uid=1000 pid=2367 comm="/usr/bin/gnome-keyring-daemon --start --foreground" label="unconfined")
** Message: 21:25:29.261: Remote error from secret service: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.457" (uid=1000 pid=13401 comm="/snap/bitwarden/76/bitwarden --no-sandbox --enable" label="snap.bitwarden.bitwarden (enforce)") interface="org.freedesktop.Secret.Service" member="OpenSession" error name="(unset)" requested_reply="0" destination=":1.78" (uid=1000 pid=2367 comm="/usr/bin/gnome-keyring-daemon --start --foreground" label="unconfined")
** Message: 21:25:29.348: Remote error from secret service: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.458" (uid=1000 pid=13401 comm="/snap/bitwarden/76/bitwarden --no-sandbox --enable" label="snap.bitwarden.bitwarden (enforce)") interface="org.freedesktop.Secret.Service" member="OpenSession" error name="(unset)" requested_reply="0" destination=":1.78" (uid=1000 pid=2367 comm="/usr/bin/gnome-keyring-daemon --start --foreground" label="unconfined")
** Message: 21:25:29.358: Remote error from secret service: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.458" (uid=1000 pid=13401 comm="/snap/bitwarden/76/bitwarden --no-sandbox --enable" label="snap.bitwarden.bitwarden (enforce)") interface="org.freedesktop.Secret.Service" member="OpenSession" error name="(unset)" requested_reply="0" destination=":1.78" (uid=1000 pid=2367 comm="/usr/bin/gnome-keyring-daemon --start --foreground" label="unconfined")
** Message: 21:25:29.358: Remote error from secret service: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.458" (uid=1000 pid=13401 comm="/snap/bitwarden/76/bitwarden --no-sandbox --enable" label="snap.bitwarden.bitwarden (enforce)") interface="org.freedesktop.Secret.Service" member="OpenSession" error name="(unset)" requested_reply="0" destination=":1.78" (uid=1000 pid=2367 comm="/usr/bin/gnome-keyring-daemon --start --foreground" label="unconfined")
** Message: 21:25:29.372: Remote error from secret service: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.459" (uid=1000 pid=13401 comm="/snap/bitwarden/76/bitwarden --no-sandbox --enable" label="snap.bitwarden.bitwarden (enforce)") interface="org.freedesktop.Secret.Service" member="OpenSession" error name="(unset)" requested_reply="0" destination=":1.78" (uid=1000 pid=2367 comm="/usr/bin/gnome-keyring-daemon --start --foreground" label="unconfined")
** Message: 21:25:29.430: Remote error from secret service: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.460" (uid=1000 pid=13401 comm="/snap/bitwarden/76/bitwarden --no-sandbox --enable" label="snap.bitwarden.bitwarden (enforce)") interface="org.freedesktop.Secret.Service" member="OpenSession" error name="(unset)" requested_reply="0" destination=":1.78" (uid=1000 pid=2367 comm="/usr/bin/gnome-keyring-daemon --start --foreground" label="unconfined")
** Message: 21:25:29.452: Remote error from secret service: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.461" (uid=1000 pid=13401 comm="/snap/bitwarden/76/bitwarden --no-sandbox --enable" label="snap.bitwarden.bitwarden (enforce)") interface="org.freedesktop.Secret.Service" member="OpenSession" error name="(unset)" requested_reply="0" destination=":1.78" (uid=1000 pid=2367 comm="/usr/bin/gnome-keyring-daemon --start --foreground" label="unconfined")
** Message: 21:25:30.323: Remote error from secret service: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.462" (uid=1000 pid=13401 comm="/snap/bitwarden/76/bitwarden --no-sandbox --enable" label="snap.bitwarden.bitwarden (enforce)") interface="org.freedesktop.Secret.Service" member="OpenSession" error name="(unset)" requested_reply="0" destination=":1.78" (uid=1000 pid=2367 comm="/usr/bin/gnome-keyring-daemon --start --foreground" label="unconfined")
** Message: 21:25:30.333: Remote error from secret service: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.463" (uid=1000 pid=13401 comm="/snap/bitwarden/76/bitwarden --no-sandbox --enable" label="snap.bitwarden.bitwarden (enforce)") interface="org.freedesktop.Secret.Service" member="OpenSession" error name="(unset)" requested_reply="0" destination=":1.78" (uid=1000 pid=2367 comm="/usr/bin/gnome-keyring-daemon --start --foreground" label="unconfined")
(node:13401) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'setContextMenu')
    at TrayMain.updateContextMenu (/snap/bitwarden/76/resources/app.asar/main.js:48772:23)
    at MessagingMain.updateTrayMenu (/snap/bitwarden/76/resources/app.asar/main.js:50734:28)
    at MessagingMain.onMessage (/snap/bitwarden/76/resources/app.asar/main.js:50668:22)
    at MessagingMain.<anonymous> (/snap/bitwarden/76/resources/app.asar/main.js:50659:151)
    at Generator.next (<anonymous>)
    at /snap/bitwarden/76/resources/app.asar/main.js:50638:71
    at new Promise (<anonymous>)
    at messaging_main_awaiter (/snap/bitwarden/76/resources/app.asar/main.js:50634:12)
    at IpcMainImpl.<anonymous> (/snap/bitwarden/76/resources/app.asar/main.js:50659:79)
    at IpcMainImpl.emit (node:events:526:28)
(node:13401) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
** Message: 21:25:32.187: Remote error from secret service: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.465" (uid=1000 pid=13401 comm="/snap/bitwarden/76/bitwarden --no-sandbox --enable" label="snap.bitwarden.bitwarden (enforce)") interface="org.freedesktop.Secret.Service" member="OpenSession" error name="(unset)" requested_reply="0" destination=":1.78" (uid=1000 pid=2367 comm="/usr/bin/gnome-keyring-daemon --start --foreground" label="unconfined")
** Message: 21:25:32.195: Remote error from secret service: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.465" (uid=1000 pid=13401 comm="/snap/bitwarden/76/bitwarden --no-sandbox --enable" label="snap.bitwarden.bitwarden (enforce)") interface="org.freedesktop.Secret.Service" member="OpenSession" error name="(unset)" requested_reply="0" destination=":1.78" (uid=1000 pid=2367 comm="/usr/bin/gnome-keyring-daemon --start --foreground" label="unconfined")

### Operating System

Linux

### Operating System Version

Lubuntu.20.04.5 LTS 

### Installation method

Other

### Build Version

Version 2022.9.1 Shell 19.0.8 Renderer 102.0.5005.148 Node 16.14.2 Architecture x64

**Comment by Hinton** [comment] 2022-10-04 13:12
Duplicate of https://github.com/bitwarden/clients/issues/2589

**Closed by Hinton** 2022-10-04 13:12 UTC
Labels: bug, desktop
