### ISSUE TITLE
Conflict with React Developer Tools

### ISSUE THREAD

**Issue by kriskratz** [bitwarden/clients#7573] opened 2024-01-16 18:39 UTC
### Steps To Reproduce

1. Using Firefox v121.0.1 on Apple M2. Install React Developer Tools browser extension.
2. Go to any web page
3. Open the browser console

### Expected Result

No error messages

### Actual Result

Infinite error messages about every 500 milliseconds: 
```
Handling window message [bootstrap-content-message-handler.js:167:21]
Bad source or badly formatted message, skipping. [bootstrap-content-message-handler.js:171:25]
```

### Screenshots or Videos

https://github.com/bitwarden/clients/assets/36646814/614c4912-810d-4664-9563-b14e4b50b86b

### Operating System

macOS

### Operating System Version

Ventura 13.5.2

### Web Browser

Firefox

### Browser Version

121.0.1

### Build Version

124.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-01-16 20:07
Duplicate of https://github.com/bitwarden/clients/issues/7575

**Comment by djsmith85** [comment] 2024-01-16 20:09
Hi @kriskratz, thank you for your report. 

Marking this as duplicate of https://github.com/bitwarden/clients/issues/7575 and closing as the other report has more information and has already been passed on to Engineering for further investigation.

Kind regards,
Daniel

**Closed** 2024-01-16 20:09 UTC
Labels: bug, browser
