### ISSUE TITLE
Black Screen GNOME 41.6 and 42.0 Wayland

### ISSUE THREAD

**Issue by limedawg99** [bitwarden/clients#2661] opened 2022-05-08 15:10 UTC
### Steps To Reproduce

1.  Launch the app image. Mine is in ~/apps/bitwarden.appimage
2. Launches to system tray.
3. Show appliation but returns a black screen.
4. Logging out and using X11 on same system presents no issues.

System info:
Fedora Workstation 35
GNOME 41.6 (wayland)
Appimage 1.33.0 (latest installed)

### Expected Result

Presents a nornaml login screen. app.log data when using X11 shows that logs should stop on launch once update check is completed. Shown below.

[2022-05-08 10:59:16.783] [info]  Checking for update
[2022-05-08 10:59:17.103] [info]  Update for version 1.33.0 is not available (latest version: 1.33.0, downgrade is disallowed).

### Actual Result

Window only shows as a black screen. app.log data for event below when trying to use Wayland.

[2022-05-08 10:57:56.009] [info]  Checking for update
[2022-05-08 10:57:56.358] [info]  Update for version 1.33.0 is not available (latest version: 1.33.0, downgrade is disallowed).
[2022-05-08 10:58:37.354] [error] TypeError: Object has been destroyed
    at WindowMain.<anonymous> (/tmp/.mount_BitwarCnwCPB/resources/app.asar/main.js:53332:36)
    at Generator.next (<anonymous>)
    at /tmp/.mount_BitwarCnwCPB/resources/app.asar/main.js:53146:71
    at new Promise (<anonymous>)
    at window_main_awaiter (/tmp/.mount_BitwarCnwCPB/resources/app.asar/main.js:53142:12)
    at WindowMain.updateWindowState (/tmp/.mount_BitwarCnwCPB/resources/app.asar/main.js:53327:16)
    at WindowMain.<anonymous> (/tmp/.mount_BitwarCnwCPB/resources/app.asar/main.js:53281:28)
    at Generator.next (<anonymous>)
    at /tmp/.mount_BitwarCnwCPB/resources/app.asar/main.js:53146:71
    at new Promise (<anonymous>)

### Operating System

Linux

### Operating System Version

Fedora 35 Workstation

### Installation method

Direct Download (from bitwarden.com)

### Build Version

1.33.0

**Comment by limedawg99** [comment] 2022-05-08 15:13
Edit: Adding screen shot

![image](https://user-images.githubusercontent.com/95552194/167302821-3e42fea2-e364-48d9-ad2e-06e6d9dc78d9.png)

**Comment by mertbingol0** [comment] 2022-05-10 14:39
The Wayland feature itself does not allow cross-window access. Follow the steps below:
1- sudo vim /etc/gdm3/custom.conf
2- #WaylandEnable=false >> WaylandEnable=true
3- Add line: DefaultSession=gnome-xorg.desktop 
4- Esc+wq+enter and run the reboot command

**Comment by CustomCodeIT** [comment] 2022-05-13 04:36
Having the same issue here too.

### System
OS: Fedora Linux 36 (Workstation Edition) x86_64
Kernel: 5.17.6-300.fc36.x86_64
DE: GNOME 42.0
Session: Wayland

### Bitwarden Package
Version: 1.33.0
Type: RPM

### Screenshots
From starting it via the terminal:
![image](https://user-images.githubusercontent.com/66106520/168211919-26b7bf32-127e-4ab8-a400-501a37791939.png)

From the GUI:
![image](https://user-images.githubusercontent.com/66106520/168211957-fc3d1638-3424-415f-8320-df8b76d39976.png)

**Comment by limedawg99** [comment] 2022-05-13 23:45
Update:

For GNOME 42.0 and Fedora 36 with wayland I am also still having the issue. Interestingly on my laptop while using the integrated intel graphics I am not having any issues but the issue persists on my desktop which only has an NVIDIA GPU. I am thinking this has something to do with NVIDIA not playing nice with wayland even though it is supposedly good enough to be the default.

**Comment by kovrom** [comment] 2022-05-14 04:32
Have the same issue with different appimage on GNOME 42.0 / Fedora 36 with wayland and NVIDIA GPU. Since the error in the terminal is related to `libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)` the only workaround I found is to set LIBVA_DRIVER_NAME. So in terminal do:
```
export LIBVA_DRIVER_NAME= _your_driver_name_
./_your_software.AppImage
```
List of driver names as per https://github.com/intel/libva/blob/master/va/drm/va_drm_utils.c#L40
```
static const struct driver_name_map g_driver_name_map[] = {
    { "i915",       4, "iHD"    }, // Intel Media driver
    { "i915",       4, "i965"   }, // Intel OTC GenX driver
    { "pvrsrvkm",   8, "pvr"    }, // Intel UMG PVR driver
    { "emgd",       4, "emgd"   }, // Intel ECG PVR driver
    { "hybrid",     6, "hybrid" }, // Intel OTC Hybrid driver
    { "nouveau",    7, "nouveau"  }, // Mesa Gallium driver
    { "radeon",     6, "r600"     }, // Mesa Gallium driver
    { "amdgpu",     6, "radeonsi" }, // Mesa Gallium driver
    { "nvidia-drm",10, "nvidia"   }, // NVIDIA driver
    { NULL,         0, NULL }
};
```

**Comment by limedawg99** [comment] 2022-05-15 01:20
Okay so I used the below command to get the name of my hardware

`lshw -c video`

It returned the below

`*-display                 
       description: VGA compatible controller
       product: GP104 [GeForce GTX 1080]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:09:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
       configuration: driver=nvidia latency=0
`
Therefore based on @kovrom s advice I ran the below

`export LIBVA_DRIVER_NAME= nvidia            
./Bitwarden-1.33.0-x86_64.AppImage
`
I got the following output and the app relaunched itself

`DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `bitwarden --trace-deprecation ...` to show where the warning was created)`

Window still is a null window like before but no more errors in app.log (shown below)

`[2022-05-14 21:10:20.237] [error] TypeError: Object has been destroyed
    at WindowMain.<anonymous> (/tmp/.mount_Bitwar1gVMwx/resources/app.asar/main.js:53332:36)
    at Generator.next (<anonymous>)
    at /tmp/.mount_Bitwar1gVMwx/resources/app.asar/main.js:53146:71
    at new Promise (<anonymous>)
    at window_main_awaiter (/tmp/.mount_Bitwar1gVMwx/resources/app.asar/main.js:53142:12)
    at WindowMain.updateWindowState (/tmp/.mount_Bitwar1gVMwx/resources/app.asar/main.js:53327:16)
    at WindowMain.<anonymous> (/tmp/.mount_Bitwar1gVMwx/resources/app.asar/main.js:53281:28)
    at Generator.next (<anonymous>)
    at /tmp/.mount_Bitwar1gVMwx/resources/app.asar/main.js:53146:71
    at new Promise (<anonymous>)
[2022-05-14 21:10:42.999] [info]  Checking for update
[2022-05-14 21:10:43.550] [info]  Update for version 1.33.0 is not available (latest version: 1.33.0, downgrade is disallowed).`

**Comment by kovrom** [comment] 2022-05-15 03:26
@limedawg99  Don't ask me why :), but try to run:
```
export LIBVA_DRIVER_NAME=nouveau
And then
./Bitwarden-1.33.0-x86_64.AppImage
```

**Comment by CustomCodeIT** [comment] 2022-05-15 03:31
@kovrom I don't know why either but I can confirm this works for me... 

* Fedora Workstation 36
* GNOME 42.0
* Nvidia Driver
* Wayland

**Comment by tangowithfoxtrot** [comment] 2022-06-17 18:43
Hey @limedawg99 ,

This is difficult for me to reproduce, since I don't actually have Nvidia hardware, but I can confirm that the AppImage launches from tray without issue using mesa drivers under Wayland.

Based on the very helpful suggestion from @kovrom, you can try creating/editing a `bitwarden.desktop` file to launch with the `LIBVA_DRIVER_NAME=nouveau` environment variable automatically. Something like this should work:

```
[Desktop Entry]
Type=Application
Version=2022.5.1
Name=Bitwarden
Exec=LIBVA_DRIVER_NAME=nouveau /path/to/your/AppImage
StartupNotify=false
Terminal=false
```

Since this appears to be more of an issue with graphics drivers/display server, I'm going to close this issue.

**Closed by tangowithfoxtrot** 2022-06-17 18:43 UTC
Labels: bug, desktop

**Comment by DoodlesEpic** [comment] 2022-07-02 14:09
> Had a similar [issue](https://github.com/mullvad/mullvadvpn-app/issues/3570) with Mullvad client. I believe that upgrading from Electron 16 to 18 solved it for Mullvad app.

It would be nice if Bitwarden could also update Electron to version 18 to fix this problem, any chance this issue can be reopened? Although it is caused by Nvidia drivers it's a bummer that we can't use the password manager under Wayland because deps are a bit out of date.

**Comment by DoodlesEpic** [comment] 2022-07-07 17:53
I've managed to trace down the exact problem upstream on Electron and it seems it's solved on Electron 17 so upgrading to version should be a possibility without any major problems, just a version bump and the problem will be fixed.
https://github.com/electron/electron/pull/33355

**Comment by djsmith85** [comment] 2022-07-07 19:14
@DoodlesEpic Thank you for your comments and research. I've passed your findings on to the team.

**Comment by djsmith85** [comment] 2022-07-11 17:15
@DoodlesEpic: The electron bump is on it's way 😉 -  https://github.com/bitwarden/clients/pull/3071
