### ISSUE TITLE
session argv doesn't work

### ISSUE THREAD

**Issue by efa2d19** [bitwarden/clients#9050] opened 2024-05-06 14:23 UTC
### Steps To Reproduce

1. Create a new session or use an existing one
2. Pass it to any command, e.g. `bw get uri aboba --session=<your_session>`

### Expected Result

Get uri or 404

### Actual Result

Being prompted to enter master password

### Additional Context

Was working correctly at 2024.3.1, but not anymore.\
Using env still works tho 🤷‍♂️

### Operating System

macOS

### Shell

Zsh

### Build Version

2024.4.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-05-14 09:15
@efa2d19 This is a duplicate of https://github.com/bitwarden/clients/issues/9067 and resolved with https://github.com/bitwarden/clients/pull/9084

Please update to [2024.4.1](https://github.com/bitwarden/clients/releases/tag/cli-v2024.4.1) which includes the fix.

Closing this now.

**Closed by djsmith85** 2024-05-14 09:15 UTC
Labels: bug, cli
