### ISSUE TITLE
Edge Extension Errors In Console

### ISSUE THREAD

**Issue by jacobtread** [bitwarden/clients#3556] opened 2022-09-18 04:03 UTC
### Steps To Reproduce

Install the extension on the Edge browser (The chromium base one) through the Microsoft edge addons 
Open console on any website

### Expected Result

No errors in console

### Actual Result

When you open the console you get the following error always:

`
autofill.js:10733 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'encrypt')
    at 45 (autofill.js:10733:33)
    at o (autofill.js:1:265)
    at autofill.js:1:316
    at 44../captureDdgGlobals.js (autofill.js:10579:49)
    at o (autofill.js:1:265)
    at autofill.js:1:316
    at 54.../../../packages/device-api/index.js (autofill.js:11616:25)
    at o (autofill.js:1:265)
    at autofill.js:1:316
    at 56../android.transport.js (autofill.js:11714:23)`

This error shows up regardless of what site I am on 

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/33708767/190885108-55565cd7-951e-4244-999e-91048149ccfe.png)

### Operating System

Windows

### Operating System Version

Windows 11 Version 21H2 (Build 22000.978)

### Web Browser

Microsoft Edge

### Browser Version

105.0.1343.42 (Official build) (64-bit) 

### Build Version

2022.9.1

**Comment by adam-townsend-tfs** [comment] 2022-11-02 18:37
i have the same issue on firefox 106.0.3. it happens when i refresh a site/page. so i have to close the tab and reopen it.

**Comment by Krychaz** [comment] 2023-08-24 11:31
Hi there,

I attempted to reproduce your issue and was unable to do so. As the issue is on the older side, it has most likely been fixed by now. If you still experience this issue please let us know. For now I will close it.

**Closed** 2024-08-13 15:00 UTC
Labels: bug, browser
