### ISSUE TITLE
Suddenly unable to View/Copy passwords protected by "Reprompt master password"

### ISSUE THREAD

**Issue by Universal-Igloo** [bitwarden/clients#6244] opened 2023-09-09 04:16 UTC
### Steps To Reproduce

(This bug is currently reproduced on the Chrome extension, MacOS desktop client & Android app. Everything used to work perfectly till now for as long as I can remember.)

1. Go to the card for whichever password you have enabled "Reprompt Master Password" for
2. Click on either view or copy Password field
3. Enter the Master password
4. click ok

### Expected Result

1. It should accept the Master Password or Tell you that it is incorrect
2. The password should be copied or viewable

### Actual Result

Bitwarden just gets stuck with after pressing the OK button and doesn't do anything. You can click cancel, but you can't view or copy your secured password.

### Screenshots or Videos

<img width="507" alt="Screenshot 2023-09-09 at 9 43 59 AM" src="https://github.com/bitwarden/clients/assets/95539123/e95d6dc3-f96b-469c-8f22-de4cfc0d3e7c">

### Operating System

macOS

### Operating System Version

Ventura 13.5.1 (22G90)

### Installation method

Homebrew

### Build Version

2023.8.3 (11485)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2023-09-09 15:51
Duplicate of https://github.com/bitwarden/clients/issues/6153

**Comment by djsmith85** [comment] 2023-09-09 15:52
@Universal-Igloo Thank you for your report this is a known issue and a duplicate of https://github.com/bitwarden/clients/issues/6153

**Closed by djsmith85** 2023-09-09 15:52 UTC
Labels: bug, desktop
