### ISSUE TITLE
Mac client keeps asking for TouchID

### ISSUE THREAD

**Issue by peppelorum** [bitwarden/clients#5594] opened 2023-06-11 17:20 UTC
### Steps To Reproduce

This is on Macos Ventura (13.0.1) and Bitwarden 2023.5.0 (9051)

1. Enable TouchId
2. Restart Bitwarden
3. Up pops a request to unlock with TouchId
4. Hit cancel
5. Same popup appears
6. Hit cancel
7. And so on

### Expected Result

The touchid popup shouldn't appear if you cancel it.

### Actual Result

The popup keeps reappearing.

### Screenshots or Videos

<img width="970" alt="Screenshot 2023-06-11 at 19 13 14" src="https://github.com/bitwarden/clients/assets/133687/ce272f69-262a-4dda-872c-e1669c7bb71f">

### Operating System

macOS

### Operating System Version

13.0.1

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.5.0 (9051)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment] 2023-06-11 17:33
Hi @peppelorum,

Thank you for your report; It seems to be a duplicate of this (https://github.com/bitwarden/clients/issues/5142).

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in that thread - our engineering team will be happy to review these.

This issue will now be closed.


Thank you again,

**Closed by SergeantConfused** 2023-06-11 17:33 UTC
Labels: bug, desktop
