### ISSUE TITLE
"a" is handled as an escape character in search

### ISSUE THREAD

**Issue by aDivineDragoness** [bitwarden/clients#2569] opened 2022-03-23 14:56 UTC
### Steps To Reproduce

1. Create Passwort with the name "Password-1" 
2. Search "Password-1"
3. Search "Passworda-1"

### Expected Result

- When searching "Password-1" only matching results are shown and the "-" behaves like a space
- When searching "Passworda-1" passwords that would only match "Password-1" are not shown, but ones that match "Passworda-1" are shown

### Actual Result

- When searching "Password-1", the search behaves like you would search "Password 1"
- When searching "Passworda-1" the search behaves like searching "Password-1" with the "-" beeing included in the search

### Additional Context

I'm not sure if this is a problem with Bitwarden specifically or with the Lunr Library
I'ts like that in the Desktop-App, the Web-App and the Browser Extension

### Operating System

Windows

### Installation method

Microsoft Store

### Build Version

1.32.1

**Comment by CarleyDiaz-Bitwarden** [comment] 2022-05-16 14:48
Thank you aDivineDragoness for bringing this to our attention at Bitwarden! I have looked into the search functionality on the Desktop app and have found that the "-" character is used as a tokenizer. Because "-" is treated as a tokenizer, it will perform essentially the same way as using a space between words. "Passworda-1" will be parsed by Lunr as "Passworda" or "1". The search results you encountered were returning "passworda-1" is because it's matching on the "1". This issue will be marked as closed because it's behaving as intended.

**Closed** 2022-07-20 15:58 UTC
Labels: bug, desktop

**Comment by NothingCtrl** [comment] 2022-11-25 13:52
Any alternative solution to search name have special character in it?
