### ISSUE TITLE
DuckDuckGo integration broken

### ISSUE THREAD

**Issue by MrSpongeHead** [bitwarden/clients#11818] opened 2024-11-01 09:07 UTC
### Steps To Reproduce

1. Go to 'DuckDuckGo browser > Settings > Passwords & Autofill'
2. Click on 'Bitwarden' within the Password Manager section

### Expected Result

The Connect to Bitwarden screen opens giving instruction on allowing integration with Bitwarden.

### Actual Result

The Connect to Bitwarden screen appears, but Bitwarden fails to authenticate properly and the Bitwarde icon re-appears constantly in the dock.

### Screenshots or Videos

https://github.com/user-attachments/assets/1f76bfe2-af52-498e-b96c-a769968ec712

### Operating System

macOS

### Operating System Version

Sequoia 15.1

### Installation method

Mac App Store

### Build Version

Version 2024.10.2 Shell 32.1.1 Renderer 128.0.6613.137 Node 20.17.0 Architecture arm64

### Issue Tracking Info

- [ ] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment] 2024-11-01 11:36
Hi there!

Thank you for your report, it seems like it is a duplicate of the issue we have triaged internally. This has been passed to our engineering team. 

This issue will now be closed.

Thanks!

**Closed by Krychaz** 2024-11-01 11:36 UTC
Labels: bug, desktop
