### ISSUE TITLE
Blank start page when launching the app, passwords cannot be accessed at all

### ISSUE THREAD

**Issue by clemlesne** [bitwarden/clients#7159] opened 2023-12-10 21:00 UTC
### Steps To Reproduce

1. Click on the Bitwarden icon
2. See the blank page

### Expected Result

See the passwords, the login page, ...

### Actual Result

A blank page with no buttons, no fields, no actions, just a blank page.

### Screenshots or Videos

![Screenshot 2023-12-10 at 21 57 10_scrubbed](https://github.com/bitwarden/clients/assets/10001945/8dc60ca4-37c4-4f74-8cff-ad8c8b4d6a08)

### Operating System

macOS

### Operating System Version

14.1.2 (23B92)

### Installation method

Mac App Store

### Build Version

2023.10.1 (13648)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment] 2023-12-11 02:32
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/clients/issues/6691

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by sammbw** 2023-12-11 02:32 UTC
Labels: bug, desktop
