### ISSUE TITLE
Firefox add-on shows autofill prompt despite being disabled

### ISSUE THREAD

**Issue by Lalufu** [bitwarden/clients#11231] opened 2024-09-25 07:56 UTC
### Steps To Reproduce

On any web page with a login field, selecting the login field shows the autofill prompt, as shown below. This is despite everything under Settings->Autofill being disabled, except for "Show context menu options"
This started today, with the update to 2024.9.1.

### Expected Result

No autofill prompt shown

### Actual Result

Autofill prompt is shown on every applicable field

### Screenshots or Videos

![2024-09-25_09-50](https://github.com/user-attachments/assets/976d75d1-9b26-466b-b2d0-46c2ed8e0a93)

### Operating System

Linux

### Operating System Version

Ubuntu 22.04.1

### Web Browser

Firefox

### Browser Version

130.0.1 (binaries from Mozilla)

### Build Version

Version: 2024.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by dkd-heymann** [comment] 2024-09-25 10:13
Same behaviour on macOS 14.7

- Operating System: macOS
- Operating System Version: 14.7
- Web Browser: Firefox
- Browser Version: 130.0.1
- Build Version: 2024.9.1

**Comment by NovaSilentium** [comment] 2024-09-25 13:24
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by cagonzalezcs** [comment] 2024-09-25 17:28
This is a duplicate of https://github.com/bitwarden/clients/issues/11173

Closing this to keep the conversation in a single thread

**Closed by cagonzalezcs** 2024-09-25 17:28 UTC
Labels: bug, browser
