### ISSUE TITLE
Mac desktop client hanging on startup

### ISSUE THREAD

**Issue by MashMathias** [bitwarden/clients#6915] opened 2023-11-20 10:15 UTC
### Steps To Reproduce

1. Start app
2. App starts and a spinning wheel is showing but never completes and never times out

### Expected Result

App should start and ask for login

### Actual Result

The app starts but is getting stuck on the spinning wheel. App can no longer be used.

### Operating System

macOS

### Operating System Version

Sonoma 14.1.1

### Installation method

Mac App Store

### Build Version

2023.10.1 (13648)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by MashMathias** [comment] 2023-11-20 10:17
Forgot to mention that I'm using an Apple MacBook Air with a M1 CPU.

**Comment by atjbramley** [comment] 2023-11-20 10:20
@MashMathias, 

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/clients/issues/6691 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by atjbramley** 2023-11-20 10:20 UTC
Labels: bug, desktop
