### ISSUE TITLE
Safari Extension not working after update v2024 3.0

### ISSUE THREAD

**Issue by GaffelWiess** [bitwarden/clients#8381] opened 2024-03-19 02:35 UTC
### Steps To Reproduce

![Screen Shot 2024-03-19 at 12 07 59](https://github.com/bitwarden/clients/assets/163954152/297fe389-4da3-4a82-af06-18d1c4da8f2d)
![Screen Shot 2024-03-19 at 12 08 11](https://github.com/bitwarden/clients/assets/163954152/cc49e1ca-0427-4d5c-bd22-ef356c101959)
![Screen Shot 2024-03-19 at 12 08 35](https://github.com/bitwarden/clients/assets/163954152/8d1e8727-e008-452e-b950-3c40496ccb97)
![Screen Shot 2024-03-19 at 12 28 07](https://github.com/bitwarden/clients/assets/163954152/747aab34-c003-4a5b-9bd2-b84bc6738d2a)

### Expected Result

Expect Bitwarden extension to load 

### Actual Result

Bitwarden extension did not load

### Operating System

macOS

### Operating System Version

Catalina

### Web Browser

Safari

### Browser Version

15.6.1

### Build Version

2024 3.0

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Hinton** [comment] 2024-03-21 11:58
This seems to be a duplicate of https://github.com/bitwarden/clients/issues/8348. Closing.

**Closed by Hinton** 2024-03-21 11:58 UTC
Labels: bug, browser

**Comment by GaffelWiess** [comment] 2024-03-22 12:43
Hi Hinton

Did not realise someone had already posted.
My post is separate from #8348  
Is there a fix in the pipeline?
Thanks
