### ISSUE TITLE
Bitwarden opens behind all opened windows

### ISSUE THREAD

**Issue by WinterLemur** [bitwarden/clients#4514] opened 2023-01-19 20:22 UTC
### Steps To Reproduce

1. Make sure that (Minimize to menu bar) or (Close to menu bar) are toggled in the Settings menu. [both settings produce the same issue]
2. Quit the Bitwarden macOS desktop client fully and reopen the application
3. Enter the vault with your credentials or open it with biometrics.
4. `Bitwarden will stay on top of other windows`
5. Close the application (X) or minimize it (-)
6. Open the application, enter the vault with password/biometrics
7. `Bitwarden will disappear, it will be on the bottom of all open windows`

Quit Bitwarden and launch it again.

### Expected Result

After entering the credentials/biometrics, Bitwarden should stay in focus and on top of all windows.

### Actual Result

After entering the credentials/biometrics, Bitwarden disappears under all open windows.

### Operating System

macOS

### Operating System Version

Ventura 13.1

### Installation method

Mac App Store

### Build Version

Version 2023.1.1Shell 21.3.1 Renderer 106.0.5249.181 Node 16.16.0 Architecture arm64

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2023-01-20 10:48
@WinterLemur Closing this as duplicate of your other opened issue #4515

**Closed** 2023-02-26 19:04 UTC
Labels: bug, desktop
