### ISSUE TITLE
Do not switch to default server after logged out

### ISSUE THREAD

**Issue by Upstream8022** [bitwarden/clients#5725] opened 2023-07-01 13:03 UTC
### Steps To Reproduce

1. Click on 'log out' @ self host server
2. Check host by 'US Region'
3. Input User Name and password
4. Nothing appears in the box.

### Expected Result

Something wrong with the server selection part. It remembers the last way to log in.

### Actual Result

Something wrong with the server selection part. It remembers the last way to log in.

### Operating System

Windows

### Operating System Version

Windows 10

### Web Browser

Chrome, Microsoft Edge

### Build Version

2023.5.1

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment] 2023-07-03 07:06
Hi @Upstream8022,

Just to make sure that you and I are on the same page, do you mean that the self-hosted server URL from the Environment Setup is cleared when you log out of the extension? I'd highly appreciate a screenshot to confirm.


Thank you in advance,

**Comment by Upstream8022** [comment] 2023-07-03 12:50
> 

Due to the disconnection of my self-built server, I am temporarily forced to migrate to the official server. However, no matter how hard I try, I cannot retrieve the stored account passwords. I attempted to log in on the `US` server, and my password and `2FA` were correct, but nothing appeared inside.
When selecting the self-built server, the space was left blank, and then I tried `vault.bitwarden.com`, which went smoothly.

<img width="716" alt="20230703204416" src="https://github.com/bitwarden/clients/assets/105393306/b0288ff1-3b64-45b0-81ce-18312afd5204">

**Comment by Upstream8022** [comment] 2023-07-03 13:39
The network monitoring software indicates that in this situation, the server used for communication during login is the official server, specifically `api.bitwarden.com`. However, after logging in, Bitwarden communicates with the `self-hosted` servers.

**Comment by trmartin4** [comment] 2024-02-27 20:17
We believe the root cause of this issue has been resolved.  @Upstream8022, can you verify that you no longer experience this problem with the latest desktop version, with the replication steps listed?

**Comment by trmartin4** [comment] 2024-03-20 20:53
We believe this issue has been resolved, so I will be closing this ticket.  Please re-open if you see the issue recur.  Thank you!

**Closed by trmartin4** 2024-03-20 20:53 UTC
Labels: bug, browser
