### ISSUE TITLE
V 2023.9.0 causes major instability in Microsoft Edge Browser on Win 11

### ISSUE THREAD

**Issue by nyjklein** [bitwarden/clients#6352] opened 2023-09-20 18:03 UTC
### Steps To Reproduce

The insatbility happens on multiple web sites. Edge becomes unresponsive and task manager shows CPU around 70%. One example, speedtest.net
1. Go to '.speedtest.net'. CPU immediately shoots up..
2. Click on '.GO.' Slow response and horrible results.
3. Disable the extension and all is back to normal!

### Expected Result

Extension should not impact performance so drastically. It was fine before the extension got upgraded today.

### Actual Result

Not sure what's happening, but it seems to be related to loading "ads" in the background.

### Operating System

Windows

### Operating System Version

Win 11 Build 22631.2338

### Web Browser

Microsoft Edge

### Browser Version

117.0.2045.36 (Official build) (64-bit)

### Build Version

2023.9.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2023-09-20 18:08
Duplicate of #6347

**Comment by djsmith85** [comment] 2023-09-20 18:09
Hi @nyjklein,

This is a duplicate of #6347

Closing this now.

**Closed** 2023-09-20 18:09 UTC
Labels: bug, browser
