### ISSUE TITLE
[Mac OS, browser add-on v2024.9.1] Unlock with Biometrics stopped working

### ISSUE THREAD

**Issue by ewjoachim** [bitwarden/clients#11245] opened 2024-09-25 17:53 UTC
### Steps To Reproduce

1. Have the native app run in the background
2. Configure the extension to use biometrics
3. Open the extension

### Expected Result

A popup should open inviting the user to provide biometrics
<img width="249" alt="Screenshot 2024-09-25 at 19 50 33" src="https://github.com/user-attachments/assets/91727119-a360-45c2-8983-269f3a953c9c">

### Actual Result

No popup. Clicking on the "Unlock with biometrics" button does nothing

### Screenshots or Videos

<img width="369" alt="Screenshot 2024-09-25 at 19 48 55" src="https://github.com/user-attachments/assets/1158ff21-b14c-463c-b673-2dd0f3065118">

### Additional Context

<img width="667" alt="Screenshot 2024-09-25 at 19 51 44" src="https://github.com/user-attachments/assets/961aca69-5678-41e2-96ca-016a17f25a61">
The app was updated today, and the issue started today, so it's most probably linked.

### Operating System

macOS

### Operating System Version

Sonoma

### Web Browser

Firefox

### Browser Version

130.0.1

### Build Version

2024.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jaydee73** [comment] 2024-09-25 18:27
I can confirm the same behavior on my macos system with Firefox. Has worked before, but now it's broken.

**Comment by gtarnaras** [comment] 2024-09-25 18:56
Same behavior here with Firefox: 130.0.1 and Bitwarden Version 2024.9.1 
Clicking the "Unlock With Biometrics" results to no actions. Nothing pops up.

**Comment by holdit** [comment] 2024-09-25 21:45
Just tested on Brave and it was working with 2024.9.0, but after updating to 2024.9.1, it stopped working.

On Firefox it also stopped working after 2024.9.1.

My client, installed via the app store, is still on 2024.8.2.

**Comment by mmolitor87** [comment] 2024-09-25 21:50
I can confirm the same behavior and same version numbers as above.

**Comment by kapitainsky** [comment] 2024-09-26 04:26
Also the same NOT working on:

macOS Sequoia: 15.0
Firefox: 130.0.1
BW client: 2024.8.2 via App Store
BW Firefox plugin: 2024.9.1

**Comment by HomeQi** [comment] 2024-09-26 13:05
also have this problem:
macos sonoma 14.5 (23F79)
chrome 129.0.6668.71
Bitwarden client:2024.8.2 appstore
chrome plugin:2024.9.1

**Comment by ewjoachim** [comment] 2024-09-26 14:49
Looks like the common thread is mac + add-on 2024.9.1, let that be on Firefox or Chrome with Sonoma or Sequoia

Let's not add more examples here unless we have a different

**Comment by jtodddd** [comment] 2024-09-26 15:16
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/11168. 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by jtodddd** 2024-09-26 15:16 UTC
Labels: bug, browser

**Comment by ewjoachim** [comment] 2024-09-29 08:00
Can't believe I missed it while searching. Sorry. Also, confirming that it seems solved now
