### ISSUE TITLE
Safari extension - vault won't sync if there are more than 2,849 entries

### ISSUE THREAD

**Issue by sporkman** [bitwarden/clients#11759] opened 2024-10-28 19:49 UTC
### Steps To Reproduce

1. Create 2,849 entries of any type (login, note, etc.) in your vault with the desktop, phone, or web client.
2. Open Safari extension, go to Settings -> Vault -> Sync -> Sync Now, observe it works
3. Add one additional entry to bring the total to 2,850
4. Open Safari extension, go to Settings -> Vault -> Sync -> Sync Now, observe that it reports "Sync Failed"
5. Remove a login using the desktop, phone, or web client, bringing the total item count to under 2,850
6. Open Safari extension, go to Settings -> Vault -> Sync -> Sync Now, observe it works

### Expected Result

The vault syncs regardless of how many entries there are.

### Actual Result

I wish I had more information, but I've been unable to pull any debug info out of the Safari extension. It simply tells me this and nothing more:

<img width="374" alt="Screenshot 2024-10-28 at 3 41 53 PM" src="https://github.com/user-attachments/assets/54d576b3-550c-4bab-8089-bfe88186848b">

### Additional Context

I observed this happening with both the official Bitwarden service and a self-hosted Vaultwarden instance.

I can confirm the the other apps/browsers I use do not seem to have this limitation/bug. This includes: current iOS app, Chrome extension, Firefox extension, and the macOS desktop app.

I found the upper limit by repeatedly nuking my (Bitwarden-hosted) vault and decreasing the size of the backup of my vault by 500 items or so until I got a successful sync. I then incremented it up until I hit a limit, then decreased until I found the magic 2,850 number. I also verified that it's not related to the size of the entries, meaning I can leave the vault at 2,849 and add multi-paragraph "notes" to some entries and syncing continues to work.

The bug began for me when Safari updated to 18.0.1. Not sure if previously I was on 18.0 or 17.x.

I have all kinds of additional notes and such, spent hours and hours on this, let me know if there's any other info I can provide.

### Operating System

macOS

### Operating System Version

Sonoma 14.7

### Web Browser

Safari

### Browser Version

18.0.1

### Build Version

Version: 2024.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sporkman** [comment] 2024-10-30 02:57
I think if you're reproducing you probably have what you need, but if there's anything specific let me know.

From my end the only thing I got really lost on is how to get any logging data out of the extension. It seems like that might be an entire process that gets complicated fast. But if there's any kind of quick HOWTO on that I'd love to check it out.

**Comment by Hinton** [comment] 2024-10-31 16:16
Hi @sporkman,

Could you try updating to Safari 18.1? I suspect this might have been a defect in Safari that got resolved as I'm unable to reproduce it with a testing account that has significantly more vault items.

**Comment by sporkman** [comment] 2024-10-31 17:50
I'm on 14.7.1 still, but I did find a developer preview of 18.1 for macOS 14, so I grabbed that and I'm all synced up!

Can you folks put something in release notes or make the support department aware of the bug so nobody else has to sink a bunch of time into sorting this out on their own like I did? :)

**Comment by trmartin4** [comment] 2024-11-02 15:41
Thank you @sporkman for confirming!  We'll make sure that we pass this along to anyone else experiencing the issue, and keep an eye out for others who open Github issues as well.

I'll be closing this ticket now, but please feel free to report any other issues you encounter.  Thank you again for your help.

**Closed by trmartin4** 2024-11-02 15:41 UTC
Labels: bug, browser
