### ISSUE TITLE
When i click on the field, it show no item, but there is if I search on the expension menu, on Chrome Extension

### ISSUE THREAD

**Issue by Flwk** [bitwarden/clients#9387] opened 2024-05-27 21:55 UTC
### Steps To Reproduce

1. Go to any website
2. Click on the id/password fill
3. The extension show no item, but there is one if i search on the extension menu.

### Expected Result

To show the id/password

### Actual Result

It show not password saved.

### Screenshots or Videos

![Capture d'écran 2024-05-27 234650](https://github.com/bitwarden/clients/assets/3245665/83ec62b5-646e-4ae0-b1af-bdb1c0097254)

### Operating System

Windows

### Operating System Version

Windows 11

### Web Browser

Chrome

### Browser Version

125.0.6422.113

### Build Version

2024.5.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Flwk** [comment] 2024-05-27 22:18
Sorry, I just found another issue, that is very similar to mine : https://github.com/bitwarden/clients/issues/9369

**Comment by sammbw** [comment] 2024-05-28 01:23
Hi there!

Thank you for your report - it does indeed seem like it is a duplicate of this issue you have linked.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by sammbw** 2024-05-28 01:23 UTC
Labels: bug, browser
