### ISSUE TITLE
2023.9.2 AppImage fails to open tresor on Debian 12.2

### ISSUE THREAD

**Issue by borque** [bitwarden/clients#6603] opened 2023-10-17 11:16 UTC
### Steps To Reproduce

Use Bitwarden 2023.9.1 (and previous) as an AppImage on Debian 12.2 to access your tresor and everything works fine.

After the update 2023.9.2 presents the PIN-Login-Screen, but after entering the PIN or clicking into a menu only shows a blank grey main window.

After going back to 2023.9.1 everything works as expected. Updating to 2023.9.2 again results in the above problem again.

This is reproducible on two different machines for me.

### Expected Result

After the update to version 2023.9.2 the tresor should open after entering the PIN or at least it should show the whole Login (with mail address, password and 2FA).

### Actual Result

With 2023.9.2 Bitwardens the main windows switches to blank grey after entering the PIN or clicking into a menu.

### Operating System

Linux

### Operating System Version

Debian 12.2, latest security-patch-level

### Installation method

Other

### Build Version

2023.9.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment] 2023-10-17 13:01
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by djsmith85** [comment] 2023-10-17 13:03
Duplicate of https://github.com/bitwarden/clients/issues/6560

**Comment by djsmith85** [comment] 2023-10-17 13:03
Hi @borque,

Thank you for your report. This report seems like it is a duplicate of this (https://github.com/bitwarden/clients/issues/6560).

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This report will now be closed.

Thank you again

**Closed by djsmith85** 2023-10-17 13:03 UTC
Labels: bug, desktop
