### ISSUE TITLE
Entry titles are unnecessarily truncated (Bitwarden browser extension)

### ISSUE THREAD

**Issue by webdev69420** [bitwarden/clients#3790] opened 2022-10-14 10:51 UTC
### Steps To Reproduce

1. Open and unlock the Bitwarden browser extension

2. Look at an entry with a long name

### Expected Result

The entry titles shouldn't be truncated (by adding '...' at the end) before almost touching the first icon on the right.

### Actual Result

Some entries that have a long **title that is unnecessarily truncated**, even though there's enough space to display the title in full (in most cases).

When searching for an entry in the vault, there's not one 2 scrollbars displaying on the right, which seems wrong (and may be related to the truncated entry title problem ?).

### Screenshots or Videos

**[Screenshot - Unnecessarily truncated title (Hosted on CleanShot Cloud)](https://cln.sh/nloLwP)**

![Image - Unnecessarily truncated title](https://media.cleanshot.cloud/media/10543/NEE0RIkwJBrkiyLKccV912IRpU1Mrt8IrgdgdbEe.jpeg?Expires=1665766717&Signature=ciIPp2Z8Km24XxaoG0U5vcMgKREdMBdJEqhvB3mgjnxKE8Ccv5j17LTLceLfSjWhicI2Knk0b2v7FkOiOkYLn4kQBtkwuweTxkIoqof651-oQf5rursbSwZOU7eBmE4U8igcNVvH0ssaboFD02P6OZ0Q2GjHG56ac56mMKb9lZ3APbhZ4ecEkxiN4TnfmbLu7zTwBZHAWPXMinBZjGzTKeqKicW~dhgx~XwON0Bi46pFyE1urbVICfdsbPf6FSG2eWFqI7S3CKfETLX93Vu7u7PS06vM6F68iNMPQd~06~VJDuOikehAv0HrRDgm1ugAohB5TPz9PvhmYOkjPCcCQQ__&Key-Pair-Id=K269JMAT9ZF4GZ)

### Operating System

macOS

### Operating System Version

12.6

### Web Browser

Chrome

### Browser Version

106.0.5249.119 (arm64)

### Build Version

2022.10.0

**Comment by Hinton** [comment] 2022-10-14 11:37
Duplicate of https://github.com/bitwarden/clients/issues/3788

**Closed by Hinton** 2022-10-14 11:37 UTC
Labels: bug, browser
