### ISSUE TITLE
Extension pop-ups appear off-screen with multiple monitors and differing display scaling.

### ISSUE THREAD

**Issue by chrrs** [bitwarden/clients#11087] opened 2024-09-16 18:47 UTC
### Steps To Reproduce

I'm unsure of the exact conditions that cause it, but here's my setup:

Screens:
First: 1920x1080 using 125% display scaling as set in Windows.
Second: 2560x1080 using 100% display scaling, to the right of the first display.

1. Open Firefox on the second screen.
2. Trigger any pop-up window of the Bitwarden extension (for example: unlocking vault, passkey selection).

### Expected Result

The pop-up appears on top of the window, visible to the user.

### Actual Result

The pop-up will appear out of the screen bounds, off to the right of the second screen. You can't interact with it, as it's not visible on screen.

### Additional Context

I'm not sure if this is a bug with the extension or with Firefox itself, but I've never noticed it happening with any other extensions, so I'm leaning towards it being a bug with the Bitwarden extension.

Note that this doesn't seem to happen if the first screen is set to 100% display scaling.
I've seen this behaviour on multiple different PC's with the same screen setup.

### Operating System

Windows

### Operating System Version

Windows 11, both 22H2 and 23H2

### Web Browser

Firefox

### Browser Version

130.0

### Build Version

2024.9.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment] 2024-09-21 14:59
Hello @chrrs,

Thank you for your report. This report seems to be a duplicate of [this GitHub report](https://github.com/bitwarden/clients/issues/10049); If there's anything you'd like to add, such as screenshots or video recordings of the screen, please feel free to add them to that existing GitHub report so that they'd be reviewed by the Bitwarden Engineering department.

This report will now be closed as a duplicate.

Thank you again,

**Closed by SergeantConfused** 2024-09-21 14:59 UTC
Labels: bug, browser
