### ISSUE TITLE
Should Bitwarden remember this password for you?" - clicking "never" does nothing.

### ISSUE THREAD

**Issue by VitasLoWang** [bitwarden/clients#6937] opened 2023-11-21 19:41 UTC
### Steps To Reproduce

1. Open some website preferrably with 2FA auth and login there
2. Bitwarden asks if you want to save this, but you don't want to save 2FA code because it's always different so doesn't make sense to save it
3. You click never, but nothing happens and Bitwarden bar stays on top of the webpage
4. You have to click cross top get rid of it

Browser tested: Mozilla FireFox

### Expected Result

clicking Never should make the Bitwarden bar disappear and not ask next time

### Actual Result

the bar stays and next time I login it asks me again

### Operating System

Windows

### Operating System Version

10

### Web Browser

Firefox

### Browser Version

199.01

### Build Version

2023.10.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment] 2023-11-28 14:11
Hi there!

Thank you for your report! It seems like it is a duplicate of an internal report on this issue.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by cbbit** 2023-11-28 14:11 UTC
Labels: bug, browser

**Comment by VitasLoWang** [comment] 2023-12-17 15:43
Very often if I click it soon enough the "never" button reacts, but does not remember it and next time it asks me again. Sometimes as I said the button does not react and bar stays there, but recently seems like it "works" by at least making it go away.

**Comment by guido-visser** [comment] 2024-01-05 09:26
Good to know for the devs, I have this issue in a dev environment (when the URL is `http://localhost:3000`). While `localhost` is added to the excluded domains, the client keeps asking to save the password. Maybe it doesn't honor the exclusion because it's on a specific port? Is there a way to add an exclusion for all ports on a url?
