### ISSUE TITLE
First use on firefox has issues with autofill/site detection

### ISSUE THREAD

**Issue by IetIesAai** [bitwarden/clients#11479] opened 2024-10-10 08:05 UTC
### Steps To Reproduce

Not 100% sure it does this every time, but frequently enough:
-fully close browser
-unlock Bitwarden plugin via icon by filling i, master password

### Expected Result

Bitwarden is unlocked, and is able to autofill logons, correct icons are shown

### Actual Result

-bitwarden will show available logons when opened via popup for the current tab, but not display the "number" icon to indicate this
-available sites will not be able to auto-filled in by any means (clocking the entry, shortcut, rightclick menu), copy paste works
-go to manage extension
-disable and re-enable the extension
-notice "lock" icon is now shown on the button
-enter master password
-number of available logins is shown on the icon and auto fill works

### Screenshots or Videos

before reloading extension: lock icon, number of logins are missing, autofill not available
![image](https://github.com/user-attachments/assets/cdc4b857-f433-476c-b6cc-8cfc4751a88a)
![image](https://github.com/user-attachments/assets/c34fb8b2-d3df-4ae2-ad06-8ee0cb16e9d1)

after reloading extension: lock icon shown, number of available logins shown, autofill works
![image](https://github.com/user-attachments/assets/aee9c1f1-010c-4649-a0e9-9fcea4c2e407)
![image](https://github.com/user-attachments/assets/76022129-3751-49b8-848f-1908843ee4f2)

### Operating System

Windows

### Operating System Version

W11

### Web Browser

Firefox

### Browser Version

131.0.2 (but previous versions also had the issue, not sure when it began)

### Build Version

Version: 2024.9.1 (not sure if it started with this version)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by mostlyjason** [comment] 2024-10-10 11:38
I am experiencing this issue on Firefox on Linux as well

**Comment by krallus** [comment] 2024-10-10 20:41
I am experiencing this as well.
Linux Mint 21.1 Cinnamon
Firefox 131.0.2 (64-bit)
Bitwarden Extension: 2024.9.1

**Comment by Krychaz** [comment] 2024-10-11 06:34
Can you please see if this helps to solve this issue:

https://github.com/bitwarden/clients/issues/10815#issuecomment-2358728761

**Comment by IetIesAai** [comment] 2024-10-11 08:52
> Can you please see if this helps to solve this issue:
> 
> [#10815 (comment)](https://github.com/bitwarden/clients/issues/10815#issuecomment-2358728761)

This indeed seems to be the same issue as described in #10814 (I did search before opening this issue, but the nature of the bug and the large number of autofill related tickets make it hard to find the correct one :-) ), and indeed a reboot triggers it (Though I only see this behaviour on my windows "work" lapop, not on the linux fedora 40 one I am using at home. 

I understand it should be solved in the next plugin version? Any idea when that is due?

**Comment by Krychaz** [comment] 2024-10-11 11:54
Should be end of next week

**Comment by Shakahs** [comment] 2024-10-14 18:57
I am also experiencing the "Unable to autofill..." bug. 
In my case it manifests every time Firefox update, and I've only been able to resolve it by uninstalling/reinstalling the Bitwarden extension after every Firefox update.

**Comment by thezoggy** [comment] 2024-10-15 17:38
seeing this as well. seems to happen anytime firefox is updated to new version :/

**Comment by krallus** [comment] 2024-10-15 17:48
> Can you please see if this helps to solve this issue:
> 
> [#10815 (comment)](https://github.com/bitwarden/clients/issues/10815#issuecomment-2358728761)

That comment describes precisely the situation for me:
> Closing and then re-opening my browser after reboot does "solve" the issue.
....
> After I reboot my device I need to do this again.

**Comment by cagonzalezcs** [comment] 2024-10-16 13:24
This is a duplicate of https://github.com/bitwarden/clients/issues/10814

Upgrade to `v2024.10.0` of the extension should resolve the issue, please try that and reach out to support if the problem persists.

**Closed by cagonzalezcs** 2024-10-16 13:24 UTC
Labels: bug, browser
