### ISSUE TITLE
Clone option doesn't exist for organization items

### ISSUE THREAD

**Issue by trparky** [bitwarden/clients#11491] opened 2024-10-10 17:35 UTC
### Steps To Reproduce

1. Click on Bitwarden extension icon to open the drop-down menu.
2. Click on Vault.
3. Find an item that's not in your organization, click on it. Note how there's an option to clone the item.
4. Go back to your Vault.
5. Find an item in your organization vault, click on it. Note how there's **no** option to clone the item.

### Expected Result

See the Steps to Reproduce section.

### Actual Result

See the Steps to Reproduce section.

### Operating System

Windows

### Operating System Version

Windows 11 23H2, 22631.4317

### Web Browser

Microsoft Edge

### Build Version

129.0.2792.79

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cbbit** [comment] 2024-10-11 14:02
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could be due to a permissions issue.

You can clone any item that you have ownership of if you want to create a duplicate of the item. Cloning items owned by an organization can be only done from the web app in the Admin Console or from Vaults view by Owners, Admins, and Users with _[Can manage](https://bitwarden.com/help/collection-management/#collection-management-settings)_ access to the collection in which the item is kept. 

More information here: https://bitwarden.com/help/managing-items/#clone

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Closed** 2024-10-11 14:02 UTC
Labels: bug, browser

**Comment by trparky** [comment] 2024-10-12 00:10
But why can't items be cloned in anything but the web app? That sounds kind of silly.
