### ISSUE TITLE
SecureInput remains enabled even after unlocking the vault.

### ISSUE THREAD

**Issue by cartesian-plane** [bitwarden/clients#7838] opened 2024-02-07 10:40 UTC
### Steps To Reproduce

Vault must be locked and unlockable with biometrics.
1. Go to any website for which Bitwarden has credentials stored.
2. Use the autocomplete shortcut (CMD + Shift + L) 
3. You will be prompted to unlock the vault with either your password or biometrics.
4. Unlock it with biometrics.
5. Use the autocomplete shortcut again. This will fill in the credentials and works as expected.

### Expected Result

SecureInput should turn off after unlocking the vault, as it does when unlocking the vault manually without the Autocomplete shortcut.

### Actual Result

SecureInput does not turn off, breaking BTT (Better Touch Tool) shortcut functionality.
A browser restart is required to disable it.

### Operating System

macOS

### Operating System Version

14.0

### Web Browser

Safari

### Browser Version

17.0

### Build Version

2023.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment] 2024-02-07 13:04
Hi there!


Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/6134 which, in turn, causes issues with Touch ID for the Safari extension.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

**Closed** 2024-02-07 13:05 UTC
Labels: bug, browser
