### ISSUE TITLE
BUG EXTENSION GOOGLE CHROME

### ISSUE THREAD

**Issue by esalanguerra** [bitwarden/clients#10840] opened 2024-09-01 21:53 UTC
### Steps To Reproduce

1. Start the Google Chrome browser normally
2. Click on the Bitwarden extension icon
3. Wait for the dialog box to open again
4. There's your problem

### Expected Result

The browser extension should open instantly, without noticeable delays, even after restarting Google Chrome.
The closed padlock icon must be displayed clearly, indicating that the extension is active and ensuring browsing security.
The autocomplete feature should work correctly on all supported sites without displaying error messages. Login information must be auto-populated accurately and securely.
When accessing a website, the extension should correctly display the number of passwords available for the specific domain, making it easier to choose the correct login credential.

### Actual Result

- The browser extension is slower than normal, about 5 seconds of delay in opening when restarting the Google Chrome browser
- Closed padlock icon does not appear
- When trying to autofill, it returns an error "Unable to fill in on the current site, copy and paste" for any site
- When accessing a website, the number of possible passwords for the website does not appear

### Additional Context

The browser extension is performing below expectations, taking around 5 seconds to open after restarting Google Chrome, which compromises the user experience when using the browser.
Furthermore, the closed padlock icon, which normally indicates the extension's security, is not being displayed, which can create uncertainty about the protection offered during browsing.
Another problem encountered is the difficulty in using the autocomplete feature. When trying to fill in the login information, the extension returns an error message: "Unable to fill in on current website, copy and paste", regardless of the website accessed. This issue forces the user to manually copy and paste credentials, which is less practical and secure.
Finally, when accessing a website, the extension is not showing the number of passwords available for that specific domain, which makes it difficult to choose the correct credential and can cause frustration when trying to access different accounts.

### Operating System

Linux

### Operating System Version

Arch Linux kernel 6.10

### Web Browser

Chrome

### Browser Version

 128.0.6613.113 (Official Build) (64-bit)

### Build Version

2024.8.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by JABirchall** [comment] 2024-09-02 00:07
Duplicate of #10814 #10815

**Comment by sammbw** [comment] 2024-09-02 02:39
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/clients/issues/10814

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by sammbw** 2024-09-02 02:39 UTC
Labels: bug, browser
