### ISSUE TITLE
Authentication fails to respond on attempt to edit password-protected item

### ISSUE THREAD

**Issue by jwhizz** [bitwarden/clients#6423] opened 2023-09-27 14:46 UTC
### Steps To Reproduce

1. Click "Edit" on a password-protected item.
2. Authentication dialog presented.
3. Enter proper authentication and click OK.
4. No response - no error message, no change in dialog, nothing.
5. Other buttons still functional (e.g. Cancel)

### Expected Result

Authentication acknowledged and item able to be edited.

### Actual Result

No change to Authentication dialog after entering proper password and clicking OK. Other buttons seem to work fine. Yes I triple checked the password I entered. It is correct.

### Operating System

Windows

### Operating System Version

10

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.8.3 (by the way there are multiple "versions" and none specify "Build Version".

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2023-09-27 14:53
Duplicate of https://github.com/bitwarden/clients/issues/6153

**Comment by djsmith85** [comment] 2023-09-27 14:53
Hi @jwhizz 

This seems to have previously been reported with https://github.com/bitwarden/clients/issues/6153 and https://github.com/bitwarden/mobile/issues/2733 (mobile) and fixes have been issued which are included in 2023.9-release. The release has already been pushed out to the stores and awaiting approval from them. It should be available soon. You could also download the latest from https://bitwarden.com/download/

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2023-09-27 14:53 UTC
Labels: bug, desktop
