### ISSUE TITLE
Bitwarden Linux App Fails to Login with Duo 2FA

### ISSUE THREAD

**Issue by hn-sl** [bitwarden/clients#9554] opened 2024-06-09 03:12 UTC
### Steps To Reproduce

1. Go to the Bitwarden Linux desktop app.
2. Enter your master password.
3. When prompted, click to launch Duo in the browser.
4. Observe the redirect to a webpage showing "Internal Server Error".
5. Refresh the webpage.
6. Complete the authentication process with Duo.
7. Notice the redirect back to the initial login page, which repeats infinitely.

### Expected Result

After completing the Duo authentication, I should be logged into my Bitwarden account on the Linux desktop app.

### Actual Result

After entering the master password and launching Duo in the browser, the process results in an "Internal Server Error" page. Refreshing the page correctly shows the authentication process, but upon completing Duo authentication, it redirects back to the initial login page and repeats the process infinitely, preventing successful login.

### Screenshots or Videos

Screen after entering master password:
![image](https://github.com/bitwarden/clients/assets/48025074/b9a86273-a329-4604-95d0-f7c62c318e99)

This redirect to Internal Server Error page:
![image](https://github.com/bitwarden/clients/assets/48025074/b1c7a290-cbe1-4748-8ec2-1231be226856)

Correct authentication page after refresh:
![image](https://github.com/bitwarden/clients/assets/48025074/3b494df0-074e-47b5-830c-aebef5a51bc5)

Infinite login loop after Duo authentication:
![image](https://github.com/bitwarden/clients/assets/48025074/b7c8bd09-60a4-40c0-8675-d02b1e9955f3)

### Operating System

Linux

### Operating System Version

Ubuntu 22.04.4 LTS

### Web Browser

Chrome

### Build Version

Version 2024.5.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment] 2024-06-09 13:19
Hi @hn-sl,

Thank you for this report.
1. How did you install that Bitwarden desktop client on Ubuntu? Snap?
2. Which browser are you using, and how was it installed?

Thank you in advance,

**Comment by hn-sl** [comment] 2024-06-09 13:24
> Hi @hn-sl,
> 
> Thank you for this report.
> 
> 1. How did you install that Bitwarden desktop client on Ubuntu? Snap?
> 2. Which browser are you using, and how was it installed?
> 
> Thank you in advance,


1. I have tried installing the Bitwarden desktop app both from the Snap Store and directly from the Bitwarden website.
2. I'm using the latest version of Chrome downloaded from the official Chrome website.

**Comment by nihakuto** [comment] 2024-07-12 04:59
I am seeing the exact same behavior on the Desktop bitwarden app installed via Archlinux's official repos.

**Comment by FabianKnapp** [comment] 2024-08-16 08:31
Same problem here. Please fix this asap!

**Comment by ljlapierre** [comment] 2024-10-31 03:26
Adding my situation... also broken with Duo.

Using NixOS, both standard nix packages for bitwarden-desktop and firefox.

Please let me know if there's any debug information I can provide that would assist, happy to do it!

**Comment by trmartin4** [comment] 2024-11-08 21:00
Hello!  We have identified an [upstream bug](https://github.com/electron-userland/electron-builder/issues/8234) in `electron-builder` that is preventing the necessary callbacks from working to support Duo.  These callbacks were necessary due to an update to Duo's SDK to support a redirect-based model instead of the previous `iframe` implementation, which we implemented earlier this year. 

We have some options for a workaround, which we are looking into, but I wanted to let you know what we believe the root cause to be.

**Comment by trmartin4** [comment] 2024-11-13 23:14
We have been able to address the upstream bug in our code with #11932.  This fix will be in our next desktop release.  At this point we cannot commit to exactly when that release will be, but this fix will be included.  I'll keep this issue open until you're able to confirm that Duo works with the proposed changes.

In the interim, if you would like to test against the build artifacts that include the change to address this, you can find them here: https://github.com/bitwarden/clients/actions/runs/11817902532.  These are development build artifacts, so please keep in mind they have not gone through our full release candidate regression testing.

**Comment by trmartin4** [comment] 2024-12-20 16:51
@hn-sl this change has been released and is available on the desktop client.  We will be closing this issue, but please feel free to re-open if you continue to encounter issues.

**Closed by trmartin4** 2024-12-20 16:51 UTC
Labels: bug, browser

**Comment by deuxdois** [comment] 2025-07-22 21:56
@trmartin4 - I am still experiencing the same exact issue as before. Both with the official Snap package and the Arch repository version (which despite being flagged out-of-date, should contain https://github.com/bitwarden/clients/pull/11932 )

My Duo 2FA opens in a firefox session - could that be part of the issue?
