### ISSUE TITLE
Indistinguishable selection color in header search box

### ISSUE THREAD

**Issue by 9Ninety** [bitwarden/clients#5318] opened 2023-05-01 16:00 UTC
### Steps To Reproduce

1. Open Bitwarden desktop client with Light theme
2. Type something in the "Search vault" input
3. Select partial text

### Expected Result

There should be a clear distinction between selected text and normal text

### Actual Result

Selected text was using blue background and white foreground, which was exactly same with normal text

### Screenshots or Videos

<img width="93" alt="Current" src="https://user-images.githubusercontent.com/38161479/235483086-3e20abe2-e354-4bfb-8f08-edddebec4a88.png">

### Operating System

Windows

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.4.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SaabirahMohamed** [comment] 2023-05-02 09:57
Hi there @9Ninety 

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration https://bitwarden.com/help/searching-vault/#wildcards-and-advanced-search-parameters

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

**Comment by 9Ninety** [comment] 2023-05-02 10:03
Hi, @SaabirahMohamed 

It’s a style issue in CSS, not about search function nor server configure.

**Comment by djsmith85** [comment] 2023-05-02 10:31
Duplicate of https://github.com/bitwarden/clients/issues/4769

**Closed by djsmith85** 2023-05-02 10:31 UTC
Labels: bug, desktop

**Comment by SaabirahMohamed** [comment] 2023-05-02 12:22
Hey @9Ninety ,

Sorry about the confusion. I was actually testing out something different with the search field, and it seems like my colleague Daniel already noted that this was a duplicate request.

I really appreciate you bringing this to our attention, though. It's always helpful to have users like you who are so observant and attentive to detail.
