### ISSUE TITLE
bw status reports "locked" state after unlock while CLI is in fact "unlocked"

### ISSUE THREAD

**Issue by Hooch180** [bitwarden/clients#6705] opened 2023-10-26 08:09 UTC
### Steps To Reproduce

1. bw login
2. bw lock
3. bw unlock (I did it with master password and --raw)
4. bw status (It now reports "locked")
5. bw list items (Lists all items and doesn't ask for the password, confirming that vault is unlocked)

### Expected Result

bw status should report "unlocked" if vault is unlocked.

### Actual Result

bw status reports "locked" for "unlocked" vault messing up any automations.

### Operating System

Windows

### Operating System Version

Windows 11

### Shell

PowerShell

### Build Version

2023.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2023-10-26 08:23
Duplicate of https://github.com/bitwarden/clients/issues/2729

**Comment by djsmith85** [comment] 2023-10-26 08:28
Hi @Hooch180,

Thank you for your report. This report seems like it is a duplicate of this (#2729).

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This report will now be closed.

Thank you again

**Closed by djsmith85** 2023-10-26 08:28 UTC
Labels: bug, cli
