### ISSUE TITLE
Master password re-prompt items not accessible via desktop, browser or app

### ISSUE THREAD

**Issue by mateusz-obara** [bitwarden/clients#6176] opened 2023-09-02 12:05 UTC
### Steps To Reproduce

On desktop (Windows 11) / browser extension (Edge) / app (Android 13) :
1. Go to item with master password re-prompt option turned on
2. Write the master password
3. Click enter or OK button

### Expected Result

It either shows the hidden password or copies copies it to clipboard

### Actual Result

On desktop (Windows 11) / browser extension (Edge) :
Nothing happens, no error. It behaves like the "OK" button is not working.

On app (Android 13) :
App crashes.

### Additional Context

I noticed the problem yesterday (2023-09-02) after desktop update to 2023.8.2. The only workaround is using the website vault.

### Operating System

Windows

### Operating System Version

Windows 11 Pro 22621.2215

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.8.2

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by gkl1368** [comment] 2023-09-02 14:29
I have the same problem, but I found a ways to solve it. you must use master password to unlock at the first time you open the app.

**Comment by waynelloyd** [comment] 2023-09-02 15:36
I have started having the same problem on the macOS app Version 2023.8.2 (11197) and IOS Version 2023.8.0 I have to use the web vault as a work around it.

**Comment by Humorist3142** [comment] 2023-09-02 16:03
I had the same problem today as well, on Android version 2023.8.0 (7466). Had to turn on my PC to retrieve the entry I needed.

**Comment by SergeantConfused** [comment] 2023-09-03 18:06
Hi @mateusz-obara,

Thank you for your report, and thanks to everyone else for submitting more information. This seems like it is a duplicate of this one (https://github.com/bitwarden/clients/issues/6153).

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in that report - our engineering team will be happy to review these.

This report here will now be closed.

Thank you again,

**Closed by SergeantConfused** 2023-09-03 18:06 UTC
Labels: bug, desktop
