### ISSUE TITLE
Browser extension breaks pretty print of xml

### ISSUE THREAD

**Issue by sweeeneey** [bitwarden/clients#7305] opened 2023-12-21 08:20 UTC
### Steps To Reproduce

1. With the Bitwarden extension enabled browse to https://www.w3schools.com/xml/note.xml

### Expected Result

The xml is rendered with Firefox's pretty print:
![Screenshot from 2023-12-21 09-14-59](https://github.com/bitwarden/clients/assets/60924557/07b6be17-3d3d-4388-a3a3-f4be0598e406)

### Actual Result

The xml is rendered as plain text:
![Screenshot from 2023-12-21 09-16-16](https://github.com/bitwarden/clients/assets/60924557/96ead2e3-031e-407a-9f8f-f78f8a0aba59)

### Operating System

Linux

### Operating System Version

Ubuntu 23.10

### Web Browser

Firefox

### Browser Version

121.0

### Build Version

2023.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2023-12-21 13:53
Duplicate of https://github.com/bitwarden/clients/issues/6865

**Closed** 2023-12-21 13:53 UTC
Labels: bug, browser
