### ISSUE TITLE
Bitwarden blocking shutdown in MacOS Sonoma

### ISSUE THREAD

**Issue by Jensette** [bitwarden/clients#9186] opened 2024-05-15 07:08 UTC
### Steps To Reproduce

1. Go to '.Apple Menu in the left upper corner'
2. Click on 'Shutdown'

### Expected Result

MacBookPro (M1) will not shut down. After a while there will be an error message saying that BW is preventing the system from shutting down.

### Actual Result

I have to "force quit" Bitwarden. 

### Screenshots or Videos

<img width="390" alt="Bildschirmfoto 2024-05-15 um 09 05 09" src="https://github.com/bitwarden/clients/assets/169880372/43300518-3db5-4da8-9ea5-a52a3fc10951">

### Operating System

macOS

### Operating System Version

14.5 (23F79)

### Installation method

Mac App Store

### Build Version

Version 2024.3.0 (21897)

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-05-15 07:22
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: #8292.

Additionally, it seems that the most recent update to the Bitwarden desktop application may have resolved the issue. Please update the desktop app to version >= 2024.3.2 and see if that resolves the issue.

This issue will now be closed.

Thanks!

**Closed** 2024-05-15 07:23 UTC
Labels: bug, desktop

**Comment by Jensette** [comment] 2024-05-15 07:40
Thank you very much for ultra fast response @djsmith85. I didn't notice that the "auto update" in the AppStore was not doing it's job. Also I am not known as a clever "existing issue and report seeker" at best of my times, sorry for bothering.

**Comment by djsmith85** [comment] 2024-05-15 07:50
> Thank you very much for ultra fast response @djsmith85. I didn't notice that the "auto update" in the AppStore was not doing it's job. Also I am not known as a clever "existing issue and report seeker" at best of my times, sorry for bothering.

Thank you for the praise @Jensette, no worries and happy to help and see it's working again.
