### ISSUE TITLE
Bitwarden for firefox signs out after a few months on its own even if "vault timeout" is set to "never"

### ISSUE THREAD

**Issue by rthfhgyhy567** [bitwarden/clients#10323] opened 2024-07-29 20:49 UTC
### Steps To Reproduce

Bitwarden for firefox signs out after a few months on its own even if "vault timeout" is set to "never"

### Expected Result

Bitwarden for firefox signs out after a few months on its own even if "vault timeout" is set to "never"

### Actual Result

Bitwarden for firefox signs out after a few months on its own even if "vault timeout" is set to "never"

### Operating System

Windows

### Operating System Version

Windows 10 Pro

### Web Browser

Firefox

### Browser Version

128.0b9 (64-bit)

### Build Version

2024.6.3

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment] 2024-07-31 07:46
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/8873

This bug should be fixed once the 2024.7.1 version of the Firefox extension gets available.

This issue will now be closed.

Thanks!

**Closed by Greenderella** 2024-07-31 07:46 UTC
Labels: bug, browser
