### ISSUE TITLE
desktop app  does not minimize when password is copied in certain situations 

### ISSUE THREAD

**Issue by T2MWorks-Mitch** [bitwarden/clients#5886] opened 2023-07-24 21:13 UTC
### Steps To Reproduce

1. right click on an entry
2. select copy password  

### Expected Result

window is mimimized 

### Actual Result

window stays open 

### Screenshots or Videos

https://github.com/bitwarden/clients/assets/78434822/b946acfc-9b40-4343-8bc5-7c5bdd32f11d

### Additional Context

note in the video the first time I right click select the entry ( at 0:03)  the "selection bar" ( on the left side of the entry) goes gray 
and the 2nd time I left click then right click ( at 0:09)  and the bar becomes blue 

if the bar is gray the app never minimizes 
if it is blue it will minimize 

### Operating System

macOS

### Operating System Version

13.4.1 (c)

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2023.5.1 Shell 24.1.1 Renderer 112.0.5615.50 Node 18.14.0 Architecture arm64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2023-07-24 23:12
Duplicate of https://github.com/bitwarden/clients/issues/4184

**Comment by djsmith85** [comment] 2023-07-24 23:13
@T2MWorks-Mitch Thank you for your report. This seems to be a duplicate so closing this now.

**Closed** 2023-07-24 23:14 UTC
Labels: bug, desktop
