### ISSUE TITLE
[Firefox extension] [Windows Desktop] [Web] Username generator with "Include number" now only generates single digit number

### ISSUE THREAD

**Issue by Tipoff4317** [bitwarden/clients#10388] opened 2024-08-03 21:26 UTC
### Steps To Reproduce

1. Firefox extension
2. Click Generator
3. Click Username, Random word, Include number

### Expected Result

A random word, plus 4-digit number, as in:

https://bitwarden.com/help/generator/

### Actual Result

A random word, plus a single-digit number

### Screenshots or Videos

The screenshot is from the web app:

![Bitwarden 2024-08-04 041752](https://github.com/user-attachments/assets/ef7f37ef-c50b-4b0f-893e-a5aea736f40c)

### Additional Context

Same "problem" with:
1. Firefox extension 2024.7.1
2. Windows desktop app 2024.7.1
3. Web app 2024.7.2

### Operating System

Windows

### Operating System Version

Windows 11 Pro 23H2

### Web Browser

Firefox

### Browser Version

128.0.1ESR

### Build Version

2024.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment] 2024-08-05 02:18
Hi there,

Thank you for your report!

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by eldergod1800** [comment] 2024-08-05 15:53
Also happening on the Linux Appimage 2024.7.1. Attached SS.
![Screenshot from 2024-08-05 11-51-24](https://github.com/user-attachments/assets/3de6e56f-6abb-47e9-93f9-35ca88309aac)
![Screenshot from 2024-08-05 11-51-57](https://github.com/user-attachments/assets/44d28deb-9513-48b0-91cf-3715634480a4)

**Comment by LZeugirdor** [comment] 2024-08-16 04:43
Can verify I'm also having this issue on windows desktop bitwarden 2024.7.1

**Comment by bin-wang** [comment] 2024-09-12 04:08
@sammbw It seems this issue has been fixed. Can you confirm that?

**Comment by sammbw** [comment] 2024-09-12 04:19
@bin-wang thanks for pointing this out - it looks like this was remedied here: https://github.com/bitwarden/clients/pull/10032

I can confirm it's working as expected in 2024.8.2 desktop for myself, as well as the 2024.8.1 Firefox extension.

I'm closing the issue as complete for now, but please feel free to comment if you see this occur again!

**Closed by sammbw** 2024-09-12 04:19 UTC
Labels: bug, browser

**Comment by eldergod1800** [comment] 2024-09-12 11:31
Yes it is working again in 22024.8.2 desktop appimage.

**Comment by cloning5480** [comment] 2025-01-31 15:04
@sammbw 
I am using the firefox extension version 2024.12.4 and it is only generating a single digit. Chromium extension has multiple digits

**Comment by chris-velox** [comment] 2025-02-18 02:26
Broken again in FF Extension 2025.1.4 and Desktop 2024.12.1.
