### ISSUE TITLE
Account Fingerprint Phrase does not match after first login in desktop apps

### ISSUE THREAD

**Issue by Tomava** [bitwarden/clients#5347] opened 2023-05-03 17:48 UTC
### Steps To Reproduce

1. Log out of desktop app or reinstall it. 
2. Log in and observe the account's fingerprint phrase. It should not match what's shown in other client apps.
3. Lock the vault and then open it again or restart the client app. The fingerprint phrase should now match the other client apps.

### Expected Result

Account's fingerprint phrase should match across all devices.

### Actual Result

The fingerprint phrase doesn't match after the first login.

### Additional Context

Seems to be related to #5297.

In addition to portable version, also happens on at least **Windows installer version**, **Windows store version** and **Linux deb package** but NOT on **Firefox browser extension (2023.3.1)** or **Android app**.

### Operating System

Windows, Linux

### Operating System Version

Windows 10 22H2, Ubuntu 20.04.6 LTS

### Installation method

Direct Download (from bitwarden.com), Microsoft Store

### Build Version

2023.4.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment] 2023-05-03 21:18
Hi there!

Thank you for your report, it seems like it is a duplicate of this one [link to the original GitHub issue]. 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by Neonwarden** 2023-05-03 21:18 UTC
Labels: bug, desktop

**Comment by Neonwarden** [comment] 2023-05-03 21:28
https://github.com/bitwarden/clients/issues/5297
