### ISSUE TITLE
Fetched thumbnails from website to vault panel are no more resized, giant display, readability problem

### ISSUE THREAD

**Issue by benjabox** [bitwarden/clients#9882] opened 2024-06-30 11:53 UTC
### Steps To Reproduce

In Firefox, with Bitwarden add-on installed : 
Simply show bitwarden panel - either in its pop-up mode or side panel mode

### Expected Result

I expect to see what I always saw : constant height lines with thumbnail, name, associated username and the handy buttons "open", "copy username", "copy password" and "copy verfication code".

![snap_240630_13h29'48](https://github.com/bitwarden/mobile/assets/70324001/b8fe11bb-4e66-4441-81ee-48b917f3c214)

### Actual Result

Instead, some of the thumbnails seem not to be correctly resized anymore. The original png file fetched from the website (where it may be unoptimized and very large) is then displayed as is, and this makes the bitwarden interface weird and unreadable. 

### Screenshots or Videos

Here are two screenshots where you see the problem in many of the entries (but not all) : 

![snap_240630_13h22'04](https://github.com/bitwarden/clients/assets/70324001/5fbb5914-d3a2-4025-9be1-a27819fa95e8)

![snap_240630_13h21'26](https://github.com/bitwarden/clients/assets/70324001/ffe05a18-4b6a-4d72-be37-b8eb7ab03a2e)

### Additional Context

Operating System: Kubuntu 24.04
KDE Plasma Version: 5.27.11
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.13
Kernel Version: 6.8.0-31-generic (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-3770K CPU @ 3.50GHz
Memory: 23.4 Gio of RAM

**Firefox 127.0 (64 bits)**  (Note that I do not know whether the bug began with a browser update or some other event, but it feels l hadn't see that until very recently, maybe weeks)
![snap_240630_13h39'38](https://github.com/bitwarden/mobile/assets/70324001/843c570f-a047-444f-b969-a7b662766a6f)

### Operating System

Linux

### Operating System Version

Kubuntu 24.04

### Web Browser

Firefox

### Browser Version

127.0

### Build Version

2024.06.03

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment] 2024-07-01 10:32
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by BWPeter** [comment] 2024-12-17 20:37
Hello @benjabox,
Closing this issue as it appears the originally posted problem has been resolved. If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.

**Closed by BWPeter** 2024-12-17 20:37 UTC
Labels: bug, browser
