### ISSUE TITLE
Bitwarden ignores Show auto-fill menu on form fields off setting in Arc

### ISSUE THREAD

**Issue by jonskoglund** [bitwarden/clients#11305] opened 2024-09-28 05:06 UTC
### Steps To Reproduce

1. Open Arc Browser.
2. Go to a login page for a website for which you have the login and password in Bitwarden. 
3. For instance https://accounts.google.com/

### Expected Result

I have set the browser extension setting 'Show auto-fill menu on form fields' to OFF.  So I don't expect any bitwarden pop-up or icon in my username and/or passowrd input field.

### Actual Result

But instead a selection menu including bitwarden icon is shown when the input field is in focus  (when you click on the input field). This started happening a few weeks ago. 

### Screenshots or Videos

![Screenshot 2024-09-28 at 06 49 12](https://github.com/user-attachments/assets/297ae82b-60d7-4a0a-963f-0f809394d419)
![Screenshot 2024-09-28 at 06 49 49](https://github.com/user-attachments/assets/608539ff-79bf-43d0-9f38-58e8b6eaa7c1)
![Screenshot 2024-09-28 at 06 20 30](https://github.com/user-attachments/assets/b5f5ef60-dee9-4936-b0d9-a5c1286a9799)

### Additional Context

I use a keyboard shortcut to enter my login details and don't want to see or use any bitwarden icon or menu. 
This was normal behaviour up until a few weeks ago.

### Operating System

macOS

### Operating System Version

15.0 (24A335)

### Web Browser

Chrome

### Browser Version

Arc Browser

### Build Version

Version 1.61.2 (54148)

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by salfers** [comment] 2024-09-28 09:46
Same issue on Firefox 130.0.1 on Linux. I have always had it set to "off" yet the selection menu started appearing recently.

**Comment by salfers** [comment] 2024-09-28 09:50
in fact this is a duplicate of #11173

**Comment by RudeDude** [comment] 2024-09-28 23:32
I'm having this same problem in FireFox (ver 130.0.1 (64-bit)) on Windows with Extension version 2024.9.1 (self hosted with ver 2024.9.1)

**Comment by sammbw** [comment] 2024-09-30 02:57
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/clients/issues/11173

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by sammbw** 2024-09-30 02:57 UTC
Labels: bug, browser
