### ISSUE TITLE
I get locked out of so many accounts because Bitwarden will generate a random password and then neglect to save it anywhere.

### ISSUE THREAD

**Issue by tacoborn** [bitwarden/clients#12496] opened 2024-12-20 02:22 UTC
### Steps To Reproduce

I get locked out of so many accounts because Bitwarden will generate a random password and then neglect to save it anywhere.

### Expected Result

I get locked out of so many accounts because Bitwarden will generate a random password and then neglect to save it anywhere.

### Actual Result

I get locked out of so many accounts because Bitwarden will generate a random password and then neglect to save it anywhere.

### Screenshots or Videos

I get locked out of so many accounts because Bitwarden will generate a random password and then neglect to save it anywhere.

### Additional Context

I get locked out of so many accounts because Bitwarden will generate a random password and then neglect to save it anywhere.

### Operating System

Windows

### Operating System Version

I get locked out of so many accounts because Bitwarden will generate a random password and then neglect to save it anywhere.

### Web Browser

Chrome

### Browser Version

I get locked out of so many accounts because Bitwarden will generate a random password and then neglect to save it anywhere.

### Build Version

I get locked out of so many accounts because Bitwarden will generate a random password and then neglect to save it anywhere.

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by tacoborn** [comment] 2024-12-20 02:23
Do with this what you fucking will. Bitwarden's lack of polish is holding it back. The sooner you guys face that reality, the better.

**Comment by BBGhub** [comment] 2024-12-20 02:27
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/12047. 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by BBGhub** 2024-12-20 02:27 UTC
Labels: bug, browser
