### ISSUE TITLE
Unable to log in. Only shows spinning icon.

### ISSUE THREAD

**Issue by Daystrom5** [bitwarden/clients#8324] opened 2024-03-13 18:14 UTC
### Steps To Reproduce

1. Launch app.

### Expected Result

Prompt to log in.

### Actual Result

Login screen pops in for 1 second and then it flips to the spinning icon.

### Screenshots or Videos

![Screenshot 2024-03-13 141023](https://github.com/bitwarden/clients/assets/133052706/7c481985-4863-42d5-98b2-40dbdf6256e0)

### Operating System

Windows

### Operating System Version

Windows 10 Home (22H2)

### Installation method

Microsoft Store

### Build Version

2024.3.0

### Issue Tracking Info

- [ ] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by bjacksonbit** [comment] 2024-03-14 01:22
Hi, 
Thanks for reporting this. This appears to be a duplicate of https://github.com/bitwarden/clients/issues/6878
To resolve this, can I ask you to close Bitwarden, then open the following location inside a File Explorer and delete the entire contents of that folder: (https://bitwarden.com/help/data-storage/)

​Following that, please re-launch Bitwarden again 
This will now be closed

**Closed by bjacksonbit** 2024-03-14 01:22 UTC
Labels: bug, desktop
