### ISSUE TITLE
Windows Hello on start not working

### ISSUE THREAD

**Issue by indiana11011100** [bitwarden/clients#6199] opened 2023-09-06 08:04 UTC
### Steps To Reproduce

1. Using the normal Desktop App not the Store version.
2. Start the app manually or automatic startup after Windows Logon.
3. Nothing happens.

### Expected Result

After logon or manual start of the App the Windows Hello prompt should show automatically (Like before).

### Actual Result

The Windows Hello Logon Button can be pressed but the flag for automatic prompt is set (See Screenshot).

### Screenshots or Videos

![grafik](https://github.com/bitwarden/clients/assets/35570269/e7957231-c112-4587-944b-51d7a1bb0745)
![grafik](https://github.com/bitwarden/clients/assets/35570269/b1b749a9-b33e-4186-b1cd-9f2f4e38f8a3)

### Additional Context

Reinstall did not solve it.

### Operating System

Windows

### Operating System Version

Win11 22H2 Build 22621.2215

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.8.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Hinton** [comment] 2023-09-07 17:08
This seems to be a duplicate of https://github.com/bitwarden/clients/issues/6172

**Closed by Hinton** 2023-09-07 17:08 UTC
Labels: bug, desktop
