### ISSUE TITLE
TOTP for an account is different on mobile compared to desktop app and browser extension on windows

### ISSUE THREAD

**Issue by phloose** [bitwarden/clients#3346] opened 2022-08-20 12:29 UTC
### Steps To Reproduce

1. Open up an account with TOTP on mobile (iOS or Android) 
2. Open up the same account on Windows (desktop app and browser extension)
3. Compare codes
4. (optional) if Authy is also configured compare the generated codes

### Expected Result

The TOTP is the same

### Actual Result

The TOTP is different on mobile compared to windows apps (desktop and browser ext)

### Additional Context

The TOTP code for an account is different on the desktop app and browser extension compared to the mobile apps (ios, android). **This seems to only affect windows apps**. On linux (desktop and browser ext) it shows the exact same TOTP as in the mobile apps.

At first i suspected bitwarden to generate the TOTP a little different than authy but on mobile both show the same TOTP.

### Operating System

Windows

### Operating System Version

Windows 10 21H1 Build 19043.1889

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Desktop 2022.8.1, Browser Ext. 2022.8.0, Android 2022.8.0 (4911), iOS 2022.6.2 (1951)

**Comment by djsmith85** [comment] 2022-08-20 19:14
Hi @phloose and thank you for your report.

Could you please check your time and timezone settings on you Windows PC/devices? When users report that the TOTP codes diverge, the cause is in most cases a wrongly set time or timezone on one of the devices.

If this solves it, please close this issue. If it doesn't please add additional information.

Kind regards,
Daniel

**Comment by djsmith85** [comment] 2022-08-22 13:43
@phloose Thank you for reporting back and I'm happy to hear you were able to solve it.

**Closed by djsmith85** 2022-08-22 13:43 UTC
Labels: bug, desktop

**Comment by L1cardo** [comment] 2023-03-09 13:01
Hi, I am seeing this issue on my Win11. The totp on my iphone is not the same as my pc. 
My pc and my phone are both on UTC+8

**Comment by jimz011** [comment] 2023-10-11 14:06
I too have the same problem, time is correct on both devices.

Also the timer for TOTP codes on the desktop is completely different (when new codes are shown on my phone, the desktop has 15 seconds left)
