### ISSUE TITLE
[Win7] Javascript issue when updating to 2022.08

### ISSUE THREAD

**Issue by sso-bitwarden** [bitwarden/clients#3264] opened 2022-08-09 02:11 UTC
### Steps To Reproduce

Update to the latest version on Windows 7

### Expected Result

Update completed.

### Actual Result

Javascript error

### Screenshots or Videos

![win7 desktop update error](https://user-images.githubusercontent.com/75601583/183548282-50e3e5dc-86d2-4a1b-addc-335b06f0fb3a.png)

### Operating System

Windows

### Operating System Version

7

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.08

**Comment by djsmith85** [comment] 2022-09-04 17:34
Please also have a look at this [thread](https://community.bitwarden.com/t/windows-7-javascript-error/43503) on our Community Forums.

**Comment by T3rm1** [comment] 2022-09-04 17:41
Any information when this will get fixed? Is it even being worked on? There is nobody assigned to this issue.

**Comment by sso-bitwarden** [comment] 2022-09-04 23:39
> Any information when this will get fixed? Is it even being worked on? There is nobody assigned to this issue.

Since Windows 7 is no longer supported, users need to downgrade to the last working version and turn off the auto-update.

**Comment by T3rm1** [comment] 2022-09-05 08:21
And what version is that? Windows 7 still receives updates through ESU and there are rumours that Microsoft will extend security updates for another three years.
So, are Bitwarden users expected to find out what the latest version with Windows 7 support is on their own? Could you give a hint, please? I suspect that it depends on the Electron version that is being used.

**Comment by Hinton** [comment] 2022-09-05 10:05
It's unfortunate that the support for Windows 7 was dropped so abruptly. The root cause of the issue is that neither Node nor Electron supports Windows 7 any longer.

**2022.6.2** is the last version using the older Electron version. The automatic updates can be disabled either by running the portable version or by setting the `ELECTRON_NO_UPDATER=1` environment flag.

**Closed** 2022-09-15 15:15 UTC
Labels: bug, wontfix, desktop
