### ISSUE TITLE
WSDL doesn't show correctly in browser

### ISSUE THREAD

**Issue by eneagiuseppe** [bitwarden/clients#7858] opened 2024-02-08 17:18 UTC
### Steps To Reproduce

1. Go to this site: https://www.w3schools.com/xml/tempconvert.asmx?WSDL

### Expected Result

WSDL structure

### Actual Result

Blank page withouth any content.

### Screenshots or Videos

With plugin active
![immagine](https://github.com/bitwarden/clients/assets/77204386/c0d9096c-ef5f-49fa-94fc-88e4ccf21045)
Without plugin active
![immagine](https://github.com/bitwarden/clients/assets/77204386/16d62a4a-c321-4310-818f-270dddc88823)

### Additional Context

When deactivate the Bitwarted plugin the page is correctly displayed.

### Operating System

Windows

### Operating System Version

11

### Web Browser

Firefox

### Browser Version

122.0.1

### Build Version

2024.1.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment] 2024-02-15 12:30
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by djsmith85** [comment] 2024-02-22 12:41
Hi @eneagiuseppe

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/clients/issues/6865

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2024-02-22 12:41 UTC
Labels: bug, browser

**Comment by eneagiuseppe** [comment] 2024-02-23 08:12
Hi, confirm #6865 .
KR
Giuseppe
