### ISSUE TITLE
Loading screen when starting does not go to access 

### ISSUE THREAD

**Issue by theroopurple** [bitwarden/clients#6704] opened 2023-10-26 02:10 UTC
### Steps To Reproduce

Click in the app mine Desktop "Manjaro Menu"

Appear Bitwarden, screen loading show access data but again show loading screen and stay here

### Expected Result

Log back in without waiting for the loading screen

### Actual Result

Gets completely stuck on the loading screen

### Screenshots or Videos

![Screenshot_20231025_230939](https://github.com/bitwarden/clients/assets/129464944/13b0a16d-4986-4b78-a9db-2ab81468a4dc)

### Operating System

Linux

### Operating System Version

Manjaro Linux

### Installation method

Other

### Build Version

Versión 2023.9.0 Shell 24.8.6 Renderer 112.0.5615.204 Node 18.14.0 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment] 2023-10-26 03:27
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/clients/issues/6560

This issue should've been addressed in 2023.9.3 clients. Please try updating to the latest version to resolve this issue.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by sammbw** 2023-10-26 03:27 UTC
Labels: bug, desktop
