### ISSUE TITLE
Update Deleted All Files in Bitwarden Program Folder

### ISSUE THREAD

**Issue by dgulik** [bitwarden/clients#2819] opened 2022-06-03 01:11 UTC
### Steps To Reproduce

1. Opened Bitwarden
2. Prompt to restart for update
3. Select cancel for Bitwarden log in
4. Selected 'restart'
5. Windows installation verification pops up; select 'yes' install
6. Prompt to delete shortcut which is no longer valid; select 'yes' delete shortcut
7. Bitwarden has been uninstalled and Program Folder is empty.

### Expected Result

Expected a simple update.

### Actual Result

Program not updated but uninstalled/files deleted.

### Operating System

Windows

### Operating System Version

Windows 10 Pro Version;21H2  OS build 19044.1706

### Installation method

Other

### Build Version

Whatever the latest version was before today's update.

**Comment by fxzxmicah** [comment] 2022-06-03 01:18
The same problem. Why is installation directory selection no longer supported? I think this is the basic function of an installer.

**Comment by PhoenixCODE2322** [comment] 2022-06-03 02:42
same here, lmao now i am reinstalling,

**Comment by krnicholls** [comment] 2022-06-03 04:10
Also the same on Windows 11 Pro 21H2 / 22000.675.

Prompted to update, then the desktop app self-destructed.

**Comment by DarkLordGMS** [comment] 2022-06-03 04:38
Same here.
Windows 10 Pro 21H2

**Comment by Gsak3l** [comment] 2022-06-03 06:07
Same thing here, Windows 11 21h2

**Comment by nurtext** [comment] 2022-06-03 07:57
Same for me and a colleague

**Comment by johegl** [comment] 2022-06-03 10:35
Same here on Windows 10 Pro 21H2. User data is still there though, so reinstalling went quickly and it kept my settings.
This is a real problem for people who are not that tech-savvy...

**Comment by FbnGnstn** [comment] 2022-06-03 11:12
Same here on Windows 11 Pro 21H2. Manually reinstalled Bitwarden, everything (settings, logged in user etc) was kept.

**Comment by avachen** [comment] 2022-06-03 16:22
Same, Windows 10 Home 21H2

**Comment by akoessler** [comment] 2022-06-04 10:41
Same for me, on three machines: Windows 11 Pro 22H2 (Insider), Windows 11 Pro 21H2, Windows 10 Enterprise 21H2
Bitwarden prompted for update, and when updating it silently removed everything, without any further interaction or message.
I even did not notice right away, noticed it when I next needed bitwarden, and then it was gone completely from the system.
After manually downloading and installing, the client does work normal.

**Comment by mikenor** [comment] 2022-06-14 01:58
This sounds like a duplicate of #2622.
Happened to me on Win 11 Pro 22H2 (Insider Preview Build 22621.1).

**Closed** 2022-07-06 13:23 UTC
Labels: bug, desktop, customer-support, already-fixed
