### ISSUE TITLE
Safari extension interferes with ReCaptcha

### ISSUE THREAD

**Issue by C10H12N2O** [bitwarden/clients#2659] opened 2022-05-08 11:04 UTC
### Steps To Reproduce

1. Go to https://play.hbomax.com/login
2. Enter credentials
3. Click on 'SIGN IN'

### Expected Result

The page should proceed with authentication and display the user selection screen.

### Actual Result

After clicking SIGN IN nothing happens on the page. However in the debug console you can see that ReCaptcha script returns an error 'Invalid API Parameter(s). Try reloading the page' (screenshot attached). Disabling the Bitwarden extension fixes the issue.

### Screenshots or Videos

<img width="746" alt="Screenshot 2022-05-08 at 12 58 08" src="https://user-images.githubusercontent.com/12178406/167293091-2a407288-45b7-45a3-8902-e326da65f8aa.png">

### Operating System

macOS

### Operating System Version

12.3.1 (21E258)

### Web Browser

Safari

### Browser Version

15.4 (17613.1.17.1.13)

### Build Version

1.58.0

**Comment by C10H12N2O** [comment] 2022-05-19 08:50
This seems to be a wider issue. I've managed to replicate the same behaviour on https://store.serif.com/en-gb/sign-in/ - console output below.

<img width="748" alt="Screenshot 2022-05-19 at 10 44 08" src="https://user-images.githubusercontent.com/12178406/169253204-eed0c8c3-a54a-4b88-a204-81dad2f9a564.png">
.

**Comment by Steve-luo** [comment] 2022-05-25 16:36
Same here. Any website that uses recaptcha for login is failing for me.

**Comment by niklaswa** [comment] 2022-05-30 20:25
Same behaviour on Spotify.com for example.

They're aware of the issue and I mentioned again here: https://github.com/bitwarden/clients/issues/1870#issuecomment-1033952045
Unfortunately no progress since then 😕

**Comment by cgarren** [comment] 2022-07-26 22:23
+1 here! This autofill bug is super annoying and happens on many sites with captchas. Another example site is [speedtest.net](https://www.speedtest.net/login)

**Comment by cagonzalezcs** [comment] 2023-11-13 15:35
@C10H12N2O @cgarren 

I've reviewed the problems reported in this ticket, and have verified that this issue no longer exists when autofilling forms on these pages. It appears that at some point the logic for collection of page details was updated to ignore `type="hidden"` DOM elements, and as a result we do not collect these input elements for autofill. 

I'm closing this ticket, as the problem is not reproducible. However, if further issues arise, please let me know and we can re-open this task to address them.

**Closed by cagonzalezcs** 2023-11-13 15:35 UTC
Labels: bug, browser
