### ISSUE TITLE
Chrome extension window now smaller/shorter

### ISSUE THREAD

**Issue by FingerlessGlov3s** [bitwarden/clients#4017] opened 2022-11-08 23:15 UTC
### Steps To Reproduce

1. Open Brave as normal.
2. Go to 'Bitwarden Logo on your extension bar and click it.'
3. Notice the window is now shorter than it used to be, maybe 2/3 or a half of the size.

This is making it harder to operate.

### Expected Result

Window length to be usual length. Like below.
![image](https://user-images.githubusercontent.com/3495647/200695873-9858b419-8eea-4ad1-bd94-b65ea80eca11.png)

### Actual Result

Window is about half the size or so

![image](https://user-images.githubusercontent.com/3495647/200695922-9e99fa74-316a-46c8-8bfa-721e7a65ca2e.png)

### Additional Context

Issue happens also on my work device, using a different chrome based browser Microsoft Edge which is a different Bitwarden account as well, but on the same selfhosted instance.

### Operating System

Windows

### Operating System Version

Windows 10 21H2

### Web Browser

Microsoft Edge, Brave

### Browser Version

Chrome 107

### Build Version

Version 1.45.118 Chromium: 107.0.5304.91 (Official Build) (64-bit)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sebtiz13** [comment] 2022-11-08 23:51
Same issue as https://github.com/bitwarden/clients/issues/3970

**Comment by djsmith85** [comment] 2022-11-09 17:52
Thank you for your reports.

This is a duplicate and the issue is being tracked with #3970

A potential workaround has also been provided: https://github.com/bitwarden/clients/issues/3970#issuecomment-1303772308

Closing this now.

**Closed by djsmith85** 2022-11-09 17:52 UTC
Labels: bug, browser
