### ISSUE TITLE
Autofill browser function doesn't work

### ISSUE THREAD

**Issue by Bitwarden-ops** [bitwarden/clients#11384] opened 2024-10-03 15:22 UTC
### Steps To Reproduce

1. Go to '...' Bitwarden browser extension
2. Click on '....' the extension and select the username and password for the website to log into
4. Click on '...'

### Expected Result

The username and password would be entered into the appropriate fields to log into the website entered

### Actual Result

Error message that it can't populate and to use the copy and paste function instead

### Additional Context

This has been the case with numerous websites it previously used to work fine with

### Operating System

macOS

### Operating System Version

Ventura 13.7

### Web Browser

Chrome

### Browser Version

129.0.6668.89

### Build Version

2024.9.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by magicWF** [comment] 2024-10-03 22:47
I have the same problems, after the last update to version 2024.9.1 of my Firefox extension.

**Comment by lplohmann** [comment] 2024-10-04 00:17
I created an account and installed Bitwarden just today. But autofill doesn't work.

MacOS, Chrome.

**Comment by NovaSilentium** [comment] 2024-10-04 09:10
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by Imberflur** [comment] 2024-10-04 17:45
Hi I've noticed this recently in firefox as well. I don't know if it is related but there is an error in the console:
> Error: Could not establish connection. Receiving end does not exist. trigger-autofill-script-injection.js:5:20

![image](https://github.com/user-attachments/assets/4be76b46-0b1f-47c1-84ca-16c627c26ed7)

**Comment by dsgiigh** [comment] 2024-10-04 20:34
The autofill has been broken off and on for over a month now. (It's broken now.) Updates or reinstalling the extension sometimes fix it, but there is no consistency. It would be helpful to have this work properly again.

Version 2024.9.1
Firefox 130.0.1 (64-bit)
Linux 24.04.1

**Comment by DarkArc** [comment] 2024-10-06 19:27
I've definitely been experiencing this as well. It's super annoying.

Another key aspect of the bug (at least for me) is that when this happens, the extension icon doesn't show the count of passwords for the website (i.e., even though when I open the extension, it opens to the tab window and shows, e.g., my GitHub account, the extension doesn't have the "1" on it).

When the extension gets into this state, I also can't "lock" the vault manually. It acts like it's going to do it, but then it doesn't. I can just immediately reopen the extension. I've also had it to where the extension won't _unlock_ and doesn't show the unlock icon.

My vault is set to automatically lock on browser restart. So, _maybe_ this is related to a bad boot of the extension where it gets stuck in some bad state and then various actions stop working correctly.

A browser restart or extension reinstall seems to temporarily fix the problem.

**Comment by cagonzalezcs** [comment] 2024-10-07 18:15
This is a duplicate of https://github.com/bitwarden/clients/issues/10814

Extension release `v2024.10.0` resolves this problem, and that should be appearing soon within Firefox/Safari. It is already present on Chromium browsers. 

Closing this thread.

**Closed by cagonzalezcs** 2024-10-07 18:15 UTC
Labels: bug, browser

**Comment by LightningRocks** [comment] 2024-10-07 22:16
I updated to 2024.10.0 and if anything it gave me this problem whereas being on 2024.9.1 did not

**Comment by cagonzalezcs** [comment] 2024-10-08 02:18
@LightningRocks Try a re-fresh or re-installation of the extension, the updated build should have the fix in place.

**Comment by LightningRocks** [comment] 2024-10-08 07:43
I did reinstall the extension just now as well as do a browser restart right after install. I'm still having some intermittent issues where sometimes it works fine and sometimes it'll randomly not work at all. Like DarkArc mentioned, when it happens, the extension icon doesn't show the count of my passwords for the website as shown 

<img width="921" alt="Screenshot 2024-10-08 at 3 43 09 AM" src="https://github.com/user-attachments/assets/002cabf6-1809-4a3f-ab88-3eba0bdc0fc7">

**Comment by cagonzalezcs** [comment] 2024-10-08 11:08
@LightningRocks Hmm... I'll try to see if I can replicate that behavior. Are you seeing any console errors in the extension background script?

**Comment by LightningRocks** [comment] 2024-10-08 11:51
I am. I get these errors
<img width="772" alt="Screenshot 2024-10-08 at 7 48 40 AM" src="https://github.com/user-attachments/assets/afb571e8-eb41-4a5a-beb6-10dbe9f67e04">

**Comment by c0ball** [comment] 2024-10-10 15:57
> This is a duplicate of #10814
> 
> Extension release `v2024.10.0` resolves this problem, and that should be appearing soon within Firefox/Safari. It is already present on Chromium browsers.
> 
> Closing this thread.

Is there an ETA for when 2020.10.0 will be available for Firefox?

**Comment by cagonzalezcs** [comment] 2024-10-11 20:11
As far as I'm aware, we've never received any indication of when Mozilla is going to publish our submitted extension. The process for them always takes at least a week, sometimes more. 

I apologize that I can't give a better answer than that, but it's not something we can control.

**Comment by c0ball** [comment] 2024-10-11 20:15
Thanks for the update, I didn't realize the delay was caused by Mozilla as I didn't know Mozilla had to review/release updates for browser extensions.

**Comment by DarkArc** [comment] 2024-10-11 20:19
> As far as I'm aware, we've never received any indication of when Mozilla is going to publish our submitted extension. The process for them always takes at least a week, sometimes more.
> 
> I apologize that I can't give a better answer than that, but it's not something we can control.

@cagonzalezcs If I understand correctly, this is because the extension is "Recommended" by Mozilla. As a Bitwarden customer ... at this point, I don't think that status is worth the customer impact when it comes to patching bugs. IIRC, this is the second time I've had to deal with a _very_ annoying bug for a prolonged period because of this verification process (I forget what the prior bug was).

I'd really like to see more bullet proof QA or this "Recommended" status dropped so that we don't have to deal with prolonged delays like this.

**Comment by LightningRocks** [comment] 2024-10-14 04:47
Okay so when I swapped to using the Chrome store version of the extension rather than the Microsoft Store one, all my issues seem to have been fixed up. I'm not sure why but I'll take it. Hope for everyone else on Firefox that it gets approved soon. I personally don't have any issues with 2024.9.1 on that though
