### ISSUE TITLE
Menu Blocking Website View

### ISSUE THREAD

**Issue by ChihweiLHBird** [bitwarden/clients#11403] opened 2024-10-04 04:00 UTC
### Steps To Reproduce

Quote an auto insurance policy on progressivedirect.com

### Expected Result

Allow me to cancel the autofill menu and select items provided by the website

### Actual Result

It blocks the options provided by the website, with no cancel button.
![image](https://github.com/user-attachments/assets/7b0cf7ee-ea92-4f6b-b9b7-e0343c4ce90c)

### Operating System

Windows

### Operating System Version

11

### Web Browser

Firefox

### Browser Version

131

### Build Version

2024.9.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by BBGhub** [comment] 2024-10-04 04:04
Hi There,

Thank you for your report, it seems like it is a duplicate of this one (https://github.com/bitwarden/clients/issues/10814). 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

You may also find a separate workaround for your specific browser within the GitHub issues comments above, using the esc key will also remove this.

This issue will now be closed.

Thanks!

**Closed by BBGhub** 2024-10-04 04:04 UTC
Labels: bug, browser

**Comment by ChihweiLHBird** [comment] 2024-10-04 09:15
@BBGhub I don't think that's the same issue. They were complaining about the auto-fill failed, and what I am complaining is that Bitwarden browser extension show a menu that blocks website's functionality and there is no way to close that menu.

**Comment by cagonzalezcs** [comment] 2024-10-04 14:17
@ChihweiLHBird 

We have some improvements coming down the pipe to help with this. For now, you can press `Esc` to close the menu, though typing in the menu will bring it up again. That behavior is being changed in https://github.com/bitwarden/clients/pull/11114

**Comment by ChihweiLHBird** [comment] 2024-11-25 05:02
@cagonzalezcs Pressing `esc` on many websites close not only the Bitwarden menu but also the website's menu..
