### ISSUE TITLE
Syncing Failed

### ISSUE THREAD

**Issue by Debagnik** [bitwarden/clients#7482] opened 2024-01-09 10:51 UTC
### Steps To Reproduce

1. Go to Bitwarden Browser extension for firefox/waterfox or edge/brave
2. Click on Settings tam and then sync
3. Click on Sync now

### Expected Result

The bitwarden vault Syncs and the username and passwords are updated

### Actual Result

An error message pops out as "Sync failed" and the old password remains on the vault

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/39880615/e1ecbbfe-5939-423c-9c34-0ae11671f732)

### Additional Context

I am using Waterfox (a fork from Firefox as my daily driver) all the browsers I tested with are on the same system and its an organisational device with a few network restrictions (Bitwarden was working fine on my device since last year)

### Operating System

Windows

### Operating System Version

11

### Web Browser

Microsoft Edge, Firefox, Brave

### Build Version

2023.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment] 2024-01-09 10:58
Hi there!

Thank you for your report, it seems like it is a duplicate of this one #7243  

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by Krychaz** 2024-01-09 10:58 UTC
Labels: bug, browser
