### ISSUE TITLE
Bitwarden Brave Extension Generates Random passwords in the background every second

### ISSUE THREAD

**Issue by PawelPWarchol** [bitwarden/clients#12285] opened 2024-12-07 22:38 UTC
### Steps To Reproduce

Go to bitwarden extension in Brave browser -> Generator -> Password history

### Expected Result

Only passwords generated previously by the user 

### Actual Result

100s of randomly generated passwords
![Screenshot 2024-12-07 at 22 22 47](https://github.com/user-attachments/assets/8ba98a4e-c90b-4a55-9abd-647bc2f4a15a)
![Screenshot 2024-12-07 at 22 22 38](https://github.com/user-attachments/assets/cd965f78-b6be-45cc-bd1c-f322776e6871)
![Screenshot 2024-12-07 at 22 22 29](https://github.com/user-attachments/assets/567fd78f-6360-4f31-821b-c05c298c24f0)
 

### Operating System

macOS

### Operating System Version

15.1.1 (24B91)

### Web Browser

Brave

### Browser Version

Version 1.73.91 Chromium: 131.0.6778.85 (Official Build) (arm64)

### Build Version

Version 1.73.91 Chromium: 131.0.6778.85 (Official Build) (arm64)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by rmcdowell-bitwarden** [comment] 2024-12-09 07:09
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/12047. 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by rmcdowell-bitwarden** 2024-12-09 07:09 UTC
Labels: bug, browser
