### ISSUE TITLE
"Change Master-Password" not poiting to self-hosted environment

### ISSUE THREAD

**Issue by GibberishIT** [bitwarden/clients#8091] opened 2024-02-26 11:16 UTC
### Steps To Reproduce

1. Go to 'Account'
2. Click on 'Change Master Password'
3. Browser window opens pointing to vault.bitwarden.com

### Expected Result

In self-hosted enviroments the link should point to the correct domain. Settings from ~/.config/Bitwarden/data.json:

[..]
        "global_environment_region": "Self-hosted",
        "global_environment_urls": {
                "base": "https://bitwarden.example.com",
[..]

Browser should point to bitwarden.exmaple.com

### Actual Result

Browser points to vault.bitwarden.com

### Operating System

Linux

### Operating System Version

Ubuntu 22.04

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-02-26 12:32
Duplicate of https://github.com/bitwarden/clients/issues/6750

**Comment by djsmith85** [comment] 2024-02-26 12:34
Hi @GibberishIT,

Thank you for your report. It seems like a duplicate of https://github.com/bitwarden/clients/issues/6750

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This report will now be closed.

Kind regards,
Daniel

**Closed by djsmith85** 2024-02-26 12:34 UTC
Labels: bug, desktop
