### ISSUE TITLE
Browser: remove "Pop out to a new window" when already popped out

### ISSUE THREAD

**Issue by patrickhlauke** [bitwarden/clients#2676] opened 2022-05-10 23:10 UTC
### Steps To Reproduce

1. Go to the extension
2. Click on 'Pop out to a new window" - the extension now opens in a new floating window
3. Click on 'Pop out to a new window" - another instance of the extension is opened up in another new floating window
4. ... etc

### Expected Result

When popped out, the button to "Pop out to a new window" should be disabled or hidden altogether.

### Actual Result

You can carry on opening infinite numbers of extension windows.

### Screenshots or Videos

![Four instances of the extension window popped out](https://user-images.githubusercontent.com/895831/167739265-ee2b5cb5-a2ed-4fc8-a61b-bbb9a8e631da.png)

### Operating System

Windows

### Operating System Version

11

### Web Browser

Chrome

### Browser Version

101.0.4951.54 (Official Build) (64-bit)

### Build Version

1.58.0

**Comment by djsmith85** [comment] 2022-05-20 08:24
@patrickhlauke Thank you for the report. Closing this as a duplicate of #1690.

**Closed by djsmith85** 2022-05-20 08:24 UTC
Labels: bug, browser
