### ISSUE TITLE
bitwarden keeps logging me out on Firefox

### ISSUE THREAD

**Issue by the9655a** [bitwarden/clients#9678] opened 2024-06-16 14:17 UTC
### Steps To Reproduce

You can't, it happens randomly but its only just now happening after using it for over a year.

### Expected Result

After configuring it so that the vault timeout action is "lock" and I have unlock with pin enabled, it should only lock it and ask for the pin when I close and reopen the browser.

### Actual Result

Recently, sometimes it completely resets when I reopen my browser and I have to enter my master password and enabled unlock with pin again.

### Additional Context

I've tried reinstalling, I did that when I first noticed it happening. Hasn't helped though.

### Operating System

Windows

### Operating System Version

10

### Web Browser

Firefox

### Browser Version

Latest (127.0)

### Build Version

2024.4.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment] 2024-06-16 14:20
Hello @the9655a,

Thank you for your report. This report seems to be a duplicate of [this GitHub report](https://github.com/bitwarden/clients/issues/8873); If there's anything you'd like to add, such as screenshots or video recordings of the screen, please feel free to add them to that existing GitHub report so that they'd be reviewed by the Bitwarden Engineering department.

This report will now be closed as a duplicate.

Thank you again,

**Closed by SergeantConfused** 2024-06-16 14:20 UTC
Labels: bug, browser
