### ISSUE TITLE
Chrome extensions load error

### ISSUE THREAD

**Issue by yodfz** [bitwarden/clients#6585] opened 2023-10-15 03:03 UTC
### Steps To Reproduce

<img width="797" alt="image" src="https://github.com/bitwarden/clients/assets/1439163/4fc757f0-12c7-4037-bb3d-da030f73c136">

### Expected Result

no error

### Actual Result

no error

### Operating System

macOS

### Web Browser

Chrome

### Build Version

116.0.5845.179

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2023-10-15 13:15
Duplicate of https://github.com/bitwarden/clients/issues/6562

**Comment by SergeantConfused** [comment] 2023-10-15 15:12
Hi @yodfz,

Thank you for your report. It seems that it is a duplicate of the report above (https://github.com/bitwarden/clients/issues/6562).

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This report will now be closed.

Thank you again,

**Closed by SergeantConfused** 2023-10-15 15:12 UTC
Labels: bug, browser
