### ISSUE TITLE
Edge WebAuthN with Phone - QR code is clipped

### ISSUE THREAD

**Issue by Redth** [bitwarden/clients#4176] opened 2022-12-02 15:47 UTC
### Steps To Reproduce

1. After enabling 2FA and adding webauthn keys on my account
2. Login on Edge to the browser extension
3. When prompted for "External excurity key or built-in sensor" or "Use phone with a QR code", choose "Use phone with a QR code"
4. Barcode is clipped / cut off and there's not enough visible area to scan properly (see image)

### Expected Result

Expected the page to fit so the barcode is completely visible, or at least be able to scroll the content of the page to make the barcode appear by scrolling.

### Actual Result

Barcode is clipped enough that it cannot be scanned.

### Screenshots or Videos

(Barcode was blacked out for privacy)

![image](https://user-images.githubusercontent.com/271950/205331504-98f33311-98ca-455e-a0db-d87ffb31d56c.png)

### Operating System

Windows

### Operating System Version

11

### Web Browser

Microsoft Edge

### Browser Version

107

### Build Version

107.0.1418.56

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TroyBW** [comment] 2023-07-14 19:34
Hi there,

I am unable to reproduce this issue in Bitwarden build version 2023.7.1. It seems that the issue you described was addressed in a subsequent release, so I am marking this issue as closed. If you are still encountering this issue, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

Thanks!

**Closed** 2023-07-14 19:34 UTC
Labels: bug, browser
