### ISSUE TITLE
Wired Window Popup with insert last credentials shortcut (Apple + Shift +L) in Firefox with opened bookmarks

### ISSUE THREAD

**Issue by hirschferkel** [bitwarden/clients#6553] opened 2023-10-11 10:04 UTC
### Steps To Reproduce

With version 2023.9.1 instead of opening a small popup at the plugin icon, a new, small window will open in firefox to unlock the vault with shortcut 

Apple + Shift + L (insert last credentials to website login) 

But I will always get the bookmarks opened in this window and it is impossible to read login information, is it possible to change again?

### Expected Result

Same Popup als with Shortcut Apple + Y (unlock vault)

### Actual Result

Absurd new window in Firefox

### Screenshots or Videos

![Bildschirmfoto 2023-10-11 um 11 45 18](https://github.com/bitwarden/clients/assets/16016422/25b1bbaa-27bb-40d8-bbcd-fe2207559f3a)

### Operating System

macOS

### Operating System Version

12.7

### Web Browser

Firefox

### Browser Version

118.01

### Build Version

Version: 2023.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by hirschferkel** [comment] 2023-10-11 20:06
@cagonzalezcs

**Comment by NovaSilentium** [comment] 2023-10-12 09:25
#duplicate of 6531

**Comment by NovaSilentium** [comment] 2023-10-12 09:27
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/6531

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Comment by hirschferkel** [comment] 2023-10-15 16:40
Maybe.

As I can see, it is not profile related but related to the origin tab.
So if sidebar with Bookmarks is open in the origin login window, the new window Pup Up for Bitwarden will have an open bookmark sidebar, too.

Actually this is not wanted, I think.

**Closed** 2023-10-16 08:37 UTC
Labels: bug, browser
