### ISSUE TITLE
Issues with Italian translation in Bitwarden Send

### ISSUE THREAD

**Issue by fabriziobagala** [bitwarden/clients#3809] opened 2022-10-17 11:11 UTC
### Steps To Reproduce

1. Go to https://vault.bitwarden.com/#/login
2. Enter username and password, and optionally two-factor authentication
3. Click on 'Send'

### Expected Result

For the Italian language, you can read the contents of the filter section in Bitwarden Send.

### Actual Result

For the Italian language, it is not possible to read the contents of the filter section in Bitwarden Send.

### Screenshots or Videos

![immagine](https://user-images.githubusercontent.com/62190484/196162688-8649f654-9e98-4026-80e4-691c69faeabd.png)

### Operating System

macOS

### Operating System Version

12.6

### Web Browser

Firefox

### Browser Version

105.0.3 (64 bit)

### Build Version

2022.10.0

**Comment by djsmith85** [comment] 2022-10-17 11:16
Hi @fabriziobagala and thank you for your report. 

This has previously been reported with https://github.com/bitwarden/clients/issues/3789 and also has received a fix last week.

This will be rolled out soon.

Duplicate of https://github.com/bitwarden/clients/issues/3789

**Closed by djsmith85** 2022-10-17 11:16 UTC
Labels: bug, web
