### ISSUE TITLE
Do not steal password focus when prompting for update

### ISSUE THREAD

**Issue by briandeheus** [bitwarden/clients#8657] opened 2024-04-10 05:10 UTC
### Steps To Reproduce

1. Open the Bitwarden app when there is an update
2. Begin entering your password
3. Whilst typing your password, there is a large chance the update alert will popup
4. Press enter to submit your password
5. Actually you will be sending input to the update alert

### Expected Result

1. Open the Bitwarden app when there is an update
2. Begin entering your password
3. The app waits for input to have lost focus
4. The app prompts for updates

### Actual Result

See steps to reproduce

### Operating System

Windows, macOS, Linux

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.3.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment] 2024-04-10 05:54
Hi there!

Thank you for your report, it seems like it is a duplicate of this one #2608  

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by daniellbw** 2024-04-10 05:54 UTC
Labels: bug, desktop

**Comment by briandeheus** [comment] 2024-04-10 10:24
My bad! I couldn't find the other tickets. Thanks.
