### ISSUE TITLE
Bitwarden will not quit

### ISSUE THREAD

**Issue by ubercool** [bitwarden/clients#8365] opened 2024-03-17 21:39 UTC
### Steps To Reproduce

1. Go to 'Bitwarden/Quit Bitwarden'
2. Click on 'Quit Bitwarden'

### Expected Result

Quit

### Actual Result

Hang

### Operating System

macOS

### Operating System Version

14.4

### Web Browser

Safari

### Build Version

2024.3.0 (21897)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-03-17 21:43
Duplicate of https://github.com/bitwarden/clients/issues/8292

**Comment by ubercool** [comment] 2024-03-17 21:49
Sorry, but in my book, “Close” is not the same as quitting. Close is clicking on a window close box.

**Comment by RemcodM** [comment] 2024-03-18 20:27
I am experiencing the same issue as you: Bitwarden will not quit on request. Still, I am tracking issue #8292 for this. Although the wording of this issue is different, this is still a duplicate as far as I am concerned.

**Comment by Leica-afk** [comment] 2024-03-19 08:28
Same problem. Please fix it soon!

**Comment by madscienceli** [comment] 2024-03-19 22:40
Same here on MacOS 14.4

**Comment by thejulian** [comment] 2024-03-21 07:01
Same here on 14.4. It also prevents shutdown.

**Comment by NeoRey73** [comment] 2024-03-22 16:19
Same here, macOS 14.4 / Bitwarden 2024.3.0 (21897)

Quit / Cmd-Q closes the main window but BItwarden won't quit
Unable to Shut Down or Restart Mac

**I found that when _Always Show In The Dock_ is active it prevents Bitwarden from quitting, when I turn this off Bitwarden will quit.** I can Exit through the menu bar icon.

**Comment by madscienceli** [comment] 2024-03-26 15:12
> Same here, macOS 14.4 / Bitwarden 2024.3.0 (21897)
> 
> Quit / Cmd-Q closes the main window but BItwarden won't quit Unable to Shut Down or Restart Mac
> 
> **I found that when _Always Show In The Dock_ is active it prevents Bitwarden from quitting, when I turn this off Bitwarden will quit.** I can completely quit it by choosing **Exit** in the menu bar icon. macOS will also Restart or Shutdown with this feature disabled.

THAT WORKED! Thank you

**Comment by andrewkr** [comment] 2024-03-26 16:42
I don’t have Bitwarden showing in the dock. I have never done that and it is one of the first things I turn off when installing Bitwarden.

Quit and/or Cmd-Q do not close the main window for me. And neither does Bitwarden quit.

My only recourse is to open Activity Monitor, select Bitwarden, then choose Force Quit.

MacOS Sonoma 14.4 Bitwarden 2024.3.0 (21897) on both 2019 Intel iMac and 2022 M1 Pro MacBook Pro

**Comment by johnnywombo** [comment] 2024-03-26 16:57
Same issue. MacOS 14.4.1 Apple M1 Max. Had to turn off all the menubar options (Show, minimize, close, start, always) to get it to quit properly.

**Comment by raphant** [comment] 2024-04-03 23:04
@ubercool 
1. As @johnnywombo said, did you try disabling all of those features: Show, minimize, close, start, always? Did it work? 
2. If not, do you have **Allow browser integration** enabled?

**Comment by SergeantConfused** [comment] 2024-04-07 16:29
Hello everyone,

Thank you all for your input. In order to consolidate this matter into a single thread, I will proceed and close this report as a duplicate of this [one](https://github.com/bitwarden/clients/issues/8292); Whilst the wording is different, it's referring to the same reproduction steps in the video. 

If you wish to add any further information, please feel free to do so at any time in that [thread](https://github.com/bitwarden/clients/issues/8292) - our engineering team will be happy to review these.

I thank you all in advance for your understanding,

**Closed by SergeantConfused** 2024-04-07 16:29 UTC
Labels: bug, browser
