### ISSUE TITLE
Blank Firefox extension screen in private browsing session

### ISSUE THREAD

**Issue by KernelBypass** [bitwarden/clients#8755] opened 2024-04-15 21:02 UTC
### Steps To Reproduce

1. Start Firefox private window
2. Go to TOTP-enabled Instagram or Gmail
3. Autofill login/pass
4. At 2FA TOTP screen click the Bitwarden extension button (to access TOTP)

### Expected Result

The Bitwarden extension button opens the mini-window that contains account info with the button to copy TOTP

### Actual Result

The mini-window is completely blank:

<img width="437" alt="image" src="https://github.com/bitwarden/clients/assets/62620821/37326bd8-80af-426b-b34a-88602d4ae5d8">

Despite the Insta being detected and account for it being pulled internally within the extension (notice `1` in the extension button meaning it's successfully suggesting a saved credential):

<img width="1463" alt="image" src="https://github.com/bitwarden/clients/assets/62620821/fe458bbe-7bad-44d0-bbf9-3a75226922c3">

### Screenshots or Videos

<img width="451" alt="image" src="https://github.com/bitwarden/clients/assets/62620821/cdfcd8fd-ba59-4895-9cd5-a19c6c99c4ba">

<img width="1463" alt="image" src="https://github.com/bitwarden/clients/assets/62620821/4ed968be-c88d-4810-ac69-17aa8c9546d5">

### Additional Context

The extension is enabled to work in private mode in Firefox settings.
Browser integration re-approved several times with the desktop client, but this bug persists.

### Operating System

macOS

### Operating System Version

macOS 14.4.1 (23E224)

### Web Browser

Firefox

### Browser Version

Firefox 124.0.2 (64-bit)

### Build Version

2024.3.0 (21897)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-04-16 16:27
Duplicate of #8729

**Closed by djsmith85** 2024-04-16 16:27 UTC
Labels: bug, browser
