### ISSUE TITLE
Linux desktop app starts but will not load vault

### ISSUE THREAD

**Issue by glottophilos-jon** [bitwarden/clients#6945] opened 2023-11-22 09:56 UTC
### Steps To Reproduce

1. Start Linux Desktop App

### Expected Result

Vault content should load.

### Actual Result

App appears but with spinning loading wheel that will not go away.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/121892254/1b76aa43-cb3f-4f2f-b6ad-9d3b73c8c846)

### Additional Context

When starting with `bitwarden-desktop` via CLI, the following error messages appear (along with the same visual behavior previously described):

`(node:18205) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `electron --trace-deprecation ...` to show where the warning was created)
(node:18205) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'init')
    at BiometricsService.<anonymous> (/usr/lib/bitwarden/app.asar/main.js:47305:55)
    at Generator.next (<anonymous>)
    at /usr/lib/bitwarden/app.asar/main.js:47271:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/usr/lib/bitwarden/app.asar/main.js:47267:12)
    at BiometricsService.init (/usr/lib/bitwarden/app.asar/main.js:47304:16)
    at Main.<anonymous> (/usr/lib/bitwarden/app.asar/main.js:54050:46)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/bitwarden/app.asar/main.js:53942:58)
(node:18205) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
09:45:47.355 › State version: 8
09:45:47.358 › Migrator ba (to version 2) should migrate: false - up
09:45:47.359 › Migrator la (to version 3) should migrate: false - up
09:45:47.360 › Migrator ua (to version 4) should migrate: false - up
09:45:47.360 › Migrator ha (to version 5) should migrate: false - up
09:45:47.360 › Migrator ga (to version 6) should migrate: false - up
09:45:47.360 › Migrator va (to version 7) should migrate: false - up
09:45:47.361 › Migrator ma (to version 8) should migrate: false - up
09:45:47.451 › Error: No password found
09:45:47.453 › Error: No password found
09:45:47.473 › Error: No password found
(node:18205) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of null (reading 'null')
    at new Menubar (/usr/lib/bitwarden/app.asar/main.js:45647:131)
    at MenuMain.<anonymous> (/usr/lib/bitwarden/app.asar/main.js:45701:56)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/bitwarden/app.asar/main.js:45671:58)
(node:18205) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
09:45:47.652 › Unable to fetch ServerConfig: undefined
09:45:47.673 › Error: No password found
09:45:47.801 › Unable to fetch ServerConfig: undefined
(node:18205) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of null (reading 'null')
    at new Menubar (/usr/lib/bitwarden/app.asar/main.js:45647:131)
    at MenuMain.<anonymous> (/usr/lib/bitwarden/app.asar/main.js:45701:56)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/bitwarden/app.asar/main.js:45671:58)
(node:18205) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
09:45:50.398 › Error: No password found
(node:18205) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of null (reading 'null')
    at new Menubar (/usr/lib/bitwarden/app.asar/main.js:45647:131)
    at MenuMain.<anonymous> (/usr/lib/bitwarden/app.asar/main.js:45701:56)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/bitwarden/app.asar/main.js:45671:58)
(node:18205) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
09:50:46.806 › Error: No password found
09:50:46.936 › Unable to fetch ServerConfig: undefined`

### Operating System

Linux

### Operating System Version

Manjaro Linux Kernel 6.6.1-1-MANJARO(64-bit)

### Installation method

Other

### Build Version

Version 2023.10.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment] 2023-11-22 17:54
@glottophilos-jon,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Please note that this is a 'duplicate' of the below bugs (for macOS and Windows) on Linux:

https://github.com/bitwarden/clients/issues/6691
https://github.com/bitwarden/clients/issues/6878

As such the same workaround should also apply:

- close Bitwarden
- delete the contents of local storage (https://bitwarden.com/help/data-storage/)
- re-launch Bitwarden

I can confirm that the team is still looking into this, despite the existence of the workaround.

Thanks once again!

**Comment by glottophilos-jon** [comment] 2023-11-22 18:26
Wonderful, thank you for letting me know! I had seen those issues but wasn't sure if it was quite the same thing, so thank you for confirming, and providing the workaround!

**Comment by AJPoulter** [comment] 2023-12-11 12:44
Please note that this ticket is a duplicate of [#6910](https://github.com/bitwarden/clients/issues/6910). Also, the workaround mentioned above does NOT solve the problem on my machine (Archlinux EndeavourOS).

**Comment by Cris70** [comment] 2024-01-12 12:57
I am posting here my findings.
I do not believe my issue is linked to this one, but I've been asked by @atjbramley to post the details here.
Fundamentally, I have the same outcome as the OP (i.e. an eternally spinning loading wheel) but the premises are different: I experience this symptom only when I start Bitwarden Desktop while I'm offline.
If I start Bitwarden Desktop in normal conditions (i.e. I'm connected to the internet) it works correctly.
I'm on linux openSUSE Tumbleweed.
Bitwarden Desktop is Version 2023.12.1
You can find the original issue here: https://github.com/bitwarden/clients/issues/7539

**Comment by Cris70** [comment] 2024-02-27 20:24
FWIW, *my* issue is now resolved.
I am using Bitwarden Version 2024.2.0

**Comment by glottophilos-jon** [comment] 2024-02-28 08:58
Yes! I switched over to the Snap package which had v2024.2.0 and the issue
seems to be resolved! It appears that my distribution's package manager is
now also up-to-date so that one should be fixed as well.

Jonathan Walls
Linacre College MPhil student in Linguistics
University of Oxford
glottophilos.com

**Closed** 2024-02-28 11:22 UTC
Labels: bug, desktop

**Comment by trmartin4** [comment] 2024-02-29 15:50
Thank you!  I will close this issue.

**Comment by QXR9** [comment] 2024-05-23 14:28
At this moment, after the last update both snap and flathub client doesn't load accounts and passwords. Human verifying works very well, logging in works very well, mobile client works very well but snap and flathub linux client have this issue. I use KDE Neon.

**Comment by glottophilos-jon** [comment] 2024-05-26 11:56
@QXR9 could you list what version you're using? I'm on snap version 2024.5.0 Rev 110 and aside from some characters not loading in (which I think is a Wayland issue), it seems to be working just fine, I can access everything.

**Comment by donaldcallen** [comment] 2024-08-06 00:55
This issue with the Linux Bitwarden application is NOT resolved for me. I am running 2024.4.1. When I start it and log in, it just sits there an spins, never loading the vault data.
