### ISSUE TITLE
Webpage Freeze Bug Still Present--Safari Plugin Still on 2024.6.1 for App Version 2024.6.2

### ISSUE THREAD

**Issue by mjs271** [bitwarden/clients#9808] opened 2024-06-24 17:15 UTC
### Steps To Reproduce

This is a re-statement of the description from #9778

I've encountered this on a handful of sites and given up or moved on, but I was able to finally diagnose it consistently on `progressive.com`.

1. Enable Bitwarden Safari Extension (2024.6.1)
2. Enter `progressive.com` in Safari address bar
3. {Website loads}
4. Click (maybe) any link on the page
   
   * In my case, I noticed it when clicking the _**Log In**_ link in the upper-right portion of the page.
5. Website becomes unresponsive, and there is not response to clicking any link on the page.

I've also confirmed that the final step above does not occur when the Bitwarden Safari extension is disabled.

### Expected Result

Access the desired webpage upon clicking the link.

### Actual Result

* Web page becomes non-responsive. Also, hovering a link does not switch the cursor into "pointing hand" mode.
* Additionally, reloading the page does not work. The tab must be closed and then navigate to the site again to repeat the behavior.

### Additional Context

This is the same behavior described in #9778, though the root cause appears to be a bookkeeping issue rather than a main-branch code issue. The issue is still present, despite the ***fix*** described in #9063 because the Safari browser extension is lagged one update behind and does not contain the fix (at least for my system). It is not clear to me what I can do from my end to address this.

### Operating System

macOS

### Operating System Version

Sonoma 14.5

### Web Browser

Safari

### Browser Version

17.5

### Build Version

2024.6.2 (application), 2024.6.1 (extension)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment] 2024-06-25 16:39
Hello @mjs271,

Thank you for your report. This report seems to be a duplicate of [this GitHub report](https://github.com/bitwarden/clients/issues/9647). If there's anything you'd like to add, such as screenshots or video recordings of the screen, please feel free to add them to that existing GitHub report so that they'd be reviewed by the Bitwarden Engineering department; Please bear in mind that there already is a fix in the pipeline for this behaviour.

As a side note, the fact that the Safari extension is version 2024.6.1 whilst the macOS desktop client is 2024.6.2 is expected.

This report will now be closed as a duplicate.

Thank you again,

**Closed by SergeantConfused** 2024-06-25 16:39 UTC
Labels: bug, browser

**Comment by Ramalama2** [comment] 2024-06-26 18:54
Ill find it a bit stupid that all Issues related to this Bug were Closed, while everyone with Safari still has this bug.
There might be a fix, but as long the fix is not distributed to the users, its continuing to be frustrating for all safari users.
