### ISSUE TITLE
Unable to load bitwarden entirely 

### ISSUE THREAD

**Issue by mihailigoshin** [bitwarden/clients#7406] opened 2024-01-01 18:52 UTC
### Steps To Reproduce

4. Click on '...'

### Expected Result

Expecting to load the Desktop app and to be able to log in.

### Actual Result

When executing bitwarden via AppImage or installed via nix I just got a blank window executing.

### Screenshots or Videos

![2024-01-01_20-47](https://github.com/bitwarden/clients/assets/67579275/39c4dc2f-1a57-4655-90b9-7bb1a7389dc8)

### Operating System

Linux

### Operating System Version

Fedora 39

### Installation method

Other

### Build Version

2023.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by luc-bw** [comment] 2024-01-01 19:32
@mihailigoshin 

Thanks for the report! This is a duplicate of #6945 

[The following](https://github.com/bitwarden/clients/issues/6945#issuecomment-1823229841) should resolve the issue while we investigate further.

**Closed by luc-bw** 2024-01-01 19:32 UTC
Labels: bug, desktop
