### ISSUE TITLE
Unable to unlock on Firefox

### ISSUE THREAD

**Issue by plinss** [bitwarden/clients#8732] opened 2024-04-14 19:19 UTC
### Steps To Reproduce

1. Click Bitwarden icon while vault is locked

### Expected Result

Pop up window with field where I can enter my password

### Actual Result

Verify Identity window without any input for password.

### Screenshots or Videos

![Screenshot 2024-04-14 at 12 11 01 PM](https://github.com/bitwarden/clients/assets/2699689/a8daea46-493f-4c26-85c6-c1a800fd2692)

### Additional Context

I have to log out and log back in to the account in order to access the vault

### Operating System

macOS

### Operating System Version

13.6.3

### Web Browser

Firefox

### Browser Version

124.0.2

### Build Version

2024.3.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by shieldwed** [comment] 2024-04-14 21:09
Same goes for Arch Linux, same Firefox version, same Bitwarden extension version

**Comment by Xophmeister** [comment] 2024-04-15 09:11
Same for me in:
* Firefox 123.0.1, on NixOS 23.11, with Bitwarden 2024.3.1
* Firefox 124.0.2, on macOS 11.7.10, with Bitwarden 2024.3.1

**Comment by daniellbw** [comment] 2024-04-15 11:36
Hi there,

I am unable to reproduce this issue on my end, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by Xophmeister** [comment] 2024-04-15 14:50
FWIW, it doesn't appear to have anything to do with other addons. I tried disabling all those I have, except Bitwarden, and the problem persists.

**Comment by plinss** [comment] 2024-04-15 15:46
I'm unable to reproduce reliably now, but it was fairly consistent for several days. One thing I noticed was that the 'Unlock with PIN' setting turned itself off. The only thing that changed on my end since filing this was turning that back on and resetting the PIN. Manually turning that off doesn't reproduce the issue, so maybe it's related to whatever turned that off (possibly during a browser upgrade?). It's also set to lock on browser restart.

The other thing the preceded this issue was the last time Firefox upgraded itself it crashed on the restart which caused it to lose all my current tabs. I'm not sure if that's what caused the 'Unlock with PIN' to turn off, but that happened around the same time.

**Comment by shieldwed** [comment] 2024-04-15 18:49
I logged out of the extension and then logged in again. The PIN setting was disabled (probably expected behaviour). Then I set the PIN again and now the extension is working properly. I cannot reproduce it either for now.

**Comment by xVemu** [comment] 2024-04-16 06:32
Same behavior on Brave

**Comment by riaanduplessis** [comment] 2024-04-17 12:29
Same issue with Google Chrome 124.0.6367.60 (Official Build) (64-bit), extension version 2024.4.1 on Ubuntu 23.10.

Same as others, logging out and back in worked and the pin setting was also turned off.

**Comment by dblitt** [comment] 2024-04-18 15:00
Same behavior on Google Chrome, Fedora Linux 38, extension 2024.4.1. PIN was enabled.

Logging out and back in seems to fix it.

**Comment by KL4RKS** [comment] 2024-04-18 17:29
I've also experienced this since the 2024.3.1 update (or maybe it was when the extensions updated to 2024.4.1?)

I use several browsers, so I cannot remember for sure all the ones that experienced this, but I know it happened last night on Brave (Windows 11) and this morning on a different device with Brave (Windows 10). I think it also happened on Chrome. I cannot remember if it has happened on Firefox (though Firefox hasn't updated to 2024.4.1 yet and had two accounts logged in (instead of just one.)

**Comment by plasmetoz** [comment] 2024-04-22 02:07
Same behavior on Google Chrome 125.0.6422.4, Fedora Linux 39, extension 2024.4.1. PIN was enabled.

**Comment by Gamax42** [comment] 2024-04-23 05:39
I have the same issue on Google Chrome 124.0.6367.61, Windows 10 Pro 22H2, extension 2024.4.1. PIN enabled after one minute.
Log out then Log in fixes the issue.

**Comment by KL4RKS** [comment] 2024-05-07 22:01
Just got the missing password field again after updating from 2024.4.1 to 2024.4.2 on Windows 10, Google Chrome 124.0.6367.119. It didn't happen with the same update in Brave. In Brave I had unlocked Bitwarden before updating extension and after updating unlocked again right away. In Chrome I hadn't unlocked Bitwarden before, nor for several hours after.

**Comment by jlf0dev** [comment] 2024-06-07 19:51
Hi everyone, can anyone confirm for me that this is still reproducible in 2024.5.1 or 2024.5.2? Thanks!

**Comment by jlf0dev** [comment] 2024-06-19 18:44
Closing for now, please let us know if you see the same behavior again. Thank you for the report!

**Closed by jlf0dev** 2024-06-19 18:44 UTC
Labels: bug, browser
