### ISSUE TITLE
Bitwarden won't import custom fields correctly when importing from 1Password

### ISSUE THREAD

**Issue by DevShubam** [bitwarden/clients#3365] opened 2022-08-23 19:38 UTC
### Steps To Reproduce

1. Export data from 1Password (.1pux file)
2. Import the data through Bitwarden's web vault
3. Look for logins that have custom fields

### Expected Result

The custom field text should be the exact same in Bitwarden as it is in 1Password.

### Actual Result

Bitwarden displays the ID instead of the title in some cases. 

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/65375709/186250094-de23e711-0558-4693-a1d7-08f4a69823e1.png)
![image](https://user-images.githubusercontent.com/65375709/186250482-5714c97e-8b57-4f55-8be7-c714639cda7c.png)

### Operating System

Windows

### Operating System Version

11

### Web Browser

Vivaldi

### Browser Version

5.4.2753.37

### Build Version

2022.8.1

**Comment by djsmith85** [comment] 2022-08-23 20:27
@DevShubam Thank you for your report. It has been a while since I wrote that importer, but I remember there being inconsistencies with how 1password exported names/titles vs id's. 

At the time I added [this method](https://github.com/bitwarden/clients/blob/95a0cfb28dd9e4032f77d681755a71451f4d19aa/libs/common/src/importers/onepasswordImporters/onepassword1PuxImporter.ts#L220) which works for most cases.

We've added this to our internal ticket tracking system and will get it prioritized. In the meantime I'm adding the good-first-issue label, in case anyone wants to take a stab at it.

Plenty of example exports can be found within the [test suite](https://github.com/bitwarden/clients/blob/master/libs/common/spec/importers/onepassword1PuxImporter.spec.ts) for 1pux.

Kind regards,
Daniel

**Comment by rituraj00** [comment] 2023-03-07 15:13
@djsmith85 Is this issue still there, if yes, I would like to take a stab at it, can you assign it to me ?

**Comment by djsmith85** [comment] 2023-03-07 15:33
@rituraj00: As far as I know, this is still up for grabs. 

Thank you for your interest in contributing. To get started, please have a look at https://contributing.bitwarden.com/. Once you have a PR ready, please link to this issue. Looking forward to see your proposed changes.

**Comment by DevShubam** [comment] 2023-03-07 15:41
@rituraj00 I made the switch over to BW about a week ago, and this issue was still there so I'm guessing it's still a problem

**Comment by rituraj00** [comment] 2023-03-07 15:48
@djsmith85 , @DevShubam Thanks for the info, I have started to work on it.

**Comment by rituraj00** [comment] 2023-03-08 05:27
@DevShubam I am unable to replicate the issue exactly, I tried to create a login/password same as your screenshot, but it seems to be working fine. https://prnt.sc/qDbS0DEt3pqH

Can you please tell me the detailed process you followed which leads you the issue?

Thanks

**Comment by rituraj00** [comment] 2023-03-08 18:58
@djsmith85 I was able to reproduce the issue and added an fix.
Here is the PR of it, please review and let me know if the solution is approved. 
https://github.com/bitwarden/clients/pull/4959

**Comment by rituraj00** [comment] 2023-03-09 18:07
@djsmith85 I have updated the PR with new updates.

**Comment by rituraj00** [comment] 2023-06-02 18:58
@prestr The PR with solution already opened a while ago, it is not merged yet, I did not get a chance to check again.

**Comment by billzhuang** [comment] 2023-08-24 03:04
> Any update on if the PR can be approved and merged? This is holding me back from switching from 1Password to BW.

+1, i'm working on the migrating, and meet the same issue. is there any chance to merge the PR?

**Comment by felipecrs** [comment] 2023-09-11 17:32
Same issue here. And it's actually simple, apparently. It looks like Bitwarden is preferring the `id` field rather than than the `title` field from the export.data:

```json
                "sections": [
                  {
                    "title": "",
                    "name": "add more",
                    "fields": [
                      {
                        "title": "agência",
                        "id": "oy3tgolrgiux7itjgc7et3675q",
                        "value": {
                          "string": "0664"
                        },
                        "guarded": false,
                        "multiline": false,
                        "dontGenerate": false,
                        "inputTraits": {
                          "keyboard": "default",
                          "correction": "no",
                          "capitalization": "sentences"
                        }
                      },
```

**Comment by tdracz** [comment] 2023-10-05 17:01
Same here - the bug is preventing me from switching from 1Password to BW

**Comment by felipecrs** [comment] 2023-10-05 17:10
Note that I built a fix, which is passing tests, but is missing review:

- https://github.com/bitwarden/clients/pull/6261

**Comment by tdracz** [comment] 2023-10-05 17:14
@djsmith85 is there a chance some can review the fix please ^^^ ? I'm looking forward to switching to BW

**Comment by ttalty** [comment] 2023-12-22 22:46
This has been resolved with the merging of https://github.com/bitwarden/clients/pull/7190

**Closed by ttalty** 2023-12-22 22:46 UTC
Labels: bug, good first issue, browser
