### ISSUE TITLE
Search does not work in Chrome Browser Plugin Version: 2024.12.3  SDK: 'main (edee180)'

### ISSUE THREAD

**Issue by emmrichd** [bitwarden/clients#12633] opened 2024-12-30 18:38 UTC
### Steps To Reproduce

1. Go to search field in browser
2. enter "Joplin" (example)
3. Nothing is found (while on IOS, entries can be found)
Note:other terms can be found?!?

### Expected Result

My "joplin" entries should be shown, as on IOS

### Actual Result

nothing is found

### Operating System

Windows

### Operating System Version

11

### Web Browser

Chrome

### Browser Version

Version 131.0.6778.205 (Offizieller Build) (64-Bit)

### Build Version

Version 131.0.6778.205 (Offizieller Build) (64-Bit)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by emmrichd** [comment] 2024-12-30 18:42
<img width="281" alt="Screenshot 2024-12-30 193931" src="https://github.com/user-attachments/assets/5864f3c1-b727-47a8-8934-af61d410bb90" />
![bitwarden](https://github.com/user-attachments/assets/9be17cc0-40ac-4abd-a86e-bbb692830cf9)

**Comment by emmrichd** [comment] 2024-12-30 18:43
![bitwarden](https://github.com/user-attachments/assets/026cdea1-e8ad-4b1c-b231-93695b148a6e)

**Comment by cbbit** [comment] 2024-12-31 14:01
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/12440

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by cbbit** 2024-12-31 14:01 UTC
Labels: bug, browser
