### ISSUE TITLE
Win11- Desktop App window size problem with Display Scaling

### ISSUE THREAD

**Issue by HaveTheBestDay** [bitwarden/clients#3824] opened 2022-10-18 16:06 UTC
### Steps To Reproduce

1. Have 2 or more monitors.
3. Enable Display Scaling on a monitor and set it to a factor larger than 1 (e.g. 200%)
4. Display Scaling between your "primary" monitor and the scaled one need to be different. (i.e. one is 100%, the other 200%)
5. See that "Remember window locations based on monitor connection" is enabled, too
6. Start Bitwarden, move its App window to said monitor, and set its width and height to your liking
7. Close Bitwarden
8. Start Bitwarden again

### Expected Result

Bitwarden opens again with the same window dimensions and in the same location as before it was closed.

### Actual Result

Bitwardens window width and height scale with the DIsplay Scaling factor of the monitor (e.g. 2x) and is now larger than before. That happens every time the app starts on that display.

### Screenshots or Videos

https://user-images.githubusercontent.com/33953353/196482933-4541e0e8-db4d-4218-a173-a3fbce155502.mp4

### Additional Context

This happened even right after doing a completely fresh Win11 install. 

The UI scaling of the App is working perfectly fine, disregarding the window size.

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.10.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by tangowithfoxtrot** [comment] 2022-12-21 22:37
Thanks, @HaveTheBestDay!

This appears to be a duplicate of https://github.com/bitwarden/clients/issues/2623, which will be resolved by https://github.com/bitwarden/clients/pull/4050 in a subsequent release. 

Closing for now, but if you feel like any aspect of the issue wasn't resolved when the fix is included in our `2023.1` release, please feel free to update us in https://github.com/bitwarden/clients/issues/2623.

**Closed** 2022-12-21 22:37 UTC
Labels: bug, duplicate, desktop
