### ISSUE TITLE
"Search vault" field is modified as I type, resulting in missing characters

### ISSUE THREAD

**Issue by drguildo** [bitwarden/clients#2708] opened 2022-05-20 09:18 UTC
### Steps To Reproduce

1. Click on Bitwarden menu icon to open menu
2. Click on 'Search vault' field
3. Start typing something 

### Expected Result

The text I entered to appear in the search field exactly as I typed it.

### Actual Result

Quite often characters I typed will be missing from the search field, because I was typing them while the field was being re-populated.

### Screenshots or Videos

![bitwarden](https://user-images.githubusercontent.com/9282/169495636-1c52ab0d-ab57-481f-834f-d2be2904dd12.gif)

### Additional Context

This only seems to happen the first time I search after opening the Bitwarden menu and search. However, if I close and re-open the menu, it'll happen again the first time I search while it's open.

### Operating System

Windows

### Operating System Version

20H2 19042.1706

### Web Browser

Firefox

### Browser Version

91.9.0esr

### Build Version

1.58.0

**Comment by djsmith85** [comment] 2022-05-20 09:25
@drguildo Thank you for the report. This seems to be a duplicate of https://github.com/bitwarden/clients/issues/2371.

Closing this now.

**Closed by djsmith85** 2022-05-20 09:25 UTC
Labels: bug, browser
