### ISSUE TITLE
Master password re-prompt no longer works in Firefox extension

### ISSUE THREAD

**Issue by davidstmartin** [bitwarden/clients#7579] opened 2024-01-16 20:25 UTC
### Steps To Reproduce

1. Go to a vault item that requires password re-prompt
2. Click on either view password, or copy password
3. The password re-prompt dialog doesn't show, and the password is displayed/copied

### Expected Result

A password re-prompt dialog should popup before copying the saved password.

### Actual Result

Password is simply copied without a prompt

### Additional Context

I've got bitwarden installed on-prem.  I recently upgraded the bitwarden server to 2024.1.0, while my firefox extension was still at v2023.12.1.  This was working when sometime before the upgrade of the bitwarden server to 2024, though I can't confirm if the upgrade caused the issue.  I've since updated the firefox extension to 2024.1.0, and the issue is not resolved.

If I login to the Bitwarden web interface, or the desktop client, password re-prompt still functions as expected.

### Operating System

Windows

### Operating System Version

11

### Web Browser

Firefox

### Browser Version

121.0.1

### Build Version

2024.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-01-16 20:40
Duplicate of #7405

**Comment by djsmith85** [comment] 2024-01-16 20:40
Hi @davidstmartin 

Thank you for your report, it seems like it is a duplicate of this one #7405

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2024-01-16 20:40 UTC
Labels: bug, browser
