### ISSUE TITLE
Firefox says "Awaiting confirmation from desktop"

### ISSUE THREAD

**Issue by chptrk** [bitwarden/clients#6155] opened 2023-08-31 02:07 UTC
### Steps To Reproduce

1. Launch Firefox
2. Click on Bitwarden extension
3. User biometric to unlock
4. "Awaiting confirmation from desktop" shows until I manually type my master password.

### Expected Result

I used to be able to unlock bitwarden with just my biometrics.

### Actual Result

I have to use both biometrics and master password now.

### Operating System

macOS

### Operating System Version

13.5.1

### Web Browser

Firefox

### Browser Version

117.0

### Build Version

2023.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by chptrk** [comment] 2023-08-31 02:08
<img width="384" alt="Screenshot 2023-08-30 at 10 07 57 PM" src="https://github.com/bitwarden/clients/assets/143673353/2709e85e-bd31-4caf-984a-3b2a79d027a6">

**Comment by spreeni151** [comment] 2023-08-31 11:37
Same here after the last Bitwarden desktop app update.

Windows Version 2023.8.2
Shell 24.1.1
Renderer 112.0.5615.50
Node 18.14.0
Architecture x64

Firefox (64bit) 117.0 Windows
Bitwarden Firefox plugin 2023.7.1

Unlocking by fingerprint sensor (windows hello) does not work - dialog is opening, fingerprint is recognized but varden in firefox is still locked. Unlocking in Desktop App AND in Chrome via plugin is working. 

So it seems for me to be a communication failure between Firefox plugin - Firefox - Desktop App

Unlocking via masterpassword is also working in firefox, btw.

regards, Frank

**Comment by spreeni151** [comment] 2023-08-31 13:47
I figured out that it is working with version 2023.8.2 of the firefox plugin. Unfortunately I cannot install it because it is not signed by Mozilla yet. I checked it with the ESR version of Firefox, in which you are allowed to disable the check-signed feature.

**Comment by msiqx9** [comment] 2023-08-31 15:16
I have extension 2023.8.2 in the Chrome browser in Windows 11 and its not working, the same situation as in Firefox where the extension is 2023.7.1

**Comment by blxckbxrd** [comment] 2023-08-31 23:08
Oh, looks like it's the same problem we have here. There was a good suggestion to include the error log.

https://github.com/bitwarden/clients/issues/6156#issuecomment-1701697183

**Comment by chptrk** [comment] 2023-08-31 23:35
Here's my log:

This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”. background.html
Could not find any MenuItem with id: root console-log.service.ts:47:16
Could not find any MenuItem with id: autofill console-log.service.ts:47:16
Could not find any MenuItem with id: root console-log.service.ts:47:16
Could not find any MenuItem with id: autofill console-log.service.ts:47:16
Could not find any MenuItem with id: root console-log.service.ts:47:16
Could not find any MenuItem with id: autofill console-log.service.ts:47:16
Could not find any MenuItem with id: root console-log.service.ts:47:16
Could not find any MenuItem with id: autofill console-log.service.ts:47:16
Could not find any MenuItem with id: root console-log.service.ts:47:16
Could not find any MenuItem with id: autofill console-log.service.ts:47:16
Could not find any MenuItem with id: root console-log.service.ts:47:16
Could not find any MenuItem with id: autofill console-log.service.ts:47:16
Could not find any MenuItem with id: root console-log.service.ts:47:16
Could not find any MenuItem with id: autofill console-log.service.ts:47:16
Could not find any MenuItem with id: root console-log.service.ts:47:16
Could not find any MenuItem with id: autofill console-log.service.ts:47:16
Uncaught (in promise) TypeError: h.fromB64ToArray(...) is null
    onMessage nativeMessaging.background.ts:324
    o background.js:1
    promise callback*l background.js:1
    o background.js:1
    promise callback*l background.js:1
    o background.js:1
    promise callback*l background.js:1
    o background.js:1
    promise callback*l background.js:1
    Pu background.js:1
    Pu background.js:1
    onMessage background.js:1
    connect nativeMessaging.background.ts:179
    Pu background.js:1
    Pu background.js:1
    connect nativeMessaging.background.ts:112
nativeMessaging.background.ts:324:41

**Comment by sammbw** [comment] 2023-09-01 05:20
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/6156

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by sammbw** 2023-09-01 05:20 UTC
Labels: bug, browser
