### ISSUE TITLE
Client 2023.9.2 broken on Linux (Mint Cinnamon)

### ISSUE THREAD

**Issue by abysso2** [bitwarden/clients#6577] opened 2023-10-13 17:28 UTC
### Steps To Reproduce

Running Linux Mint Cinnamon 21.2

1. Download and start Bitwarden-2023.9.2-x86_64.AppImage (also  Bitwarden-2023.9.2-amd64.deb)
2. Enter anything (Mailaddress, PIN - doesn matter)
3. Client is a kind of "blank" see attached screen shot

### Expected Result

Normal behavior (Bitwarden 2023.9.1 works like a charm)

### Actual Result

After typing any character (numbers or letters), the windows of the client truns "grey and blank".

### Screenshots or Videos

![grafik](https://github.com/bitwarden/clients/assets/8254322/f4978530-7d20-49dd-b5ad-3527cccfa853)

### Additional Context

./Bitwarden-2023.9.2-x86_64.AppImage 
(node:13764) DeprecationWarning: file property is deprecated and will be removed in v5.
(Use `bitwarden --trace-deprecation ...` to show where the warning was created)
(node:13764) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'init')
    at BiometricsService.<anonymous> (/tmp/.mount_BitwarkEAjOy/resources/app.asar/main.js:47194:55)
    at Generator.next (<anonymous>)
    at /tmp/.mount_BitwarkEAjOy/resources/app.asar/main.js:47160:71
    at new Promise (<anonymous>)
    at biometrics_service_awaiter (/tmp/.mount_BitwarkEAjOy/resources/app.asar/main.js:47156:12)
    at BiometricsService.init (/tmp/.mount_BitwarkEAjOy/resources/app.asar/main.js:47193:16)
    at Main.<anonymous> (/tmp/.mount_BitwarkEAjOy/resources/app.asar/main.js:53805:46)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_BitwarkEAjOy/resources/app.asar/main.js:53702:58)
(node:13764) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:13764) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of null (reading 'null')
    at new Menubar (/tmp/.mount_BitwarkEAjOy/resources/app.asar/main.js:45540:131)
    at MenuMain.<anonymous> (/tmp/.mount_BitwarkEAjOy/resources/app.asar/main.js:45594:56)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_BitwarkEAjOy/resources/app.asar/main.js:45564:58)
(node:13764) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
19:19:38.999 › Checking for update
19:19:39.772 › Update for version 2023.9.2 is not available (latest version: 2023.9.2, downgrade is disallowed).

### Operating System

Linux

### Operating System Version

Mint 21.2 Cinnamon

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.9.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2023-10-13 17:35
Duplicate of https://github.com/bitwarden/clients/issues/6560

**Comment by djsmith85** [comment] 2023-10-13 17:36
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/6560.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2023-10-13 17:36 UTC
Labels: bug, desktop
