### ISSUE TITLE
Lag when opening extension in Chrome

### ISSUE THREAD

**Issue by mdavis6890** [bitwarden/clients#3592] opened 2022-09-22 15:00 UTC
### Steps To Reproduce

Chrome Version 105.0.5195.127
Using Chrome Extension.

1. While vault is locked, click on the extension
2. The password prompt appears
3. Immediately try typing
4. Note that focus does not go to the password field for ~1sec, so if you start typing immediately the first few characters are lost, or captured by whatever HAD the focus.

### Expected Result

When the password prompt appears, it should instantly have focus.

### Actual Result

There is some lag (~1sec) between when the password prompt appears and when it receives focus, losing a few characters if you start typing to soon.

### Operating System

Windows

### Operating System Version

10

### Web Browser

Chrome

### Browser Version

105.0.5195.127

### Build Version

2022.9.1

**Comment by djsmith85** [comment] 2022-09-22 16:11
Hi @mdavis6890 thank you for your report.

This seems to be a duplicate of #3562.

Closing this now.

**Closed by djsmith85** 2022-09-22 16:11 UTC
Labels: bug, browser
