### ISSUE TITLE
Resizing of extension popup

### ISSUE THREAD

**Issue by TriggerDingus** [bitwarden/clients#3221] opened 2022-08-02 16:00 UTC
### Steps To Reproduce

Within either LibreWolf (Firefox) or Brave (Chromium), click the extension to expose the popup. Attempt to resize the popup by grabbing the window corners or edges so you can view more within it.

### Expected Result

I've been using Bitwarden a few years now and up until a month or two ago, I'm certain I used to be able to resize the extension window. The scrollbars aren't helpful because my extension window is so small to begin with.  (see screen cap)

### Actual Result

Recently, I open the Bitwarden extension and the window is tiny and much like trying to view a landscape through a soda straw. When I attempt to resize it, there are no resizable edges or corners from which to do so. I attempted to resize in both Librewolf and Brave, with no luck.

### Screenshots or Videos

![SKDesktop](https://user-images.githubusercontent.com/75340371/182418937-a89cf8e7-1c09-425f-bf21-69fbecae1b96.png)

### Operating System

Linux

### Operating System Version

Pop!_OS 22.04 LTS

### Web Browser

Firefox, Brave

### Browser Version

Up-to-the-minute versions of both

### Build Version

Version: 2022.6.1

**Comment by bnagawiecki** [comment] 2022-09-01 19:26
Hey @TriggerDingus,

Thanks for taking the time to submit this issue!

Resizing the extension without popping it out into a window or sidebaring it is not a feature.

That said, I see from your screenshot that the window does appear to be half height. I did some digging, and it looks like this can be caused by the extension not being able to detect your display/browser resolution, which can be blocked by some browsers. #1582 has a workaround for Firefox which might help for your LibreFox case.

I'm going to close this out since the inability to resize is not a bug. If you'd like to submit a feature request for it, the [Bitwarden Community Forums](https://community.bitwarden.com/) has a [Feature Requests section](https://community.bitwarden.com/c/feature-requests) for submitting, voting for, and discussing requests.

**Closed by bnagawiecki** 2022-09-01 19:26 UTC
Labels: bug, browser

**Comment by djsmith85** [comment] 2022-09-06 13:27
Linking https://github.com/bitwarden/clients/issues/1451

**Comment by tristandostaler** [comment] 2022-11-11 16:56
> Hey @TriggerDingus,
> 
> Thanks for taking the time to submit this issue!
> 
> Resizing the extension without popping it out into a window or sidebaring it is not a feature.
> 
> That said, I see from your screenshot that the window does appear to be half height. I did some digging, and it looks like this can be caused by the extension not being able to detect your display/browser resolution, which can be blocked by some browsers. #1582 has a workaround for Firefox which might help for your LibreWolf case.
> 
> I'm going to close this out since the inability to resize is not a bug. If you'd like to submit a feature request for it, the [Bitwarden Community Forums](https://community.bitwarden.com/) has a [Feature Requests section](https://community.bitwarden.com/c/feature-requests) for submitting, voting for, and discussing requests.

Thanks! That did it for me. In the Brave browser, in "brave://flags", I had to disable the "Block screen fingerprinting".
