### ISSUE TITLE
Update available dialog opens while typing password, keystrokes trigger buttons

### ISSUE THREAD

**Issue by teunvg** [bitwarden/clients#3196] opened 2022-07-28 13:21 UTC
### Steps To Reproduce

1. Open the Bitwarden desktop client while there is an update available.
2. Start typing your password.

### Expected Result

I can log in to my Bitwarden account. Alternatively, I may want to _choose_ to update Bitwarden, but through a less intrusive pop-up dialog.

### Actual Result

An update dialog appears mid-password, and keystrokes in the password trigger one of the buttons, potentially closing the program and starting the update, or simply resulting in an incorrect password because of missed keystrokes.

### Operating System

Windows

### Operating System Version

Windows 10

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.6.2 (after the last update...)

**Comment by djsmith85** [comment] 2022-07-28 14:31
@teunvg Thank you for your report. Closing this as duplicate of https://github.com/bitwarden/clients/issues/2608

**Closed by djsmith85** 2022-07-28 14:31 UTC
Labels: bug, desktop
