### ISSUE TITLE
Firefox extention loses unlock by pin setting and requires master password when reload

### ISSUE THREAD

**Issue by Soit78** [bitwarden/clients#9586] opened 2024-06-11 17:07 UTC
### Steps To Reproduce

1. Go to Settings
2. Click on unlock with pin and enter Pin uncheck lock with Master password on restart of browser
3. Click on 'OK.'

### Expected Result

When restart of Firefox occurs unlock extension with pin.

### Actual Result

Intermittently on Firefox restart the extension  will lose the unlock with pin setting and require master password

### Operating System

Windows

### Operating System Version

Version 23h2 

### Web Browser

Firefox

### Browser Version

126.01

### Build Version

Version 2024.4.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by thebodzio** [comment] 2024-06-12 00:34
I can confirm this for FF 127.0 and extension 2024.4.2, except for "intermittently"—it occurs reliably, every time I restart my browser.

**Comment by jtodddd** [comment] 2024-06-12 13:23
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/8873. 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by jtodddd** 2024-06-12 13:23 UTC
Labels: bug, browser
