### ISSUE TITLE
Bug in fingerprint release

### ISSUE THREAD

**Issue by Manuel3190** [bitwarden/clients#7960] opened 2024-02-15 10:12 UTC
### Steps To Reproduce

After manually locking the Windows app and with activated biometric authentication via fingerprint, the app immediately requests fingerprint unlocking again via a pop-up after locking.

### Expected Result

The app should simply remain locked without an immediate fingerprint unlock request

### Actual Result

The app shows the unlocking by fingerprint although the app should not be unlocked and should simply remain locked until it is manually unlocked again with Windows Hello

### Screenshots or Videos

![Screenshot 2024-02-15 110926](https://github.com/bitwarden/clients/assets/93059120/f354fe9f-11d5-402f-b9ac-c81bb642056e)

### Operating System

Windows

### Operating System Version

11 23H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.2.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment] 2024-02-15 10:22
Hi there!
Thank you for your report, it seems like it is a duplicate of this one  #7908   
If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.
This issue will now be closed.
Thanks!

**Closed by daniellbw** 2024-02-15 10:22 UTC
Labels: bug, desktop

**Comment by Manuel3190** [comment] 2024-02-15 10:43
Yes nearby. But mine is a windows Bug Not on Mac. GreetingsAm 15.02.2024 um 11:23 schrieb daniellbw ***@***.***>:﻿
Closed #7960 as not planned.
