### ISSUE TITLE
Browser Plugin silently fails on desktop client version mismatch.

### ISSUE THREAD

**Issue by mkeveney** [bitwarden/clients#11306] opened 2024-09-29 00:06 UTC
### Steps To Reproduce

After activating "Unlock with Biometrics" in the plugin setup screen, click the plugin icon; click "Unlock with Biometrics" ...and nothing.

### Expected Result

Expected the system fingerprint dialog to pop up as before.  

### Actual Result

Nothing; no error message; no warning

### Additional Context

This was working fine until just recently.  I've reinstalled the plugin (found via Firefox's search feature) to no effect.  
Note: version in the plugin 'about' screen says 2024/9/1.. though I found somewhere that there is a later version.
If so, how do I install it?

The desktop Bitwarden app is running fine, with the biometric feature active.

### Operating System

macOS

### Operating System Version

Sonoma 14.6.1

### Web Browser

Firefox

### Browser Version

131.0b9 64-bit,  Developer Edition

### Build Version

2024/9/1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by gdurys** [comment] 2024-09-29 14:07
I had the same problem until I updated the desktop client to 2024.9.0.

**Comment by mkeveney** [comment] 2024-09-29 17:56
Thank you @gdurys that cured it.
Change bug title to: Browser Plugin silently fails on desktop client version mismatch.

**Comment by sammbw** [comment] 2024-09-30 03:31
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/clients/issues/11168

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by sammbw** 2024-09-30 03:31 UTC
Labels: bug, browser
