### ISSUE TITLE
bw snap does not allow storing local files

### ISSUE THREAD

**Issue by tingdahl** [bitwarden/clients#11280] opened 2024-09-27 08:31 UTC
### Steps To Reproduce

1. install the bw snap on a linux system (preferably Ubuntu).

`snap install bw`

2. Try to run an export
`bw export --organizationid  <org_id> --format json --output vault.json`

Error message will show:
Cannot save file to ./vault.json

### Expected Result

The backup can be stored locally

### Actual Result

The snap cannot store the local data

### Additional Context

The reason is likely that the snap is confined, and may not access the local file system.

`snap connections bw`

does not contain the 'home' interface. By adding that to the snap, it may access files under the user's home directory.

Solution: Add 'home' to the 'plugs' section of the snapcraft-yaml:
`
    plugs:

      - home
 
      - network

      - network-bind

      - desktop
`

### Operating System

Linux

### Operating System Version

Ubunut 24.04

### Shell

Bash

### Build Version

2024.9.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by atjbramley** [comment] 2024-09-27 09:39
Hi @tingdahl !

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/3923. 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by atjbramley** 2024-09-27 09:39 UTC
Labels: bug, cli
