### ISSUE TITLE
Appimage not autostarting on Ubuntu Linux

### ISSUE THREAD

**Issue by danielrosehill** [bitwarden/clients#8401] opened 2024-03-20 13:29 UTC
### Steps To Reproduce

1. Download the appimage from the Bitwarden site.
2. Launch the application / GUI.
3. Enable "start automatically on login"

![autostart](https://github.com/bitwarden/clients/assets/40233203/6ff96b20-c66c-4a05-98de-840a9058f018)

### Expected Result

Bitwarden should automatically start after login (or start minimised to the tray icon depending on settings).

### Actual Result

Bitwarden does not start. 

### Additional Context

I'm using LXDE as my DE which is a little old and buggy so perhaps this issue is DE-related.

### Operating System

Linux

### Operating System Version

22.04 LTS

### Installation method

Direct Download (from bitwarden.com), Other

### Build Version

Version 2024.3.0 Shell 28.2.4 Renderer 120.0.6099.291 Node 18.18.2 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment] 2024-03-20 15:42
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/2938. 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by Neonwarden** 2024-03-20 15:42 UTC
Labels: bug, desktop

**Comment by danielrosehill** [comment] 2024-03-20 15:51
@Neonwarden - K. Added the notes there. Perhaps other Linux users are still experiencing this.
