### ISSUE TITLE
Get OTP timestamp codes from Desktop client

### ISSUE THREAD

**Issue by icastillejogomez** [bitwarden/clients#2980] opened 2022-06-25 22:32 UTC
### Steps To Reproduce

1. Ensure you have a enable suscription on bitwarden.com
2. Create a valid login item from one of your websites
3. Registre the login credentials and the TOPT secret
4. Check that code generation (on mobile client and web client) works good
5. Try to get the OTP code from Desktop client

### Expected Result

Get the generated OTP codes from Desktop client

### Actual Result

The OTP code is not present in the desktop app

### Screenshots or Videos

<img width="481" alt="Screenshot 2022-06-26 at 00 29 08" src="https://user-images.githubusercontent.com/16567802/175792293-2da6988d-f1f1-48cf-be91-7964b43c7a80.png">
<img width="954" alt="Screenshot 2022-06-26 at 00 30 56" src="https://user-images.githubusercontent.com/16567802/175792294-31a602d4-9442-476d-ba53-88d8bf4b82dd.png">
<img width="481" alt="Screenshot 2022-06-26 at 00 28 33" src="https://user-images.githubusercontent.com/16567802/175792295-c3ead031-83be-4df0-9c5d-2ef835fbe98c.png">

### Operating System

macOS

### Operating System Version

12.4 (21F79)

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 1.33.0 Shell 16.1.0 Renderer 96.0.4664.174 Node 16.9.1 Architecture x64

**Comment by djsmith85** [comment] 2022-07-21 10:27
Hi @icastillejogomez sorry to hear you are experiencing issues with TOTP generation. The premium status is usually synced when you log-in to a new device. I assume you logged in to the web and browser extension after you purchased premium. Please try logging out of the desktop app and log back in. This should re-sync the premium status and the TOTP generation should be working as expected.

Closing this now, but please feel free to re-open if this did not work. Please provide any additional detail to assist with reproduction and root cause analysis.

**Closed by djsmith85** 2022-07-21 10:27 UTC
Labels: bug, desktop
