### ISSUE TITLE
All Firefox variants - unable to unlock Bitwarden via PIN or set PIN once disabled

### ISSUE THREAD

**Issue by rekabis** [bitwarden/clients#6393] opened 2023-09-25 04:33 UTC
### Steps To Reproduce

1. Attempt to log into Bitwarden under Firefox using PIN

or 

1. Attempt to set a PIN in BitWarden under Firefox

### Expected Result

With a PIN set, either hitting the Enter key, or the Unlock button, opens bitwarden up.

When setting a PIN, hitting the Enter key or the OK button sets the PIN.

### Actual Result

Neither logging in with a PIN or setting a PIN produces any sort of a response from the add-in.

Of particular note: when attempting to set a PIN, when the OK button is clicked on, it darkens slightly and does not lighten again when the mouse moves off of it.

### Screenshots or Videos

Unable to procure a screenshot. My Greenshot is not cooperating.

### Additional Context

Occurs under Firefox and LibreWolf for Windows, Mac and Linux.

I mean, I am able to _log in_ using my full password+2FA, but at 53 characters, it’s a bit annoying to always have to use the full traditional login.

This issue DOES NOT happen under any Chrome-based browser, or under Safari (Mac). I am able to log in with a PIN, and set a PIN under Safari and Chrome-based browsers for Mac, Windows, and Linux.

### Operating System

Windows, macOS, Linux

### Operating System Version

Windows 10 Pro 22H2 19045.3448, MacOS Monterey 12.6.9, OpenSUSE Tumbleweed

### Web Browser

Firefox

### Browser Version

Firefox 117.0.1, LibreWolf 117.0.1-1, Waterfox Classic 2022.11

### Build Version

2023.8.3 (client)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment] 2023-09-25 05:01
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/clients/issues/6286

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by sammbw** 2023-09-25 05:01 UTC
Labels: bug, browser
