### ISSUE TITLE
Plugin interferes with rendering of plain xml files

### ISSUE THREAD

**Issue by rikbrandt** [bitwarden/clients#8430] opened 2024-03-21 18:04 UTC
### Steps To Reproduce

Navigate to plain xml file, without associated stylesheet

### Expected Result

Browser renders a pretty-printed, collapsible xml tree:
![image](https://github.com/bitwarden/clients/assets/164392503/ed7d379a-9b62-46c7-9f6b-50ae154eb7ea)

### Actual Result

Browser displays node contents as plain text, omitting tags:
![image](https://github.com/bitwarden/clients/assets/164392503/0ae558f4-a619-43ba-ac52-500526e84820)

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/164392503/ed7d379a-9b62-46c7-9f6b-50ae154eb7ea)
=> 
![image](https://github.com/bitwarden/clients/assets/164392503/0ae558f4-a619-43ba-ac52-500526e84820)

### Additional Context

Problem starts in version 2024.2.0.
Version 2024.1.1 unaffected.
Version 2024.2.1 affected.

Problem disappears when you manually log out of the vault (User icon > Log out).
It reappears when you click on the extension icon, even without logging in.

### Operating System

Windows

### Operating System Version

Windows 10 Pro

### Web Browser

Firefox

### Browser Version

123.0.1

### Build Version

2024.2.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment] 2024-03-21 18:46
Duplicate of https://github.com/bitwarden/clients/issues/6865

A fix for this issue is currently in review. https://github.com/bitwarden/clients/pull/8214

**Closed by Neonwarden** 2024-03-21 18:46 UTC
Labels: bug, browser
