### ISSUE TITLE
No collection available when adding to a collection.

### ISSUE THREAD

**Issue by FreshFoxyHD** [bitwarden/clients#8368] opened 2024-03-18 08:33 UTC
### Steps To Reproduce

Click on a collection of an orag, then on the plus and then on Save.
This will not work because you have to select a collection and this is not selected by default, or you cannot see it at all

### Expected Result

Default selection of the collection I want to add it to

### Actual Result

The entry that is created via the collection is not automatically added to the collection

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/70152162/193dea29-2e37-42ad-a284-e5c692a91e9e)

### Operating System

Windows

### Operating System Version

Windows 11 21H2

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.3.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SREDV-Germany** [comment] 2024-03-18 08:36
same problem

**Comment by Krychaz** [comment] 2024-03-18 08:51
Hi there!

Thank you for your report, it seems like it is a duplicate of this one #8258

This issue will now be closed.

Thanks!

**Closed by Krychaz** 2024-03-18 08:51 UTC
Labels: bug, desktop
