### ISSUE TITLE
Password with passkey could not display properly and causes crashes on chrome extension and macos app when using zh-TW as display language

### ISSUE THREAD

**Issue by jchen8tw** [bitwarden/clients#10895] opened 2024-09-05 01:42 UTC
### Steps To Reproduce

1. Change the display language to zh-TW
2. Go to any password stored with passkey
3. Click on the password

### Expected Result

The password should show properly just like how it does on IOS app.

### Actual Result

The password did not show properly. It become uneditable and occasionally causes the app to hang or crash if I click other password afterwards.

### Screenshots or Videos

<img width="418" alt="截圖 2024-08-30 上午9 47 06" src="https://github.com/user-attachments/assets/0902c8c8-a512-4b53-86e7-0fe5f155354b">

### Operating System

macOS

### Operating System Version

14.6.1（23G93）

### Installation method

Mac App Store

### Build Version

版本 2024.8.1
Shell 31.3.1
Renderer 126.0.6478.185
Node 20.15.1
Architecture arm64

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-09-05 09:06
Duplicate of https://github.com/bitwarden/clients/issues/6821

**Comment by djsmith85** [comment] 2024-09-05 09:07
Hi @jchen8tw!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/clients/issues/6821

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2024-09-05 09:07 UTC
Labels: bug, desktop
