### ISSUE TITLE
Update modal popping up when typing is really unpolished.

### ISSUE THREAD

**Issue by jamespedid** [bitwarden/clients#10963] opened 2024-09-09 17:00 UTC
### Steps To Reproduce

Try and log in when an update is available. While typing, the update modal pops up and you end up choosing an option to restart. This is annoying. Sometimes I'm in a hurry to grab a password. 

### Expected Result

Please change this behavior to just be inlined on the page. Alternatively, queue up the update for when I exit the program, don't interrupt my flow when I'm trying to lookup a password. It's very jarring.

### Actual Result

Try and log in when an update is available. While typing, the update modal pops up and you end up choosing an option to restart. 

### Operating System

Windows

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2024.8.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-09-09 17:12
Duplicate of https://github.com/bitwarden/clients/issues/2608

**Comment by djsmith85** [comment] 2024-09-09 17:13
Hi @jamespedid!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/2608

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2024-09-09 17:13 UTC
Labels: bug, desktop
