### ISSUE TITLE
Bitwarden opens, login and no more

### ISSUE THREAD

**Issue by Antonio-52** [bitwarden/clients#9098] opened 2024-05-09 14:44 UTC
### Steps To Reproduce

1. Click on 'Bitwarden' icon on 'preferred' bar
2. (Bitwarden windows opens asking for main password); username was retained)
3. Insert main password 
4. (gear icon rotates and no more)

### Expected Result

1. Click on 'Bitwarden' icon on 'preferred' bar
2. (Bitwarden windows opens asking for main password; username is retained)
3. Insert main password 
4. (gear icon rotates for 1-2 s) then display 'La mia cassaforte'

### Actual Result

2. (Bitwarden windows opens asking for main password; username is retained)
3. Insert main password 
4. (gear icon rotates and no more)

### Screenshots or Videos

![Schermata del 2024-05-09 16-28-45](https://github.com/bitwarden/clients/assets/46651541/77d91e87-9aa9-4f9f-b316-87451bf6ae1a)

### Additional Context

The main password is correct and the described behaviour occurs everytime.
Hardware acceleration setting has no effect.

### Operating System

Linux

### Operating System Version

Ubuntu 20.04.6 LTS

### Installation method

Snap

### Build Version

Versione 2024.4.3 Shell 28.3.1 Renderer 120.0.6099.291 Node 18.18.2 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Adedamola-Aina** [comment] 2024-05-09 16:34
Hi @Antonio-52 

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/8651. 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by Adedamola-Aina** 2024-05-09 16:34 UTC
Labels: bug, desktop

**Comment by Antonio-52** [comment] 2024-05-09 17:33
Hi Adedamola.
It seems to me different from issue #8651 because the problem arise just after inserting the main password, not forcing to sync.
I am not sure I really log in: I never get the main screen.
--
Antonio Angelo

Inviato da Proton Mail Android

-------- Messaggio originale --------
09/05/24 18:35, Adedamola Aina  ha scritto:
