### ISSUE TITLE
No response when I press "Ok" for the Master Password re-prompt 

### ISSUE THREAD

**Issue by kareemamr5** [bitwarden/clients#6323] opened 2023-09-18 13:37 UTC
### Steps To Reproduce

1. Open Bitwarden
2. Input your Password or PIN
3. Go to any saved credential that has "Master Password re-prompt" activated
4. Copy password, username or Edit 
5. Enter Master Password
6. Press OK
7. Result: No response at all and doesn't all me to copy or edit

### Expected Result

Copy or Edit the saved credential 

### Actual Result

No response when pressing Ok

### Operating System

Windows

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.8.4

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2023-09-18 14:05
@kareemamr5 Thank you for your report this is a known issue and a duplicate of https://github.com/bitwarden/clients/issues/6153. A fix has been issued and is included in the upcoming `2023.9` release.

**Closed by djsmith85** 2023-09-18 14:05 UTC
Labels: bug, desktop
