### ISSUE TITLE
Nothing shows when desktop client starts

### ISSUE THREAD

**Issue by fenderwhite** [bitwarden/clients#8288] opened 2024-03-11 15:06 UTC
### Steps To Reproduce

No steps required.
I even clean installed the news macOS (Sonoma 14.4) and just installed Bitwarden Desktop from Mac App Store.

### Expected Result

UI should be shown to log in.

### Actual Result

The UI shows black, so I cannot log in since I cannot find out where the buttons are.

### Screenshots or Videos

<img width="1062" alt="스크린샷 2024-03-12 오전 12 01 37" src="https://github.com/bitwarden/clients/assets/7065438/d383d6c8-93af-47ad-80f1-f241bb0a220e">

### Additional Context

I tried changing mac's theme (dark or light) but it was no use.
To add, web browser extensions work nicely.

### Operating System

macOS

### Operating System Version

Sonoma 14.4

### Installation method

Mac App Store

### Build Version

2024.2.1 (21689)

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-03-11 15:34
Duplicate of https://github.com/bitwarden/clients/issues/8003

**Comment by djsmith85** [comment] 2024-03-11 15:35
Hello @fenderwhite,

Thank you for this report. It seems like a duplicate of the https://github.com/bitwarden/clients/issues/8003 linked above.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This report will now be closed.

Kind regards,
Daniel

**Closed by djsmith85** 2024-03-11 15:35 UTC
Labels: bug, desktop
