### ISSUE TITLE
Grey screen if no internet connection

### ISSUE THREAD

**Issue by Profesor08** [bitwarden/clients#10611] opened 2024-08-19 10:04 UTC
### Steps To Reproduce

1. Disconnect from internet
2. Open extension

### Expected Result

To see interface and to be able to copy passwords.

### Actual Result

Grey screen

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/827388f2-70d5-48d7-ab3b-9b6bf9c7e878)

### Operating System

Windows

### Web Browser

Chrome

### Build Version

2024.7.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment] 2024-08-19 10:16
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/clients/issues/10439

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by Greenderella** 2024-08-19 10:16 UTC
Labels: bug, browser
