### ISSUE TITLE
Master password re-prompt fails in browser

### ISSUE THREAD

**Issue by goose-ws** [bitwarden/clients#6433] opened 2023-09-28 14:04 UTC
### Steps To Reproduce

1. Add a credit card item, without a URI that automatches to anything
2. Enable the "Master password re-prompt" radio option for the item
3. Some time later, unlock the browser extension vault (via biometrics)
4. Click on the credit card to copy the number so it can be used
5. Enter master password
6. Click "OK" or hit "[Enter]"

### Expected Result

The master password prompt will disappear and the data will be copied to clipboard

### Actual Result

The master password prompt does not go away, and the data is not copied to clipboard

### Operating System

Windows

### Operating System Version

Windows 11 Pro, Version 22H2

### Web Browser

Firefox

### Browser Version

118.0

### Build Version

2023.8.3

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2023-09-28 19:40
Duplicate of https://github.com/bitwarden/clients/issues/6153

**Comment by djsmith85** [comment] 2023-09-28 19:40
Hi @goose-ws 

This seems to have previously been reported with https://github.com/bitwarden/clients/issues/6153 and https://github.com/bitwarden/mobile/issues/2733 (mobile) and fixes have been issued which are included in 2023.9-release. The release has already been pushed out to the stores and awaiting approval from them. It should be available soon.

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2023-09-28 19:40 UTC
Labels: bug, browser
