### ISSUE TITLE
Unable to login via the Firefox plugin

### ISSUE THREAD

**Issue by BlueRaja** [bitwarden/clients#5715] opened 2023-06-30 02:50 UTC
### Steps To Reproduce

1. Attempt to login via the Firefox plugin

### Expected Result

Logging in works

### Actual Result

> An error has occurred
> i is undefined

### Screenshots or Videos

![2023-06-29 19_38_23-Greenshot](https://github.com/bitwarden/clients/assets/650323/fd67b7e8-3b30-43d5-8d69-fe302fe293c3)

### Additional Context

I am 100% certain my username/password are correct. I'm able to login successfully via the website vault.

### Operating System

Windows

### Operating System Version

Windows 11

### Web Browser

Firefox

### Browser Version

114.0.2

### Build Version

2023.5.1 ("last updated today")

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2023-06-30 07:20
Hi @BlueRaja and thank you for your report.

This seems to be a duplicate of https://github.com/bitwarden/clients/issues/4076. Please add any additional information there.

Closing this now.

**Closed by djsmith85** 2023-06-30 07:20 UTC
Labels: bug, browser
