### ISSUE TITLE
Beginning with 2024.1.1, Bitwarden now autofills and drops the cursor to the end of the Username field 

### ISSUE THREAD

**Issue by brett-berger** [bitwarden/clients#7652] opened 2024-01-23 14:25 UTC
### Steps To Reproduce

Autofill any password on Chrome (Windows) after upgrading to 2024.1.1 and after autofill, the cursor jumps to the username field. 

Previously (in 2024.1.0) it would autofill and the cursor would stay on the password field.  (desired outcome)
This allows you to add any additional characters to the password after autofill was done. 

### Expected Result

After autofill, cursor stays in the password field.

### Actual Result

After autofill, cursor jumps to the end of the username field.

### Operating System

Windows

### Operating System Version

Windows 10

### Web Browser

Chrome

### Browser Version

120.0.6099.225

### Build Version

2024.1.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by cagonzalezcs** [comment] 2024-01-24 20:39
@brett-berger 

Thank you for the bug report. I spoke with our product team regarding this behavior, and confirmed that this is the expected behavior for the feature. The reason this is expected comes as a result of focus behavior, and expected positioning of the cursor by non-sighted users. Users who deal with this concern expect their keyboard focus to return to the most recently focused input field when navigating into the inline auto-fill menu and selecting a cipher to fill. 

That said, two workarounds exist that you might consider. The first, if you plan on keeping the inline auto-fill menu enabled, would be to focus the password field with either your mouse or keyboard navigation, then trigger the fill action. This will bring focus back to that field shortly after enacting the autofill process, and at that point you can enter the rest of your password (as you're expecting to do). 

The second workaround would be to disable the inline auto-fill menu, as this will trigger the old behavior of focusing the last filled cipher element.

Because this is expected behavior, I will be closing this ticket. Please let me know if you have any questions or concerns.

**Closed by cagonzalezcs** 2024-01-24 20:39 UTC
Labels: bug, browser
