### ISSUE TITLE
Slow performance in v2023.7.0 for Edge extension

### ISSUE THREAD

**Issue by hgtok** [bitwarden/clients#5808] opened 2023-07-13 07:07 UTC
### Steps To Reproduce

1. Edge installed with 'Bitwarden' browser extension
2. Go to any website with saved credentials
3. Click on 'Bitwarden' browser extension

### Expected Result

* Typically loading is completed within 1 sec.

### Actual Result

* Extension took around 40 secs to complete loading.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/11731575/5d482c97-7d77-4987-8fb7-613c8fb76cfc)

### Additional Context

* Workaround
  * install the extension from Chrome webstore (on Edge) instead (version 2023.5.1)

### Operating System

Windows

### Operating System Version

21H2

### Web Browser

Microsoft Edge

### Browser Version

114.0.1823.41 (Official build) (64-bit)

### Build Version

2023.7.0

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Albatrauz** [comment] 2023-07-13 07:38
I'm also experiencing higher CPU load as usual and it keeps logging me out everytime. Will install the extension from the Chrome Store in the meanwhile.

**Comment by sascha-schieferdecker** [comment] 2023-07-13 07:43
I am also experiencing this on edge since today

**Comment by djsmith85** [comment] 2023-07-13 07:45
Duplicate of https://github.com/bitwarden/clients/issues/5807

**Closed by djsmith85** 2023-07-13 07:45 UTC
Labels: bug, browser
