### ISSUE TITLE
Firefox extension hides and loses search when not in focus

### ISSUE THREAD

**Issue by nebula-it** [bitwarden/clients#5526] opened 2023-05-27 20:52 UTC
### Steps To Reproduce

1. Go to 'Firefox'
2. Click on 'Bitwarden Extension Icon'
3. Scroll down 'Search for any credentials'
4. Click anywhere else or switch windows(apps)
5. As soon as you do that, FF Bitwarden extension will hide/close 
6. If you reopen the extension (same as Step 2), your last search query/state will be gone and extension would show the default page.

### Expected Result

FF Bitwarden extension window should stay open, same behavior as any chromium based browser (Edge/Chrome)

### Actual Result

FF Bitwarden extension closes/hides on losing focus

### Operating System

Windows, macOS, Linux

### Operating System Version

OS Independent issue

### Web Browser

Firefox

### Browser Version

113.0.1-1

### Build Version

2023.4.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SaabirahMohamed** [comment] 2023-05-29 11:03
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by idelsink** [comment] 2023-06-28 13:27
I have the same happening to me on Google Chrome on Linux. I also see that when I have Bitwarden open as a separate window it also interference with other Google Chrome tabs.

Some info:
```
$ google-chrome --version
Google Chrome 114.0.5735.133
```

And Bitwarden Version: 2023.5.0

**Comment by djsmith85** [comment] 2023-06-30 07:35
This is a duplicate of #1798, please see the [comment in that thread](https://github.com/bitwarden/browser/issues/1798#issuecomment-831574003) for the status of this and recommended workarounds. Thanks!

**Closed by djsmith85** 2023-06-30 07:35 UTC
Labels: bug, browser
