### ISSUE TITLE
Edge Browser: Unlock via biometric - doesn't work - nothing happens

### ISSUE THREAD

**Issue by Overblown8831** [bitwarden/clients#11195] opened 2024-09-23 08:03 UTC
### Steps To Reproduce

1. Go to 'Bitwarden Browser Extension'
2. Click on 'biometric unlocking'

### Expected Result

Unlocking

### Actual Result

is not working - nothing happens

### Additional Context

Hi, 

in our Edge browser ( 129.0.2792.52 ) the biometric unlocking no longer works for a number of users. 

The Master password is requested directly. When you click on the biometric unlock option. Nothing happens. 

Curiosly, in the Bitwarden Desktop App the biometric unlock works. 

What do we have to do to get the biometric unlock working again in the browser? 

Bitwarden Desktop App:Version 2024.8.2
Shell 31.3.1
Renderer 126.0.6478.185
Node 20.15.1
Architecture x64

Bitwarden Browser Extension: Version: 2024.9.1
Server version (self-hosted): 2024.9.1

### Operating System

Windows

### Operating System Version

Win 10 , Win 11

### Web Browser

Microsoft Edge

### Browser Version

 129.0.2792.52 

### Build Version

 2024.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment] 2024-09-23 08:07
Duplicate of #11168

**Closed** 2024-09-23 08:09 UTC
Labels: bug, browser
