### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by WaciX** [bitwarden/clients#8963] opened 2024-04-28 20:30 UTC
### Steps To Reproduce

1. Open Bitwarden desktop app
2. Type your email.
3. Type your master password or login with another device
4. Enter the 6 digit code from email and confirm

### Expected Result

Logged in

### Actual Result

Error, see screenmshot

### Screenshots or Videos

![Screenshot from 2024-04-28 22-17-22](https://github.com/bitwarden/clients/assets/2446228/e4bad27a-21e2-4627-8a94-e72e44198f5a)

### Operating System

Linux

### Operating System Version

Ubuntu 22.04.4 LTS

### Installation method

Snap

### Build Version

Version 2024.4.0 Shell 28.2.8 Renderer 120.0.6099.291 Node 18.18.2 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment] 2024-04-29 06:10
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/clients/issues/8651

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by sammbw** 2024-04-29 06:10 UTC
Labels: bug, desktop
