### ISSUE TITLE
Unable to view/copy password if "Master password re-prompt" is enabled and vault is unlocked using biometrics

### ISSUE THREAD

**Issue by Javalar** [bitwarden/clients#6359] opened 2023-09-21 02:05 UTC
### Steps To Reproduce

1. Enable login with biometrics. (for example, "Windows Hello" in Windows, or "Unlock with Biometrics" in Android).
2. Create a login with "Master password re-prompt".
3. Lock the vault.
4. Unlock the vault by using biometrics.
5. Select the previously created login and either press the button to reveal it or copy it.
6. Enter the master password when prompted.

### Expected Result

Password is displayed or copied depending on the button pressed.

### Actual Result

Windows: Nothing happens, master password prompt remains on screen.
Browser Extension: Nothing happens, master password prompt remains on screen.
Android App: App crashes.

### Screenshots or Videos

Vault unlocked with biometrics:
![Unlocked with biometrics](https://github.com/bitwarden/clients/assets/39832337/d2884fb2-0cf1-4403-8411-26363d59e0d4)

Vault unlocked with master password:
![Unlocked with master password](https://github.com/bitwarden/clients/assets/39832337/6e55ba4f-f580-41c5-b3e6-0451407b3bdc)

### Operating System

Windows

### Operating System Version

11

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.8.4

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment] 2023-09-21 02:25
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/clients/issues/6153

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by sammbw** 2023-09-21 02:25 UTC
Labels: bug, desktop
