### ISSUE TITLE
Constant Touch/Master Unlock Requests - Desktop

### ISSUE THREAD

**Issue by JWhiteUX** [bitwarden/clients#7688] opened 2024-01-25 18:46 UTC
### Steps To Reproduce

1. Open Bitwarden
2. Unlock Bitwarden using Master or TouchID
3. Timeout will result in BW locking
4. Upon locking, BW will continually request to be unlocked

### Expected Result

* Selecting Cancel dismisses the unlock request 
* Dismissing the unlock request stops future requests until BW is in focus
* On unfocus, the message no longer takes focus 

### Actual Result

* Bitwarden will continually ask to be unlocked regardless of timeout setting (currently 15min)
* Bitwarden continually reloads in the background
* Bitwarden authentication draws focus when typing, selecting, navigation, or interacting with other apps/services

### Screenshots or Videos

BW Reloading constantly
https://github.com/bitwarden/clients/assets/12961108/408cff9d-3ad5-4717-82c1-ab9ca602ce18

BW Dialog taking focus
![image](https://github.com/bitwarden/clients/assets/12961108/ad0f7171-678d-492e-87e9-97e045edfb65)

Disrupting BW Focus by selecting **Use Password** - _This effectively pauses the dialogs while it waits for input however the dialog is displayed at the system level. The dialog can be moved and will no longer steal focus_
![image](https://github.com/bitwarden/clients/assets/12961108/6aaf6253-f99c-4bac-9f24-85e62be3fc8b)

### Additional Context

**Security Concerns**
* Behavior is similar to an MFA Fatigue Attack
* Disabling lock-timeout would effectively downgrade security posture

### Operating System

macOS

### Operating System Version

14.2.1 (23C71)

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2024.1.0 (18112)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-01-25 18:50
Duplicate of https://github.com/bitwarden/clients/issues/7541

**Comment by djsmith85** [comment] 2024-01-25 18:51
Hi @JWhiteUX,

this is a duplicate of https://github.com/bitwarden/clients/issues/7541 which has received a fix with https://github.com/bitwarden/clients/pull/7350. The changes will be included in the upcoming release (2024.2)

Closing this now.

Kind regards,
Daniel

**Closed by djsmith85** 2024-01-25 18:51 UTC
Labels: bug, desktop

**Comment by JWhiteUX** [comment] 2024-02-23 18:24
Seems like this is happening again, although rather than before (constantly asking) upon `Lock` it throws the `Unlock` dialog. See screenshot

![image](https://github.com/bitwarden/clients/assets/12961108/0f04b8be-049e-42bd-aea1-b54a556576d6)

Expected Behavior:
* Bitwarden locks itself on `timeout` and doesnt ask to be unlocked until in`focus`

**Comment by nodakai** [comment] 2024-03-05 18:28
It looks like another round of fixes will be applied under https://github.com/bitwarden/clients/issues/7908
