### ISSUE TITLE
Failed to decode access token: JWT must have 3 parts

### ISSUE THREAD

**Issue by DomSperanza** [bitwarden/clients#8841] opened 2024-04-19 18:47 UTC
### Steps To Reproduce

When i was attempting to add a new password into my passwords, I received the error message "Failed to decode access token: JWT must have 3 parts

### Expected Result

Password was not saved and error message received. All my previous passwords are still available. 

### Actual Result

When trying to add in a new password, getting error message. 

### Operating System

Linux

### Operating System Version

22.04

### Installation method

Snap

### Build Version

Version 2024.4.0 Shell 28.2.8 Renderer 120.0.6099.291 Node 18.18.2 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TroyBW** [comment] 2024-04-19 20:36
Hi there!

Thank you for your report, it seems like it is a duplicate of this one: [https://github.com/bitwarden/clients/issues/8651](https://github.com/bitwarden/clients/issues/8651). 

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by TroyBW** 2024-04-19 20:36 UTC
Labels: bug, desktop
