### ISSUE TITLE
Firefox loses internet when Bitwarden extension is enabled since last update (Extension also doesn't load).

### ISSUE THREAD

**Issue by bigrjsuto** [bitwarden/clients#9309] opened 2024-05-22 14:50 UTC
### Steps To Reproduce

1. Enable Extension
2. Try to access the internet

### Expected Result

When I enable the Bitwarden extension I expect the extension to work and also have internet access.

### Actual Result

When enabled, the extension doesn't even load it's small window in the corner for login. The internet stops working across all my tabs as well. I have to disable the extension, close firefox, and open it back up to restore internet access.

### Operating System

Linux

### Operating System Version

Linux Mint 21 (Cinnamon 5.4.12, Kernel 6.5.0-35-generic) 

### Web Browser

Firefox

### Browser Version

126

### Build Version

2024.4.2

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by waredrive** [comment] 2024-05-22 14:59
Having the same issue:

- OS: Manjaro Linux x86_64 (Plasma 6.0.4, Kernel 6.9.0)
- Browser: Firefox v126
- Extension version: 2024.4.2

**Comment by StephenJBarlow** [comment] 2024-05-22 18:23
Same issue here as well:


    OS: macOS Sonoma 14.4.1
    Browser: Firefox Developer 127.0b5
    Extension version: 2024.4.2

**Comment by mgth** [comment] 2024-05-30 08:20
Same for me : 
Firefox : 127.0b8
Windows : 23H2 22631.3593
Bitwarden : 2024.4.2

**Comment by paulaime** [comment] 2024-05-31 17:34
Same issue here. When I click on the Bitwarden extension in the toolbar, it kind of breaks Firefox (can't open any other extension), and disconnects it from the Internet. I'm on Firefox 126.0.1, on Fedora 39, using the latest version of the Bitwarden extension (2024.4.2).

**Comment by shadow-identity** [comment] 2024-05-31 22:09
In my case it hangs on FF 127.0b9 (64-bit) (Developer Edition). I disabled all other extensions, but it does not help.
It does not hang on FF 126.0.1 (64-bit), and keep working.
I use the same Mozilla and BW accounts on both browsers. Both run on macOS 14.5 (23F79).

**Comment by bryanbuckley** [comment] 2024-06-02 02:48
Same for me on Win10. Seems like it would happen after the problem with logging in or blank UI for a site i.e. #9253  -> disable ext -> enable ext -> now FF loses internet

**Comment by solonovamax** [comment] 2024-06-02 20:47
from my testing it does not seem to "lose internet", but rather the extension consumes 100% of the cpu, not allowing other processes to load things, for example when navigating to a new webpage.

if I kill the "Extensions" subprocess with `kill [pid]`, then it will allow me to continue using my browser.

Similar/identical to
- #9253

Possibly similar/identical to
- #8759
- #8673
- #8651


Possibly fixed by
- #9400
- #9404

Related bugzilla report: https://bugzilla.mozilla.org/show_bug.cgi?id=1891305

Apparently, uninstalling and re-installing the extension fixes this. Have not tested this, will update when I do.

**Comment by Kaukov** [comment] 2024-06-03 07:24
I experienced this and what fixed it for me was uninstalling and reinstalling the addon.

**Comment by JoernSchimmelpfeng** [comment] 2024-06-06 15:07
Same issue with FF 126.0.1 (64-bit) on Windows 10. When I touch the Bitwarden Icon Firefox stops working and needs to be restarted. Reinstalling it also solved the issue.

**Comment by cape-optional** [comment] 2024-06-06 20:38
I am having the same issue on FF 126.0.1 (64-bit) with Windows 10 (BW FF extension version 2024.4.2).  However, it is neither fixed for me by a reinstall nor Solonovamax's magic method.

**Comment by megamit** [comment] 2024-06-08 20:17
I also had this issue. a plain reinstall of the extension didnt seem to help.
When i did it the extension settings didnt appear to get removed.
What i did to fix was:
close desktop app (not sure if important)
remove the extension
restart firefox in safe mode (hold shift after clicking short cut)
install bitwarden whilst in safe mode.
restart firefox again and bitwarden is working again.

**Comment by Bart-Westenenk** [comment] 2024-06-18 08:11
This problem also started appearing on my machine since yesterday. I have now removed the bitwarden extension and my browser works as expected again.

OS: Linux - Fedora 40
Browser: Firefox 127.0 
Device: Lenovo Thinkpad P15v (gen 1)
Extension version: latest? I have deleted it before writing this comment ..

**Comment by rktjmp** [comment] 2024-06-18 14:42
I observed the same as solonovamax, when the extension is opened, the window shows the spinner and firefoxes process manager shows the "extensions" process pegged at 100%. 

Clicking away hides the window and I am never able to bring it back up during that firefox session.

I could not revive bitwarden _at all_, no combination of disabling, enabling, removing and reinstalling or restarting firefox or computer would let it ever show the login window get passed the spinner and not brick firefox networking.

Eventually, with the "store" extension removed, I installed the `2024.6.1` build https://github.com/bitwarden/clients/releases/tag/browser-v2024.6.1 via `about:addons` &rarr; `this firefox` &rarr; `load temporary addon`, this correctly loaded and I was able to see the login screen. I did not login. I then restarted firefox and installed the regular extension, and, for now, it performs correctly. I also flipped `xpinstall.signatures.required` to `false` in `about:config` but I'm not sure if that's required for temporary plugins.

I did not check any "remember me" options in the login box this time in case that was related some how.

Perhaps installing the temporary plugin managed to clear/clobber some cached data that removing it did not, perhaps it was just cosmic rays.

Hope that helps anyone else where just reinstalling the plugin didn't work.

- Arch Linux
- Firefox 126.0

**Comment by Bart-Westenenk** [comment] 2024-06-18 14:44
I am observing the _exact_ same behaviour as rktjmp. I did not measure any CPU usage, but this describes my experience yesterday exactly.

**Comment by bigrjsuto** [comment] 2024-06-25 00:31
Yesterday I installed extension version 2024.6.2 and it's working perfectly fine again. Can others confirm the same before I close this?

**Comment by cape-optional** [comment] 2024-06-25 00:42
With the new version, it works again for me as well.

**Comment by shadow-identity** [comment] 2024-06-25 10:34
There is no clear reproduction steps. Right now it works, let's see how it behaves in the future.

**Comment by Bart-Westenenk** [comment] 2024-06-25 13:34
This new version also seems to fix it for me. I am using Fedora 40.

**Comment by JoernSchimmelpfeng** [comment] 2024-06-25 19:28
Could not reproduce the issue with the latest version. It seems to be fixed.

**Closed** 2024-06-25 20:48 UTC
Labels: bug, browser
