### ISSUE TITLE
Login on PayPal broken on MS Edge

### ISSUE THREAD

**Issue by bpsib** [bitwarden/clients#5880] opened 2023-07-24 00:00 UTC
### Steps To Reproduce

I get a captcha error when trying to use Bitwarden to login PayPal on Edge. It says "please enter the valid CAPTCHA code" yet there's no code to be seen.

1. Go to 'paypal.com'
2. Click on 'Bitwarden'
3. Click on the PayPal login thing
4. Press enter

### Expected Result

To be logged in PayPal

### Actual Result

It says "please enter the valid CAPTCHA code" yet there's no code to be seen.

### Operating System

Windows

### Web Browser

Microsoft Edge

### Browser Version

115

### Build Version

115.0.1901.183

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SaabirahMohamed** [comment] 2023-07-25 09:53
Hi @bpsib 

I attempted to reproduce your issue and was unable to do so. Help Center, trying to achieve a balance between helping them, but not encouraging them to use GitHub as a support site).

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by bpsib** [comment] 2023-07-26 22:09
Now getting the same problem in Firefox. I don't understand why you can't reproduce it.

**Comment by ddirt** [comment] 2023-07-29 09:36
This is happening to me with Paypal / Bitwarrden as well on edge. I have to lock the bitwarden vault and then I can login normally to PayPal.

**Comment by SaabirahMohamed** [comment] 2023-07-31 07:59
Hello @bpsib and @ddirt 

Thank you for raising this. 

I have re-tested this and I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

In the meantime, you manually type in your username, and this will allow you into the PayPal.

Thanks once again!

**Comment by ameeno** [comment] 2023-07-31 09:51
yup same here, also updated edge. weird

**Comment by ddirt** [comment] 2023-07-31 11:39
Seems is only an issue when using auto-fill. I can copy/paste the credentials manually into the login fields and paypal works normally.

**Comment by rwunderer** [comment] 2023-08-07 09:40
I see this issue too, in FireFox. From looking at the page with Developer Tools, it seems the following hidden field is the Problem. Bitwarden fills in the generated TOTP which gets posted as `captcha`  to the next screen.

```
<input id="splitPasswordCaptcha"name="captcha"type="text"class="hasHelp  validateEmpty   "value=""		autocomplete=	"off"			placeholder=	"Code eingeben"		aria-describedby="captchaErrorMessage"/>
```

![image](https://github.com/bitwarden/clients/assets/2046825/f6e41c27-cef3-47ae-92bb-dc0941255f31)

![image](https://github.com/bitwarden/clients/assets/2046825/fc869238-e74a-4a71-8336-9f2459270e1d)

**Comment by ErikSlevin** [comment] 2023-08-15 00:49
Same Here with Auto fill and edge

**Comment by cagonzalezcs** [comment] 2023-08-16 17:28
@bpsib 

Thank you for providing detailed information for this issue. I went ahead and tested this behavior and was able replicate it against the `v2023.7` release of the extension.

I tested this against our master branch as well and found that the problem was not reproducible. I believe that's because we have resolved the issue within PR #5700 . The issue appears due to an error that allows TOTP fields to be filled when they are not visible within the browser viewport. The changes in #5700 effectively resolve this issue, and I'm not seeing the problem within any extension that has this set of changes in place. 

That code change will be released with the `v2023.8` release of the extension to all platforms, which should be going out soon. 

If the problem persists, I'll be happy to investigate further and re-open this issue.

**Closed by cagonzalezcs** 2023-08-16 17:28 UTC
Labels: bug, browser

**Comment by dlorde** [comment] 2023-12-10 15:43
I'm now getting this PayPal captcha problem with the Brave browser, using extension Version 2023.12.0.

**Comment by mvthde** [comment] 2023-12-13 10:23
Same problem again with Firefox 120.0.1 and extension version 2023.12.0.

**Comment by bpsib** [comment] 2023-12-13 11:56
It's the failed attempt to auto-fill the TOTP code that causes this. I asked them to an option to disable attempted auto TOTP filling in case this happens again. https://github.com/bitwarden/clients/issues/5915#issuecomment-1685313188 Did they listen? Exactly. And now the problem is back. And I have never known auto TOTP filling to work anyway.

A workaround I have found is to clone the PayPal login item and delete the TOTP key from the clone. Then use the cloned version to login PayPal then copy and paste the TOTP code from the original.

**Comment by cagonzalezcs** [comment] 2023-12-13 22:40
I've reopened https://github.com/bitwarden/clients/issues/5915 to dig into why this might be happening. Will continue conversation on that issue.

**Comment by muphli** [comment] 2023-12-16 07:29
Can confirm issue with Firefox 120.0.1 and  Bitwarden Extension 2023.12.0.

**Comment by OdinGitDat** [comment] 2023-12-22 13:38
2023.12.1 same issue as well.

**Comment by garethsnaim** [comment] 2024-01-17 21:07
Wow 6 months later and here we are still a thing.

**Comment by CodingMarkus** [comment] 2024-01-18 09:47
> Wow 6 months later and here we are still a thing.

Actually not "still" but "again". The problem has been fixed before but then PayPal changed their login form a second time. The better issue for this is #5915 since this issue here says "broken on MS Edge" but actually it's broken in all browsers, that has nothing to do with MS Edge in particular.
