### ISSUE TITLE
bw cli - create attachment generates error

### ISSUE THREAD

**Issue by terribletrouble** [bitwarden/clients#4556] opened 2023-01-24 22:23 UTC
### Steps To Reproduce

Grab an existing item, set your session, execute the following:

bw create attachment --file ./hist.txt --itemid REDACTED --session ‘REDACTED’

### Expected Result

Expect the attachment to be added.

### Actual Result

This is the actual error generated:

node:fs:585
handleErrorFromBinding(ctx);
^

Error: EACCES: permission denied, open ‘/home/jason/hist.txt’
at Object.openSync (node:fs:585:3)
at Object.openSync (pkg/prelude/bootstrap.js:796:32)
at Object.readFileSync (node:fs:453:35)
at Object.readFileSync (pkg/prelude/bootstrap.js:1082:36)
at CreateCommand. (/snapshot/clients/apps/cli/build/bw.js:31997:55)
at Generator.next ()
at /snapshot/clients/apps/cli/build/bw.js:31900:71
at new Promise ()
at /snapshot/clients/apps/cli/build/bw.js:31896:12
at CreateCommand.createAttachment (/snapshot/clients/apps/cli/build/bw.js:31979:16) {
errno: -13,
syscall: ‘open’,
code: ‘EACCES’,
path: ‘/home/jason/hist.txt’
}

### Screenshots or Videos

Not needed.
Permissions on the test file are as follows:

ls -asl hist.txt 
8 -rw-rw-r-- 1 jason jason 7466 Jan 21 23:15 hist.txt

### Additional Context

Not sure where the permission denied error comes from, clearly I can access my own file, and running su/sudo looses the session, so that is N/A.

### Operating System

Linux

### Operating System Version

Linux ubuntu 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Shell

Bash

### Build Version

2023.1.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment] 2023-03-14 12:57
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by BlueTurtle121** [comment] 2023-05-29 00:15
Hi,

I am having this issue. The CLI, file, folder, and user all have the appropriate permissions. I can create items fine, just not attachments. The attachment was a PDF.

**Comment by djsmith85** [comment] 2023-12-22 14:17
Duplicate of https://github.com/bitwarden/clients/issues/3923

**Comment by djsmith85** [comment] 2023-12-22 14:18
Hi @terribletrouble,

Thank you for your report. This report seems like it is a duplicate of https://github.com/bitwarden/clients/issues/3923

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This report will now be closed.

Thank you again

**Closed by djsmith85** 2023-12-22 14:18 UTC
Labels: bug, cli
