### ISSUE TITLE
"No Folder" showing accounts in a folder

### ISSUE THREAD

**Issue by davefn26** [bitwarden/clients#2879] opened 2022-06-09 18:21 UTC
### Steps To Reproduce

1. Go to No Folder
2. Edit random item
3. Check Folder

### Expected Result

No folder to be present in the folders drop down field

### Actual Result

Folder name

### Screenshots or Videos
![No Folder Issue](https://user-images.githubusercontent.com/96265427/172917718-0feca336-f4f5-4a54-8a47-f71aeac4daa3.jpg)

### Operating System

Windows

### Operating System Version

Win11 - 21H2 - Build 22000.675

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2022.5.1

**Comment by lech** [comment] 2022-06-09 22:59
Version 2022.5.1
Shell 16.1.0
Renderer 96.0.4664.174
Node 16.9.1
Architecture x64

Seeing similar with the "No Folder" category, although it's listing everything on my end. I do also have my accounts organized by Folder/SubFolder (eg Work/Logins vs Play/Logins) which list accurately within. Not sure what's going on but it's making for a somewhat difficult task to identify what's organized vs what is not.

**Comment by KDaro** [comment] 2022-06-10 09:05
@lech , look on Issue #2821 - items with selected folder also listed in category "No Folder" so in these items you will see the folder they actually belong to

**Comment by aj-bw** [comment] 2022-06-10 15:19
Hi @davefn26 ,

Thank you for reporting this to us! Closing this as a duplicate of #2821 as @KDaro mentioned. Please watch that issue for a resolution.

**Closed by aj-bw** 2022-06-10 15:19 UTC
Labels: bug, desktop
