### ISSUE TITLE
TypeError: userSettings.serverConfig.environment is null

### ISSUE THREAD

**Issue by JP95Git** [bitwarden/clients#6562] opened 2023-10-12 12:42 UTC
### Steps To Reproduce

Having BitWarden and the Firefox plugin installed in the given version.

Go to a random website.

Open the developer tools and show the console.

You will see several occurrences of the mentioned error.

I am web developer and use the console daily for my apps. So seeing those errors in the console which is normally empty is very annoying.

The error was not shown in the past (same BitWarden server, but older plugin).

### Expected Result

No error in the developer console.

### Actual Result

The error
TypeError: userSettings.serverConfig.environment is null
notificationBar.js:97:17
appears multiple times in the developer console.

### Operating System

Windows

### Operating System Version

Windows 11 Pro 22H2

### Web Browser

Firefox

### Browser Version

118.0.2

### Build Version

2023.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment] 2023-10-12 19:07
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by JP95Git** [comment] 2023-10-12 20:35
Which information do you need?

The notificationBar.js is your code. The problem seems to be related with the update of the Firefox plugin, because I never saw such error before. I also asked our IT department to update the BitWarden server. Perhaps this will help, but they are very busy at the moment.

**Comment by levin-ems** [comment] 2023-10-13 09:03
Similar error in my browser console on macOS Sonoma 14.0

Bitwarden browser extension version 2023.9.1
selfhosted server version 2.28.1 

Firefox 118.0.1
TypeError: userSettings.serverConfig.environment is null
[notificationBar.js:97:17]

Firefox Developer Edition 119.0b6
TypeError: can't access property "vault", userSettings.serverConfig.environment is null
notificationBar.js:97:44

Google Chrome Version 117.0.5938.149
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'vault')
    at HTMLDocument.<anonymous> (notificationBar.js:97:82)
    at Generator.next (<anonymous>)
    at fulfilled (notificationBar.js:7:58)

**Comment by JP95Git** [comment] 2023-10-14 09:35
Our IT updated the BitWarden server from 2022-06-01 to the latest one. After the update BitWarden was suddenly called vaultwarden. The admin explained that we always had vaultwarden  installed, but it was called BitWarden in the past.

Unfortunately with vaultwarden 1.29.2 (version in the web was 2023-06-01) the issue still occurred. By accident I was able to resolve the issue by logout in the settings of the Firefox plugin and login again. The errors are no longer shown in the console.

**Comment by elanchan1983** [comment] 2023-11-22 04:55
> Similar error in my browser console on macOS Sonoma 14.0
> 
> Bitwarden browser extension version 2023.9.1 selfhosted server version 2.28.1
> 
> Firefox 118.0.1 TypeError: userSettings.serverConfig.environment is null [notificationBar.js:97:17]
> 
> Firefox Developer Edition 119.0b6 TypeError: can't access property "vault", userSettings.serverConfig.environment is null notificationBar.js:97:44
> 
> Google Chrome Version 117.0.5938.149 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'vault') at HTMLDocument. (notificationBar.js:97:82) at Generator.next () at fulfilled (notificationBar.js:7:58)

Have you solved this problem？ This mistake is too annoying

**Comment by levin-ems** [comment] 2023-11-23 08:02
This error finally disappeared after updating the self hosted server to the latest version.

**Comment by djsmith85** [comment] 2024-02-21 15:59
Closing this, as the issue seemed to be related to an outdated vaultwarden version.

**Closed by djsmith85** 2024-02-21 15:59 UTC
Labels: bug, browser
