### ISSUE TITLE
Bitwarden extension is very slow.

### ISSUE THREAD

**Issue by ksa-real** [bitwarden/clients#12287] opened 2024-12-08 04:21 UTC
### Steps To Reproduce

1. Start Chrome
2. Click on Bitwarden extension icon.

### Expected Result

Vault should react instantly.

### Actual Result

Around 3 seconds (up to 10 seconds) until Bitwarden reacts, usually 3 seconds.

### Screenshots or Videos

https://github.com/user-attachments/assets/9c8f0f3d-5cd7-4779-b83b-18aac338a231

### Operating System

macOS

### Web Browser

Chrome

### Build Version

Version: 2024.11.2, Server version: 2024.11.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jaredswarts55** [comment] 2024-12-09 17:16
Also having issue with it taking about 3-5 seconds to load

Chrome Version 131.0.6778.109 (Official Build) (arm64)

**Comment by amyxst** [comment] 2024-12-09 19:46
Same issue - except my extension won't even open, the icon stays 'clicked' 
Version 131.0.6778.109 (Official Build) (arm64)

**Comment by jtodddd** [comment] 2024-12-09 20:02
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by deekayw0n** [comment] 2024-12-10 06:22
Similar delay for me, with the same versions of the extension and chrome already reported.  

Symptoms: delayed 2-3 second delay opening extension UI or auto-filling. 

Also tried enabling Bitwarden extension in incognito mode with no other Chrome extensions active with no improvement in performance.

**Comment by djsmith85** [comment] 2024-12-10 12:29
Duplicate of https://github.com/bitwarden/clients/issues/12286

**Closed** 2024-12-10 12:29 UTC
Labels: bug, browser
