### ISSUE TITLE
 Unable to login on Bitwarden client on Linux (Ubuntu Desktop 22.04) 

### ISSUE THREAD

**Issue by Nije-PCH** [bitwarden/clients#9252] opened 2024-05-19 12:14 UTC
### Steps To Reproduce

4. Click on '...'

### Expected Result

After entering master password and MFA token expect the bitwarden client app to unlock the database.

### Actual Result

Follow-up toi https://github.com/bitwarden/clients/issues/9212
After reinstall, master password is accepted only to have MFA error.
Again master password and MFA work just fine on Windows client and firefox plugin.

### Screenshots or Videos

![image](https://github.com/bitwarden/clients/assets/80590663/3b1f724d-7f8f-464b-8c9a-a5b03c110030)

![image](https://github.com/bitwarden/clients/assets/80590663/888595b8-5a73-4a21-b3ab-2bdbf3ccb865)

### Additional Context

Did remove bitwarden client and reinstall.
Master Password IS correct and can be used just fine to unlock firefox extention or Bitwarden client on Windows 11 PC.
Same goes for MFA

### Operating System

Linux

### Operating System Version

Ubuntu Desktop 22.04

### Installation method

Snap

### Build Version

Version 2024.4.3 Shell 28.3.1 Renderer 120.0.6099.291 Node 18.18.2 Architecture x64

### Issue Tracking Info

- [ ] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by chaosfreak93** [comment] 2024-05-19 12:24
Hey,

Same issue here on EndeavourOS (Arch Linux)

My Bitwarden app.log:
`[2024-05-19 14:18:15.237] [info]  No state version found, assuming empty state.
[2024-05-19 14:18:15.817] [info]  State version: 58
[2024-05-19 14:18:46.633] [info]  Error: The name is not activatable
[2024-05-19 14:18:46.636] [info]  Error: The name is not activatable
[2024-05-19 14:18:46.643] [info]  Error: The name is not activatable
[2024-05-19 14:18:46.671] [info]  Error: The name is not activatable
[2024-05-19 14:18:46.672] [info]  Error: The name is not activatable
[2024-05-19 14:18:46.693] [info]  Error: The name is not activatable
[2024-05-19 14:18:46.694] [info]  Error: The name is not activatable
[2024-05-19 14:18:46.698] [info]  Error: The name is not activatable
[2024-05-19 14:18:46.701] [info]  Error: The name is not activatable
[2024-05-19 14:18:46.704] [info]  Error: The name is not activatable
[2024-05-19 14:18:46.705] [info]  Error: The name is not activatable
[2024-05-19 14:18:46.707] [info]  Error: The name is not activatable
[2024-05-19 14:18:46.707] [info]  Error: The name is not activatable
[2024-05-19 14:18:46.707] [info]  Error: The name is not activatable
[2024-05-19 14:18:46.708] [info]  Error: The name is not activatable
[2024-05-19 14:18:46.713] [info]  Error: The name is not activatable
[2024-05-19 14:18:46.714] [info]  Error: The name is not activatable
[2024-05-19 14:18:46.718] [info]  Error: The name is not activatable
[2024-05-19 14:18:46.725] [error] Error: Failed to decode access token: JWT must have 3 parts
[2024-05-19 14:18:55.825] [info]  Error: The name is not activatable
[2024-05-19 14:19:05.825] [info]  Error: The name is not activatable
[2024-05-19 14:19:15.825] [info]  Error: The name is not activatable
[2024-05-19 14:19:25.824] [info]  Error: The name is not activatable
[2024-05-19 14:19:35.824] [info]  Error: The name is not activatable
[2024-05-19 14:19:45.824] [info]  Error: The name is not activatable
[2024-05-19 14:19:55.824] [info]  Error: The name is not activatable
[2024-05-19 14:20:05.824] [info]  Error: The name is not activatable
[2024-05-19 14:20:15.823] [info]  Error: The name is not activatable
[2024-05-19 14:20:25.824] [info]  Error: The name is not activatable
[2024-05-19 14:20:35.824] [info]  Error: The name is not activatable
[2024-05-19 14:20:45.824] [info]  Error: The name is not activatable
[2024-05-19 14:20:55.824] [info]  Error: The name is not activatable
[2024-05-19 14:21:05.824] [info]  Error: The name is not activatable
[2024-05-19 14:21:15.824] [info]  Error: The name is not activatable
[2024-05-19 14:21:25.825] [info]  Error: The name is not activatable
[2024-05-19 14:21:35.825] [info]  Error: The name is not activatable
[2024-05-19 14:21:45.824] [info]  Error: The name is not activatable
[2024-05-19 14:21:55.824] [info]  Error: The name is not activatable
[2024-05-19 14:22:05.825] [info]  Error: The name is not activatable
[2024-05-19 14:22:15.824] [info]  Error: The name is not activatable
[2024-05-19 14:22:25.825] [info]  Error: The name is not activatable
[2024-05-19 14:22:35.823] [info]  Error: The name is not activatable
[2024-05-19 14:22:45.824] [info]  Error: The name is not activatable
[2024-05-19 14:22:55.824] [info]  Error: The name is not activatable
[2024-05-19 14:23:05.824] [info]  Error: The name is not activatable
[2024-05-19 14:23:15.392] [info]  Error: The name is not activatable
[2024-05-19 14:23:15.396] [info]  Error: The name is not activatable
[2024-05-19 14:23:15.824] [info]  Error: The name is not activatable
[2024-05-19 14:23:25.824] [info]  Error: The name is not activatable
[2024-05-19 14:23:35.825] [info]  Error: The name is not activatable
[2024-05-19 14:23:42.603] [info]  Error: The name is not activatable
[2024-05-19 14:23:42.606] [info]  Error: The name is not activatable
[2024-05-19 14:23:42.608] [info]  Error: The name is not activatable
[2024-05-19 14:23:42.625] [error] Error: Failed to decode access token: JWT must have 3 parts
[2024-05-19 14:23:45.824] [info]  Error: The name is not activatable
[2024-05-19 14:23:55.824] [info]  Error: The name is not activatable
[2024-05-19 14:24:05.824] [info]  Error: The name is not activatable`

**Comment by DevOpsJoel** [comment] 2024-05-19 16:23
The issue is with installing Bitwarden from snap please install the package using terminal, it 's work for me, here is the page https://bitwarden.com/es-la/download/

**Comment by SergeantConfused** [comment] 2024-05-19 17:09
Hello @Nije-PCH and everyone else,

Thank you for all your input. This report appears to be a duplicate of this [GitHub report](https://github.com/bitwarden/clients/issues/8651). If you wish, please feel free to add your input, screenshots, and/or other details into that existing thread so that they'd be reviewed by the Engineering department. At this stage, this GitHub report will be closed.

Thank you again,

**Comment by chaosfreak93** [comment] 2024-05-19 17:10
I tested it with `yay` and `pacman`. Both doesnt work. Im not using snap.

**Closed by SergeantConfused** 2024-05-19 17:09 UTC
Labels: bug, desktop

**Comment by SergeantConfused** [comment] 2024-05-21 08:26
Hi @chaosfreak93,

You can consider testing an [upcoming build](https://github.com/bitwarden/clients/issues/8651#issuecomment-2096839654) to see if it works as expected in your environment, or to use an older version, such as 2024.3.0, till this is improved in an upcoming release; Please remember to back your passwords up, if you decide to test that upcoming build.

All the best,
