### ISSUE TITLE
Autofill will not go away, is always shown despite being turned off in settings

### ISSUE THREAD

**Issue by lococola** [bitwarden/clients#11548] opened 2024-10-14 21:34 UTC
### Steps To Reproduce

1. Go to Bitwarden browser extension
2. Click on Settings => Autofill
3. Scroll down to "Show autofill menu on form fields"
4. Click on 'Off'

### Expected Result

Login fields on websites do NOT show the Bitwarden autofill popup when clicking on them.

### Actual Result

The Bitwarden autofill popup is shown when clicking on login fields on websites.

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/fa3ce479-8588-4c94-ba16-98d4fd28708c)

### Additional Context

This seems to be the opposite from what is mainly reported here, which is autofill not showing up. In my case it won't go away.

### Operating System

Windows

### Operating System Version

10 with latest updates

### Web Browser

Firefox

### Browser Version

131.0.3 (latest version)

### Build Version

2024.9.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by insunaa** [comment] 2024-10-16 08:25
This is fixed in version 2024.10.0 but the Extension is not being updated in the Firefox Store, despite the version having been released for over a week now

**Comment by cagonzalezcs** [comment] 2024-10-16 13:22
Duplicate of https://github.com/bitwarden/clients/issues/11173#issuecomment-2416138001

I'm seeing `v2024.10.0` within the Firefox add-on store now as of the posting of this message. Please upgrade to that version to resolve the issue.

**Closed by cagonzalezcs** 2024-10-16 13:22 UTC
Labels: bug, browser
