### ISSUE TITLE
String in log in dialog is messed up

### ISSUE THREAD

**Issue by biloti** [bitwarden/clients#7651] opened 2024-01-23 12:49 UTC
### Steps To Reproduce

1. Lock the vault
3. See the message below the entry for your password

### Expected Result

Should be presented something like

Logged in as <you@domain.com> on <something goes here>

### Actual Result

Logged in as <you@domain.com> on **__$2__**

### Screenshots or Videos

![Captura de tela de 2024-01-23 09-46-17](https://github.com/bitwarden/clients/assets/45002941/b326d584-13d0-4cd6-85b1-3ec42c62e5ce)

### Operating System

Linux

### Operating System Version

Debian 12.3

### Installation method

Direct Download (from bitwarden.com)

### Build Version

2023.12.0

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-01-23 12:51
Duplicate of https://github.com/bitwarden/clients/issues/7160

**Comment by djsmith85** [comment] 2024-01-23 12:52
Hi @biloti!

Thank you for your report, it seems like it is a duplicate of this one: https://github.com/bitwarden/clients/issues/7160.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Closed by djsmith85** 2024-01-23 12:52 UTC
Labels: bug, desktop
