### ISSUE TITLE
JavaScript Error occured in main process on opening app after latest in app deskop update to 2022.9.1 (Windows 7 64bit)

### ISSUE THREAD

**Issue by Ncrypt3dit** [bitwarden/clients#3737] opened 2022-10-10 17:17 UTC
### Steps To Reproduce

1. Just opening desktop app as usual from icon.
2. Have uninstalled and reinstalled 2022.9.1 from site too, same error
3. Have uninstalled (used Revo Uninstaller)  2022.9.1, restarted and tried installing 2022.8.0 and now having the same issue too.
4. Getting same issue with the portable builds of 2022.9.1 2022.8.1 & 2022.8.0
5. Everything was running fine till the update happened his morning.

[https://i.imgur.com/5eQbASk.png](url)

### Expected Result

The desktop app to give me a login screen.

### Actual Result

The following error pops up.
https://i.imgur.com/5eQbASk.png

### Screenshots or Videos

https://i.imgur.com/5eQbASk.png

### Operating System

Windows

### Operating System Version

Windows 7 Pro 64bit

### Installation method

Direct Download (from bitwarden.com), Other

### Build Version

2022.9.1

**Comment by Hinton** [comment] 2022-10-11 14:15
Closed as a duplicate of  https://github.com/bitwarden/clients/issues/3264

**Closed by Hinton** 2022-10-11 14:15 UTC
Labels: bug, desktop
