### ISSUE TITLE
Since the new update 2024.3.0 (21897) Bitwarden crashes on Catalina 10.15.7

### ISSUE THREAD

**Issue by Isaac-Balbin** [bitwarden/clients#8339] opened 2024-03-15 00:01 UTC
### Steps To Reproduce

 it crashes sporadically. I can't tell why/what causes it

### Expected Result

continue

### Actual Result

asks me to restart. I noticed also that the safari extension doesn't load. I have deleted it completely and re-installed to no avail.

### Operating System

macOS

### Operating System Version

10.15.7

### Installation method

Mac App Store

### Build Version

21897

### Issue Tracking Info

- [X] I understand that work is tracked outside of GitHub. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment] 2024-03-15 02:04
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by bowlcut187** [comment] 2024-03-15 03:12
Seeing it with the desktop AppStore install.  Same 10.15.7 os. Version 2024.4.3.0 (21897) that was updated yesterday.  Even if I dont fully login/unlock and do a cmd+q it gives a 'bitwarden quit unexpectedly'.  Same if I use menu -> quit.  Am not seeing any issue in Chrome or Firefox extensions/AddOns.  Just the desktop app throws error on close.  But opens up fine even after that 'crash'.

Have not tried deleting and reinstalling since it just works still it seems.

**Comment by Isaac-Balbin** [comment] 2024-03-15 06:49
Yes this is the behaviour I am seeing. It still works as stated butA) reinstall doesn’t help B) the safari extension doesn’t load (brings up a grey screen)Best,Isaac____________________________Isaac Balbin, B.Sc.(Hons), M.Sc., Ph.D. (Melb)On 15 Mar 2024, at 2:13 PM, Kevin ***@***.***> wrote:﻿
Seeing it with the desktop AppStore install.  Same 10.15.7 os. Version 2024.4.3.0 (21897) that was updated yesterday.  Even if I dont fully login/unlock and do a cmd+q it gives a 'bitwarden quit unexpectedly'.  Same if I use menu -> quit.  Am not seeing any issue in Chrome or Firefox extensions/AddOns.  Just the desktop app throws error on close.  But opens up fine even after that 'crash'.
Have not tried deleting and reinstalling since it just works still it seems.

**Comment by Stradivariuz** [comment] 2024-03-16 17:12
I am also seeing this behavior. Sporadically crashes on 2024.3.0 (21897) on macOS Catalina 10.15.7

**Comment by SergeantConfused** [comment] 2024-03-16 17:14
Hello everyone,

Thank you all for your input. Can you please let me know if, in addition to the 2024.3.0 desktop client closing unexpectedly, you're seeing the Safari extension as illustrated in the screenshots [here](https://github.com/bitwarden/clients/issues/8348) on macOS 10.15.7?


Thank you in advance,

**Comment by nauta** [comment] 2024-03-16 18:50
Same issue, on MacOS Catalina. 
On Safari, both the extension and surfing to vault.bitwarden.com only show loading spinner. And the Bitwarden application crashes:
```
Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [46263]

Thread 0 Crashed:: CrBrowserMain  Dispatch queue: com.apple.main-thread
0   argon2.node                   	0x0000000109c78000 0x109c78000 + 0
1   com.github.Electron.framework 	0x000000011501a3fa node::AsyncResource::CallbackScope::CallbackScope(node::AsyncResource*) + 1578
2   com.github.Electron.framework 	0x000000011500f11a node::Stop(node::Environment*, node::StopFlags::Flags) + 5722
3   com.github.Electron.framework 	0x000000011501a08d node::AsyncResource::CallbackScope::CallbackScope(node::AsyncResource*) + 701
4   com.github.Electron.framework 	0x0000000114fc5e64 node::EmitAsyncDestroy(node::Environment*, node::async_context) + 72660
5   com.github.Electron.framework 	0x0000000114ff481a node::EmitAsyncDestroy(node::Environment*, node::async_context) + 263562
6   com.github.Electron.framework 	0x0000000114fb1c1c node::FreeEnvironment(node::Environment*) + 172
7   com.github.Electron.framework 	0x000000010d8fee99 v8::CodeEvent::GetScriptName() + 272137
8   com.github.Electron.framework 	0x000000010d846f50 v8::internal::compiler::SLVerifierHintParametersOf(v8::internal::compiler::Operator const*) + 76528
9   com.github.Electron.framework 	0x00000001101706c5 node::GetArrayBufferAllocator(node::IsolateData*) + 2556581
10  com.github.Electron.framework 	0x0000000110172047 node::GetArrayBufferAllocator(node::IsolateData*) + 2563111
11  com.github.Electron.framework 	0x000000011016da3e node::GetArrayBufferAllocator(node::IsolateData*) + 2545182
12  com.github.Electron.framework 	0x000000010daedd62 v8::internal::compiler::BasicBlock::set_loop_header(v8::internal::compiler::BasicBlock*) + 16754
13  com.github.Electron.framework 	0x000000010daeeff7 v8::internal::compiler::BasicBlock::set_loop_header(v8::internal::compiler::BasicBlock*) + 21511
14  com.github.Electron.framework 	0x000000010daeede5 v8::internal::compiler::BasicBlock::set_loop_header(v8::internal::compiler::BasicBlock*) + 20981
15  com.github.Electron.framework 	0x000000010daed61a v8::internal::compiler::BasicBlock::set_loop_header(v8::internal::compiler::BasicBlock*) + 14890
16  com.github.Electron.framework 	0x000000010daed728 v8::internal::compiler::BasicBlock::set_loop_header(v8::internal::compiler::BasicBlock*) + 15160
17  com.github.Electron.framework 	0x000000010d75075b ElectronMain + 155
18  libdyld.dylib                 	0x00007fff6ccf4cc9 start + 1
```

**Comment by Isaac-Balbin** [comment] 2024-03-16 22:52
Yes that’s what I’m seeing too Best,Isaac____________________________Isaac Balbin, B.Sc.(Hons), M.Sc., Ph.D. (Melb)On 17 Mar 2024, at 4:15 AM, SergeantConfused ***@***.***> wrote:﻿
Hello everyone,
Thank you all for your input. Can you please let me know if, in addition to the 2024.3.0 desktop client closing unexpectedly, you're seeing the Safari extension as illustrated in the screenshots here on macOS 10.15.7?
Thank you in advance,

**Comment by yokoyosef** [comment] 2024-03-17 13:16
Hi, I too am also seeing this behavior. Bitwarden crashes consistently with version 2024.3.0 (21897) on macOS Catalina 10.15.7.

Rebooting made no difference, and removing the app downloaded from the App Store and reinstalling also made no difference.

It seems to crash as soon as you try and log on and enter a valid username and password. It worked fine up until this latest version.

**Comment by nicolaibach** [comment] 2024-03-17 18:02
My installation doesn't crash on Catalina if “Close to menu bar” is checked in settings and I choose “Exit” from the menu bar.  Also doesn't crash if “Close to menu bar” is unchecked and I choose “Window → Hide to menu bar” before closing the app.

**Comment by ryanjrp** [comment] 2024-03-21 02:33
I too have issues with BitWarden macOS desktop client not working properly.  I have tried re-installing the AppStore BitWarden client on my 2012 iMac running macOS 10.15.7 and I can't even see the login screen, there are a couple of black rectangles blocking much of the UI.  I can use VoiceOver to navigate the login screen, then the app crashes out.  I have downloaded the standalone DMG version of BitWarden for macOS and it shows me the login screen but crashes right after putting in the email and password information.

For my account I have my Encryption key setting as:
KDF algorithm: Argon2id
KDF memory (MB): 64
KDF iterations 10
KDF parallelism: 4

If that helps with identifying any of the problem.  I have been submitting the crash reports to Apple, and don't know if those make it back to BitWarden development team.

**Comment by anilkamath87** [comment] 2024-03-21 07:37
possibly related I am having similar issues on my android as well but can repro on saves. I created another issue though https://github.com/bitwarden/clients/issues/8419

**Comment by tartalakrem** [comment] 2024-03-21 12:02
# Bugs sur macOS

- Version du système: macOS Catalina 10.15.7
- Version de Safari: 15.6.1 (15613.3.9.1.16, 15613)
- Version de Bitwarden Desktop: 2024.3.0 (21897)

## Symptômes

1. Bitwarden Desktop (erreur systèmatique)

  - Charger Bitwarden Desktop
  - Quitter Bitwarden Desktop (sans rien saisir)
  - Message: Bitwarden a quitté de manière imprévue
  - Crashed Thread: 0 CrBrowserMain Dispatch Queue: com.apple.main-thread
  - Exception type: EXC_BAD_ACCESS (SIGSEGV)
  - Exception Codes: EXC_I386_GPFLT
  - Exception Note: EXC_CORPSE_NOTIFY
  - Termination signal: Segmentation fault: 11
  - Termination Reason: Namespace SIGNAL, code 0xb
  - Termination process: exc handler [2008]
  - 0 argon2.node ...

2. Safari (erreur systèmatique)

  - Charger Safari
  - Aller sur la page bitwarden.com
  - Cliquer sur Login
  - Busy Loop
  - Ouvrir le menu développement, afficher l'inspecteur Web
  - Syntax Error: Unexpected token '{' vendor.44f180acb796df74966f.js:2

**Comment by fdawans** [comment] 2024-03-23 11:13
Desktop works fine for me but Safari extension does not load (I tried to reinstall but no improvement).

**Comment by ma2oliveira** [comment] 2024-03-26 18:00
Similar predicament here: desktop application and other browser extensions work fine, but Safari extension does not (icon is blue, but clicking it shows a blank  (sub)window with everlasting progress swirl). 
macOS 10.15.7, Safari 15.6.1, Bitwarden 2024.3.0.

**Comment by mrcheeky123** [comment] 2024-04-01 23:19
Same issue. It's not related to the app, when I try logging in via safari I get the same:

![image](https://github.com/bitwarden/clients/assets/16994234/523e589e-990f-48f1-b671-2d6bfc4b155f)

**Comment by Boburto** [comment] 2024-04-02 15:18
I have the same issue on MacOS. Desktop app works but extension and website show the spinning wheel constantly. MacOS Ventura Version 13.1 (22C65)

**Comment by CrayCJ** [comment] 2024-04-02 16:15
Same issue: Grey rotating symbol in safari extension, Desktop app crashes _after_ I close it...

Same error report as @nauta from the desktop app.

Unable to revert to a previous version unfortunately as the desktop app updates itself upon closing. (Safari doesn't show the extension with previous versions for some reason. I have to download the App Store version for the extension to show up - which is the latest, of course.)

Mac OS: Catalina 10.15.7
Safari: Version 15.6.1 (15613.3.9.1.16, 15613)
Bitwarden: Version 2024.3.0 (21897)

**Comment by zutz** [comment] 2024-04-06 04:13
i just noticed today the automatic download of the new version 2024.3.0 failed to install and i was not able to get it to download the update from the app store.  reading the issues in this thread makes me think i might be better off not getting the update since i am using Mac OS: Catalina 10.15.7 on a rebuilt macbook pro 2012 as well.

**Comment by tartalakrem** [comment] 2024-04-06 07:05
Bitwarden Desktop Client 2024.3.0 crashed always when quitting on macOS Catalina 10.15.7
the desktop application works fine before quitting, and synchronization works fine.
ignore crash when quitting and click ok, not restart.

Bitwarden Web Application does not work with Safari 15.6.1 on macOS Catalina 10.15.7
I "solved" this problem with installing Firefox in place of Safari !

No problems on Linux/Ubuntu 22.04 LTS

**Comment by SergeantConfused** [comment] 2024-04-07 16:19
Hello everyone,

Thank you all for your input. In order to consolidate this matter, I will proceed and close this report as a duplicate of this [one](https://github.com/bitwarden/clients/issues/8454); Please note the comment [here](https://github.com/bitwarden/clients/issues/8454#issuecomment-2021523081).

With regard to the fact that the Bitwarden browser extension is not rendering as expected on older versions of Safari, this will be tracked [here](https://github.com/bitwarden/clients/issues/8348).

With regard to the fact that the Bitwarden Web App does not render as expected on older browsers, including Safari, this is already being tracked internally.

I thank you all in advance for your understanding,

**Closed by SergeantConfused** 2024-04-07 16:19 UTC
Labels: bug, browser, desktop
