### ISSUE TITLE
Vault doesn't open/Load on desktop

### ISSUE THREAD

**Issue by roland73hoedje** [bitwarden/clients#3867] opened 2022-10-21 06:38 UTC
### Steps To Reproduce

1. Open app
2. Rotating window on Windows 10 wheel spin and spin and never stop
3. Vault never opens
4. Developer tools show error on line 57 of app index.html file

### Expected Result

Vault to open and ask for vault password

### Actual Result

Wheel never stops spinning

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/97446104/197129182-fb8c177d-ef33-4e7f-a307-220bd6a5b93e.png)

### Operating System

Windows

### Operating System Version

10

### Installation method

Direct Download (from bitwarden.com)

### Build Version

Version 2022.10.1 Shell 19.0.8 Renderer 102.0.5005.148 Node 16.14.2 Architecture x64

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by bnagawiecki** [comment] 2022-11-30 13:52
Hey @roland73hoedje,

Thanks for submitting this issue. I wanted to check and see if this was still regularly occurring, as I was unable to reproduce it over on my end. If it is, have you tried a fresh install of the app?

**Comment by djsmith85** [comment] 2023-01-02 21:53
Hi @roland73hoedje, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.

**Closed by djsmith85** 2023-01-02 21:53 UTC
Labels: bug, desktop, info-needed
