### ISSUE TITLE
BitWarden extension freeze our organization website

### ISSUE THREAD

**Issue by darnasii** [bitwarden/clients#9802] opened 2024-06-24 06:29 UTC
### Steps To Reproduce

Since it's our organization website, you don't have access to it, but it's the same behaviour as Proxmox or Home Assistant problems. I provide some tech info below.

### Expected Result

Solving the problem

### Actual Result

Some pages on our website freeze for 60+ seconds when BitWarden extension in Chrome/Vivaldi/Opera/Edge (yup, many browsers on chromium) is active. Problem not occure when I disable the extension. Problem exists since 2024.6.x version, even on the newest 6.2. On version 2024.5.2 problem is not exist.

It seems to be a problem with autofill mechanism, even if I disabled all autofill options in extension.

### Screenshots or Videos

![bitwarden1](https://github.com/bitwarden/clients/assets/129312219/6e42d167-089c-4aea-becd-46637b56a39b)

### Operating System

Windows

### Operating System Version

10,11

### Web Browser

Chrome, Microsoft Edge, Opera, Vivaldi

### Browser Version

Newest

### Build Version

2024.6.2

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment] 2024-06-24 10:33
Hi Darnasil,

Since this is an internal organisational website, this makes it difficult to try reproduce.
This seems like a duplicate of #9617 

https://github.com/bitwarden/clients/issues/9617#issuecomment-2172419393 -- this comment here refers to how this user got it to work on Edge and Brave by changing the Site Access option to "On all sites".

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Closed by daniellbw** 2024-06-24 10:33 UTC
Labels: bug, browser
