### ISSUE TITLE
Browser freezes when using text areas in GitHub

### ISSUE THREAD

**Issue by KreigD** [bitwarden/clients#7822] opened 2024-02-05 22:18 UTC
### Steps To Reproduce

1. Go to github.com in Firefox
2. Create a pull request on a repository
3. Attempt to update the description of the pull request

### Expected Result

Be able to use the text area as expected (enter/remove text, change cursor position, etc.)

### Actual Result

Text entry/removal and cursor positioning is slow and sometimes freezes. Firefox shows a banner that Bitwarden is slowing down the page. Stopping Bitwarden fixes the problem.

### Operating System

macOS

### Web Browser

Firefox

### Build Version

2024.1.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-02-06 09:47
Duplicate of https://github.com/bitwarden/clients/issues/7628

**Comment by djsmith85** [comment] 2024-02-06 09:47
Hi @KreigD,

the issue is that textareas are treated as inputs for inline-autofill. It was previously reported with https://github.com/bitwarden/clients/issues/7628.

This has been addressed with https://github.com/bitwarden/clients/pull/7655 and will be included in a future release (2024.2).

Closing this now.

**Closed by djsmith85** 2024-02-06 09:47 UTC
Labels: bug, browser
