### ISSUE TITLE
`bw status` reports locked vault although BW_SESSION is correctly set

### ISSUE THREAD

**Issue by kevinschweikert** [bitwarden/clients#7487] opened 2024-01-09 14:56 UTC
### Steps To Reproduce

1. Unlock Vault with `bw unlock`
2. Set BW_SESSION environment variable
3. Get Vault status with `bw status`

```shell
$ bw unlock
? Master password: [hidden]
Your vault is now unlocked!

To unlock your vault, set your session key to the `BW_SESSION` environment variable. ex:
$ export BW_SESSION="[SESSION_ID]"
> $env:BW_SESSION="[SESSION_ID]"

You can also pass the session key to any command with the `--session` option. ex:
$ bw list items --session [SESSION_ID]

$ export BW_SESSION="[SESSION_ID]"
$ echo $BW_SESSION 
[SESSION_ID]
$ bw status
{"serverUrl":null,"lastSync":"2024-01-09T14:19:30.054Z","userEmail":"...","userId":"...","status":"locked"}
```

### Expected Result

Unlocked Status like

`{"serverUrl":null,"lastSync":"2024-01-09T14:19:30.054Z","userEmail":"...","userId":"...","status":"unlocked"}`

### Actual Result

Locked status

### Additional Context

I can't use the Ansible Bitwarden Lookup Plugin because they check the vault status with parsing the JSON response from `bw status`

### Operating System

macOS

### Operating System Version

14.2.1 (23C71)

### Shell

Zsh

### Build Version

2023.12.1

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment] 2024-01-09 15:10
Hi @kevinschweikert,

Thank you for your report. This report seems like it is a duplicate of/similar to this (https://github.com/bitwarden/clients/issues/2729).

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This report will now be closed.

Thank you again

**Closed by djsmith85** 2024-01-09 15:10 UTC
Labels: bug, cli
